apis/python/src/tiledbsc/scgroup.py
```
>>> a = ad.read_h5ad('anndata/pbmc3k_processed.h5ad')
>>> g = tiledbsc.SCGroup('bar', verbose=True)
>>> g.from_anndata(a)
```
=> Make a from_anndata factory method

apis/python/README.md, apis/python/ingestor.py, apis/python/src/tiledbsc/__init__.py, apis/python/src/tiledbsc/soma.py, apis/python/tests/test_tiledbsc.py
For #14: not urgent, but let's get this merged sooner while a smaller number of people have their eyes on it.
=> SCGroup -> SOMA

apis/python/src/tiledbsc/soma.py
Per conversation with @bkmartinjr on Slack; also related to #17.
* On an upcoming PR we'll make such params user-specifiable
* The (quick) goal for the moment is to improve the defaults
Pleasant side effect is some disk-space reduction:
Before:
```
du -hs tiledb-data/*
237M  tiledb-data/bruce-559
192K  tiledb-data/bruce-nan
640M  tiledb-data/bruce-spatial
296K  tiledb-data/pbmc-small
299M  tiledb-data/pbmc3k_processed
```
After:
```
$ du -hs tiledb-data/*
105M  tiledb-data/bruce-559
192K  tiledb-data/bruce-nan
640M  tiledb-data/bruce-spatial
296K  tiledb-data/pbmc-small
237M  tiledb-data/pbmc3k_processed
```
=> Use CZI default parameters, pending configurability

apis/python/src/tiledbsc/soma.py, apis/python/src/tiledbsc/util_ann.py, apis/python/tests/test_type_diversity.py
For https://github.com/single-cell-data/TileDB-SingleCell/issues/42
=> Use dtypes from anndata objects as much as possible

apis/python/tests/test_type_diversity.py
=> test case for issue 58

apis/python/outgestor.py, apis/python/src/tiledbsc/soma.py
The production read path will involve C++ and pyarrow. Meanwhile here is enough to help us build confidence we're doing the right thing with soma storage -- in particular, checking we can convert anndata to tiledb and back again, and get something sensible.
```
./ingestor.py anndata/pbmc3k_processed.h5ad tiledb-data/pbmc3k_processed
./outgestor.py tiledb-data/pbmc3k_processed anndata-readback/pbmc3k_processed.h5ad
./desc-ann.py anndata/pbmc3k_processed.h5ad
./desc-ann.py anndata-readback/pbmc3k_processed.h5ad
```
To do on a subsequent PR: fix `obsp`/`varp` crash. (Commented out for now.)
Example:
```
$ ingestor.py anndata/pbmc-small.h5ad
START  SOMA.from_h5ad anndata/pbmc-small.h5ad -> tiledb-data/pbmc-small
START  READING anndata/pbmc-small.h5ad
FINISH READING anndata/pbmc-small.h5ad …
```
=> to_anndata/to_h5ad skeleton

apis/python/src/tiledbsc/soma.py
Context: https://github.com/single-cell-data/TileDB-SingleCell/issues/69
=> Corner-case with raw dense X having zero items

apis/python/src/tiledbsc/soma.py, apis/python/src/tiledbsc/util.py, apis/python/src/tiledbsc/util_ann.py, apis/python/tests/test_anndata_uns.py
The class-structure organizing on #72 will result in a big PR. This is a split-out attempting to make that PR smaller.
=> Move decategoricalize to util.py

apis/python/ingestor.py, apis/python/outgestor.py, apis/python/src/tiledbsc/raw_group.py
This overrides the default directory they put files into.
Just a dev-tool mod.
=> Let ingestor.py/outgestor.py take a -o flag

apis/python/ingestor.py
=> Various what-if-exists options for ingestor.py

apis/python/setup.cfg
Fold in recent bugfixes in `tiledb-py` 0.14.5.
=> Depend on tiledb-py 0.14.5

apis/python/src/tiledbsc/annotation_matrix.py, apis/python/src/tiledbsc/util.py, apis/python/tests/test_type_diversity.py
Re-do of PR #75: see narrative there. Solves issue #74.
=> Fix issue #74: pandas.DataFrame, not numpy.ndarray, in an obsm slot

apis/python/src/tiledbsc/assay_matrix.py, apis/python/src/tiledbsc/util.py
This logic will get re-used in the soma-collection-query logic so we extract a utility function now.
This is a line-count-reducing PR to make the upcoming (and large) soma-collection-query PR smaller and easier to review.
=> Extract a utility method for tiledb X to COO X [trivial]

apis/python/src/tiledbsc/annotation_dataframe.py, apis/python/src/tiledbsc/annotation_matrix.py, apis/python/src/tiledbsc/annotation_matrix_group.py, apis/python/src/tiledbsc/annotation_pairwise_matrix.py, apis/python/src/tiledbsc/annotation_pairwise_matrix_group.py, apis/python/src/tiledbsc/assay_matrix.py, apis/python/src/tiledbsc/soma.py, apis/python/src/tiledbsc/tiledb_array.py, apis/python/src/tiledbsc/tiledb_group.py, apis/python/tests/test_soma_group_indexing.py, apis/python/tests/test_tiledbsc.py
This is a line-count-reducing PR to make the upcoming (and large) soma-collection-query PR smaller and easier to review.
It's also part of the "discoverability" aspects of the SOMA API.
=> Add a few more SOMA accessors

apis/python/src/tiledbsc/tiledb_array.py, apis/python/src/tiledbsc/tiledb_group.py, apis/python/tests/test_soma_group_indexing.py
Another convenience item for the SOMA API.
=> Implement .exists() for SOMA and SOMA elements

apis/python/src/tiledbsc/uns_group.py, apis/python/tests/test_soma_group_indexing.py
Noticed by @bkmartinjr during SOMA-API-navigation tire-kicking
=> Fix a couple uns-accessing issues

apis/python/src/tiledbsc/annotation_matrix_group.py, apis/python/src/tiledbsc/annotation_pairwise_matrix_group.py, apis/python/src/tiledbsc/assay_matrix_group.py, apis/python/src/tiledbsc/raw_group.py, apis/python/src/tiledbsc/soma.py, apis/python/src/tiledbsc/tiledb_group.py, apis/python/src/tiledbsc/uns_group.py
=> Simplify group-add operations

apis/python/src/tiledbsc/__init__.py, apis/python/src/tiledbsc/soma.py, apis/python/src/tiledbsc/soma_collection.py, apis/python/src/tiledbsc/tiledb_group.py, apis/python/tests/test_soco_ops.py, apis/python/tools/peek-soco, apis/python/tools/populate-soco
Context: #113
This adds a `SOMACollection` object, along with a simple wrapper script for command-line use.
More to come in terms of slicing operations etc as I pull more reviewable/mergeable pieces out of #80.
Also, more to come in separate PRs regarding examples/docs.
=> Initial SOMACollection class

apis/python/src/tiledbsc/annotation_dataframe.py, apis/python/src/tiledbsc/annotation_matrix.py, apis/python/src/tiledbsc/annotation_pairwise_matrix.py, apis/python/src/tiledbsc/assay_matrix.py, apis/python/tests/test_chunked_writes.py, apis/python/tests/test_dim_select.py, apis/python/tests/test_soma_group_indexing.py
Found while exploring data.
Before:
=> Ensure dataframe readbacks all have appropriate set_index

apis/python/src/tiledbsc/annotation_dataframe.py, apis/python/src/tiledbsc/annotation_matrix.py, apis/python/src/tiledbsc/annotation_matrix_group.py, apis/python/src/tiledbsc/annotation_pairwise_matrix_group.py, apis/python/src/tiledbsc/assay_matrix.py, apis/python/src/tiledbsc/tiledb_array.py, apis/python/src/tiledbsc/tiledb_group.py, apis/python/src/tiledbsc/tiledb_object.py, apis/python/src/tiledbsc/uns_array.py
Pointed out by @bkmartinjr -- many callsites were updated faithfully by @Shelnutt2 on #8 but I haven't been as diligent with all code added since then.
=> Add more .ctx arguments

apis/python/src/tiledbsc/util_tiledb.py
As discussed with @aaronwolen .
=> Simplify metadata type-naming

apis/python/mkmd.sh
Split out from #157 to make that PR smaller
=> mkmd.sh was renaming off README.md et al. and should not have

apis/python/mkmd.sh, apis/python/src/tiledbsc/assay_matrix.py
I made this method a while back but missed a spot I should have been calling it from
Split-out from #157 to make that PR smaller
=> Use existing .csr() method to neaten a callsite

.gitignore, apis/python/pyproject.toml, apis/python/setup.cfg, apis/python/setup.py, apis/python/src/tiledbsc/__init__.py
Thanks to help from @gsakkis -- this replaces #165
=> Implement Python package versioning

apis/python/src/tiledbsc/tiledb_object.py, apis/python/src/tiledbsc/util.py, apis/python/tests/test_type_diversity.py
```
$ ./tools/ingestor /Users/johnkerl/mini-corpus/anndata/Puck_200903_10.h5ad
$ peek-soma tiledb-data/Puck_200903_10
>>> soma.obs.tiledb_array_schema()
ArraySchema(
domain=Domain(*[
Dim(name='obs_id', domain=(None, None), tile=None, dtype='|S0', var=True, filters=FilterList([ZstdFilter(level=-1), ])),
]),
attrs=[
Attr(name='assay_ontology_term_id', dtype='|S0', var=True, nullable=False, filters=FilterList([ZstdFilter(level=-1), ])),
Attr(name='development_stage_ontology_term_id', dtype='|S0', var=True, nullable=False, filters=FilterList([ZstdFilter(level=-1), ])),
Attr(name='donor_BMI', dtype='|S0', var=True, nullable=False, filters=FilterList([ZstdFilter(level=-1), ])),
Attr(name='donor_uuid', dtype='|S0', var=True, nullable=False, filters=FilterList([ZstdFilter(level=-1), ])), …
```
=> Use bool attrs from tiledb-py 0.16.0

apis/python/src/tiledbsc/annotation_dataframe.py, apis/python/src/tiledbsc/annotation_matrix.py, apis/python/src/tiledbsc/annotation_matrix_group.py, apis/python/src/tiledbsc/annotation_pairwise_matrix_group.py, apis/python/src/tiledbsc/assay_matrix.py, apis/python/src/tiledbsc/assay_matrix_group.py, apis/python/src/tiledbsc/raw_group.py, apis/python/src/tiledbsc/soma.py, apis/python/src/tiledbsc/soma_collection.py, apis/python/src/tiledbsc/tiledb_array.py, apis/python/src/tiledbsc/tiledb_group.py, apis/python/src/tiledbsc/tiledb_object.py, apis/python/src/tiledbsc/uns_array.py, apis/python/src/tiledbsc/uns_group.py
Following @gsakkis advice on https://github.com/single-cell-data/TileDB-SingleCell/pull/208#discussion_r911661248
=> Use keyword-only args

apis/python/src/tiledbsc/annotation_matrix_group.py, apis/python/src/tiledbsc/annotation_pairwise_matrix_group.py, apis/python/src/tiledbsc/soma_collection.py, apis/python/tests/test_soco_ops.py, apis/python/tests/test_soma_group_indexing.py
Follow-on to #210 incorporating advice from @gsakkis
=> Correctly use __delitem__ and __delattr__

apis/python/examples/soco-slice-query.py, apis/python/examples/uniformizer.py, apis/python/setup.cfg, apis/python/src/tiledbsc/io.py, apis/python/src/tiledbsc/soma_collection.py, apis/python/src/tiledbsc/tiledb_array.py, apis/python/src/tiledbsc/tiledb_group.py, apis/python/src/tiledbsc/tiledb_object.py, apis/python/src/tiledbsc/uns_group.py, apis/python/src/tiledbsc/util.py
Enable `mypy --strict` and fix remaining typing issues.
=> Strict static typing

apis/python/src/tiledbsc/soma_collection.py, apis/python/src/tiledbsc/tiledb_group.py
Internal detail, used for sandbox testing
=> Allow relative flag as argument

libtiledbsc/include/tiledbsc/column_buffer.h, libtiledbsc/src/CMakeLists.txt, libtiledbsc/src/pyapi/pytiledbsc.cc
Merging #217 introduced C++ build issue related to pybind11. 
This PR fixes the build issue and introduces pybind11 changes coming in  #224.
=> Fix pybind11 build issue

apis/python/src/tiledbsc/io.py
=> from_h5ad_unless_exists() needs to accept ctx

apis/python/src/tiledbsc/annotation_dataframe.py
Several more callsites can benefit from this pattern
=> Some thread-pool-executor parallelizations, part 1/n

apis/python/src/tiledbsc/io.py, apis/python/src/tiledbsc/raw_group.py
Let the `X` layer name be selectable in `from_anndata` as well as`to_anndata` (which was done on #244).
=> Continuation of #244

.gitignore, libtiledbsc/include/tiledbsc/column_buffer.h, libtiledbsc/include/tiledbsc/common.h, libtiledbsc/include/tiledbsc/logger_public.h, libtiledbsc/include/tiledbsc/managed_query.h, libtiledbsc/include/tiledbsc/soma.h, libtiledbsc/include/tiledbsc/soma_collection.h, libtiledbsc/include/tiledbsc/soma_collection_query.h, libtiledbsc/include/tiledbsc/soma_query.h, libtiledbsc/include/tiledbsc/tiledbsc, libtiledbsc/include/tiledbsc/util.h, libtiledbsc/src/cli.cc, libtiledbsc/src/column_buffer.cc, libtiledbsc/src/logger.cc, libtiledbsc/src/logger.h, libtiledbsc/src/managed_query.cc, libtiledbsc/src/pyapi/libtiledbsc.cc, libtiledbsc/src/soma.cc, libtiledbsc/src/soma_collection.cc, libtiledbsc/src/soma_collection_query.cc, libtiledbsc/src/soma_query.cc, libtiledbsc/src/util.cc, libtiledbsc/test/unit_column_buffer.cc, libtiledbsc/test/unit_managed_query.cc, libtiledbsc/test/unit_soco.cc, libtiledbsc/test/unit_soma.cc
Add copyright notice to all C++ files
=> Add copyright notice to all C++ files

apis/python/setup.cfg, apis/python/src/tiledbsc/annotation_dataframe.py
Key is https://github.com/TileDB-Inc/TileDB-Py/pull/1291 which will enable us in this package to select only desired columns, in a more efficient way.
=> Depend on tiledb-py 0.17.2

.github/workflows/cpp-ci.yml, apis/python/setup.py
Disable building libtiledbsc pending changes to enable release to PyPI.
=> Disable building libtiledbsc

apis/python/src/tiledbsc/soma_collection.py, apis/python/src/tiledbsc/tiledb_group.py
=> Document/enforce direct-child relation for SOMA in collection with relative=True

libtiledbsc/README.md, scripts/README.md
=> libtiledbsc build info

apis/python/setup.cfg
https://github.com/TileDB-Inc/TileDB-Py/releases/tag/0.17.3
=> Depend on TileDB-Py 0.17.3

apis/python/src/tiledbsoma/io.py, apis/python/src/tiledbsoma/soma_sparse_nd_array.py
For the Python write path we need to support starting with a zero-sized array and letting a user extend it.
=> Support zero-sized arrays

tools/ci/build-and-check-r-package.sh, tools/ci/deploy-pkgdown.sh, tools/ci/install-linux-dependencies.sh, tools/ci/install-pkgdown-dependencies.sh, tools/ci/install-r-dependencies.sh
https://github.com/single-cell-data/TileDB-SOMA/pull/292#discussion_r973382601
=> Late update from #292

apis/python/setup.py, libtiledbsoma/README.md, libtiledbsoma/src/pyapi/query_condition.cc, scripts/bld, scripts/setup
Changes to address issues found building the C++ library on different hosts:
* Update build from source docs and `./scripts/setup` script to remove old build files.
* Fix runtime error: `ImportError: generic_type: type "PyQueryCondition" is already registered!`
* Update `./scripts/bld` script to support building on ARM.
=> Improve C++ build

apis/python/src/tiledbsoma/factory.py, apis/python/src/tiledbsoma/soma_collection.py, apis/python/src/tiledbsoma/soma_dataframe.py, apis/python/src/tiledbsoma/soma_dense_nd_array.py, apis/python/src/tiledbsoma/soma_indexed_dataframe.py, apis/python/src/tiledbsoma/soma_sparse_nd_array.py, apis/python/src/tiledbsoma/tiledb_platform_config.py, apis/python/src/tiledbsoma/util_tiledb.py
=> Optimize __repr__

scripts/bld
=> Document C++ build options

.gitignore, apis/python/.gitignore, libtiledbsoma/include/tiledbsoma/array_buffers.h, libtiledbsoma/include/tiledbsoma/soma_reader.h, libtiledbsoma/src/CMakeLists.txt, libtiledbsoma/src/cli.cc
* Update the C++ CLI example to work with the new SOMA spec.
* Add more comments to C++ classes.
=> Update C++ CLI example

apis/python/src/tiledbsoma/soma_collection.py
=> Propagate ctx through reprs and member-constructs

apis/python/src/tiledbsoma/factory.py
From https://github.com/single-cell-data/TileDB-SOMA/issues/315#issuecomment-1255271556
=> Propagate ctx through reprs and member-constructs, continued

.github/workflows/r-cmd-check.yaml
Following on from #289 #291 #292 #346
=> Unbreak R CI

apis/r/DESCRIPTION, apis/r/NEWS.md
For first `tiledbsoma` release: with R and Python both
=> Bump R version

apis/python/setup.cfg, apis/python/setup.py
It's always good to stay current, but here the more pressing concern is #359 which needs this
=> Depend on TileDB-Py 0.17.5

apis/python/tests/test_type_system.py
Improve unit test for type system round-trip.  Now uses only the public SOMA API to minimize assumptions about internal package.
=> update type system test to only use public SOMA API

apis/python/src/tiledbsoma/soma_collection.py, apis/python/src/tiledbsoma/soma_dataframe.py, apis/python/src/tiledbsoma/soma_dense_nd_array.py, apis/python/src/tiledbsoma/soma_experiment.py, apis/python/src/tiledbsoma/soma_indexed_dataframe.py, apis/python/src/tiledbsoma/soma_measurement.py, apis/python/src/tiledbsoma/soma_sparse_nd_array.py, apis/python/src/tiledbsoma/tiledb_object.py, apis/python/tests/test_soma_dense_nd_array.py, apis/python/tests/test_soma_sparse_nd_array.py
=> rename type to soma_type

apis/r/R/SOMASparseNdArray.R, apis/r/tests/testthat/test_SOMASparseNdArray.R
=> Match SparseNdArray dim/attr names to spec

apis/python/src/tiledbsoma/io.py, apis/python/src/tiledbsoma/soma_dataframe.py, apis/python/src/tiledbsoma/soma_dense_nd_array.py, apis/python/src/tiledbsoma/soma_indexed_dataframe.py, apis/python/src/tiledbsoma/soma_sparse_nd_array.py, apis/python/src/tiledbsoma/tiledb_platform_config.py
This is unsupported behavior which should not be exposed as a configuration option.
=> Disallow duplicates [main branch]

apis/python/src/tiledbsoma/annotation_dataframe.py, apis/python/src/tiledbsoma/annotation_matrix.py, apis/python/src/tiledbsoma/assay_matrix.py, apis/python/src/tiledbsoma/soma_options.py, apis/python/src/tiledbsoma/uns_array.py
This is unsupported behavior which should not be exposed as a configuration option.
=> Disallow duplicates [main-old branch]

.github/workflows/ci.yml, .github/workflows/cpp-ci.yml
=> Run Python CI on 3.8 and 3.9

apis/r/tools/get_tarball.R, libtiledbsoma/cmake/Modules/FindTileDB_EP.cmake, scripts/update-tiledb-version.py
In prep for #446 #400 #447 as discussed with @ihnorton
=> Depend on TileDB Core 2.12.0

libtiledbsoma/include/tiledbsoma/column_buffer.h, libtiledbsoma/src/cli.cc, libtiledbsoma/src/pyapi/arrow_adapter.h
Add column name to the arrow schema. The column name is optional, but needed for R.
=> [c++] Add column name to the arrow schema

apis/python/src/tiledbsoma/soma_dataframe.py, apis/python/src/tiledbsoma/soma_indexed_dataframe.py, apis/python/tests/test_soma_dataframe.py, apis/python/tests/test_soma_indexed_dataframe.py
=> Correctly handle zero-length dataframes with SOMAReader

apis/python/tests/test_soma_dataframe.py, apis/python/tests/test_soma_indexed_dataframe.py
Follow-up from
https://github.com/single-cell-data/TileDB-SOMA/pull/459#pullrequestreview-1153616376
=> More unit-test cases for #459

apis/python/setup.cfg, apis/python/setup.py, apis/python/src/tiledbsoma/query_condition.py
More updates to follow including replacing `attr_cond` with `cond`, etc. -- this is solely the version-bump bit
=> Update to TileDB-Py 0.18.0 [main]

apis/python/setup.cfg, apis/python/setup.py
More updates to follow including replacing `attr_cond` with `cond`, etc. -- this is solely the version-bump bit
=> Update to TileDB-Py 0.18.0 [main-old]

apis/python/src/tiledbsoma/annotation_dataframe.py
=> Use TileDB-Py 0.18.0 attr_cond -> cond

apis/python/src/tiledbsoma/collection.py, apis/python/src/tiledbsoma/dataframe.py, apis/python/src/tiledbsoma/indexed_dataframe.py, apis/python/src/tiledbsoma/io.py, apis/python/tools/ingestor
=> Replace Exception with SOMA-specific exceptions

.github/workflows/r-ci.yml, apis/r/tools/r-ci.sh
This PR reenables what was tried with the previous token and should hopefully be 'cooking' now.
=> [r] Enable code coverage token use

apis/python/src/tiledbsoma/indexed_dataframe.py, apis/python/tests/test_indexed_dataframe.py
Nothing too exciting here...just some small/cheesy tweaks to the unit tests to hit remaining uncovered code paths in indexed_dataframe.py
=> improving IndexedDataFrame test coverage

apis/python/src/tiledbsoma/annotation_dataframe.py, apis/python/src/tiledbsoma/annotation_matrix.py, apis/python/src/tiledbsoma/annotation_matrix_group.py, apis/python/src/tiledbsoma/annotation_pairwise_matrix_group.py, apis/python/src/tiledbsoma/assay_matrix.py, apis/python/src/tiledbsoma/assay_matrix_group.py, apis/python/src/tiledbsoma/io.py, apis/python/src/tiledbsoma/raw_group.py, apis/python/tests/test_basic_anndata_io.py, apis/python/tools/ingestor
=> Introduce schema-only-mode for parallel append-ingest

apis/python/src/tiledbsoma/dataframe.py, apis/python/tests/test_dataframe.py
Along with https://github.com/single-cell-data/SOMA/pull/49
=> [python] Remove DataFrame::is_indexed

libtiledbsoma/src/pyapi/libtiledbsoma.cc
Release Python GIL as described in #549.
=> [c++] Release Python GIL on reads

apis/python/src/tiledbsoma/dataframe.py, apis/python/tests/test_dataframe.py
Fixes #300 
Improve error checking and unit tests for categorical/dictionary types
=> [python] unit tests and error checking for #300

apis/r/R/SOMADataFrame.R, apis/r/src/rinterface.cpp, apis/r/src/riterator.cpp, apis/r/tests/testthat/test-SOMADataFrame.R
This PR updates the read method in SOMADataFrame to use the C++ layer of TileDB-SOMA.
=> Use soma_reader in SOMADataFrame

apis/python/src/tiledbsoma/__init__.py, apis/python/src/tiledbsoma/collection.py, apis/python/src/tiledbsoma/dataframe.py, apis/python/src/tiledbsoma/dense_nd_array.py, apis/python/src/tiledbsoma/factory.py, apis/python/src/tiledbsoma/io.py, apis/python/src/tiledbsoma/measurement.py, apis/python/src/tiledbsoma/sparse_nd_array.py, apis/python/src/tiledbsoma/util.py, apis/python/tests/__init__.py, apis/python/tests/test_basic_anndata_io.py, apis/python/tests/test_collection.py, apis/python/tests/test_dense_nd_array.py, apis/python/tests/test_experiment_basic.py, apis/python/tests/test_io.py, apis/python/tests/test_metadata.py, apis/python/tests/test_sparse_nd_array.py
Conforms with spec update https://github.com/single-cell-data/SOMA/pull/55
=> [python] Rename NdArray -> NDArray

apis/python/src/tiledbsoma/factory.py, apis/python/src/tiledbsoma/util.py
Revert part of #608, allowing the continued use of older datasets.
=> Support reading data that uses old NdArray name

apis/python/src/tiledbsoma/dataframe.py, apis/python/tests/test_dataframe.py
Following on #622.
Issue: #484
=> Support indexing by [] -> empty results in Python

apis/python/src/tiledbsoma/collection.py, apis/python/src/tiledbsoma/dataframe.py, apis/python/src/tiledbsoma/dense_nd_array.py, apis/python/src/tiledbsoma/experiment.py, apis/python/src/tiledbsoma/sparse_nd_array.py, apis/python/src/tiledbsoma/tiledb_object.py, apis/python/src/tiledbsoma/util.py, apis/python/src/tiledbsoma/util_arrow.py, apis/python/src/tiledbsoma/util_tiledb.py, apis/python/tests/test_type_system.py
=> [python] Add some docstrings

apis/r/NAMESPACE, apis/r/R/SOMASparseNdArray.R, apis/r/man/SOMAArrayBase.Rd, apis/r/man/SOMACollection.Rd, apis/r/man/SOMACollectionBase.Rd, apis/r/man/SOMADataFrame.Rd, apis/r/man/SOMADenseNDArray.Rd, apis/r/man/SOMASparseNDArray.Rd, apis/r/man/TileDBArray.Rd, apis/r/man/TileDBGroup.Rd
This PR corrects or enhances a few small things:
- export the sparse array class
- carries the read-as-arrow-table function over from dense array
- roxygenize to update some filenames and conventions
- corrects one more uint64 -> int64 reference in docs
=> [r] Enhancements to SparseNDArray

apis/python/src/tiledbsoma/io.py, apis/python/src/tiledbsoma/tiledb_platform_config.py
The 'if true then take new path' has been in place since October of last year. It's safe to move on now.
=> [python] Deadstrip some old code

apis/python/src/tiledbsoma/dataframe.py, apis/python/tests/test_dataframe.py
Great follow-on advice from #637 637
=> Add len(dataframe)

apis/python/setup.cfg, apis/python/setup.py
Belated feedback on https://github.com/single-cell-data/TileDB-SOMA/pull/653#discussion_r1062606074
=> [python] setup.* `typing-extensions` vs `import typing_extensions`

apis/python/src/tiledbsoma/io.py, apis/python/src/tiledbsoma/tiledb_object.py
=> [python] Remove _indent

apis/python/tests/test_basic_anndata_io.py, apis/python/tests/test_experiment_basic.py, apis/python/tests/test_platform_config.py, apis/python/tools/ingestor, apis/python/tools/outgestor, apis/r/tests/testthat/test_SOMAReader-Iterated.R, libtiledbsoma/src/cli.cc, libtiledbsoma/test/test_soma_reader.py
=> Use RNA not mRNA in examples/tests

tools/ci/install-r-dependencies.sh
Undoes the temporary #586 as tracked by #654
=> [r] TileDB-R 0.17.1 

apis/python/setup.py
Several of us found today that if we did `pip uninstall tiledbsoma`, then clean (below), then `pip install -v -e apis/python`, we got a very quick and "successful" build, but on `import tiledbsoma` we got
```
ImportError: dynamic module does not define module export function (PyInit_libtiledbsoma)
```
Bisecting commits between `0.5.0a2` (good) and `main` (bad) identified #674 as the culprit. This PR restores code that was deleted on #674.
Fix validated on laptop with:
```
rm -rf  $(find . -name '*.so' -o -name '*.dylib')
rm -rvf $(find . -name dist -o -name build)
rm -rf venv
rm -rvf test/soco
rm -rvf test/tiledbsoma
pip uninstall -y tiledbsoma
pip install -v -e apis/python
python
>>> import tiledbsoma
```
Everything makes sense here in that the `build_ext` was simply _gone_, so of course …
=> [python] Unbreak clean install

apis/python/setup.py
Neaten #689; only the `build_ext` command has to be restored.
=> Remove bdist_egg command & unused names from setup.py

apis/r/tests/testthat/test_SOMASparseNdArray.R
This small PR extends the unit test code for sparse arrays.
=> [r] Additional sparse test code

.github/workflows/python-packaging.yml
This one line would have saved me (imperfect person that I am, as are many other folks) an hour yesterday.
=> [ci/python] Include missing doc link in wheels YAML

.pre-commit-config.yaml, libtiledbsoma/test/test_query_condition.py, libtiledbsoma/test/test_simple.py, libtiledbsoma/test/test_soma_reader.py, scripts/show-versions.py
Updated version of https://github.com/single-cell-data/TileDB-SOMA/pull/453
=> Apply black/isort/flake8/mypy to all repo .py files

LICENSE
Add CZI to the license. Also update the license to 2023.
Add CZI to the license. Also update the license to 2023.
None.
=> Add CZI to the license and modify to include 2023

apis/python/tools/ingestor
=> [python] Audit for bare Exception

apis/python/src/tiledbsoma/dense_nd_array.py, apis/python/src/tiledbsoma/sparse_nd_array.py
Issues https://github.com/single-cell-data/SOMA/pull/85 and https://github.com/single-cell-data/TileDB-SOMA/issues/744
Following discussion at https://github.com/single-cell-data/SOMA/pull/85
To make this mergeable, we'll need a 0.0.0a4 of `somacore` first
=> [python] Take ndim accessor from somacore

apis/r/DESCRIPTION, apis/r/R/SOMADataFrame.R, apis/r/tests/testthat/test_SOMADataFrame.R
#741, #686 
`ids` -> `coords` for `read` methods
Nothing else ... 👋
=> [r] `ids` to `coords` as read args

.pre-commit-config.yaml, apis/python/setup.py, apis/python/src/tiledbsoma/dense_nd_array.py, apis/python/src/tiledbsoma/sparse_nd_array.py
=> [python] Remove ndims/ndim temp mod, given somacore 0.0.0a4

apis/python/src/tiledbsoma/collection.py, apis/python/src/tiledbsoma/dataframe.py, apis/python/src/tiledbsoma/factory.py, apis/python/src/tiledbsoma/io.py, apis/python/src/tiledbsoma/tiledb_array.py, apis/python/src/tiledbsoma/util_iter.py, apis/python/tools/ingestor, apis/python/tools/outgestor
#433 
Switching to typed exceptions.
Along the way I realized the outgest needs programmable `X_layer_name` -- I'm happy to split this out into a separate PR if desired.
=> [python] Replace bare `assert` with typed exceptions

apis/python/setup.py, apis/r/DESCRIPTION, apis/r/tools/get_tarball.R, libtiledbsoma/cmake/Modules/FindTileDB_EP.cmake
#752 
Only package-version dependency updates.
This PR does not implement UTF-8 mods for #415, although it does unblock work in that direction.
=> [r/python/c++] Depend on core 2.14, tiledb-r 0.18, tiledb-py 0.20

apis/python/tests/test_dataframe.py, apis/python/tests/test_type_system.py, apis/r/tests/testthat/test_SOMADataFrame.R
#707
Back in the day we had `SOMAIndexedDataFrame` and `sidf` was a nice name for a localvar. Now, it's `SOMADataFrame` (R) and `soma.DataFrame` (Python) so let's use `sdf`.
=> [r/python] Rename sidf to sdf [trivial]

apis/python/src/tiledbsoma/collection.py
=> [python] Change _CachedElement._TdbInfo.type from str to type

libtiledbsoma/test/test_query_condition.py
Adding to our unit tests, primarily motivated by code coverage gaps.
Partial solution for #778 
Add unit tests for value_filter AKA QueryCondition
None
=> enhance value filter unit tests

apis/python/src/tiledbsoma/dataframe.py, apis/python/src/tiledbsoma/dense_nd_array.py, apis/python/src/tiledbsoma/sparse_nd_array.py, apis/python/src/tiledbsoma/tiledb_array.py
A minor improvement now, which will also soon facilitate providing the correct timestamp and perhaps open tiledb::Array handle.
=> [python] refactor SOMAReader construction into TileDBArray base helper method

apis/r/R/SOMADenseNdArray.R, apis/r/R/SOMASparseNdArray.R, apis/r/man/SOMADataFrame.Rd, apis/r/man/SOMADenseNDArray.Rd, apis/r/man/SOMASparseNDArray.Rd, apis/r/tests/testthat/test_SOMADenseNdArray.R, apis/r/tests/testthat/test_SOMASparseNdArray.R
This PR adds two more readers for dense and sparse matrices off corresponding SOMA*NDArrays.  
This is still a draft which may benefit from additional discussion and refinement.
=> [r] Additional matrix readers for NDArrays

apis/python/setup.py, apis/r/DESCRIPTION
#806 
I'm looking for feedback from @Shelnutt2 @ihnorton @eddelbuettel on whether this approach is sound or not.
This is a Python-only PR -- given @eddelbuettel's notes below, it'll take some time for me to digest/incorporate this into my fledgling knowledge of R. There will be a separate R PR.
=> [python] Pin to specific TileDB core major+minor

.pre-commit-config.yaml, apis/python/setup.py
Brings in https://github.com/single-cell-data/SOMA/pull/101 from https://github.com/single-cell-data/TileDB-SOMA/issues/805
=> [python] Depend on somacore 0.0.0a8]

.gitignore, apis/r/R/SOMAArrayBase.R, apis/r/R/SOMADataFrame.R, apis/r/R/SOMADenseNdArray.R, apis/r/R/SOMASparseNdArray.R, apis/r/tests/testthat/test_SOMAReader-Iterated.R
Adding iterated readers to the key SOMA classes
This PR is aligned with specification paper draft, yet may of course be extended or revised.  Additional tests for the three supported classes have been added.
See https://app.shortcut.com/tiledb-inc/story/24880/add-iterated-readers-to-soma-classes
=> [r] Add iterated readers for SOMA classes

apis/python/src/tiledbsoma/io.py, apis/python/tests/test_basic_anndata_io.py
#643 
Based on computational-biologist feedback comparing `main-old` to `main`
=> [python] Generalize `tiledbsoma.io.add_X_layer` to `obsm`, `varp`, etc.

apis/python/src/tiledbsoma/util_tiledb.py
Context: Part of #638 and https://github.com/single-cell-data/SOMA/issues/41. Split out from largerPR #824.
Unlike typical file objects, when a TileDB object is opened in `w` mode, it is *only* a writer; it can't actually read anything at all. This introduces a class that allows you to manage both of them in one place, and more easily flush writes and ensure that they are visible.
---
It feels pretty silly that this very small change is about the best thing that I can separate out from the other [HUUUUGE](https://www.youtube.com/watch?v=pQO0v_HEGU0#t=27s) change but here we are.
This ends up being important for the immediately forthcoming big huge massive awful change that restructures creation and opening. If I’ve missed something obvious here and it’s all much simpler than I’m making …
=> [python] Create `ReadWriteHandle` to manage TileDB handles

apis/r/R/RcppExports.R, apis/r/R/SOMAArrayBase.R, apis/r/R/SOMACollection.R, apis/r/R/SOMACollectionBase.R, apis/r/R/SOMADataFrame.R, apis/r/R/SOMADenseNdArray.R, apis/r/R/SOMAExperiment.R, apis/r/R/SOMAMeasurement.R, apis/r/R/SOMASparseNdArray.R, apis/r/R/TileDBArray.R, apis/r/R/TileDBGroup.R, apis/r/R/TileDBObject.R, apis/r/R/TileDBURI.R
=> [r] Add lifecycle-maturity tags to Roxygen blocks

LICENSE
=> Update LICENSE to make the years the same.

apis/python/src/tiledbsoma/__init__.py
=> [python] Unexpose TileDBArray and TileDBObject

.github/ISSUE_TEMPLATE/bug_report.md
Issue #728 / #851 
Now that #855 is merged, let's put it to use as proposed at https://github.com/single-cell-data/TileDB-SOMA/pull/728#discussion_r1094627801
=> Use `show_package_versions` in bug-report issue template

apis/python/src/tiledbsoma/tiledb_array.py, apis/python/src/tiledbsoma/util_arrow.py
Not related to anything in particular, just something I noticed in the course of other stuff.
=> [python] Use the array we already have open to generate the Arrow schema

apis/python/src/tiledbsoma/__init__.py, apis/python/src/tiledbsoma/util_tiledb.py, apis/python/tests/test_util_tiledb.py, libtiledbsoma/src/pyapi/libtiledbsoma.cc
Issue: #514 
Bring this one step closer to the user, following the R lead at #865
=> [python] Add user-level stats hooks, to reach parity with tiledbsoma-r

apis/python/tests/test_dataframe.py
#875
Follow-on to #878 -- let's do the same validation for dataframe objects as well
=> [python] Schema validation for DataFrame

apis/python/src/tiledbsoma/common_nd_array.py, apis/python/src/tiledbsoma/dataframe.py, apis/python/src/tiledbsoma/options/tiledb_create_options.py
=> [python] `string_dim_zstd_level` -> `int64_dim_zstd_level`

apis/python/src/tiledbsoma/tiledb_object.py, apis/python/tests/test_collection.py, apis/python/tests/test_dataframe.py, apis/python/tests/test_dense_nd_array.py, apis/python/tests/test_experiment_basic.py, apis/python/tests/test_factory.py, apis/python/tests/test_sparse_nd_array.py
=> Add static `exists` method to TileDBObject.

apis/python/src/tiledbsoma/collection.py
This separates the way URIs are processed when creating a new child element from the way they are processed when adding an existing SOMA object into the collection.
When creating a new child element, we already know the new relative or absolute URI that we want to use to set it as a member, but we might need to figure out what URI to use to create the new element.
coll.add_new_thing("new_key", ...)
coll.add_new_thing("abs_key", uri="file:///abs/path")
Conversely, when adding an existing object into a collection, we know the absolute URI of the collection that we are adding, but we *don't* know the relative URI we might want to use to set the object as a member of the collection.
to_add = tiledbsoma.open("file:///path/to/something")
coll["new_key"] = to_add
In both cases, `tiledb://` URLs …
=> [python] Refactor processing of URIs for collection creation/setting

apis/python/src/tiledbsoma/util.py, apis/python/tests/test_sparse_nd_array.py
=> [python] Fix and test over-indexing semantics

apis/python/src/tiledbsoma/annotation_dataframe.py, apis/python/src/tiledbsoma/annotation_matrix.py, apis/python/src/tiledbsoma/assay_matrix.py, apis/python/src/tiledbsoma/tiledb_array.py
@Shelnutt2 I'm looking for your feedback here please
=> [python] Consolidate+vacuum (except bulk array data) on ingest

apis/r/cleanup, apis/r/man/SOMAArrayBase.Rd, apis/r/man/SOMACollection.Rd, apis/r/man/SOMACollectionBase.Rd, apis/r/man/SOMADataFrame.Rd, apis/r/man/SOMADenseNDArray.Rd, apis/r/man/SOMAExperiment.Rd, apis/r/man/SOMAMeasurement.Rd, apis/r/man/SOMASparseNDArray.Rd, apis/r/man/TileDBArray.Rd, apis/r/man/TileDBGroup.Rd, apis/r/man/TileDBObject.Rd
`man/` was out of sync
`roxygenize()` has been called, files have been updated
#906 and https://app.shortcut.com/tiledb-inc/story/25203/run-roxygenize
=> [r] Update man/ directory by running roxygenize (closes #906)

apis/python/src/tiledbsoma/options/soma_tiledb_context.py, apis/python/tests/test_platform_config.py
Fixes #904 
Added `replace` method and unit tests, allowing contexts to be updated/evolved.
=> [python] Add `replace` method to `SOMATileDBContext`

apis/r/R/SOMAArrayBase.R, apis/r/R/SOMACollection.R, apis/r/R/SOMACollectionBase.R, apis/r/R/SOMADataFrame.R, apis/r/R/SOMADenseNdArray.R, apis/r/R/SOMAExperiment.R, apis/r/R/SOMAMeasurement.R, apis/r/R/SOMASparseNdArray.R, apis/r/R/TileDBArray.R, apis/r/R/TileDBGroup.R, apis/r/R/TileDBObject.R, apis/r/R/TileDBURI.R, apis/r/man/SOMAArrayBase.Rd, apis/r/man/SOMACollection.Rd, apis/r/man/SOMACollectionBase.Rd, apis/r/man/SOMADataFrame.Rd, apis/r/man/SOMADenseNDArray.Rd, apis/r/man/SOMAExperiment.Rd, apis/r/man/SOMAMeasurement.Rd, apis/r/man/SOMASparseNDArray.Rd, apis/r/man/TileDBArray.Rd, apis/r/man/TileDBGroup.Rd, apis/r/man/TileDBObject.Rd
=> [r] Re-punctuate lifecycle tags

README.md, apis/r/README.md
#853 
As in #853
Reviewer-friendly links:
* https://github.com/single-cell-data/TileDB-SOMA/blob/kerl/readme-refresh/README.md
* https://github.com/single-cell-data/TileDB-SOMA/blob/kerl/readme-refresh/apis/python/README.md
* https://github.com/single-cell-data/TileDB-SOMA/blob/kerl/readme-refresh/apis/r/README.md
=> [docs] Harmonize `README.md` files

README.md
**Issue and/or context:** #950
=> Fix duplicate-sentence typo in `README.md`

apis/python/tests/test_collection.py
area man forgets to actually commit changes he intended to make
=> Add comments on why we expect replace tests to fail.

apis/r/R/SOMADataFrame.R, apis/r/tests/testthat/test_SOMADataFrame.R
`SOMADataFrame` should write `RecordBatch` as well as `Table` objects
**Changes:**
The `write` method was extended, and test were added.
#839
#939 
[SC 25570](https://app.shortcut.com/tiledb-inc/story/25570/somadataframe-also-write-recordbatch)
Fixes #839
=> [r] Extend SOMADataFrame to writes to RecordBatch

apis/python/src/tiledbsoma/__init__.py
=> [python] Expose `ResultOrder` in top-level namespace

apis/python/tests/test_collection.py
Formally check that we at least fixed the specific pathology in #919 although [others may yet lurk](https://github.com/chanzuckerberg/cell-census/pull/210)!
Can rebase on #981 if we go that way.
=> Add regression test for bug #919

libtiledbsoma/src/pyapi/libtiledbsoma.cc
Follow-on from https://github.com/single-cell-data/TileDB-SOMA/pull/968#discussion_r1114656039
=> [c++] Improved bounds-detection for Arrow array data

apis/python/src/tiledbsoma/_dataframe.py, apis/python/tests/test_dataframe_index_columns.py, libtiledbsoma/src/pyapi/libtiledbsoma.cc
Issue #960. Follow-on PR to #968.
=> [python] Handle timestamp index types for `DataFrame`

.pre-commit-config.yaml, apis/python/setup.py
In prep for tagging 1.0.0rc1 of this repository
=> Depend on `somacore` 1.0.0rc2

apis/python/src/tiledbsoma/options/_soma_tiledb_context.py
=> [python] Remove an extraneous print statement

apis/python/tests/test_dataframe.py, apis/python/tests/test_dataframe_index_columns.py
Follow-on to https://github.com/single-cell-data/SOMA/pull/141 for issue #960
=> [python] Raise `TypeError` on unsupported index type `bool`

libtiledbsoma/README.md
=> Update C++ sandbox-build instructions

apis/python/src/tiledbsoma/_collection.py, apis/python/src/tiledbsoma/_common_nd_array.py, apis/python/src/tiledbsoma/_dataframe.py, apis/python/src/tiledbsoma/_dense_nd_array.py, apis/python/src/tiledbsoma/_factory.py, apis/python/src/tiledbsoma/_sparse_nd_array.py, apis/python/src/tiledbsoma/_tiledb_object.py
Work related to #975 
**Changes:**
Added :raises: to docstrings.  
More remains to be done.
Focus is primarily on those exceptions the implementation will commonly raise. There are many corner cases not yet explored.
=> [python] Start adding errors to docstrings

apis/python/src/tiledbsoma/_dataframe.py, apis/python/src/tiledbsoma/_tiledb_array.py, apis/python/tests/test_dataframe_index_columns.py
**Issue and/or context:** #961 
Requires as a prerequisite: https://github.com/single-cell-data/SOMA/pull/143
=> [python] Explicit shaping for `DataFrame`

apis/python/src/tiledbsoma/_tiledb_object.py, apis/python/tests/test_dataframe.py, apis/python/tests/test_tiledbobject.py
**Issue and/or context:** #1035
=> [python] Return False on various `.exists()`

apis/python/setup.py
=> [python] Depend on attrs package >= 22.2

apis/python/devtools/ingestor, apis/python/src/tiledbsoma/io/ingest.py, apis/python/tests/test_basic_anndata_io.py, apis/python/tests/test_platform_config.py
=> [python] Ingestor must return readable result

.github/workflows/python-packaging.yml
**Issue and/or context:** #965
**Changes:** Run python-packaging.yml nightly at 09:42Z
=> [python] Run packaging workflow nightly

apis/r/README.md
**Issue and/or context:** More on issue #1032 following PR #1054
**Changes:** Results of a a test-drive on a from-scratch host
=> [r] Test-drive `apis/r/README.md` on a fresh EC2 instance

apis/python/src/tiledbsoma/io/ingest.py
A bad merge introduced some garbled docs.
**Changes:**
- Fix the garbled docs for `from_h5ad`
=> [docs] Fix documentation bug for from_h5ad

apis/r/README.md
Helpful things from helpful conversations with @eddelbuettel over the last few days
=> [r] A bit more dev advice for R

apis/python/src/tiledbsoma/__init__.py, apis/python/src/tiledbsoma/_collection.py, apis/python/src/tiledbsoma/_dataframe.py, apis/python/src/tiledbsoma/_sparse_nd_array.py, apis/python/src/tiledbsoma/_tiledb_object.py, apis/python/src/tiledbsoma/_util.py, apis/python/src/tiledbsoma/io/ingest.py, apis/python/src/tiledbsoma/options/_soma_tiledb_context.py, apis/python/tests/test_dense_nd_array.py, apis/python/tests/test_experiment_query.py, apis/python/tests/test_sparse_nd_array.py, doc/source/python-api.rst
**Issue and/or context:** #1041
**Changes:** Trivial mods for things that look OK in Python on-line help but are in fact revealed to be sub-optimal when previewed in sandbox readthedocs preview.
**Information for the reviewer:** Here's how to preview this kind of work in a sandbox environment:
https://github.com/single-cell-data/TileDB-SOMA/wiki/Doc-work-and-sandbox-previews
=> [python] Trivial doc-neatens in prep for web publishing

apis/python/notebooks/tutorial_exp_query.ipynb
For #1016 
Reviewer-friendly link:
https://github.com/single-cell-data/TileDB-SOMA/blob/kerl/query-notebook/apis/python/notebooks/tutorial_exp_query.ipynb
=> Add experiment-query example notebook

.pre-commit-config.yaml, apis/python/setup.py
For the 1.0.0 release which is happening right after this
=> [python] Depend on somacore 1.0.0

apis/r/tests/testthat/test_SOMASparseNdArray.R
The spec desires a test for `nnz()` when the schema contains duplicates
**Changes:**
A test has been added.  Given that the package does not yet cover _writing_ arrays from R we farm parts out to the TileDB R package.
#991 
[SC 26467](https://app.shortcut.com/tiledb-inc/story/26467/ass-test-for-support-of-nnz-under-duplicates-true)
=> [r] Add test for nnz() when duplicates==TRUE

.github/workflows/ci.yml, apis/python/setup.cfg
**Issue and/or context:** Backport #1115 to `main-old`
=> [python] Pin typeguard to < 3.0 [main-old]

apis/python/src/tiledbsoma/io/ingest.py
**Issue and/or context:** #1088. See also https://github.com/single-cell-data/SOMA/pull/153.
=> [python] Add more lifecycle-experimental indicators to docstrings [WIP]

.github/workflows/r-python-interop-testing.yml, apis/system/tests/test_densendarray_write_r_read_python.py
Fix one test that was accidentally broken.
=> [r] [python] fix TestDenseNDArrayWriteRReadPython

doc/source/conf.py
Minor neatens. Found while working on #1089.
=> [docs/python] Neaten Sphinx config

.github/workflows/r-python-interop-testing.yml, apis/system/tests/test_dataframe_write_python_read_r.py, apis/system/tests/test_densendarray_write_r_read_python.py, apis/system/tests/test_sparsendarray_write_python_read_r.py, apis/system/tests/test_sparsendarray_write_r_read_python.py
https://github.com/single-cell-data/TileDB-SOMA/issues/435
**Changes:**
- Add a pair of tests for SparseNDArray
=> [r][python] SparseNDArray R-Python roundtrip testing 

apis/python/setup.py, apis/python/src/tiledbsoma/_general_utilities.py
=> [python] Include OS info in `show_package_versions`

apis/r/man/ConfigList.Rd, apis/r/man/PlatformConfig.Rd, apis/r/man/SOMAArrayBase.Rd, apis/r/man/SOMACollection.Rd, apis/r/man/SOMACollectionBase.Rd, apis/r/man/SOMAContextBase.Rd, apis/r/man/SOMADataFrame.Rd, apis/r/man/SOMADenseNDArray.Rd, apis/r/man/SOMAExperiment.Rd, apis/r/man/SOMAMeasurement.Rd, apis/r/man/SOMASparseNDArray.Rd, apis/r/man/SOMATileDBContext.Rd, apis/r/man/ScalarMap.Rd, apis/r/man/TileDBArray.Rd, apis/r/man/TileDBGroup.Rd
=> [r] Rerun roxygenise

README.md
Change README to reflect new CZ CELLxGENE Census slack channel name
=> CZI slack channel name change

.github/workflows/python-packaging.yml
=> [python] Include PyPI wheel-publish in release CI

apis/python/src/tiledbsoma/_dataframe.py, apis/python/src/tiledbsoma/_dense_nd_array.py, apis/python/src/tiledbsoma/_sparse_nd_array.py, apis/python/src/tiledbsoma/io/ingest.py, apis/python/src/tiledbsoma/options/_soma_tiledb_context.py
Iterative work on https://github.com/single-cell-data/TileDB-SOMA/issues/1089
=> [docs/python] More doc links/styling

apis/python/tests/test_platform_config.py
=> Add tests for `*_dim_zstd_level` create options.

apis/r/README.md
=> [r] Add `pbmc3k.tiledb` info to `apis/r/README.md`

apis/r/tests/testthat/test-TileDBCreateOptions.R
Introduced by yours truly on #1216
=> [r] Fix (venial) typo in R unit test

apis/python/src/tiledbsoma/io/ingest.py, apis/python/tests/test_basic_anndata_io.py
**Issue and/or context:** #1245
**Changes:**
=> [python] Store `obsm` and `varm` sparsely

apis/python/setup.py
As discussed at https://github.com/TileDB-Inc/tiledbsoma-feedstock/pull/13.
Context: https://github.com/single-cell-data/TileDB-SOMA/issues/1242
=> [python] Flexible `--libtiledbsoma` specification in `setup.py`

apis/python/src/tiledbsoma/io/ingest.py, apis/python/tests/test_io.py
**Issue and/or context:** User feedback
**Changes:**
=> [python] Handle ingest of completely empty sparse arrays

.pre-commit-config.yaml, apis/python/setup.py, apis/python/src/tiledbsoma/_measurement.py, apis/python/src/tiledbsoma/io/ingest.py
**Issue and/or context:** #1203
=> [python] Depend on somacore 1.0.2

apis/python/src/tiledbsoma/_collection.py, apis/python/src/tiledbsoma/_common_nd_array.py, apis/python/src/tiledbsoma/_dataframe.py, apis/python/src/tiledbsoma/_factory.py, apis/python/src/tiledbsoma/_tiledb_object.py, apis/python/src/tiledbsoma/io/ingest.py, apis/python/src/tiledbsoma/options/_soma_tiledb_context.py
**Issue and/or context:** #1294 is too easy a mistake to make.
=> [python] Add a run-time type check on contexts provided to `tiledbsoma.io`

apis/r/.Rbuildignore, apis/r/NEWS.md, apis/r/tools/r-ci.sh, apis/r/vignettes/soma-experiment-queries.Rmd, apis/r/vignettes/soma-objects.Rmd, apis/r/vignettes/soma-reading.Rmd
**Issue and/or context:** #1180
**Changes:** Adds the following vignettes to the R package:
- SOMA objects overview
- Reading from SOMA objects
- Querying SOMA experiments
**Notes for Reviewer:** Thanks to @johnkerl for the copyediting.
=> [r] Port notebooks to R vignettes

apis/r/R/ephemeral.R, apis/r/R/write_seurat.R, apis/r/tests/testthat/test-EphemeralCollection.R, apis/r/tests/testthat/test-EphemeralExperiment.R, apis/r/tests/testthat/test-EphemeralMeasurement.R, apis/r/tests/testthat/test-SeuratIngest.R, apis/r/tests/testthat/test-SeuratOutgest.R
This is a line-count-reducing PR which will help simplify PR #1325 for issue #1346.
It is absolutely trivial, consisting solely of added linebreaks.
=> [r] Add some whitespace for improved readability

libtiledbsoma/src/CMakeLists.txt, libtiledbsoma/src/soma/soma_array.h, libtiledbsoma/src/soma/soma_group.cc, libtiledbsoma/src/soma/soma_group.h, libtiledbsoma/src/tiledbsoma/tiledbsoma, libtiledbsoma/src/utils/common.h, libtiledbsoma/test/CMakeLists.txt, libtiledbsoma/test/unit_soma_group.cc
https://github.com/single-cell-data/TileDB-SOMA/issues/1247
https://github.com/single-cell-data/TileDB-SOMA/issues/1248
https://github.com/single-cell-data/TileDB-SOMA/issues/1122
**Changes:**
Addition of internal `SOMAGroup` class that will be used to build `SOMACollection`, `SOMAExperiment`, and `SOMAMeasurement`.
=> [c++] Addition of `SOMAGroup`

libtiledbsoma/src/soma/soma_array.h, libtiledbsoma/src/soma/soma_group.h, libtiledbsoma/test/unit_soma_array.cc, libtiledbsoma/test/unit_soma_group.cc
Follow up PR to review comments by @beroy in #1339.
**Changes:**
* Make variables names more clear in unit tests
* Add example usage for `MetadataValue` and `MetadataInfo`
* Make verbs consistent in documentation
=> [c++] Make `SOMA{Array,Group}` Changes According To Review in #1339

apis/r/src/Makevars.in
Addresses #1366, which is a point-in-time update within the broader narrative of #1365.
=> [r] Update MacOS build for developer-with-local-core corner case

README.md
**Issue and/or context:** For #1362
=> [docs] Fix signup link for TileDB Community Slack

apis/python/src/tiledbsoma/io/ingest.py
Symptom to fix: `obsm` elements have many writes of too-small sizes, most visible with `tiledbsoma.logging.debug()` set.
@gspowley is updating chunking logic. That work is still in progress. Meanwhile, there is a straightforward bug in `obsm` chunking, with a clear fix in the interim.
**Changes:**
Notes in code comments on this PR.
=> [python] Update obsm-chunking logic

apis/r/R/TileDBGroup.R
Remnants from #1325
**Changes:**
=> [r] Remove two debug statements

apis/python/src/tiledbsoma/io/ingest.py
=> [python] Improve resume-mode experience

apis/r/vignettes/soma-objects.Rmd
Addresses
https://github.com/single-cell-data/TileDB-SOMA/pull/1417/files/7248f6b1924a5a0aa478985a55f21db3e9a27930#r1205705303
=> [r] Vignette follow-up from #1417

apis/r/README.md
Fixes #1333
The README in `apis/r` had drifted slightly from current installation steps.
**Changes:**
Small edits to the README.
https://github.com/single-cell-data/TileDB-SOMA/issues/1333
[SC 29381](https://app.shortcut.com/tiledb-inc/story/29381/update-readme-md-for-apis-r)
=> [r/docs] Update README.md to current build setup

.pre-commit-config.yaml, apis/python/setup.py, apis/python/src/tiledbsoma/__init__.py, apis/python/src/tiledbsoma/_collection.py, apis/python/src/tiledbsoma/_common_nd_array.py, apis/python/src/tiledbsoma/_dataframe.py, apis/python/src/tiledbsoma/_exception.py, apis/python/src/tiledbsoma/_general_utilities.py, apis/python/src/tiledbsoma/_util.py, apis/python/src/tiledbsoma/io/ingest.py, apis/python/src/tiledbsoma/options/__init__.py, apis/python/src/tiledbsoma/options/_tiledb_create_options.py, apis/python/tests/test_io.py, apis/python/tests/test_platform_config.py
Brings in frrom `main`:
* #1405
* #1408
* #1430
* #1431
=> [python] 1.2.5 backports

libtiledbsoma/test/unit_soma_array.cc
As per @johnkerl's [comment](https://github.com/single-cell-data/TileDB-SOMA/pull/1439#pullrequestreview-1462981924)  in https://github.com/single-cell-data/TileDB-SOMA/pull/1439, the unit test for `SOMAArray::read_next` should be its own PR.
**Changes:**
N/A
N/A
=> [c++] Add Unit Test for `SOMAArray::read_next`

apis/python/src/tiledbsoma/_common_nd_array.py, apis/r/R/TileDBArray.R, apis/r/man/TileDBArray.Rd
**Issue and/or context:** #1445.
**Changes:** Clarifies that we use shape in the capacity sense of the word.
=> [r/python] Clarify online docs re shape-as-capacity

apis/r/man/sr_setup.Rd
**Issue and/or context:** Failed to add the updated docs for sr_setup() in #1461.
=> [r] Fix example error in sr_setup docs

README.md
**Issue and/or context:** Issue #1387 
**Changes:**
* The base `README.md` on this PR
* Wiki content https://github.com/single-cell-data/TileDB-SOMA/wiki/Python-quick-start/_compare/695f3a5d122c7e8e270e62816c373a21131cfd7b...0915f15842bacc5a3d74e71cf2699d93af6d72db
* Wiki content https://github.com/single-cell-data/TileDB-SOMA/wiki/R-quick-start/_compare/7798aada359edb2bc5cc5ddfa3fc0e44c49457ee...bf1e6783984b88d486260bf4ee4bc116026e573e
=> [docs] Update install/quick-start notes

apis/python/src/tiledbsoma/io/ingest.py
**Issue and/or context:** Resolves #1466
**Changes:** Don't ingest uningestibles
**Notes for Reviewer:** @aaronwolen @mojaveazure looking for compbio feedback on this approach
=> [python] Skip ingest of zero-cell uns arrays

apis/python/src/tiledbsoma/io/ingest.py
**Issue and/or context:** Currently, the user-level `ingest_mode` string in `tiledbsoma.io` is re-used for internal decision-making, via things like `if ingest_mode == "resume": ...`. This is already a little confusing, but it will be worse with append-mode (#1278).
**Changes:** On this PR we simplify by separating the single, easily keyable user-level mode string from a set of orthogonal, directly iffable boolean flags.
=> [python] Simplify internal ingestion API via `IngestionParams`

apis/python/src/tiledbsoma/io/ingest.py, apis/python/tests/test_basic_anndata_io.py
Backport #1459 from `main` to `release-1.2` in prep for 1.2.6
=> [python] Backport #1459 from `main` to `release-1.2` branch

.github/workflows/python-ci-full.yml, .github/workflows/python-ci-minimal.yml
=> [ci/python] Run full CI on merges to `release-i.j` branches

apis/python/src/tiledbsoma/_query_condition.py
Same as #1491 but merging to `release-1.2` branch rather than `main`.
=> [python] Trivial commit to test #1490 (2 of 2)

.github/workflows/python-ci-full.yml, .github/workflows/python-ci-minimal.yml
Backports #1490 to the release-1.2 branch.
=> [ci/python] Run full CI on merges to `release-i.j` branches (#1490)

apis/python/src/tiledbsoma/io/ingest.py
Minor opportunity found on PR #1498 for issue #1278
=> [python] Minor function-extract in ingestion logic

apis/python/src/tiledbsoma/io/ingest.py
**Issue and/or context:** Clears the ground a little underneath a to-be-written PR for #1404
=> [python] Trivial extract-method in uns ingestor

.github/workflows/backport.yml
**Issue and/or context:** #1335
**Changes:**
Not sure what else is needed to complete this -- things I've found:
* https://github.com/TileDB-Inc/TileDB/pull/1669/files
* https://github.com/tibdex/backport/blob/main/README.md
* https://github.com/marketplace/actions/backporting
=> [ci] Initial experiments with backport-bot

apis/r/R/TileDBGroup.R, apis/r/tests/testthat/test-membership-caching.R
**Issue and/or context:** Presented in detail here
https://github.com/single-cell-data/TileDB-SOMA/issues/1477#issuecomment-1627373304
**Changes:** Presented in detail here
https://github.com/single-cell-data/TileDB-SOMA/issues/1477#issuecomment-1627373304
=> [r] Fix bug found on nested close

apis/r/src/rutilities.cpp, apis/r/tests/testthat/test-SOMAArrayReader-Iterated.R
In issue #1494 it has been highlighted that out-of-domain 'dim points' (and 'dim ranges') are not checked in the iterated reader and that an error should be triggered for unsuitable values.
**Changes:**
This PR adds checks that requested dimensions points (and ranges) conform to the domain of the respective dimension.
#1494
=> [r] Check dimension domain when setting dim points and ranges

apis/r/DESCRIPTION, apis/r/NEWS.md, apis/r/R/SOMAExperiment.R, apis/r/man/SOMADenseNDArray.Rd, apis/r/man/SOMAExperiment.Rd, apis/r/man/SOMASparseNDArray.Rd, apis/r/tests/testthat/test-SOMAExperiment-query.R
**Issue and/or context:** #1538
**Changes:** Adds `axis_query()`to `SOMAExperiment`.
=> [r] Add `axis_query()` method to `SOMAExperiment`

.github/workflows/r-ci.yml, .github/workflows/r-python-interop-testing.yml
**Issue and/or context:** Found on #1542 where CI checks did not run as expected
=> [r] Run R/interop CI on release branches as well as main

libtiledbsoma/src/CMakeLists.txt, libtiledbsoma/src/soma/soma_dataframe.cc, libtiledbsoma/src/soma/soma_dense_ndarray.cc, libtiledbsoma/src/soma/soma_dense_ndarray.h, libtiledbsoma/src/soma/soma_sparse_ndarray.cc, libtiledbsoma/src/soma/soma_sparse_ndarray.h, libtiledbsoma/src/tiledbsoma/tiledbsoma, libtiledbsoma/test/CMakeLists.txt, libtiledbsoma/test/unit_soma_dataframe.cc, libtiledbsoma/test/unit_soma_dense_ndarray.cc, libtiledbsoma/test/unit_soma_sparse_ndarray.cc
https://github.com/single-cell-data/TileDB-SOMA/issues/1258
**Changes:**
* Addition of `SOMADenseNDArray` and `SOMASparseNDArray` which inherit from `SOMAArray`
N/A
=> [c++] Addition of `SOMA{Dense,Sparse}NDArray`

apis/r/configure
* Issue #1567 
* Attempting to fix https://github.com/r-universe/tiledb-inc/actions/runs/5741370604
**Changes:** As suggested by @eddelbuettel 
=> [r] Experiments for r-universe dependencies on Mac

apis/r/DESCRIPTION, apis/r/NEWS.md, apis/r/README.md
**Issue and/or context:** #1567 
**Changes:**  Bumps the version to 1.4.0 in preparation for release.
**Notes for Reviewer:** Also deemphasizes `main-old` in the README to keep the focus here.
=> [r] Release 1.4.0

apis/python/src/tiledbsoma/io/ingest.py, apis/python/tests/test_update_dataframes.py
Issue #1562
**Changes:**
* For this v1, add/drop but no type-mutation for existing columns
* A v2 with type-mutation for existing columns will be follow-on work
=> [python] `update_obs`/`update_var`

apis/python/src/tiledbsoma/io/ingest.py
**Issue and/or context:** #1592
**Changes:**
=> [backport release-1.4] [python] Make `tiledbsoma.io._create_or_open_coll` compatible with 1.2.7

apis/python/src/tiledbsoma/io/ingest.py, apis/python/tests/test_registration_mappings.py
**Issue and/or context:** #1592 was inadvertently including the WIP #1587. This PR leaves only the #1592 essentials.
=> [python] Decouple 1587 and 1592

apis/r/DESCRIPTION
#1596 for `release-1.4` branch
=> [r] Backport #1596 to release-1.4 branch

apis/r/DESCRIPTION
Following our procedure at
https://github.com/single-cell-data/TileDB-SOMA/wiki/Branches-and-releases
Context: #1619
=> [r] Bump DESCRIPTION in prep for 1.4.3 release

apis/python/devtools/outgestor
**Issue and/or context:** Found while testing #1650.
**Changes:**
**Notes for Reviewer:** Unit tests are not affected as this is an internal-only dev tool.
=> [python] Typo fix in `devtools/outgestor`

.github/workflows/python-ci-minimal.yml, apis/r/R/TileDBArray.R, apis/r/man/SOMAAxisIndexer.Rd, apis/r/man/SOMAAxisQueryResult.Rd, apis/r/man/SOMADataFrame.Rd, apis/r/man/SOMADenseNDArray.Rd, apis/r/man/SOMAExperiment.Rd, apis/r/man/SOMAExperimentAxisQuery.Rd, apis/r/man/TileDBArray.Rd, apis/r/src/Makevars.in, apis/r/src/riterator.cpp, apis/r/tests/testthat.R, apis/r/tests/testthat/helper-test-tiledb-objects.R, apis/r/tests/testthat/test-SCEOutgest.R, apis/r/tests/testthat/test-SOMAArrayReader-Iterated.R, apis/r/tests/testthat/test-SeuratOutgest-object.R, apis/r/tests/testthat/test-SeuratOutgest-reduction.R, apis/r/tests/testthat/test-SingleCellExperimentIngest.R, apis/r/tools/r-ci.sh
`R CMD check` nagged again (see SC link).  In one case a missing colon (added), in other cases either/or/may both a re-run of `roxygenize()` along with the fact that my machine has the updated `arrow` package released yesterday.
**Changes:**
One R file corrected in source documentation, several Rd files updated mechanically.
[SC-33619](https://app.shortcut.com/tiledb-inc/story/33619/r-rd-documentation-regression)
=> [r] Update Rd/ directory to quieten checks

apis/python/src/tiledbsoma/io/__init__.py, apis/python/tests/test_update_dataframes.py
**Issue and/or context:** Follow-on to PR #1586 for issue #1562
**Changes:**
=> [python] Export `update_obs` and `update_var` from `tiledbsoma.io`

.github/workflows/r-ci.yml, .github/workflows/r-python-interop-testing.yml
Addresses a nit found at https://github.com/single-cell-data/TileDB-SOMA/pull/1679#discussion_r1327428946
=> [ci] Trivial typofixes

scripts/run-clang-format.sh
=> [ci] Have clang-format show version

.github/workflows/python-ci-minimal.yml, libtiledbsoma/src/soma/logger_public.h, libtiledbsoma/src/utils/logger.cc
Neaten of #1692. Findings by @ihnorton. Parent context #866.
=> [ci] MacOS CI updates

.pre-commit-config.yaml, apis/python/src/tiledbsoma/_collection.py, apis/python/src/tiledbsoma/_experiment.py, apis/python/src/tiledbsoma/_measurement.py, apis/python/src/tiledbsoma/io/_registration/signatures.py, apis/python/src/tiledbsoma/io/ingest.py, apis/python/tests/test_collection.py, apis/python/tests/test_dataframe.py, apis/python/tests/test_dense_nd_array.py, apis/python/tests/test_experiment_basic.py, apis/python/tests/test_metadata.py, apis/python/tests/test_registration_signatures.py, apis/python/tests/test_tiledbobject.py, apis/python/tests/test_util.py
This updates us to the latest versions of Black and Ruff, which results in some minor non-behavioral changes to the code.
=> Update tools used in pre-commit testing.

README.md
=> Update README.md to indicate status of Seurat I/O

apis/python/setup.py
=> [python] Temporarily pin to AnnData 0.9.*

apis/python/setup.py
**Issue and/or context:** As in #1765. There is now a 0.10.1 which solves the problem (we were not the only ones to suffer). See also #1785 for longer-term follow-up (next year).
**Changes:**
=> [python] Use AnnData 0.10.1

apis/python/src/tiledbsoma/io/ingest.py
**Issue and/or context:** GitHub issue #1783 and Shortcut story [sc-28843].
=> [python] Update chunk-sizing estimator for chunked matrix write

apis/r/DESCRIPTION
Following
https://github.com/single-cell-data/TileDB-SOMA/wiki/Branches-and-releases
=> [r] Bump to 1.4.4 in `apis/r/DESCRIPTON` on `release-1.4`

apis/r/DESCRIPTION
=> [r] Articulate R version 1.4.4.1

apis/python/MANIFEST.in
=> add py.typed to package manifest

apis/python/src/tiledbsoma/io/ingest.py, apis/python/tests/test_basic_anndata_io.py, scripts/bld
**Issue and/or context:** Post-review feedback from @aaronwolen for PR #1770 / issue #1764.
**Changes:** As requested.
=> [python] Allow uns-key restriction for ingest and outgest

.github/workflows/r-ci.yml, apis/python/setup.py, apis/r/tools/get_tarball.R, libtiledbsoma/cmake/Modules/FindTileDB_EP.cmake
TileDB-R 0.21.2 in `apis/r/DESCRIPTION` to follow once that becomes available
=> [c++/python] Depend on core 2.17.3 and TileDB-Py 0.23.2

apis/python/setup.py, apis/r/DESCRIPTION, apis/r/tools/get_tarball.R, libtiledbsoma/cmake/Modules/FindTileDB_EP.cmake
=> Depend on core 2.17.4, tiledb-py 0.23.4, and tiledb-r 0.21.2

apis/python/src/tiledbsoma/pytiledbsoma.cc, libtiledbsoma/src/CMakeLists.txt, libtiledbsoma/src/cli/cli.cc, libtiledbsoma/src/soma/array_buffers.cc, libtiledbsoma/src/soma/array_buffers.h, libtiledbsoma/src/soma/column_buffer.cc, libtiledbsoma/src/soma/column_buffer.h, libtiledbsoma/src/soma/managed_query.cc, libtiledbsoma/src/soma/managed_query.h, libtiledbsoma/src/soma/soma_array.cc, libtiledbsoma/src/soma/soma_array.h, libtiledbsoma/src/utils/arrow_adapter.cc, libtiledbsoma/src/utils/arrow_adapter.h, libtiledbsoma/test/unit_soma_array.cc, libtiledbsoma/test/unit_soma_group.cc
=> Manually backport 1852 to release 1.5

apis/r/DESCRIPTION, apis/r/NEWS.md
Following on #1854 / #1855 the PR sets to package version to 1.5.0
**Changes:**
None
[SC 36501](https://app.shortcut.com/tiledb-inc/story/36501/roll-version-to-1-5-0)
=> [r] Set the package version to 1.5.0, and update `NEWS.md`

apis/r/DESCRIPTION, apis/r/NEWS.md
**Issue and/or context:** #1856
**Changes:**
=> [r] Manually backport 1856 to `release-1.5`

.github/workflows/python-ci-minimal.yml, .github/workflows/python-ci-single.yml, apis/python/tests/test_sparse_nd_array.py
Changes:
* Pytest now logs 20 slowest tests for both Python and C++ pytests
* Reduce cost of SparseNDArray python unit tests
=> [python] Excess `pytest` duration

apis/r/tests/testthat/test-SOMADataFrame.R
**Issue and/or context:** #1862 #1867
**Changes:**
=> [r] Unit-test queryability of enumerated columns

apis/python/setup.py, apis/python/src/tiledbsoma/_foo.py, apis/r/DESCRIPTION, apis/r/tools/get_tarball.R, libtiledbsoma/cmake/Modules/FindTileDB_EP.cmake
=> Depend on core 2.18.2, tiledb-py 0.24.0, tiledb-r 0.22.0

.pre-commit-config.yaml, apis/python/setup.py
**Issue and/or context:** For issue #1930 and PR #1934
**Changes:**
=> [python] Depend on `somacore` 1.0.6

.github/workflows/r-ci.yml
**Issue and/or context:** Follow-on to commit https://github.com/single-cell-data/TileDB-SOMA/pull/1953/commits/7e0961ee78ff1a481eeb81369293ab3cc1c4f396 of #1953
**Changes:**
=> [r/ci] Show CPU info in R CI as well as Python CI

libtiledbsoma/src/CMakeLists.txt
**Changes:**
Fixes build failures by reverting change originally introduced in #1811. c.c. @johnkerl
=> [c++] Have `tiledbsoma-cli` link to `tiledbsoma`

apis/r/DESCRIPTION, apis/r/NEWS.md, codecov.yml
Same bugfix as for 1.5.2, but on the `release-1.6` branch: #1964
=> [r] Update `DESCRIPTION` and `NEWS.md` for 1.6.1

apis/python/src/tiledbsoma/io/ingest.py, apis/python/tests/test_basic_anndata_io.py
**Issue and/or context:** #1993 for the `release-1.5` branch
**Changes:**
=> [python] Allow specification of X names on ingest [release-1.5]

apis/python/src/tiledbsoma/io/ingest.py
**Issue and/or context:** We have a PR on three branches: #1995, #1996, #1993. The first and third are open; the second one has been merged. @aaronwolen 's code review on #1995 surfaced a wording change which has been applied to #1995 and #1993. This PR makes that same wording change for #1996.
**Changes:**
=> [python] Minor update to `from_h5ad` online help

apis/python/src/tiledbsoma/io/ingest.py
**Issue and/or context:** Backport #1999 to the `release-1.5` branch
**Changes:**
=> [python] Minor update to `from_h5ad` online help (backport release-1.5)

apis/r/DESCRIPTION
* https://github.com/single-cell-data/TileDB-SOMA/releases/tag/1.6.1 exists
* `main` should be "past" that
=> [r] Bump `apis/r/DESCRIPTION` for `main` past current latest release

apis/r/DESCRIPTION, apis/r/R/write_soma.R, apis/r/man/write_soma_objects.Rd, apis/r/tests/testthat/test-write-soma-objects.R
Backport #2013 to the `release-1.6` branch
=> [Backport release-1.6][r] Add support for registering arrays with write_soma()

apis/r/README.md
Issue #2029 on updating documentation to mention the version of C++ compiler to install the R package
**Changes:**
Update `aps/r/README.md` 
N/A
=> [r] Update documentation on g++ requirement for R package

apis/r/configure, apis/r/tools/get_tarball.R
Fixes R cross builds: https://github.com/r-universe/eddelbuettel/actions/runs/7597093792/job/20691678507
=> [r] Support cross compiling on MacOS with R

apis/r/DESCRIPTION, apis/r/NEWS.md
**Issue and/or context:** Following our [established procedure](https://github.com/single-cell-data/TileDB-SOMA/wiki/Branches-and-releases), as I am soon to tag 1.7.0
**Changes:**
**Notes for Reviewer:** See also #2040 on the `main` branch.
=> [r] tiledbsoma-r 1.7.0

apis/python/src/tiledbsoma/io/conversions.py
=> [python] Silence a unit-test warning

apis/python/devtools/outgestor, apis/python/src/tiledbsoma/io/ingest.py, apis/python/tests/test_basic_anndata_io.py
**Issue and/or context:** #2015
**Changes:**
=> [python] Save off ingest-time obs/var index names for use at outgest

apis/r/tools/get_tarball.R, libtiledbsoma/cmake/Modules/FindTileDB_EP.cmake, scripts/update-tiledb-version.py
=> Use core 2.19.1

apis/python/src/tiledbsoma/_collection.py
Context: https://github.com/single-cell-data/TileDB-SOMA/issues/2086#issuecomment-1917669879
=> [python] Elaborate docstring re relativity for add-new

apis/python/src/tiledbsoma/__init__.py, apis/python/src/tiledbsoma/_experiment.py, apis/python/src/tiledbsoma/_index_util.py, apis/python/tests/test_indexer.py, apis/python/tests/test_reindexer_api.py, libtiledbsoma/src/reindexer/reindexer.cc, libtiledbsoma/test/test_indexer.cc
**Issue and/or context:** #2067
We need an external python API for the C++ reindexer
**Changes:**
=> [python] Reindexer external python API

apis/python/src/tiledbsoma/_index_util.py
Follow-ups from #2080 and #2081.
=> [python] Fix some docstring typos

apis/python/src/tiledbsoma/__init__.py, apis/python/src/tiledbsoma/_experiment.py, apis/python/src/tiledbsoma/_index_util.py, apis/python/tests/test_indexer.py, apis/python/tests/test_reindexer_api.py, libtiledbsoma/src/reindexer/reindexer.cc, libtiledbsoma/test/test_indexer.cc
Backports #2080 to the `release-1.7` branch
=> [Backport release-1.7] [python] Reindexer external python API

profiler/profiler.py, profiler/setup.py
=> [python] Minor fixes to the profiler

apis/r/configure
=> [r] Fix quoting for a particular Docker-build environment (`main`)

apis/python/src/tiledbsoma/_util.py, apis/python/src/tiledbsoma/io/_registration/signatures.py, apis/python/src/tiledbsoma/io/conversions.py, apis/python/src/tiledbsoma/io/ingest.py, apis/python/tests/test_basic_anndata_io.py, apis/python/tests/test_platform_config.py, apis/python/tests/test_registration_mappings.py, apis/python/tests/test_registration_signatures.py, apis/python/tests/test_update_dataframes.py
=> [python] Do not mutate `adata.obs`/`adata.var` on ingest

.github/workflows/python-ci-minimal.yml, apis/python/tests/test_basic_anndata_io.py
Fixes failed CI lint check on main due to formatting error in tests
**Changes:**
=> [python] Lint fix

apis/python/src/tiledbsoma/io/ingest.py, apis/python/tests/test_basic_anndata_io.py
Backport #2119 to the `release-1.7` branch
=> [Backport release-1.7] [python] Outgest additional X layers to AnnData

apis/r/DESCRIPTION, apis/r/NEWS.md
=> [r] TileDB-SOMA-R 1.7.1

apis/python/setup.py, apis/python/src/tiledbsoma/pytiledbsoma.cc, apis/python/src/tiledbsoma/soma_dense_ndarray.cc, apis/python/src/tiledbsoma/soma_sparse_ndarray.cc, libtiledbsoma/src/soma/soma_dense_ndarray.cc, libtiledbsoma/src/soma/soma_dense_ndarray.h, libtiledbsoma/src/soma/soma_sparse_ndarray.cc, libtiledbsoma/src/soma/soma_sparse_ndarray.h
[#2128](https://github.com/single-cell-data/TileDB-SOMA/issues/2128)
**Changes:**
Addition of `soma_dense_ndarray.cc` and `soma_sparse.ndarray.cc`.
These changes were picked out of https://github.com/single-cell-data/TileDB-SOMA/pull/1817.
These changes are on top of https://github.com/single-cell-data/TileDB-SOMA/pull/2126.
=> [python] Add bindings for ndarrays

apis/r/DESCRIPTION, apis/r/NEWS.md
=> [r] tiledbsoma 1.7.2

apis/python/src/tiledbsoma/_dataframe.py, apis/python/src/tiledbsoma/soma_array.cc, apis/python/src/tiledbsoma/soma_dataframe.cc, apis/python/src/tiledbsoma/soma_object.cc
It failed post-merge CI. I'll resubmit.
=> [release-1.7] Revert #2162

apis/r/tools/get_tarball.R, libtiledbsoma/cmake/Modules/FindTileDB_EP.cmake, scripts/update-tiledb-version.py
`./scripts/update-tiledb-version.py 2.19.2` and commit resulting mods
=> Use core 2.19.2 for the `release-1.7` branch

libtiledbsoma/src/reindexer/reindexer.h, libtiledbsoma/src/reindexer/test_indexer_data_types_perf.py, libtiledbsoma/src/soma/soma_context.cc, libtiledbsoma/src/soma/soma_context.h
Addressing minor issues related to reindexer's shared threadpool and its optimization for pandas and pyarrow: review comments from #2148 and #2159.
**Changes:**
=> [c++] Address issues related to reindexer advanced features

apis/python/src/tiledbsoma/_experiment.py, apis/python/src/tiledbsoma/_index_util.py, apis/python/src/tiledbsoma/_read_iters.py, apis/python/src/tiledbsoma/reindexer.cc, apis/python/tests/test_indexer.py, apis/python/tests/test_reindexer_api.py, apis/r/DESCRIPTION, libtiledbsoma/src/CMakeLists.txt, libtiledbsoma/src/reindexer/reindexer.cc, libtiledbsoma/src/reindexer/reindexer.h, libtiledbsoma/src/reindexer/test_indexer_data_types_perf.py, libtiledbsoma/src/soma/soma_context.cc, libtiledbsoma/src/soma/soma_context.h, libtiledbsoma/test/test_indexer.cc
#2189 has maddening discrepancies not worth the debugging. The `main` and `release-1.8` branches are so close, they can just be bulk-synched.
Literally I did:
* `git pull` on `main`
* `git pull` on `release-1.8`
* `git diff -r release-1.8 -r main > x`
* `patch -p1 < x`
Then make a PR branch off `release-1.8`, commit, push.
Tracking issue: #2149.
=> Sync `main` to `release-1.8`

apis/python/src/tiledbsoma/_dataframe.py
**Issue and/or context:** #2197 
**Changes:** As in #2197, pulls the array-evolve outside the loop over columns.
Existing unit-test coverage suffices to prove nothing was broken by this PR. No new cases need to be added. As discussed on #2197 this only happens on faster hardware, and in particular, non-CI setups since CI machines simply run more slowly. For _this particular bug_, interactive validation following the scenario of #2197 suffices.
<details>
```
================================================================
$ ./test-categoricals.py both -n1 -bB before
Wrote pyarrow Table pyarrow.Table
soma_joinid: int64
bool-ordered: dictionary<values=bool, indices=int8, ordered=1>
bool-unordered: dictionary<values=bool, indices=int8, ordered=0>
----
soma_joinid: …
```
=> Fix race condition (GitHub issue upcoming)

apis/r/DESCRIPTION, apis/r/NEWS.md
=> [r] tiledbsoma-r 1.8.0

apis/r/DESCRIPTION, apis/r/NEWS.md
=> [r] tiledbsoma-r 1.7.3

scripts/bld
Sibling of #2216
See also https://github.com/single-cell-data/TileDB-SOMA/issues/2219 for tracking
=> [release-1.8] Append `LD_LIBRARY_PATH` for census

scripts/bld
Per Slack conversation with @bkmartinjr 
See also https://github.com/single-cell-data/TileDB-SOMA/issues/2219 for tracking
=> [release-1.7] Append `LD_LIBRARY_PATH` for census

.github/workflows/python-so-copying.yml, apis/python/setup.py
I don't know why backport-bot is failing today. This is #2220 and #2221 for #2219 and #2210.
=> [release-1.8] Backport #2220 and #2221

.github/workflows/python-so-copying.yml, apis/python/setup.py
I don't know why backport-bot is failing today. This is #2220 and #2221 for #2219 and #2210.
=> [release-1.7] Backport #2220 and #2221

apis/python/src/tiledbsoma/_experiment.py, apis/python/src/tiledbsoma/_index_util.py, apis/python/src/tiledbsoma/_read_iters.py, apis/python/tests/test_indexer.py, apis/python/tests/test_reindexer_api.py
**Issue and/or context:** #2225
**Changes:**
=> [python] Fix context-type for `tiledbsoma_build_index`

apis/python/src/tiledbsoma/_experiment.py, apis/python/src/tiledbsoma/_index_util.py, apis/python/src/tiledbsoma/_read_iters.py, apis/python/tests/test_indexer.py, apis/python/tests/test_reindexer_api.py
=> [release-1.7] Fix context-type for `tiledbsoma_build_index`

apis/python/src/tiledbsoma/_experiment.py, apis/python/src/tiledbsoma/_index_util.py, apis/python/src/tiledbsoma/_read_iters.py, apis/python/tests/test_indexer.py, apis/python/tests/test_reindexer_api.py
=> [release-1.8] Fix context-type for `tiledbsoma_build_index`

.github/workflows/python-so-copying.yml
=> [Backport release-1.8] [ci] Only run build tests when build files are modified

.github/workflows/python-so-copying.yml
=> [Backport release-1.7] [ci] Only run build tests when build files are modified

apis/python/tests/test_io.py
**Issue and/or context:** #1565 
**Notes for Reviewer:** unsuccessful first attempt to repro #1565. Either the issue was fixed, or I'm missing something necessary to repro it. Thoughts welcome.
=> [python] Attempt to repro #1565

.pre-commit-config.yaml, apis/python/setup.py
**Issue and/or context:** #1791
=> Bump `somacore` to 1.0.9

libtiledbsoma/src/utils/arrow_adapter.cc
=> [c++] Match `delete[]` with `new[]`

.github/workflows/python-ci-minimal.yml, apis/python/tests/test_io.py, profiler/src/profiler/data.py, profiler/src/profiler/profiler.py
Backports #2247 to the `release-1.8` branch
=> [Backport release-1.8] [python/ci] Restore pre-merge lint checks

apis/r/DESCRIPTION, apis/r/NEWS.md
=> [r] Prepare for tiledbsoma 1.8.1

.github/workflows/python-so-copying.yml, apis/python/setup.py, apis/r/DESCRIPTION, apis/r/tools/get_tarball.R, libtiledbsoma/cmake/Modules/FindTileDB_EP.cmake
[sc-43172]
Procedure:
https://github.com/single-cell-data/TileDB-SOMA/wiki/Branches-and-releases#incrementing-core-versions
=> Use TileDB core 2.21.0, TileDB-Py 0.27.0, TileDB-R 0.25.0

.github/workflows/python-ci-single.yml, apis/python/src/tiledbsoma/_dataframe.py, apis/python/src/tiledbsoma/_types.py, apis/python/src/tiledbsoma/_util.py, apis/python/src/tiledbsoma/io/_registration/__init__.py, apis/python/src/tiledbsoma/io/conversions.py, apis/python/src/tiledbsoma/io/ingest.py, apis/python/tests/__init__.py
**Issue and/or context:** while working on #2252, cleaned up a few things while trying to understand/audit them.
=> `ingest.py` cleanups, doc nits

.github/workflows/python-so-copying.yml, apis/r/tools/get_tarball.R, libtiledbsoma/cmake/Modules/FindTileDB_EP.cmake
=> Use core 2.21.1

.github/workflows/python-ci-minimal.yml
=> [python/ci] Typofix from #2305

apis/r/DESCRIPTION, apis/r/NEWS.md
=> [r] R version for `release-1.9` branch

apis/r/DESCRIPTION, apis/r/NEWS.md
=> [r] TileDB-SOMA 1.9.3

apis/python/src/tiledbsoma/io/ingest.py
**Issue and/or context:** fixes #2359
Documentation follow-up to #2258
=> [python] `tiledbsoma.io.from_h5ad`: document new `additional_metadata` param

apis/python/src/tiledbsoma/io/_registration/ambient_label_mappings.py
**Issue and/or context:** #2368 
**Changes:** Propagate contexts appropriately
**Notes for Reviewer:** As an ongoing task we need to improve our unit-test coverage beyond this open-source repo to handle non-free stores such as TileDB Cloud and Amazon S3. Note that all unit-test cases passed before and after this PR, as the unit-test cases within this repo don't utilize Amazon S3, let alone multi-region S3.
A repro nonetheless is here:
<details>
First at the shell
```
unset AWS_ACCESS_KEY_ID
unset AWS_SECRET_ACCESS_KEY
unset AWS_DEFAULT_REGION
export AK="[redacted]"
export SK="[redacted]"
```
then
```
import tiledbsoma.io
import tiledbsoma.logging
import tiledb
import sys, os, shutil
local_input_paths = [
"/home/ubuntu/s/a/stack-small/stack1.h5ad", …
```
=> [python] Expand coverage for registration of multi-region S3-backed H5ADs

.github/workflows/r-ci.yml, .github/workflows/r-python-interop-testing.yml
#2275 edited only one of two necessary files
=> [r/ci] Continue #2275

apis/r/DESCRIPTION, apis/r/NEWS.md
=> [r] TileDB-SOMA-R 1.9.4

apis/r/DESCRIPTION, apis/r/NEWS.md
**Issue and/or context:** Following our [established procedure](https://github.com/single-cell-data/TileDB-SOMA/wiki/Branches-and-releases)
**Changes:**
**Notes for Reviewer:** To be merged after https://github.com/TileDB-Inc/tiledbsoma-feedstock/pull/131 is green
=> [r] TileDB-SOMA 1.9.5

apis/r/DESCRIPTION, apis/r/NEWS.md
=> [r] TileDB-SOMA R 1.10 (`release-1.10` branch)

apis/r/DESCRIPTION, apis/r/NEWS.md
=> [r] TileDB-SOMA-R 1.10.1

libtiledbsoma/src/soma/soma_dataframe.cc, libtiledbsoma/src/utils/arrow_adapter.cc, libtiledbsoma/src/utils/arrow_adapter.h
https://github.com/single-cell-data/TileDB-SOMA/issues/2480
**Changes:**
Add inline documentation for `PlatformConfig` options and add more robust checking for passed in values.
=> [c++] Add documentation and better checking to `PlatformConfig`

.github/workflows/python-so-copying.yml
=> Stage requirements.txt into its own file.

apis/r/R/SOMAExperimentAxisQuery.R, apis/system/tests/test_densendarray_write_python_read_r.py
**Issue and/or context:** This is debug atop #2453 with the assistance of the incomparable @mojaveazure. It will be merged into #2453.
**Changes:**
=> [r] Resolve R issues with dense-read-performance PR #2453 [WIP]

apis/r/R/SOMADenseNDArray.R, apis/r/R/SOMAExperimentAxisQuery.R, apis/r/tests/testthat/test-SOMADenseNDArray.R, apis/r/tools/r-ci.sh, apis/system/tests/test_densendarray_write_python_read_r.py, libtiledbsoma/src/soma/managed_query.cc, libtiledbsoma/test/unit_soma_dense_ndarray.cc
Backports #2453 to the `release-1.10` branch
=> [Backport release-1.10] [c++] Do not add dimensions for dense array queries if not requested

apis/python/src/tiledbsoma/io/ingest.py
Following up from PR #2516 for issue #2499 / [sc-46790]
=> [python] Continue #2516

libtiledbsoma/src/reindexer/test_indexer_data_types_perf.py, libtiledbsoma/src/soma/managed_query.h, libtiledbsoma/src/soma/soma_array.h
Apparently introduced here:
https://github.com/single-cell-data/TileDB-SOMA/blame/main/libtiledbsoma/src/soma/soma_array.h#L285
=> [c++] Remove extraneous print statements

apis/python/src/tiledbsoma/_arrow_types.py, apis/python/src/tiledbsoma/_util.py, apis/python/tests/_util.py, apis/python/tests/conftest.py, apis/python/tests/test_basic_anndata_io.py, apis/python/tests/test_experiment_query.py, apis/python/tests/test_io.py, apis/python/tests/test_platform_config.py, apis/python/tests/test_registration_mappings.py, apis/python/tests/test_registration_signatures.py, apis/python/tests/test_update_dataframes.py, apis/python/tests/test_update_matrix.py, libtiledbsoma/src/reindexer/test_indexer_data_types_perf.py, libtiledbsoma/src/soma/managed_query.h, libtiledbsoma/src/soma/soma_array.h
**Issue and/or context:** Pre-PR to facilitate #2518
**Changes:** Just renames and comments -- zero functional changes
=> [python] Clarify `test_update_dataframe.py` and `_arrow_types.py`

apis/python/src/tiledbsoma/_arrow_types.py, apis/python/src/tiledbsoma/_dataframe.py, apis/python/src/tiledbsoma/_util.py, apis/python/src/tiledbsoma/io/ingest.py, apis/python/tests/test_update_dataframes.py
**Issue and/or context:** #2517 / [sc-46654]
**Changes:** As described in the PR
=> [python] Fix `failed to convert buffer` on `update_obs`/`update_var`

apis/r/DESCRIPTION, libtiledbsoma/src/reindexer/test_indexer_data_types_perf.py
**Issue and/or context:** This is a documented step in our [established procedure](https://github.com/single-cell-data/TileDB-SOMA/wiki/Branches-and-releases#branchtag-mechanics).
**Changes:**
[sc-46600]
=> [r] Prep on `main` for `release-1.11` branch

.github/workflows/r-ci.yml, .github/workflows/r-python-interop-testing.yml, apis/r/tools/install-tiledb-r.R
**Issue and/or context:** #2546. This and a backport of #2540 (which must come first) will be needed for #2549.
**Changes:**
=> [r] Backport #2546 to `release-1.10`

.github/workflows/r-ci.yml, .github/workflows/r-python-interop-testing.yml, apis/r/R/SOMAExperimentAxisQuery.R, apis/r/tools/install-tiledb-r.R
=> [r] Backport #2540 and #2546 to `release-1.10`

apis/r/DESCRIPTION, apis/r/NEWS.md
=> [r] Prep for 1.11.0

apis/r/DESCRIPTION, apis/r/NEWS.md
https://github.com/single-cell-data/TileDB-SOMA/issues/2556#issuecomment-2110422212Solely for a readthedocs issue as documented here:
=> [r] tiledbsoma 1.11.1

apis/python/src/tiledbsoma/_tdb_handles.py
Clean up some dev remnants (my own!)
=> [python] Trivial neaten

apis/python/src/tiledbsoma/experimental/__init__.py, apis/python/src/tiledbsoma/experimental/ingest.py
This function is added to make prototyping and testing faster when reading cellxgene h5ad files containing visium spatial data
**Changes:**
Refactored the core logic of ingestion into a separate function
=> [python] Add functionality to read cellxgene spatial h5ad files

apis/python/src/tiledbsoma/options/_tiledb_create_options.py, apis/python/version.py, scripts/bld
**Issue and/or context:** N/A
**Changes:**
Couple typo fixes, and `version.py` cleanups that I didn't squash into #2590
=> [python/c++] Typo fixes / nits

libtiledbsoma/src/utils/arrow_adapter.cc
https://github.com/TileDB-Inc/tiledbsoma-feedstock/issues/153#issuecomment-2122979236
#2608
=> [c++] Fix nightly build failure on `formattable` of `json` type

apis/python/src/tiledbsoma/options/_tiledb_create_options.py, apis/python/version.py, scripts/bld
Manually backport #2596 to `release-1.11`
https://github.com/single-cell-data/TileDB-SOMA/pull/2596#issuecomment-2122859357
=> [Backport release-1.11] [python/c++] Typo fixes / nits

apis/r/DESCRIPTION, apis/r/NEWS.md
=> [r] TileDB-SOMA 1.11.3

.github/workflows/r-ci.yml, apis/r/tests/testthat/test-SingleCellExperimentIngest.R, apis/r/tests/testthat/test-SummarizedExperimentIngest.R, apis/r/tests/testthat/test-write-soma-resume.R
Increase timeout for downloading files, including packages to install. Setting to 300 seconds on advice from @eddelbuettel
=> [r/ci] Adjust file download timeout to 300 seconds

apis/r/DESCRIPTION, apis/r/NEWS.md
=> [r] tiledbsoma 1.11.4

.github/workflows/python-ci-single.yml, .github/workflows/r-ci.yml, .github/workflows/r-python-interop-testing.yml
**Issue and/or context:** Follow-on from #2685
=> [ci] Switch from 16MB to 32MB buffer sizes for tiny GHA runners

apis/python/src/tiledbsoma/_coordinates.py, apis/python/src/tiledbsoma/experimental/ingest.py
=> [spatial] Lint/typecheck fixes

.github/workflows/pkgdown.yaml, apis/r/tools/install-pkgdown-dependencies.sh
Addresses #2702. See also particular CI run https://github.com/single-cell-data/TileDB-SOMA/actions/runs/9446113943
=> [r/ci] Unbreak `pkgdown` CI

.github/workflows/r-valgrind.yaml
Follow-on from #2703; issue #2702
=> [r/ci] Unbreak `r-valgrind` CI

apis/python/tests/test_dataframe.py
This is expected to fail given a PR from yesterday and some in-Slack conversations today. This will be merged into an upcoming bugfix PR.
=> [python] Augment unit-testing for enumeration extensions

apis/python/tests/test_dataframe.py, libtiledbsoma/src/soma/soma_array.cc
**Issue and/or context:** This is @nguyenv 's fix for an issue found earlier and discussed in #2722.
**Changes:** Apply recent column-data changes to column-levels logic: @nguyenv ; also, unit-test enhancement from #2722 has been merged into here.
=> [c++] Fix enum-of-bool leveling

apis/python/src/tiledbsoma/_arrow_types.py, apis/python/src/tiledbsoma/io/ingest.py, apis/python/tests/test_basic_anndata_io.py, apis/python/tests/test_update_dataframes.py
**Issue and/or context:** #2717
=> [python] Support `tiledbsoma.io.update_obs` with post-nullable non-string attributes

apis/python/src/tiledbsoma/experimental/ingest.py
Add `obs_scene` and `var_scene` creation to the experimental Visium ingestor.
=> [spatial] Add presence matrices to experimental ingestor

apis/python/setup.py
**Issue and/or context:** #2536
=> [python] Pin to numpy < 2.0 for 1.12 release

apis/r/DESCRIPTION, apis/r/NEWS.md
Context: https://github.com/single-cell-data/TileDB-SOMA/issues/2672
=> [r] TileDB-SOMA 1.12

apis/r/DESCRIPTION, apis/r/NEWS.md
Incorporates #2757 
Please also see #2672 #2758
=> [r] TileDB-SOMA 1.12.1

apis/python/src/tiledbsoma/io/outgest.py
A debug statement should not have been retained.
=> [python] Remove a debug statement

apis/r/DESCRIPTION, apis/r/NEWS.md
=> [r] TileDB-SOMA 1.12.2

apis/r/DESCRIPTION, apis/r/NEWS.md
=> tiledbsoma-r 1.12.3

libtiledbsoma/src/soma/soma_dataframe.cc, libtiledbsoma/src/soma/soma_dataframe.h, libtiledbsoma/src/soma/soma_dense_ndarray.cc, libtiledbsoma/src/soma/soma_dense_ndarray.h, libtiledbsoma/src/soma/soma_sparse_ndarray.cc, libtiledbsoma/src/soma/soma_sparse_ndarray.h, libtiledbsoma/test/unit_soma_dataframe.cc, libtiledbsoma/test/unit_soma_dense_ndarray.cc, libtiledbsoma/test/unit_soma_sparse_ndarray.cc
**Issue and/or context:** #2793, [sc-49546]
**Changes:**
Add `SOMAContext` argument for `exist` methods.
=> [c++] `exists` should take in `SOMAContext`

.pre-commit-config.yaml, apis/python/pyproject.toml, apis/python/src/tiledbsoma/_arrow_types.py, apis/python/src/tiledbsoma/_collection.py, apis/python/src/tiledbsoma/_factory.py, apis/python/src/tiledbsoma/_indexer.py, apis/python/src/tiledbsoma/_types.py, apis/python/src/tiledbsoma/io/conversions.py, apis/python/src/tiledbsoma/io/ingest.py, apis/python/src/tiledbsoma/options/_soma_tiledb_context.py, apis/python/tests/test_dataframe.py, apis/python/tests/test_funcs.py, apis/python/tests/test_registration_mappings.py, apis/python/tests/test_regression.py, apis/python/tests/test_sparse_nd_array.py
Changes:
* ran `pre-commit autoupdate` which updated black, ruff and mypy versions
* ran pre-commit, which applied latest formatting rules
* updated pyproject.toml to fix obsolete syntax issue with ruff config
* fix lint pointed out by latest mypy
=> pre-commit update

apis/python/tests/test_sparse_nd_array.py
**Issue and/or context:** Continuation of #2826. I somehow missed some unit-test signal.
**Changes:**
=> [python] More `reshape` neatens

apis/python/tests/test_query_condition.py
Follow-up from https://github.com/single-cell-data/TileDB-SOMA/pull/2864#discussion_r1712996264
=> [python] Fix a comment

apis/python/src/tiledbsoma/_experiment.py, apis/python/src/tiledbsoma/_soma_object.py, apis/python/src/tiledbsoma/_tdb_handles.py
For https://github.com/single-cell-data/TileDB-SOMA/pull/2884#issuecomment-2287113522
=> [python] Remove some dead code

apis/r/DESCRIPTION, apis/r/NEWS.md
=> [r] TileDB-SOMA 1.13.1

libtiledbsoma/src/soma/soma_object.cc
**Issue and/or context:** Found while working on #2785 for issue #2407 / [[sc-51048]](https://app.shortcut.com/tiledb-inc/story/51048). 
**Changes:** Use the named constant, like other places within this file.
=> [c++] Trivial name-neaten

apis/python/src/tiledbsoma/_dense_nd_array.py, libtiledbsoma/test/unit_soma_dense_ndarray.cc
**Changes:**
Add some tracking links, as I've recently created the newly referenced tracking issue.
This is a trivial split-out from #2950 to help reduce the line-count there.
=> Add tracking links for dense/new-shape support

apis/r/tools/install-tiledb-r.R
The `install-tiledb-r.R` script isn't correctly handling the case where all repos contain a valid version of tiledb-r. Currently, we're using `-idx[!valid]` which returns `integer(0)` when `valid` is all `TRUE`; to fix, adjust this dropping to run only when `!all(valid)`
Also contains the following adjustments:
- switch upstream dependency solving to an `apply()` in case of multiple valid versions with differing upstream dependencies
- fix the `bspm::disable()` check to actually use bspm where available
[SC-54635](https://app.shortcut.com/tiledb-inc/story/54635/)
=> [r/ci] Fix bug when installing tiledb-r

libtiledbsoma/src/utils/logger.cc
I find this very useful, particularly on #2407 / [[sc-51048]](https://app.shortcut.com/tiledb-inc/story/51048). If useful to other folks, great; if not, hopefully not too disruptive.
=> [c++] Support option to set log level from environment

libtiledbsoma/test/unit_soma_dataframe.cc
=> [c++] Deconfuse a test name

.pre-commit-config.yaml, apis/python/notebooks/tutorial_spatial.ipynb, apis/python/setup.py, apis/python/src/tiledbsoma/_multiscale_image.py, apis/python/src/tiledbsoma/_point_cloud.py, apis/python/src/tiledbsoma/_scene.py, apis/python/src/tiledbsoma/_spatial_util.py
* Modify names of methods in the `Scene` class
* Use `@` instead of `*` for `CoordinateTransform` composition
=> Update the spatial branch to match changes to somacore

apis/python/src/tiledbsoma/_common_nd_array.py, apis/python/src/tiledbsoma/_dataframe.py, apis/python/src/tiledbsoma/_sparse_nd_array.py, apis/python/src/tiledbsoma/_tdb_handles.py, apis/python/src/tiledbsoma/options/_soma_tiledb_context.py, apis/python/src/tiledbsoma/options/_tiledb_create_write_options.py, apis/r/NEWS.md, apis/r/R/SOMADataFrame.R, apis/r/R/SOMANDArrayBase.R, apis/r/R/TileDBArray.R, apis/r/man/SOMADataFrame.Rd, apis/r/man/SOMANDArrayBase.Rd, apis/r/man/TileDBArray.Rd
Includes updated ETAs for the work on #1632 and #2407
=> [python/r] Update ETA for new-shape feature

apis/python/src/tiledbsoma/__init__.py, apis/python/src/tiledbsoma/_dataframe.py, apis/python/src/tiledbsoma/_flags.py, apis/python/src/tiledbsoma/_sparse_nd_array.py, apis/python/tests/test_dataframe.py, apis/python/tests/test_shape.py, apis/python/tests/test_sparse_nd_array.py
**Issue and/or context:** Follow-up from here: https://github.com/single-cell-data/TileDB-SOMA/pull/3001#issuecomment-2355914110
**Changes:**
=> [python] Move temporary feature flag into a module

apis/r/DESCRIPTION, apis/r/NEWS.md
=> [r] Post-1.14 version for `main` branch

apis/r/DESCRIPTION, apis/r/NEWS.md
=> [r] 1.14 version for `release-1.14` branch

apis/r/DESCRIPTION, apis/r/NEWS.md
=> [r] TileDB-SOMA 1.14.1

libtiledbsoma/test/unit_soma_collection.cc, libtiledbsoma/test/unit_soma_dataframe.cc, libtiledbsoma/test/unit_soma_dense_ndarray.cc, libtiledbsoma/test/unit_soma_sparse_ndarray.cc
**Changes:**
Just some neatens and careful spellings.
=> [c++] Be a bit more careful testing dim-max vs shape

libtiledbsoma/test/unit_soma_dataframe.cc
**Changes:**
Fixes a bad merge of #3012 and #3020 (each of which had green pre-merge CI) as identified by @jp-dark 
=> [c++] Fix bad merge from #3012 and #3020

libtiledbsoma/test/unit_managed_query.cc, libtiledbsoma/test/unit_soma_array.cc, libtiledbsoma/test/unit_soma_dataframe.cc, libtiledbsoma/test/unit_soma_dense_ndarray.cc, libtiledbsoma/test/unit_soma_group.cc, libtiledbsoma/test/unit_soma_sparse_ndarray.cc
**Issue and/or context:** Issue found while debugging memory-management concerns on #3028 for issue #2407 / [[sc-51048]](https://app.shortcut.com/tiledb-inc/story/51048).
**Changes:**
Not super-high-pri, but, I found these while debugging another problem & thought it worth putting up a PR.
=> [c++] Fix a `valgrind` issue in unit-test code

.github/ISSUE_TEMPLATE/bug_report.md, .github/workflows/python-ci-full.yml, .github/workflows/python-ci-minimal.yml, .pre-commit-config.yaml, apis/python/pyproject.toml, apis/python/setup.py, apis/python/src/tiledbsoma/_general_utilities.py, apis/python/src/tiledbsoma/_types.py, apis/python/src/tiledbsoma/io/ingest.py, apis/python/tests/test_funcs.py, libtiledbsoma/README.md
https://github.com/single-cell-data/TileDB-SOMA/issues/2141
[sc-41048](https://app.shortcut.com/tiledb-inc/story/41048/soma-python-drop-support-for-python-3-8)
=> [python] Use `somacore` 1.0.16

.pre-commit-config.yaml, apis/python/notebooks/tutorial_spatial.ipynb, apis/python/setup.py, apis/python/src/tiledbsoma/_geometry_dataframe.py, apis/python/src/tiledbsoma/_multiscale_image.py, apis/python/src/tiledbsoma/_point_cloud.py, apis/python/src/tiledbsoma/_scene.py, apis/python/src/tiledbsoma/_spatial_dataframe.py, apis/python/src/tiledbsoma/experimental/ingest.py
This PR updates the spatial branch to use the latest updates to the spatial API released in somacore 1.0.18.
=> Update the spatial branch to work with somacore==1.0.18

.github/workflows/python-ci-packaging.yml, apis/r/tools/get_tarball.R, libtiledbsoma/cmake/Modules/FindTileDB_EP.cmake
=> Use core 2.26.2

libtiledbsoma/src/CMakeLists.txt, libtiledbsoma/src/soma/soma_experiment.cc, libtiledbsoma/src/soma/soma_object.cc, libtiledbsoma/src/soma/soma_scene.cc, libtiledbsoma/src/soma/soma_scene.h, libtiledbsoma/src/tiledbsoma/tiledbsoma, libtiledbsoma/test/CMakeLists.txt, libtiledbsoma/test/unit_soma_scene.cc
Add a simple C++ SOMAScene class to libtiledbsoma.
=> [c++] Add `SOMAScene` class

.pre-commit-config.yaml, apis/python/setup.py, apis/python/src/tiledbsoma/_geometry_dataframe.py, apis/python/src/tiledbsoma/_multiscale_image.py, apis/python/src/tiledbsoma/_point_cloud_dataframe.py, apis/python/src/tiledbsoma/_scene.py, apis/python/src/tiledbsoma/_tdb_handles.py, libtiledbsoma/src/soma/soma_object.cc
- Rename `PointCloud` -> `PointCloudDataFrame`
- Make `coordinate_space` property not optional in `MultiscaleImage`, `GeometryDataFrame`, and `PointCloudDataFrame`.
=> [python/c++] Update TileDB-SOMA to somacore 1.0.19

.github/workflows/python-packaging.yml
**Issue and/or context:** nightly failures #3102, #3105; follow-on to #3076
=> `setuptools>=70.1` in sdist GHA

apis/python/src/tiledbsoma/__init__.py, apis/python/src/tiledbsoma/_arrow_types.py, apis/python/src/tiledbsoma/_constants.py, apis/python/src/tiledbsoma/_factory.py, apis/python/src/tiledbsoma/_multiscale_image.py, apis/python/src/tiledbsoma/_soma_object.py, apis/python/src/tiledbsoma/_spatial_util.py, apis/python/src/tiledbsoma/_tdb_handles.py, apis/python/src/tiledbsoma/soma_collection.cc, apis/python/src/tiledbsoma/soma_object.cc, apis/python/tests/test_multiscale_image.py
Add the Python implementation for the new `MultiscaleImage` class.
=> [python] Add implementation of the `MultiscaleImage` to `main`

.pre-commit-config.yaml, apis/python/setup.py
Helps with #2407 and spatial-demo work
=> [python] Use `somacore` 1.0.20

apis/r/DESCRIPTION, apis/r/NEWS.md
https://github.com/single-cell-data/TileDB-SOMA/pull/3121#issuecomment-2392176587
#2406 
#3058 
[[sc-55674]](https://app.shortcut.com/tiledb-inc/story/55674/r-use-libtiledbsoma-for-dims-attrs-accessors)
=> [r] `DESCRIPTION` and `NEWS.md` for #3121

apis/r/DESCRIPTION, apis/r/NEWS.md, apis/r/R/SOMANDArrayBase.R, apis/r/R/SOMASparseNDArray.R, apis/r/tests/testthat/test-SOMADenseNDArray.R, apis/r/tests/testthat/test-SOMASparseNDArray.R
Backports #3145 to the `release-1.14` branch
=> [r] Backport #3145 to `release-1.14`; 1.14.3

apis/r/DESCRIPTION, apis/r/NEWS.md, apis/r/R/SOMADenseNDArray.R, apis/r/R/SOMASparseNDArray.R
#3055 [[sc-55682]](https://app.shortcut.com/tiledb-inc/story/55682/r-use-libtiledbsoma-for-all-tiledb-schema-callsites)
=> [r] Remove two more `tiledb::schema` callsites

libtiledbsoma/src/CMakeLists.txt, libtiledbsoma/src/geometry/operators/envelope.cc, libtiledbsoma/src/geometry/operators/envelope.h, libtiledbsoma/test/CMakeLists.txt, libtiledbsoma/test/unit_geometry_envelope.cc
This PR adds the ability to compute an `Envelope` for all supported geometry types.
=> [c++] Geometry envelope computation

.github/workflows/python-ci-full.yml, .github/workflows/python-ci-minimal.yml, .github/workflows/python-ci-packaging.yml, .github/workflows/python-ci-single.yml, .github/workflows/python-packaging.yml
**Issue and/or context:** https://github.com/actions/runner-images/issues/10721
**Changes:**
=> [ci] Move CI workers from `macos-12` to `macos-latest`

.pre-commit-config.yaml, apis/python/setup.py, apis/python/src/tiledbsoma/_geometry_dataframe.py, apis/python/src/tiledbsoma/_multiscale_image.py, apis/python/src/tiledbsoma/_point_cloud_dataframe.py, apis/python/src/tiledbsoma/_scene.py, apis/python/tests/test_point_cloud_dataframe.py
Update somacore version and implement the following changes from somacore:
* Update name and arguments in the `Scene` methods for adding new assets.
* Change the `create` methods for the `PointCloudDataFrame` and `GeometryDataFrame` classes to directly take the `CoordinateSpace` as an argument instead of only accepting a tuple of axis names.
* Use new factory method for creating a `CoordinateSpace` from axis names.
=> Update TileDB-SOMA to use somacore==1.0.21

apis/python/tests/test_dataframe.py, apis/python/tests/test_dataframe_index_columns.py
=> [python] Domain-at-create unit-test PR 3/5

apis/python/tests/test_sparse_nd_array.py
=> [python] Domain-at-create unit-test PR 5/5

apis/python/tests/test_point_cloud_dataframe.py, apis/python/tests/test_scene.py
=> [python] Domain-at-create unit-test PR 1/5

apis/python/tests/test_factory.py
We’ve identified intermittent failures in CI for `test_factory.py` during [these runs](https://github.com/single-cell-data/TileDB-SOMA/actions/runs/11395503805/job/31707792429),
**Changes:**
To resolve race conditions, metadata is now written and read at designated timestamps.
=> [python] Add timestamps for group metadata writes and reads

apis/r/DESCRIPTION, apis/r/NEWS.md, apis/r/man/SOMADataFrameCreate.Rd, apis/r/man/SOMADataFrameOpen.Rd, apis/r/man/SOMADenseNDArray.Rd, apis/r/man/SOMANDArrayBase.Rd, apis/r/man/SOMASparseNDArray.Rd, apis/r/man/TileDBObject.Rd, apis/r/man/soma_context.Rd
**Issue and/or context:** For #3217
[SC-57387](https://app.shortcut.com/tiledb-inc/story/57387)
[SC-57804](https://app.shortcut.com/tiledb-inc/story/57804)
=> [r] Prep for 1.14.4 release

.github/workflows/python-packaging.yml
#1849
#3221 
python-packaging.yml run on this branch: [#907](https://github.com/single-cell-data/TileDB-SOMA/actions/runs/11481922172) ✅
=> [ci] `python-packaging.yml`: add Python 3.12 wheels

apis/r/DESCRIPTION, apis/r/NEWS.md
For https://github.com/single-cell-data/TileDB-SOMA/pull/3225
=> [r] Prepare for 1.14.5

.pre-commit-config.yaml, apis/python/requirements_dev.txt, apis/python/setup.py
**Issue and/or context:** #3216, #3246
=> Use `typeguard==4.4.0`, `somacore==1.0.22`

apis/r/tests/testthat/test-contexts.R
Missed a `git add` and two `git rm` on #3257
=> File add/removes for bulk-sync from `main` to `release-1.15`

apis/r/DESCRIPTION, apis/r/NEWS.md, apis/r/tests/testthat/test-shape.R
**Changes:**
More for https://github.com/TileDB-Inc/centralized-tiledb-nightlies/issues/25
=> [r] More fixes for unit-test cases with dense + core 2.27

apis/python/src/tiledbsoma/_dataframe.py
**Changes:**
A couple spots I missed on a previous PR. I found these while working on #3285.
=> [python] More auto-detect of `function_name_for_messages`

apis/python/src/tiledbsoma/__init__.py, apis/python/src/tiledbsoma/_common_nd_array.py, apis/python/src/tiledbsoma/_dataframe.py, apis/python/src/tiledbsoma/_indexer.py, apis/python/src/tiledbsoma/_sparse_nd_array.py, apis/python/src/tiledbsoma/io/ingest.py, apis/python/src/tiledbsoma/io/outgest.py, apis/python/src/tiledbsoma/io/shaping.py, apis/python/src/tiledbsoma/stats.py
**Issue and/or context:** Found while working on #3282 and #3285.
**Changes:** Make sphinx output look less wrong.
**Notes for Reviewer:** Comments inline.
=> [python] Misc. formatting fix-ups

apis/python/src/tiledbsoma/_dataframe.py, apis/python/src/tiledbsoma/_sparse_nd_array.py, apis/python/src/tiledbsoma/io/shaping.py, apis/r/R/SOMADenseNDArray.R, apis/r/R/SOMANDArrayBase.R, apis/r/R/SOMASparseNDArray.R, apis/r/R/TileDBArray.R, apis/r/man/TileDBArray.Rd, doc/source/python-tiledbsoma-dataframe.rst
**Changes:**
Atop PRs #3283 and #3284 as tracked on issue #3282.
Stacking as of today:
* `main`
* #3284
* #3285
* Copy of #3276 in `kerl/dataframe-shape-temp`
* #3290
=> [python] Doc updates for new-shape feature

apis/python/README.md, apis/r/README.md
=> [r/python] Note on dev installs and `spdlog` failures

apis/r/src/rinterface.cpp, apis/r/src/rutilities.cpp, libtiledbsoma/test/common.cc
**Issue and/or context:** More in the vein of #3310. Found by 👀 on a drive-by.
**Changes:**
=> [r] Address two more compiler warnings

libtiledbsoma/src/soma/soma_array.h, libtiledbsoma/src/soma/soma_geometry_dataframe.cc, libtiledbsoma/src/soma/soma_geometry_dataframe.h, libtiledbsoma/test/common.cc
Follow up PR on #3266, this PR concatenates internal dimensions and report the as one to match the number of index columns
=> [c++] Hide internal dimensions on domain

apis/python/src/tiledbsoma/_dataframe.py, apis/python/tests/test_dataframe.py, apis/r/R/SOMADataFrame.R, apis/r/tests/testthat/test-06-SOMADataFrame.R
**Issue and/or context:** As tracked on issue #2407 / [[sc-51048]](https://app.shortcut.com/tiledb-inc/story/51048). Reverts #3300.
**Changes:** Per @bkmartinjr 
**Notes for reviewer:**
=> [r/python] Revert #3300

.github/workflows/python-ci-packaging.yml, apis/r/tools/get_tarball.R, libtiledbsoma/cmake/Modules/FindTileDB_EP.cmake
**Issue and/or context:** #3364
**Changes:**
=> [c++/python/r] Use core 2.27.0-rc3

apis/python/src/tiledbsoma/_query.py
PR #3359 introduced a bug in the reading of sparse arrays. In some situations, it would allow a buffer of type insufficient to store the results (int32 instead of int64). This was due to a sign inversion in a comparison.
There was also a second edge case where the dim0 and dim1 buffers would be of different type, which is unsupported by the `fastercsx` package. 
This change chooses the buffer type correctly, based on the max needed by both dimensions.
=> [python] Fix incorrect type handling in `ExperimentAxisQuery` sparse reader

apis/r/DESCRIPTION, apis/r/NEWS.md
I forgot to update the changelog and develop version for #3395 :facepalm:
=> [r] Update changelog and develop version for #3395

apis/python/src/tiledbsoma/io/ingest.py
**Issue and/or context:** Found while working on #3354. See also [sc-59344](https://app.shortcut.com/tiledb-inc/story/59344).
**Changes:**
=> [python] Some memory-reduction for append mode

libtiledbsoma/src/soma/managed_query.cc
=> [c++] Fix merge of #3436

.pre-commit-config.yaml, apis/python/setup.py
**Issue and/or context:** Missed on #2407
**Changes:**
=> [python] Use `somacore` 1.0.25

apis/r/DESCRIPTION, apis/r/NEWS.md
=> [r] TileDB-SOMA 1.15.0

apis/r/DESCRIPTION, apis/r/NEWS.md
[[sc-59686]](https://app.shortcut.com/tiledb-inc/story/59686/update-projects-to-tiledb-2-27)
=> [r] TileDB-SOMA 1.15.2 [skip ci]

libtiledbsoma/src/utils/fastercsx.h
On #3541 I failed to downgrade C++20-isms (`main`) to C++17 (`release-1.15`)
=> [c++] Fix backport on #3541

apis/python/src/tiledbsoma/_query.py
The `_read` function and `AxisQueryResult` appear to exist to prevent future code duplication. However, this adds indirection and line noise to the current codebase. We can add these back in the future if/when they are needed.
**Notes for Reviewer:** This change is primarily code movement.
=> [python] Inline `_read` and `AxisQueryResult` to `to_anndata`

apis/r/DESCRIPTION, apis/r/NEWS.md
=> [r] TileDB-SOMA 1.15.3

apis/python/src/tiledbsoma/io/shaping.py
**Issue and/or context:** Fixes #3581.
**Changes:** Validated manually by calling the following on an experiment URI which is inaccessible without context:
* `tiledbsoma.io.show_experiment_shapes`
* `tiledbsoma.io.upgrade_experiment_shapes`
* `tiledbsoma.io.resize_experiment`
**Notes for Reviewer:** Unit-test cases using closed-source resources is a cross-cutting project tracked on [[sc-25441]](https://app.shortcut.com/tiledb-inc/story/25441).
=> [python] Pass more context in `io/shaping.py`

doc/source/python-tiledbsoma-experimentaxisquery.rst, doc/source/python-tiledbsoma-io-spatial.rst
**Issue and/or context:** #3592
**Changes:**
Add the `tiledbsoma.io.spatial` module and the `ExperimentQueryAxis.to_spatialdata` method to read the docs.
=> [python] Add spatial I/O functions to readthedocs

libtiledbsoma/test/unit_soma_column.cc
**Issue and/or context:** Found while building today
**Changes:**
=> [c++] Remove an unused-variable warning

apis/python/src/tiledbsoma/common.cc, apis/python/src/tiledbsoma/common.h
**Issue and/or context:** Following on multiple backports today
**Changes:**
=> [c++] Downgrade C++20isms to C++17isms for `release-1.15` branch

apis/python/src/tiledbsoma/reindexer.cc, apis/python/src/tiledbsoma/soma_object.cc
**Issue and/or context:** Found on drive-by
**Changes:**
=> [c++] Remove some compiler warnings

apis/r/DESCRIPTION, apis/r/NEWS.md
=> [r] TileDB-SOMA 1.15.4

doc/source/python-tiledbsoma-affine-transform.rst, doc/source/python-tiledbsoma-identity-transform.rst, doc/source/python-tiledbsoma-scale-transform.rst, doc/source/python-tiledbsoma-uniform-scale-transform.rst, doc/source/python-tiledbsoma.rst
**Issue and/or context:** As found from user feedback.
**Changes:**
Preview: https://tiledbsoma.readthedocs.io/en/kerl-more-spatial-transform-doc/python-api.html
=> [python] Add spatial transforms to readthedocs

apis/python/src/tiledbsoma/__init__.py
**Issue and/or context:** [sc-59919](https://app.shortcut.com/tiledb-inc/story/59919/add-coordinate-space-transform-to-all)
**Changes:**
Re-export coordinate transforms from somacore.
=> [python] Re-export coordinate transforms from somacore

doc/source/python-tiledbsoma-multiscaleimage.rst
**Issue and/or context:** Backport of #3651 to the `release-1.15` branch
**Changes:**
=> [Backport release-1.15][python] Backport 3651

apis/python/src/tiledbsoma/managed_query.cc, apis/python/tests/test_dataframe.py, apis/python/tests/test_sparse_nd_array.py, libtiledbsoma/src/soma/column_buffer.cc, libtiledbsoma/src/soma/column_buffer.h, libtiledbsoma/src/soma/managed_query.cc, libtiledbsoma/src/soma/managed_query.h, libtiledbsoma/src/soma/soma_array.cc, libtiledbsoma/src/utils/util.cc, libtiledbsoma/src/utils/util.h
**Issue and/or context:** Manually backport #3611 to the `release-1.15` branch given the robofail at https://github.com/single-cell-data/TileDB-SOMA/pull/3611#issuecomment-2631235515
**Changes:**
=> [Backport release-1.15][c++] Fix offsets for nullable columns

apis/r/DESCRIPTION, apis/r/NEWS.md
**Issue and/or context:** #3662 .Following our [established procedure](https://github.com/single-cell-data/TileDB-SOMA/wiki/Branches-and-releases).
**Changes:**
=> [r] TileDB-SOMA 1.15.7

.github/workflows/python-dependency-variation.yml
**Issue and/or context:** [[sc-63023]](https://app.shortcut.com/tiledb-inc/story/63023)
**Changes:**
=> [python/ci] Test against older dependency versions

.github/workflows/python-remote-storage.yml
**Issue and/or context:** Having seen https://github.com/single-cell-data/TileDB-SOMA/actions/runs/13222801334
**Changes:**
=> [ci] Fix typo in new CI job

apis/python/remote_tests/test_04_append.py
**Issue and/or context:** Found while looking at the `unittest` user's activity in the cloud UI
**Changes:**
=> [python/ci] Clean up a bit more after a test case

libtiledbsoma/src/soma/soma_column.cc
**Issue and/or context:** Found on drive-by
**Changes:**
=> [c++] Fix some misbroken lines [trivial]

apis/python/src/tiledbsoma/io/ingest.py
**Issue and/or context:** #3633
**Changes:**
Skip checks when appending to a `Dataframe` when there is no new data to write.
=> [python] Skip checks for append to a dataframe when no new data

apis/r/tools/r-ci.sh
**Issue and/or context:** #3705
**Changes:**
=> [r/ci] Use R 4.4 for MacOS CI

apis/python/tests/test_dense_nd_array.py
Add [more tests](https://github.com/TileDB-Inc/cloud-dev-temp/blob/main/debug/new-shape/dense-corners.py) for `DenseNDArray` (originally written by @johnkerl). Follow-up to https://github.com/single-cell-data/TileDB-SOMA/pull/3708.
=> [python] Add more unit tests for `DenseNDArray`

.github/workflows/libtiledbsoma-asan-ci.yml, .github/workflows/python-ci-packaging.yml, apis/r/tools/get_tarball.R, libtiledbsoma/cmake/Modules/FindTileDB_EP.cmake
```
./scripts/update-tiledb-version.py 2.27.1
```
#3720 [[sc-63626]](https://app.shortcut.com/tiledb-inc/story/63626/tiledb-soma-1-16-0)
=> [c++] Update to core 2.27.1

apis/r/DESCRIPTION, apis/r/NEWS.md
#3720 [[sc-63626]](https://app.shortcut.com/tiledb-inc/story/63626/tiledb-soma-1-16-0)
=> [r] Update `DESCRIPTION` for `main`, post 1.16.0

apis/python/src/tiledbsoma/_query_condition.py
**Issue and/or context:** [sc-61558](https://app.shortcut.com/tiledb-inc/story/61558/python-deprecationwarning-related-to-query-condition-when-running-python-3-12)
**Changes:**
Remove deprecated `ast.NameConstant` and `ast.Num` types. Use `ast.Constant` instead.
=> [python] Remove deprecated `ast.NameConstant` and `ast.Num`

apis/python/src/tiledbsoma/_query_condition.py, apis/python/tests/test_query_condition.py
**Issue and/or context:** #3738
**Changes:** As in the PR.
**Notes for Reviewer:** Needs unit-test cases.
=> [python] Fix query condition for `in` operator combined with `attr(...)`

.github/workflows/python-ci-full.yml, .github/workflows/python-ci-minimal.yml, .github/workflows/python-packaging.yml, apis/python/setup.py, apis/python/src/tiledbsoma/io/_util.py
**Issue and/or context:** https://github.com/conda-forge/tiledbsoma-feedstock/pull/6, #3704, [[sc-63457]](https://app.shortcut.com/tiledb-inc/story/63457/try-out-python-3-13-with-tiledb-soma)
**Changes:**
=> [python/ci] Try Python 3.13 in CI

apis/python/tests/test_basic_anndata_io.py, apis/python/tests/test_dataframe.py
**Issue and/or context:** factored out of #3740
=> [python] Remove dead code, `s/Tuple/tuple/`

apis/r/DESCRIPTION, apis/r/NEWS.md
=> [r] TileDB-SOMA 1.16.1

apis/python/src/tiledbsoma/soma_array.cc, apis/python/tests/test_sparse_nd_array.py
=> [Backport release-1.16][python] Cast object to child class in pybind11 `SOMAArray.reopen`

libtiledbsoma/src/soma/managed_query.cc, libtiledbsoma/src/soma/managed_query.h
**Issue and/or context:** Split out from #3784 for #3785 / [[sc-63930]](https://app.shortcut.com/tiledb-inc/story/63930/dataframe-need-api-to-extend-column-enum-values-without-doing-a-write#activity-64471)
**Changes:**
* On #3784 it will be necessary to have an otherwise-obtained enumeration passed. There's no strict need for `_extend_enumeration` to be instantiating the core `tiledb::Enumeration` object
* As a bonus, we avoid a double instantiate:
* https://github.com/single-cell-data/TileDB-SOMA/blob/86f08d524efff3d20a9f1779f922252aa07ac3ec/libtiledbsoma/src/soma/managed_query.cc#L953-L954
* https://github.com/single-cell-data/TileDB-SOMA/blob/86f08d524efff3d20a9f1779f922252aa07ac3ec/libtiledbsoma/src/soma/managed_query.cc#L1038-L1039
* Along the way, I now pass the core …
=> [c++] Pass `Enumeration` through `_extend_enumeration`

apis/python/setup.py, apis/r/configure, apis/r/src/Makevars.in, libtiledbsoma/CMakeLists.txt
**Issue and/or context:** #3787 
**Changes:**
- Remove GCC version check
- Relax min macOS version from 13.3 to 11.0
=> [c++/python/r] Relax GCC13 build requirements

LICENSE, apis/r/R/QueryCondition.R, doc/source/conf.py, libtiledbsoma/CMakeLists.txt
**Issue and/or context:** #3591, #3619
**Changes:**
Remove year ranges from copyright matter in:
- `LICENSE`
- ReadTheDocs' Sphinx template
- `libtiledbsoma/CMakeLists.txt`
- `apis/r/R/QueryCondition.R`
=> Remove some copyright year ranges

.github/workflows/libtiledb-ci.yml, .github/workflows/libtiledbsoma-asan-ci.yml, .github/workflows/python-ci-minimal.yml, .github/workflows/python-ci-packaging.yml, .github/workflows/python-dependency-variation.yml, .github/workflows/python-dockers.yml, .github/workflows/python-remote-storage.yml, .github/workflows/r-ci.yml, .github/workflows/r-python-interop-testing.yml, docker/README.md, docker/bookworm.dockerfile, docker/langchain.dockerfile, docker/ubuntu-src.dockerfile, docker/ubuntu.dockerfile
**Issue and/or context:** Manual backport of #3763 since the backport bot silently did nothing on that PR. :|
**Changes:**
=> [Backport release-1.16][ci] Example Dockerfiles install from source / PyPI

apis/python/src/tiledbsoma/io/ingest.py
**Issue and/or context:** Trivial; found on a drive-by.
**Changes:**
=> [python] Fix a typo in a comment [skip ci]

.pre-commit-config.yaml, apis/python/src/tiledbsoma/_collection.py, apis/python/src/tiledbsoma/_constants.py, apis/python/src/tiledbsoma/_exception.py, apis/python/src/tiledbsoma/_experiment.py, apis/python/src/tiledbsoma/_general_utilities.py, apis/python/src/tiledbsoma/_measurement.py, apis/python/src/tiledbsoma/_query.py, apis/python/src/tiledbsoma/_read_iters.py, apis/python/src/tiledbsoma/io/conversions.py, apis/python/src/tiledbsoma/io/shaping.py, apis/python/src/tiledbsoma/io/spatial/_util.py, apis/python/src/tiledbsoma/options/_tiledb_create_write_options.py, apis/python/tests/ht/_arrow_util.py, apis/python/tests/ht/_ht_test_config.py
Changes:
1. Updated pre-commit repo versions to latest, _excluding_ mypy
2. Ran pre-commit - other changes are auto-fixes from ruff, et al.
=> [ci/python] Update pre-commit repos, except `mypy`

apis/python/src/tiledbsoma/_dataframe.py, apis/python/src/tiledbsoma/_dense_nd_array.py, apis/python/src/tiledbsoma/_geometry_dataframe.py, apis/python/src/tiledbsoma/_point_cloud_dataframe.py, apis/python/src/tiledbsoma/_soma_array.py, apis/python/src/tiledbsoma/_sparse_nd_array.py, apis/python/src/tiledbsoma/managed_query.cc, apis/python/src/tiledbsoma/pytiledbsoma.cc, apis/python/tests/test_dataframe.py, libtiledbsoma/src/soma/managed_query.cc, libtiledbsoma/src/soma/managed_query.h, libtiledbsoma/test/unit_soma_array.cc
Done manually after https://github.com/single-cell-data/TileDB-SOMA/pull/3764#issuecomment-2767076801
=> [python/c++] Allow GOW multi-submit for single commit (#3764)

apis/python/src/tiledbsoma/managed_query.cc, apis/r/src/arrow.cpp, libtiledbsoma/src/soma/managed_query.cc, libtiledbsoma/src/soma/managed_query.h, libtiledbsoma/src/soma/soma_collection.cc, libtiledbsoma/src/soma/soma_collection.h, libtiledbsoma/src/soma/soma_dense_ndarray.cc, libtiledbsoma/src/soma/soma_dimension.cc, libtiledbsoma/src/soma/soma_sparse_ndarray.cc, libtiledbsoma/src/utils/arrow_adapter.cc, libtiledbsoma/src/utils/arrow_adapter.h, libtiledbsoma/test/common.cc, libtiledbsoma/test/unit_arrow_adapter.cc, libtiledbsoma/test/unit_soma_array.cc, libtiledbsoma/test/unit_soma_collection.cc, libtiledbsoma/test/unit_soma_column.cc, libtiledbsoma/test/unit_soma_dataframe.cc, libtiledbsoma/test/unit_soma_dense_ndarray.cc, libtiledbsoma/test/unit_soma_geometry_dataframe.cc, libtiledbsoma/test/unit_soma_point_cloud_dataframe.cc, libtiledbsoma/test/unit_soma_sparse_ndarray.cc
**Issue and/or context:** [sc-65116](https://app.shortcut.com/tiledb-inc/story/65116/c-fix-asan-errors-in-unit-tests)
**Changes:**
=> [c++] Fix Arrow memory leaks in unit tests

apis/python/src/tiledbsoma/io/__init__.py
**Issue and/or context:** [[sc-65041]](https://app.shortcut.com/tiledb-inc/story/65041) #3920
**Changes:** As in #3920.
=> [python] Protect against an AnnData/SciPy incompatibility

apis/python/remote_tests/test_03_versions.py, apis/python/src/tiledbsoma/io/__init__.py, apis/python/src/tiledbsoma/io/shaping.py, apis/python/tests/test_shape.py, apis/python/tests/test_soma_experiment_versions.py, doc/source/python-tiledbsoma-io.rst
**Issue and/or context:** Backport #3962 which includes #3949
**Changes:**
=> [Backport release-1.16][python] Refactor `io/shaping.py`; `get_experiment_shapes`

.github/workflows/daily-python-packaging-issue-template.md, .github/workflows/daily-test-build-issue-template.md, .github/workflows/python-packaging.yml
Backports #3973 following https://github.com/single-cell-data/TileDB-SOMA/pull/3973#issuecomment-2803183518
=> [Backport release-1.16][python/ci] Harmonize/GC daily-GHA-failure issue templates

apis/python/src/tiledbsoma/soma_vfs.cc, apis/python/tests/test_basic_anndata_io.py
Backports #3976 given https://github.com/single-cell-data/TileDB-SOMA/pull/3976#issuecomment-2803185216
=> [Backport release-1.16][python][c++] Correctly manage lifetime of `SOMAVFS` with `SOMAVFSFilebuf`

apis/python/src/tiledbsoma/soma_array.cc, apis/python/tests/ht/test_ht_io_anndata.py, libtiledbsoma/src/soma/soma_array.cc
**Issue and/or context:** Found in internal ops-testing
**Changes:** Fix error introduced on #3958.
Also has a workaround for #4000 which appeared unbidden today, not caused by this PR.
=> [c++] Fix error in raise-if-slow path

apis/python/tests/ht/test_ht_io_anndata.py
Fixes #4000 
The to/from anndata round trip hypothesis strategy did not account for reserved keys in the `uns` structure.
=> [python] fix bad unit test

libtiledbsoma/src/soma/managed_query.h
**Issue and/or context:** To be written up.
**Changes:**
=> [c++] Trivial method-order rearrange

apis/python/example-scripts/ingest_h5ads.py
**Issue and/or context:** Authored by @bkmartinjr ; I'm simply putting up the PR.
Companion to https://documentation.cloud.tiledb.com/academy/structure/life-sciences/single-cell/tutorials/.
[[sc-64771]](https://app.shortcut.com/tiledb-inc/story/64771/docs-update-academy-to-account-for-enum-evolution-api)
**Changes:**
=> [python] Sample bulk-ingestion script

libtiledbsoma/src/soma/soma_array.cc
=> [c++] Fix error introduced by renaming lambda

apis/r/R/BlockwiseIter.R, apis/r/R/Factory.R, apis/r/R/SOMASparseNDArrayRead.R, apis/r/R/utils-arrow.R, apis/r/man/BlockwiseTableReadIter.Rd, apis/r/man/SOMACollectionCreate.Rd, apis/r/man/SOMADataFrameCreate.Rd, apis/r/man/SOMAExperimentCreate.Rd, apis/r/man/SOMAMeasurementCreate.Rd, apis/r/man/SOMASparseNDArrayBlockwiseRead.Rd, apis/r/man/SOMASparseNDArrayCreate.Rd, apis/r/man/r_type_from_arrow_type.Rd
Fix links to other packages in the docs for CRAN
Fixes [SOMA-26](https://linear.app/tiledb/issue/SOMA-26/ensure-urls-are-valid)
=> [r] Update cross-references in documentation

apis/r/DESCRIPTION, apis/r/R/Factory.R, apis/r/R/TileDBObject.R, apis/r/man/SOMADataFrameCreate.Rd, apis/r/man/SOMADataFrameOpen.Rd, apis/r/man/TileDBObject.Rd
Update docs for CRAN
Fixes [SOMA-25](https://linear.app/tiledb/issue/SOMA-25/ensure-all-paramters-are-documented)
=> [r] Document missing parameters

.pre-commit-config.yaml, apis/python/HISTORY.md
Add change log / HISTORY.md for the Python API.
Also added a pre-commit to lint this file.
=> [python] add HISTORY.md

apis/r/NEWS.md
Add PR links to the changelog
Fixes [SOMA-53](https://linear.app/tiledb/issue/SOMA-53/r-add-pr-links-to-newsmd)
=> [r] Add links to `NEWS.md`

README.md
Added links to the R and Python package change logs
=> add release notes / change log to top-level README.md

.pre-commit-config.yaml, apis/python/src/tiledbsoma/_experiment.py, apis/python/src/tiledbsoma/_measurement.py
Update pre-commit versions to latest and deal with a few changes to mypy type checks
=> [chore] update pre-commit repo versions

apis/python/HISTORY.md, apis/r/DESCRIPTION, apis/r/NEWS.md
Prepare changelogs for release 1.17.0rc0.
=> Update changelogs for release 1.17.0rc0

.pre-commit-config.yaml, apis/python/HISTORY.md, apis/python/src/tiledbsoma/soma_array.cc, apis/python/src/tiledbsoma/soma_dataframe.cc, apis/python/src/tiledbsoma/soma_geometry_dataframe.cc, apis/python/src/tiledbsoma/soma_point_cloud_dataframe.cc, apis/python/src/tiledbsoma/transformer.cc, libtiledbsoma/src/soma/soma_array.cc, libtiledbsoma/src/soma/soma_geometry_column.cc, libtiledbsoma/src/utils/arrow_adapter.cc
**Issue and/or context:** [SOMA-169](https://linear.app/tiledb/issue/SOMA-169/c-memory-leak-in-somaarray-get-core-domainish)
**Changes:**
=> [c++/python] Fix domain getter memory leak on C++/Python layer

apis/python/src/tiledbsoma/common.h
=> [python] Remove unnecessary query condition allocation

.github/ISSUE_TEMPLATE/bug_report.md
Need to ensure issue creators explicitly share core version for compatibility with bindings
**Changes:**
Added bullet to emphasize the core version
Based on user feedback
=> emphasize core version in bug report template

apis/python/HISTORY.md, apis/r/DESCRIPTION, apis/r/NEWS.md
Update the changelogs and the R development version.
=> Prepare for 1.18.0rc0

apis/python/src/tiledbsoma/_dataframe.py
**Issue and/or context:** [SOMA-95](https://linear.app/tiledb/issue/SOMA-95/python-soma-dataframe-with-column-named-x00-is-silently-modified-to)
**Changes:**
=> [python] Check for null bytes in column name

dev_docs/POLICIES.md
Add policies for how we handle both TileDB and TileDB-SOMA on-disk format changes.
=> Add policies around format changes

libtiledbsoma/src/soma/managed_query.cc, libtiledbsoma/src/soma/managed_query.h
**Issue and/or context:** [SOMA-355](https://linear.app/tiledb/issue/SOMA-355/use-enumerationindex-of-function-from-core)
**Changes:**
=> [c++] Use `index_of` function from Enumeration API

.github/workflows/libtiledbsoma-asan-ci.yml, .github/workflows/python-ci-packaging.yml, apis/python/HISTORY.md, apis/r/DESCRIPTION, apis/r/NEWS.md, apis/r/tools/get_tarball.R, libtiledbsoma/cmake/Modules/FindTileDB_EP.cmake
Update the TileDB version to 2.28.1 for the latest release.
=> Update TileDB core to 2.28.1

apis/python/devtools/ingestor, apis/python/pyproject.toml, apis/python/src/tiledbsoma/_multiscale_image.py, apis/python/src/tiledbsoma/_util.py, apis/python/src/tiledbsoma/io/_registration/ambient_label_mappings.py, apis/python/tests/ht/test_ht_io_anndata.py, apis/python/tests/test_context.py, apis/python/tests/test_metadata.py, apis/python/tests/test_shape.py, apis/python/tests/test_stats.py, apis/python/version.py, scripts/update-tiledb-version.py
More enforced lint checks in CI
Part of SOMA-323
=> [python] enable Ruff Python lint rules PLC, PLE, PLW

.github/workflows/python-dependency-variation.yml
Remove extra `-` in Python dependency variation test.
=> [ci] Remove errant '-' from github action

dev_docs/POLICIES.md
**Issue and/or context:** Closes SOMA-205
**Changes:**
Add policy around error messages.
=> Add error style guide to policies

apis/python/src/tiledbsoma/io/_registration/ambient_label_mappings.py, apis/python/src/tiledbsoma/io/conversions.py
=> Fix mypy issues

libtiledbsoma/src/tiledb_adapter/platform_config.cc, libtiledbsoma/src/tiledb_adapter/platform_config.h, libtiledbsoma/src/utils/arrow_adapter.cc, libtiledbsoma/src/utils/arrow_adapter.h
More code movement out of `arrow_adapter.h/cc`.
=> Move initial ArraySchema creation to platform config file

apis/r/R/utils-arrow.R
Remove two arrow utility functions that are no longer called anywhere.
=> [r] Remove no longer used arrow utils helper functions

.github/workflows/ci-full.yml, .github/workflows/test-r.yml
Fix two typos introduced in PR #4225
=> [ci] Fix typos in CI

apis/python/src/tiledbsoma/_collection.py, apis/python/src/tiledbsoma/_common_nd_array.py, apis/python/src/tiledbsoma/_coordinate_selection.py, apis/python/src/tiledbsoma/_dataframe.py, apis/python/src/tiledbsoma/_dense_nd_array.py, apis/python/src/tiledbsoma/_geometry_dataframe.py, apis/python/src/tiledbsoma/_managed_query.py, apis/python/src/tiledbsoma/_point_cloud_dataframe.py, apis/python/src/tiledbsoma/_query.py, apis/python/src/tiledbsoma/_read_iters.py, apis/python/src/tiledbsoma/_soma_array.py, apis/python/src/tiledbsoma/_soma_group.py, apis/python/src/tiledbsoma/_soma_object.py, apis/python/src/tiledbsoma/_sparse_nd_array.py, apis/python/src/tiledbsoma/_tdb_handles.py, apis/python/src/tiledbsoma/io/ingest.py, apis/python/src/tiledbsoma/io/outgest.py, apis/python/tests/ht/test_ht_dataframe.py, apis/python/tests/ht/test_ht_sparsendarray.py, apis/python/tests/test_basic_anndata_io.py, apis/python/tests/test_dataframe.py, apis/python/tests/test_dense_nd_array.py, apis/python/tests/test_factory.py, apis/python/tests/test_metadata.py, apis/python/tests/test_sparse_nd_array.py
**Issue and/or context:** Towards SOMA-500
**Changes:**
* Rename handle wrapper members `_handle` -> `_handle_wrapper`.
* Add clib handles as direct `SOMAObject` members.
* Replace many handle wrapper calls with direct calls to the clib handles.
* Remove some of the unneeded functions from the handle wrappers.
=> [python] Prepare to remove handle wrappers

apis/python/HISTORY.md, apis/r/DESCRIPTION, apis/r/NEWS.md
**Issue and/or context:** Closes [SOMA-572]
**Changes:**
* Update changelogs
* Update R version number
=> Release candidate 2.0.0rc0

.github/workflows/ci-full.yml, .github/workflows/ci-r-python-interop.yml, .github/workflows/python-dependency-variation.yml, .github/workflows/test-python.yml
**Issue and/or context:** Closes SOMA-580
**Changes:**
Small changes to the CI to fix failed python tests on release.
=> [ci] Fix issue where we are unable to checkout tag

apis/r/DESCRIPTION, apis/r/NEWS.md
Update the R version number and NEWS in preparation for the 2.0.0 release.
=> [r] Update new and version number for 2.0.0 release
