.github/workflows/python-so-copying.yml

Backports #2435 to the `release-1.9` branch

[Backport release-1.9] [python/ci] Run SO copying workflow on macos-13 to avoid SIP

---

apis/python/src/tiledbsoma/io/ingest.py

One of @nguyenv 's last comments on #2434, I applied in sandbox but failed to git-push to remote before merging the latter. Here they are.

[python] Code-review-feedback follow-up from #2434

---

apis/python/src/tiledbsoma/__init__.py
apis/python/src/tiledbsoma/_general_utilities.py

**Issue and/or context:** #1837 
**Changes:**
- Add `verify_core_versions` helper which asserts that TileDB-Py's and `libtiledbsoma`'s core versions match
- Add `verify_core_versions()` to `tiledbsoma.__init__.py`
- Add `TILEDB_CORE_MISMATCHED_VERSIONS_ERROR_LEVEL=err` "escape hatch"; if the check above catches any users, and they *really* want to just keep running and fix it later, this allows it (but prints a relevant error message).
- Minor reformatting of `show_package_versions` output:
```diff
< tiledbsoma.__version__        1.5.0rc0.post272.dev2332272127
< TileDB-Py tiledb.version()    (0, 27, 1)
< TileDB core version           2.21.1
< libtiledbsoma version()       libtiledb=2.21.1
< python version                3.11.8.final.0
< OS version                    Darwin 23.2.0
---
> …
```

[python] `verify_core_versions()` during `import tiledbsoma`

---

.github/workflows/python-so-copying.yml
apis/python/setup.py
apis/r/DESCRIPTION
apis/r/tools/get_tarball.R
libtiledbsoma/cmake/Modules/FindTileDB_EP.cmake

**Issue and/or context:** Following our [established procedure](https://github.com/single-cell-data/TileDB-SOMA/wiki/Branches-and-releases)
**Changes:**
**Notes for Reviewer:** This PR is not ready for review. First I will look for green CI.

Use core 2.22.0, TileDB-Py 0.28.0, TileDB-R 0.26.0 on `main` branch

---

Makefile

Running `make format` causes the nanoarrow files to be unnececessarily reformatted.
**Changes:**
Exclude nanoarrow files in make format's find.

Do not include nanoarrow files in clang-format

---

.github/workflows/r-ci.yml
.github/workflows/r-python-interop-testing.yml

TileDB-SOMA uses TileDB Embedded and needs to ensure it builds / tests with a TileDB-R version using the same TileDB Embedded version
**Changes:**
Ensure the corresponding version from tiledb-inc.r-universe.dev is used on macOS and Linux
The r-ci.yml contained a number of paragraphs we had accumulated over the last several month when debugging other issues.  They are not needed, and may distract overall.  So this PR removes them but they can be restored as desired. This PR aims to serve as an existence proof of working CI as e.g. provided in [this run](
https://github.com/single-cell-data/TileDB-SOMA/actions/runs/8714532260/job/23904928763) moments ago.

[r/ci] Required changes to `r-ci.yml`, plus simplifications

---

apis/r/DESCRIPTION

Please see #2328 for previous
[sc-44519]

Bump `DESCRIPTION` version past 1.10 (`main` branch)

---

.github/workflows/r-ci.yml
.github/workflows/r-python-interop-testing.yml
apis/r/DESCRIPTION

**Issue and/or context:** Per https://github.com/single-cell-data/TileDB-SOMA/pull/2373#issuecomment-2035526682 following advice https://stackoverflow.com/questions/63834412/enforce-upper-bound-for-r-package-version-dependency which is at variance with https://github.com/rstudio/renv/issues/764 and, in fact, everything I've ever been told. I'm currently uncertain whether the bidirectional-pin syntax is genuinely new.
**Changes:** Try it out!
**Notes for Reviewer:** This PR is not ready for review. I will take this PR out of draft status as such time as it becomes ready  for review.

[r] Experiment with syntax for lower and upper pin bounds on `tiledb-r`

---

libtiledbsoma/src/external/include/nanoarrow/nanoarrow.h
libtiledbsoma/src/soma/soma_array.h
libtiledbsoma/src/soma/soma_collection.cc
libtiledbsoma/src/soma/soma_collection.h
libtiledbsoma/src/soma/soma_dataframe.cc
libtiledbsoma/src/soma/soma_dataframe.h
libtiledbsoma/src/soma/soma_dense_ndarray.cc
libtiledbsoma/src/soma/soma_dense_ndarray.h
libtiledbsoma/src/soma/soma_experiment.cc
libtiledbsoma/src/soma/soma_experiment.h
libtiledbsoma/src/soma/soma_measurement.cc
libtiledbsoma/src/soma/soma_measurement.h
libtiledbsoma/src/soma/soma_object.cc
libtiledbsoma/src/soma/soma_object.h
libtiledbsoma/src/soma/soma_sparse_ndarray.cc
libtiledbsoma/src/soma/soma_sparse_ndarray.h
libtiledbsoma/src/utils/arrow_adapter.cc
libtiledbsoma/src/utils/arrow_adapter.h
libtiledbsoma/test/CMakeLists.txt
libtiledbsoma/test/common.cc
libtiledbsoma/test/common.h
libtiledbsoma/test/test_indexer.cc
libtiledbsoma/test/unit_column_buffer.cc
libtiledbsoma/test/unit_managed_query.cc
libtiledbsoma/test/unit_soma_array.cc
libtiledbsoma/test/unit_soma_collection.cc
libtiledbsoma/test/unit_soma_dataframe.cc
libtiledbsoma/test/unit_soma_dense_ndarray.cc
libtiledbsoma/test/unit_soma_group.cc
libtiledbsoma/test/unit_soma_sparse_ndarray.cc

**Issue and/or context:** #2228 
Part of larger branch https://github.com/single-cell-data/TileDB-SOMA/pull/2367
**Changes:**
- Addition of `tiledb_schema_from_arrow_schema` converter that takes in an `ArrowSchema` with `ColumnIndexInfo`, which contains info about the dimension's extent and tiles, and `PlatformConfig`, which contains info for other TileDB `ArraySchema` settings such as filters, etc.
- All `SOMAObject` `create` functions now take in `ArrowSchema`, `ColumnIndexInfo`, and `PlatformConfig` arguments; return signature is void to avoid opening the TileDB object until necessary
- Add unit test helper functions in `common.cc` and `common.h`

[c++] Addition of `ArrowSchema` to TileDB `ArraySchema` Converter

---

libtiledbsoma/src/reindexer/reindexer.cc
libtiledbsoma/src/reindexer/reindexer.h
libtiledbsoma/src/soma/soma_collection.h
libtiledbsoma/src/soma/soma_dataframe.h
libtiledbsoma/src/soma/soma_dense_ndarray.h
libtiledbsoma/src/soma/soma_experiment.h
libtiledbsoma/src/soma/soma_measurement.h
libtiledbsoma/src/soma/soma_sparse_ndarray.h
libtiledbsoma/src/utils/arrow_adapter.cc
libtiledbsoma/test/test_indexer.cc
libtiledbsoma/test/unit_soma_array.cc
libtiledbsoma/test/unit_soma_collection.cc
libtiledbsoma/test/unit_soma_group.cc

**Issue and/or context:** As part of validating that libtiledbsoma does not use deprecated TileDB APIs, I tried to build it on my Windows machine with a build of TileDB with all deprecated APIs removed from the headers. I encountered a couple of errors and this PR fixes them. I also migrated two deprecated API usages in the tests.
**Changes:** With an exception in two tests, we mostly replace constructs that caused errors for MSVC with constructs that do not. The deprecated API migration is very straightforward.
Validated by successfully building libtiledbsoma and `unit_soma` on my local machine and running the tests. To prevent further regressions we should eventually work towards reenabling Windows CI in #1962.

Fix Windows build regressions and stop using deprecated TileDB APIs.

---

apis/python/src/tiledbsoma/__init__.py
apis/python/src/tiledbsoma/_collection.py
apis/python/src/tiledbsoma/_common_nd_array.py
apis/python/src/tiledbsoma/_dataframe.py
apis/python/src/tiledbsoma/_exception.py
apis/python/src/tiledbsoma/io/ingest.py

**Issue and/or context:** [sc-45626]
**Changes:** Be respectful of creation-URI semantics for multiple object stores. Error introduced on #2434.
**Notes for Reviewer:** Tested manually using object stores not applicable to this open-source repo -- hence, this repo is not the correct location for unit-test cases of this form

[python]Robust URI handling for Ingestion-performance improvement

---

.github/workflows/r-ci.yml
apis/r/tools/r-ci.sh

CI was starting to fail as GHA apparently decided to spice things up by mixing macOS hardware platforms.
**Changes:**
The stale vendored copy of `r-ci.sh` received a small, tested and already used generarlization for 'architecture', and the main YAML has three more blocks we once needed but currently do not removed.  
These changes were tested in another repo first.
[SC 46010](https://app.shortcut.com/tiledb-inc/story/46010/r-ci-update-ci-tooling-for-r)

[r,ci] Update `r-ci.sh`, remove unneeded entries from `r-ci.yml`

---

.pre-commit-config.yaml
apis/python/setup.py
apis/python/tests/test_experiment_query.py

**Issue and/or context:** As in #2473
**Changes:**

[python] Allow `obs_query=None`/`var_query=None` in `ExperimentAxisQuery`

---

apis/r/DESCRIPTION
apis/r/NAMESPACE
apis/r/NEWS.md
apis/r/R/Factory.R
apis/r/R/TileDBObject.R
apis/r/R/utils.R
apis/r/R/write_bioc.R
apis/r/R/write_seurat.R
apis/r/R/write_soma.R
apis/r/man/SOMACollectionCreate.Rd
apis/r/man/SOMACollectionOpen.Rd
apis/r/man/SOMADataFrameCreate.Rd
apis/r/man/SOMADataFrameOpen.Rd
apis/r/man/SOMADenseNDArrayOpen.Rd
apis/r/man/SOMAExperimentCreate.Rd
apis/r/man/SOMAExperimentOpen.Rd
apis/r/man/SOMAMeasurementCreate.Rd
apis/r/man/SOMAMeasurementOpen.Rd
apis/r/man/SOMASparseNDArrayCreate.Rd
apis/r/man/SOMASparseNDArrayOpen.Rd
apis/r/man/TileDBObject.Rd
apis/r/man/write_soma.Seurat.Rd
apis/r/man/write_soma.SingleCellExperiment.Rd
apis/r/man/write_soma.SummarizedExperiment.Rd
apis/r/man/write_soma_objects.Rd
apis/r/man/write_soma_seurat_sub.Rd
apis/r/tests/testthat/test-SeuratIngest.R
apis/r/tests/testthat/test-write-soma-objects.R
apis/r/tests/testthat/test-write-soma-resume.R

Implement resume-mode ingestion in the R API
This PR parallels #664; it adds support for resume-mode in factory functions, which allows `SOMA*Create()` to check for an already existing TileDB object at `uri` and if so, simply connect to it rather than try to re-create
It also adds support for resume-mode in `write_soma()` methods; these methods check the `soma_joinids` that are present in the input data and that already exist on disk, and only writes data for `soma_joinids` that are missing from disk
The following SOMA functions have been modified to with an `ingest_mode` parameter:
- `SOMADataFrameCreate()`
- `SOMASparseNDarrayCreate()`
- `SOMACollectionCreate()`
- `SOMAMeasurementCreate()`
- `SOMAExperimentCreate()`
The following methods of `write_soma()` have been modified with an …

[r] Port resume-mode to R

---

apis/r/DESCRIPTION
apis/r/NEWS.md
apis/r/R/TileDBCreateOptions.R
apis/r/man/TileDBCreateOptions.Rd
apis/r/tests/testthat/test-TileDBCreateOptions.R

Set default creation options during `TileDBCreateOptions$initialize()` instead of on-the-fly in the accessors. This allows easy serialization of `TileDBCreateOptions` with `TileDBCreateOptions$to_list()`
Also add a new `build_filters` parameter to `TileDBCreateOptions$to_list()`; if `TRUE`, builds filters with `tiledb::tiledb_filter()`, otherwise leaves as characters/lists of characters describing the filters
Also simplify a lot of the accessors/filter building methods, and move `$.dim()`, `$.attr()`, `$.build_filters()`, and `$.build_filter()` to be private methods instead of public ones

[r] Set default create options during `TileDBCreateOptions$new()`

---

apis/r/DESCRIPTION
apis/r/R/TileDBCreateOptions.R

Ensure filters are always returned in `TileDBCreateOptions$to_list()`

[r] Always return filters in `TileDBCreateOptions`

---

libtiledbsoma/src/soma/soma_dataframe.cc
libtiledbsoma/src/utils/arrow_adapter.cc
libtiledbsoma/src/utils/arrow_adapter.h

This is a follow up PR to #2481.
**Changes:**
Use `bool` instead of `tiledb_array_type_t` to indicate whether the ArraySchema should be sparse or dense.

[c++] Pass Boolean to indicate sparse or dense in ArraySchema

---

.github/workflows/r-ci.yml

Running code coverage under GitHub Actions periodically descends into instability that is both non-reproducible outside of GitHub Actions and has there (despite concerted best efforts) not been avoided. 
**Changes:**
Coverage will now run in workflow_dispatch events, i.e. when manually triggered.
[SC 46218](https://app.shortcut.com/tiledb-inc/story/46218/r-run-coverage-in-workflow-dispatch-mode-only)

[r,ci] Run coverage only on workflow_dispatch events

---

apis/r/DESCRIPTION
apis/r/NAMESPACE
apis/r/NEWS.md
apis/r/R/Factory.R
apis/r/R/TileDBObject.R
apis/r/R/utils.R
apis/r/R/write_bioc.R
apis/r/R/write_seurat.R
apis/r/R/write_soma.R
apis/r/man/SOMACollectionCreate.Rd
apis/r/man/SOMACollectionOpen.Rd
apis/r/man/SOMADataFrameCreate.Rd
apis/r/man/SOMADataFrameOpen.Rd
apis/r/man/SOMADenseNDArrayOpen.Rd
apis/r/man/SOMAExperimentCreate.Rd
apis/r/man/SOMAExperimentOpen.Rd
apis/r/man/SOMAMeasurementCreate.Rd
apis/r/man/SOMAMeasurementOpen.Rd
apis/r/man/SOMASparseNDArrayCreate.Rd
apis/r/man/SOMASparseNDArrayOpen.Rd
apis/r/man/TileDBObject.Rd
apis/r/man/write_soma.Seurat.Rd
apis/r/man/write_soma.SingleCellExperiment.Rd
apis/r/man/write_soma.SummarizedExperiment.Rd
apis/r/man/write_soma_objects.Rd
apis/r/man/write_soma_seurat_sub.Rd
apis/r/tests/testthat/test-SeuratIngest.R
apis/r/tests/testthat/test-write-soma-objects.R
apis/r/tests/testthat/test-write-soma-resume.R

**Issue and/or context:** Backport #2405 from `main` to the `release-1.10` branch. The backport bot didn't run; I don't know why not. So this is manual.
Also sets R 1.10.2 in `apis/r/DESCRIPTION` (per our [established procedure](https://github.com/single-cell-data/TileDB-SOMA/wiki/Branches-and-releases)) in an attempt to reduce CI load.

[r] Backport resume-mode for R to the `release-1.10` branch, and R 1.10.2

---

Makefile
scripts/bld

The current `build=Debug` flag to `make` controls symbols in binary artifacts. We lack a standard way to set verbosity for `cmake` so that Makefiles will show full compile lines when executed. These two things are orthogonal to one another, and they are both important.
This is crucial for customer support, e.g. on #2402 it was necessary to ask an end user to do a manual edit. This is not sustainable.
Likewise, developers doing sandbox debug often don't need full compile lines hidden from them (which is the default).
A few of us have independently modded this in sandbox. A due appreciation for use of people's time compels us to make this a resuable option in source control.
Example default output: https://gist.github.com/johnkerl/26b4ac9cdb58e17f4bc595f2c174338a
Example cmake-verbose …

[c++] Support `cmake-verbose` flag in `Makefile`

---

.github/workflows/python-so-copying.yml
.pre-commit-config.yaml
apis/python/setup.py
apis/python/src/tiledbsoma/__init__.py
apis/python/src/tiledbsoma/_experiment.py
apis/python/src/tiledbsoma/_factory.py
apis/python/src/tiledbsoma/_scene.py
apis/python/src/tiledbsoma/experimental/ingest.py
apis/python/src/tiledbsoma/io/ingest.py
apis/python/tests/test_experiment_basic.py
libtiledbsoma/src/soma/soma_experiment.cc
libtiledbsoma/src/soma/soma_experiment.h

#2484
**Changes:**
Add Python Scene class that implements the abc class in somacore.
This is a prototype for the spatial work. Do not merge into `main`.

[python][spatial] Implement Scene class in Python

---

apis/python/src/tiledbsoma/_sparse_nd_array.py

We were previously using `range(20)` as an arbitrarily high number of dimensions that people were unlikely to use. Instead, `itertools.count` provides a range-like counter that goes on forever. The function is still guaranteed to exit because there will always be a finite number of `soma_dim_{i}_domain_{endpoint}` metadata values.
---
I'm going to wait until #2446 is in to submit this, to avoid stepping on that change, but am putting it out now so that when that is in, I can just rebase and be done.

Remove arbitrary dimension limit in `used_shape`.

---

apis/r/DESCRIPTION
apis/r/NEWS.md
apis/r/R/SOMAExperimentAxisQuery.R
apis/r/R/utils.R
apis/r/tests/testthat/test-SeuratOutgest-command.R

Muffle warnings about missing command logs in `SOMAExperimentAxisQuery$to_seurat()`; warnings can be restored with `options(verbose = TRUE)`

[r] Silence missing command logs warning

---

apis/python/src/tiledbsoma/_arrow_types.py
apis/python/tests/test_registration_mappings.py
apis/python/tests/test_update_dataframes.py

**Issue and/or context:** Presented in detail on #2456.
**Changes:** As on #2456.
**Notes for Reviewer:** See also updates below.

[python] Append-mode enum bit-width mods

---

apis/python/src/tiledbsoma/io/ingest.py

**Issue and/or context:** Fixes #2499
**Changes:**
**Notes for Reviewer:** The customer callpath wasn't provided in its entirety but it's clear where the bug is

[python] Fix unbound-local error

---

.github/workflows/python-ci-packaging.yml
CONTRIBUTING.md
scripts/update-tiledb-version.py

TileDB-SOMA-Py is built and distributed in many different ways (from source, PyPI wheels, conda binaries). We want to identify any packaging-related problems immediately in the PR that generates them instead of in a nightly build or worse after the release has been made.
**Changes:**
This PR includes 2 main changes:
* The first is rebranding my existing CI pipeline to `python-ci-packaging.yml`. The original name was from my initial PR to test the shared object copying behavior (#1937, #2220). However, I had already previously expanded the pipeline to test the pure setuptools installation setup (which we use in tiledbsoma-feedstock) (#2221). With the addition of a 3rd job (below), I wanted to update the CI to better match its purpose
* The 1.9.0 release was …

[python/ci] Add CI job to test building wheel from sdist

---

apis/python/tests/test_dense_nd_array.py
apis/python/tests/test_sparse_nd_array.py
libtiledbsoma/src/soma/soma_dense_ndarray.cc
libtiledbsoma/src/soma/soma_sparse_ndarray.cc

As reported in slack, `SOMADenseNDArray`s were erroneously creating nullable columns by default.
**Changes:**
Explicitly set `ArrowSchema` flag to 0 in the `NDArray` create methods.

[c++] Explicitly set `ArrowSchema` flag to 0

---

apis/python/src/tiledbsoma/_util.py
apis/python/tests/_util.py
apis/python/tests/conftest.py
apis/python/tests/test_basic_anndata_io.py
apis/python/tests/test_experiment_query.py
apis/python/tests/test_io.py
apis/python/tests/test_platform_config.py
apis/python/tests/test_registration_mappings.py
apis/python/tests/test_registration_signatures.py
apis/python/tests/test_update_dataframes.py
apis/python/tests/test_update_matrix.py

**Issue and/or context:** Proposed for inclusion in #2521
**Changes:**
- More descriptive `pytest.fixture` names
- "Manually" expose each `TestCase` member as a `fixture`, removing automatic fixture creation hack using `globals()` ([diff](https://github.com/single-cell-data/TileDB-SOMA/commit/98bcc9736967e3b7c228d9b867964ccc703bdbc9#diff-8656b690b8df46bf6432c6aabffe4b3b71e35fdea3dc0feda652b660224b2055L80-L101))
- Factor/Rename a couple test helpers (e.g. `maybe_raises`)
Hopefully this strikes a reasonable balance between "discoverability of `pytest.fixture`s defined in conftest.py" vs. having to spell it out at each fixture-use site.
The "auto-generated fixtures for each `TestCase` field" bit in particular was too magical, I've unrolled it here.

test fixture/helper cleanup

---

apis/r/DESCRIPTION
apis/r/NEWS.md
apis/r/R/SOMADataFrame.R
apis/r/man/SOMADataFrame.Rd
apis/r/tests/testthat/test-SOMADataFrame.R
apis/r/tests/testthat/test-write-soma-objects.R

New `$shape()` method for `SOMADataFrame` that throws a not-yet-implemented error. This is implemneted as a custom error instead of `.NotYetImplmented()` because:
- `.NotYetImplemented()` does not understand R6 methods and produces a janky error message
```R
Error: `$` is not yet implmeneted`sdf` is not yet implemented`shape()` is not yet implemented
```
- `.NotYetImplemented()` throws a simple error (same as `stop()`) which is harder to catch; I'm custom-classing this error as `notYetImplementedError` so that any `tryCatch()` can catch this and only this
New SOMA methods:
- `SOMADataFrame$shape()`: throw a `notYetImplementedError`
This parallels the Python's API #2533

[r] Ensure `SOMADataFrame$shape()` throws a not-yet-implemented error

---

apis/python/src/tiledbsoma/_tdb_handles.py
apis/python/tests/test_dataframe.py

As per the SOMA spec, `DataFrame`s do not have `shape` implemented.
This parallels the R API's https://github.com/single-cell-data/TileDB-SOMA/pull/2531.
**Changes:**
Raise `NotImplementedError` for `DataFrame.shape`.

[python] Raise `NotImplementedError` for `DataFrame.shape`

---

apis/r/DESCRIPTION
apis/r/NEWS.md
apis/r/R/SOMAExperimentAxisQuery.R

SeuratObject v5.0.2 throws a warning when the layer requested does not exist. During SOMA -> `Seurat` outgestion, this occurs when running `SeuratObject::.CalcN` eg.
```r
> obj <- query$to_seurat(X_layers = c('data' = 'data'))
Warning: Layer counts isn't present in the assay object; returning NULL
```
Since the results of `.CalcN()` should already exist in the SOMA, we can disable this processing and suppress the warning

[r] Suppress Warnings on SOMA -> `Seurat` Outgestion

---

.github/workflows/r-ci.yml
apis/r/DESCRIPTION
apis/r/NEWS.md
apis/r/R/SOMAExperimentAxisQuery.R
apis/r/tools/install-tiledb-r.R

Update `r-ci.yml` to respect the doublepin of tiledb-r in `DESCRIPTION`; this is accomplished by doing the following:
- setting environment variable `R_REMOTES_UPGRADE` to `"never"` to prevent upgrading of dependencies in `tools/r-ci.sh install_all`
- setting `tiledb-inc.r-universe.dev` as an additional repo for installing dependencies
- parsing `apis/r/DESCRIPTION` to find constraints on tiledb-r
- searching through all repos to find all accessible versions of tiledb-r
- identifying the version of tiledb-r that matches our constraints
- installing upstream dependencies of tiledb-r from all accessible repos
- installing the correctly-constrained version of tiledb-r

[r/ci] Utilize pin of tiledb-r during install

---

apis/python/src/tiledbsoma/_dense_nd_array.py
apis/python/tests/test_regression.py

**Issue and/or context:** #2537
**Changes:**
When writing a dense array, this change will check if the data is neither row major nor column major and explicitly set it to be row-major before writing.

[python] Fix write from array that is not row or column order

---

.github/workflows/python-ci-minimal.yml
.github/workflows/r-ci.yml

**Issue and/or context:** #2230
**Changes:**
- Convert `paths-ignore` to `paths` ([GHA docs](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#onpushpull_requestpull_request_targetpathspaths-ignore)), in order to sequence inclusions and exclusions, e.g. (adapted from `r-ci.yml`):
```yml
- '**'                          # trigger GHA on all paths, by default
- '!.github/**'                 # override: exclude changes to .github
- '.github/workflows/r-ci.yml'  # override²: un-exclude changes to current workflow file
```
- Add exclusions to Python/R PR GHAs (`docs/**`, `**.md`)
I tested the new python-ci-minimal.yml rules at [test-paths.yml](https://github.com/ryan-williams/TileDB-SOMA/actions/workflows/test-paths.yml) (in my fork): …

Restrict R/Python GHAs from running on irrelevant `{.github,doc}` changes

---

apis/python/src/tiledbsoma/io/ingest.py
doc/README.md
doc/local-build.sh
doc/requirements_doc.txt
doc/source/conf.py
doc/source/python-tiledbsoma-io.rst
doc/source/python-tiledbsoma-logging.rst

Also seems to fix #2474; best guess is newer sphinx allows missing newline before `Lifecycle:`?
**Issue and/or context:** #2474
**Changes:**
- Update doc deps
- Update `local-build.sh`
- Fix `from_h5ad` docstr / rtd rendering ([current version](https://tiledbsoma.readthedocs.io/en/latest/_autosummary/tiledbsoma.io.from_h5ad.html#tiledbsoma.io.from_h5ad) has broken formatting, missed args)

[python] Update `doc/` README/deps, fix warnings, `from_h5ad` formatting

---

.github/workflows/r-ci.yml
.github/workflows/r-python-interop-testing.yml
apis/r/tools/install-tiledb-r.R

Follow-up to #2540 
bspm does not respect the `repos` argument in `install.packages()`; this is an issue where the valid version of tiledb-r is on R-universe, but not on CRAN. In this situation, bspm will still install from APT rather than the repository specified in `install.pacakges(repos = )`
To get around this, I've added a check that asks
- is bspm installed
- is the valid tiledb-r avaialble only on alternate repos
If both of those are true, disable bspm for installing tiledb-r; bspm is still used for upstream dependencies of tiledb-r
Note, this has the unfortunate side-effect of installing tiledb-r from source on Linux CI. This is because Linux CI is currently using 22.04 jammy while [R-universe is now building binaries for 24.04 noble](https://tiledb-inc.r-universe.dev/tiledb). As …

[r/ci] Add check to disable BSPM in R CI

---

.github/workflows/python-ci-packaging.yml
apis/python/setup.py
apis/r/DESCRIPTION
apis/r/tools/get_tarball.R
libtiledbsoma/cmake/Modules/FindTileDB_EP.cmake

**Issue and/or context:** [sc-46600]
**Changes:**

Use core 2.23.0, TileDB-Py 0.29.0, TileDB-R 0.27.0

---

apis/python/src/tiledbsoma/__init__.py
apis/python/src/tiledbsoma/_sparse_nd_array.py
doc/source/python-tiledbsoma.rst

**Issue and/or context:** #2502
**Changes:**
- Export `SparseNDArrayRead` from `tiledbsoma` module
- Include `SparseNDArrayRead` in docs ([tiledbsoma.readthedocs.io/en/latest/python-tiledbsoma.html#classes](https://tiledbsoma.readthedocs.io/en/latest/python-tiledbsoma.html#classes))
- Are there any concerns about adding a new class to the `tiledbsoma` top-level/module API?
- This is currently based on #2538, should auto-redirect to `main` once that's merged.

[python] Export `tiledbsoma.SparseNDArrayRead`, include in module doc site

---

.github/workflows/r-ci.yml
.github/workflows/r-python-interop-testing.yml
apis/r/DESCRIPTION
apis/r/R/SOMAExperimentAxisQuery.R
apis/r/tools/install-tiledb-r.R

**Issue and/or context:** Following our [established procedure](https://github.com/single-cell-data/TileDB-SOMA/wiki/Branches-and-releases), I am working on tiledbsoma 1.11 today
[sc-46600]
**Changes:**
@mojaveazure I am following https://github.com/single-cell-data/TileDB-SOMA/wiki/Branches-and-releases#incrementing-core-versions
However, since that was updated we do have #2540 and #2546 on `main`; I'm not sure what's the right thing to do here on the `release-1.10` branch, as I am going to create a `release-1.11` branch today -- @mojaveazure let's work together on this.

[r] Two-sided R pin for `release-1.10` branch; backport #2540, #2546, #2549

---

apis/python/setup.py
apis/python/src/tiledbsoma/experimental/ingest.py

- Fix `setup.py` to reference `somacare` from `dark/query-part-1` branch
- Fix typo in the import section of `experimental/ingest.py`
**Changes:**

Add minor typo related bug fixes

---

libtiledbsoma/src/utils/arrow_adapter.cc

Found while doing analysis on [sc-47279].
In that story we have a simple repro including
<details>
```
context = tiledbsoma.SOMATileDBContext(tiledb_config = {
"py.init_buffer_bytes": 4 * 1024**3,
"py.deduplicate": "true",
"soma.init_buffer_bytes": soma_init_buffer_bytes,
"sm.mem.reader.sparse_global_order.ratio_array_data": 0.3,
"sm.consolidation.total_buffer_size": 4 * 1024**3,
"sm.compute_concurrency_level": cpu_count,
"sm.io_concurrency_level": cpu_count,
})
platform_config =  {
"tiledb": {
"create": {
"capacity": 2**16,
"dims": {
"soma_dim_0": {"tile": 2048, "filters": [{"_type": "ZstdFilter", "level": compression_level}]},
"soma_dim_1": {"tile": 2048, "filters": ["ByteShuffleFilter", {"_type": "ZstdFilter", "level": compression_level}]},
},
"attrs": {"soma_data": {"filters": …
```

[c++] Allow `row-major` and `col-major` in `SOMArray::create`

---

.readthedocs.yml
apis/python/setup.py
apis/python/version.py

[`1.5.0`](https://github.com/single-cell-data/TileDB-SOMA/tree/1.5.0) (Nov '23) is typically the most recent tag that's an ancestor of `main`, because subsequent release tags all exist on release branches.
This means local installs get versions like `1.5.0rc0.post332.dev6296020074`, adapted from `git describe` (the `dev` number is the Git short SHA, `git log -1 --format=%h`, converted to base 10, for [PEP440](https://peps.python.org/pep-0440/)-compliance).
It's a little weird to see `1.5.0*` on dev installs, and it crashes in shallow clones (which GHA / RTD use by default).
If `git describe` returns `1.5.0` as the nearest tagged ancestor, synthesize a more meaningful version number:
1. Find the latest release tag in the local repo (or tracked remote, if there are no local tags, e.g. in …

[python] Prototype: better version numbers during development

---

apis/python/src/tiledbsoma/_util.py
apis/python/src/tiledbsoma/options/_tiledb_create_options.py
apis/python/src/tiledbsoma/pytiledbsoma.cc
apis/python/src/tiledbsoma/soma_dataframe.cc
apis/python/src/tiledbsoma/soma_dense_ndarray.cc
apis/python/src/tiledbsoma/soma_sparse_ndarray.cc
apis/python/tests/test_dataframe.py
apis/python/tests/test_platform_config.py
libtiledbsoma/src/CMakeLists.txt
libtiledbsoma/src/external/include/nlohmann/json.hpp
libtiledbsoma/src/soma/soma_collection.cc
libtiledbsoma/src/soma/soma_collection.h
libtiledbsoma/src/soma/soma_dataframe.cc
libtiledbsoma/src/soma/soma_dataframe.h
libtiledbsoma/src/soma/soma_dense_ndarray.cc
libtiledbsoma/src/soma/soma_dense_ndarray.h
libtiledbsoma/src/soma/soma_experiment.cc
libtiledbsoma/src/soma/soma_experiment.h
libtiledbsoma/src/soma/soma_measurement.cc
libtiledbsoma/src/soma/soma_measurement.h
libtiledbsoma/src/soma/soma_sparse_ndarray.cc
libtiledbsoma/src/soma/soma_sparse_ndarray.h
libtiledbsoma/src/utils/arrow_adapter.cc
libtiledbsoma/src/utils/arrow_adapter.h
libtiledbsoma/test/unit_soma_collection.cc
libtiledbsoma/test/unit_soma_dataframe.cc
libtiledbsoma/test/unit_soma_dense_ndarray.cc
libtiledbsoma/test/unit_soma_sparse_ndarray.cc

#2520
**Changes:**
* Add `column-major` as valid column ordering value
* Add missing `dense_nd_array_dim_zstd_level` option
* `tiledb_schema_from_arrow_schema` needs to take in additional `std::string soma_type` argument to ensure `PlatformConfig` parameters `dataframe_dim_zstd_level`, `dense_nd_array_dim_zstd_level`, and `sparse_nd_array_dim_zstd_level` get applied correctly
* Use the default `PlatformConfig` constructor if one has not been provided, not `std::nullopt`. This is why the default levels were not getting set correctly
* Apply default filter zstd (at TileDB default level) to attributes
* Filter names coming in from R API need to be respected
* `PlatformConfig` should be representable in JSON format; options for `FilterList`s should take in JSON …

[c++] `PlatformConfig` refactoring

---

apis/r/DESCRIPTION
apis/r/NEWS.md
apis/r/R/SOMADataFrame.R
apis/r/R/TileDBGroup.R
apis/r/R/TileDBObject.R
apis/r/R/write_seurat.R
apis/r/R/write_soma.R
apis/r/man/TileDBObject.Rd
apis/r/tests/testthat/test-SeuratIngest.R

Internal timestamps of not `NULL` cause `$reopen()` to fail when reopening in `"WRITE"` mode; this PR allows `$reopen()` to do one of the following:
- set the time to the current time (required for `$reopen("WRITE")`)
- restore the time to the previously set timestamp
- open at a custom timestamp by passing a `POSIXct` object
Currently, the existing timestamp causes an error when reopening for write and modifying an existing array (eg. schema evolution). For example
```r
library(SeuratObject)
data(pbmc_small)
uri <- "/path/to/uri"
tiledbsoma::write_soma(pbmc_small, uri = uri)
exp <- tiledbsoma::SOMAExperimentOpen(uri)
obs_df <- as.data.frame(exp$obs$read()$concat())
obs_df$colors <- sample(
c("red", "blue", "green"),
size = ncol(pbmc_small),
replace = TRUE
)
obs_df$soma_joinid <- …
```

[r] Better handling of timestamps in `$reopen()`

---

apis/r/tests/testthat/test-SOMADataFrame.R

**Issue and/or context:** It never made sense to set row/cell order in array-schema creation. But https://github.com/TileDB-Inc/TileDB/pull/4973 recently formalized this.
We shouldn't ask for unordered at schema-create time.
See also: https://github.com/TileDB-Inc/TileDB-Py/pull/1970
Note the above core change isn't in 2.23, only in `dev` -- but https://github.com/TileDB-Inc/tiledbsoma-feedstock has nightlies which point at core dev: https://github.com/jdblischak/centralized-tiledb-nightlies/issues/6#issuecomment-2115841783
**Changes:**

[r] Fix builds against current TileDB Embedded 

---

apis/r/tests/testthat/test-SOMADenseNDArray.R
apis/r/tests/testthat/test-SOMASparseNDArray.R

"UNORDERED" is no longer a permitted cell order value on schema creation.
**Changes:**
This follows #2573 and applies a similar change to the sparse and dense array cases.
[SC 47577](https://app.shortcut.com/tiledb-inc/story/47577/r-no-more-unordered-cell-order)

[r] Switch 'UNORDERED' cell order to 'ROW_MAJOR' on schema creation

---

apis/python/notebooks/tutorial_soma_append_mode.ipynb
doc/source/notebooks/tutorial_soma_append_mode.ipynb

**Issue and/or context:** #2569
**Changes:**
- Add "Tutorial: TileDB-SOMA append-mode" notebook (created by @johnkerl a while back, mistakenly not published)
- RTD automatically picks it up; preview: https://tiledbsoma.readthedocs.io/en/rw-apptut/notebooks/tutorial_soma_append_mode.html

Tutorial: TileDB-SOMA append-mode

---

apis/python/version.py

**Issue and/or context:** #2588
**Changes:**
Make sure "version inference from Git tags" fails silently/gracefully when run outside of a Git clone (e.g. during wheel build).
[Here](https://github.com/single-cell-data/TileDB-SOMA/actions/runs/9161139637) is a passing "sdist & wheel build" GHA dispatched from this branch.

[python] `version.py`: guard `git` calls during wheel builds (sans `.git`)

---

.github/workflows/python-ci-packaging.yml

The recent update to `version.py` broke package builds that rely on `RELEASE-VERSION` outside the context of a Git repo
xref: #2588, https://github.com/single-cell-data/TileDB-SOMA/pull/2563, https://github.com/TileDB-Inc/tiledbsoma-feedstock/issues/153#issuecomment-2120605388
**Changes:**
This is exactly the type of build error that my packaging CI workflow is supposed to catch. I've updated it so that it now extracts the sdist outside of the Git repo that was cloned, which should catch this type of error in the future
The packaging CI is expected to fail. I will rebase it after we merge the fix from @ryan-williams

[python/ci] Build wheel from sdist outside of Git repository

---

.github/workflows/python-packaging.yml

**Issue and/or context:** Just a drive-by after a mention in Slack by @jdblischak 
**Changes:**

[python/ci] Use `macos-11` -> `macos-12` for `python-packaging.yml`

---

apis/python/src/tiledbsoma/__init__.py
apis/python/src/tiledbsoma/_dataframe.py
apis/python/src/tiledbsoma/_sparse_nd_array.py
apis/python/src/tiledbsoma/options/__init__.py
apis/python/src/tiledbsoma/options/_tiledb_create_options.py
apis/python/src/tiledbsoma/soma_array.cc
apis/python/tests/test_sparse_nd_array.py
libtiledbsoma/src/soma/managed_query.cc
libtiledbsoma/src/soma/managed_query.h
libtiledbsoma/src/soma/soma_array.cc
libtiledbsoma/src/soma/soma_array.h

**Issue and/or context:** #2054
The C++-ification of the SOMA API now allows us to utilize global writes when writing to sparse arrays, thus saving time by skipping the coordinate sorting step when the coordinates are already known to be ordered.
**Changes:**
- Add `sort_coords` setting in the `PlatformConfig`, where by default, it is set to `False` and thus still uses `TILEDB_UNORDERED`
- Add `sort_coords` parameter to `SOMAArray::write` and `ManagedQuery::submit_write`

[c++/python] Enable optional global-order writes for sparse arrays

---

libtiledbsoma/src/soma/soma_context.h
libtiledbsoma/test/unit_soma_array.cc

The argument to a `SOMAContext` is a `tiledb::Config` object (as represent by a `map<string, string>`), not a `PlatformConfig` object. `PlatformConfig` is for configuring `SOMAArray`s with settings that cannot be represented by an `ArrowSchema`.
**Changes:**
- Rename argument name `platform_config` to `tiledb_config`
- Add explicit check to ensure passed config settings are honored in `SOMAContext`

[c++] Correct `platform_config` to `tiledb_config`

---

libtiledbsoma/src/utils/arrow_adapter.cc

**Changes:**
Allow both "NONE" and "NOOP" as acceptable strings to map to `TILEDB_FILTER_NONE`.

[c++] Also map "NONE" to `TILEDB_FILTER_NONE`

---

apis/python/src/tiledbsoma/soma_dataframe.cc
apis/python/tests/test_dataframe.py
libtiledbsoma/src/soma/column_buffer.h
libtiledbsoma/src/soma/soma_array.cc
libtiledbsoma/src/soma/soma_array.h
libtiledbsoma/src/utils/arrow_adapter.cc

#2511
**Changes:**
We only dealt with large string and binary before, which use 64-bit offsets. This also supports small string and binary, which use 32-bit offsets.

[c++] Handle 32-bit string and binary in writes

---

apis/python/notebooks/tutorial_soma_append_mode.ipynb

**Issue and/or context:** #2569 / https://github.com/chanzuckerberg/cellxgene-census/issues/1132, builds on #2571
**Changes:**
Extend notebook to demonstrate "atlas"-model ingestion (no prior `Experiment`, one "register" call, multiple "from"s)
- [RTD preview](https://tiledbsoma.readthedocs.io/en/rw-apptut/notebooks/tutorial_soma_append_mode.html#Ingesting-multiple-datasets-to-a-SOMA-Experiment)
- [Direct link](https://github.com/single-cell-data/TileDB-SOMA/blob/6a878db910b3d0601475bbff88ee231ad8360c15/apis/python/notebooks/tutorial_soma_append_mode.ipynb) to .ipynb on this branch (rendered more nicely than in PR view here)
- [nbviewer.org link to new section](https://nbviewer.org/github/single-cell-data/TileDB-SOMA/blob/6a878db910b3d0601475bbff88ee231ad8360c15/api …

[python] Append-mode tutorial: "atlas model"

---

apis/python/version.py

**Issue and/or context:** Manual backport of #2590 to `release-1.11` following https://github.com/single-cell-data/TileDB-SOMA/pull/2590#issuecomment-2122702827

[Backport release-1.11] [python] `version.py`: guard `git` calls during wheel builds (sans `.git`)

---

apis/r/DESCRIPTION
apis/r/NEWS.md
apis/r/R/SOMADataFrame.R
apis/r/R/TileDBGroup.R
apis/r/R/TileDBObject.R
apis/r/R/write_seurat.R
apis/r/R/write_soma.R
apis/r/man/TileDBObject.Rd
apis/r/tests/testthat/test-SeuratIngest.R

Manual backport of #2497. I added the `backport release-1.11` tag there and backport didn't run; I don't know why not.

[Backport release-1.11] [r] Better handling of timestamps in `$reopen()`

---

.github/workflows/python-ci-packaging.yml

Backport #2589 to `release-1.11`

[Backport release-1.11] [python/ci] Build wheel from sdist outside of Git repository

---

libtiledbsoma/src/utils/arrow_adapter.cc

Manually backport #2599 to `release-1.11`
https://github.com/single-cell-data/TileDB-SOMA/pull/2599#issuecomment-2122703348

[Backport release-1.11] [c++] Also map "NONE" to `TILEDB_FILTER_NONE` (#2599)

---

apis/python/version.py

**Issue and/or context:** https://github.com/TileDB-Inc/tiledbsoma-feedstock/pull/157, #2560, #2563, #2588, #2590
**Changes:**
- `lines`/`line` helpers catch `CalledProcessError`s, return `None`
- Git-version computations they are used in are all optional / best-effort
- Don't `raise RuntimeError` if Git remote tags aren't found, or if multiple lines of stdout are returned from commands expected to return 1; just `return None`.
**Notes for Reviewers:**
Tested in a couple configurations locally:
- normal Git clone
- "wheel build" (not in a Git clone)
- shallow Git clone, with a remote containing release tags
- shallow Git clone, with a remote containing no release tags
"sdist & wheels" GHA is also running, [here](https://github.com/single-cell-data/TileDB-SOMA/actions/runs/9195292651).

`version.py`: prevent Git version computation from `raise`ing

---

apis/r/R/SOMAExperimentAxisQuery.R
apis/r/R/utils-matrixZeroBasedView.R
apis/r/man/SOMAExperimentAxisQuery.Rd
apis/r/man/matrixZeroBasedView.Rd

Running `R CMD check --as-cran` (or its equivalent forms) was nagging over four `\link{}` entries missing the leading backslashes (as a follow-up from R now checking for stray pairs of `{ }`).
**Changes:**
Corrected in R files, and Rd files re-rerendered.
No code changes. No test changes.
[SC 47990](https://app.shortcut.com/tiledb-inc/story/47990/r-minor-formatting-correction-got-four-rd-help-files)

[r] Correct four \link{} references in help pages

---

apis/r/.Rbuildignore
apis/r/vignettes/soma-experiment-queries.Rmd
apis/r/vignettes/soma-objects.Rmd
apis/r/vignettes/soma-reading.Rmd

Running R CMD check under r-devel (for an unrelated issue: our use of the dual inequality in Imports actually lead to me filing an upstream R bug ([#18735](https://bugs.r-project.org/show_bug.cgi?id=18735)) for which I wanted assert the fix) flagged that three URLs (pointing at the same spot) had change with Paul handing SeuratObject over to Rahul.
**Changes:**
A simple update of the URL in three vignettes.  No new code, no new tests.
[SC 48040](https://app.shortcut.com/tiledb-inc/story/48040/r-minor-url-rot-in-vignette-documentation)

[r] Update changed URL in three vignette files

---

.github/workflows/python-packaging.yml

Our current package-release CI is broken. It requires manual wheel-publish as at
https://github.com/single-cell-data/TileDB-SOMA/wiki/PyPI-packaging-notes
CI failures are like
https://github.com/single-cell-data/TileDB-SOMA/actions/runs/9189052757
following the well-intentioned but fateful #2491.
Also nightly wheel-build failures such as #2630.
Debugging reveals:
* #2491 moved Python wheel-builds from macos 11 and 12 to 14 and 12
* Why we did that: GitHub Actions is deprecating macos 11 runners
* Printing `python -c 'from distutils import util; print(util.get_platform())'` at build-wheel time and smoke-test-wheel time
* Build-wheel time on macos 14: this reports (!) `macosx-10.9-universal2`
* https://github.com/single-cell-data/TileDB-SOMA/actions/runs/9193078472/job/25283290847#step:4:20 …

[python/ci] Stop wheel-smoke-test failures for MacOS > 11

---

.github/workflows/python-packaging.yml

**Issue and/or context:** #2634
Several improvements to `python-packaging.yml` ("sdist & wheels" GHA):
- Parallelize over Python versions (3x4 4-minute jobs instead of 3 4x4-minute jobs)
- Restore/Add wheel "smoke tests"
- Restore macOS wheel smoke-test (x86 only; ~ARM still WIP~ now includes ARM, thanks @dudoslav / #2641)
- Add smoke-tests for Python 3.10 (in addition to 3.11), across 3 {os,arch}'s
- Only download necessary artifacts in each job (previously each smoke-test downloaded wheels for all {os,arch,python} combos)
[![Screenshot 2024-05-24 at 12 45 28 AM](https://github.com/single-cell-data/TileDB-SOMA/assets/465045/f7ff2ba5-5c84-469c-b89c-d11b6ef99ae3)](https://github.com/single-cell-data/TileDB-SOMA/actions/runs/9212122517) …

Restore/add wheel smoke-tests, parallelize wheel builds

---

libtiledbsoma/src/utils/arrow_adapter.cc
libtiledbsoma/src/utils/arrow_adapter.h

https://github.com/single-cell-data/TileDB-SOMA/issues/2644
* Derefencing and passing a `Context` object into `_create_dim_aux` prematurely decrements a reference count to the `Context` which then garbage collects the object. When we attempt to reference the `shared_ptr<Context>` again, it is invalid and segfaults
* Fixes intermittent bug in Release mode that is consistently reproducible in Debug mode

[c++] Pass in a `shared_ptr<Context>` to `_create_dim_aux`

---

apis/python/README.md

[python] Include guidance for older CPU architectures

---

apis/python/tests/test_dataframe.py
libtiledbsoma/src/soma/column_buffer.h

This bug was caught when C++-ifying the SOMA R API. https://github.com/single-cell-data/TileDB-SOMA/pull/2629 originally contains the bug fix but has now separated out into this new PR.
**Changes:**
* In Arrow, the validity buffer is stored as bitpacked buffers whereas in TileDB, they are stored as uint8_t buffers. We need to properly unpack the bits and cast them to uint8_t on writes
* Although we have unit tests in the SOMA Python API for nullable attributes in several areas, they somehow happened to write and read back fine so this issue went uncaught. This PR adds a new unit test that fails currently on main but is fixed by this PR

[c++] Fix validity buffer bit unpacking

---

apis/python/README.md

Backport #2643 to `release-1.11`.
I don't know why the backport bot didn't run on #2643.

[Backport release-1.11] [python] Include guidance for older CPU architectures

---

apis/python/src/tiledbsoma/_util.py

This fix has been tested against the code below and confirmed passing:
```
import pandas as pd
import pyarrow as pa
import tiledbsoma 
from cellxgene_census_builder.build_soma.globals import CENSUS_OBS_TABLE_SPEC
df_dict = {'cell_type_ontology_term_id': {0: 'CL:0000192', 1: 'CL:0000192', 2: 'CL:0000192', 3: 'CL:0000192', 4: 'CL:0000192', 5: 'CL:0000192', 6: 'CL:0000192', 7: 'CL:0000192', 8: 'CL:0000192', 9: 'CL:0000192', 10: 'CL:0000192', 11: 'CL:0000192', 12: 'CL:0000192', 13: 'CL:0000192', 14: 'CL:0000192', 15: 'CL:0000192'}, 'assay_ontology_term_id': {0: 'EFO:0009922', 1: 'EFO:0009922', 2: 'EFO:0009922', 3: 'EFO:0009922', 4: 'EFO:0008931', 5: 'EFO:0008931', 6: 'EFO:0008931', 7: 'EFO:0008931', 8: 'EFO:0009922', 9: 'EFO:0009922', 10: 'EFO:0009922', 11: …
```

[python] Correctly handle string vs large string in `Enumeration`s

---

.github/workflows/python-ci-single.yml
.github/workflows/r-ci.yml
.github/workflows/r-python-interop-testing.yml
libtiledbsoma/src/soma/column_buffer.cc
libtiledbsoma/src/soma/column_buffer.h

**Issue and/or context:** As on #2682: switch the default from small to medium. The small/CI regime is preserved via opt-in environment variable.
See also https://github.com/single-cell-data/TileDB-SOMA/pull/531 wherein I found that even 512MB was too big for Windows CI -- which is why on this PR I have explicit CI logic.

[c++] Improve default buffer sizes

---

apis/r/DESCRIPTION

Following https://github.com/TileDB-Inc/tiledbsoma-feedstock/issues/168#issuecomment-2152804811

[r] Use `arrow` minimum 14, not 15

---

README.md

As noted in #2694 the README.md points to a stale ci yaml file for Python.
**Changes:**
The link has been updated to show the status of the 'Python CI (Full)' job
[SC 49175](https://app.shortcut.com/tiledb-inc/story/49175/doc-ci-readme-md-has-stale-link-to-old-python-ci-yaml-results-state)

[doc] Update README.md badge for Python CI (closes #2694) [ci skip]

---

apis/r/DESCRIPTION
apis/r/NEWS.md

[r] R versioning past `release-1.12` branch

---

apis/python/src/tiledbsoma/_dataframe.py
apis/python/src/tiledbsoma/_general_utilities.py
apis/python/src/tiledbsoma/options/_soma_tiledb_context.py
apis/python/src/tiledbsoma/soma_context.cc
apis/python/tests/test_context.py

[sc-49124]
Deprecating usage of `tiledb.Ctx` for users is necessary for the complete removal of tiledb-py. Internally, the codebase now passes around a `TileDBSOMAContext.native_context` which is a C++ `SOMAContext` binding. We no longer use `tiledb.Ctx` anywhere.
**Changes:**
* Deprecate `tiledb_ctx` as an argument into the constructor and `replace`
* Deprecate `tiledb_ctx` as an attribute getter
* Use `tiledb_config` as an alternative 
I have set the deprecation for 1.14.

[python] Deprecate `tiledb_ctx` usage in `TileDBSOMAContext`

---

libtiledbsoma/src/utils/arrow_adapter.cc

* Fixes https://github.com/TileDB-Inc/tiledbsoma-feedstock/issues/170
* Basically a recurrence of https://github.com/single-cell-data/TileDB-SOMA/pull/2609
* There, the `fmt::format` argument which was not `formattable` was of type `json`
* Here, the `fmt::format` argument which is not `formattable` is of core type `tiledb_datatype_t` which is a C++ int-backed `enum` type
* Open question in my mind: why is that these issues compile OK in our TileDB-SOMA repo CI but fail to compile in the nightlies? I'd love to surface these errors sooner.

[c++] Fix a nightly-build issue

---

apis/python/src/tiledbsoma/_dense_nd_array.py
libtiledbsoma/src/soma/soma_collection.cc
libtiledbsoma/src/soma/soma_collection.h
libtiledbsoma/src/soma/soma_experiment.cc
libtiledbsoma/src/soma/soma_experiment.h
libtiledbsoma/src/soma/soma_group.cc
libtiledbsoma/src/soma/soma_group.h
libtiledbsoma/src/soma/soma_measurement.cc
libtiledbsoma/src/soma/soma_measurement.h
libtiledbsoma/test/unit_soma_collection.cc

https://github.com/single-cell-data/TileDB-SOMA/issues/2509
**Changes:**
- Add `timestamp`, `result_order`, and `platform_config` parameters to `SOMACollection::add_new_{soma_object}`
- Add `X`, `obs`, and `vars` setters

[c++] Add missing `SOMACollection` getters and setters

---

apis/r/R/BlockwiseIter.R
apis/r/R/SOMASparseNDArrayRead.R
apis/r/man/BlockwiseReadIterBase.Rd
apis/r/man/BlockwiseSparseReadIter.Rd
apis/r/man/BlockwiseTableReadIter.Rd
apis/r/man/IntIndexer.Rd
apis/r/man/SOMASparseNDArrayBlockwiseRead.Rd
apis/r/man/SOMASparseNDArrayRead.Rd
apis/r/man/roxygen/templates/param-blockwise-iter.R
apis/r/man/roxygen/templates/param-repr-read.R
apis/r/tests/testthat/test-Blockwise.R

Connect the re-indexer to the blockwise iterator, allowing reads to be re-indexed on-the-fly. This PR parallels #1792 and completes #2152 and #2637; in addition, provides new shorthand for `reindex_disable_on_axis`:
- `TRUE`: disable re-indexing on all axes
- `FALSE`: re-index on all axes
- `NA`: re-index only on major axis, disable re-indexing on all axes (default)
`BlockwiseTableReadIter$concat()` and `BlockwiseSparseReadIter$concat()` are disabled when re-indexing is requested (paralleling Python)
`BlockwiseSparseReadIter` now accepts `repr = "R"` or `repr = "C"` under certain circumstances:
- axis 0 (`soma_dim_0`) must be re-indexed to allow `repr = "R"`
- axis 1 (`soma_dim_1`) must be re-indexed to allow `repr = "C"`
`repr` of `"T"` is allowed in all circumstances and continues to be …

[r] Connect re-indexer to blockwise iterator

---

libtiledbsoma/src/soma/soma_array.h
libtiledbsoma/src/soma/soma_collection.cc
libtiledbsoma/src/soma/soma_collection.h
libtiledbsoma/src/soma/soma_experiment.cc
libtiledbsoma/src/soma/soma_experiment.h
libtiledbsoma/src/soma/soma_group.cc
libtiledbsoma/src/soma/soma_group.h
libtiledbsoma/src/soma/soma_measurement.cc
libtiledbsoma/src/soma/soma_measurement.h
libtiledbsoma/src/soma/soma_object.h
libtiledbsoma/test/unit_soma_collection.cc
libtiledbsoma/test/unit_soma_group.cc

This work is originally a part of https://github.com/single-cell-data/TileDB-SOMA/pull/2675
**Changes:**
- Replace contents of `SOMACollection::get` with a call to `SOMAObject::open`
- Rename `SOMAGroup::member_to_uri_mapping` to `SOMAGroup::members` (this is a getter that returns a map of the child member's name and its associated `SOMAGroupEntry`)
- Refactor `SOMAGroup::members` mapping to store `SOMAGroupEntry` values. `SOMAGroupEntry` stores the URI of the child member and the type of `SOMAObject` it is. This type info gets passed into `SOMAObject::open` (via `SOMACollection::get`) to reduce the number of unnecessary `tiledb::open` calls
- Add an iterator for `SOMACollection`
- Add missing documentation
- Rethrow `TileDBError` as `TileDBSOMAError` where …

[c++] More `SOMAGroup` refinements

---

apis/python/src/tiledbsoma/common.cc
apis/python/src/tiledbsoma/common.h
apis/python/src/tiledbsoma/pytiledbsoma.cc
apis/python/src/tiledbsoma/soma_array.cc
apis/python/src/tiledbsoma/soma_collection.cc
apis/python/src/tiledbsoma/soma_group.cc
libtiledbsoma/src/soma/soma_group.h
libtiledbsoma/test/unit_soma_collection.cc

These changes are on top of https://github.com/single-cell-data/TileDB-SOMA/pull/2731
**Changes:**
- Add bindings for `SOMAGroup` which gets inherited by `SOMACollection`, `SOMAMeasurement`, and `SOMAExperiment`
- Add bindings for `URIType` enumeration
- Move shared metadata functions used by both `SOMAArray` and `SOMAGroup` into `common.{cc,h}`
- Rename `reader` to `array` in `SOMAArray`

[python] Add `pybind11` bindings for `SOMAGroup` 2/5

---

apis/python/src/tiledbsoma/_collection.py
apis/python/src/tiledbsoma/_dataframe.py
apis/python/src/tiledbsoma/_dense_nd_array.py
apis/python/src/tiledbsoma/_experiment.py
apis/python/src/tiledbsoma/_factory.py
apis/python/src/tiledbsoma/_measurement.py
apis/python/src/tiledbsoma/_sparse_nd_array.py
apis/python/src/tiledbsoma/_tdb_handles.py
apis/python/src/tiledbsoma/_tiledb_object.py
apis/python/src/tiledbsoma/soma_array.cc
apis/python/src/tiledbsoma/soma_collection.cc
apis/python/src/tiledbsoma/soma_group.cc
apis/python/tests/test_basic_anndata_io.py

This is on top of https://github.com/single-cell-data/TileDB-SOMA/pull/2732
**Changes:**
- Replace `GroupWrapper` (`tiledb.Group`) with `SOMAGroupWrapper` (`clib.SOMAGroup`)
- Remove `_reader_wrapper_type` as we now use `clib.SOMAObject` for all classes
- Use a mapper in `_tdb_handles.open` instead of if-else statements
- Create `from_soma_group_entry` to place `clib.SOMAObject`s into `GroupEntry`
- Remove duplicated "Check ms" test
This PR completes the move over for `SOMAArray` and `SOMAGroup` to use the C++ bindings. There will be several more PRs on top of this to remove tiledb-py completely.

[python] Use bindings for `SOMAGroup` 3/5

---

apis/python/src/tiledbsoma/_collection.py
apis/python/src/tiledbsoma/_exception.py
apis/python/src/tiledbsoma/_experiment.py
apis/python/src/tiledbsoma/_factory.py
apis/python/src/tiledbsoma/_measurement.py
apis/python/src/tiledbsoma/_soma_array.py
apis/python/src/tiledbsoma/_soma_object.py
apis/python/src/tiledbsoma/_tdb_handles.py
apis/python/src/tiledbsoma/io/ingest.py
apis/python/src/tiledbsoma/soma_group.cc
apis/python/tests/test_basic_anndata_io.py
apis/python/tests/test_collection.py

This is on top of https://github.com/single-cell-data/TileDB-SOMA/pull/2735
**Changes:**
- Replace `TileDBObject` with `SOMAObject`; and `_tiledb_object` with `_soma_object`
- Remove `tiledb.TileDBError` usage

[python] Replace `TileDBObject` with `SOMAObject`; Remove `tiledb.TileDBError` usage 4/5

---

apis/python/src/tiledbsoma/__init__.py
apis/python/src/tiledbsoma/_arrow_types.py
apis/python/src/tiledbsoma/_general_utilities.py
apis/python/tests/test_query_condition.py

This is on top of https://github.com/single-cell-data/TileDB-SOMA/pull/2736
This removes `import tiledb` from `apis/python/src` but not in `io` or `options` which will be done in subsequent PRs.
**Changes:**
- Remove `tiledb_schema_to_arrow` as we no longer use TileDB `ArraySchema`
- Remove `get_tiledb_py_core_version` and `verify_core_versions`

[python] Remove tiledb-py from top-level src (sans `io` and `options`) 5/5

---

libtiledbsoma/src/soma/soma_collection.cc
libtiledbsoma/src/soma/soma_experiment.cc
libtiledbsoma/src/soma/soma_group.cc
libtiledbsoma/src/soma/soma_measurement.cc

Fix for https://github.com/jdblischak/centralized-tiledb-nightlies/issues/12#issuecomment-2178827937
**Changes:**
Rethrow `TileDBError` as `TileDBSOMAError` in `SOMAGroup` classes.

[c++] Remap `TileDBError` to `TileDBSOMAError`

---

.github/workflows/python-ci-packaging.yml
apis/python/setup.py
apis/r/tools/get_tarball.R
libtiledbsoma/cmake/Modules/FindTileDB_EP.cmake

Following our [established procedure](https://www.notion.so/785d165226074071872a8b797133d36c?v=c168da78516e487eac3746d38924fa97&p=d1c7a37761b04cf699a705bb8963dea9&pm=s).
Note in particular that core artfacts are updated using the error-proof `./scripts/update-tiledb-version.py 2.24.1`.

Use core 2.24.1 on `release-1.12` branch

---

libtiledbsoma/src/CMakeLists.txt
libtiledbsoma/test/CMakeLists.txt

**Issue and/or context:** #2408
**Changes:**
Create a separate object library for nanoarrow without `-Werror`.

Split nanoarrow into a separate object library

---

apis/python/src/tiledbsoma/options/_soma_tiledb_context.py
apis/python/tests/test_context.py

[sc-50154]
**Changes:**
https://github.com/single-cell-data/TileDB-SOMA/pull/2693 deprecated `tiledb.Ctx` in favor of `clib.SOMAContext`. When setting `tiledb_config`, we switched over to using the config in `clib.SOMAContext`. However, if the user passed in a `tiledb_ctx`, it would ignore it and not use the correct config. Since we are still allowing `tiledb_ctx` until it is removed in 1.14, ensure that we still pull the config from `tiledb_ctx` if that is what the user passed in.
Passing this in as a `tiledb_config` works as expected.

[python] Continue to use `tiledb.Ctx`'s config until it is removed

---

apis/python/devtools/outgestor

Drive-by while looking at outgestor performance.
* Remove a vfs check which doesn't work well with cloud URIs
* Add the option to produce tiledb stats

[python] `devtools/outgestor` stats and neaten

---

.github/workflows/python-ci-packaging.yml
apis/python/setup.py
apis/r/tools/get_tarball.R
libtiledbsoma/cmake/Modules/FindTileDB_EP.cmake

Applies #2757 to `main`
I ran `./scripts/update-tiledb-version.py 2.24.1` as per our [established procedure](https://github.com/single-cell-data/TileDB-SOMA/wiki/Branches-and-releases).

Use core 2.24.1 on `main` branch

---

.github/workflows/python-ci-packaging.yml
apis/r/tools/get_tarball.R
libtiledbsoma/cmake/Modules/FindTileDB_EP.cmake

As always, I ran the error-proof
```
./scripts/update-tiledb-version.py 2.24.2
```

Use core 2.24.2

---

apis/r/R/Init.R

[[sc-50464]](https://app.shortcut.com/tiledb-inc/story/50464/customer-soma-version-conflicts-in-pypi-install)
See also #2783

Compare core to tiledb-py/tiledb-r major+minor, `main` branch

---

apis/python/src/tiledbsoma/_general_utilities.py
apis/r/R/Init.R

[[sc-50464]](https://app.shortcut.com/tiledb-inc/story/50464/customer-soma-version-conflicts-in-pypi-install)
See also #2784

Compare core to tiledb-py/tiledb-r major+minor, `release-1.12` branch

---

apis/python/src/tiledbsoma/options/_soma_tiledb_context.py

Currently warnings about the deprecated `tiledb_ctx` have a not-super useful traceback:
```pytb
/home/ubuntu/miniforge3/envs/cellxgene-census-bump-tiledbsoma/lib/python3.11/site-packages/tiledbsoma/options/_soma_tiledb_context.py:27: DeprecationWarning: tiledb_ctx is now deprecated for removal in 1.14. Use tiledb_config instead by passing SOMATileDBContext(tiledb_config=ctx.config().dict()).
warnings.warn(
```
This change makes it a little more useful by showing the relevant callsite:
```
tests/test_get_anndata.py: 81 warnings
/home/ubuntu/miniforge3/envs/cellxgene-census-bump-tiledbsoma/lib/python3.11/site-packages/tiledbsoma/_tdb_handles.py:333: DeprecationWarning: tiledb_ctx is now deprecated for removal in 1.14. Use tiledb_config instead by passing …
```

[python] Bump the stack level of the `tiledb_ctx` deprecation warning

---

.github/workflows/libtiledb-ci.yml
libtiledbsoma/src/soma/managed_query.cc
libtiledbsoma/src/soma/managed_query.h

**Issue and/or context:** Split out from PR #2785 for issue #2407. This change is makes a unit-test case pass on that PR. For this PR, it's sufficient to observe that existing unit tests all still pass.

[c++] Improve exception-handling for query futures

---

apis/python/src/tiledbsoma/options/_soma_tiledb_context.py

Five fails on backport bot: https://github.com/single-cell-data/TileDB-SOMA/actions/runs/9881520734 -- I don't know why. Manually patching. Backports #2788 to the `release-1.12` branch.

[python] Backport #2788 to `release-1.12`

---

apis/python/src/tiledbsoma/soma_collection.cc
apis/python/src/tiledbsoma/soma_dataframe.cc
apis/python/src/tiledbsoma/soma_dense_ndarray.cc
apis/python/src/tiledbsoma/soma_object.cc
apis/python/src/tiledbsoma/soma_sparse_ndarray.cc

This issue was internally reported by @bkmartinjr:
> I am using the latest Python SOMA, and seeing some really weird serialization of my API requests that "feel" like the GIL is not being released for some I/O operations.
>
> For example:  soma.DataFrame.count.  If I'm reading the code right, it calls the underlying nnz method without releasing it.
**Changes:**
- Just as we do for `clib.SOMAArray.nnz`, we need to release the GIL for `clib.SOMADataFrame.count`
- Also release for all `create` and `open` operations

[python] Release GIL where necessary in pybind11 code

---

apis/python/src/tiledbsoma/_dataframe.py
apis/python/src/tiledbsoma/_util.py
apis/python/src/tiledbsoma/io/ingest.py
apis/python/tests/test_dataframe.py
libtiledbsoma/src/soma/soma_array.cc
libtiledbsoma/src/soma/soma_array.h
libtiledbsoma/test/unit_soma_array.cc

https://github.com/single-cell-data/TileDB-SOMA/issues/2709
**Changes:**
Still failing Python one last unit test `test_write_categorical_types` where if the attribute in the ArraySchema is not an enumeration, but the column in the ArrowTable contains a dictionary encoding then it segfaults.

[c++] Cast `ArrowTable` values in `SOMAArray::write` to match `ArraySchema` on-disk

---

apis/python/src/tiledbsoma/soma_dataframe.cc
apis/python/src/tiledbsoma/soma_dense_ndarray.cc
apis/python/src/tiledbsoma/soma_sparse_ndarray.cc

We have observed CI randomly segfaulting since the merger of https://github.com/single-cell-data/TileDB-SOMA/pull/2733. Consistent in all these stacktraces is `open`. This PR reverts the addition of `gil_scoped_release` from the `SOMAArray::open` bindings.

[python] Hold onto GIL for open methods

---

apis/python/src/tiledbsoma/soma_collection.cc
apis/python/src/tiledbsoma/soma_dataframe.cc
apis/python/src/tiledbsoma/soma_dense_ndarray.cc
apis/python/src/tiledbsoma/soma_object.cc
apis/python/src/tiledbsoma/soma_sparse_ndarray.cc

This continues to partially revert commit 72a4e203f878c53da098a684c49a72179b68265f in conjuction with https://github.com/single-cell-data/TileDB-SOMA/pull/2800. We are now only retaining releasing the GIL for `SOMADataFrame::count`.
Due to multiple reports of intermittent segfaults internally and externally, `SOMAArray::exists` should also be reverted until we have a better way to identify and test releasing the GIL in the pybind11 code. I tested this revert fixed my itermittent segfaults locally by running `make test` 6 times. Previously, I could get a segfault to occur with 3 `make test` runs.

[python] Retain GIL for `exist`

---

apis/python/src/tiledbsoma/soma_dataframe.cc
apis/python/src/tiledbsoma/soma_dense_ndarray.cc
apis/python/src/tiledbsoma/soma_sparse_ndarray.cc
apis/python/tests/test_dataframe.py
apis/python/tests/test_dense_nd_array.py
apis/python/tests/test_sparse_nd_array.py

As internally reported, the `open` bindings error out when `column_names` uses the default argument `py::none` because the C++ argument is a `std::vector<std::string>` and not `optional<...>`.
```
In [10]: clib.SOMAObject.open("tiledb://TileDB-Inc/4b53d109-27aa-4e17-b02a-d61710719b7b", mode=clib.OpenMode.read, context=native_context)
Out[10]: <tiledbsoma.pytiledbsoma.SOMADataFrame at 0x7bc8d4304eb0>
In [11]: clib.SOMADataFrame.open("tiledb://TileDB-Inc/4b53d109-27aa-4e17-b02a-d61710719b7b", mode=clib.OpenMode.read, context=native_context)
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Cell In[11], line 1
----> 1 …
```

[python] Replace `py::none` with `py::list` for `column_names` default arg

---

apis/python/src/tiledbsoma/_util.py
apis/python/tests/test_platform_config.py

Found while experimenting with write-performance tuning, including dogfooding of #2564.
It turns out if the platform-config create spec for a dim has tile extent _and_ a filter, the filter was begin ignored.
I fixed this, and improved the unit-test coverage to catch the fixed bug.

[python] Allow platform config to set extent and filter

---

apis/python/src/tiledbsoma/io/ingest.py
apis/python/tests/test_io.py

Found while experimenting with write-performance tuning, including dogfooding of #2564, as on #2808.
An unfortunate search-and-replace on #2776 (fault: my own) changed an import path in a desirable way, while renaming a function parameter in an undesirable way.
This PR:
* Improves readability
* Facilitates dogfooding of write-performance mods from #2564 
* Does not break any existing functionality

[python] Typo-fix some parameter names in some internal functions

---

libtiledbsoma/src/soma/soma_dense_ndarray.cc
libtiledbsoma/src/soma/soma_dense_ndarray.h
libtiledbsoma/src/soma/soma_sparse_ndarray.cc
libtiledbsoma/src/soma/soma_sparse_ndarray.h
libtiledbsoma/test/unit_soma_dense_ndarray.cc
libtiledbsoma/test/unit_soma_sparse_ndarray.cc

https://github.com/single-cell-data/TileDB-SOMA/issues/2797
**Changes:**
As requested for the SOMA R API, add `soma_data_type` for `SOMADenseNDArray` and `SOMASparseNDArray`.

[c++] Add `NDArray::soma_data_type`

---

libtiledbsoma/src/soma/soma_array.cc
libtiledbsoma/src/soma/soma_array.h

https://github.com/single-cell-data/TileDB-SOMA/issues/2197
**Changes:**
Move the schema evolution call to outside of the loop so that it is called only once for a table instead for every column.
Although this fixes the race condition for `test_write_categorical_types` and `test_dataframe_with_enumeration` as observed in the issue above, it does not fix the issues with the recent intermittent segfaults which I believe is fixed by https://github.com/single-cell-data/TileDB-SOMA/pull/2801.

[c++] Do not call schema evolution for each column

---

libtiledbsoma/src/soma/soma_array.h

As reported by @ryan-williams, `pytest test_dataframe.py::test_dataframe_with_enumeration` was segfaulting on an Amazon Linux 2 EC2 instance (although not reproducible on other platforms).
**Changes:**
For nullable dictionary columns, when the value is null, the corresponding index may be a negative integer (depending on whether the index type is a signed or unsigned integer type). Using a negative integer to index into the vector `enums_in_write` causes a segfault so check the index value first.
There are no added tests as `test_dataframe.py::test_dataframe_with_enumeration` no longer segfaulting on the EC2 instance proves that it is fixed.

[c++] Check index in enumeration casting before using

---

apis/r/R/SOMANDArrayBase.R
apis/r/man/SOMANDArrayBase.Rd

The `roxygenize()` helper function would no longer run unless the R6 class method `set_data_type()` was also documented.
**Changes:**
This PR adds a simple short documentation entry.
[SC 51948](https://app.shortcut.com/tiledb-inc/story/51948/r-complete-rd-content)

[r] Add missing documentation for set_data_type

---

apis/python/src/tiledbsoma/_soma_object.py
apis/python/src/tiledbsoma/_tdb_handles.py
apis/python/src/tiledbsoma/options/_soma_tiledb_context.py
apis/python/src/tiledbsoma/soma_array.cc
apis/python/src/tiledbsoma/soma_group.cc
apis/python/tests/test_collection.py
apis/python/tests/test_dataframe.py
apis/python/tests/test_dense_nd_array.py
apis/python/tests/test_experiment_basic.py
apis/python/tests/test_sparse_nd_array.py
libtiledbsoma/src/soma/soma_array.cc
libtiledbsoma/src/soma/soma_array.h
libtiledbsoma/src/soma/soma_group.cc
libtiledbsoma/src/soma/soma_group.h

https://github.com/single-cell-data/TileDB-SOMA/issues/921
**Changes:**
- Addition of `SOMA{Array,Group}::reopen` in C++ and bindings in pybind11
- Addition of `SOMAObject.reopen` in Python
- Correct `SOMAArray` pybind11 inheritance

[c++/python] Add `reopen` for `SOMAArray` and `SOMAGroup`

---

apis/r/DESCRIPTION
apis/r/NEWS.md
apis/r/R/TileDBObject.R
apis/r/man/TileDBObject.Rd
apis/r/tests/testthat/test-reopen.R

As discussed on Slack, `$reopen()` should not default to switching open mode; instead `mode` should always be passed in by the user
- `TileDBObject$reopen()`: `mode` no longer has a default; instead, the user must supply a mode to reopen the object as
[SC-51935](https://app.shortcut.com/tiledb-inc/story/51935)

[r] Remove default mode-flipping in `$reopen()`

---

apis/python/src/tiledbsoma/_soma_object.py
apis/python/src/tiledbsoma/_tdb_handles.py
apis/python/tests/test_collection.py
apis/python/tests/test_dataframe.py
apis/python/tests/test_dense_nd_array.py
apis/python/tests/test_experiment_basic.py
apis/python/tests/test_sparse_nd_array.py
libtiledbsoma/src/soma/soma_array.cc
libtiledbsoma/src/soma/soma_array.h
libtiledbsoma/src/soma/soma_group.cc
libtiledbsoma/src/soma/soma_group.h

As reported internally, the `reopen` unit tests intermittenly fail due to a race condition when objects are opened at the same timestamp.
**Changes:**
Add `tiledb_timestamp` for `reopen` methods and modify tests to use explicit timestamps to prevent race conditions.

[c++/python] Add `tiledb_timestamp` argument for `reopen`

---

apis/r/DESCRIPTION
apis/r/NEWS.md
apis/r/R/SOMAExperimentAxisQuery.R
apis/r/man/SOMAExperimentAxisQuery.Rd
apis/r/tests/testthat/helper-test-data.R
apis/r/tests/testthat/helper-test-soma-objects.R
apis/r/tests/testthat/test-SCEOutgest.R
apis/r/tests/testthat/test-SeuratOutgest-assay.R
apis/r/tests/testthat/test-SeuratOutgest-object.R

R analog of #2811 and single-cell-data/SOMA#204; add a `drop_levels` paramter to the ecosystem outgestors to drop unused factor levels from resulting data frames
- `SOMAExperimentAxisQuery$to_seurat()`: add `drop_levels` to drop drop unused levels from `obs` and `var` data frames
- `SOMAExperimentAxisQuery$to_seurat_assay()`: add `drop_levels` to drop unused levels from `var` data frame
- `SOMAExperimentAxisQuery$to_single_cell_experiment()`: add `drop_levels` to drop unused levels from `obs` and `var` data frames
Also shifts `SOMAExperimentAxisQuery$to_seurat()` and `SOMAExperimentAxisQuery$to_seurat_assay()` to use `SOMAExperimentAxisQuery$private$.load_df()` for loading `obs` and `var`; removing standalone code and increase sharing with the SCE outgestor
resolves …

[r] Add `drop_levels` to `SOMAExperimentAxisQuery` -> ecosystem outgestors

---

apis/python/src/tiledbsoma/_common_nd_array.py
apis/python/tests/test_dense_nd_array.py

**Issue and/or context:** The `reshape` method is not part of [the SOMA spec](https://github.com/single-cell-data/SOMA/blob/main/abstract_specification.md). And it is raising `NotImplementedError` so no one can be using it. This needs to be GC'ed. This is a split-out from PR #2785 for issue #2407. See also [[sc-51048]](https://app.shortcut.com/tiledb-inc/story/51048).
**Changes:**

[python] Remove `reshape` stub

---

apis/r/R/RcppExports.R
apis/r/R/TileDBObject.R
apis/r/src/RcppExports.cpp
apis/r/src/soma.cpp
apis/r/tests/testthat/test-write-soma-objects.R

Object type (i.e. Array or Group) is currently gotten via a tiledb-r function.
**Changes:**
This PR exposes the corresponding libtiledbsoma function, and adds tests.
[SC 52390](https://app.shortcut.com/tiledb-inc/story/52390/r-expose-somaobject-type)

[r] Expose object-type getter

---

apis/python/src/tiledbsoma/_query_condition.py
apis/python/tests/test_query_condition.py

**Issue and/or context:** [[sc-52135]](https://app.shortcut.com/tiledb-inc/story/52135) [[sc-52172]](https://app.shortcut.com/tiledb-inc/story/52172)
**Changes:** Improve the error message.
Example:
```
import sys
expr = 'foo is True'
if len(sys.argv) == 2:
expr = sys.argv[1]
with tiledbsoma.Experiment.open('/var/p') as exp: # /var/p is a copy of pbmc3k; any Experiment will do
exp.obs.read(value_filter=expr).concat()
```
```
johnkerl@exade[prod][kerl/qc-parser-nonconstant-rhs][python]$ python q1.py 'louvain == leukocyte'
File "/Users/johnkerl/git/single-cell-data/TileDB-SOMA/apis/python/q1.py", line 12, in <module>
exp.obs.read(value_filter=expr).concat()
File …
```

[python] Improve error message on non-constant query-condition RHS

---

apis/python/src/tiledbsoma/_sparse_nd_array.py
apis/python/src/tiledbsoma/_types.py
apis/r/R/TileDBArray.R
apis/r/man/TileDBArray.Rd

**Issue and/or context:** For #2407
**Changes:**

[r/python] Deprecation notices for `used_shape`

---

apis/r/R/TileDBArray.R
apis/r/tests/testthat/test-SOMASparseNDArray.R
apis/r/tests/testthat/test-write-soma-resume.R

Follow-on from https://github.com/single-cell-data/TileDB-SOMA/pull/2834#issuecomment-2269958874 for issue 2407
Example interactive use:
```
> exp <- SOMAExperimentOpen('/var/p')
> exp$ms$get("RNA")$X$get("data")$used_shape()
$soma_dim_0
integer64
[1] 0    2637
$soma_dim_1
integer64
[1] 0    1837
Warning message:
used_shape will be removed in TileDB-SOMA 1.14
```

[r] Use `.Deprecated` for `used_shape` in R

---

apis/python/src/tiledbsoma/io/_registration/signatures.py
apis/python/src/tiledbsoma/io/ingest.py
apis/python/src/tiledbsoma/io/outgest.py
apis/python/tests/test_dataframe_io_roundtrips.py

1. The first commit in this PR just adds [new unit tests][ROUND_TRIPS], which verify several categories of ingest/outgest "round-trip mutations."
- See https://github.com/single-cell-data/TileDB-SOMA/issues/2829 for more details.
2. The second commit factors DF ingest/outgest logic currently ≈duplicated in 2 places each:
- ingest: `ingest.py`/`signatures.py`
- outgest: `obs`/`var`
In the near future we'll want to use both for `uns` as well.
3. The third commit adds a 2nd set of tests, functionally identical to those added in 1., except they directly round-trip an "obs" DataFrame (using `_write_dataframe` and `_read_dataframe`; the latter is added in 2.).
- The tests from 1. round-trip using `{from,to}_anndata`), and are still present.
[ROUND_TRIPS]: …

[python] Ingest/outgest round-trip improvements

---

apis/python/src/tiledbsoma/_collection.py
apis/python/src/tiledbsoma/_tdb_handles.py
apis/python/tests/test_collection.py

https://github.com/single-cell-data/TileDB-SOMA/issues/2787
**Changes:**
The binding from Python to C++ `SOMAGroup::members_map` already exists. We are just exposing this at the API level so that the user can call `SOMA{Collection,Experiment,Measurement}.members()` to get a dictionary of member names to a tuple of (uri, type).
https://github.com/single-cell-data/TileDB-SOMA/blob/main/libtiledbsoma/src/soma/soma_group.cc#L142-L156
When creating or opening a `SOMAGroup` in C++, we call `fill_caches` which populates the member mapping by calling `tiledb::Object::member` rather than opening each object in the collection.

[python] Add `CollectionBase.members`

---

apis/python/src/tiledbsoma/_dataframe.py
apis/python/src/tiledbsoma/_sparse_nd_array.py
apis/python/tests/test_sparse_nd_array.py

Implements #2841 
See also [[sc-52470]](https://app.shortcut.com/tiledb-inc/story/52470/python-implement-scheduled-removal-of-tiledbcreateoptions-being-passed-to-write-methods)

[python] Implement scheduled removal of `TileDBCreateOptions` being passed to `write` methods

---

apis/python/src/tiledbsoma/_collection.py
apis/python/src/tiledbsoma/_tdb_handles.py

https://github.com/single-cell-data/TileDB-SOMA/issues/2812
**Changes:**
Use original error message when re-raising with `DoesNotExistError`

[python] Use original error message when re-raising with `DoesNotExistError`

---

.github/workflows/python-ci-single.yml

**Issue and/or context:** #2839 [[sc-52471]](https://app.shortcut.com/tiledb-inc/story/52471)
- `actions/cache` and `actions/setup-python` cache Python dependencies based on a hash of the contents of `python-ci-single.yml`.
- `python-ci-single.yml` changed on Friday ([#2827](https://github.com/single-cell-data/TileDB-SOMA/pull/2827)) for the first time since June 6 ([#2688](https://github.com/single-cell-data/TileDB-SOMA/pull/2688))
- Some lint jobs have been failing since, apparently due to loading existing `setup-python` caches, which don't like the `# type: ignore[misc]` at [_types.py:24](https://github.com/single-cell-data/TileDB-SOMA/blob/36a4fc619d25e3a481365ca2d7485f196f4372ae/apis/python/src/tiledbsoma/_types.py#L24) (added in …

[python] Debug CI `mypy` failures related to `# type: ignore[misc]`

---

apis/python/pyproject.toml
apis/python/src/tiledbsoma/io/_common.py
apis/python/src/tiledbsoma/io/_registration/ambient_label_mappings.py
apis/python/src/tiledbsoma/io/_registration/signatures.py
apis/python/src/tiledbsoma/io/ingest.py
apis/python/src/tiledbsoma/io/outgest.py
apis/python/tests/test_collection.py
apis/python/tests/test_registration_mappings.py
apis/python/tests/test_update_dataframes.py

**Issue and/or context:** various cleanups/tweaks, factored out of #2804
**Changes:**
The commits should all be orthogonal / messages relatively self-explanatory:
- remove some unused function arguments
- fix some docstring typos
- improve an error msg in `_update_dataframe`
- ~`deepcopy` test-AnnDatas (to verify "originals" aren't mutated by `from_anndata`)~ punted to a future PR
- factor more commonly-reused kwargs in ingest.py
No user API is affected by this PR.

[python] Misc. ingest/outgest code-neaten improvements

---

apis/python/tests/test_dataframe.py
libtiledbsoma/src/soma/soma_array.cc
libtiledbsoma/src/soma/soma_array.h

As caught be @eddelbuettel, the C++ write path was calling `SchemaEvolution.array_evolve` for every write. This call is only necessary if we have extended the enumerations. Otherwise, we end up bloating the `__schema` directory with unnecessary fragment files.
**Changes:**
- `SOMAArray` methods `_extend_enumeration`, `_extend_and_evolve_schema{,_str}`, and `_create_and_cast_column` return `bool` to indicate whether the column called `SchemaEvolution.extend_enumeration`
- Only call `SchemaEvolution.array_evolve` if any of the columns in the table called `SchemaEvolution.extend_enumeration`
The test for this is written in Python as it is much more complicated to construct an `ArrowTable` with dictionary columns in C++.

[c++] Only evolve schema when enumerations are extended

---

.github/workflows/r-ci.yml
.pre-commit-config.yaml
apis/python/src/tiledbsoma/_indexer.py
apis/python/src/tiledbsoma/_types.py

also simplify some `if TYPE_CHECKING` blocks
**Issue and/or context:** #2839, #2853
The unpinned `pandas-stubs` dep in `.pre-commit-config.yaml` allowed existing local environments (and old cached `setup-python` environments, which in some cases were being incorrectly used in our GHAs, per https://github.com/actions/setup-python/issues/919) to run the pre-commit `mypy` hook using `pandas-stubs<2`, where `pd.Series` is the type, and `pd.Series[Any]` requires a `# type: ignore[misc]` annotation.
With `pandas-stubs>=2` (which new environments have been picking up), `pd.Series[Any]` is the correct type, and the `# type: ignore[misc]` annotation was flagged as "unused" ([example](https://github.com/single-cell-data/TileDB-SOMA/actions/runs/10291856865/job/28485041039?pr=2853#step:7:43)). …

[python] pin `pandas-stubs>=2` during pre-commit `mypy` hook

---

apis/python/src/tiledbsoma/_query_condition.py
apis/python/tests/test_query_condition.py

**Issue and/or context:** #2832 
@kounelisagis I suggest that we should do the same in TileDB-Py. I'll file a Shortcut task.
**Changes:** Provide a better error message.
Script:
```
expr = 'lou.vain == "leukocyte"'
uri = '/var/p'
with tiledbsoma.Experiment.open(uri) as exp:
o = exp.obs.read(value_filter=expr).concat()
print(o)
```
Before:
```
File "/Users/johnkerl/git/johnkerl/tiledb-misc/notes/2024-08-06-qcond-syntax/x", line 6, in <module>
o = exp.obs.read(value_filter=expr).concat()
File "/Users/johnkerl/git/single-cell-data/TileDB-SOMA/apis/python/src/tiledbsoma/_dataframe.py", line 409, in read
sr.set_condition(QueryCondition(value_filter), handle.schema) …
```

[python] Offer better guidance on attribute names with `.`

---

apis/python/src/tiledbsoma/io/_util.py
apis/python/src/tiledbsoma/io/ingest.py
apis/python/src/tiledbsoma/pytiledbsoma.cc

I previously had [this PR](https://github.com/single-cell-data/TileDB-SOMA/pull/2751) to move tiledb-py out of `_update_dataframe`, but this should not go in C++ API as it is specifically for `tiledbsoma.io`. This also makes the code easier to follow.
**Changes:**
Move tiledb-py steps into pybind11.

[python] Move `_update_column` into pybind11

---

apis/python/src/tiledbsoma/soma_dataframe.cc
apis/python/tests/test_dataframe.py

**Issue and/or context:** #2869

`python` Utilize Arrow schema `pa.field` nullabilities in `DataFrame.create`

---

apis/python/tests/test_registration_mappings.py

`test_registration_mappings.py::test_pandas_indexing` is one of the tests closest to the issues described in #2829, but I struggled to parse what the 14 cases were verifying, so I reformatted and documented them in a way that I feel makes them easier to understand.
**Changes:**
The first commit surfaces that the 14 cases are 2 similar blocks of 7 cases each (one where the `default_index_name` is `obs_id`, one where it's `alt_id`). Each set of 7 can be further subdivided into:
- 3 cases where `default_index_name` matches the name of the column that was promoted to `df.index` (and `df.index.name` is either preserved, set to `"index"`, or set to `None`)
- 3 cases where it's the other column (and similarly `df.index.name` is either preserved, set to `"index"`, or set …

[python] `test_registration_mappings.py::test_pandas_indexing` reformat

---

apis/r/R/SOMADataFrame.R
apis/r/R/SOMASparseNDArray.R
apis/r/R/TileDBArray.R
apis/r/R/TileDBGroup.R
apis/r/R/TileDBObject.R
apis/r/R/utils.R
apis/r/R/write_soma.R
apis/r/man/TileDBObject.Rd

Expose timestamps publicly through a new active binding; replace calls to `private$tiledb_timestamp` with `self$tiledb_timestamp`
Also plumb timestamps through for `write_soma()` in resume-mode

[r] Expose timestamps publicly and plumb through for resume-mode

---

.pre-commit-config.yaml
apis/python/setup.py

For
* https://github.com/single-cell-data/SOMA/releases/tag/python-v1.0.14
* https://github.com/single-cell-data/SOMA/pull/208
* https://github.com/single-cell-data/SOMA/pull/209

[python] Use `somacore` 1.0.14

---

apis/python/src/tiledbsoma/_util.py
apis/python/tests/_util.py
apis/python/tests/test_basic_anndata_io.py
apis/python/tests/test_dataframe_io_roundtrips.py
apis/python/tests/test_platform_config.py
apis/python/tests/test_registration_mappings.py
apis/python/tests/test_registration_signatures.py
apis/python/tests/test_update_dataframes.py

**Changes:**
- Introduce `assert_adata_equal` utilitiy
- Replaces `verify_obs_and_var_eq`, `anndata_dataframe_unmodified`, `anndata_dataframe_unmodified_nan_safe`
- Use `assert_adata_equal` in tests
- This surfaces I/O round-trip misbehavior in `test_basic_anndata_io.py::test_uns_io` (some covered by [#2829](https://github.com/single-cell-data/TileDB-SOMA/issues/2829), some specific to `uns` / not previously documented)
- That test is updated here, to verify and document current behavior.
- https://github.com/single-cell-data/TileDB-SOMA/compare/rw/eq...rw/uns includes follow-on work improving/fixing the issues.
#2874 builds on this, fixes some of the `uns` issues, and removes code added to `test_uns_io` here.

[python] More AnnData equality assertions in tests

---

apis/python/src/tiledbsoma/io/ingest.py
apis/python/tests/_util.py
apis/python/tests/parametrize_cases.py
apis/python/tests/test_basic_anndata_io.py
apis/python/tests/test_dataframe.py
apis/python/tests/test_dataframe_io_roundtrips.py

**Issue and/or context:** #2829, #2804, #2868
**Changes:**
- Tests introduced in #2804 included configurable `outgest_default_index_name` and `outgest_fallback_index_name` fields, that were never set to non-default values. Removing them here, to avoid confusion.
- Other comment updates / typo fixes

[python] Update comments, remove unused test params

---

libtiledbsoma/src/soma/soma_group.cc
libtiledbsoma/test/unit_soma_collection.cc
libtiledbsoma/test/unit_soma_group.cc

Tracking: #2885 
As caught interally, the `dataset_type` needs to be set to `soma` for `SOMAExperiment` on tiledb-cloud upon creation.

[c++] Add `dataset_type` into `SOMAExperiment` metadata

---

Makefile
libtiledbsoma/src/soma/soma_group.cc
libtiledbsoma/test/unit_soma_group.cc

CI fail introduced on #2884.
`std::strcmp` returns 0 on match so the intended use is `!std::strcmp("foo", "foo")` to get a truthy value.

[c++] Fix typos in unit-test case

---

libtiledbsoma/test/unit_soma_group.cc

Follow-up from https://github.com/single-cell-data/TileDB-SOMA/pull/2888#discussion_r1716813679
I had used this to make it easier to get a breakpoint in the right spot in `gdb` while debugging #2888. I neglected to take it back out.

[c++] Remove a temporary `gdb` hook from #2888

---

.github/workflows/daily-test-build-issue-template.md

Follow-up from #2890. At the time that rule was created, @mlin was actively involved in TileDB-SOMA CI.
At the current point in time, @ryan-williams is actively involved in this particular area; @mlin less so; @nguyenv and @johnkerl still involved.

[ci] Update autocut rule for current ownership

---

apis/python/src/tiledbsoma/io/ingest.py
apis/python/src/tiledbsoma/io/outgest.py
apis/python/tests/test_basic_anndata_io.py

**Issue and/or context:** builds on #2872
**Changes:**
- During `from_anndata` ingest, `copy` DataFrames supplied by user in `uns` before passing to `_write_dataframe`, to avoid mutating user-supplied objects
- `obs` and `var` are already copied before being passed to `_write_dataframe`, by being passed through `conversions.decategoricalize_obs_or_var` ([example](https://github.com/single-cell-data/TileDB-SOMA/blob/main/apis/python/src/tiledbsoma/io/ingest.py#L512))
- During `to_anndata` outgest, use `_read_dataframe` on `uns` DataFrames, to better restore what was originally ingested
- Clean up tests (added in #2872) which codify previous behavior

[python] improve `uns` DataFrame I/O

---

apis/python/src/tiledbsoma/io/outgest.py
apis/python/tests/_util.py
apis/python/tests/parametrize_cases.py

**Issue and/or context:** 
- Parent: #2874
- Child: #2876 (uses the new `maybe_raises` / `verify_logs` functionality, this was factored from there)
**Changes:**
- `maybe_raises` can be passed a `str` (to match against an error message, regardless of error type) or an `(exc, msg)` tuple (to match against error type as well as message. As before, this is useful for tests where some cases expect no error, while others want to verify an error's class and/or message.
- `tests._util.verify_logs` helper, which can verify presence of expected log messages, given a pytest ["caplog"](https://docs.pytest.org/en/7.1.x/how-to/logging.html#caplog-fixture) fixture

[python] Docstring typo, test-assertion msgs, `maybe_raises` improvement, `verify_logs` helper

---

apis/python/tests/_util.py
apis/python/tests/test_basic_anndata_io.py
apis/python/tests/test_dataframe_io_roundtrips.py

Follow-on from https://github.com/single-cell-data/TileDB-SOMA/pull/2873#discussion_r1713967875
There are Pandas DataFrame objects, and SOMA DataFrame objects. This minor name-change makes it clearer which kind the helper function is returning.

[python] Unit-test helper `make_df` -> `make_pd_df`

---

apis/python/tests/test_dataframe.py
libtiledbsoma/src/soma/soma_array.cc

**Issue and/or context:** #2879 
**Changes:** If we've got the array open at a timestamp, and we need to evolve it, evolve from that same timestamp.
Material from @nguyenv to be incorporated into unit-test material:
**Script:**
```
$ cat ts.py
import tiledb
import tiledbsoma as soma
import pyarrow as pa
import tempfile
import numpy as np
import pandas as pd
import time
with tempfile.TemporaryDirectory() as uri:
asch = pa.schema([("foo", pa.dictionary(pa.int8(), pa.large_string()))])
soma.DataFrame.create(uri, schema=asch, tiledb_timestamp=1).close()
pydict = {}
pydict["soma_joinid"] = [0, 1, 2]
pydict["foo"] = pd.Series(['a', 'b', 'a'], dtype='category')
rb = pa.Table.from_pydict(pydict)
with soma.DataFrame.open(uri, "w", tiledb_timestamp=2) as sdf:
sdf.write(rb) …
```

[c++] Apply `ArraySchemaEvolution` to specified timestamp

---

apis/python/src/tiledbsoma/common.cc

**Issue and/or context:** For #2698
I ran an audit here: https://gist.github.com/johnkerl/a9eb64de62f881e80cd8e7ee54aa1c5c
Findings:
* Python: At initial group-creation and array-creation time we have these:
* https://github.com/single-cell-data/TileDB-SOMA/blob/1.13.0/libtiledbsoma/src/soma/soma_group.cc#L58-L68
* https://github.com/single-cell-data/TileDB-SOMA/blob/1.13.0/libtiledbsoma/src/soma/soma_array.cc#L65-L75
* These explicitly, and correctly, specifies type `TILEDB_STRING_UTF8`
* Python: For subsequent post-create metadata updates we have this:
* https://github.com/single-cell-data/TileDB-SOMA/blob/1.13.0/apis/python/src/tiledbsoma/_tdb_handles.py#L531-L536
* https://github.com/single-cell-data/TileDB-SOMA/blob/1.13.0/apis/python/src/tiledbsoma/soma_group.cc#L102-L106
* …

[c++] Final update for Python/R metadata typing

---

apis/python/tests/test_dataframe.py
libtiledbsoma/src/soma/soma_array.cc

**Issue and/or context:** Fixes issue #2896.
**Changes:** Remap indices whether or not the enumeration is extended, as shown in the unit-test example added here.

[c++] Corner-case bug in extend-enumeration logic

---

apis/r/R/Init.R
apis/r/R/RcppExports.R
apis/r/src/RcppExports.cpp
apis/r/src/rutilities.cpp

When comparing major.minor versions of the underlying library we were reconstruction <major,minor,patch> from the string when we do actually have the components and can use then directly.
**Changes:**
This applies a small simplification to supply a two element <major,minor> vector as needed for the comparison and also uses the vector form the other version.  This allow us to remove two `strsplit()` calls.
[SC 50630](https://app.shortcut.com/tiledb-inc/story/50630/r-minor-robustification-for-version-comparison) 
I put this together after the previous vacation and didn't PR it yet as it wasn't that important but seeing that we are doing other cleanups this weekend may as well put it up.

[r]  Small robustification for version comparison

---

.pre-commit-config.yaml
apis/python/setup.py
apis/python/src/tiledbsoma/_experiment.py
apis/python/src/tiledbsoma/_measurement.py
apis/python/src/tiledbsoma/experimental/ingest.py

* Rename `[obs|var]_scene` -> `[obs|var]_spatial_presence`
* Default to not creating `var_spatial_presence` dataframe when ingesting cellxgene hdf5 files
* Fix the `obsl[loc]` dataframe to only have columns for the `soma_joinid` and location data (position & spot size)

Small adjustments to the spatial branch

---

libtiledbsoma/test/common.cc
libtiledbsoma/test/common.h
libtiledbsoma/test/unit_soma_collection.cc
libtiledbsoma/test/unit_soma_dataframe.cc
libtiledbsoma/test/unit_soma_dense_ndarray.cc
libtiledbsoma/test/unit_soma_sparse_ndarray.cc

**Issue and/or context:** This is a line-count-reducing under-diff split out from #2785 for issue #2407; [[sc-51048]](https://app.shortcut.com/tiledb-inc/story/51048). It will help reduce distractions on upcoming review of more substantial PRs.
**Changes:**
Up until now the number of rows in arrow-schema/arrow-data for dataframe setup from Python/R to C++ has had 3 slots. On #2785 it will necessarily have 5. This PR parameterizes some hard-coded values of `3` to now reference `n`, after `int n = 3`.
Similarly, this PR replaces a hard-coded within-function 1000 to a new parameter `dim_max` for use by callers, who will need explicit construction access to test resize logic for upcoming PRs on #2407.
#2785 is unreviewable as-is: besides being a WIP, it's an all-in-one …

[c++] Trivial parameterizes in `test/common.cc`

---

libtiledbsoma/src/soma/soma_array.cc
libtiledbsoma/src/soma/soma_array.h

**Issue and/or context:** This is a line-count-reducing under-diff split out from #2785 for issue #2407; [[sc-51048]](https://app.shortcut.com/tiledb-inc/story/51048).
**Changes:**
On #2895 I made an inline code block for instantiating an `ArraySchemaEvolution` object pointed at the current array's context and open-at timestamp (if any). That was after I did a call-graph analysis that showed that this was the sole spot in `main` -- at that point in time -- where we needed to do this.
However, on #2785 we'll be making more use of schema evolution, from more than one callsite. It makes even more sense now to encapsulate this logic in a single place.
#2785 is unreviewable as-is: besides being a WIP, it's an all-in-one experimental area. Smaller PRs such as this one …

[c++] Methodize timestamped-schema-evolution factory

---

libtiledbsoma/test/common.cc
libtiledbsoma/test/common.h
libtiledbsoma/test/unit_soma_collection.cc

**Issue and/or context:** Found while working on issue #2407 / [[sc-51048]](https://app.shortcut.com/tiledb-inc/story/51048).
**Changes:** The three places `create_schema` is called, it is not used.

[c++] Remove some dead unit-test code

---

libtiledbsoma/src/external/include/nanoarrow/nanoarrow.h
libtiledbsoma/src/external/include/nanoarrow/nanoarrow.hpp
libtiledbsoma/src/external/src/nanoarrow/nanoarrow.c

This PR updates the "vendored" [`nanoarrow`](https://github.com/apache/arrow-nanoarrow) to its recent-ish 0.5.0 release made in May.  The same release is now used in `tiledb-r` too.
**Changes:**
The three files `nanoarrow.{c,h,hpp}` were updated.   
No new code, no new tests.
[SC 53287](https://app.shortcut.com/tiledb-inc/story/53287/c-r-update-vendored-nanoarrow-to-release-0-5-0)

[c++,r] Update vendored `nanoarrow` to release 0.5.0

---

scripts/bld

<details>
<summary>
<a href="https://github.com/single-cell-data/TileDB-SOMA/pull/2218/files#r1728970448">
#2218 (comment)
</a>
</summary>
<br/>
> `$"LD_LIBRARY_PATH"` evaluates to the string `LD_LIBRARY_PATH`; the `$` needs to be inside the quotes:
> 
> ```bash
> docker run --rm bash -c 'foo=1; echo $"foo" "$foo"'
> # foo 1
> ```
> 
> `[ -z $"LD_LIBRARY_PATH" ]` is always false, so we've inadvertently been doing what @bkmartinjr suggested (always prepending `${tiledb}:`). I think this is also why the `set +u` seemed necessary; the "append" block was running even with `LD_LIBRARY_PATH` unset, which `set -u` was flagging as an error.
> 
> A common way of doing these two `if` blocks is:
> ```bash
> export LD_LIBRARY_PATH="$tiledb${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}"
> export …
```

shellcheck `scripts/bld`

---

apis/r/DESCRIPTION
apis/r/NEWS.md
apis/r/R/SOMAArrayBase.R
apis/r/R/SOMADataFrame.R
apis/r/R/SOMADenseNDArray.R
apis/r/R/SOMASparseNDArray.R
apis/r/R/TileDBArray.R
apis/r/R/TileDBObject.R
apis/r/R/utils.R
apis/r/man/TileDBObject.Rd
apis/r/tests/testthat/test-SOMASparseNDArray.R
apis/r/tests/testthat/test-Timestamps.R

Improved handling of timestamp and timestamp ranges for libtiledbsoma. When users provide a timestamp to `SOMA*Open()`, it is expected to be a scalar, defined as "read up to this point"; as libtiledbsoma expects a vector of timestamps in the form of `<t0, t1>`, add a new `.tiledb_timestamp_range` active binding to automagically convert the scalar `tiledb_timestamp` to a vector, or `NULL` if no timestamp was specified
New SOMA properites:
- `TileDBObject$.tiledb_timestamp_range`: new active binding to return the timestamp as a range `<t0, t1>` for libtiledbsoma; exposed as an active binding for use outside of the R6 objects
- `TileDBObject$initialize(tiledb_timestamp = )`: now requires `tiledb_timestamp` to be either `NULL` or a scalar, finite `POSIXct` object
- …

[r] Expose timestamp ranges for libtiledbsoma

---

apis/r/DESCRIPTION
apis/r/NEWS.md
apis/r/R/Factory.R
apis/r/R/SOMAArrayBase.R
apis/r/R/SOMADataFrame.R
apis/r/R/SOMANDArrayBase.R
apis/r/R/SOMASparseNDArray.R
apis/r/R/TileDBArray.R
apis/r/man/SOMADataFrame.Rd
apis/r/man/SOMANDArrayBase.Rd
apis/r/man/TileDBArray.Rd
apis/r/tests/testthat/test-Timestamps.R

Use cached timestamps in `$write()` and `$create()` methods instead of exposing a timestamp/timestamp range parameter. If a user wishes to write a at a new timestamp, they can reopen at a new time with `$reopen()`
- `SOMADataFrame$write()`: remove `tsrange` parameter in favor of using `self$.tiledb_timestamp_range`; writing at a new timestamp now requires re-opening at a new time with `$reopen(tiledb_timestamp = )`
- `TileDBArray$set_metadata()`: remove `timestamps` parameter in favor of using `self$.tiledb_timestamp_range`
- `SOMANDArrayBase$create()` and `SOMADataFrame$create()`: remove `timestamps` parameter in favor of using `self$.tiledb_timestamp_range`
- `SOMAArrayBase$private$write_object_type_metadata()`: remove `timestamps` parameter in favor of using …

[r] Use cached timestamp in `$create()` and `$write()`

---

apis/python/src/tiledbsoma/io/_common.py
apis/python/src/tiledbsoma/io/ingest.py
apis/python/src/tiledbsoma/io/outgest.py
apis/python/src/tiledbsoma/io/update_uns.py
apis/python/tests/test_basic_anndata_io.py
apis/python/tests/test_update_uns.py

- Fixes #1769
- Extends #2892 
- Takes an already-open-for-write `Experiment`
- Mostly only supports writing keys that don't currently exist:
- Existing scalars can be updated with other scalars.
- If the existing or new value is an array or dataframe, the update is not performed
- Overwriting scalars with arrays/dataframes should be support-able, can add here or in a future PR.
- `strict` param controls behavior in the presence of unsupported updates:
- Default (`strict=True`):
- Performs a "dry run," which `raise`s on unsupported updates, but does not perform any writes (corresponds to `strict="dry_run"`)
- If dry run succeeds, a second pass (with `strict="raise"`) performs the updates.
- The expectation is nothing will be `raise`d by this pass.
- This ensures updates are either all …

[python] `update_uns_by_uri`, `_update_uns`

---

apis/r/configure
apis/r/tools/check_cmake_and_git.R
apis/r/tools/get_tarball.R

As seen in #2931, error messages are not clear enough and do not break the build soon enough.
**Changes:**
Ensure the failing error code is transmitted.  Make error text displayed a little 'louder' as well.
[SC 53847](https://app.shortcut.com/tiledb-inc/story/53847/r-make-some-build-failure-modes-more-visible)

[r] Signal script failure to calling script, polish messages

---

libtiledbsoma/src/soma/soma_array.cc

**Issue and/or context:** Found at https://github.com/single-cell-data/TileDB-SOMA/pull/2911/files#r1721037749 on PR #2911, for issue #2407 / [[sc-51048]](https://app.shortcut.com/tiledb-inc/story/51048). It will help reduce distractions on upcoming review of more substantial PRs -- although this PR has a bit more substance than #2908, #2909, and #2910.
**Changes:**
We were capable of returning incorrect information for arrays which do not have `int64_t` dimensions. However, passing status on all Python/R-level unit tests shows that this is a safe and non-breaking change.
This PR should be approved and merged before #2911. Then #2915 can be rebased on top of the new `main`.

[c++] Remove some dead code in int64-only shape accessor

---

libtiledbsoma/test/common.cc

**Issue and/or context:** This is a line-count-reducing under-diff followingon #2919 for issue #2407 / [[sc-51048]](https://app.shortcut.com/tiledb-inc/story/51048).
**Changes:**
Just some prep for my next step to unit-test #2916 and #2917, namely, we need libtiledbsoma-level support for variant-indexed dataframes (those whose dim is something other than a single int64).
#2785 is unreviewable as-is: besides being a WIP, it's an all-in-one experimental area. Smaller PRs such as this one are being offered for manageable review.

[c++] Pre-neatens before making unit-test helpers for variant-indexed dataframes

---

libtiledbsoma/test/unit_soma_collection.cc

**Issue and/or context:** This is a line-count-reducing under-diff following on #2911 for issue #2407 / [[sc-51048]](https://app.shortcut.com/tiledb-inc/story/51048).
**Changes:**
This is more in the vein of https://github.com/single-cell-data/TileDB-SOMA/pull/2911#discussion_r1733506115 -- I missed a few spots
Suggestion: review with the ignore-white-space option. There's not much here. :)
#2785 is unreviewable as-is: besides being a WIP, it's an all-in-one experimental area. Smaller PRs such as this one are being offered for manageable review.

[c++] More `use_current_domain` unit-test parameterization

---

.pre-commit-config.yaml
apis/python/notebooks/tutorial_spatial.ipynb
apis/python/setup.py
apis/python/src/tiledbsoma/__init__.py
apis/python/src/tiledbsoma/_coordinates.py
apis/python/src/tiledbsoma/_images.py
apis/python/src/tiledbsoma/_point_cloud.py
apis/python/src/tiledbsoma/_scene.py
apis/python/src/tiledbsoma/experimental/ingest.py
apis/python/tests/test_coordinates.py

This removes the `Axis`, `CoordinateSpace`, and `CoordinateTransform` classes from TileDB-SOMA and instead imports them from somacore. It also replaces the return type of `AffineTransform` with `ScaleTransform` when getting transformations of the levels of the `Image2DCollection` (soon to be `MultiscaleImage`).

Move CoordinateSpace and CoordinateTransform to SOMA

---

apis/python/src/tiledbsoma/_experiment.py

Hotfix to just update example embedded in doc str of `tiledbsoma.Experiment`
**Changes:**

[python] Fix ref to method in docstring example

---

libtiledbsoma/test/unit_soma_dense_ndarray.cc
libtiledbsoma/test/unit_soma_sparse_ndarray.cc

**Issue and/or context:** This follows on #2945 for issue #2407 / [[sc-51048]](https://app.shortcut.com/tiledb-inc/story/51048). Here we implement `resize`.
**Changes:**
Given the improved fixturing for `libtiledbsoma`, it's now a short hop to implement unit-test coverage for `resize` in these two classes.

[c++] Unit-test `resize` for `SparseNDArray` and `DenseNDArray`

---

libtiledbsoma/test/unit_soma_dataframe.cc

**Issue and/or context:** This is an underdiff split beneath #2944 for issue #2407 / [[sc-51048]](https://app.shortcut.com/tiledb-inc/story/51048). 
**Changes:**
While I made a test fixture on #2944 for the new unit-test cases there, I realized the same fixture applied to existing test-cases.
This PR separates out from #2944 the fixture itself, and the keystroke-reduction for existing unit tests. This allows the reviewer to focus solely on the fixture and the refactor without being distracted by any new cases.

[c++] Make a Catch2 test fixture for dataframes

---

libtiledbsoma/src/soma/soma_array.h
libtiledbsoma/src/utils/arrow_adapter.cc
libtiledbsoma/test/common.cc
libtiledbsoma/test/unit_soma_dataframe.cc

**Issue and/or context:** This is iterative progress for issue #2407 / [[sc-51048]](https://app.shortcut.com/tiledb-inc/story/51048). 
**Changes:**
Leverages #2939 and #2945 to unit-test variant-indexed soma dataframes at the `libtiledbsoma` level.
No shape-accessor logic is checked on this PR: see #2916.
No resize logic is checked on this PR: see #2917.

[c++] Unit-test variant-indexed dataframes

---

libtiledbsoma/src/soma/soma_array.cc
libtiledbsoma/src/soma/soma_array.h
libtiledbsoma/test/unit_soma_dense_ndarray.cc
libtiledbsoma/test/unit_soma_sparse_ndarray.cc

**Issue and/or context:** As tracked on issue #2407 / [[sc-51048]](https://app.shortcut.com/tiledb-inc/story/51048). 
**Changes:**
Implements the `upgrade_shape` method at the C++ level.

[c++] Implement `upgrade_shape` for `SparseNDArray` and `DenseNDArray`

---

libtiledbsoma/src/soma/soma_array.cc
libtiledbsoma/src/soma/soma_array.h
libtiledbsoma/src/soma/soma_dataframe.cc
libtiledbsoma/src/soma/soma_dataframe.h
libtiledbsoma/test/unit_soma_dataframe.cc

**Issue and/or context:** This is iterative progress for issue #2407 / [[sc-51048]](https://app.shortcut.com/tiledb-inc/story/51048). 
**Changes:**
While iterating at the application level (#2950) I realized I'd needlessly confused myself with the accessors to get a dataframe's shape/maxshape along the `soma_joinid` dimension (if it has one).
These clarify the picture.
In this PR these methods are unit-tested against their stated semantics. They'll get put to work in a PR split out from #2950.

[c++] Clarify dataframe-shaping test/access points

---

libtiledbsoma/src/soma/soma_group.cc

As discussed over DMs, the check for 'absolute vs relative' URLs was not checking for leading slashes as on local filesystems.
**Changes:**
The check has been expanded.  
[SC 54529](https://app.shortcut.com/tiledb-inc/story/54529/c-generalize-relative-vs-absolute-check-for-group-url)

[c++] Also check for leading slash when checking for 'relative' URLs

---

apis/python/src/tiledbsoma/_common_nd_array.py
apis/python/src/tiledbsoma/_dataframe.py
apis/python/src/tiledbsoma/_tdb_handles.py
apis/python/src/tiledbsoma/soma_dataframe.cc
apis/python/src/tiledbsoma/soma_dense_ndarray.cc
apis/python/src/tiledbsoma/soma_sparse_ndarray.cc
apis/python/tests/test_dataframe.py
apis/python/tests/test_shape.py
apis/python/tests/test_sparse_nd_array.py
apis/r/R/RcppExports.R
apis/r/R/SOMADataFrame.R
apis/r/R/SOMANDArrayBase.R
apis/r/R/TileDBArray.R
apis/r/src/RcppExports.cpp
apis/r/src/rinterface.cpp
apis/r/tests/testthat/test-SOMASparseNDArray.R
apis/r/tests/testthat/test-shape.r
libtiledbsoma/src/soma/soma_array.h
libtiledbsoma/src/soma/soma_dataframe.cc
libtiledbsoma/src/soma/soma_dataframe.h
libtiledbsoma/test/unit_soma_collection.cc
libtiledbsoma/test/unit_soma_sparse_ndarray.cc

**Changes:**
* These accessors are already implemented and unit-tested in C++
* On this PR, I expose only the language bindings as-is with minimal unit-testing -- more unit-testing to follow (including feature-flag logic) as tracked on #2407 
* The `_maybe_sjid_shape` and `_maybe_sjid_maxshape` accessors will be crucial for experiment-level resize logic as on append mode, which does not yet exist in TileDB-SOMA-R (see #1630)

[python/r] Expose shape-related accessors to Python/R bindings

---

apis/python/src/tiledbsoma/__init__.py
apis/python/src/tiledbsoma/pytiledbsoma.cc
apis/python/src/tiledbsoma/stats.py
apis/python/tests/test_stats.py

**Issue and/or context:** [[sc-54474]](https://app.shortcut.com/tiledb-inc/story/54474/python-tiledb-stats-dump-needs-ability-to-return-stats-as-a-data-structure)
**Changes:**
`tiledbsoma_stats_dump` prints to stdout, with a header. We should have an option to get just the JSON, as a string.
Demo:
```
>>> print(tiledbsoma.tiledbsoma_stats_json())
[
{
"timers": {
"Context.StorageManager.load_group_from_all_uris.sum": 0.00176317,
"Context.StorageManager.load_group_from_all_uris.avg": 0.000440792,
"Context.StorageManager.load_group_details.sum": 0.00189163,
"Context.StorageManager.load_group_details.avg": 0.000472906,
"Context.StorageManager.group_open_for_reads.sum": 0.00189546,
"Context.StorageManager.group_open_for_reads.avg": 0.000473865, …
```

[python] Expose tiledbsoma stats as JSON string or Python-parsed

---

apis/python/src/tiledbsoma/_dataframe.py
apis/python/src/tiledbsoma/_soma_array.py
apis/python/src/tiledbsoma/_tdb_handles.py
apis/python/src/tiledbsoma/soma_array.cc
libtiledbsoma/src/soma/soma_array.h

**Changes:**
* Exposed SOMA-level `domain` and `maxdomain` to Python
* Reduce name-confusion in C++ via explicit and well-commented delgation
There is no R counterpart on this PR (compare #2951 which is at parity):
* TileDB-SOMA-R has no `domain` accessor for arrays, and so nothing to put a `maxdomain` next to
* TileDB-SOMA-R is still [going through TileDB-R](https://github.com/single-cell-data/TileDB-SOMA/blob/1e2b13170bfc905483365549fe904cf93e472922/apis/r/R/TileDBArray.R#L132-L137), not libtiledbsoma, for its `$dimensions()` accessor
* Also note …

[c++/python] Map core-to-soma domains correctly

---

apis/r/DESCRIPTION
apis/r/NEWS.md
apis/r/R/CoordsStrider.R
apis/r/R/SOMASparseNDArrayRead.R
apis/r/tests/testthat/test-Blockwise.R

When using the blockwise iterator, I get the following error on the last iteration's read:
```
Error: Subarray: Cannot add range to dimension 'soma_dim_0'; Range [2638, 2638] is out of domain bounds [0, 2637]
```
It turns out we were not handling 0-based coordinates correctly. When creating a new blockwise read, we would start at 0L, but then go up to `array$shape()[dimension]`, which is a 1-indexed value. This needed to be corrected to `array$shape()[dimension] - 1L`
However, this messed up calculating a dimension for the returning matrix; to get around this, if `coords$start == 0L`, we increase the length of the coords by 1 (eg. if the coordinates run from `[0, 499]`, then the length should be 500, not 499)
- `SOMASparseNDArray$new()`: decrease the end of the …

[r] Fix bug in blockwise iterator

---

apis/python/src/tiledbsoma/pytiledbsoma.cc
apis/python/src/tiledbsoma/soma_array.cc
apis/python/tests/test_dataframe.py
apis/python/tests/test_dataframe_index_columns.py
apis/python/tests/test_dense_nd_array.py
apis/python/tests/test_shape.py
apis/python/tests/test_sparse_nd_array.py

**Issue and/or context:** Resolves #2961 
**Changes:**
Do explicit try-catch. See also #783.
It's not necessarily causal that this triggered on https://github.com/jdblischak/centralized-tiledb-nightlies/issues/21. It's true that the `apis/python/tests/test_shape.py` was recently introduced on the #2407 stack. However, whether un-rethrown errors (on implicit pybind body, as in the "before" parts of this PR) reach the Python level as `tiledbsoma.SOMAError` or `RuntimeError` or `tiledb.cc.TileDBError` has some element of randomness.
There's an attempt to globally register a rethrow:
https://github.com/single-cell-data/TileDB-SOMA/blob/1.13.1/apis/python/src/tiledbsoma/pytiledbsoma.cc#L36-L50
However, @nguyenv and I have long found that some things come through as …

[python] Fix nightly-build failure

---

apis/python/src/tiledbsoma/_tdb_handles.py
apis/python/src/tiledbsoma/soma_array.cc

**Changes:**
This is a minor deconfuse as I was trying to understand `SOMADataFrame`'s `domain` and `maxdomain` on the Python side in prep to port them to R.
This is follow-on to #2957: this is a spot I missed there, and should (ideally) have done on that PR.

[python] Minor name-neaten in internals for `domain`/`maxdomain`

---

apis/r/R/SOMADenseNDArray.R
apis/r/tests/testthat/test-SOMADenseNDArray.R

**Issue and/or context:** Found while debugging an issue with #2950 for issue #2407 / [[sc-51048]](https://app.shortcut.com/tiledb-inc/story/51048).
**Changes:**
Make it possible to write to a `DenseNDArray` using an open-for-write after the array is created.
Note that the create methods return an array opened for write.
For `SparseNDArray` and `DenseNDArray` you can do:
* create
* write data
* close the handle from create
For `SparseNDArray`, you can do:
* create
* close the handle from create
* open for write
* write data
* close the handle from open
For `DenseNDArray`, this does not work before this PR. The error message is
```
Error: soma_data must be a DataType, not NULL
```
You can reproduce this by including in your checkout the mod to …

[r] Fix `DenseNDArray` write after create

---

apis/python/src/tiledbsoma/soma_array.cc

**Issue and/or context:** A minor item on issue #2407 / [[sc-51048]](https://app.shortcut.com/tiledb-inc/story/51048).
**Changes:**
Since `SOMASparseNDArray` and `SOMADenseNDArray` have `shape` while `SOMADataFrame` has `domain`, what's exposed in Python is correct. However we have a dangling/unused `pybind11` hook for `SOMAArray`.
```
$ grep '"shape"' *.cc
soma_array.cc:        .def_property_readonly("shape", &SOMAArray::shape)
soma_dense_ndarray.cc:        .def_property_readonly("shape", &SOMADenseNDArray::shape)
soma_sparse_ndarray.cc:        .def_property_readonly("shape", &SOMASparseNDArray::shape)

[python] Trivial dead-strip

---

apis/r/tests/testthat/test-SOMASparseNDArray.R

Paul and I both found a test having hiccups. The issue appears to be a `_true` missing, and the indexing can be done as vectors too as opposed to lists (single set of brackets).
**Changes:**
Correct one line. 
No new code. No new tests.
[SC 54879](https://app.shortcut.com/tiledb-inc/story/54879/r-correct-a-test-expression)

[r] Correct a test expression

---

.github/workflows/python-ci-single.yml
.github/workflows/r-ci.yml
apis/python/src/tiledbsoma/__init__.py
apis/python/src/tiledbsoma/_dataframe.py
apis/python/src/tiledbsoma/_sparse_nd_array.py
apis/python/src/tiledbsoma/soma_array.cc
apis/python/tests/test_dataframe.py
apis/python/tests/test_shape.py
apis/python/tests/test_sparse_nd_array.py
apis/r/R/Init.R
apis/r/R/SOMANDArrayBase.R
apis/r/R/utils-arrow.R
apis/r/tests/testthat/test-SOMASparseNDArray.R
apis/r/tests/testthat/test-shape.r

**Changes:**
* Array-creation mods including the crucial arrow-table link are already bullet-proof tested in C++ on #2911 
* More unit-test cases for Python and R are upcoming on #2407
* The status-quo code and the opt-in to-be-released-later code are both tested in CI
* There are further upcoming PRs as tracked on #2407

[python/r] Array-creation mods for new shape

---

apis/python/src/tiledbsoma/common.h
apis/python/src/tiledbsoma/pytiledbsoma.cc
apis/python/src/tiledbsoma/reindexer.cc
apis/python/src/tiledbsoma/soma_array.cc
apis/python/tests/test_dataframe.py
apis/python/tests/test_indexer.py

**Issue and/or context:** [[sc-54978]](https://app.shortcut.com/tiledb-inc/story/54978/tiledbsomaerror-exceptions-from-c-layer-show-up-as-runtimeerror-in-macos)
**Changes:**
* Continues #2963. I missed a couple spots.
* Also fixes a couple spots that were leading to `RuntimeError` on @bkmartinjr 's #2978. (I applied this PR on top of 2978 in my Mac sandbox & observed no more `RuntimeError`.)
* As a neaten (could be a separate PR), `TileDBSOMAPyError` is redundant with `TileDBSOMAError` (multiple-author syndrome I suspect) -- the two serve identical roles and are coalesced on this PR.

[c++/python] More exception-mapping fixes

---

libtiledbsoma/src/soma/managed_query.cc
libtiledbsoma/src/soma/managed_query.h
libtiledbsoma/src/soma/soma_array.cc
libtiledbsoma/src/soma/soma_array.h

[[sc-54744]](https://app.shortcut.com/tiledb-inc/story/54744/python-soma-read-does-an-open-on-an-already-open-array)
https://github.com/single-cell-data/TileDB-SOMA/pull/2975
This is the first of multiple PRs that will be split out from above
**Changes:**
The `ArrayBuffers` are now fully managed by `ManagedQuery` and not `SOMAArray`

[c++] Remove `ArrayBuffers` from `SOMAArray`

---

libtiledbsoma/src/soma/soma_array.cc
libtiledbsoma/src/soma/soma_array.h

https://github.com/single-cell-data/TileDB-SOMA/pull/2975
This is the second of multiple PRs that will be split out from above
**Changes:**
This is just code reorganization for cleaning up switch-case statements. Create specialized templates for types that need special handling when casting into write buffers. For strings, we need to deal with different size offset buffers depending on whether the user passed in `large_string` or regular `string`. For Boolean, we need to convert from Arrow (bit) to TileDB (`uint8_t`) representation.

[c++] Create specialized templates for `SOMAArray` casting functions

---

.pre-commit-config.yaml
apis/python/setup.py

**Issue and/or context:** [[sc-51048]](https://app.shortcut.com/tiledb-inc/story/51048)
**Changes:**
Brings in https://github.com/single-cell-data/SOMA/releases/tag/python-v1.0.15 which has https://github.com/single-cell-data/SOMA/pull/216

[python] Use `somacore` 1.0.15

---

libtiledbsoma/src/soma/column_buffer.cc
libtiledbsoma/src/soma/column_buffer.h

https://github.com/single-cell-data/TileDB-SOMA/pull/2975
This is the third of multiple PRs that will be split out from above
**Changes:**
- Replace [this](https://github.com/single-cell-data/TileDB-SOMA/blob/main/libtiledbsoma/src/soma/managed_query.cc#L96-L216) in `ManagedQuery::set_column_data` and move the steps into `ColumnBuffer::attach_subarray` (for writing dimension on dense arrays) and `ColumnBuffer::attach_buffer` (for all other cases)
- Condense `ColumnBuffer::set_data` into a templated function that only accepts `uint64_t` and `uint32_t`
The changes aren't actually used by `SOMAArray` yet in this PR

[c++] Support writes when attaching `Query` to `ColumnBuffer`

---

apis/r/DESCRIPTION
apis/r/NEWS.md
apis/r/R/TileDBGroup.R
apis/r/R/TileDBObject.R
apis/r/tests/testthat/test-TileDBGroup.R

Cache a SOMA context during `$new()` as a private field when instantiating new objects. This cached context can then be used in other methods. Note, this PR is not yet changing the UX of config/context options. As the context from `soma_context()` is cached globally, we can modify the global one before instantiating to test customized cached contexts
- `TileDBObject$new()`: creates context and caches it within the object
- `TileDBGroup$create()`: no longer caches context, instead uses cached context from `$new()`
- `TileDBGroup$open()`: uses cached context rather than calling `soma_context()`
[SC-55084](https://app.shortcut.com/tiledb-inc/story/55084/)

[r] Use cached SOMA context rather than re-creating

---

apis/r/R/SOMADataFrame.R
apis/r/src/rutilities.cpp

This fairly narrow PR provides a small usage improvement when logging level 'info' is used to test during development (which can be turned on easily now via environment variable `SPDLOG_LEVEL`) as it lowers a few older entries from 'info' to 'debug'.  (Some still remain in other helper files. They can be addressed at a later date.)
**Changes:**
Substitute level 'debug' for 'info' in about a dozen spots.  
No new code, no new tests.
[SC 55110](https://app.shortcut.com/tiledb-inc/story/55110/r-lower-a-remaining-logging-item-from-info-to-debug)

[r] Lower some logging from 'info' to 'debug'

---

libtiledbsoma/src/soma/soma_array.cc
libtiledbsoma/src/soma/soma_array.h
libtiledbsoma/src/utils/util.cc
libtiledbsoma/src/utils/util.h

https://github.com/single-cell-data/TileDB-SOMA/pull/2989#discussion_r1759112933
**Changes:**
Move `cast_bit_to_uint8` from `SOMAArray` to `util`

[c++] Move `cast_bit_to_uint8` into `util`

---

apis/python/tests/test_dataframe.py
libtiledbsoma/src/soma/soma_array.cc

https://github.com/single-cell-data/TileDB-SOMA/pull/2989#discussion_r1759104645
**Changes:**
Always call remap indexes even if no new enumerations were added. These were done correctly in the specialized templates for string and Boolean types but needed to be added for the general case as well. Also add unit tests in Python to check for string and integer category value types.

[c++] Remap indexes even if no new enums were added

---

apis/r/R/Init.R
apis/r/R/RcppExports.R
apis/r/man/delete_metadata.Rd
apis/r/man/get_all_metadata.Rd
apis/r/man/get_metadata.Rd
apis/r/man/get_metadata_num.Rd
apis/r/man/has_metadata.Rd
apis/r/src/metadata.cpp

`R CMD check` was nagging about some missing fields as well as one undefined global
**Changes:**
Injected missing `is_arrow` documentation, removed one stale/unused assignment with a missing global and re-ran `roxygenize()` to refresh Rd files.
`R CMD check` is now down to complaining about `tiledb` being too frequently in Depends, Imports, Suggests or Enhances (which get taken care of) and a pair of missing Rd cross-references, which is in sum a lot quieter.
[SC 65150](https://app.shortcut.com/tiledb-inc/story/55150/r-package-documentation-refresher_

[r] Documentation refresher

---

apis/python/src/tiledbsoma/_dense_nd_array.py
apis/python/src/tiledbsoma/_util.py
apis/python/src/tiledbsoma/options/_tiledb_create_write_options.py

**Issue and/or context:** Resolves #2579. See also #2999 and [[sc-53002]](https://app.shortcut.com/tiledb-inc/story/53002/update-projects-to-tiledb-2-26).
**Changes:**

[python] Post-deprecation removal of `consolidate_and_vacuum` from `TileDBCreateOptions`

---

libtiledbsoma/src/utils/arrow_adapter.cc
libtiledbsoma/src/utils/arrow_adapter.h
libtiledbsoma/test/common.cc
libtiledbsoma/test/unit_soma_array.cc
libtiledbsoma/test/unit_soma_collection.cc
libtiledbsoma/test/unit_soma_dataframe.cc
libtiledbsoma/test/unit_soma_dense_ndarray.cc
libtiledbsoma/test/unit_soma_sparse_ndarray.cc

**Changes:**
Extracting readback of core domain, current domain, and non-empty domain are all currently:
* Done slotwise within `libtiledbsoma`, templatized;
* For Python: there is a loop over dim names in the `pybind11` layer lke this https://github.com/single-cell-data/TileDB-SOMA/blob/b3feada0d1282442d1190f56a43670a32dad97ae/apis/python/src/tiledbsoma/soma_array.cc#L671-L830;
* For R: currently these are using TileDB-R -- which is a dependency we're currently removing -- and I don't want to imitate the above in R
The best option for Python/R interop is:
* Push down loop-over-dim-names to `libtiledbsoma`
* Make more use of `nanoarrow` to interface with Python and R
The …

[c++] Centralize some `nanoarrow` helpers

---

.github/workflows/python-ci-packaging.yml
apis/r/tools/get_tarball.R
libtiledbsoma/cmake/Modules/FindTileDB_EP.cmake
scripts/bld

As always, core artifacts were updated using the error-proof and automated `./scripts/update-tiledb-version.py 2.26.1`.

[c++] Use core 2.26.1

---

libtiledbsoma/src/utils/arrow_adapter.h

Addresses https://github.com/single-cell-data/TileDB-SOMA/actions/runs/10900533993/job/30248339956
Since this only failed in the nightly `pkgdown` run, I manually ran that on this PR's branch:
* https://github.com/single-cell-data/TileDB-SOMA/actions/workflows/pkgdown.yaml
* https://github.com/single-cell-data/TileDB-SOMA/actions/runs/10904361981 -- ✅

[c++/r] Fix `pkgdown` build errors

---

apis/python/setup.py
apis/python/src/tiledbsoma/__init__.py

Long-awaited work coming to fruition:
* https://github.com/single-cell-data/TileDB-SOMA/issues/1849
* https://github.com/single-cell-data/TileDB-SOMA/pull/2692
* https://github.com/single-cell-data/TileDB-SOMA/pull/2734
* https://github.com/TileDB-Inc/TileDB/pull/5223 went into [core 2.26](https://github.com/TileDB-Inc/TileDB/releases/tag/2.26.0), making this possible
See also https://github.com/single-cell-data/TileDB-SOMA/issues/2999 [[sc-53002]](https://app.shortcut.com/tiledb-inc/story/53002/update-projects-to-tiledb-2-26)

[python] Remove `pyarrow` pin on MacOS

---

apis/r/DESCRIPTION
apis/r/NEWS.md
apis/r/R/SOMASparseNDArrayRead.R

Add checks to ensure that `axis` is a valid axis when initializing a sparse blockwise read
- `SOMASparseNDArrayBlockwiseRead()`: add value and type checking for `axis`
[SC-55366](https://app.shortcut.com/tiledb-inc/story/55366/)

[r] Add `axis` checks when initializing a sparse blockwise read

---

apis/python/src/tiledbsoma/options/_soma_tiledb_context.py
apis/python/src/tiledbsoma/options/_tiledb_create_write_options.py

**Issue and/or context:** #2998 was (it turns out) incomplete and did not fail until after [1.14.0](https://github.com/single-cell-data/TileDB-SOMA/releases/tag/1.14.0) was tagged. :(
See also #2999 [[sc-53002]](https://app.shortcut.com/tiledb-inc/story/53002/update-projects-to-tiledb-2-26)
**Changes:**

[python] Fix deprecation warnings

---

apis/python/src/tiledbsoma/options/_soma_tiledb_context.py
apis/python/src/tiledbsoma/options/_tiledb_create_write_options.py

Sibling for `main` of #3013 for `release-1.14`
Fixes https://github.com/single-cell-data/TileDB-SOMA/actions/runs/10912549693/job/30287424101#step:13:6876
See also #2999 [[sc-53002]](https://app.shortcut.com/tiledb-inc/story/53002/update-projects-to-tiledb-2-26

[python] Fix deprecation warnings [main]

---

Makefile
apis/python/src/tiledbsoma/_dataframe.py
libtiledbsoma/src/soma/soma_array.h
libtiledbsoma/test/unit_soma_dataframe.cc

This is split out from #2995 to make 2995 simpler.
These are higher-line-count mods, which would distract from the more substantive mods on 2995.
**Changes:**

[c++] Pre-neatens for polymorphic domainish accessors

---

libtiledbsoma/test/unit_soma_dataframe.cc

**Changes:**
Split-out underneath #3012

[c++] Update dataframe unit-test writes in prep for polytype domainish accessors

---

libtiledbsoma/src/utils/arrow_adapter.cc
libtiledbsoma/src/utils/arrow_adapter.h
libtiledbsoma/test/CMakeLists.txt
libtiledbsoma/test/common.cc
libtiledbsoma/test/unit_arrow_adapter.cc
libtiledbsoma/test/unit_soma_dataframe.cc

**Changes:**
This is atop #3017

[c++] Readback-testing pieces for polytype domainish accessors

---

libtiledbsoma/src/soma/soma_array.cc
libtiledbsoma/test/unit_soma_dataframe.cc

**Issue and/or context:** Pre-existing bug found while working on issue #2407 / [[sc-51048]](https://app.shortcut.com/tiledb-inc/story/51048).
I ran `sdf.count()` on a variant-indexed dataframe which has dim0 being a string (which [the spec](https://github.com/single-cell-data/SOMA/blob/main/abstract_specification.md) allows even though most users don't take advantage of this). I got the error
```
[TileDB::FragmentInfo] Error: Cannot get non-empty domain; Dimension is variable-sized
```
There is a repro now built into the unit-test cases on this PR.
**Changes:**
Only use the code that assumes dim0 is `int64` `soma_joinid` when that is in fact the case.

[c++] Fix bug in `nnz` of variant-indexed dataframes

---

libtiledbsoma/test/unit_soma_dataframe.cc

**Changes:**
@jp-dark pointed out we should have a test case where `soma_joinid` is a dim but is not the first one.

[c++] Have a `DataFrame` test case with `soma_joinid` not first

---

apis/python/src/tiledbsoma/_tdb_handles.py
apis/python/src/tiledbsoma/soma_array.cc

**Changes:**
Leveraging PRs on #2407 the full domain will be gotten from C++ `libtiledbsoma` with a simple cast in the `pybind11`/`Rcpp` layers.
However I missed one naming spot in the `pybind11` layer.

[python] One more rename in prep for domainish pushdown

---

libtiledbsoma/src/soma/soma_array.h
libtiledbsoma/test/unit_soma_dataframe.cc

**Changes:**
Found while porting domainish accessors to Python on the WIP #3027.
Reasoning is as commented within `soma_array.h`.

[c++] Improve current-domain signaling for string dims

---

apis/python/src/tiledbsoma/_collection.py
apis/python/src/tiledbsoma/_soma_group.py
apis/python/tests/test_collection.py

**Issue:**  #3023
**Changes:** This change moves functionality from the python `Collection` class into a new `Group` class. This is a precursor for the new `MultiscaleImage` class that is a TileDB group, but not a SOMA `Collection`
**Notes for Reviewer:** This change is primarily code movement.

[python] Create `Group` base class for `Collection`

---

apis/python/src/tiledbsoma/_arrow_types.py
apis/python/tests/test_arrow_type.py

Prevent extra index column from being added to pandas dataframe generated schema.

[python] Drop extra index array schema name

---

apis/python/src/tiledbsoma/_multiscale_image.py
apis/python/src/tiledbsoma/_point_cloud.py

The transformation argument in the `read_region` is easy to misinterpret. Add an explicit check for the correct `output_axes` in the transform for better error messaging.

[spatial] Add ValueError for mismatched transform names

---

apis/python/src/tiledbsoma/experimental/ingest.py

Previously, the code was using hard-coded paths that assumed a posix-like structure. Update to use helper function for joining paths.

Fix URI creation in spatial ingest

---

apis/r/src/arrow.cpp
apis/r/src/groups.cpp
apis/r/src/metadata.cpp
apis/r/src/reindexer.cpp
apis/r/src/rinterface.cpp
apis/r/src/riterator.cpp
apis/r/src/rutilities.cpp
apis/r/src/soma.cpp

While working on #2407 / [[sc-51048]](https://app.shortcut.com/tiledb-inc/story/51048) and #2406.
This was fully automated via
```
clang-format -i  apis/r/src/[a-z]*.cpp
```
with the exception of a couple fix-ups on `//'`-style comments.
Note that we enitrely avoid `apis/r/src/RcppExports.cpp` which is auto-generated.
On this PR I just manually ran the formatter on the relevant source files. On a follow-up PR I'll stop excluding these files from the format-checker which we run on the rest of our `libtiledbsoma` and `pybind11` C++ source:
https://github.com/single-cell-data/TileDB-SOMA/blob/1.14.1/.github/workflows/python-ci-single.yml#L62-L64
Also note that we should move the `clang-format` checker from `python-ci-single.yml` to another C++-specific YAML file.

[r] Run `clang-format` on `apis/r/src`

---

apis/r/R/RcppExports.R
apis/r/R/TileDBArray.R
apis/r/src/RcppExports.cpp
apis/r/src/rinterface.cpp

**Issue and/or context:** #3058
**Changes:**

[r] Push `ndim` down to C++

---

.pre-commit-config.yaml
apis/python/setup.py

**Issue and/or context:** #3064 -- includes https://github.com/single-cell-data/SOMA/pull/229
**Changes:**

[python] Use `somacore` 1.0.17

---

.github/workflows/python-packaging.yml
apis/python/pyproject.toml

**Issue and/or context:** https://github.com/single-cell-data/TileDB-SOMA/issues/3072
Daily "TileDB-SOMA python sdist & wheels" workflow was still attempting to use Python 3.8, and failed.

[python] Remove more Python 3.8 references

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/workflows/python-ci-full.yml
.github/workflows/python-ci-minimal.yml
.github/workflows/python-packaging.yml
.pre-commit-config.yaml
apis/python/pyproject.toml
apis/python/setup.py
apis/python/src/tiledbsoma/io/ingest.py
apis/r/DESCRIPTION
apis/r/NEWS.md

This contains backports of #3021 #3070 #3073. Done as a  single PR to reduce CI burden.
[[sc-56256]](https://app.shortcut.com/tiledb-inc/story/56256/tiledb-soma-1-14-2)

Bulk-backport Python 3.8 and `somacore` 1.0.17 mods to `release-1.14` branch

---

apis/r/tests/testthat/helper-test-data.R
apis/r/tests/testthat/helper-test-soma-objects.R
apis/r/tests/testthat/test-Arrow-utils.R
apis/r/tests/testthat/test-EphemeralCollection.R
apis/r/tests/testthat/test-Factory.R
apis/r/tests/testthat/test-SCEOutgest.R
apis/r/tests/testthat/test-SOMAAxisQuery.R
apis/r/tests/testthat/test-SOMACollection.R
apis/r/tests/testthat/test-SOMADataFrame.R
apis/r/tests/testthat/test-SOMAExperiment-query-m-p.R
apis/r/tests/testthat/test-SOMAExperiment-query-matrix-outgest.R
apis/r/tests/testthat/test-SOMAExperiment-query.R
apis/r/tests/testthat/test-SOMAExperiment.R
apis/r/tests/testthat/test-SeuratOutgest-assay.R
apis/r/tests/testthat/test-SeuratOutgest-graph.R
apis/r/tests/testthat/test-SeuratOutgest-object.R
apis/r/tests/testthat/test-SeuratOutgest-reduction.R
apis/r/tests/testthat/test-TileDBArray.R
apis/r/tests/testthat/test-TileDBCreateOptions.R
apis/r/tests/testthat/test-TileDBGroup.R
apis/r/tests/testthat/test-shape.R
apis/r/tests/testthat/test-utils-uris.R
apis/r/tests/testthat/test-utils.R

**Issue and/or context:** The names `foo` `bar` `baz` are giving me some context-switching headaches -- which one is the string again? This PR simply makes the names of the attributes say what they are.
Part of #2407 / [[sc-51048]](https://app.shortcut.com/tiledb-inc/story/51048).

[r] Improve test-case field names for `DataFrame`

---

apis/r/R/RcppExports.R
apis/r/R/TileDBArray.R
apis/r/src/RcppExports.cpp
apis/r/src/rinterface.cpp

**Issue and/or context:** #3058, first of a few PRs here
**Changes:**

[r] Push `dimnames` down to C++

---

libtiledbsoma/src/soma/soma_array.cc
libtiledbsoma/test/unit_soma_dataframe.cc
libtiledbsoma/test/unit_soma_sparse_ndarray.cc

**Changes:**
For various debugs a while back I'd apparently left some Catch2 flags to on or off vs. looping over both. This PR fixes those overssights.

[c++] Extend some unit-test cases for new shape

---

.github/workflows/pkgdown.yaml

**Issue and/or context:** Address some warnings in [pkgdown GHA](https://github.com/single-cell-data/TileDB-SOMA/actions/workflows/pkgdown.yaml) ([example](https://github.com/single-cell-data/TileDB-SOMA/actions/runs/11058461787))
- Neither [setup-pandoc@v1] nor [setup-r@v2](https://github.com/r-lib/actions/blob/v2/setup-r/action.yml) takes a `working-directory` input
- [setup-pandoc@v1] is deprecated; bumping to `@v2`
How can I verify that bumping to [setup-pandoc@v2] is a no-op?
I've manually run it against this PR [here](https://github.com/single-cell-data/TileDB-SOMA/actions/runs/11059535835/job/30728069442).
[setup-pandoc@v1]: https://github.com/r-lib/actions/blob/v1/setup-pandoc/action.yml
[setup-pandoc@v2]: …

[r] Address some pkgdown GHA warnings

---

apis/python/src/tiledbsoma/_dataframe.py
apis/python/src/tiledbsoma/_tdb_handles.py
apis/python/src/tiledbsoma/soma_array.cc
apis/r/R/RcppExports.R
apis/r/R/SOMADataFrame.R
apis/r/R/TileDBArray.R
apis/r/R/utils-arrow.R
apis/r/src/RcppExports.cpp
apis/r/src/rinterface.cpp
apis/r/src/rutilities.cpp
apis/r/src/rutilities.h
apis/r/tests/testthat/test-shape.R
libtiledbsoma/src/soma/soma_array.cc
libtiledbsoma/src/utils/arrow_adapter.cc
libtiledbsoma/src/utils/arrow_adapter.h
libtiledbsoma/test/common.cc
libtiledbsoma/test/common.h
libtiledbsoma/test/unit_arrow_adapter.cc
libtiledbsoma/test/unit_soma_collection.cc
libtiledbsoma/test/unit_soma_dataframe.cc
libtiledbsoma/test/unit_soma_dense_ndarray.cc
libtiledbsoma/test/unit_soma_sparse_ndarray.cc

See also [[sc-55659]](https://app.shortcut.com/tiledb-inc/story/55659/r-current-domain-tasks).
**Changes:**
Following #3012 we can now connect tiledbsoma-py to use the full domainish accessors from `libtiledbsoma`.
R mods to come on this same PR.
This PR is a work in progress. It is not ready for review.

[python/r] Use pushdown domainish accessors at the Python/R UX level

---

.github/workflows/python-ci-single.yml

Mitigate excessive logspam on PRs where many tests fail.
Multiple GHAs recently have failed with a huge amount of logspam, such that my browser tab never finishes loading the page, or any of the logs.
[Here's](https://github.com/single-cell-data/TileDB-SOMA/actions/runs/10910221889/job/30280188276) an example, from #3001; downloading its logs:
```bash
j=30280188276
gh run view -j $j --log > $j.txt
```
Shows 472k lines / 77MiB. It looks like 482 test failures, some of which output ≈700 lines each.
The PRs where I've seen this recently have generally involved changing Python or Typeguard versions; Typeguard issues can cause large numbers of test cases to fail very verbosely.
[This gist](https://gist.github.com/ryan-williams/2206c5b05050ac9d786ad5b20bd5ddf8) has the first 10,000 lines from …

[python] add `--maxfail=50` to GHA `pytest` invocations

---

.pre-commit-config.yaml
apis/python/setup.py
apis/python/src/tiledbsoma/_constants.py
apis/python/src/tiledbsoma/_experiment.py
apis/python/src/tiledbsoma/_geometry_dataframe.py
apis/python/src/tiledbsoma/_measurement.py
apis/python/src/tiledbsoma/_multiscale_image.py
apis/python/src/tiledbsoma/_point_cloud.py
apis/python/src/tiledbsoma/_scene.py

This PR updates somacore and adds the new spatial types to TileDB-SOMA as empty classes that throw `NotImplementedErrors`.  It updates `Experiment` and `Measurement` to match the updated somacore API.
Issues: #3043 #3042

[python] Update TileDB-SOMA to use the `somacore` release with spatial datatypes

---

apis/r/man/BlockwiseReadIterBase.Rd
apis/r/man/BlockwiseSparseReadIter.Rd
apis/r/man/BlockwiseTableReadIter.Rd
apis/r/man/ConfigList.Rd
apis/r/man/EphemeralCollection.Rd
apis/r/man/EphemeralCollectionBase.Rd
apis/r/man/EphemeralExperiment.Rd
apis/r/man/EphemeralMeasurement.Rd
apis/r/man/PlatformConfig.Rd
apis/r/man/SOMAArrayBase.Rd
apis/r/man/SOMACollection.Rd
apis/r/man/SOMACollectionBase.Rd
apis/r/man/SOMAContextBase.Rd
apis/r/man/SOMADataFrame.Rd
apis/r/man/SOMADenseNDArray.Rd
apis/r/man/SOMAExperiment.Rd
apis/r/man/SOMAMeasurement.Rd
apis/r/man/SOMANDArrayBase.Rd
apis/r/man/SOMASparseNDArray.Rd
apis/r/man/SOMASparseNDArrayBlockwiseRead.Rd
apis/r/man/SOMASparseNDArrayRead.Rd
apis/r/man/SOMATileDBContext.Rd
apis/r/man/ScalarMap.Rd
apis/r/man/SparseReadIter.Rd
apis/r/man/TableReadIter.Rd
apis/r/man/TileDBArray.Rd
apis/r/man/TileDBCreateOptions.Rd
apis/r/man/TileDBGroup.Rd

On conversation with @mojaveazure I realized that while `roxygen2::roxygenise()` and `devtools::document()` both do pretty much the same thing, they differ a little -- namely, lines such as
```diff
-\code{tiledbsoma::ReadIter} -> \code{BlockwiseReadIterBase}
+\code{\link[tiledbsoma:ReadIter]{tiledbsoma::ReadIter}} -> \code{BlockwiseReadIterBase}
```
The line-count on #3032 is largeish, mainly because I did `devtools::document()` on 3032 after some prior PR had been merged with the result of `roxygen2::roxygenise()`.
Merging this PR first & rebasing 3032 on top will make 3032 simpler.
Also, @mojaveazure and I have agreed to standardize on `devtools::document()` moving forward, to simplify matters.

[r] Run `devtools::document()`

---

apis/python/src/tiledbsoma/_constants.py
apis/python/src/tiledbsoma/_factory.py
apis/python/src/tiledbsoma/_tdb_handles.py
apis/r/R/utils.R
libtiledbsoma/src/soma/soma_object.cc
libtiledbsoma/src/utils/common.h

**Changes:** 
* Update the SOMA metadata encoding to 1.1.0. 
* Update `soma_type` checks to describe spatial types as "not implemented" instead of "invalid".
**Issue:** #3045

[python/r/c++] Update allowed soma types and the metadata encoding version

---

.github/workflows/python-ci-packaging.yml
apis/python/pyproject.toml
apis/python/setup.py
doc/requirements_doc.txt

As of `wheel>=44.0.0` (Aug '24), `wheel.bdist_wheel` [warns](https://github.com/pypa/wheel/blob/0.44.0/src/wheel/bdist_wheel.py#L5-L11):
```python
warn(
"The 'wheel' package is no longer the canonical location of the 'bdist_wheel' "
"command, and will be removed in a future release. Please update to setuptools "
"v70.1 or later which contains an integrated version of this command.",
DeprecationWarning,
stacklevel=1,
)
```
I've moved us to `setuptools>=70.1` and `setuptools.command.bdist_wheel` here; hopefully this is a no-op / CI will surface any issues…

[python] Replace deprecated `wheel.bdist_wheel` with `setuptools.command.bdist_wheel`

---

libtiledbsoma/src/CMakeLists.txt
libtiledbsoma/src/soma/soma_multiscale_image.cc
libtiledbsoma/src/soma/soma_multiscale_image.h
libtiledbsoma/src/soma/soma_object.cc
libtiledbsoma/src/tiledbsoma/tiledbsoma
libtiledbsoma/test/CMakeLists.txt
libtiledbsoma/test/unit_soma_multiscale_image.cc

Add a simple C++ SOMAMultiscaleImage class to libtiledbsoma.

[c++] Add `SOMAMultiscaleImage` class

---

apis/python/src/tiledbsoma/_dataframe.py
apis/python/src/tiledbsoma/_sparse_nd_array.py
apis/python/tests/test_shape.py

**Changes:**
In Python we were trying to use default max shapes there were 31-bit friendly for R compatibility. However, in R we're already setting 63-bit maxdomain:
https://github.com/single-cell-data/TileDB-SOMA/blob/1.14.1/apis/r/R/utils-arrow.R#L127

[python] Use same default max domain between Python and R

---

.github/workflows/python-ci-packaging.yml
apis/python/pyproject.toml
apis/python/setup.py
apis/python/src/tiledbsoma/_constants.py
apis/python/src/tiledbsoma/_factory.py
apis/python/src/tiledbsoma/_tdb_handles.py
apis/r/R/utils.R
apis/r/tools/get_tarball.R
doc/requirements_doc.txt
libtiledbsoma/cmake/Modules/FindTileDB_EP.cmake
libtiledbsoma/src/CMakeLists.txt
libtiledbsoma/src/soma/soma_array.cc
libtiledbsoma/src/soma/soma_array.h
libtiledbsoma/src/soma/soma_multiscale_image.cc
libtiledbsoma/src/soma/soma_multiscale_image.h
libtiledbsoma/src/soma/soma_object.cc
libtiledbsoma/src/utils/common.h
libtiledbsoma/test/CMakeLists.txt
libtiledbsoma/test/unit_soma_dataframe.cc
libtiledbsoma/test/unit_soma_multiscale_image.cc

**Changes:**
While the full-generality `upgrade_domain` is tasked out on #2407, the foremost use-case for append mode, and `tests/testthat/test-write-soma-resume.R` for PR #3089, will need a simpller keystroke-saver which is already implemented in C++.
What this existing method does in C++ is resize the `soma_joinid` dim, if it's a dim, and leave the other dims as-is; if `soma_joinid` is not a dim, leave it as-is. This exists in C++, it's unit-tested in C++, and it's ready (and it's time) to be plumbed up to Python and R as well.
I realize now that having C++ …

[c++] Simplify internal API for dataframe-resizer

---

apis/r/DESCRIPTION
apis/r/NEWS.md
apis/r/R/Factory.R
apis/r/R/SOMADataFrame.R
apis/r/R/utils-arrow.R
apis/r/man/SOMADataFrame.Rd
apis/r/man/SOMADataFrameCreate.Rd
apis/r/src/rutilities.cpp
apis/r/tests/testthat/test-shape.R

**Issue and/or context:** As tracked on issue #2407 / [[sc-51048]](https://app.shortcut.com/tiledb-inc/story/51048). Fixes #2967 / [[sc-55657]](https://app.shortcut.com/tiledb-inc/story/55657/use-domain-in-somadataframecreate).
**Changes:**
As a legacy R/Python-parity issue, the `domain` argument to `SOMADataFrame`'s `create` -- from the [SOMA spec](https://github.com/single-cell-data/SOMA/blob/main/abstract_specification.md) -- was never implemented in R. Here we remedy that.
This PR is a work in progress. It is not ready for review.
Unit-test cases are not yet implemented.

[r] Implement missing `domain` argument to `DataFrame` `create`

---

apis/python/src/tiledbsoma/_dataframe.py
apis/python/src/tiledbsoma/_tdb_handles.py
apis/python/src/tiledbsoma/soma_dataframe.cc
apis/python/tests/test_shape.py
apis/r/R/RcppExports.R
apis/r/R/SOMADataFrame.R
apis/r/src/RcppExports.cpp
apis/r/src/rinterface.cpp
apis/r/tests/testthat/test-shape.R
libtiledbsoma/src/soma/soma_array.cc
libtiledbsoma/src/soma/soma_array.h
libtiledbsoma/test/unit_soma_dataframe.cc

**Changes:**
While the full-generality `upgrade_domain` is on track for #2407, the most important special case is resizing the `soma_joinid` index column and leaving the others alone, if `soma_joinid` is an index column -- otherwise leaving it alone.
This already exists in C++ and is well-tested there. This PR simply connects it to Python/R. It's time for this, as we need:
* `tests/testthat/test-soma-write-resume.R` for R on #3089 
* Experiment-level resizer for Python on #2964 
* This PR is stacked on top of #3090
* This PR isn't super-big -- 200 …

[python/r] `DataFrame` resizer

---

libtiledbsoma/src/soma/soma_array.cc
libtiledbsoma/src/soma/soma_array.h
libtiledbsoma/test/unit_soma_dataframe.cc
libtiledbsoma/test/unit_soma_sparse_ndarray.cc

**Changes:**
For experiment-level resize (e.g. append mode) it will be crucial that we implement a mechanism to detect whether all arrays in the experiment are resizable up to the new `(nobs, nvar)` before attempting any resizes. In particular, it would be bad to succeed in resizing some member arrays and fail on one or more.

[c++] Add can-resize helpers in prep for experiment-level resize

---

apis/r/R/write_soma.R
apis/r/tests/testthat/test-write-soma-resume.R

**Changes:**
Stacked on top of #3032.

[r] Make `DataFrame` objects shapeable at ingest

---

.gitignore

Long-standing minor annoyance: `rg` wasn't showing me some things in our pybind11 source unless I did `rg -u`. Today I finally got around to figuring out why. Our current `.gitignore` rule was masking `apis/python/src/tiledbsoma/pytiledbsoma.cc`.

Minor update to `.gitignore`

---

apis/python/setup.py
apis/python/src/tiledbsoma/__init__.py
apis/python/src/tiledbsoma/_constants.py
apis/python/src/tiledbsoma/_factory.py
apis/python/src/tiledbsoma/_point_cloud_dataframe.py
apis/python/src/tiledbsoma/_scene.py
apis/python/src/tiledbsoma/_spatial_dataframe.py
apis/python/src/tiledbsoma/_spatial_util.py
apis/python/src/tiledbsoma/_tdb_handles.py
apis/python/src/tiledbsoma/pytiledbsoma.cc
apis/python/src/tiledbsoma/soma_object.cc
apis/python/src/tiledbsoma/soma_point_cloud_dataframe.cc
apis/python/tests/test_coordinates.py
apis/python/tests/test_point_cloud_dataframe.py

Add the Python implementation of the new `PointCloudDataFrame` class.
**Issue:**  #3046 #3108

Add Python implementation of the `PointCloudDataFrame` class

---

apis/python/src/tiledbsoma/pytiledbsoma.cc
apis/python/tests/test_dataframe.py
libtiledbsoma/src/utils/arrow_adapter.cc
libtiledbsoma/src/utils/arrow_adapter.h

- Rename `ArrowAdapter::_isvar` to `ArrowAdapter::arrow_is_string_type` and expose in public API
- In pybind11 `SOMAArray._update_dataframe`, check if the Arrow column's type is a string type and set the `Attr`'s cell value to `TILEDB_VAR_NUM` if so

[c++/python] Check `arrow_is_string_type` in `_update_dataframe`

---

libtiledbsoma/src/utils/arrow_adapter.cc

While working on #3100 for #3057 / [[sc-55679]](https://app.shortcut.com/tiledb-inc/story/55679/r-use-libtiledbsoma-for-schema-evolution) (parent #2406) I ran into a cryptic error from Arrow. It turns out that when the number of buffers doesn't match -- 2 for non-variable-length validity/data vs. 3 for variable-length validity/offsets/data -- we can get message like
```
tiledbsoma._exception.SOMAError: ArrowInvalid: Column 4: In chunk 0: Invalid: First or last binary offset out of bounds
At:
pyarrow/error.pxi(92): pyarrow.lib.check_status
```
Now, the dev situation in which I was setting up data to _generate_ such a situation is perhaps incorrect -- but -- we should fail sooner, and more transparently.
The status quo is that I turned on libtiledbsoma trace-logging & saw lines like
``` …
```

[c++] Fail earlier if `n_buffers` is not as expected

---

apis/python/src/tiledbsoma/_point_cloud_dataframe.py
apis/python/src/tiledbsoma/_spatial_util.py
apis/python/tests/test_scene.py

* Added tests for what is currently implemented
* Would still need tests for
- `subcollection`
- `add_{spatial_datatype}` (currently using `create`)
- `GeometryDataFrame` (currently skipping)

[python] Add `Scene` tests

---

libtiledbsoma/src/utils/arrow_adapter.cc

This was my own error a few PRs ago. :|

[c++] Fix a minor typo in logging statements

---

apis/python/src/tiledbsoma/_point_cloud_dataframe.py
apis/python/src/tiledbsoma/_spatial_util.py

* Update `transform_from_json` and `transform_to_json` to support additional `CoordinateSpace` types `UniformScaleTransform` and `ScaleTransform`
* Correct error message in `PointCloud.coordinate_space` setter

[python] Update coordinate space <-> JSON converters

---

apis/python/src/tiledbsoma/io/ingest.py
apis/python/src/tiledbsoma/pytiledbsoma.cc
libtiledbsoma/src/soma/soma_dataframe.cc
libtiledbsoma/src/soma/soma_dataframe.h

**Issue and/or context:** For #3057 [[sc-55679]](https://app.shortcut.com/tiledb-inc/story/55679/r-use-libtiledbsoma-for-schema-evolution)
**Changes:**
On the R side we'll need to use `libtiledbsoma` rather than TileDB-R for schema evolution. Meanwhile the logic currently in our `pybind11` layer can go directly into `libtiledbsoma` where our `Rcpp` layer can call it.
No functional change: only code motion. No new unit tests: all existing tests should pass.

[c++/python] Push `update_dataframe_schema` down to `libtiledbsoma`

---

apis/r/DESCRIPTION
apis/r/NEWS.md
apis/r/R/RcppExports.R
apis/r/R/SOMADataFrame.R
apis/r/man/SOMADataFrame.Rd
apis/r/src/RcppExports.cpp
apis/r/src/rinterface.cpp
apis/r/src/rutilities.cpp
apis/r/src/rutilities.h

**Issue and/or context:** This is an item on #2406: in particular #3057 / [[sc-55679]](https://app.shortcut.com/tiledb-inc/story/55679/r-use-libtiledbsoma-for-schema-evolution)/
**Changes:**
* Move the `pybind11` `update_dataframe` entirely to `libtiledbsoma` (it's ready to go, no mods needed)
* Call that from R, removing another TileDB-R callsite
See also #3115.

[c++/python/r] Use `libtiledbsoma` for R schema evolution

---

apis/python/src/tiledbsoma/__init__.py
apis/python/src/tiledbsoma/_factory.py
apis/python/src/tiledbsoma/_scene.py
apis/python/src/tiledbsoma/_soma_object.py
apis/python/src/tiledbsoma/_tdb_handles.py
apis/python/src/tiledbsoma/soma_collection.cc
apis/python/src/tiledbsoma/soma_object.cc
apis/python/tests/test_scene.py

Adds the Python implementation of the new `Scene` collection class.
Issue: #3040

Add the Python implementation of the Scene collection

---

apis/python/src/tiledbsoma/_multiscale_image.py

Before this PR:
```py
scene.img["tissue"].get_transform_to_level(0)
scene.img["tissue"].get_transform_to_level("hires")
```
With this PR:
```py
scene.img["tissue"].get_transform_to_level(0)
scene.img["tissue"].get_transform_to_level("hires")
```

[python] Fix retrieval of named levels from a MultiscaleImage

---

apis/r/R/RcppExports.R
apis/r/R/SOMADenseNDArray.R
apis/r/R/TileDBArray.R
apis/r/src/RcppExports.cpp
apis/r/src/rinterface.cpp
libtiledbsoma/src/soma/soma_array.cc
libtiledbsoma/src/soma/soma_array.h

#2406 
#3058 
[[sc-55674]](https://app.shortcut.com/tiledb-inc/story/55674/r-use-libtiledbsoma-for-dims-attrs-accessors)

[r] Push `attrnames` down to C++

---

apis/r/DESCRIPTION
apis/r/NEWS.md
apis/r/R/RcppExports.R
apis/r/R/SOMADataFrame.R
apis/r/R/SOMADenseNDArray.R
apis/r/R/TileDBArray.R
apis/r/R/utils-arrow.R
apis/r/src/RcppExports.cpp
apis/r/src/rinterface.cpp
apis/r/tests/testthat/test-SOMADataFrame.R

**Issue and/or context:** #2406 #3055 [[sc-55682]](https://app.shortcut.com/tiledb-inc/story/55682/r-use-libtiledbsoma-for-all-tiledb-schema-callsites)
**Changes:**

[r] Push `schema` accessor down to `libtiledbsoma`

---

libtiledbsoma/src/soma/soma_array.cc
libtiledbsoma/src/soma/soma_array.h
libtiledbsoma/test/unit_soma_dataframe.cc
libtiledbsoma/test/unit_soma_dense_ndarray.cc
libtiledbsoma/test/unit_soma_sparse_ndarray.cc

**Issue and/or context:** In support of issue #2407 / [[sc-51048]](https://app.shortcut.com/tiledb-inc/story/51048).
**Changes:**
1st commit: I prefer longer/clearer names often, but, these are repeated and are causing unnecessary `clang-format` adjustments, particularly in PRs stacked on top of this.
2nd commit: another renaming. Not worth a separate PR IMO.

[c++] Trivial name-shortens in unit-test code

---

apis/python/src/tiledbsoma/_spatial_util.py
apis/python/tests/test_multiscale_image.py

The `read_spatial_region` method should be able to accept `None` for a region. When this is provided, the whole array is returned.

[python] Fix `MultiscaleImage.read_spatial_region` full region read

---

apis/python/src/tiledbsoma/_dataframe.py
apis/python/src/tiledbsoma/_tdb_handles.py
apis/python/src/tiledbsoma/soma_dataframe.cc
apis/python/tests/test_shape.py
apis/r/R/RcppExports.R
apis/r/R/SOMADataFrame.R
apis/r/R/write_soma.R
apis/r/man/SOMADataFrame.Rd
apis/r/src/RcppExports.cpp
apis/r/src/rinterface.cpp
apis/r/tests/testthat/test-shape.R
apis/r/tests/testthat/test-write-soma-resume.R
libtiledbsoma/src/soma/soma_array.cc
libtiledbsoma/src/soma/soma_array.h
libtiledbsoma/test/unit_soma_dataframe.cc

**Issue and/or context:** In support of issue #2407 / [[sc-51048]](https://app.shortcut.com/tiledb-inc/story/51048).
**Changes:**
This is to help me deconfuse on #2964. The method in question is mainly an internal helper for experiment-level resizing. I want its name to be as clear as possible nonetheless.

[c++/python/r] Rename a helper function

---

apis/python/src/tiledbsoma/soma_dataframe.cc
apis/python/src/tiledbsoma/soma_sparse_ndarray.cc
apis/r/R/RcppExports.R
apis/r/src/RcppExports.cpp
apis/r/src/rinterface.cpp
libtiledbsoma/src/soma/soma_array.cc
libtiledbsoma/src/soma/soma_array.h
libtiledbsoma/test/unit_soma_dataframe.cc
libtiledbsoma/test/unit_soma_dense_ndarray.cc
libtiledbsoma/test/unit_soma_sparse_ndarray.cc

**Changes:**
* This is underpinning for #2964
* As @nguyenv pointed out, it might be nice for the C++ layer to just return enums only ...
* ... but as I pointed out
* informative messages really require specific context such as the user-provided shape and the limit it ran into
* I don't want to write those all twice in Python and R
* So we are making user-presentable strings in the C++ code
* That said, we should not be hard-coding the function names from the caller -- given that C++ is creating user-facing error strings _on behalf of_ Python and R, the C++ code should enable and empower the Python/R code to pass in their function names (whatever those are)
**Notes for …

[c++] Propagate Python/R function names to C++ for upgrade/resize methods

---

apis/r/DESCRIPTION

https://github.com/single-cell-data/TileDB-SOMA/issues/3134
[[sc-56962]](https://app.shortcut.com/tiledb-inc/story/56962/tiledb-soma-1-15-0rc0)

[r] `main` version now that `release-1.15` branch exists

---

libtiledbsoma/src/soma/soma_array.cc
libtiledbsoma/src/soma/soma_array.h
libtiledbsoma/test/unit_soma_dataframe.cc
libtiledbsoma/test/unit_soma_sparse_ndarray.cc

**Changes:**
Continues on #3125 #3127 #3130 underpinnings toward the goal of #2964 wherein we need:
* Experiment-level upgrade/resize
* Since there are multiple arrays in an experiment, a can-we-upgrade/resize-them-all pass
Note that `upgrade_domain` is the full-generality dataframe domain-upgrader, but, for experiment-level work we really need the plumbing that focuses on dataframe `soma_joinid` shape.

[c++] Dataframe-sizing helpers

---

apis/python/src/tiledbsoma/options/_soma_tiledb_context.py

1.15.0rc0 was failing post-merge CI with things like 
```
>       assert (int(version[0]), int(version[1])) < (major, minor)
E       AssertionError
```
https://github.com/single-cell-data/TileDB-SOMA/actions/runs/11187321846/job/31104123666

Do not fatal on 1.15-related assertions

---

apis/python/src/tiledbsoma/_dense_nd_array.py
apis/python/src/tiledbsoma/soma_array.cc
apis/python/tests/test_basic_anndata_io.py
apis/python/tests/test_dense_nd_array.py
libtiledbsoma/src/soma/managed_query.cc
libtiledbsoma/src/soma/soma_array.h

Found issue while working on spatial's `MultiscaleImage` and erroring out when applying `read_spatial_region` to a level that had not been written to yet.
**Changes:**
* Add new `non_empty_domain_slot_opt` alongside `non_empty_domain_slot` that returns `std::nullopt` if it is empty rather than (0, 0)
* Fix logic in C++ `ManagedQuery::setup_read` to check if the array has been written to yet. If it hasn't, set the subarray to use soma_dim_0's full domain. Otherwise, use the non-empty domain as before
* Also fix logic in Python `DenseNDArray.read` to use the new `non_empty_domain_slot_opt` and correctly set the `data_shape` to the full domain if the array has not been written to yet
* Add unit test in pytest

[c++,python] Fix default reads on unwritten dense arrays

---

apis/python/setup.py
apis/python/src/tiledbsoma/io/_common.py
apis/python/src/tiledbsoma/io/ingest.py

[python] Drop `anndata` version pin; use `CSCDataset`/`CSRDataset`

---

apis/python/setup.py

We found on `pip install --pre tiledbsoma==0.15.0rc1` that we were getting an undesired `anndata==0.11.0rc2` version of `anndata`.

[python] Avoid RCs of dependent packages for our RC

---

apis/r/DESCRIPTION
apis/r/NEWS.md
apis/r/R/SOMANDArrayBase.R
apis/r/R/SOMASparseNDArray.R
apis/r/tests/testthat/test-SOMADenseNDArray.R
apis/r/tests/testthat/test-SOMASparseNDArray.R

Fix bug in handling of numeric coordinates when reading a sparse array. Now, always cast any integerish value to `bit64::integer64` (casting a `bit64::integer64` to a `bit64::integer64` is a no-op). Also strengthen value checking of `coords` to
- require `coords` to be a list of `NULL` or positive, finite, integerish values
- require `coords` to have a length
- require `coords` to be a list of length `array$dimnames()` or be named with `array$dimnames()`
- filter `NULLs` from `coords`; if `coords` is all `NULL`, convert to `NULL`
- `SOMANDArrayBase$private$.convert_coords()`: cast all integerish values to `bit64::integer64`; strengthen value checking of `coords`
[SC-57096](https://app.shortcut.com/tiledb-inc/story/57096)

[r] Handle numeric `coords` better in `SOMASparseNDArray$read()`

---

apis/python/src/tiledbsoma/_multiscale_image.py
apis/python/tests/test_multiscale_image.py

- Added string lookup for `level_properties`
- Expanded `read_spatial_region` tests with different regions
- Added testing for to and from levels

[python] Extend `MultiscaleImage` testing

---

libtiledbsoma/src/soma/soma_array.cc
libtiledbsoma/test/unit_soma_dataframe.cc

**Changes:**
Unit-test the dataframe upgrader.

[c++] Unit-test the dataframe upgrader

---

libtiledbsoma/src/soma/soma_array.h
libtiledbsoma/src/utils/arrow_adapter.cc
libtiledbsoma/src/utils/arrow_adapter.h
libtiledbsoma/test/unit_soma_dataframe.cc

As part of the work for #1632 to move tiledb-py (and tiledb-r) out of unit tests, this PR adds accessor `SOMAArray::config_options_from_schema` for retrieving properties such as cell order and filter lists. The method `ArrowAdapter::platform_config_from_tiledb_schema` accepts a `tiledb::ArraySchema` and serializes additional metadata not captured by `SOMAArray::arrow_schema` into a `PlatformConfig` object.

[c++] Add `SOMAArray::config_options_from_schema ` getter

---

apis/python/src/tiledbsoma/_sparse_nd_array.py
apis/python/src/tiledbsoma/_tdb_handles.py
apis/python/src/tiledbsoma/io/_registration/ambient_label_mappings.py
apis/python/src/tiledbsoma/soma_sparse_ndarray.cc
apis/python/tests/test_registration_mappings.py
apis/python/tests/test_shape.py

**Changes:**
For experiment-level resize and append mode (#3148) we'll need the registrar to offer up the new shapes that the experiment will need to be resized to. This PR supports that goal.
This PR is a work in progress. It is not ready for review.

[python] Let registrar provide new shapes for resize

---

libtiledbsoma/test/common.cc

Issue reported by @aneesav on a Mac not too different from mine (which is odd she sees it & I don't). Regardless:
https://gist.github.com/aneesav/514b43786e666aae2ef7bab2cb13603a#file-gistfile1-txt-L75
which is reminiscent of https://github.com/single-cell-data/TileDB-SOMA/pull/2609/files
The error message just points to something at line 122 of `libtiledbsoma/test/common.cc`, and there are four `{}`, but the others are already `std::string` or `bool` so the only remaining option for which of the four triggers the 'not formattable' error is the `tiledb_datatype_t` enum.
The change I'm making here doesn't hurt, and, will likely help @aneesav with `pip install -e apis/python` on her system.

[c++] Fix an issue with some compilers

---

apis/python/tests/test_shape.py

**Changes:**
Here we keep around an old-style experiment to regress on our ability to upgrade its shapes.
For this PR we only test accessors on the data. On #3148 these unit test will be extended to check their upgrading of the old-style experiment.

[python] Canned tests for old/new arrays without/with new shapes

---

apis/python/src/tiledbsoma/common.cc
apis/python/src/tiledbsoma/common.h
apis/python/src/tiledbsoma/soma_array.cc
apis/python/src/tiledbsoma/soma_group.cc
apis/python/tests/test_factory.py
libtiledbsoma/src/soma/soma_array.cc
libtiledbsoma/src/soma/soma_array.h
libtiledbsoma/src/soma/soma_group.cc
libtiledbsoma/src/soma/soma_group.h
libtiledbsoma/src/soma/soma_object.h

As part of https://github.com/single-cell-data/TileDB-SOMA/pull/2883 to remove tiledb-py from unit tests
**Changes:**
* Use the SOMA API to create objects and then modify the reserved metadata values; incorrect encoding versions and SOMA object types should still error out as before
* Add `force` flag to `delete_metadata` to match `set_metadata`

[python/c++] Remove tiledb-py from `test_factory.py`

---

apis/python/src/tiledbsoma/io/__init__.py
apis/python/src/tiledbsoma/io/shaping.py
apis/python/tests/test_shape.py

**Changes:**
Tests the experiment-level upgrader and resizer.
There is more to do in `tiledbsoma.io` for append-mode ingest on #3148.
Example verbose output:
```
uri = "/var/ns/pbmc3k"
tiledbsoma.io.show_experiment_shapes(uri)
```
<details>
```
[DataFrame] obs
URI file:///var/ns/pbmc3k/obs
count                2638
domain               ((0, 9223372036854773758),)
maxdomain            ((0, 9223372036854773758),)
upgraded             False
[DataFrame] ms/RNA/var
URI file:///var/ns/pbmc3k/ms/RNA/var
count                1838
domain               ((0, …
```

[python] Experiment-level upgrader/resizer

---

apis/python/src/tiledbsoma/_soma_array.py
apis/python/src/tiledbsoma/_tdb_handles.py
apis/python/tests/test_dataframe.py
apis/python/tests/test_dense_nd_array.py
apis/python/tests/test_platform_config.py
apis/python/tests/test_sparse_nd_array.py
libtiledbsoma/src/utils/arrow_adapter.cc
libtiledbsoma/src/utils/arrow_adapter.h
libtiledbsoma/test/unit_soma_dataframe.cc

This is the first of multiple changes pulled out from from https://github.com/single-cell-data/TileDB-SOMA/pull/2883 to remove tiledb-py from unit tests
**Changes:**
- Addition of `config_options_from_schema` binding to retrieve `ArraySchema` info not encapsulated by the `ArrowSchema`
- Corrected JSON `dims` and `attrs` by returning `tile` for `dims` and using `filters` keys for `FilterList` values
- Replace `tiledb.FilterList` with `PlatformConfig`'s JSON formatted strings

[python/c++] Use `config_options_from_schema` in pytest unit tests

---

apis/python/src/tiledbsoma/soma_group.cc
apis/python/tests/test_basic_anndata_io.py
libtiledbsoma/src/soma/soma_group.h

This is the second of multiple changes pulled out from from https://github.com/single-cell-data/TileDB-SOMA/pull/2883 to remove tiledb-py from unit tests
**Changes:**
- Add `SOMAGroup::is_relative` in C++ and associated binding in Pybind11
- Replace tiledb-py `is_relative` test with new binding

[python/c++] Add `SOMAGroup::is_relative` and use in pytest unit tests

---

apis/python/src/tiledbsoma/soma_array.cc
apis/python/tests/test_dataframe.py

This is pulled out from https://github.com/single-cell-data/TileDB-SOMA/pull/2883 to remove tiledb-py from unit tests
**Changes:**
While replacing the tiledb-py `tiledb.consolidate` and `tiledb.vacuum` commands in `test_dataframe.py::test_timestamped_ops` to use the already existing tiledbsoma-py `TileDBWriteOptions.consolidate_and_vacuum`, it was found that the binding for `SOMAArray::consolidate_and_vacuum` was not properly configured to use the default value `{"fragment_meta", "commits"}`.

[python] Correct `consolidate_and_vacuum` default `modes`

---

apis/python/tests/test_basic_anndata_io.py
apis/python/tests/test_dataframe.py

This is the fourth of multiple changes pulled out from from https://github.com/single-cell-data/TileDB-SOMA/pull/2883 to remove tiledb-py from unit tests
**Changes:**
Replace `tiledb.VFS` and `tiledb.FragmentInfoList` with `pathlib.Path.iterdir` to count fragments without relying on tiledb-py

[python] Use `pathlib.Path.iterdir` to count fragments

---

apis/r/DESCRIPTION
apis/r/NEWS.md
apis/r/R/QueryCondition.R
apis/r/R/RcppExports.R
apis/r/src/RcppExports.cpp
apis/r/src/query_condition.cpp
apis/r/tests/testthat/test-query-condition.R
libtiledbsoma/test/common.cc

**Issue and/or context:** #3051 [[sc-55672]](https://app.shortcut.com/tiledb-inc/story/55672/r-port-the-query-condition-logic-from-tiledb-r-to-tiledb-soma-r)
**Changes:**
Here I am only introducing a non-exported function `parse_query_condition_new`, and unit-testing it thoroughly. Replacing the exiting `parse_query_condition` with this will be a follow-on PR.
Timestamp handling will be deferred to a follow-up PR: #3163.

[r] Port the query-condition logic from TileDB-R to TileDB-SOMA-R

---

apis/python/setup.py
apis/python/src/tiledbsoma/io/_registration/ambient_label_mappings.py
apis/python/src/tiledbsoma/io/_util.py
apis/python/src/tiledbsoma/io/ingest.py
apis/python/src/tiledbsoma/pytiledbsoma.cc
apis/python/src/tiledbsoma/soma_vfs.cc
apis/python/src/tiledbsoma/vfs.cc

This PR is separated out from https://github.com/single-cell-data/TileDB-SOMA/pull/2752
**Changes:**
- This completely removes tiledb-py in `io/_util.py` by binding the necessary VFS methods in tiledbsoma-py
**Note for Reviewers**
https://github.com/single-cell-data/TileDB-SOMA/pull/2882#issuecomment-2286697745

[python] Add `VFS` binding in `pybind11`

---

apis/python/notebooks/tutorial_spatial.ipynb
apis/python/src/tiledbsoma/experimental/ingest.py

Add an input parameter to the experimental `from_visium` ingestor that specifies if images should be ingested with the channel first or last.

[python] Adds Visium ingestion option to set image channel order

---

apis/python/tests/test_basic_anndata_io.py
apis/python/tests/test_dataframe.py
apis/python/tests/test_dataframe_index_columns.py
apis/python/tests/test_dense_nd_array.py
apis/python/tests/test_experiment_query.py

This is the sixth of multiple changes pulled out from from https://github.com/single-cell-data/TileDB-SOMA/pull/2883 to remove tiledb-py from unit tests. These are the more minor remaining changes that could be outlined in a single PR.
**Changes:**
* `test_basic_anndata_io.py`
- `test_null_obs`: Use arrow schema to check nullability
- `test_export_obsm_with_holes`: Use `Experiment.metadata` directly
* `test_dataframe.py::test_enum_schema_report`: Remove redundant type checking against tiledb-py. Checks are already encompassed by Arrow schema check below
* `test_dataframe_index_columns.py::test_types_read_errors`: Remove extra parens
* `test_dense_nd_array::pytest_read_to_unwritten_array`: Create expected data output by create a numpy array with the fill value …

[python] Various tiledb-py removals from pytest

---

apis/python/src/tiledbsoma/_scene.py
apis/python/tests/test_scene.py

Add a helper function `_open_subcollection` to the `Scene` that reduces the amount of duplicate code needed in the `Scene` class. This update also adds support for setting/getting transforms on data that is more than one level deep in a scene (e.g. anything stored in `varl`).

[python] Add `_open_subcollection` helper method to `Scene`

---

apis/python/setup.py
apis/python/tests/test_basic_anndata_io.py
apis/python/tests/test_dataframe.py
apis/python/tests/test_regression.py

**Issue and/or context:** #2536
**Changes:**
Main thing to watch for: NumPy 2.0 does not support Python 3.8, while we have not yet dropped support for Python 3.8 (#2141).
Per https://github.com/numpy/numpy/releases/tag/v2.0.0:
> The Python versions supported by this release are 3.9-3.12.
I thought we'd need a bit in `setup.py` like
```
"numpy<2; python_version<'3.9'",
"numpy; python_version>='3.9'",
```
but in hindsight it seems not -- a Python 3.8 asking to get NumPy will simply not be _offered_ version 2 in the first place 😎

[python] Support NumPy 2

---

apis/r/DESCRIPTION
apis/r/NEWS.md
apis/r/R/QueryCondition.R
apis/r/R/SOMADataFrame.R
apis/r/src/query_condition.cpp
apis/r/tests/testthat/test-SCEOutgest.R
apis/r/tests/testthat/test-SOMAArrayReader-Arrow.R
apis/r/tests/testthat/test-query-condition.R
libtiledbsoma/test/common.cc

**Issue and/or context:** Issue #3051 / [[sc-55672]](https://app.shortcut.com/tiledb-inc/story/55672/r-duplicate-query-condition-logic). Stack: #3162, #3163, this.
**Changes:**
Replaces the existing `parse_query_condition`, which uses TileDB-R, with the one currently named `parse_query_condition_new` which uses `libtiledbsoma`.
This or #3163 can be landed in either order.

[r] Move `parse_query_condition_new` -> `parse_query_condition`

---

apis/r/R/QueryCondition.R

**Issue and/or context:** Issue #3051 / [[sc-55672]](https://app.shortcut.com/tiledb-inc/story/55672/r-duplicate-query-condition-logic). Stack: #3162, #3163, this.
**Changes:**
Fix a bad merge of #3174. CI was green pre-merge; red after https://github.com/single-cell-data/TileDB-SOMA/actions/runs/11368178584/job/31622625962

[r] Fix bad merge of #3174

---

apis/python/src/tiledbsoma/_dense_nd_array.py
apis/python/src/tiledbsoma/_tdb_handles.py
apis/python/tests/test_shape.py
libtiledbsoma/test/unit_soma_dense_ndarray.cc

**Changes:** Work off to-do items in the code

[python] Support for current domain on dense arrays

---

apis/python/src/tiledbsoma/_dense_nd_array.py
apis/python/src/tiledbsoma/_tdb_handles.py
apis/python/src/tiledbsoma/pytiledbsoma.cc
apis/python/tests/test_context.py
apis/python/tests/test_shape.py
libtiledbsoma/test/common.cc
libtiledbsoma/test/common.h
libtiledbsoma/test/unit_soma_collection.cc
libtiledbsoma/test/unit_soma_dense_ndarray.cc

**Issue and/or context:** Key point here is test-unbreaks when someone points at `dev` of core which has some recent mods including https://github.com/TileDB-Inc/TileDB/pull/5303/
**Changes:**
Make unit tests pass when core is recent `dev`, e.g. https://github.com/TileDB-Inc/centralized-tiledb-nightlies/issues/24
There is more to do on #2407 / [[sc-51048]](https://app.shortcut.com/tiledb-inc/story/51048) for Python and R both to incorporate new support for current domain in dense arrays.

[c++/python] Updates for core 2.27

---

.github/workflows/python-ci-full.yml
.github/workflows/python-ci-minimal.yml
.github/workflows/python-ci-packaging.yml
.github/workflows/python-ci-single.yml
.github/workflows/python-packaging.yml

**Issue and/or context:** #3185; follow-up from https://github.com/single-cell-data/TileDB-SOMA/pull/3182#discussion_r1803863705
**Changes:**
Manual run for sdist+wheels CI (normally runs nightly and on tagged releases):
https://github.com/single-cell-data/TileDB-SOMA/actions/runs/11375025992

[ci/python] Use `ubuntu-latest` CI runners

---

apis/r/R/Init.R
apis/r/R/SOMANDArrayBase.R
apis/r/R/SOMASparseNDArray.R
apis/r/R/utils-arrow.R
apis/r/tests/testthat/test-shape.R

[r] Support for dense current domain with core 2.27

---

apis/r/DESCRIPTION
apis/r/NEWS.md
apis/r/R/utils-assertions.R
apis/r/tests/testthat/test-utils.R

**Issue and/or context:** Fixes #3181 
**Changes:** as on #3181, with unit-test coverage.

Fix `is_named_list` bug #3181

---

apis/python/src/tiledbsoma/io/_registration/ambient_label_mappings.py
apis/python/src/tiledbsoma/io/_registration/id_mappings.py
apis/python/src/tiledbsoma/io/ingest.py
apis/python/src/tiledbsoma/io/shaping.py
apis/python/tests/test_basic_anndata_io.py
apis/python/tests/test_registration_mappings.py

**Changes:**
Support experipment-level `upgrade_shape` and `resize`.

[python] Append mode with resizing

---

apis/python/tests/test_type_system.py
apis/python/tests/test_unicode.py

[python] Domain-at-create unit-test PR 2/5

---

apis/python/tests/test_collection.py
apis/python/tests/test_experiment_basic.py
apis/python/tests/test_experiment_query.py
apis/python/tests/test_io.py

[python] Domain-at-create unit-test PR 4/5

---

apis/r/R/QueryCondition.R
apis/r/tests/testthat/test-query-condition.R

**Issue and/or context:** #3051 [[sc-55672]](https://app.shortcut.com/tiledb-inc/story/55672/r-port-the-query-condition-logic-from-tiledb-r-to-tiledb-soma-r)
**Changes:** Follow-up to #3162 and #3174, in particular, https://github.com/single-cell-data/TileDB-SOMA/pull/3162#discussion_r1801606040 by @nguyenv 
See also https://github.com/TileDB-Inc/TileDB-R/pull/771 (same bug)

[r] More unit-test cases for query-condition parser

---

apis/python/setup.py
apis/python/src/tiledbsoma/_tdb_handles.py
apis/python/src/tiledbsoma/options/_soma_tiledb_context.py
apis/python/src/tiledbsoma/options/_tiledb_create_write_options.py
apis/python/tests/test_context.py
apis/python/tests/test_dense_nd_array.py

https://github.com/single-cell-data/TileDB-SOMA/issues/1632
This completes the SOMA Python API move over from tiledb-py to C++.
**Changes:**
- Remove `tiledb.ctx` usage
- Remove `tiledb.Filter` usage

[python] Remove tiledb-py dependency

---

apis/python/src/tiledbsoma/_scene.py
apis/python/tests/test_scene.py

The previous implementation of the `set_transform_to_*` methods in the `Scene` class had the validation on the transform input axes and output axes flipped. This fixes that bug and adds a generic `set_transform_to_element` method.

[python] Fix and refactor `set_transform_to_*` methods

---

apis/python/src/tiledbsoma/_dataframe.py
apis/python/src/tiledbsoma/_dense_nd_array.py
apis/python/src/tiledbsoma/_point_cloud_dataframe.py
apis/python/src/tiledbsoma/_sparse_nd_array.py

**Changes:**
In the design at #2407 we decided that `None` no longer means "as big a domain as possible" but now rather "as small as possible" -- as only upward resizes, not downward resizes, are possible. This is a breaking change we have already agreed on.

[python] Min-sizing for dataframes/arrays with new shape feature

---

apis/r/DESCRIPTION
apis/r/NEWS.md
apis/r/R/SOMACollectionBase.R
apis/r/R/utils-arrow.R
apis/r/tests/testthat/helper-test-data.R
apis/r/tests/testthat/helper-test-soma-objects.R
apis/r/tests/testthat/test-Factory.R
apis/r/tests/testthat/test-OrderedAndFactor.R
apis/r/tests/testthat/test-SOMACollection.R
apis/r/tests/testthat/test-SOMADataFrame.R
apis/r/tests/testthat/test-Timestamps.R
apis/r/tests/testthat/test-query-condition.R
apis/r/tests/testthat/test-reopen.R
apis/r/tests/testthat/test-shape.R

**Changes:**
In the design at #2407 we decided that `None` no longer means "as big a domain as possible" but now rather "as small as possible" -- as only upward resizes, not downward resizes, are possible. This is a breaking change we have already agreed on.
This is the R counterpart to the Python PRs #3190 #3191 #3192 #3193 #3194 #3203. I didn't split this one up into multiple PRs as I did those. However, the mods are the same:
* Have unit-test cases always provide `domain` at `create`
* Apply the policy that `domain` being `NULL` overall or slotwise makes …

[r] Min-sizing for dataframes/arrays with new shape feature

---

libtiledbsoma/src/soma/column_buffer.cc
libtiledbsoma/src/soma/column_buffer.h
libtiledbsoma/src/soma/soma_array.cc
libtiledbsoma/src/soma/soma_dataframe.cc
libtiledbsoma/src/soma/soma_dense_ndarray.cc
libtiledbsoma/src/soma/soma_sparse_ndarray.cc
libtiledbsoma/src/utils/arrow_adapter.cc
libtiledbsoma/src/utils/arrow_adapter.h

This PR prepares the geometry dataframe support by enabling the use of WKB and WKT attributes and dimensions

[c++] Add support for WKB and WKT attributes and dimensions

---

libtiledbsoma/src/utils/arrow_adapter.cc

**Issue and/or context:** Arose while troubleshooting an issue.
**Changes:**
As obvious hindsight, this error message is more helpful when it reports the affected column name.

[c++] Include column name in a particular error message

---

.github/workflows/python-ci-full.yml
.github/workflows/python-ci-minimal.yml
.github/workflows/python-ci-packaging.yml
.github/workflows/python-ci-single.yml
.github/workflows/python-packaging.yml
apis/python/requirements_dev.txt
apis/python/tests/test_dataframe.py
apis/python/tests/test_sparse_nd_array.py

For issue #1849 -- which has a long history.
See also #2999 and [[sc-53002]](https://app.shortcut.com/tiledb-inc/story/53002/update-projects-to-tiledb-2-26).
This needs https://github.com/single-cell-data/SOMA/pull/222

[python] Python 3.12 support

---

apis/python/src/tiledbsoma/_scene.py
apis/python/tests/_util.py
apis/python/tests/test_scene.py

Add support for setting the transform when a `PointCloud` or `MultiscaleImage` is first added to a `Scene`.

[python] Add support for transforms in the `Scene` `add_new_*` methods

---

apis/python/src/tiledbsoma/_scene.py
apis/python/tests/test_scene.py

Implement the methods to get the coordinate transformation from elements in the scene back to the scene itself.

[python] Implement `get_transform_from_*` methods in the `Scene`

---

libtiledbsoma/src/soma/soma_array.cc
libtiledbsoma/src/soma/soma_array.h
libtiledbsoma/test/common.cc
libtiledbsoma/test/common.h
libtiledbsoma/test/unit_soma_dataframe.cc

**Changes:**
* This is `can_upgrade_domain` for `SOMADataFrame` at the C++ level

[c++] `can_upgrade_domain`

---

libtiledbsoma/src/soma/soma_array.cc

**Issue and/or context:** [[sc-58277]](https://app.shortcut.com/tiledb-inc/story/58277/python-sparse-array-nnz-performance-regression)
**Changes:**

[c++] Fix fast path for `SparseNDArray` `nnz`

---

.github/workflows/r-python-interop-testing.yml
apis/system/tests/test_dataframe_write_python_read_r.py
apis/system/tests/test_dataframe_write_r_read_python.py

**Changes:**
We have four unit-test suites: C++ in `libtiledbsoma/test`; Python in `apis/python/tests`; R in `apis/r/tests/testthat`; R/Python interop in `apis/system/tests`.
I found on #3230 that while I'd been running C++, Python, and R CI "both ways", I'd not been doing the same for R/Python interop testing. This PR fixes that.
#3230 goes on top of this

[ci] Run R/Python interop tests with new/shape flag off/on

---

.github/workflows/python-ci-single.yml
.github/workflows/r-ci.yml
.github/workflows/r-python-interop-testing.yml
apis/python/src/tiledbsoma/_flags.py
apis/r/R/Init.R
apis/system/tests/test_dataframe_write_python_read_r.py
apis/system/tests/test_dataframe_write_r_read_python.py

**Changes:**
While we're still running CI both ways, set the default to true for sandbox/dogfooding within the team, as discussed earlier this week.
This is atop #3230.

[ci] Default the new-shape feature to enabled, still testing both

---

libtiledbsoma/src/geometry/geometry.h
libtiledbsoma/src/geometry/operators/io/read.h
libtiledbsoma/src/geometry/operators/io/write.cc
libtiledbsoma/src/geometry/operators/io/write.h
libtiledbsoma/test/unit_soma_geometry_dataframe.cc

Change BinaryBuffer from `std::vector<uint8_t>` to `std::vector<std::byte>`

[c++] Change `BinaryBuffer` type

---

apis/python/src/tiledbsoma/_dataframe.py
apis/python/src/tiledbsoma/_tdb_handles.py
apis/python/src/tiledbsoma/io/shaping.py
apis/python/src/tiledbsoma/soma_dataframe.cc
apis/python/tests/test_dataframe.py
libtiledbsoma/src/soma/soma_array.cc
libtiledbsoma/src/soma/soma_array.h
libtiledbsoma/test/unit_soma_dataframe.cc

**Changes:**
Resolve discrepancies between function names and #2407.

[python] Proper prefixing for shape-related methods

---

apis/python/src/tiledbsoma/_tdb_handles.py

**Changes:**
At present we have four layers:
* User-facing Python like `DataFrame`
* Wrappers in `_tdb_handles.py`
* `pybind11` as in `apis/python/soma_dataframe.cc`
* `libtiledbsoma` as in `libtiledbsoma/src/soma/soma_array.h`
Throughout the new-shape project (#2407) I've been putting docstrings in the `_tdb_handles.py` layer which is silly because:
* Users don't read them
* It's double-keystroking on my part to write them (content is the same as in the user-facing layer)
This PR is a work in progress. It is not ready for review.

[python] Strip needless wrapper-class docstrings

---

apis/python/tests/test_shape.py

**Changes:**
#3236 had green CI pre-merge, red CI post-merge. Fix this.

[python] Fix bad merge of #3236

---

apis/python/MANIFEST.in
apis/python/requirements_spatial.txt
apis/python/setup.py

Add optional spatial ingest/outgest requirements to `setup.py`.

Add spatial-io optional dependencies

---

apis/python/requirements_dev.txt

Context: https://github.com/single-cell-data/TileDB-SOMA/issues/3246
https://github.com/agronholm/typeguard/pull/496 caused CI to begin failing on Python 3.9 ([example](https://github.com/single-cell-data/TileDB-SOMA/actions/runs/11522767244/job/32157898699)).
This pins Typeguard to https://github.com/agronholm/typeguard/commit/afad2c7b6be830900776922bb39f9346c2e77f6f (the last commit that works with our build), while we try to root-cause or work around more durably.

Pin typeguard@afad2c7

---

apis/r/DESCRIPTION
apis/r/NEWS.md
apis/r/R/RcppExports.R
apis/r/R/SOMADataFrame.R
apis/r/R/SOMANDArrayBase.R
apis/r/R/utils.R
apis/r/R/write_soma.R
apis/r/src/RcppExports.cpp
apis/r/src/rinterface.cpp
apis/r/tests/testthat/test-shape.R
apis/r/tests/testthat/test-write-soma-resume.R
libtiledbsoma/src/soma/soma_array.cc

**Changes:**
Direct R analogue of #3236 

[r] Proper prefixing for shape-related methods

---

apis/python/src/tiledbsoma/_dataframe.py
apis/r/DESCRIPTION
apis/r/NEWS.md
apis/r/R/RcppExports.R
apis/r/R/SOMADataFrame.R
apis/r/src/RcppExports.cpp
apis/r/src/rinterface.cpp
apis/r/tests/testthat/test-shape.R

**Changes:**
Straight-across port of #3235 from Python to R
The Python side has an optarg `check_only` defaultingi to `False`. I'll add that on the R side too -- on a PR after this.

[r] Bindings for `upgrade_domain`

---

apis/python/src/tiledbsoma/_dataframe.py
apis/python/src/tiledbsoma/_dense_nd_array.py
apis/python/src/tiledbsoma/_point_cloud_dataframe.py
apis/python/src/tiledbsoma/_read_iters.py
apis/python/src/tiledbsoma/_soma_array.py
apis/python/src/tiledbsoma/_sparse_nd_array.py
apis/python/src/tiledbsoma/_spatial_dataframe.py

**Changes:**
@nguyenv mentioned the other doing this. However while working on #3244 I realized it was a good deconfuse for me to go ahead and do this sooner than later.

[python] Rename `set_reader_coords` to `set_coords`

---

apis/r/DESCRIPTION
apis/r/NEWS.md
apis/r/R/TileDBObject.R
apis/r/tests/testthat/test-contexts.R

Allow plumbing tiledb-r contexts `SOMATileDBContext` objects into libtiledbsoma `soma_context()` objects
- `TileDBObject$new()`: plumb `tiledbsoma_ctx` config options into `soma_context()` when provided
[SC-56531](https://app.shortcut.com/tiledb-inc/story/56531) 
addresses #3213

[r] Plumb old-style contexts to new `libtiledbsoma` contexts

---

apis/r/DESCRIPTION
apis/r/NEWS.md
apis/r/R/TileDBObject.R

Also includes a backport of #3252 to the `release-1.15` branch

[r] Prepare for 1.15.0rc3

---

.github/workflows/python-ci-single.yml
.github/workflows/r-ci.yml
apis/python/src/tiledbsoma/_flags.py
apis/r/R/Init.R

While recent PRs have put the `release-1.15` branch in sync with current `main`, we shiould stop short of releasing the new-shape feature pending more documentation work as tracked on #2407 / [[sc-51048]](https://app.shortcut.com/tiledb-inc/story/51048).

Save new-shape feature-flag enable for 1.15.0

---

apis/python/src/tiledbsoma/_dense_nd_array.py
apis/python/src/tiledbsoma/_flags.py
apis/python/src/tiledbsoma/_tdb_handles.py
apis/python/src/tiledbsoma/soma_array.cc
apis/python/src/tiledbsoma/soma_dense_ndarray.cc
apis/python/src/tiledbsoma/soma_sparse_ndarray.cc
apis/python/tests/test_shape.py

**Changes:**
This is a split-out to simplify #3244 which turns out to be multi-faceted
No new unit tests -- proof of success here is that all existing unit-test cases contiunue to pass.

[python] Centralize sparse/dense `pybind11` shape methods

---

apis/python/src/tiledbsoma/_flags.py
apis/r/R/Init.R
libtiledbsoma/src/soma/managed_query.cc
libtiledbsoma/src/soma/managed_query.h
libtiledbsoma/test/common.cc
libtiledbsoma/test/unit_soma_sparse_ndarray.cc

**Changes:**
As found on #3244:
* The main context of #3244 is:
* For dense arrays only
* If any dim's subarray range isn't specified, core uses the core domain
* With new-shape feature-flag enabled, and with core 2.27 where dense arrays _can_ have current domain (they couldn't in 2.26), we are indeed using data-sized core current domain and huge core domain
* Put those together and we get these problems
* Note there are a few other issues on this PR, and a few _not_ yet included in this PR, other than that -- and those should be split out into separate PRs
* On this PR …

[c++] Apply subarrays for dense reads and writes

---

apis/python/src/tiledbsoma/_common_nd_array.py
apis/python/src/tiledbsoma/_dense_nd_array.py
apis/python/src/tiledbsoma/_sparse_nd_array.py
apis/python/tests/test_dense_nd_array.py
libtiledbsoma/src/soma/managed_query.h

**Changes:**
Fixes another core 2.27 corner case, aside from the main case on #3263.

[python] Fix 3D/4D cases with core 2.27

---

apis/python/src/tiledbsoma/_dense_nd_array.py
libtiledbsoma/src/soma/managed_query.cc
libtiledbsoma/src/soma/managed_query.h

**Changes:**
Following on #3263 and #3268 which deal with issues with core 2.27 and dense arrays. See also https://github.com/TileDB-Inc/centralized-tiledb-nightlies/issues/25.
There is more work to be done for R tests at 2.27 (#3270) but this resolves the final issue with the Python side.
There is a TODO marked in the code on this PR: there are other cases which _would have failed_ even at 2.26 and below, _had they been written_. This is addressed on #3271.

[python] Fix last 2.27+Python+dense failing test case

---

.pre-commit-config.yaml
apis/python/notebooks/tutorial_spatial.ipynb
apis/python/setup.py
apis/python/src/tiledbsoma/__init__.py
apis/python/src/tiledbsoma/_constants.py
apis/python/src/tiledbsoma/_multiscale_image.py
apis/python/src/tiledbsoma/_scene.py
apis/python/src/tiledbsoma/_spatial_util.py
apis/python/src/tiledbsoma/experimental/ingest.py
apis/python/tests/test_multiscale_image.py
apis/python/tests/test_scene.py

Update the TileDB-SOMA implementation to support the API changes in somacore 1.0.23.
This is includes:
* `MultiscaleImage` changes already approved in #3262 
* Update the `subcollection` parameters in the `Scene` class

[python] Update spatial API to match somacore 1.0.23

---

libtiledbsoma/src/soma/soma_array.cc
libtiledbsoma/src/soma/soma_array.h

**Changes:**
This introduces a `schema_` field to the `SOMAArray`, replacing any `mq->schema()` calls with `schema_` directly.

[c++] Use schema from `tiledb::Array` instead of `ManagedQuery`

---

libtiledbsoma/src/soma/managed_query.cc
libtiledbsoma/src/soma/managed_query.h
libtiledbsoma/src/soma/soma_array.cc

**Changes:**
This is some minor clean up that replaces the switch-case setting in `SOMAArray` into a separate `ManagedQuery::set_layout`.

[c++] Add `ManagedQuery::set_layout`

---

doc/source/python-tiledbsoma-io.rst
doc/source/python-tiledbsoma-logging.rst
doc/source/python-tiledbsoma.rst

**Issue and/or context:** This is one step in #3282. There is more work to do on #3282.
**Changes:**
I added new things to manually curated `.rst` files within `doc/`.
PR stacking as of today:
* `main`
* #3283
* #3284
* #3285

[docs] Add new things to `.rst` files

---

.github/workflows/python-ci-single.yml
.github/workflows/r-python-interop-testing.yml
apis/python/requirements_spatial.txt
apis/python/src/tiledbsoma/experimental/_xarray_backend.py
apis/python/tests/test_basic_xarray_io.py

**Issue:** Closes #3242
**Changes:**
Adds an Xarray `BackendArray` wrapper and `DataStore` for the `SOMADenseNDArray`. This allows the user to open a single `SOMADenseNDArray` as an Xarray `Dataset` with a single `DataArray`. 
This is important because we already use (and need) the SpatialData package, and it uses Xarray objects.

[python] Create `xarray` backend for DataArray types

---

apis/python/src/tiledbsoma/_dense_nd_array.py
apis/python/src/tiledbsoma/_tdb_handles.py
apis/python/tests/test_shape.py

**Changes:**
This was an omission on the 2.27 work.
PR stacking as of today:
* `main`
* #3288 
* #3289 
* Branch [kerl/dataframe-shape-temp](https://github.com/single-cell-data/TileDB-SOMA/tree/kerl/dataframe-shape-temp) which is a copy of of #3276, inserted here as a simplifying prerequisite as noted above
* #3290

[python] Include `tiledbsoma_upgrade_shape` for `DenseNDArray`

---

libtiledbsoma/src/soma/managed_query.cc
libtiledbsoma/src/soma/managed_query.h
libtiledbsoma/src/soma/soma_array.h

**Changes:**
- Add a new constructor that takes in a `SOMAArray` argument
- Add method `ManagedQuery::query_status`

[c++] Add `ManagedQuery` constructor that takes `SOMAArray`

---

apis/python/setup.py
apis/python/src/tiledbsoma/managed_query.cc
apis/python/src/tiledbsoma/pytiledbsoma.cc
libtiledbsoma/src/soma/managed_query.cc
libtiledbsoma/src/soma/managed_query.h
libtiledbsoma/src/soma/soma_array.h

**Changes:**
Adds `ManagedQuery` bindings to Pybind11 code.

[python] Add `ManagedQuery` bindings

---

apis/python/src/tiledbsoma/_dataframe.py
apis/python/src/tiledbsoma/_dense_nd_array.py
apis/python/src/tiledbsoma/_point_cloud_dataframe.py
apis/python/src/tiledbsoma/_read_iters.py
apis/python/src/tiledbsoma/_soma_array.py
apis/python/src/tiledbsoma/_sparse_nd_array.py
apis/python/src/tiledbsoma/_spatial_dataframe.py
apis/python/src/tiledbsoma/_tdb_handles.py
apis/python/src/tiledbsoma/_util.py

**Changes:**
This is clean-up work.
This takes the separate implementations of `_set_coords` from `_dataframe`, `_sparse_nd_array`,  `_spatial_dataframe`, and `_soma_array` into a single `_util._set_coords`. `_cast_domainish` was also moved out of `SOMAArrayWrapper` and into `_util` to support casting of domains and NEDs in `_set_coord`.
**Note for reviewers:**
I am unsure if `_util.py` is the appropriate place for this.

[python] Consolidate all `_set_coords` methods into single `_util` function

---

doc/source/python-tiledbsoma-axis.rst
doc/source/python-tiledbsoma-axiscolumnnames.rst
doc/source/python-tiledbsoma-axisquery.rst
doc/source/python-tiledbsoma-collection.rst
doc/source/python-tiledbsoma-coordinatespace.rst
doc/source/python-tiledbsoma-dataframe.rst
doc/source/python-tiledbsoma-densendarray.rst
doc/source/python-tiledbsoma-experiment.rst
doc/source/python-tiledbsoma-experimentaxisquery.rst
doc/source/python-tiledbsoma-intindexer.rst
doc/source/python-tiledbsoma-io.rst
doc/source/python-tiledbsoma-measurement.rst
doc/source/python-tiledbsoma-multiscaleimage.rst
doc/source/python-tiledbsoma-pointclouddataframe.rst
doc/source/python-tiledbsoma-resultorder.rst
doc/source/python-tiledbsoma-scene.rst
doc/source/python-tiledbsoma-somatiledbcontext.rst
doc/source/python-tiledbsoma-sparsendarray.rst
doc/source/python-tiledbsoma-sparsendarrayread.rst
doc/source/python-tiledbsoma-tiledbcreateoptions.rst
doc/source/python-tiledbsoma-tiledbwriteoptions.rst
doc/source/python-tiledbsoma.rst

**Issue and/or context:** Ongoing work as part of #3282. Also fixes #3227.
**What's right**
* Go here: https://tiledbsoma.readthedocs.io/en/stable/python-tiledbsoma.html
* Scroll to "Classes"
* Pick one like `tiledbsoma.Measurement`
* Hover over that:
* This is a link; click it and you get here: https://tiledbsoma.readthedocs.io/en/stable/_autosummary/tiledbsoma.Measurement.html#tiledbsoma.Measurement
* Docstrings are present for the class -- _full_ docstrings and not just the first summary sentence
**What's wrong**
* Simply go one level deeper: scroll down to "Methods"
* Hover over a method, e.g. `add_new_collection`
* This is _not_ a hyperlink
* What you see is the _first sentence_ of its docstring
* Nothing you can click on will show you the rest of the docstring
At the first level we …

[docs] Fix Sphinx issue with linkless summaries

---

libtiledbsoma/src/CMakeLists.txt
libtiledbsoma/src/soma/soma_geometry_dataframe.cc
libtiledbsoma/src/soma/soma_geometry_dataframe.h
libtiledbsoma/src/soma/soma_object.cc
libtiledbsoma/src/tiledbsoma/tiledbsoma
libtiledbsoma/src/utils/arrow_adapter.cc
libtiledbsoma/src/utils/arrow_adapter.h
libtiledbsoma/src/utils/common.h
libtiledbsoma/test/CMakeLists.txt
libtiledbsoma/test/common.cc
libtiledbsoma/test/unit_soma_geometry_dataframe.cc

This PR adds the new `SOMAGeometryDataFrame` object. This new object requires spatial axes to be determined and uses them internally to index geometry objects stored as a WKB encoded attribute. To differentiate between binary attributes and WKB binary attributes the Arrow schema requires a `dtype` metadata key with the value `WKB`.

[c++] Geometry Dataframe

---

.github/workflows/python-ci-single.yml
.github/workflows/r-ci.yml
.github/workflows/r-python-interop-testing.yml
apis/python/src/tiledbsoma/_dataframe.py
apis/python/src/tiledbsoma/_dense_nd_array.py
apis/python/src/tiledbsoma/_flags.py
apis/python/src/tiledbsoma/_point_cloud_dataframe.py
apis/python/src/tiledbsoma/_sparse_nd_array.py
apis/python/src/tiledbsoma/io/ingest.py
apis/python/tests/test_basic_anndata_io.py
apis/python/tests/test_dataframe.py
apis/python/tests/test_registration_mappings.py
apis/python/tests/test_shape.py
apis/python/tests/test_sparse_nd_array.py
apis/r/R/Init.R
apis/r/R/utils-arrow.R
apis/r/R/write_soma.R
apis/r/tests/testthat/test-SOMASparseNDArray.R
apis/r/tests/testthat/test-shape.R
apis/r/tests/testthat/test-write-soma-resume.R

**Changes:**
These have been on by default for several weeks now. It's time to keep them.
Note there is another bit of logic (same files) around whether dense arrays can have current domain, which can't be removed until core 2.27 is released, and we move our core dependency to 2.27.
This is less ambitious than #3259, which needs to wait until core 2.27.

[python/r] Move beyond the new-shape feature flag

---

apis/python/src/tiledbsoma/io/ingest.py

**Issue and/or context:** As for example
https://github.com/single-cell-data/TileDB-SOMA/actions/runs/11727945417/job/32670239706?pr=3300
Note that `anndata` 0.11 just dropped, and I had failed to run any pre-assess checks using the RC series.

[python] Unbreak CI with `anndata==0.11`

---

apis/python/src/tiledbsoma/_dataframe.py
apis/python/tests/test_dataframe.py
apis/r/R/SOMADataFrame.R
apis/r/tests/testthat/test-SOMADataFrame.R
apis/r/tests/testthat/test-shape.R

Arose during discussion of #2407 / [[sc-51048]](https://app.shortcut.com/tiledb-inc/story/51048), but the defect here predates the new-shape work.

[python/r] Enforce dataframe domain lower bound == 0

---

apis/python/notebooks/tutorial_soma_shape.ipynb

**Changes:**
* Notebook material for Python. (R material will be a separate PR.)
* The Python material is ready for review.
* Handy link for reviewers:
* https://github.com/single-cell-data/TileDB-SOMA/blob/kerl/new-shape-notebook-and-vignette/apis/python/notebooks/tutorial_soma_shape.ipynb
* I'm working on the R material.

[python] Tutorial notebook for the new-shape feature

---

apis/python/src/tiledbsoma/io/shaping.py

**Changes:**
Make this more performant in the most common case. This helps with larger datasets stored remotely, as found by experiment.

[python] Performance improvement for experiment-level resize

---

apis/python/notebooks/tutorial_soma_shape.ipynb

**Changes:**
Fix bad merge of #3294. Looks like this commit: https://github.com/single-cell-data/TileDB-SOMA/pull/3294#discussion_r1833109086
Review link:
https://github.com/single-cell-data/TileDB-SOMA/blob/kerl/fix-notebook-merge/apis/python/notebooks/tutorial_soma_shape.ipynb

[python] Fix bad merge of soma-shapes notebook

---

libtiledbsoma/test/common.cc

**Changes:**
Fix a compiler warning:
```
/home/ubuntu/git/single-cell-data/TileDB-SOMA/libtiledbsoma/test/common.cc: In function ‘std::unique_ptr<ArrowSchema> helper::create_index_cols_info_schema(const std::vector<DimInfo>&)’:
/home/ubuntu/git/single-cell-data/TileDB-SOMA/libtiledbsoma/test/common.cc:156:26: warning: comparison of integer expressions of different signedness: ‘size_t’ {aka ‘long unsigned int’} and ‘int64_t’ {aka ‘long int’} [-Wsign-compare]
156 |     for (size_t i = 0; i < schema->n_children; ++i) {
```

[c++] Fix a compiler warning

---

apis/python/src/tiledbsoma/io/_common.py
apis/python/src/tiledbsoma/io/ingest.py

Follow-on to #3305
Unfortunately, I still see these which appear to be outside of our control:
```
>>> import scanpy
/Users/kerl/.pyenv/versions/3.11.9/lib/python3.11/site-packages/anndata/utils.py:429: FutureWarning: Importing read_csv from `anndata` is deprecated. Import anndata.io.read_csv instead.
warnings.warn(msg, FutureWarning)
/Users/kerl/.pyenv/versions/3.11.9/lib/python3.11/site-packages/anndata/utils.py:429: FutureWarning: Importing read_excel from `anndata` is deprecated. Import anndata.io.read_excel instead.
warnings.warn(msg, FutureWarning)
/Users/kerl/.pyenv/versions/3.11.9/lib/python3.11/site-packages/anndata/utils.py:429: FutureWarning: Importing read_hdf from `anndata` is deprecated. Import anndata.io.read_hdf instead.
warnings.warn(msg, FutureWarning) …
```

[python] Fix some warnings at `anndata==0.11`

---

.github/workflows/r-python-interop-testing.yml
.github/workflows/r-valgrind.yaml

More of #1871 -- which I didn't apply to sufficiently many CI YAML files.

[r/ci] Avoid log truncation with "Last 13 lines of output"

---

.github/workflows/r-valgrind.yaml

**Issue and/or context:** #3315 [[sc-59088]](https://app.shortcut.com/tiledb-inc/story/59088/recent-failures-in-tiledb-soma-s-r-valgrind-ci)
**Changes:** With #3313 in place to avoid the problematic (default) truncation to 13 lines of output, I ran https://github.com/single-cell-data/TileDB-SOMA/actions/runs/11744677785/job/32720341469 and saw
```
2024-11-08T15:36:21.1886016Z   **4849** new/new[] failed and should throw an exception, but Valgrind
2024-11-08T15:36:21.1887203Z   **4849**    cannot throw exceptions and so is aborting instead.  Sorry.
```
I'm imitating a memory config from other R CI YAMLs in our project in hopes this will help.
Manual `r-valgrind` run (since that CI doesn't run on every PR):
https://github.com/single-cell-data/TileDB-SOMA/actions/runs/ …

[r/ci] Try to unbreak `r-valgrind` CI

---

.github/workflows/pkgdown.yaml
.github/workflows/r-ci.yml
.github/workflows/r-python-interop-testing.yml
.github/workflows/r-valgrind.yaml

Remove specific installation steps for tiledb-r as the doublepin was removed in #3006
Resolves #3314
[SC-59087](https://app.shortcut.com/tiledb-inc/story/59087)

[r/ci] Remove tiledb-r specific install

---

apis/python/src/tiledbsoma/_multiscale_image.py
apis/python/tests/test_multiscale_image.py

This adds two new methods to access the URIs of resolution levels in the MultiscaleImage.
1. `levels` - a method similar to the `Collection.members` method. Returns shape instead of element types as all levels have type `DenseNDArray`.
2. `level_uri` - returns just the URI for a level specified by either index or name.
This addition is needed for exporting a `MultiscaleImage` level to SpatialData.

[python] Add `MultiscaleImage` methods to access level URI

---

apis/python/src/tiledbsoma/_multiscale_image.py
apis/python/tests/test_multiscale_image.py

The to/from level 0 transform is always the identity transform. Return the `IdentityTransform` class instead of the more generic `ScaleTransform` with ones for the scale factors.

[python] Return identity for `MultiscaleImage` transform to/from level 0

---

apis/python/src/tiledbsoma/io/outgest.py
apis/python/tests/test_basic_anndata_io.py

**Changes:**
Found a spot in one-off/ad-hoc testing in my laptop on a particular old dataset.

[python] Use new shape in one more spot

---

apis/python/src/tiledbsoma/experimental/outgest.py
apis/python/tests/test_export_point_cloud_dataframe.py
apis/python/tests/test_spatial_outgest_util.py

Fixes:
* Fix changes from SOMA coordinate axis names to SpatialData coordinate dimension names.
* Invert SOMA scene-to-points transform to correctly store SpatialData point-to-scene transformation.
* Fix type annotation for GeoPandas `GeoDataFrame`.
Clean-up:
* Import `spatialdata` as `sd`. 
* Add tests for converting transformations.

Fix and test SpatialData transformation exporter

---

.readthedocs.yml

- #3154
- [RTD build failed](https://readthedocs.org/projects/tiledbsoma/builds/26329893/) after #3331 
- Test RTD build from this branch ✅: https://readthedocs.org/projects/tiledbsoma/builds/26331078/
**Changes:**
Use Ubuntu 24.04 in RTD build

[python/docs] Use `ubuntu-24.04` (C++ 20) for `readthedocs`

---

.pre-commit-config.yaml
apis/python/setup.py
apis/python/src/tiledbsoma/_dataframe.py
apis/python/src/tiledbsoma/_eager_iter.py
apis/python/src/tiledbsoma/_experiment.py
apis/python/src/tiledbsoma/_fast_csr.py
apis/python/src/tiledbsoma/_fastercsx.py
apis/python/src/tiledbsoma/_indexer.py
apis/python/src/tiledbsoma/_query.py
apis/python/src/tiledbsoma/_read_iters.py
apis/python/src/tiledbsoma/_types.py
apis/python/src/tiledbsoma/_util.py
apis/python/src/tiledbsoma/experimental/_xarray_backend.py
apis/python/src/tiledbsoma/experimental/ingest.py
apis/python/tests/test_eager_iter.py
apis/python/tests/test_experiment_query.py

Accompanying SOMA "core" changes: https://github.com/single-cell-data/SOMA/pull/244
It can be awkward having some implementations in that repo:
- I'm experimenting with a `dask` kwarg to `ExperimentAxisQuery.to_anndata`; EAQ impl has lived in the core repo, to date, but arguably should not
- @bkmartinjr has been working on improved "fast CSR" algorithms, which were previously implemented and used in the SOMA core repo, but arguably belong in an implementation repo like this one.
**Changes:**
Move files and classes from single-cell-data/SOMA to this repo:
- `_query.py`:
- `Axis`
- `AxisIndexer`
- `AxisQueryResult`
- `ExperimentAxisQuery`
- `MatrixAxisQuery`
- `JoinIDCache`
- `_fast_csr.py`
- `_eager_iter.py`

[python] Ingest `somacore` classes

---

apis/python/README.md

This removes the tiledb-py requirement from the `README.md`. All other steps remain the same.

[python] Update README.md to remove tiledb-py

---

apis/python/README.md

Since moving to C++20, we now use `std::fmt` and have removed `spdl::fmt`.

[python] Update `README.md` to remove `fmt` reference

---

apis/python/src/tiledbsoma/experimental/outgest.py
apis/python/tests/test_export_multiscale_image.py

Exports a single resolution level of `MultiscaleImage` to a SpatialData `Image2DModel` or `Image3DModel`.

[python] Add MultiscaleImage level SpatialData exporter

---

.github/workflows/python-packaging.yml

**Issue and/or context:** #3154 #3348
**Changes:** Ensure we have GCC >= 13 for our nightly (and at-tag) sdist&wheels CI.
**Notes for Reviewer:** https://github.com/single-cell-data/TileDB-SOMA/issues/3348#issuecomment-2489142617

[ci] Change `manylinux` version for sdist&wheels CI (C++ 20)

---

scripts/update-tiledb-version.py

When core releases are missing artifacts for one or more platforms (e.g. [2.27.0-rc1](https://github.com/TileDB-Inc/TileDB/releases/tag/2.27.0-rc1), [2.27.0-rc2](https://github.com/TileDB-Inc/TileDB/releases/tag/2.27.0-rc2)), have our one-stop artifact updater print more easily accessible information about what's missing.
Tracking issue: #3364.

[packaging] More failure info in `update-tiledb-versions.py`

---

apis/python/src/tiledbsoma/experimental/outgest.py
apis/python/tests/test_export_point_cloud_dataframe.py

Add a function to export a SOMA `PointCloudDataFrame` to the SpatialData "points" model.

[python] Add PointCloudDataFrame to SpatialData points model

---

libtiledbsoma/src/utils/arrow_adapter.cc
libtiledbsoma/test/common.cc
libtiledbsoma/test/unit_soma_collection.cc
libtiledbsoma/test/unit_soma_dataframe.cc
libtiledbsoma/test/unit_soma_dense_ndarray.cc
libtiledbsoma/test/unit_soma_geometry_dataframe.cc
libtiledbsoma/test/unit_soma_point_cloud_dataframe.cc
libtiledbsoma/test/unit_soma_sparse_ndarray.cc

**Issue and/or context:** As tracked on issue #2407 / [[sc-51048]](https://app.shortcut.com/tiledb-inc/story/51048). Also #3273.
**Changes:**
The `use_current_domain` logic was solely transitional while awaiting core 2.27.0rc3, which we now have in place. It's time to dismantle this code which is now needlessly complicating our unit-test framework.
This is first in a series of PRs. While the changes are trivial, the line-count can be intimidating when it's attempted all at once.
Stacked on #3368

[c++] Some `use_current_domain` unit-test/feature-flag teardown, part 1 of 4

---

libtiledbsoma/src/utils/arrow_adapter.cc
libtiledbsoma/src/utils/arrow_adapter.h

**Issue and/or context:** As tracked on issue #2407 / [[sc-51048]](https://app.shortcut.com/tiledb-inc/story/51048). Also #3273.
**Changes:**
This is second in a series of PRs. While the changes are trivial, the line-count can be intimidating when it's attempted all at once.
Stacked on https://github.com/single-cell-data/TileDB-SOMA/pull/3369

[c++] Some `use_current_domain` unit-test/feature-flag teardown, part 2 of 4

---

libtiledbsoma/src/utils/arrow_adapter.cc
libtiledbsoma/test/common.cc
libtiledbsoma/test/common.h
libtiledbsoma/test/unit_soma_collection.cc
libtiledbsoma/test/unit_soma_dataframe.cc
libtiledbsoma/test/unit_soma_dense_ndarray.cc
libtiledbsoma/test/unit_soma_geometry_dataframe.cc
libtiledbsoma/test/unit_soma_point_cloud_dataframe.cc
libtiledbsoma/test/unit_soma_sparse_ndarray.cc

**Issue and/or context:** As tracked on issue #2407 / [[sc-51048]](https://app.shortcut.com/tiledb-inc/story/51048). Also #3273.
**Changes:**
This is third in a series of PRs. While the changes are trivial, the line-count can be intimidating when it's attempted all at once.
Stacked on https://github.com/single-cell-data/TileDB-SOMA/pull/3370
The line count is big but mostly whitespace. Suggestion: hide whitespace when reviewing:
https://github.com/single-cell-data/TileDB-SOMA/pull/3371/files?diff=split&w=1

[c++] Some `use_current_domain` unit-test/feature-flag teardown, part 3 of 4

---

apis/python/requirements_spatial.txt
apis/python/src/tiledbsoma/experimental/_util.py
apis/python/src/tiledbsoma/experimental/_xarray_backend.py
apis/python/src/tiledbsoma/experimental/outgest.py
apis/python/tests/test_export_multiscale_image.py

Add function to export a full `MultiscaleImage` to a SpatialData `Image2DModel` or `Image3DModel`. 
Note: At the time of this PR, SpatialData is in the process of changing the multiscale image model to move from the legacy `xarray_datatree.datatree.DataTree` class to the new `xarray.DataTree` model. This PR implements both versions and checks which to use based on the SpatialData version.

[python] Add export for `MultiscaleImage` to SpatialData

---

apis/r/DESCRIPTION
apis/r/NEWS.md

[r] Prepare for 1.15.0rc4

---

libtiledbsoma/test/unit_soma_group.cc

Remove usage of deprecated `dump` function with stream operator.

[c++] Remove use of deprecated schema-display function

---

apis/python/src/tiledbsoma/experimental/_xarray_backend.py
apis/python/src/tiledbsoma/experimental/outgest.py

Fix two typos in warnings and try importing geopandas after spatialdata.

[python] Fix typos and import order in the spatial outgest

---

apis/python/src/tiledbsoma/_query.py
apis/python/src/tiledbsoma/io/outgest.py
apis/python/tests/test_experiment_query.py

Fixes #3360 
**Changes:**
obsp/varp slots in the AnnData returned by ExperimentAxisQuery.to_anndata will be sparse matrices.  Previously they were dense NDArray.
1. this required a bit of refactoring
2. as part of this, obsp/varp will be read using the partitioned reader (same as X layers)

ExperimentAxisQuery - to_anndata obsp/varp as sparse matrices

---

apis/python/src/tiledbsoma/_scene.py
apis/python/src/tiledbsoma/soma_collection.cc
apis/python/tests/test_scene.py
libtiledbsoma/src/soma/soma_scene.cc
libtiledbsoma/src/soma/soma_scene.h

1. Add spatial disclaimer as warning.
2. Implement writing the coordinate space at create.
3. Use Scene C++ code instead of going through Python superclass.
* Requires updating Scene C++ create method to match behavior of existing code (do not create `obsl`/`varl`/`img` at create).

[python] Update Scene create method in the Python API

---

apis/python/src/tiledbsoma/io/spatial/outgest.py
apis/python/tests/test_export_multiscale_image.py
apis/python/tests/test_export_point_cloud_dataframe.py

Add support for exporting a `PointCloudDataFrame` or `GeometryDataFrame` to SpatialData even if we don't have a mapping from the object to the `Scene` it is stored in.

[python] Add support for exporting to SpatialData without transform

---

.github/workflows/r-ci.yml

Not important, but I noticed this use of CXX17 earlier this week and wanted to fix it before I forgot about it
xref: https://github.com/single-cell-data/TileDB-SOMA/issues/3154, https://github.com/single-cell-data/TileDB-SOMA/pull/3352

[ci] Replace CXX17FLAGS with CXX20FLAGS

---

apis/r/R/BlockwiseIter.R
apis/r/tests/testthat/test-00-Blockwise.R

The blockwise iterator + re-indexer in the R API currently return a matrix with the full domain of the array, not the re-indexed shape. This PR adjusts the behavior to return the matrix with the re-indexed shape
The new behavior mimics the Python API demonstrated [here](https://gist.github.com/mojaveazure/beb4ecda9d37dc67140ba494e4ec43a5#file-soma-blockwise-reindexer-py-rmd)
- `BlockwiseSparseReadIter$private$soma_reader_transform()`: if re-indexing is enabled, adjust the shape for each re-indexed axis to the re-indexed shape
#3385 [SC-59743](https://app.shortcut.com/tiledb-inc/story/59743)

[r] Adjust blockwise + re-indexer to return condensed matrix, not full domain

---

apis/python/tests/test_spatial_outgest_util.py

One instance of renaming the `experimental` module was missed in PR #3384.

[python] Change import `experimental` -> `io.spatial` in test

---

apis/python/requirements_spatial.txt

**Issue and/or context:** #3398
**Changes:** Pinning dask to 2024.11.2 version

[python/ci] Pin dask version 2024.11.2 to unblock CI

---

apis/r/DESCRIPTION
apis/r/NEWS.md
apis/r/R/RcppExports.R
apis/r/R/SOMADataFrame.R
apis/r/R/SOMANDArrayBase.R
apis/r/src/RcppExports.cpp
apis/r/src/rinterface.cpp
apis/r/tests/testthat/test-11-shape.R

**Changes:**
These parallel logic surfaced on the Python side but not on the R side.
Found while working on https://cloud.tiledb.com/academy/structure/life-sciences/single-cell/tutorials/shapes/
There is unit-test coverage. Also, I ran the cells in https://github.com/TileDB-Inc/TileDB-Documentation/pull/454.

[r] Add `check_only` support for domain/shape updates

---

apis/python/src/tiledbsoma/io/spatial/outgest.py
apis/python/tests/test_export_point_cloud_dataframe.py

The previous implementation of `to_spatial_data_points` was exporting data to a pandas `DataFrame`, but SpatialData expected a dask `DataFrame`. This type error was not caught in the tests using `spatialdata.models.PointsModel.validate`. This fixes the tests to check the type along with additional validataion by using `spatialdata.models.get_model` instead of the `validate` methods, and updates the exporter to return the correct type.

[python] Fix output type when exporting `PointCloudDataFrame` to SpatialData points

---

apis/python/src/tiledbsoma/_dataframe.py
apis/python/src/tiledbsoma/_dense_nd_array.py
apis/python/src/tiledbsoma/_point_cloud_dataframe.py
apis/python/src/tiledbsoma/_read_iters.py
apis/python/src/tiledbsoma/_sparse_nd_array.py
apis/python/src/tiledbsoma/_util.py
apis/python/src/tiledbsoma/managed_query.cc
apis/python/tests/test_dataframe.py
apis/python/tests/test_dense_nd_array.py
apis/python/tests/test_sparse_nd_array.py
libtiledbsoma/src/soma/managed_query.cc
libtiledbsoma/src/soma/managed_query.h

This finishes up https://github.com/single-cell-data/TileDB-SOMA/issues/3053 [[sc-54744]](https://app.shortcut.com/tiledb-inc/story/54744/python-soma-read-does-an-open-on-an-already-open-array)
**Changes:**
- Remove `clib.SOMAArray.open` in all `SOMAArray` derived class `read` calls
- Pass query arguments coords, column names, result order, value filter, and platform config that were formerly passed to `clib.SOMAArray.open` or `clib.SOMAArray.reset` instead to `TableReadIter` and `SparseNDArrayRead`
- `_set_coords` on the `ManagedQuery` rather than through `SOMAArray`
- `_arrow_table_reader` and `SparseTensorReadIterBase` initialize a `ManagedQuery` object and set the query arguments listed above; set up the read; and submit reads and return results until the …

[python] Remove double open For `SOMAArray` reads

---

apis/python/src/tiledbsoma/io/conversions.py
apis/python/src/tiledbsoma/io/ingest.py
apis/python/tests/test_basic_anndata_io.py

**Issue and/or context:** #3353 [[sc-59407]](https://app.shortcut.com/tiledb-inc/story/59407)
**Changes:**
As proposed on #3353 [[sc-59407]](https://app.shortcut.com/tiledb-inc/story/59407)

[python] Protect against huge enum-of-strings input

---

.github/workflows/python-ci-packaging.yml
apis/r/tools/get_tarball.R
libtiledbsoma/cmake/Modules/FindTileDB_EP.cmake

FYI, intentionally (per @ihnorton ) we had core `2.27.0-rc4` but `2.27.0.rc5` (i.e. `-` -> `.`).

[c++] Use core 2.27.0.rc5

---

apis/python/src/tiledbsoma/managed_query.cc
libtiledbsoma/src/soma/managed_query.cc
libtiledbsoma/src/soma/managed_query.h

The new `ManagedQuery` class `set_condition` method was resetting all instance state. This had the side-effect of losing layout and other query params for any `ManagedQuery` with a query condition.

[c++] `ManagedQuery::set_condition` should not reset entire instance state

---

.github/workflows/python-ci-packaging.yml
apis/r/tools/get_tarball.R
libtiledbsoma/cmake/Modules/FindTileDB_EP.cmake

Script invocation:
```
./scripts/update-tiledb-version.py 2.27.0
```
This PR simply commits those autogenerated mods.
[[sc-59686]](https://app.shortcut.com/tiledb-inc/story/59686/update-projects-to-tiledb-2-27)

[c++] Use core 2.27.0

---

apis/python/src/tiledbsoma/io/spatial/__init__.py
apis/python/src/tiledbsoma/io/spatial/outgest.py
apis/python/tests/test_basic_spatialdata_io.py

Add `to_spatial_data` exporter that exports a full SOMA `Experiment` to a `SpatialData` object.

[python] Export full experiment to SpatialData

---

apis/python/src/tiledbsoma/_query.py
apis/python/tests/test_experiment_query_spatial.py

Add the method `to_spatial_data` to `ExperimentAxisQuery` that exports the results from the axis query to a `SpatialData` object.
[[sc-59943]](https://app.shortcut.com/tiledb-inc/story/59943/add-spatialdata-exporter-to-experimentaxisquery)

[python] Add `to_spatial_data` method to `ExperimentAxisQuery` 

---

libtiledbsoma/src/soma/soma_array.cc
libtiledbsoma/src/soma/soma_array.h

**Issue and/or context:** As pointed out by @XanthosXanthopoulos .
**Changes:**
This makes the zero-basing logic the same for both old-style and new-style (pre-1.15 and post-1.15) sparse arrays the same.
It also renames some methods which had names that did not well reflect their purposes.
No unit tests are changed, so all passes still: this mod is a no-op for all non-spatial data since those all have soma domain/maxdomain (core current domain/domain) starting at 0. However, this helps clear the path for further development on other arrays which may have their domain/maxdomain not starting at zero.

[c++] Match zero-basing for old/new sparse-array shapes

---

apis/python/setup.py
apis/python/src/tiledbsoma/io/ingest.py

Pre-emptively avoids https://github.com/single-cell-data/TileDB-SOMA/pull/new/kerl/pin-scipy-less-than-1.15. Tracking: https://github.com/single-cell-data/TileDB-SOMA/issues/3444.
Note that scipy 1.15.0 is not released yet, but, its 1.15.0rc1 is out, and our next tiledbsoma release (coincidentally also named 1.15.0) is coming out soon, and we want to pre-emptively protect against any time window in which we could suffer from this bug. Once https://github.com/scverse/anndata/issues/1802 is addressed (be it by a bugfix in SciPy or AnnData), we can remove this pin.
**Changes:**

[python] Pre-emptively avoid SciPy 1.15, pending a bugfix

---

apis/python/src/tiledbsoma/_indexer.py
apis/python/src/tiledbsoma/reindexer.cc
apis/python/tests/test_indexer.py
libtiledbsoma/src/reindexer/reindexer.h

IntIndexer would do strange things when given malformed inputs.  See for example sc-60689 and sc-60690
IntIndexer also incorrectly handled any arrow array with an offset, and would return incorrect outputs.  See sc-60795
**Changes:**
1. More error checking in pybind-ings, plus tests.  The desired parts of the implicit casting are moved up into the Python code where they are more easily managed.
2. Minimal fix to correctly use array offsets (note: this code needs refactoring to use nanoarrow interfaces)

[python,c++] Improve error handling in `IntIndexer`

---

apis/python/src/tiledbsoma/_query.py
apis/python/src/tiledbsoma/io/spatial/__init__.py
apis/python/src/tiledbsoma/io/spatial/outgest.py
apis/python/tests/test_basic_spatialdata_io.py
apis/python/tests/test_experiment_query_spatial.py
apis/python/tests/test_export_multiscale_image.py
apis/python/tests/test_export_point_cloud_dataframe.py
apis/python/tests/test_spatial_outgest_util.py

Change name of methods that contain `to_spatial_data` to `to_spatialdata`.

[python] Rename `to_spatial_data` -> `to_spatialdata`

---

.github/workflows/libtiledbsoma-asan-ci.yml
Makefile
libtiledbsoma/README.md
scripts/bld
scripts/update-tiledb-version.py

1. Update `bld/script.sh` to skip downloading TileDB prebuilt for all non-`Release` configurations.
2. Add new weekly CI job that runs the CI for the ASAN configuration.
3. Update developer docs for building with sanitizers.
[[sc-34306]](https://app.shortcut.com/tiledb-inc/story/34306/soma-run-sanitizer-s-in-ci)

[c++] Add ASAN run of CI to weekly CI job

---

apis/python/src/tiledbsoma/soma_object.cc

As reported internally, the pybind11 implemented `SOMAObject.open` contains a conditional fall-through as of #3402.
**Changes:**
Wrap the C++ call in try-catch block where `SOMAObject::open` should already throw an exception for unknown types. In the Pybind11 code, if the conditional falls through then trigger an `assert` for unreachable code.

[python] Fix conditional fall-through in `SOMAObject.open`

---

apis/python/src/tiledbsoma/_query.py
apis/python/src/tiledbsoma/io/spatial/__init__.py
apis/python/src/tiledbsoma/io/spatial/outgest.py
apis/python/tests/test_basic_spatialdata_io.py
apis/python/tests/test_experiment_query_spatial.py
apis/python/tests/test_export_multiscale_image.py
apis/python/tests/test_export_point_cloud_dataframe.py
apis/python/tests/test_spatial_outgest_util.py

Manual backport following https://github.com/single-cell-data/TileDB-SOMA/pull/3449#issuecomment-2546122830

[Backport release-1.15][python] Rename `to_spatial_data` -> `to_spatialdata`

---

.pre-commit-config.yaml
apis/python/setup.py

Found on
https://github.com/single-cell-data/TileDB-SOMA/actions/runs/12364349712/job/34507422201
in light of
https://github.com/single-cell-data/TileDB-SOMA/pull/3455
[[sc-59686]](https://app.shortcut.com/tiledb-inc/story/59686/update-projects-to-tiledb-2-27)

[python] Use `somacore` 1.0.26

---

apis/python/src/tiledbsoma/fastercsx.cc
apis/python/tests/test_libfastercsx.py
libtiledbsoma/src/utils/fastercsx.h

The C++ `fastercsx` layer assumes all COO data "chunks" are of the same size.  However, the Python bindings failed to perform this check, which in some circumstances can lead to reads off the end of an array buffer.
**Changes:**
1. added explicit check in the Python binding
2. added `NDEBUG` assertion in the core package
3. added a test that the error is caught

[python/c++] Fix invalid memory read in `fastercsx`

---

apis/python/src/tiledbsoma/_soma_array.py
apis/python/src/tiledbsoma/_tdb_handles.py
apis/python/src/tiledbsoma/io/spatial/_xarray_backend.py
apis/python/src/tiledbsoma/pytiledbsoma.cc
apis/python/src/tiledbsoma/soma_array.cc
apis/python/tests/test_dataframe.py
apis/python/tests/test_dense_nd_array.py
apis/python/tests/test_platform_config.py
apis/python/tests/test_sparse_nd_array.py
libtiledbsoma/src/soma/soma_array.h
libtiledbsoma/src/utils/arrow_adapter.cc
libtiledbsoma/src/utils/arrow_adapter.h
libtiledbsoma/test/unit_soma_dataframe.cc

* Create new `PlatformSchemaConfig` class with only TileDB schema properties
* Create new method `schema_config_options` that returns the `PlatformSchemaConfig`.

[python/c++] Deprecate `config_options_from_schema` in favor of new function

---

apis/python/tests/test_experiment_query_spatial.py
scripts/show-versions.py

Extra tests to help with debugging sporadic failures in the Python 3.12 tests for exporting to SpatialData from an `ExperimentAxisQuery`.
Issue #3471

[python] Add extra asserts for SpatialData tests

---

doc/source/notebooks/tutorial_soma_shape.ipynb
doc/source/notebooks/tutorial_spatial.ipynb

**Issue and/or context:** Post-1.15.0 :( I realized that when I synced `main` and `release-1.15` (modulo necessary differences of course) the files that had been symlinks in `main` became plain files in `release-1.15` -- worse, files containing only the path to their referees. :(
[[sc-59686]](https://app.shortcut.com/tiledb-inc/story/59686/update-projects-to-tiledb-2-27)
**Changes:** Make these symlinks as they should be.

[docs] Fix broken tutorial-doc symlinks in `release-1.15`

---

apis/r/DESCRIPTION
apis/r/NEWS.md
apis/r/src/groups.cpp
apis/system/tests/test_character_write_python_read_r.py
apis/system/tests/test_character_write_r_read_python.py

String group-level metadata was previously encoded using `TILEDB_CHAR` or `TILEDB_STRING_ASCII`; however, this resulting in the metadata being read in as `bytes` in the Python API instead of as `str`. The Python API already [encodes all strings (`str`) as `TILEDB_STRING_UTF8`](https://github.com/single-cell-data/TileDB-SOMA/blob/884342a1ceb994d677c52c74ba2d789fc4e208d4/apis/python/src/tiledbsoma/common.cc#L211-L223) so this PR brings the R API in-line with the Python API
[SC-61001](https://app.shortcut.com/tiledb-inc/story/61001)
adresses #2698

[r] Write group-level string metadata as `TILEDB_STRING_UTF8`

---

apis/python/src/tiledbsoma/__init__.py
apis/python/src/tiledbsoma/_query.py
apis/python/tests/test_experiment_query.py

**Issue and/or context:** After 1.15.0 was tagged, we found that users can no longer instantiate `tiledbsoma.ExperimentAxisQuery`.
Repro:
<details>
```
import scanpy as sc
import tiledbsoma.io
import tempfile
pbmc3k = sc.datasets.pbmc3k()
sc.pp.calculate_qc_metrics(pbmc3k, inplace=True)
tmpdir = tempfile.TemporaryDirectory().name
tiledbsoma.io.from_anndata(tmpdir, anndata=pbmc3k, measurement_name="RNA")
exp = tiledbsoma.Experiment.open(tmpdir)
exp.obs.read().concat().to_pandas()
exp.ms["RNA"].var.read().concat().to_pandas()
exp.ms["RNA"].X["data"].read().coos().concat()
exp.obs.read(
coords=[slice(0, 99)],
value_filter="total_counts > 4000",
column_names=["soma_joinid", "obs_id", "total_counts"],
).concat().to_pandas()
exp.ms["RNA"].var.read(
value_filter="var_id in …
```

[python] Re-enable `tiledbsoma.ExperimentAxisQuery`

---

apis/r/DESCRIPTION
apis/r/NEWS.md
apis/r/src/groups.cpp

**Issue and/or context:** Backport of #3469. Also label 1.15.1.
**Changes:**

[Backport release-1.15][r] Write group-level string metadata as `TILEDB_STRING_UTF8`; 1.15.1

---

libtiledbsoma/src/soma/soma_array.cc
libtiledbsoma/src/soma/soma_array.h
libtiledbsoma/src/soma/soma_dataframe.cc
libtiledbsoma/src/soma/soma_dataframe.h
libtiledbsoma/src/soma/soma_dense_ndarray.cc
libtiledbsoma/src/soma/soma_dense_ndarray.h
libtiledbsoma/src/soma/soma_experiment.cc
libtiledbsoma/src/soma/soma_experiment.h
libtiledbsoma/src/soma/soma_geometry_dataframe.cc
libtiledbsoma/src/soma/soma_group.cc
libtiledbsoma/src/soma/soma_group.h
libtiledbsoma/src/soma/soma_measurement.cc
libtiledbsoma/src/soma/soma_measurement.h
libtiledbsoma/src/soma/soma_point_cloud_dataframe.cc
libtiledbsoma/src/soma/soma_point_cloud_dataframe.h
libtiledbsoma/src/soma/soma_sparse_ndarray.cc
libtiledbsoma/src/soma/soma_sparse_ndarray.h

Replace unnecessary `std::move` and `std::string` with const references and `std::string_view` where possible in all the static create functions.

[c++] Use const references and `std::string_view` in `create` function

---

libtiledbsoma/src/geometry/base.h
libtiledbsoma/src/soma/soma_array.h
libtiledbsoma/src/soma/soma_collection.h
libtiledbsoma/src/soma/soma_group.h

Prevents undefined behavior if we ever attempt to delete a derived class through a pointer to the base class.

[c++] Make destructors of base classes virtual

---

apis/python/tests/test_basic_anndata_io.py

Observed in a cloud-images CI job:
```
/opt/conda/lib/python3.9/site-packages/anndata/__init__.py:55: FutureWarning: `anndata.read` is deprecated, use `anndata.read_h5ad` instead. `ad.read` will be removed in mid 2024.
```

[python] Fix a test deprecation warning

---

.github/workflows/libtiledbsoma-asan-ci.yml

Disable leak detection from ASAN CI job and enable the job for general C++ PRs.

[c++/ci] Disable leak detection and add ASAN CI job to all C++ PRs

---

apis/python/pyproject.toml

Prevent spatial disclaimer from being printed to the pytest output.

[python] Filter spatial disclaimer from pytest

---

apis/python/src/tiledbsoma/__init__.py

Flagged in [#3476 (comment)](https://github.com/single-cell-data/TileDB-SOMA/pull/3476/files#r1890926269).
`# ruff: noqa` midway through the file was actually turning off `ruff` for the whole file.
This replaces that with a couple of more specific ruff rule disables, which only apply to relevant sections.

[python] `tiledbsoma.__init__.py`: restore lint checks

---

apis/python/src/tiledbsoma/_collection.py
apis/python/tests/test_basic_spatialdata_io.py
apis/python/tests/test_experiment_query_spatial.py

* Add `kwargs` to `add_new_collection` so the full API for `Scene.create` can be supported.
* Update test fixtures to use `add_new_collection` for creating a `Scene` inside the `spatial` collection.

[python] Update `add_new_collection` method to support `Scene` collections

---

apis/python/src/tiledbsoma/fastercsx.cc
apis/python/tests/test_libfastercsx.py

Fastercsx python bindings did not verify that argument arrays had native byteorder. This could result in incorrect conversion from COO to CSx in some cases.
Add explicit check and test case. 
[sc-61252]

[python] validate byteorder on fastercsx argument arrays

---

apis/python/setup.py
libtiledbsoma/src/CMakeLists.txt
libtiledbsoma/src/soma/enums.h
libtiledbsoma/src/soma/soma_array.h
libtiledbsoma/src/soma/soma_column.cc
libtiledbsoma/src/soma/soma_column.h
libtiledbsoma/src/soma/soma_dimension.cc
libtiledbsoma/src/soma/soma_dimension.h
libtiledbsoma/src/tiledbsoma/tiledbsoma
libtiledbsoma/src/utils/arrow_adapter.cc
libtiledbsoma/src/utils/arrow_adapter.h
libtiledbsoma/test/CMakeLists.txt
libtiledbsoma/test/common.cc
libtiledbsoma/test/common.h
libtiledbsoma/test/unit_soma_column.cc

Add helpers methods to convert from TileDB dimension and attribute to arrow schema and set current domain.
Issues: [sc-59427](https://app.shortcut.com/tiledb-inc/story/59427/create-an-abstraction-layer-for-soma-columns)
These methods will be used and tested in the following PR chained of this.

[c++] Add helper methods to convert to ArrowSchema

---

libtiledbsoma/src/CMakeLists.txt
libtiledbsoma/src/soma/soma_attribute.cc
libtiledbsoma/src/soma/soma_attribute.h
libtiledbsoma/src/tiledbsoma/tiledbsoma
libtiledbsoma/test/unit_soma_column.cc

This PR introduce the `SOMAAttribute` concrete class to wrap TileDB `Attribute` and `Enumeration` pairs.

[c++] Column abstraction: `SOMAAttribute`, part 2

---

apis/python/src/tiledbsoma/io/spatial/ingest.py

**Issue and/or context:** [sc-61280](https://app.shortcut.com/tiledb-inc/story/61280/add-support-for-visium-v1)
**Changes:**
1. Explicitly set header columns for 
2. Throw error if Visium version number is unknown.
3. Make check for Visium filename version specific (this can be over-ridden by the user).

[python] Add support for Visium v1

---

apis/python/src/tiledbsoma/_dense_nd_array.py
apis/python/src/tiledbsoma/_read_iters.py
apis/python/src/tiledbsoma/_util.py
apis/python/tests/test_sparse_nd_array.py

[[sc-61128](https://app.shortcut.com/tiledb-inc/story/61128/python-1-15-regression-on-table-iterator)]
**Changes:**
- Introduce a high-level `ManagedQuery` class, analogous to the other `SOMAObject` classes, serving as a thin wrapper around the `clib.ManagedQuery` pybind11 object. This class links together the lifetime of `clib.ManagedQuery` to the high-level `SOMAArray` object (not `clib.SOMAArray`)
- Clean up the array setters in `_util.py` to use the `_array` stored in `ManagedQuery`, eliminating the need to pass the array in as a separate argument
- Add a test to confirm the resolution of the previously reported bug and to ensure separate `SOMArray` instances at the same URI iterate using distinct `ManagedQuery` instances
Another …

[python] Link lifetimes of `SOMAArray` and `ManagedQuery`

---

apis/python/src/tiledbsoma/io/_registration/ambient_label_mappings.py
apis/python/src/tiledbsoma/io/ingest.py
apis/python/tests/test_registration_mappings.py

**Issue and/or context:** #3517 [[sc-61390]](https://app.shortcut.com/tiledb-inc/story/61390/handle-non-list-non-tuple-input-in-tiledbsoma-io-registration)
**Changes:** Allow non-list/non-tuple single-item arguments

[python] Handle non-list/non-tuple input in `tiledbsoma.io` registration

---

apis/python/src/tiledbsoma/_indexer.py
apis/python/tests/test_indexer.py

Fixes #3524 - there was both a bad test, and an actual bug in casting Pandas (nullable) integer arrays.
[[sc-61414]](https://app.shortcut.com/tiledb-inc/story/61414/python-test-indexer-py-test-indexer-fails-with-pandas-1-5)

[python] Fix casting bug in `IntIndexer`

---

apis/python/setup.py

Follow-up from https://github.com/single-cell-data/TileDB-SOMA/issues/3444#issuecomment-2575991387

[python] Unpin `scipy`

---

libtiledbsoma/src/soma/soma_object.cc

Found while debugging. This will make debugging fractionally easier.
Repro using TileDB-Py:
```
import tiledb
tiledb.group_create('foo')
tiledbsoma.open('foo')
```

[c++] When a group has no type info, say its name

---

.github/workflows/python-packaging.yml
apis/r/src/Makevars.in
libtiledbsoma/CMakeLists.txt
libtiledbsoma/src/CMakeLists.txt
libtiledbsoma/src/reindexer/reindexer.h
libtiledbsoma/src/soma/soma_array.cc

For the C++20 migration to work we need to increase the minimum macOS deployment target to 13.3 to have support for floating-point formatter. 
#3154
[[sc-57301]](https://app.shortcut.com/tiledb-inc/story/57301/use-c-20)

[c++] Update minimum macOS deployment target

---

apis/python/src/tiledbsoma/io/shaping.py

As tracked on #2407 / [[sc-51048]](https://app.shortcut.com/tiledb-inc/story/51048) and documented at
https://cloud.tiledb.com/academy/structure/life-sciences/single-cell/tutorials/shapes/
we have a new shape feature as of TileDB-SOMA 1.15. This is a core-database-managed construct which keeps track of the 'bounding box' of a sparse array, regardless of how many cells have (or have not) been written to the array.
All TileDB-SOMA experiments created at 1.15 and above will have this new shape on all component dataframes/arrays.
For TileDB-SOMA experiments created by TileDB-SOMA software versions < 1.15, we offer `tiledbsoma.io.upgrade_shape` as documented also here
https://cloud.tiledb.com/academy/structure/life-sciences/single-cell/tutorials/shapes/
This leverages the old `used_shape` …

[python] Account for missing end-rows in shape-upgrader

---

libtiledbsoma/src/utils/fastercsx.h

[[sc-61341]](https://app.shortcut.com/tiledb-inc/story/61341/indexerror-coordinate-out-of-range)
[[sc-61579]](https://app.shortcut.com/tiledb-inc/story/61579/print-actual-coordinate-values-for-out-of-bounds-errors)

[c++] Show which coordinate is out of range in `fastercsx` error messages

---

apis/python/src/tiledbsoma/soma_vfs.cc

[[sc-61381]](https://app.shortcut.com/tiledb-inc/story/61381/python-from-h5ad-fails-with-filenotfounderror-when-using-s3-uris-regression-in-1-15)
Although `h5py` does [support](https://github.com/h5py/h5py/blob/master/h5py/_hl/files.py#L503-L507) ingesting S3 files directly, as already [noted](https://github.com/single-cell-data/TileDB-SOMA/blob/main/apis/python/src/tiledbsoma/io/_util.py#L63-L65) in our documentation, `anndata` uses the [default driver](https://github.com/h5py/h5py/blob/master/h5py/_hl/files.py#L499) which means it expects local files with `os.PathLike URIs`. This is what motivates us to [implement](https://github.com/single-cell-data/TileDB-SOMA/blob/main/apis/python/src/tiledbsoma/io/_util.py#L66) the `_FSPathWrapper` so that `anndata` can …

[python] Implement `read`, `seek`, and `tell` for `SOMAVFSFilebuf`

---

apis/python/tests/test_sparse_nd_array.py
libtiledbsoma/src/soma/managed_query.cc
libtiledbsoma/src/soma/managed_query.h
libtiledbsoma/src/soma/soma_array.h

But reported via chanzuckerberg/cellxgene-census#1327 - root cause was incorrect destructor ordering in the new ManagedQuery class.
The tiledb::Array class _requires_ a tiledb::Context to destruct, but only holds a `std::reference_wrapper<Context>`.  It is holder's responsibility to ensure that the Array's context is alive when the array is destructed.
ManagedQuery just had the context and array shared pointers in the wrong order, causing the context to destruct first in some cases.
[sc-61614]
**Changes:**
Change declaration order of members, thereby correctly ordering the dtor calls.

[C++] Fix `ManagedQuery` segv: ctor/dtor order fix

---

apis/python/src/tiledbsoma/_query.py
apis/python/src/tiledbsoma/io/spatial/outgest.py
apis/python/tests/test_experiment_query_spatial.py

Issues: [sc-61570](https://app.shortcut.com/tiledb-inc/story/61570/add-region-key-instance-key-columns-and-region-metadata-when-exporting-to-spatialdata)
SpatialData requires additional data the links table annotations to the regions they annotate. This adds columns and metadata to the exported AnnData table with the missing data.

[python] Add region columns and metadata to SpatialData

---

apis/python/src/tiledbsoma/_point_cloud_dataframe.py
apis/python/src/tiledbsoma/_scene.py
apis/python/tests/test_multiscale_image.py
apis/python/tests/test_point_cloud_dataframe.py
apis/python/tests/test_scene.py

**Issue and/or context:** [sc-61913](https://app.shortcut.com/tiledb-inc/story/61913/ensure-all-spatial-elements-include-spatial-version-number)
Adds the spatial encoding version to `Scene` and `PointCloudDataFrame` objects.

[python] Add the spatial-encoding version to `Scene` and `PointCloudDataFrame` objects

---

apis/python/src/tiledbsoma/_tdb_handles.py
apis/python/src/tiledbsoma/common.cc
apis/python/src/tiledbsoma/common.h
apis/python/tests/test_metadata.py

A follow-up PR to #3548 that adds support for Unicode metadata. 
UTF-8 support is not enough to store 1D numpy string arrays because Unicode arrays are by default UTF-32 encoded and can contain NULL bytes. 
Additionally improved robustness of metadata writing by attempting to write all modifications and collecting errors throughout the process and raising an exception cumulative at the end, rather than throwing midway. 
[sc-61687](https://app.shortcut.com/tiledb-inc/story/61687/python-add-unicode-metadata-support)

[python] Add Unicode metadata support 

---

apis/python/src/tiledbsoma/soma_vfs.cc

Follow up to https://github.com/single-cell-data/TileDB-SOMA/pull/3543
**Changes:**
Release GIL for long-lived I/O methods `open`, `read`, and `seek`.

[python] Release GIL in VFS bindings

---

apis/python/src/tiledbsoma/soma_vfs.cc
apis/python/tests/test_basic_anndata_io.py

[[sc-61909](https://app.shortcut.com/tiledb-inc/story/61909/misleading-error-message-in-soma-ingestor-when-input-file-is-not-found)]
**Changes:**
Fix misleading error by throwing an explicit error in `SOMAVFSFilebuf.open` if the file does not exist.

[python] Throw error in `SOMAVFSFilebuf.open` on file-not-found

---

apis/python/src/tiledbsoma/soma_vfs.cc

**Issue and/or context:** When backporting #3569 I failed to check for C++ 17 isms. See also #3154 which is still open.
**Changes:**

Fix #3569 backport to `release-1.15`

---

apis/python/tests/test_update_dataframes.py
libtiledbsoma/src/soma/soma_dataframe.cc

Users adds an enumeration column, then drops it, then re-adds it.
Error message:
```
RuntimeError: [TileDB::REST] Error: Error in libcurl POST operation: libcurl error message 'CURLE_OK';
HTTP code 500; server response data '{"code":1006,"message":"error evolving schema for array try 
again","request_id":"8e33095a-4ea2-4c89-9335-420238c29f9f"}'.
```
or:
```
error evolving schema for array [...] ArraySchema: Error adding enumeration.
Enumeration with name '[...]' already exists in this ArraySchema
```
```
import tiledbsoma.io
import anndata as ad
import os, shutil
soma_uri = './repro-460'
h5ad_uri = '/var/s/a/pbmc3k_processed.h5ad'
if os.path.exists(soma_uri):
shutil.rmtree(soma_uri)
tiledbsoma.io.from_h5ad(soma_uri, h5ad_uri, measurement_name = …
```

[c++] Handle add/drop/re-add of enumerated types

---

apis/python/src/tiledbsoma/_query.py

Rather than deconstructing and reconstruction annotation names (`obsm`, `varp`, etc.) create a single function `_get_annotation_layer` that does not use the `AxisName` enum.

[python] Merge `_axisp_get_array` and `_axism_get_array` into a single function

---

doc/requirements_doc.txt
doc/source/conf.py

**Issue and/or context:** #3561
**Changes:** Found by googling. Tested in sandbox using `doc/sandbox*.sh` as noted there.

[python] Fix search in `readthedocs`

---

apis/python/src/tiledbsoma/_query.py
apis/python/tests/test_experiment_query.py

The `ExperimentAxisQuery` used the `AxisName` enumeration to access attributes with either `obs` or `var` in the name. This PR directly calls the appropriate functions, primarily by pushing up the calls to one function higher (e.g. pass in `self.indexer.by_obs`/`self.indexer.by_var` instead of `AxisName.OBS`/`AxisName.VAR`).
This change allowed `ExperimentAxisQuery._convert_to_ndarray` and `ExperimentAxisQuery._axism_inner_ndarray` to be merged into a single non-member function, and `ExperimentAxisQuery._axisp_inner_sparray` to be replaced with a direct call to `_read_as_csr`.

[python] Remove `AxisName.getattr_from` from `ExperimentAxisQuery`

---

doc/requirements_doc.txt

**Issue and/or context:** #3573 was fine in sandbox test as noted there. However, `latest` build at `readthedocs` failed at https://app.readthedocs.org/projects/tiledbsoma/builds/26876140 with
```
ERROR: Cannot install -r doc/requirements_doc.txt (line 1), -r doc/requirements_doc.txt (line 12), -r doc/requirements_doc.txt (line 13), -r doc/requirements_doc.txt (line 6) and sphinx==8.1.3 because these package versions have conflicting dependencies.
The conflict is caused by:
The user requested sphinx==8.1.3
breathe 4.35.0 depends on Sphinx!=5.0.0 and >=4.0
nbsphinx 0.9.3 depends on sphinx>=1.8
sphinxcontrib-jquery 4.1 depends on Sphinx>=1.8
sphinx-rtd-theme 2.0.0 depends on sphinx<8 and >=5
```
**Changes:** Go back to 7.3.7.

[python] More `readthedocs` search fix

---

apis/python/src/tiledbsoma/options/_soma_tiledb_context.py

**Issue and/or context:** Found while working on #3581 / #3582.
In a debug script, due to a copy/paste error, I had
```
context = tiledbsoma.SOMATileDBContext(tiledb_config={
"key1": "value1",
"key2": "value2",
}),
```
Note the trailing comma, which I did not see. (In the copy-from text, this had been in an argument list where comma is needed. In the paste-to text, I was assigning it to a variable, where comma is not needed.)
Then, running a repro, I got
```
File "/Users/kerl/git/single-cell-data/TileDB-SOMA/apis/python/src/tiledbsoma/options/_soma_tiledb_context.py", line 377, in _validate_soma_tiledb_context
raise TypeError(f"context is not a SOMATileDBContext")
TypeError: context is not a SOMATileDBContext
```
This baffled me for a while since I was clearly setting `context` to be a …

[python] On is-not-context error, show type

---

apis/python/src/tiledbsoma/_query.py

**Issue and/or context:** [sc-61662](https://app.shortcut.com/tiledb-inc/story/61662/convert-the-spatialdata-region-key-column-to-a-categorical)
**Changes:**
SpatialData expects the "region_key" column in the `obs` dataframe to be a categorical. This makes that change.

[python] Make `region_key` a categorical when exporting to SpatialData

---

apis/python/notebooks/tutorial_spatial.ipynb
apis/python/src/tiledbsoma/io/spatial/ingest.py

**Issue and/or context:** [sc-61587](https://app.shortcut.com/tiledb-inc/story/61587/enable-obs-presence-matrix-by-default-in-visium-ingestor)
**Changes:** 
Change the `from_visium` ingestor to create the `obs` presence matrix by default. A presence matrix is required for exporting to SpatialData from a `ExperimentAxisQuery`.

[python] Change `from_visium` to create `obs` presence matrix by default

---

apis/python/src/tiledbsoma/_factory.py

**Issue and/or context:** [sc-61991](https://app.shortcut.com/tiledb-inc/story/61991/feature-request-prescriptive-error-message-when-opening-too-new-a-file)
**Changes:**
Add in a prescriptive fix for warning about TileDB-SOMA encoding version.

[python] Update warning on unsupported version

---

.github/workflows/r-ci.yml
apis/r/DESCRIPTION

Configure R on macOS CI to use package binaries instead of sources. Also adjust the `Additional_repositories` field of `DESCRIPTION` to fetch package binaries for data packages
[SC-62227](https://app.shortcut.com/tiledb-inc/story/62227) 
resolves #3590

[r] [CI] Use binaries for packages on macOS

---

apis/python/src/tiledbsoma/_point_cloud_dataframe.py
apis/python/src/tiledbsoma/_scene.py
apis/python/tests/test_multiscale_image.py
apis/python/tests/test_point_cloud_dataframe.py
apis/python/tests/test_scene.py

Backport #3559 to the `release-1.15` branch after robofail at https://github.com/single-cell-data/TileDB-SOMA/pull/3559#issuecomment-2605738677

[Backport release-1.15][python] Add the spatial-encoding version to `Scene` and `PointCloudDataFrame` objects

---

apis/python/src/tiledbsoma/_scene.py
apis/python/src/tiledbsoma/soma_collection.cc
apis/python/tests/test_scene.py
libtiledbsoma/src/CMakeLists.txt
libtiledbsoma/src/soma/soma_coordinates.cc
libtiledbsoma/src/soma/soma_coordinates.h
libtiledbsoma/src/soma/soma_scene.cc
libtiledbsoma/src/soma/soma_scene.h
libtiledbsoma/src/tiledbsoma/tiledbsoma
libtiledbsoma/src/utils/common.h
libtiledbsoma/test/CMakeLists.txt
libtiledbsoma/test/unit_soma_coordinates.cc
libtiledbsoma/test/unit_soma_scene.cc

Backport #3580 to the `release-1.15` branch after robofail at https://github.com/single-cell-data/TileDB-SOMA/pull/3580#issuecomment-2605657608

[Backport release 1.15][python/c++] Add C++ `SOMACoordinateSpace` and use it to push `Scene` metadata down to C++

---

doc/source/python-api.rst
doc/source/python-tiledbsoma-io-spatial.rst

**Issue and/or context:** I didn't adequately test #3595. The `readthedocs` build https://app.readthedocs.org/projects/tiledbsoma/builds/26926597/ failed.
**Changes:**
In the repo base directory, on this PR's branch, I ran
```
./doc/sandbox-gen.sh
./doc/sandbox-open.sh
```
and then looked at the changes in the browser window that opened up.

[python] Fix rendering of spatial docs

---

doc/requirements_doc.txt

**Issue and/or context:** #3606 was nice, but, readthedocs failed at https://app.readthedocs.org/projects/tiledbsoma/builds/26927429/ with
```
/home/docs/checkouts/readthedocs.org/user_builds/tiledbsoma/checkouts/latest/apis/python/src/tiledbsoma/io/spatial/outgest.py:16: UserWarning: Experimental spatial outgestor requires the spatialdata package.
warnings.warn("Experimental spatial outgestor requires the spatialdata package.")
WARNING: Failed to import tiledbsoma.io.spatial.
...
* ModuleNotFoundError: No module named 'spatialdata'
* AttributeError: module 'tiledbsoma.io' has no attribute 'spatial'
...
```
**Changes:**
Add in the `spatialdata` dependency to `doc/requirements_doc.txt`

[python] Iterate on spatial + readthedocs

---

libtiledbsoma/src/soma/soma_dataframe.cc
libtiledbsoma/src/utils/fastercsx.h

**Issue and/or context:** Found in Docker builds for cloud deploys, using 1.15.4. Compling fine on our CI though. See #3154.
**Changes:**

[c++] Fix some build errors for Docker

---

apis/r/tests/testthat/test-04-TileDBArray.R
libtiledbsoma/src/soma/soma_array.cc
libtiledbsoma/src/soma/soma_array.h
libtiledbsoma/src/soma/soma_dataframe.cc
libtiledbsoma/src/soma/soma_dense_ndarray.cc
libtiledbsoma/src/soma/soma_point_cloud_dataframe.cc
libtiledbsoma/src/soma/soma_sparse_ndarray.cc
libtiledbsoma/test/unit_soma_array.cc
libtiledbsoma/test/unit_soma_dataframe.cc
libtiledbsoma/test/unit_soma_dense_ndarray.cc
libtiledbsoma/test/unit_soma_sparse_ndarray.cc

Remove the requirement for additional metadata to reconstruct `SOMAColumn` list from all `SOMAArray` derived classes except `GeometryDataframe`. Also removed automatic metadata reconstruction since a `GeometryDataframe` should always have associated metadata.
**Changes:**

[c++] Make `SOMAColumn` metadata required only for `GeometryDataframe`

---

apis/python/src/tiledbsoma/_multiscale_image.py
apis/python/src/tiledbsoma/soma_collection.cc
libtiledbsoma/src/soma/soma_multiscale_image.cc
libtiledbsoma/src/soma/soma_multiscale_image.h
libtiledbsoma/test/unit_soma_multiscale_image.cc

**Issue and/or context:** [sc-62102](https://app.shortcut.com/tiledb-inc/story/62102/push-down-spatial-metadata-in-the-multiscaleimage-class-from-python-to-c)
**Changes:**
Write the `MultiscaleImage` coordinate-space metadata and spatial-encoding metadata in the C++ layer instead of in Python. This leaves the `MultiscaleImageMetadata` properties to be addressed in a future PR.

[c++] Push-down spatial metadata in the `MultiscaleImage` class from Python to C++

---

apis/python/src/tiledbsoma/_dense_nd_array.py
apis/python/src/tiledbsoma/_util.py
apis/python/tests/test_dense_nd_array.py

[[sc-61920](https://app.shortcut.com/tiledb-inc/story/61920/python-densendarray-read-with-result-order-auto-returns-non-deterministic-result-order-and-default-behavior-is-undefined)]
**Changes:**
- Deprecate `auto` result order option for `DenseNDArray` reads
- By default, use row order
- Add test

[python] Deprecate `result_order="auto"` for `DenseNDArray` reads

---

apis/r/tests/testthat/test-04-TileDBGroup.R
apis/r/tests/testthat/test-06-SOMACollection.R
apis/r/tests/testthat/test-06-SOMADenseNDArray.R
apis/r/tests/testthat/test-06-SOMASparseNDArray.R
apis/r/tests/testthat/test-11-example-datasets.R

Replace calls to `tiledb::tiledb_object_type()` with `get_tiledb_object_type()`
[SC-62778](https://app.shortcut.com/tiledb-inc/story/62778)
Note: this PR is not going into `main`, but into a separate branch to accumulate all of these little PRs before filing the larger one to remove tiledb-r

[r] Remove calls to `tiledb::tiledb_object_type()`

---

apis/r/R/utils-tiledb.R
apis/r/R/zzz.R
apis/r/tests/testthat/test-12-SOMAExperiment-query-base.R

Replace calls to `tiledb::tiledb_version()` with new helper function `get_tiledb_version()`; `get_tiledb_version()` wraps `tiledb_embedded_version()`, but adds a parameter `compact` to replicate the `compact = TRUE` mode of `tiledb::tiledb_version()`
[SC-62779](https://app.shortcut.com/tiledb-inc/story/62779)
Note: this PR is not going into `main`, but into a separate branch to accumulate all of these little PRs before filing the larger one to remove tiledb-r

[r] Remove calls to `tiledb::tiledb_version()`

---

doc/source/python-tiledbsoma-multiscaleimage.rst

**Issue and/or context:** As found by @ivirshup 
**Changes:**
We found on #3284 that manual curation of methods is required in order to obtain correct rendering.

[python] Add missing `MultiscaleImage` methods to docs

---

apis/python/src/tiledbsoma/common.cc

**Issue and/or context:** [sc-62798](https://app.shortcut.com/tiledb-inc/story/62798/metadata-reading-back-as-first-character-for-some-uris-as-of-tiledbsoma-1-15-4)
Bug introduced as of [TileDB-SOMA 1.15.4](https://github.com/single-cell-data/TileDB-SOMA/releases/tag/1.15.4) via PR #3607 which was the backport to the `release-1.15` branch of #3558.
**Changes:**
Metadata were raeding back incorrectly in the cases when their values' `tdb_type` was `TILEDB_STRING_ASCII` (11) rather than `TILEDB_STRING_UTF8` (12).
Note, however, that I ran the following test today:
* Write arrays using TileDB-SOMA 1.14.5, 1.15.0, 1.15.1, 1.15.2, 1.15.3, 1.15.4, and 1.15.5, pip-install each version
* Outer-loop over those same versions, pip-installing each one
* Inner-loop over the arrays from above
* Try …

[python] Fix readback of some older-style metadata

---

apis/python/tests/ht/README.md
apis/python/tests/ht/_array_state_machine.py
apis/python/tests/ht/_ht_test_config.py
apis/python/tests/ht/_ht_util.py
apis/python/tests/ht/_ledger.py
apis/python/tests/ht/conftest.py
apis/python/tests/ht/test_ht_dataframe.py
apis/python/tests/ht/test_ht_densendarray.py
apis/python/tests/ht/test_ht_sparsendarray.py

**Issue and/or context:** stacked on #3560
I chased a few yellow/red squigglies in my editor, and also ran `mypy` on `apis/python/tests/ht` and skimmed the issues it flagged (just as an audit; `mypy` is normally disabled for `tests/` because it generates too many FPs).
**Changes:**
Added/Tweaked some type annotations, removed a few unused functions, etc.

#3560 review

---

apis/python/tests/test_dataframe.py
apis/python/tests/test_sparse_nd_array.py
libtiledbsoma/src/soma/column_buffer.cc

**Issue and/or context:** Resolves #3667 as described on #3667; see also #3611.
**Changes:**

[python] Resolve issue with #3611 and `pyarrow<17`

---

apis/python/tests/test_dataframe.py
libtiledbsoma/src/soma/managed_query.cc
libtiledbsoma/src/soma/soma_array.cc

[[sc-62887](https://app.shortcut.com/tiledb-inc/story/62887/python-c-enum-regression-in-pr-3647)]
**Changes:**
When evolving the schema, we need to re-open the array so that on subsequent writes it sees the latest version. Previously this was done in `SOMAArray::write`. Now that we are replacing this with `ManagedQuery::write`, the reopening step needs to be moved into this method. There should be no performance degradation as are simply moving the same step from `SOMAArray::write` to `ManagedQuery::write`.
My original thought was to combine chunks in the Python side to avoid the repeated reopening steps for multiple chunks in the first place, but it sounds like the overhead of creating the copy is worse than reopening.

[python] Fix enum regression in PR #3647

---

apis/python/tests/test_dataframe.py
apis/python/tests/test_sparse_nd_array.py
libtiledbsoma/src/soma/column_buffer.cc

Manual bcakport of #3669.
Resolves #3667 as described on #3667; see also #3611.

[Backport release-1.15] [python] Resolve issue with #3611 and `pyarrow<17`

---

libtiledbsoma/CMakeLists.txt

Add GCC minimum version check to CMake.
Context: #3154 / [[sc-57301]](https://app.shortcut.com/tiledb-inc/story/57301/use-c-20). See also https://github.com/single-cell-data/TileDB-SOMA/pull/3673#pullrequestreview-2595929065.

[c++] Add CMake check for GCC minimum version 13

---

apis/python/src/tiledbsoma/managed_query.cc
apis/r/DESCRIPTION
apis/r/NEWS.md
apis/r/R/BlockwiseIter.R
apis/r/R/RcppExports.R
apis/r/R/ReadIter.R
apis/r/R/SOMADataFrame.R
apis/r/R/SOMANDArrayBase.R
apis/r/R/SOMASparseNDArray.R
apis/r/R/utils-readerTransformers.R
apis/r/R/utils.R
apis/r/src/Makevars.in
apis/r/src/RcppExports.cpp
apis/r/src/arrow.cpp
apis/r/src/rinterface.cpp
apis/r/src/riterator.cpp
apis/r/src/rutilities.cpp
apis/r/src/rutilities.h
apis/r/tests/testthat/test-10-SOMAArrayReader-Iterated.R
libtiledbsoma/src/soma/managed_query.cc
libtiledbsoma/src/soma/managed_query.h
libtiledbsoma/test/unit_soma_column.cc

Part of work for https://github.com/single-cell-data/TileDB-SOMA/issues/2054
**Changes:**
- Change C++ `ManagedQuery` constructor to take in `SOMAArray` instead of `std::unique_ptr<SOMAArray>`. Pybind11 by default holds a `unique_ptr` (`shared_ptr` can be used, but there are known issues which prevents us from using it) whereas Rcpp holds a `shared_ptr` - to easily support both, pass by value rather than smart pointer
- Refactor tiledbsoma-r to use `ManagedQuery` for read and write queries
- Rename `sr_{setup,next,etc}` to `mq_{setup,next,etc}` where `mq_setup` now returns a `ManagedQuery` (rather than `SOMAArray`) that can be iterated through with `sr_next` 
- Update `apply_dim_{points,ranges}` utility functions to take in a `ManagedQuery`
**Notes for …

[r] Replace `SOMAArray` read and write calls with `ManagedQuery`

---

apis/python/src/tiledbsoma/_arrow_types.py
apis/python/tests/test_basic_anndata_io.py

**Issue and/or context:** See #3685.
**Changes:** Jump through the Pandas and Arrow hoops needed to get an entirely null-filled enum-of-strings column.

[python] Correctly create null-filled enum-of-string columns in `tiledbsoma.io`

---

apis/python/tests/test_io.py

Running this to imitate CI:
```
alias ttci='uadr; PYTHONPATH=$(pwd)/apis/python/src python -m pytest --cov=apis/python/src --cov-report=xml apis/python/tests -v --durations=20 --maxfail=50'
```
I noticed at the end:
```
================================================= slowest 20 durations =================================================
1027.84s call     tests/test_io.py::test_write_arrow_table[100-10000]
143.45s call     tests/test_basic_anndata_io.py::test_decat_append
101.24s call     tests/ht/test_ht_sparsendarray.py::TestSOMASparseNDArray::runTest
41.43s call     tests/ht/test_ht_dataframe.py::TestSOMADataFrame::runTest
14.52s call     tests/ht/test_ht_densendarray.py::TestSOMADenseNDArray::runTest
10.42s call …
```

[ci] Speed up a test case

---

apis/python/src/tiledbsoma/io/ingest.py
apis/python/src/tiledbsoma/pytiledbsoma.cc
apis/python/src/tiledbsoma/soma_dataframe.cc
apis/python/tests/test_update_dataframes.py
apis/r/src/rinterface.cpp
libtiledbsoma/src/soma/managed_query.cc
libtiledbsoma/src/soma/soma_array.cc
libtiledbsoma/src/soma/soma_array.h
libtiledbsoma/src/soma/soma_attribute.cc
libtiledbsoma/src/soma/soma_column.cc
libtiledbsoma/src/soma/soma_dataframe.cc
libtiledbsoma/src/soma/soma_dataframe.h
libtiledbsoma/src/utils/arrow_adapter.cc
libtiledbsoma/src/utils/util.cc
libtiledbsoma/src/utils/util.h

[[sc-63086](https://app.shortcut.com/tiledb-inc/story/63086/multiple-tiledb-soma-issues-with-schema-evolution-and-categoricals)]
**Changes:**
Previously, we set enumeration labels to be the same as attribute names. However this causes an issue when dropping a column but then readding a column with the same name but different enumeration dtypes. To fix this case, create a new util function `get_enmr_label` to create enumeration labels as `[the name of the attribute][the dictionary value's format type]`.

[c++] Modify enum labels to `{name}_{dtype}`

---

apis/python/src/tiledbsoma/_dataframe.py
apis/python/tests/test_dataframe_index_columns.py

**Issue and/or context:** [[sc-62231]](https://app.shortcut.com/tiledb-inc/story/62231)
**Changes:**
Make it the same for `binary` as for `string`.
Repro script (in addition to unit-test cases on this PR):
```
import pyarrow as pa
import numpy as np
import sys, os, shutil
uri_a = "62231a"
uri_b = "62231b"
for uri in [uri_a, uri_b]:
if os.path.exists(uri):
shutil.rmtree(uri)
schema_a = pa.schema([
pa.field('soma_joinid',pa.int64(),nullable=False),
pa.field('00', pa.large_string(), nullable=False),
pa.field('B', pa.int8()),
])
with tiledbsoma.DataFrame.create(
uri_a,
schema=schema_a,
domain=((0, np.iinfo(np.int64).max-2050), ('','')),
index_column_names=['soma_joinid','00'],
) as A:
print("A domain")
print(A.domain)
schema_b = …
```

[python] Allow `("","")` for `binary` as well as `string` dataframe domain

---

apis/python/src/tiledbsoma/_dense_nd_array.py
apis/python/tests/test_dense_nd_array.py
libtiledbsoma/src/soma/managed_query.cc

https://github.com/single-cell-data/TileDB-SOMA/issues/3271
**Changes:**
Previously, dense arrays returned only the non-empty domain by default. With this update, dense arrays now return the full shape of the array.

[c++,python] Correct slicing for `DenseNDArray`

---

apis/python/tests/test_dataframe.py
apis/python/tests/test_dense_nd_array.py
apis/python/tests/test_sparse_nd_array.py
apis/r/tests/testthat/test-06-SOMADataFrame.R
apis/r/tests/testthat/test-06-SOMADenseNDArray.R
apis/r/tests/testthat/test-06-SOMASparseNDArray.R
libtiledbsoma/src/soma/managed_query.cc
libtiledbsoma/test/unit_soma_dataframe.cc
libtiledbsoma/test/unit_soma_dense_ndarray.cc
libtiledbsoma/test/unit_soma_sparse_ndarray.cc

Found during dev on a forthcoming PR. I believe we lost this check in decoupling `ManagedQuery` from `SOMArray`. And we missed the fact that we lost the check due to missing unit-test coverage. This PR fixes both.
#3720 [[sc-63626]](https://app.shortcut.com/tiledb-inc/story/63626/tiledb-soma-1-16-0)

[c++] Check arrays are open for write at write time

---

apis/python/tests/conftest.py
apis/python/tests/test_basic_anndata_io.py
apis/python/tests/test_platform_config.py
apis/python/tests/test_registration_mappings.py
apis/python/tests/test_update_dataframes.py
apis/python/tests/test_update_matrix.py

**Issue and/or context:** In support of [[sc-61088]](https://app.shortcut.com/tiledb-inc/story/61088).
As detailed there:
* Using the `pytest` fixture `tmp_path`:
* Are removed only three test runs later, not at process exit -- this is a feature
* Most of our test cases use these
* Total usage is tens of thousands of files and directories not reaped until three runs later
* this is fine
* `tempfile.TemporaryDirectory` files:
* are deleted at process exit
* whether or not the test failed
* whether or not a context-manager syntax was used
* this is fine
* `tempfile.mkdtemp` files:
* are not deleted at process exit
* We should be removing these
**Changes:**
For this PR, simply apply the prefixing feature which makes analysis easier. This is not the final PR on this matter.
**Notes for …

[python] Name temp paths for clarity

---

.github/workflows/r-ci.yml
.github/workflows/r-python-interop-testing.yml
.gitignore

Use r-lib/actions instead of `tools/r-ci.sh` for R CI; also makes use of RSPM/P3M + pak for binaries and system requirements
[SC-63716](https://app.shortcut.com/tiledb-inc/story/63716)

[r] [ci] Migrate R CI to r-lib/actions

---

apis/python/src/tiledbsoma/io/outgest.py
apis/python/tests/test_soma_experiment_versions.py

**Issue and/or context:** [[sc-63713]](https://app.shortcut.com/tiledb-inc/story/63713/defect-in-used-shape-removal); #3729; blocks 1.16.0 #3720
**Changes:** 
#3723 was defective. After `used_shape` was removed -- as planned, with deprecation in 1.15. and removal in 1.16 -- an old, pre-existing defect in the case beneath it was revealed.
**Notes for Reviewer:** Stacked atop #3730.

[python] Fix `obsm` outgest shape for non-upgraded pre-1.15 arrays

---

apis/python/tests/test_from_visium.py
scripts/prepare-test-data.sh

**Issue and/or context:** [sc-56889](https://app.shortcut.com/tiledb-inc/story/56889/test-visium-ingestor-on-a-wider-range-of-input-datasets) [sc-63606](https://app.shortcut.com/tiledb-inc/story/63606/add-additional-checks-in-visium-test) 
**Changes:**
* Download additional data for the `from_visium` tests.
* Add a complete test of ingesting a Visium v1 dataset.
* Update Visium v2 test to include checking point/spot data, coordinate space data, and coordinate transform data.

[python] Make the testing of `from_visium` more thorough

---

apis/python/src/tiledbsoma/_experiment.py
apis/python/src/tiledbsoma/_query.py
apis/python/src/tiledbsoma/io/outgest.py
apis/python/src/tiledbsoma/io/spatial/ingest.py
apis/python/tests/_util.py
apis/python/tests/test_basic_anndata_io.py
apis/python/tests/test_experiment_query.py
apis/python/tests/test_fastercsx.py

- Use {`dict`,`tuple`,`list`,`type`} types (available since Python 3.9) in some places (instead of `typing.{Dict,Tuple,List,Type}` counterparts)
- Reference some types directly, instead of quoting them as strings
- Misc other typo fixes / lints

[python] Type/comment tweaks

---

.github/workflows/python-ci-single.yml

xref: https://github.com/single-cell-data/TileDB-SOMA/pull/3712, https://github.com/TileDB-Inc/centralized-tiledb-nightlies/pull/40, https://github.com/TileDB-Inc/centralized-tiledb-nightlies/pull/39#discussion_r1973716522
**Changes:**
Remove redundant step to prepare test data

[python/ci] Remove redundant step to prepare test data

---

apis/python/src/tiledbsoma/options/__init__.py
apis/python/src/tiledbsoma/options/_soma_tiledb_context.py

We use `dict[str, str | float]` in a few places, to mean "TileDB config"; this factors+names that.
#3740 was the impetus for resurrecting this; I'm referencing this type in other files there.

[python] Config type aliases

---

apis/python/tests/test_aaa_setup.py
scripts/prepare-test-data.sh
test/README.md

Found today in my sandbox:
```
kerl@arvad[prod][kerl/dots-in][TileDB-SOMA]$ make data
Begin preparing data.
-- Skipping dataset 'data/soco'; directory 'data/soco' already exists.
-- Skipping dataset 'data/example-visium-v2'; directory 'data/example-visium-v2' already exists.
-- Skipping dataset 'data/example-visium-v1'; directory 'data/example-visium-v1' already exists.
-- Preparing dataset 'data/soma-experiment-versions' ...
-- Skipping dataset 'data/soma-experiment-versions'; directory 'data/soma-experiment-versions' already exists.
... finished preparing dataset 'data/soma-experiment-versions'.
```
```
kerl@arvad[prod][kerl/dots-in][TileDB-SOMA]$ python -m pytest apis/python/tests/
================================================================================ …
```

[python] Fix `make data` sandbox issue

---

apis/python/setup.py
apis/python/src/tiledbsoma/_geometry_dataframe.py
apis/python/src/tiledbsoma/pytiledbsoma.cc
apis/python/src/tiledbsoma/transformer.cc
apis/python/tests/test_geometry_dataframe.py
libtiledbsoma/src/CMakeLists.txt
libtiledbsoma/src/soma/soma_coordinates.cc
libtiledbsoma/src/soma/soma_coordinates.h
libtiledbsoma/src/soma/soma_geometry_dataframe.cc
libtiledbsoma/src/soma/soma_geometry_dataframe.h
libtiledbsoma/src/soma/soma_transformers.cc
libtiledbsoma/src/soma/soma_transformers.h
libtiledbsoma/src/tiledbsoma/tiledbsoma
libtiledbsoma/src/utils/arrow_adapter.cc
libtiledbsoma/src/utils/arrow_adapter.h
libtiledbsoma/src/utils/transformer.cc
libtiledbsoma/src/utils/transformer.h

**Changes:**
This PR moves the helper methods transforming from polygon outlines to WKB encoded geometry into a separate class. Adds a basic transformer pipeline and exposes it to the python API and adds helper methods to the python API for ingesting with a transformation. 
The C++ `GeometryDataFrame` cleanup will happen after updating all read and write operations with `ManagedQuery`

[c++/python] `SOMAGeometryDataFrame` basic write

---

apis/python/src/tiledbsoma/io/spatial/__init__.py
apis/python/src/tiledbsoma/io/spatial/ingest.py

* Add placeholder function `register_visium_dataset` that throws a `NotImplementedError`.
* Clean-up parameters to the `from_visium` function. Some of the options that are used in append mode don't apply to `from_visium`.
* Clean-up `from_visium` docstring.

[python] Add `register_visium_dataset` function with `NotImplementedError`

---

apis/python/setup.py
apis/python/src/tiledbsoma/_read_iters.py
apis/python/src/tiledbsoma/_util.py
apis/python/src/tiledbsoma/managed_query.cc
apis/python/src/tiledbsoma/pytiledbsoma.cc
apis/python/src/tiledbsoma/soma_array.cc
apis/python/src/tiledbsoma/soma_column.cc
libtiledbsoma/src/soma/column_buffer.h
libtiledbsoma/src/soma/managed_query.h
libtiledbsoma/src/soma/soma_attribute.cc
libtiledbsoma/src/soma/soma_attribute.h
libtiledbsoma/src/soma/soma_column.h
libtiledbsoma/src/soma/soma_dimension.cc
libtiledbsoma/src/soma/soma_dimension.h
libtiledbsoma/src/soma/soma_geometry_column.cc
libtiledbsoma/src/soma/soma_geometry_column.h
libtiledbsoma/src/soma/soma_geometry_dataframe.cc
libtiledbsoma/src/soma/soma_geometry_dataframe.h
libtiledbsoma/src/tiledbsoma/tiledbsoma
libtiledbsoma/test/unit_soma_column.cc
libtiledbsoma/test/unit_soma_geometry_dataframe.cc

**Issue and/or context:** [sc-52732](https://app.shortcut.com/tiledb-inc/story/52732/polygonal-geometry-queries-for-geometrydataframe)
**Changes:**
`ManagedQuery` ranges are not set directly, but the associated `SOMAColumn` sets the necessary dimension ranges
This PR adds SOMAColumn bindings to python and updates the coordinate setter to use the new `SOMAColumn` setters. To better work with the `ManagedQuery` binding the SOMAColumn method signatures are changed to accept a reference to a `ManagedQuery` object instead of a unique pointer.

[c++/python] Integrate `SOMAColumn` into `ManagedQuery` read

---

apis/python/src/tiledbsoma/_geometry_dataframe.py
apis/python/src/tiledbsoma/_read_iters.py
apis/python/src/tiledbsoma/_spatial_util.py
apis/python/src/tiledbsoma/_util.py
apis/python/src/tiledbsoma/soma_column.cc
apis/python/tests/test_geometry_dataframe.py
libtiledbsoma/src/utils/arrow_adapter.cc

**Issue and/or context:** [sc-52732](https://app.shortcut.com/tiledb-inc/story/52732/polygonal-geometry-queries-for-geometrydataframe)
**Changes:**
Coordinate setter utils are now aware of SpatialDataFrame coordinate space. Also domain is expected to be a mapping between axis names and the axis domain for geometry columns. 
This PR adds spatial reads to `GeometryDataFrame`. The spatial ranges per axis are all grouped under the spatial column's name. When setting the coordinate ranges for each dimension the geometry column is identified by the added `dtype` metadata field on the arrow schema field.

[python] Add spatial read to `GeometryDataFrame`

---

README.md

**Issue and/or context:** TileDB logo in the README wasn't displaying.
**Changes:** Updated image URL to point to core's `main` branch, now that `dev` is no longer used.

[docs] Fix core logo in `README.md`

---

apis/python/src/tiledbsoma/_dense_nd_array.py
apis/python/src/tiledbsoma/io/ingest.py
apis/python/tests/ht/test_ht_densendarray.py
apis/python/tests/test_collection.py
apis/python/tests/test_dense_nd_array.py

[[sc-61815](https://app.shortcut.com/tiledb-inc/story/61815/python-densearray-read-and-write-use-different-definition-of-coordinate-slices)]
**Changes:**
Modify read slicing to be inclusive.

[python] Use same inclusive slicing semantics for `DenseNDArray`

---

apis/python/src/tiledbsoma/io/_util.py

**Issue and/or context:** Backports #3728 manually since backport bot is [having a bad day](https://github.com/single-cell-data/TileDB-SOMA/actions/runs/13701682568).
**Changes:**

[Backport release-1.16] Fix python 3.13 compatibility

---

apis/python/notebooks/tutorial_soma_append_mode.ipynb
apis/python/notebooks/tutorial_soma_shape.ipynb
apis/python/src/tiledbsoma/io/shaping.py

**Issue and/or context:** After extensive, thoughtful, and deliberate team discussion including @ivirshup and @bkmartinjr , we decided not to expose a `.shape` accessor for dataframes.
The thinking we agreed to, collectively and as a team, at that point in time was that having a `.shape`  accessor for DataFrame objects would decrease confusion for some others but add confusion for others.
The status quo is:
* Suppose an experiment has `nobs=1000` and `nvar=2000`
* In AnnData, one would have
* `adata.obs.shape = (1000, m)` where `m` is the number of columns in `obs`
* `adata.var.shape = (2000, n)` where `n` is the number of columns in `var`
* `adata.X.shape` = (1000, 2000)`
* In TileDB-SOMA, we have
* `exp.obs.shape` does not exist (as discussed above)
* `exp.obs.domain = ((0, 999),)`
* …

[python] Show DataFrame `.count` in `show_experiment_shapes`

---

apis/python/src/tiledbsoma/_fastercsx.py
apis/python/tests/ht/test_ht_fastercsx.py
apis/python/tests/test_fastercsx.py

**Issue and/or context:** factored out of #3740
**Changes:**
Add `Format = Literal["csc", "csr"]` alias (used in 3 files here, and more to come in #3740)

[python] Add `_fastercsx.Format` type alias

---

apis/python/src/tiledbsoma/_util.py
apis/python/src/tiledbsoma/io/outgest.py
apis/python/tests/test_basic_anndata_io.py

#3773 
[[sc-63400]](https://app.shortcut.com/tiledb-inc/story/63400/python-tiledbsoma-io-to-anndata-raises-error-when-x-layer-missing-but-not-requested)

[python] Fix `to_anndata` with no `X`

---

apis/r/tests/testthat/helper-test-soma-objects.R

Replace tiledb-r with SOMA for test helper function to create an empty sparse nd-array
[SC-64301](https://app.shortcut.com/tiledb-inc/story/64301)

[r] Replace tiledb-r with SOMA for test helper

---

apis/python/src/tiledbsoma/_tdb_handles.py
apis/python/tests/test_sparse_nd_array.py
libtiledbsoma/src/soma/soma_array.cc

[[sc-61118](https://app.shortcut.com/tiledb-inc/story/61118/python-reopen-loses-metadata-modifications)]
**Changes:**
Previously, the `reopen` method only opened and returned a new `SOMAArray` object without actually performing a flush operation.

[c++,python] Flush the `Array` object in `SOMAArray::reopen`

---

apis/python/src/tiledbsoma/soma_array.cc
apis/python/tests/test_sparse_nd_array.py

[[sc-61123](https://app.shortcut.com/tiledb-inc/story/61123/python-reopening-sparsendarray-removes-shape-attribute)]
The `reopen` method returns a `SOMAArray`. The `shape` attribute exists only on the `NDArray` classes, not for all `SOMArray` classes. Calling `reopen` on a `SparseNDArray` returned a `SOMAArray`, so calling `shape` yielded this error: 
```
AttributeError: 'tiledbsoma.pytiledbsoma.SOMAArray' object has no attribute 'shape'
```
**Changes:**
Refactor the Pybind11 `SOMAArray.reopen` to be a factory method which correctly casts the `SOMAArray` object to the correct child class according to the `soma_object_type` metadata value.
On top of https://github.com/single-cell-data/TileDB-SOMA/pull/3775.

[python] Cast object to child class in pybind11 `SOMAArray.reopen`

---

libtiledbsoma/src/soma/soma_array.cc

**Issue and/or context:** Fixes a scaling issue found on an 800K x 38K experiment. [[sc-64476]](https://app.shortcut.com/tiledb-inc/story/64476/exp-obs-count-yields-error-with-1-16-0#activity-64528)
**Changes:**
PR #3735 had an unintended omission:
* Before: a column-select to reduce memory consumption https://github.com/single-cell-data/TileDB-SOMA/blob/96e08e8ca9e379b42b0df97de4b46235d4facdb5/libtiledbsoma/src/soma/soma_array.cc#L632 
* After: the column-select was omitted https://github.com/single-cell-data/TileDB-SOMA/blob/d8a60e6192116f8e867f82ebaffcc50e4caf75b5/libtiledbsoma/src/soma/soma_array.cc#L512-L517
This PR restores the column-select statement. (Solution thanks to @nguyenv .)

[python] Fix memory usage in `nnz_slow`

---

apis/r/tests/testthat/test-13-write-soma-objects.R

While adding the R tests to the conda feedstock (https://github.com/TileDB-Inc/tiledbsoma-feedstock/pull/294, https://github.com/TileDB-Inc/tiledbsoma-feedstock/pull/295), I discovered a single test that requires {SeuratObject} to be installed but wasn't protected by `skip_if_not_installed()`. The test was added in https://github.com/single-cell-data/TileDB-SOMA/commit/0c9be67f1fad7f2ed0a2f3a065951f61ad3238ac via https://github.com/single-cell-data/TileDB-SOMA/pull/2833.
**Changes:**
I added the missing `skip_if_not_installed()`
I tested this by installing r-tiledbsoma into a conda env and then running the local tests in `apis/r/tests/`
```sh
mamba create --yes -n soma-testthat -c conda-forge -c tiledb \
r-testthat r-tiledbsoma
mamba …
```

[r] Skip {testthat} test if SeuratObject is not installed

---

libtiledbsoma/src/soma/managed_query.cc
libtiledbsoma/src/utils/util.cc
libtiledbsoma/src/utils/util.h

**Issue and/or context:** In the vein of #3783: a line-count-reducing PR split out from #3784.
**Changes:** Consolidate the three try-catch blocks into a single helper. On #3784 there will be a fourth callsite, and I didn't want a fourth try-catch.

[c++] Extract `get_enumeration` helper

---

apis/python/src/tiledbsoma/io/spatial/_util.py
apis/python/tests/test_10x_reader.py

**Issue and/or context:** [sc-64133](https://app.shortcut.com/tiledb-inc/story/64133/create-10x-hdf5-matrix-reader)
Create a reader for ingesting 10x HDF5 matrix without first ingesting into AnnData, for Visium ingestion.

[python] Reader for 10x HDF5 matrix file

---

libtiledbsoma/src/soma/soma_transformers.cc
libtiledbsoma/src/utils/arrow_adapter.cc

**Issue and/or context:** Drive-by improvements found while working on #3784 for #3785 / [[sc-63930]](https://app.shortcut.com/tiledb-inc/story/63930/dataframe-need-api-to-extend-column-enum-values-without-doing-a-write#activity-64471)
**Changes:**
Eliminate these warnings (found with `clang` on MacOS):
```
/Users/kerl/git/single-cell-data/TileDB-SOMA/libtiledbsoma/src/soma/soma_transformers.cc:93:26: warning: moving a temporary object prevents copy elision [-Wpessimizing-move]
93 |         arrays.push_back(std::move(std::make_unique<ArrowArray>(ArrowArray{})));
|                          ^
/Users/kerl/git/single-cell-data/TileDB-SOMA/libtiledbsoma/src/soma/soma_transformers.cc:93:26: note: remove std::move call here
93 | …
```

[c++] Fix some compiler warnings

---

.github/workflows/python-dockers.yml
.github/workflows/python-packaging.yml
.github/workflows/python-remote-storage.yml

When nightly GHAs fail, often our first move is to try re-running, but this can result in duplicate issues being filed, e.g.:
- https://github.com/single-cell-data/TileDB-SOMA/issues/3808
- https://github.com/single-cell-data/TileDB-SOMA/issues/3809
- https://github.com/single-cell-data/TileDB-SOMA/issues/3810
This change skips filing issues except on the 1st "attempt".
It also bumps a few `actions/checkout` versions.

GHAs: don't file issues on re-run failures

---

.github/workflows/python-dockers.yml
.github/workflows/python-packaging.yml
.github/workflows/python-remote-storage.yml

When nightly GHAs fail, often our first move is to try re-running, but this can result in duplicate issues being filed, e.g.:
- https://github.com/single-cell-data/TileDB-SOMA/issues/3808
- https://github.com/single-cell-data/TileDB-SOMA/issues/3809
- https://github.com/single-cell-data/TileDB-SOMA/issues/3810
This only files an issue when the 1st "attempt" fails
**Changes:**
Backport of #3820 from `main` to `release-1.16`

[Backport release-1.16][ci] GHAs: don't file issues on re-run failures (#3820)

---

libtiledbsoma/src/utils/arrow_adapter.cc

**Issue and/or context:** See #3787. I introduced this on #3783.
**Changes:**

[c++] Fix a missed call to `std::format`

---

apis/python/src/tiledbsoma/_dataframe.py
apis/python/src/tiledbsoma/_dense_nd_array.py
apis/python/src/tiledbsoma/_geometry_dataframe.py
apis/python/src/tiledbsoma/_point_cloud_dataframe.py
apis/python/src/tiledbsoma/_soma_object.py
apis/python/src/tiledbsoma/_sparse_nd_array.py
apis/python/src/tiledbsoma/soma_array.cc
apis/python/tests/test_dataframe.py

**Issue and/or context:** Split out from 3815 for #3785 / [[sc-63930]](https://app.shortcut.com/tiledb-inc/story/63930/dataframe-need-api-to-extend-column-enum-values-without-doing-a-write#activity-64471).  See in particular [this comment](https://github.com/single-cell-data/TileDB-SOMA/pull/3815/files#r2013014784).
**Changes:**
* Update the wording of the existing `_check_open_read` as suggested
* Re-raise the core error when doing `get_enumeration_values` on a closed array as `SOMAError`
* Unit-test that
* Find the existing check-open-for-read and check-open-for-write, colocate them within the source file, and change the name of the existing private read-check method to be similar to the existing public write-check method

[c++/python] Improve error-handling for enum-getter and modes

---

apis/python/tests/test_sparse_nd_array.py
libtiledbsoma/src/soma/managed_query.cc
libtiledbsoma/src/soma/managed_query.h

**Issue and/or context:** On commit https://github.com/single-cell-data/TileDB-SOMA/commit/32ba743cfdbca91a4eff64fe4647387941636ae0 of PR #3823 I moved the `<std::string>` specialization of `_cast_column_aux` above the generic implementation. I missed, and thus neglected to do the same, for the `<bool>` specialization. This PR fixes that.
**Changes:** As above. Also, rename a helper method to have a clearer name for TileDB <-> Arrow / bytemap <-> bitmap conversions.
Existing unit-test cases suffices to verify nothing is broken, as I'm simply moving one method higher up in a source file.

[c++] Colocate another pair of template instantiations [trivial]

---

apis/r/tests/testthat/test-06-SOMADataFrame.R
apis/r/tests/testthat/test-06-SOMADenseNDArray.R
apis/r/tests/testthat/test-06-SOMASparseNDArray.R

Replace calls to `tiledb::attrs()` with `$attributes()` accessor
[SC-64999](https://app.shortcut.com/tiledb-inc/story/64999)

[r] Replace tiledb attribute filter checks with `$attributes()`

---

apis/r/R/RcppExports.R
apis/r/src/RcppExports.cpp
apis/r/src/rinterface.cpp
apis/r/src/rutilities.cpp
apis/r/src/rutilities.h
apis/r/tests/testthat/test-06-SOMADataFrame.R
apis/r/tests/testthat/test-06-SOMADenseNDArray.R
apis/r/tests/testthat/test-06-SOMASparseNDArray.R

Replace calls the following tiledb-r schema accessors with new libtiledbsoma functions:
- `tiledb::capacity()` replaced with `c_capacity()`
- `tiledb::tile_order()` replaced with `c_tile_order()`
- `tiledb::cell_order()` replaced with `c_cell_order()`
[SC-64997](https://app.shortcut.com/tiledb-inc/story/64997)

[r] Replace calls to tiledb-r schema checkers with libtiledbsoma

---

libtiledbsoma/src/soma/soma_column.cc
libtiledbsoma/src/soma/soma_column.h

**Issue and/or context:** [conda-forge/tiledbsoma-feedstock/pull/7](https://github.com/conda-forge/tiledbsoma-feedstock/pull/7#issuecomment-2754852179)
**Changes:**
- Remove static deserializer map and replace it with a switch statement
ASAN was reporting an ODR violation exporting the static map from libtiledbsoma shared library

[c++] Remove static deserializer map

---

apis/python/tests/test_dataframe.py
libtiledbsoma/src/soma/soma_array.cc
libtiledbsoma/src/utils/arrow_adapter.h

**Issue and/or context:** For issue #3785 / [[sc-63930]](https://app.shortcut.com/tiledb-inc/story/63930/dataframe-need-api-to-extend-column-enum-values-without-doing-a-write#activity-64471).
**Changes:** @bkmartinjr found during his testing that the unit-test coverage in #3784 was insufficient to surface a defect. This PR includes unit-test cases that reproduce this defect, along with a fix for that defect.

[c++/python] Unit-test and fix `get_enumeration_values` for boolean types

---

apis/python/tests/test_dataframe.py

**Issue and/or context:** I had a `not_an_enum` column defined in the schema as `pa.large_string()`. Then writing it with `pd.Categorical`. That surfaces no error, which is by design as implemented on #3354. However, #3354 isn't being tested here; this was a copy/paste error, not intentional; and it adds needless confusion.
Surrounding context: #3785 / [[sc-63930]](https://app.shortcut.com/tiledb-inc/story/63930/dataframe-need-api-to-extend-column-enum-values-without-doing-a-write#activity-64471).
**Changes:** Write non-enum string data to the non-enum string column.

[python] Fix a venial typo in a unit-test case

---

apis/python/src/tiledbsoma/io/ingest.py

The backport bot failed to act on #3830. This is a manual backport.
This PR is trivial.

[Backport release-1.16][python] Fix a typo in a comment [skip ci]

---

apis/python/tests/test_dataframe.py
libtiledbsoma/src/soma/managed_query.cc
libtiledbsoma/src/soma/managed_query.h

[[sc-62449](https://app.shortcut.com/tiledb-inc/story/62449/python-c-enum-evolution-does-not-correctly-handle-category-value-of-nan)]
`std::find` does not work "as expected" for NaN values, since NaN != NaN (which is the correct behavior for floating-point comparisons, but not what is intended in this context).
**Changes:**
Add `ManagedQuery::_find_enum_match` which uses bitwise comparison. Like `std::find`, the method returns an iterator that points to the match value in the container; if not found, returns an iterator to the end of the container.

[c++] Correctly handle NaN category values

---

apis/python/src/tiledbsoma/io/shaping.py
apis/python/tests/test_shape.py

**Issue and/or context:** [sc-65008](https://app.shortcut.com/tiledb-inc/story/65008/prepare-io-shaping-for-spatial-additions)
**Changes:**
* Update docstrings to reflect which elements inside the experiment are being accessed.
* Refactor `_treewalk` to make adding more elements easier.

[python] Prepare `io.shaping` for spatial additions

---

apis/python/src/tiledbsoma/_dataframe.py
apis/python/src/tiledbsoma/_dense_nd_array.py
apis/python/src/tiledbsoma/_geometry_dataframe.py
apis/python/src/tiledbsoma/_point_cloud_dataframe.py
apis/python/src/tiledbsoma/_soma_array.py
apis/python/src/tiledbsoma/_sparse_nd_array.py
apis/python/src/tiledbsoma/managed_query.cc
apis/python/src/tiledbsoma/pytiledbsoma.cc
apis/python/tests/test_dataframe.py
libtiledbsoma/src/soma/managed_query.cc
libtiledbsoma/src/soma/managed_query.h
libtiledbsoma/test/unit_soma_array.cc

https://github.com/single-cell-data/TileDB-SOMA/issues/2054
Previously, this chunked table would have resulted in 3 fragments or commits. After separating the `submit` and `finalize` methods, this only results in a single fragment. Note that for unordered writes, this would still result in 3 fragments.
```
with soma.open(uri, mode="w") as A:
A.write(
pa.concat_tables(
[
pa.Table.from_pandas(df_0, preserve_index=False),
pa.Table.from_pandas(df_1, preserve_index=False),
pa.Table.from_pandas(df_2, preserve_index=False),
]
),
platform_config=soma.TileDBWriteOptions(**{"sort_coords": False}),
)
assert len(list((Path(uri) / "__commits").iterdir())) == 1
assert len(list((Path(uri) / "__fragments").iterdir())) == 1
```
**Changes:**
- Separate `finalize` and …

[python/c++] Allow GOW multi-submit for single commit

---

.github/workflows/python-ci-single.yml
apis/python/src/tiledbsoma/io/_caching_reader.py
apis/python/src/tiledbsoma/io/_util.py
apis/python/src/tiledbsoma/soma_vfs.cc
apis/python/tests/ht/test_ht_caching_reader.py

`soma.io.from_h5ad` will read H5ADs from any path VFS supports. However, performance on S3 is extremely slow.
Analysis shows that this is caused by two issues:
* `h5py` (which underpins AnnData) assumes it is reading from a file system (eg, issues many small reads, does not read the object sequentially, etc)
* The current implementation translates those requests directly to VFS read calls, which is a documented antipattern (see vfs.h header where it recommends issuing fewer, larger reads)
**Changes:**
This PR introduces a Python caching reader, similar in concept to `io.BufferedReader`, to mediate between `h5Py` and VFS. It introduces several changes in behavior:
* the minimum read size is increased significantly (configurable)
* previously read blocks are …

[python] Ingest from S3 performance

---

.github/workflows/python-ci-full.yml

@bkmartinjr noticed our ubuntu GHAs had `cc`/`cxx` set to `clang` ([example](https://github.com/single-cell-data/TileDB-SOMA/actions/runs/14184688749/job/39738791732#step:9:11)). This was [apparently](https://github.com/single-cell-data/TileDB-SOMA/pull/750/files#diff-9920b0afa17c2e73928b7fc1639e011370756aee90d805c32e76cffb5d0bbd58R19-R22) the case since `python-ci-full.yml` was added in #750.
With this PR, a [manually-dispatched GHA](https://github.com/single-cell-data/TileDB-SOMA/actions/runs/14197589446/job/39776369369#step:9:11) shows GCC, as expected:
```
CC: gcc-13
CXX: g++-13
```
[sc-65188]

[python] `python-ci-full.yml`: fix `include` rules for compiler choice

---

apis/r/src/groups.cpp
apis/r/src/metadata.cpp
apis/r/src/query_condition.cpp
apis/r/src/rinterface.cpp
apis/r/src/riterator.cpp
apis/r/src/rutilities.cpp
apis/r/src/rutilities.h

**Issue and/or context:**  [296](https://github.com/TileDB-Inc/tiledbsoma-feedstock/issues/296)
**Changes:**
Use exposed `tilesdbsoma` logging function instead of `spdlog` directly
```
library(tiledbsoma)
tiledbsoma::set_log_level("<desired log level>")
tiledbsoma::SOMAExperimentOpen("/some/path")
```

[r] Use exposed logger in C++ bindings

---

.github/workflows/python-remote-storage.yml

**Issue and/or context:** Follow-on to PR #3884 given that issue #3879 revealed a defect in #3764 that was detected by the nightly remote-storage CI but not pre-merge CI. See also [[sc-65205]](https://app.shortcut.com/tiledb-inc/story/65205/apparent-umr-in-offsets-returned-on-remote-write).
**Changes:**
Wall times for these two are comparable:
* https://github.com/single-cell-data/TileDB-SOMA/actions/workflows/python-ci-full.yml
* https://github.com/single-cell-data/TileDB-SOMA/actions/workflows/python-remote-storage.yml
Note that the first uses many runners, and the latter only one -- so this PR won't double our per-commit CI time.

[ci] Run remote-storage workflow on all commits

---

.github/workflows/python-dockers.yml
apis/python/pyproject.toml
docker/bookworm.dockerfile
docker/langchain.dockerfile
docker/ubuntu.dockerfile

CMake 4 (released [Friday, 3/27](https://pypi.org/project/cmake/4.0.0/)) broke our vcpkg-source build:
- #3890
- #3867
- #2482
- #2413
**Changes:**
- Pin `cmake<4` in `pyproject.toml` `build-system.requirements`
- Use a pip ["constraints" file](https://pip.pypa.io/en/stable/user_guide/#constraints-files) in Docker builds, to force setuptools to use `cmake<4`.
- This makes [python-dockers.yml] work again, but the ARM Linux jobs still take 25-35mins building wheels (vs. 1-2mins on other platforms).
- It also remains a mystery why we're not getting vcpkg binaries, and why our vcpkg source build is getting an [old/broken cmrc][CMakeRC.cmake#L37].
[![GitHub Actions screenshot showing job timings; ARM jobs take 25-35mins (vs. 1-2mins for x86 …

[python] Pin `build-system.requires`, ARM Linux Docker-builds to `cmake<4`

---

.github/workflows/daily-python-dockers-issue-template.md
.github/workflows/python-dockers.yml
.github/workflows/python-packaging.yml

`python-docker.yml` began failing Friday (#3867), then continued failing for several days, generating a new issue each day (#3870, #3871, #3874, #3880, #3892).
**Changes:**
- `update_existing: true`: update any existing open issue with the same title as the one about to be filed
- Requires removing the date from the title, but I think that makes sense; #3867 turned into a rolling/tracking issue about a build break that lasted multiple days.
- Move assignees from issue-template to `JasonEtco/create-an-issue@v2` invocation (seems a bit nicer)
- Fix an unrelated broken wiki link
I haven't tested this, seems likely correct / we can troubleshoot if/when the next failure occurs. Alternative is I can manually-dispatch it to create a test issue, …

[ci/python] `python-dockers.yml`: improve issue template

---

.github/workflows/python-ci-packaging.yml

Otherwise it runs on any branch push that touches relevant `paths`, which is not necessary (given the `paths` are already tested for `pull_request` events).
Example: I canceled [this run](https://github.com/single-cell-data/TileDB-SOMA/actions/runs/14222818216) on a non-PR branch (where I'm testing `python-packaging.yml` by manually-dispatching runs).

[ci/python] `python-ci-packaging.yml`: only run on `push` events to `main`

---

.github/workflows/python-remote-storage.yml

**Issue and/or context:** On #3885 I converted this job from cron to per-commit. But I forgot to remove the ticket-cutter block.
**Changes:**

[ci] Remove ticket-cutter for no-longer-nightly job

---

.github/workflows/python-dockers.yml
.github/workflows/python-packaging.yml

**Issue and/or context:** Backport #3894 from `main` to `release-1.16` since the backport bot silently did nothing
**Changes:**

[ci] Backport 3894

---

libtiledbsoma/src/soma/soma_group.cc
libtiledbsoma/src/soma/soma_object.cc
libtiledbsoma/src/utils/util.cc
libtiledbsoma/src/utils/util.h

**Issue and/or context:** [[sc-65212]](https://app.shortcut.com/tiledb-inc/story/65212)
**Changes:** The only legitimate thing this type can be is  `Object::Type::Invalid`, and the existing error message already says "Invalid". So, strictly speaking, there's no new information here -- but, it will feel to the user less like we're hiding information: the infamous "Invalid value" error message antipattern wherein we say something is _bad_ without saying what it _was_. (Also, if the value is indeed anything other than `Array`, `Group`, or `Invalid` -- that would likely be memory corruption or an uninitialized memory read, and we this message will help surface that fact as well.)

[c++] Show errant value in not-array-not-group error messages

---

libtiledbsoma/src/soma/soma_array.cc

**Issue and/or context:** [sc-65364](https://app.shortcut.com/tiledb-inc/story/65364/c-logging-broken-in-nnz)
**Changes:**

[c++] Replace deprecated `FragmentInfo.dump` function

---

apis/python/src/tiledbsoma/io/spatial/ingest.py
apis/python/tests/test_from_visium.py

**Issue and/or context:** 
* [sc-63795](https://app.shortcut.com/tiledb-inc/story/63795/remove-anndata-generation-step)
* [sc-56837](https://app.shortcut.com/tiledb-inc/story/56837/add-logging-to-the-visium-ingestor)
**Changes:**
* Directly read data from 10x HDF5 instead of opening it with AnnData.
* (bug fix) Add `platform_config` to spatial array creation.

[python] Directly read Visium table instead of filtering through AnnData

---

apis/python/requirements_spatial.txt
apis/python/setup.py

`pip install tiledbsoma` was issuing a warning like:
```
********************************************************************************
Please consider removing the following classifiers in favor of a SPDX license expression:
License :: OSI Approved :: MIT License
See https://packaging.python.org/en/latest/guides/writing-pyproject-toml/#license for details.
********************************************************************************
```
([GHA example](https://github.com/single-cell-data/TileDB-SOMA/actions/runs/14276171882/job/40019409594#step:9:52); compare to lack of warning in [GHA for this PR](https://github.com/single-cell-data/TileDB-SOMA/actions/runs/14312394947/job/40110373749#step:9:51))
**Changes:**
Our MIT license is already specified in the …

`setup.py`: remove deprecated `License ::` from `classifiers`

---

doc/requirements_doc.txt

- #3917 
- RTD build [still failing](https://app.readthedocs.com/projects/tiledb-inc-tiledb-soma/builds/2947815/#33747619--713), need `numcodecs<0.16` in `requirements_doc.txt` as well.
[RTD build](https://app.readthedocs.com/projects/tiledb-inc-tiledb-soma/builds/2948417/) passed.

[python] `numcodecs<0.16` in docs build

---

apis/python/requirements_spatial.txt
apis/python/src/tiledbsoma/_query.py
apis/python/src/tiledbsoma/io/outgest.py
apis/python/src/tiledbsoma/soma_array.cc
libtiledbsoma/src/soma/soma_array.cc
libtiledbsoma/src/soma/soma_array.h

`tiledbsoma.io.to_anndata` and `ExperimentAxisQuery.to_anndata` contain a partitioned reader optimization. This code uses `nnz` to estimate partition sizes, and in doing so naively assumed `nnz` would always be fast (ie., would only use fragment metadata).  However, there are cases where this is not true, and `nnz` performs the very slow operation of reading and counting all data.
In this "slow" case, the end result is that the `to_anndata` methods will read the entire X array once to count `nnz`, and then read it again to construct the AnnData.
**Changes:**
1. Introduced a private, internal-only API to have `nnz` throw an exception if it is unable to use the "fast" path - ie.., compute nnz from fragment metadata.
2. Used this new hook in the partitioned readers …

[python] Fix partition readers' naïve assumption that `nnz` is fast

---

apis/r/R/SOMAExperimentAxisQuery.R
apis/r/man/SOMAExperimentAxisQuery.Rd
apis/r/tests/testthat/helper-test-soma-objects.R
apis/r/tests/testthat/test-14-SeuratOutgest-assay.R

Seurat v5 adds support for ragged arrays, where not every `X` layer has exactly the same cells and features. To handle this, ragged `X` layers need to be re-indexed and re-shaped on ingestion to resize down to only the data present
- `SOMAExperimentAxisQuery$to_seurat()` and `SOMAExperimentAxisQuery$to_seurat_assay()`: now read in as v5 assays
New SOMA methods:
- `SOMAExperimentAxisQuery$private$.to_seurat_assay_v5()`: helper method to read in ragged and non-ragged arrays into a v5 assay; note this method only handles expression layers, all other assay-level information is handled by parent `$to_seurat_assay()` to share code with v3 assay outgestion
Requires #2523 and #3007
[SC-52261](https://app.shortcut.com/tiledb-inc/story/52261/) #2673

[r] Add support for reading v5 assays from an axis query

---

libtiledbsoma/src/soma/soma_attribute.cc
libtiledbsoma/src/soma/soma_geometry_column.cc
libtiledbsoma/src/utils/arrow_adapter.cc
libtiledbsoma/src/utils/arrow_adapter.h

**Issue and/or context:** [sc-65508](https://app.shortcut.com/tiledb-inc/story/65512/c-valgrind-error-when-running-unit-tests-test-basic-anndata-io-py-k-test-decat-append)
**Changes:**
Use a `malloc`-allocated raw pointer instead of an `std::unique_ptr` (which implicitly does `new`) for child Arrow schema generated by a TileDB attribute.
**Notes for Reviewer:** Continuation of #3873.
On https://github.com/single-cell-data/TileDB-SOMA/pull/3873/files this changed to `malloc`:
https://github.com/single-cell-data/TileDB-SOMA/blob/1c6a0570936928efcaa32bbc3825e9de2ae28c95/libtiledbsoma/src/utils/arrow_adapter.cc#L475
but this use of `std::make_unique` is an implicit `new`:
https://github.com/single-cell-data/TileDB-SOMA/blob/1c6a0570936928efcaa32bbc3825e9de2ae28c95/libtiledbsoma/src/utils/arrow …

[c++] Use raw pointer for child `Attribute` Arrow schema

---

apis/python/setup.py
apis/python/src/tiledbsoma/io/_registration/ambient_label_mappings.py
apis/python/src/tiledbsoma/io/_registration/enum.py
apis/python/src/tiledbsoma/io/_registration/id_mappings.py
apis/python/src/tiledbsoma/io/_util.py
apis/python/src/tiledbsoma/io/ingest.py
apis/python/src/tiledbsoma/io/spatial/ingest.py
apis/python/tests/test_basic_anndata_io.py
apis/python/tests/test_dataframe_io_roundtrips.py
apis/python/tests/test_registration_mappings.py
doc/source/python-tiledbsoma-io.rst

Manual backport of #3865 since backport bot failed here https://github.com/single-cell-data/TileDB-SOMA/pull/3865#issuecomment-2787456227 which, in turn, happened because #3835 hadn't been backported yet and overlapped. Now that #3835 has been backported to #3931 and merged to `release-1.16`, this backport goes in cleanly following the instructions at https://github.com/single-cell-data/TileDB-SOMA/pull/3865#issuecomment-2787456227.

[Backport release-1.16][python] Ingest performance improvements (#3865)

---

apis/python/tests/ht/_ht_util.py
apis/python/tests/test_libfastercsx.py

`valgrind` reports a number of references to uninitialized data in the unit tests.
Root cause is use of `numpy.empty` to allocate memory. Modified tests to use `numpy.zeros`
[[sc-65578]](https://app.shortcut.com/tiledb-inc/story/65578)

[python] Fix valgrind `uninitialized` errors in unit tests

---

libtiledbsoma/src/soma/soma_array.cc
libtiledbsoma/src/soma/soma_array.h

**Issue and/or context:** [[sc-65594]](https://app.shortcut.com/tiledb-inc/story/65594)
As of #3873 and #3928 the method `ArrowAdapter::arrow_schema_from_tiledb_attribute` the `ArrowSchema*` is now allocated using `malloc`:
https://github.com/single-cell-data/TileDB-SOMA/blob/d65892d3fb23e423cfe77b7193c9785291424fe0/libtiledbsoma/src/utils/arrow_adapter.cc#L497
This is used by `SOMAAttribute::arrow_schema_slot` here, and passed through:
https://github.com/single-cell-data/TileDB-SOMA/blob/d65892d3fb23e423cfe77b7193c9785291424fe0/libtiledbsoma/src/soma/soma_attribute.cc#L145-L149
That is converted into `std::unique_ptr` by `SOMAArray::arrow_schema_for_column` here:
https://github.com/single-cell-data/TileDB-SOMA/blob/d65892d3fb23e423cfe77b7193c9785291424fe0/libtiledbsoma/src/soma/soma_array …

[c++] Follow-up to #3873 and #3928

---

apis/python/src/tiledbsoma/_dataframe.py
apis/python/tests/test_dataframe.py

**Issue and/or context:** Improve error-handling UX for #3785 / [[sc-63930]](https://app.shortcut.com/tiledb-inc/story/63930/dataframe-need-api-to-extend-column-enum-values-without-doing-a-write#activity-64471). 
**Changes:**
Before:
```
with tiledbsoma.Experiment.open(uri, "w") as exp:
exp.obs.extend_enumeration_values({'louvain':["three-eyed-alien cells"]})
```
fails with
```
AttributeError: 'list' object has no attribute 'type' 
```
This is confusing and doesn't clearly tell the user what they did wrong, nor how to fix it.
After:
```
ValueError: value column name 'louvain' must be pyarrow.Array: got '<class 'list'>'
```

[python] Improve UX for `extend_enumeration_values` with non-Arrow types

---

apis/python/requirements_spatial.txt
doc/requirements_doc.txt

`zarr==2.18.7` removes the need for it.
- https://github.com/zarr-developers/zarr-python/issues/2963
- #3917
- #3922

[python] Remove `numcodecs<0.16` pin

---

.github/workflows/python-dockers.yml
docker/python-uv.dockerfile

- #3944
- #3890
- #3909
**Changes:**
- Add `python-uv.dockerfile`, verifying using `uv` to `pip install tiledbsoma` in `python:<version>` Docker images (Debian 12 / bookworm-based, but need GCC 13 installed for TileDB-SOMA ≥1.16).
- Add `python:3.{12,13}` x {x86,ARM} builds to `python-dockers.yml` [GHA](https://github.com/single-cell-data/TileDB-SOMA/actions/workflows/python-dockers.yml)

[python] Add `python-uv.dockerfile`

---

.pre-commit-config.yaml

- [#3724] added [pre-commit/mirrors-prettier](http://github.com/pre-commit/mirrors-prettier) hook
- [#3842] bumped it from `v3.0.3` to `v4.0.0-alpha.8`
- [pre-commit/mirrors-prettier] was archived in April '24.
- `v4.0.0-alpha.8` fails for me, locally:
```
prettier.................................................................Failed
- hook id: prettier
- duration: 0.36s
- exit code: 1
node:internal/event_target:1101
process.nextTick(() => { throw err; });
^
TypeError [ERR_INVALID_ARG_TYPE]: The "event" argument must be an instance of Event. Received an instance of SyntaxError
at WorkerShim.dispatchEvent (node:internal/event_target:757:13)
at Worker.<anonymous> (file:///Users/ryan/.cache/pre-commit/repo97q9xrl6/node_env-default/lib/node_modules/prettier/node_modu …
```

[python] Remove `pre-commit/mirrors-prettier` hook

---

apis/python/src/tiledbsoma/soma_array.cc

**Issue and/or context:** Found interactively by @ryan-williams. Issue was `RuntimeError` was being seen at the Python level rather than `tiledbsoma.SOMAError`.
These are tricky to unit-test for, since in the past we've found that usually this works as intended: only on some platforms/installs does the exception get thrown as `RuntimeError`. In particular, I ran Ryan's exact repro script on my system, and it didn't throw `RuntimeError` for me as it did for him on his system. This meant I couldn't craft a unit-test case that failed without this PR's codemod but passed with this PR's codemod. Hence, no new unit-test cases are added on this PR; it suffices that existing unit-test cases continue to pass.
**Changes:** Explicit try-catch using the paradigm already established within …

[python] Fix a spurious exception-class issue

---

apis/python/src/tiledbsoma/common.cc
apis/python/src/tiledbsoma/managed_query.cc
apis/python/tests/test_dataframe.py
apis/python/tests/test_shape.py
apis/python/tests/test_sparse_nd_array.py
apis/python/tests/test_unicode.py
libtiledbsoma/src/soma/managed_query.h

[[sc-61222](https://app.shortcut.com/tiledb-inc/story/61222/python-somasparsearray-read-returns-arrow-table-not-matching-array-schema-nullability#activity-65401)]
This PR fixes several problems when we do not explicitly pass a schema to `pa.Table.from_{arrays,pydict,pandas}` converters:
1. In the Pybind11 [utility function `_buffer_to_table`](https://github.com/single-cell-data/TileDB-SOMA/compare/viviannguyen/sc-61222/python-somasparsearray-read-returns-arrow?expand=1#diff-d123499d8c03fff7d820bb52ab295e45080a15c7a815123ae43cdd2d8bdf0674R218-R235) which takes an `ArrayBuffer` and converts it to a Python `pa.Table` using `pa.Table.from_arrays`, we were taking in a list of names which meant it was inferring the schema from the data in the arrays. We now generate a …

[python] Ensure schema is explicitly passed to `pa.Table.from*` converters

---

apis/python/remote_tests/test_03_versions.py
apis/python/src/tiledbsoma/io/__init__.py
apis/python/src/tiledbsoma/io/shaping.py
apis/python/tests/test_shape.py
apis/python/tests/test_soma_experiment_versions.py
doc/source/python-tiledbsoma-io.rst

**Issue and/or context:** Analog of `tiledbsoma.io.show_experiment_shapes` for programmatic use as requested on [[sc-64098]](https://app.shortcut.com/tiledb-inc/story/64098/get-output-of-tiledbsoma-io-show-experiment-shapes).
**Changes:**
Example outputs can be found in the unit-test files.
Stacked atop #3962.

[python] Implement `tiledbsoma.io.get_experiment_shapes`

---

apis/python/remote_tests/test_03_versions.py
apis/python/src/tiledbsoma/io/__init__.py
apis/python/src/tiledbsoma/io/shaping.py
apis/python/tests/test_shape.py
apis/python/tests/test_soma_experiment_versions.py
doc/source/python-tiledbsoma-io.rst

**Issue and/or context:** This is a refactor split out from #3949 based on a code-review feedback request.
**Changes:**
* On this PR: only do the refactor of existing code.
* On #3949: introduce `get_experiment_shapes`. Then 3949 will no longer be trying to do two things (too many).
By accident I merged #3949 first, not this one. So while the two were reviewed independently, they'll appear in revision history as a single squashed commit. My apologies!

[python] Refactor `io/shaping.py`; `get_experiment_shapes`

---

apis/python/src/tiledbsoma/io/shaping.py

**Issue and/or context:** As noted on #3962:
> By accident I merged https://github.com/single-cell-data/TileDB-SOMA/pull/3949 first, not this one. So while the two were reviewed independently, they'll appear in revision history as a single squashed commit. My apologies!
This PR removes a debug-print I meant not to keep.
**Changes:** Only that.
**Notes for Reviewer:** #3966 includes this. So if 3966 is OK, we can merge 3966 & be done. But if there's any doubt/delay with 3966 let's merge this PR instead.

[python] Fix a typo on #3949

---

apis/python/src/tiledbsoma/io/shaping.py

**Issue and/or context:** Backports #3965 to `release-1.16` following https://github.com/single-cell-data/TileDB-SOMA/pull/3965#issuecomment-2798093586
**Changes:**

[Backport release-1.16][python] Fix a typo on #3949

---

apis/python/src/tiledbsoma/io/ingest.py
apis/python/tests/test_basic_anndata_io.py

[[sc-63459](https://app.shortcut.com/tiledb-inc/story/63459/python-tiledbsoma-io-from-anndata-ignores-ndarray-byteorder-writes-incorrect-data-if-array-is-not-host-byteorder)]
**Changes:**
In `_write_matrix_to_{dense,sparse}NDArray`, ensure that the byteorder is little-endian.

[python] Ensure `ndarray` byteorder is little-endian on matrix writes

---

apis/python/src/tiledbsoma/io/_registration/ambient_label_mappings.py
apis/python/tests/test_registration_mappings.py

The recent changes to ingest registration failed to correctly handle the case where the user requested an obs or var join on something other than the obs/var index.
The docstring for `from_h5ad` clearly states:
```
obs_id_name/var_id_name: Which AnnData ``obs`` and ``var`` columns, respectively, to use
for append mode.
Values of this column will be used to decide which obs/var rows in appended
inputs are distinct from the ones already stored, for the assignment of ``soma_joinid``.  If
this column exists in the input data, as a named index or a non-index column name, it will
be used. If this column doesn't exist in the input data, and if the index is nameless or
named ``index``, that index will be given this name when written to the SOMA experiment's
``obs`` / …
```

[python] Fix mishandling of join-ID column

---

apis/python/src/tiledbsoma/_tdb_handles.py
apis/python/tests/test_metadata.py

**Issue and/or context:** [sc-62840](https://app.shortcut.com/tiledb-inc/story/62840/python-increase-unit-test-coverage-for-various-metadata-value-types)
**Changes:**
- Add more Unicode sequences to metadata unit test
- Add test for bitsized numpy scalars
- Improve error messages for metadata errors

[python] Increase unit-test coverage for various metadata value-types

---

.github/workflows/daily-python-dockers-issue-template.md
.github/workflows/daily-python-packaging-issue-template.md
.github/workflows/daily-test-build-issue-template.md
.github/workflows/python-packaging.yml

- Issue title was missing info on #3969 (`python-dockers.yml` failure)
- `python-packaging.yml`-failure issue-titles could be clearer about which daily build was failing  (cf. #3968)
**Changes:**
- Updated issue-template titles for `python-{dockers,packaging}.yml` to "Daily `XXX.yml` build failing"
- Removed unused `.github/workflows/daily-remote-tests-issue-template.md`
- Renamed issue templates to `daily-python-{dockers,packaging}-issue-template.md`
- Changed `python-packaging.yml` to update an existing issue (to consolidate consecutive-day failures onto one issue)
- This also required removing the date from the issue title. "Daily `XXX.yml` build failing" should capture the spirit of the problem better.
**Notes for reviewer:**
Git{,Hub} are rendering the diff …

[python] Harmonize/GC daily-GHA-failure issue-templates

---

apis/python/src/tiledbsoma/soma_vfs.cc
apis/python/tests/test_basic_anndata_io.py

[[sc-65831](https://app.shortcut.com/tiledb-inc/story/65831/python-c-segv-memory-issues-in-somavfs-somavfsfilebuf)]
**Changes:**
Modify `SOMAVFSFilebuf` to hold a smart pointer to `SOMAVFS`.

[python][c++] Correctly manage lifetime of `SOMAVFS` with `SOMAVFSFilebuf`

---

apis/python/src/tiledbsoma/io/shaping.py
apis/python/tests/test_shape.py

**Issue and/or context:** Implements https://github.com/single-cell-data/TileDB-SOMA/pull/3949#discussion_r2040234927
[sc-64098](https://app.shortcut.com/tiledb-inc/story/64098/get-output-of-tiledbsoma-io-show-experiment-shapes)
**Changes:**

[python] Test `get_experiment_shapes` for underpopulated experiments

---

apis/python/src/tiledbsoma/_soma_object.py

[#3402] [changed](https://github.com/single-cell-data/TileDB-SOMA/pull/3402/files#diff-37c77dc8fe14164529674bc6d4155c68329b4283443501554195bde86b027488L100-R104) `SOMAObject.open` to not use the `clib_type` kwarg. AFAICT:
- Calling `SOMAObject.open` with the default `clib_type=None` will error (`cls._wrapper_type` will raise `AttributeError: type object 'SOMAObject' has no attribute '_wrapper_type'`).
- We never do that; [_tdb_handles.py:89](https://github.com/single-cell-data/TileDB-SOMA/blob/8b8183bfc87bd3b09ebe7c022bb359004400bb9f/apis/python/src/tiledbsoma/_tdb_handles.py#L89) is the only direct reference I see to `SOMAObject.open`; I guess we never call that without explicit `clib_type` either?
- Maybe `clib_type` type-annotation should be modified to …

[python] `SOMAObject.open`: rm unused `clib_type` kwarg

---

apis/r/R/RcppExports.R
apis/r/R/SOMADataFrame.R
apis/r/man/SOMADataFrame.Rd
apis/r/src/RcppExports.cpp
apis/r/src/rinterface.cpp
apis/r/tests/testthat/test-06-SOMADataFrame.R

Replace tiledb-r enum accessors with new libtiledb/Rcpp accessors; also add new `SOMADataFrame$levels()` method to fetch enumeration levels
New SOMA methods:
- `SOMADataFrame$levels()`: get the enumeration levels from one or more enumerated columns. By default `column_names = NULL`: returns a named list of all enumerated columns with their enumeration levels
[SC-65002](https://app.shortcut.com/tiledb-inc/story/65002)

[r] Replace tiledb-r enum accessors with libtiledb/Rcpp

---

apis/python/src/tiledbsoma/io/_caching_reader.py
apis/python/src/tiledbsoma/io/_util.py

There was a cleanup race which only manifested when:
* running in the `ipython` REPL
* an exception was thrown while an AnnData was open using the `soma.io.` anndata read proxy
* and the exception was caught and reported by the ipython REPL (which holds a latent reference to the stack traceback)
All of these together would cause a SEGV in h5py/hdf5.
Work-around is to manually break the race by closing the proxy handle when an exception occurs
**Changes:**
[sc-65863]

h5py cleanup race fix

---

apis/python/src/tiledbsoma/io/_util.py
apis/python/src/tiledbsoma/soma_vfs.cc
apis/python/tests/test_basic_anndata_io.py

[[sc-65864](https://app.shortcut.com/tiledb-inc/story/65864/python-c-valgrind-reports-bad-ref-in-somavfs)]
**Changes:**
Fix lifetime issues with the `Context` by encapsulating `VFS` and `VFSFilebuf` into a single `SOMAFileHandle` Pybind11 class.

[python] Have `SOMAFileHandle` encapsulate both `VFS` and `VFSFilebuf`

---

apis/python/src/tiledbsoma/soma_array.cc
libtiledbsoma/src/soma/soma_array.cc
libtiledbsoma/src/soma/soma_array.h
libtiledbsoma/test/unit_soma_array.cc
libtiledbsoma/test/unit_soma_sparse_ndarray.cc

**Issue and/or context:** [sc-64438](https://app.shortcut.com/tiledb-inc/story/64438/c-sparsendarray-nnz-is-missing-useful-optimization), [sc-64677](https://app.shortcut.com/tiledb-inc/story/64677/c-sparsendarray-nnz-could-use-core-s-count-aggregator)
**Changes:**
- Use the `COUNT` aggregate instead or doing a read and returning the number of rows
- Use the `COUNT` aggregate only on overlapping fragments
Closes #3908

[c++] Optimize `nnz` computation

---

apis/r/R/RcppExports.R
apis/r/src/RcppExports.cpp
apis/r/src/rinterface.cpp
apis/r/src/rutilities.cpp
apis/r/src/rutilities.h
apis/r/tests/testthat/test-06-SOMADataFrame.R
apis/r/tests/testthat/test-06-SOMADenseNDArray.R
apis/r/tests/testthat/test-06-SOMASparseNDArray.R
apis/r/tests/testthat/test-11-OrderedAndFactor.R

Replace calls to `tiledb::domain()` and other domain accessors with libtiledbsom/Rcpp `c_domain()`
[SC-65000](https://app.shortcut.com/tiledb-inc/story/65000)
Requires #3851

[r] Replace `tiledb::domain()` with Rcpp `c_domain()`

---

apis/python/tests/test_dataframe.py
libtiledbsoma/src/soma/managed_query.cc
libtiledbsoma/src/soma/soma_array.cc
libtiledbsoma/src/utils/arrow_adapter.cc
libtiledbsoma/src/utils/arrow_adapter.h

[[sc-62364](https://app.shortcut.com/tiledb-inc/story/62364/python-dataframe-incorrectly-handles-dictionary-types-with-a-timestamp-value-type)]
**Changes:**
For datetime types, use nanoarrow's `ArrowSchemaSetTypeDateTime` to set the time. Previously, we were using a workaround for the column's schema to set the datetime. For the dictionary value's schema, we were setting all datetime types to int64. Remove datetime types that are not supported.

[c++] Use nanoarrow `ArrowSchemaSetTypeDateTime` for datetime values

---

apis/r/DESCRIPTION
apis/r/R/zzz.R

Package startup messages are not allowed in load hook; move them to the attach hook to follow CRAN's policies
Fixes [SOMA-24](https://linear.app/tiledb/issue/SOMA-24)

[r] Move package startup messages to attach hook

---

apis/python/src/tiledbsoma/_dataframe.py
apis/python/tests/test_dataframe.py

DataFrame.create will raise numeric overflow warnings when it should not.  sc-61509

[python] suppress insignificant overflow warning from numpy

---

.pre-commit-config.yaml
apis/python/pyproject.toml
apis/python/tests/test_fastercsx.py
apis/python/tests/test_metadata.py

Changes in preparation for changing default line length:
* Wire up `black` configuration so we can use non-default line length
* Explicitly set python line length to 88 in ruff and black
* Remove skip line too long warning
* run pre-commits (which triggered a couple of small reformats)
Note to reviewers: at a later date, we will move to 120 character line length and reformat the code base.

[python] prepare for ruff/black line length change

---

apis/python/tests/ht/_ht_util.py

the Hypothesis strategy to generate field names in an Arrow schema inadvertently allowed names starting with `soma_`, which are prohibited.  This PR changes the strategy to filter out those names

[python, test] fix HT bug in schema name generation

---

.pre-commit-config.yaml
CONTRIBUTING.md
README.md
apis/python/HISTORY.md
apis/python/README.md
apis/python/notebooks/data/README.md
apis/python/remote_tests/README.md
apis/python/testdata/README.md
apis/python/tests/ht/README.md
apis/r/NEWS.md
apis/r/README.md
apis/r/inst/extdata/README.md
apis/r/vignettes/UsingPlatformConfig.Rmd
apis/r/vignettes/soma-experiment-queries.Rmd
apis/r/vignettes/soma-objects.Rmd
apis/r/vignettes/soma-reading.Rmd
apis/r/vignettes/soma-shapes.Rmd
data/10x-pbmc-multiome-v1.0/README.md
data/README.md
data/simple/dim-uint64_attr-int64_10cells/README.md
doc/README.md
docker/README.md
encoding_specification.md
libtiledbsoma/README.md
libtiledbsoma/doc/README.md
overview.md
profiler/README.md
pull_request_template.md

Changes:
1. Add pre-commit hook to run mdformat on all markdown, including R vignettes
2. Ran hook and commit formatting changes
Excluded `.github` directory as several of those files are space-sensitive when presented in GH issue editor, etc.

Format markdown with mdformat; add pre-commit hook for mdformat

---

apis/r/DESCRIPTION

Let usethis manage dependencies (eg sorting)
Add a link to the docsite so that CRAN can link to it
Fixes [SOMA-46](https://linear.app/tiledb/issue/SOMA-46/clean-up-description)

[r] Clean up `DESCRIPTION`

---

apis/r/DESCRIPTION

Allow building on Conda against R 4.3
Fixes [SOMA-68](https://linear.app/tiledb/issue/SOMA-68/r-roll-back-minimum-version-of-rmatrix)
resolves TileDB-Inc/tiledbsoma-feedstock#313

[r] Roll back minimum version of Matrix

---

.github/workflows/libtiledbsoma-asan-ci.yml
.github/workflows/python-ci-packaging.yml
.github/workflows/r-ci.yml
.github/workflows/r-python-interop-testing.yml
apis/python/HISTORY.md
apis/r/DESCRIPTION
apis/r/NEWS.md
apis/r/tools/get_tarball.R
libtiledbsoma/cmake/Modules/FindTileDB_EP.cmake

Update the TileDB version to 2.28.0 and TileDB-R to 0.32.0.
fixes [SOMA-73](https://linear.app/tiledb/issue/SOMA-73/fix-r-ci-failure-from-pakpkgbuild-bug)

Update the TileDB version to 2.28.0 and TileDB-R to 0.32.0

---

apis/python/tests/test_query_condition.py

Fixes SOMA-129
Valgrind was reporting an error in a unit test. Root cause was calling Pandas DataFrame.all() on an empty dataframe. Worked around by testing first for the empty state.

[python] work around valgrind error in Pandas

---

apis/python/src/tiledbsoma/_dataframe.py
apis/python/src/tiledbsoma/_util.py
apis/python/src/tiledbsoma/soma_column.cc
apis/python/tests/ht/_ht_test_config.py
apis/python/tests/ht/test_ht_dataframe.py
apis/python/tests/test_dataframe_index_columns.py
libtiledbsoma/src/CMakeLists.txt
libtiledbsoma/src/soma/enums.h
libtiledbsoma/src/soma/managed_query.cc
libtiledbsoma/src/soma/managed_query.h
libtiledbsoma/src/soma/soma_array.cc
libtiledbsoma/src/soma/soma_binary_column.cc
libtiledbsoma/src/soma/soma_binary_column.h
libtiledbsoma/src/soma/soma_column.cc
libtiledbsoma/src/soma/soma_dataframe.cc
libtiledbsoma/src/soma/soma_dense_ndarray.cc
libtiledbsoma/src/soma/soma_geometry_dataframe.cc
libtiledbsoma/src/soma/soma_point_cloud_dataframe.cc
libtiledbsoma/src/soma/soma_sparse_ndarray.cc
libtiledbsoma/src/utils/arrow_adapter.cc
libtiledbsoma/src/utils/arrow_adapter.h
libtiledbsoma/src/utils/common.h

**Issue and/or context:** [62236](https://app.shortcut.com/tiledb-inc/story/62236/python-dataframe-create-with-binary-index-column-reports-wrong-column-type-via-schema-property)
**Changes:**
- Adds a new column type `SOMABinaryColumn` that can be both an index column and a ordinary attribute.
- When it is an index column the dimension is internally treated as `TILEDB_STRING_ASCII` type.
- When it is an index column extra metadata are required.
- Values written or returned by such column is casted as `std::vector<std::byte>`.
- Enumerations have been optimized like string attributes.

[c++/python] Add support for binary column

---

apis/python/HISTORY.md
apis/python/src/tiledbsoma/options/_soma_tiledb_context.py

Fixes SOMA-72
A timestamp value of zero is not a legal timestamp in TileDB. TileDB APIs treat `None` and `0` as equivalent to the default time of `now`.  As of TileDB-SOMA 1.15 this package regressed and treated zero as a specific time, which will raise inscrutable errors in various code paths.
**Changes:**
A timestamp value of zero (int) or epoch (datetime.datetime) is equivalent to `now`.

[python] treat timestamp of zero as equivalent to None

---

apis/python/tests/test_basic_anndata_io.py
apis/python/tests/test_platform_config.py
apis/python/tests/test_registration_mappings.py
apis/python/tests/test_update_matrix.py

A number of python unit tests were leaving temp files after a run. Most simply needed to be converted to use the preferred `tmp_path` pytest fixture.
Fixes SOMA-194
There are no change to test semantics, just how those tests create/cleanup temporary files.

[python] unit tests temp file cleanup

---

apis/python/HISTORY.md
apis/python/src/tiledbsoma/io/ingest.py
apis/python/tests/test_basic_anndata_io.py

`"resume"` mode for tiledbsoma.io ingestion methods is deprecated
Fixes SOMA-152
**Changes:**
* added function to check mode and conditionally generate the deprecation warning
* added checks for the warning in unit tests
* a very slight refactoring of `from_anndata` to allow consistent stacklevel warning
Example deprecation message:
```
test.py:276: DeprecationWarning: The 'resume' ingest_mode is deprecated and will be removed in a future version. The current implementation has a known issue that can can cause multi-dataset appends to not resume correctly.
The recommended and safest approach for recovering from a failed ingestion is to delete the partially written SOMA Experiment and restart the ingestion process from the original input files or a known-good …
```

[python] deprecate tiledbsoma.io resume mode

---

apis/python/HISTORY.md
apis/python/setup.py
apis/python/src/tiledbsoma/_indexer.py
apis/python/src/tiledbsoma/_soma_array.py
apis/python/src/tiledbsoma/io/ingest.py
apis/python/tests/test_basic_anndata_io.py
apis/python/tests/test_io.py
apis/python/tests/test_registration_mappings.py

tiledbsoma.io.append_{obs,var,X} are deprecated
Fixes SOMA-147
**Changes:**
* Added dependency pin for typing-extensions - minimum set to the version where the deprecated decorator was added
* Marked append functions as deprecated
* Marked several other (previously) deprecated functions with the deprecation decorator
* Added tests to verify warning is generated for append functions

[python] deprecate tiledbsoma.io.append_ functions

---

.github/workflows/python-dockers.yml

- #3909 
**Changes:**
- Test Docker builds ([python-dockers.yml](https://github.com/single-cell-data/TileDB-SOMA/actions/workflows/python-dockers.yml)) against 1.16.2 (wheels) instead of 1.16.0 (source build, on ARM Linux)
1.16.x ARM images [are fast now](https://github.com/single-cell-data/TileDB-SOMA/actions/runs/15189344256?pr=4079) (1-2mins, instead of 20-30 from source):
<details><summary>Timings screenshot</summary>
</details>

[python] `python-dockers`: bump 1.16.x builds (to pick up ARM wheels)

---

apis/r/R/ConfigList.R
apis/r/R/MappingBase.R
apis/r/R/PlatformConfig.R
apis/r/R/SOMAContextBase.R
apis/r/R/SOMATileDBContext.R
apis/r/R/ScalarMap.R
apis/r/R/TileDBCreateOptions.R
apis/r/man/ConfigList.Rd
apis/r/man/MappingBase.Rd
apis/r/man/PlatformConfig.Rd
apis/r/man/SOMAContextBase.Rd
apis/r/man/SOMATileDBContext.Rd
apis/r/man/ScalarMap.Rd
apis/r/man/TileDBCreateOptions.Rd

Add examples for the following objects
- `ConfigList`
- `PlatformConfig`
- `ScalarMap`
- `SOMATileDBContext`
- `TileDBCreateOptions`
Add links from the following ABCs to real classes:
- `MappingBase` ABC
- `SOMAContextBase` ABC
Fixes [SOMA-211](https://linear.app/tiledb/issue/SOMA-211/add-examples-for-mapping-types)
Partially replaces #4075

[r] Add examples for mapping types

---

apis/python/src/tiledbsoma/io/_registration/ambient_label_mappings.py

Add explicit cast to fix emergent lint error from mypy - looks like it was released as a dot-dot patch, which spontaneously started breaking our CI.

[python] fix pre-commit lint

---

apis/r/R/utils-matrixZeroBasedView.R
apis/r/R/utils-tiledb.R
apis/r/man/matrixZeroBasedView.Rd
apis/r/man/show_package_versions.Rd

Add examples for the following objects
- `matrixZeroBasedView`
- `show_package_versions()`
Fixes [SOMA-214](https://linear.app/tiledb/issue/SOMA-214/add-examples-for-utils)
Partially replaces #4075

[r] Add examples for exported `utils-*.R` objects

---

apis/r/R/BlockwiseIter.R
apis/r/R/ReadIter.R
apis/r/R/SparseReadIter.R
apis/r/R/TableReadIter.R
apis/r/man/BlockwiseReadIterBase.Rd
apis/r/man/BlockwiseSparseReadIter.Rd
apis/r/man/BlockwiseTableReadIter.Rd
apis/r/man/ReadIter.Rd
apis/r/man/SparseReadIter.Rd
apis/r/man/TableReadIter.Rd

Add examples for the following objects:
- `BlockwiseSparseReadIter`
- `BlockwiseTableReadIter`
- `SparseReadIter`
- `TableReadIter`
Add links from the following ABCs to real classes:
- `ReadIter` ABC
- `BlockwiseReadIterBase` ABC
Note for reviewers: the `#' @examplesIf` construct allows conditional examples; this is used as
- CRAN requires all docs that write to disk to write to a temporary directory
- CRAN requires that all temporary directories be cleaned up
- withr handles the temporary directory management, but I don't want to take a hard dependency on it
- `#' @examplesIf` allows the examples to run if and only if the conditions are met (eg. withr is installed)
Fixes [SOMA-210](https://linear.app/tiledb/issue/SOMA-210/add-examples-for-read-iterators)
Partially replaces #4075

[r] Add examples for read iterators

---

.github/workflows/r-ci.yml
.github/workflows/r-python-interop-testing.yml

Use release version of pak for R dependency resolution. As of today (2025-06-02), the current versions of pak and pkgbuild are:
- [pak](https://cran.r-project.org/package=pak): 0.9.0 released 2025-05-27
- [pkgbuild](https://cran.r-project.org/package=pkgbuild) 1.4.8 released 2025-05-26
cf r-lib/pak#778, r-lib/pkgbuild#208
Fixes [SOMA-74](https://linear.app/tiledb/issue/SOMA-74/roll-back-pakpkgbuild-devel-to-release)

[r] [ci] Use pak-release instead of pak-devel for R dependencies

---

apis/python/tests/_util.py

Our Python unit tests use some private pytest API which was changed in pytest 8.4.0.
Short term fix which introspects the pytest version to adapt to this change.
Affects only a handful of unit tests

add support for pytest 8.4.0

---

apis/python/HISTORY.md
apis/python/src/tiledbsoma/_factory.py
apis/python/src/tiledbsoma/_geometry_dataframe.py
apis/python/src/tiledbsoma/_multiscale_image.py
apis/python/src/tiledbsoma/_point_cloud_dataframe.py
apis/python/src/tiledbsoma/_scene.py
apis/python/src/tiledbsoma/_soma_group.py
apis/python/src/tiledbsoma/_soma_object.py
apis/python/src/tiledbsoma/_tdb_handles.py
apis/python/src/tiledbsoma/soma_array.cc
apis/python/src/tiledbsoma/soma_group.cc
apis/python/tests/_util.py
apis/python/tests/ht/_array_state_machine.py
apis/python/tests/test_collection.py
apis/python/tests/test_dataframe.py
apis/python/tests/test_dense_nd_array.py
apis/python/tests/test_experiment_basic.py
apis/python/tests/test_reopen.py
apis/python/tests/test_sparse_nd_array.py
libtiledbsoma/src/soma/soma_array.cc
libtiledbsoma/src/soma/soma_array.h
libtiledbsoma/src/soma/soma_group.cc
libtiledbsoma/src/soma/soma_group.h

Towards SOMA-168
**Changes:**
The Python `SOMAObject.reopen` method is documented as creating a new `SOMAObject` with the requested mode and timestamp from an existing `SOMAObject`. The existing behavior was to close and reopen the original `SOMAObject` in its original mode in order to write metadata to the object before reopening, and would then create and return a new `SOMAObject` with the requested mode and timestamp.
This breaking change will close the internal handle, open a new internal handle in the requested mode and timestamp, and return the original (i.e. `self`) from the method in the requested mode and timestamp.

Fix undocumented reopen behavior in Python

---

apis/python/HISTORY.md
apis/python/src/tiledbsoma/io/ingest.py

Ingest (`from_anndata`/`from_h5ad`) will filter duplicate obs and var IDs as part of appending new data. In the case where the obs axis is a priori known to contain only unique IDs, this filter step can be bypassed, for a performance win. This builds upon the previous change to `register_{anndatas,h5ads}` which introduced the `allow_duplicate_obs_ids` parameter.
Fixes SOMA-259

[python] skip obs axis read-back when appending known unique observations to Experiment

---

libtiledbsoma/src/soma/soma_array.cc
libtiledbsoma/src/soma/soma_array.h
libtiledbsoma/src/soma/soma_dataframe.cc
libtiledbsoma/src/soma/soma_dataframe.h
libtiledbsoma/src/soma/soma_dense_ndarray.cc
libtiledbsoma/src/soma/soma_dense_ndarray.h
libtiledbsoma/src/soma/soma_geometry_dataframe.cc
libtiledbsoma/src/soma/soma_geometry_dataframe.h
libtiledbsoma/src/soma/soma_point_cloud_dataframe.cc
libtiledbsoma/src/soma/soma_point_cloud_dataframe.h
libtiledbsoma/src/soma/soma_sparse_ndarray.cc
libtiledbsoma/src/soma/soma_sparse_ndarray.h
libtiledbsoma/test/unit_soma_dense_ndarray.cc

Towards SOMA-168
**Changes:**
Deduplicate `exists` checks for `SOMAArray` and use the faster `SOMAArray::open` methods instead of `SOMAObject::open`` factory method.
Internal refactor - no changelog changes.

Update C++ exists methods to use SOMAArray _exists method

---

apis/python/HISTORY.md
apis/python/src/tiledbsoma/__init__.py
apis/python/src/tiledbsoma/_general_utilities.py
apis/python/src/tiledbsoma/pytiledbsoma.cc
apis/python/tests/test_context.py
apis/python/tests/test_general_utilities.py
libtiledbsoma/src/utils/version.cc
libtiledbsoma/src/utils/version.h

There have been several examples where users end up with corrupted conda environments, manifesting as strange and difficult to diagnose errors. Root cause in at least one is a mismatch between the build-time and run-time TileDB version. This is an attempt to provide some detection and warning of this condition.
Changes:
1. Add C++ API to report the TileDB version that the Python pybind11 module was built against ("expected" TileDB version)
2. Add package import-time check to validate that our build-time and run-time TileDB versions match. A `RuntimeError` (exception) is raised upon mismatch.
3. Tests
Fixes SOMA-267

[python] import time check of expected TileDB version

---

.github/workflows/backport.yml

Latest version of `tibdex/backport` is v2
Fixes [SOMA-244](https://linear.app/tiledb/issue/SOMA-244/backportyml)
Partially tackles [SOMA-76](https://linear.app/tiledb/issue/SOMA-76/periodic-chore-update-all-gh-workflow-action-versions)

[ci] Update GH actions in `backport.yml`

---

.github/workflows/backport.yml

Backport v2 runs on any labeled PR and throws an error if the PR is open; this updates the action to run only on merged PRs with a backport label
Condition taken from the [example `backport.yml`](https://github.com/tibdex/backport/blob/7005ef85c4562bc23b0e9b4a9940d5922f439750/.github/workflows/backport.yml)
Fixes [SOMA-330](https://linear.app/tiledb/issue/SOMA-330/run-backportyml-only-on-backport-labeled-prs)

[ci] Run `backport.yml` only on backport-labeled PRs

---

apis/python/HISTORY.md
apis/python/src/tiledbsoma/_constants.py
apis/python/src/tiledbsoma/_query.py
apis/python/src/tiledbsoma/_util.py
apis/python/src/tiledbsoma/io/_common.py
apis/python/src/tiledbsoma/io/ingest.py
apis/python/src/tiledbsoma/io/outgest.py
apis/python/tests/test_dataframe_io_roundtrips.py
apis/python/tests/test_experiment_query.py

Add functionality to `ExperimentAxisQuery.to_anndata` which will set the axis dataframe index:
* on user request
* or using the ingestion-time metadata
Fixes SOMA-89
Acknowledgement: this is largely based upon #3779

[python] Add obs_id_name/var_id_name params to ExperimentAxisQuery.to_anndata

---

apis/r/DESCRIPTION
apis/r/man/SOMAArrayBase.Rd
apis/r/man/SOMACollectionBase.Rd
apis/r/man/SOMAObject.Rd

It looks like some delete-mode docs for R weren't generated; this PR generates them
Fixes [SOMA-329](https://linear.app/tiledb/issue/SOMA-329/r-update-missing-docs)

[r/docs] Update missing docs

---

apis/python/HISTORY.md
apis/python/src/tiledbsoma/_query.py
apis/python/src/tiledbsoma/_soma_group.py
apis/python/src/tiledbsoma/io/outgest.py
apis/python/tests/ht/_array_state_machine.py
apis/python/tests/test_collection.py
apis/python/tests/test_experiment_query.py

The SOMAGroup / Collection caches reified objects in getitem. This code lacked any concurrency protection, so objects requested concurrently would repeatedly load and overwrite the cache slot in the parent group.
This had a couple of problematic effects if a race to populate the cache occurs:
* the TileDB group is read multiple times, create multiple SOMA objects, etc. Essentially a performance problem
* unlike serial invocations, it would return different SOMA objects for the same underlying array, causing object identity tests to fail (we don't normally promise that the identities are `eq`, but a side effect of the cache is that they are anyway)
Changes:
* add a simple mutex around the cache update
* pre-commit/ruff also reformatted a couple of misc files for free
* this PR (randomly) …

[python] add lock around SOMAGroup reification

---

apis/python/pyproject.toml
apis/python/src/tiledbsoma/_dataframe.py
apis/python/src/tiledbsoma/_geometry_dataframe.py
apis/python/src/tiledbsoma/_managed_query.py
apis/python/src/tiledbsoma/_point_cloud_dataframe.py
apis/python/src/tiledbsoma/_read_iters.py
apis/python/src/tiledbsoma/_tdb_handles.py
apis/python/src/tiledbsoma/_util.py
apis/python/src/tiledbsoma/io/_registration/ambient_label_mappings.py
apis/python/src/tiledbsoma/io/ingest.py
apis/python/src/tiledbsoma/io/shaping.py
apis/python/src/tiledbsoma/io/spatial/_spatialdata_util.py
apis/python/tests/test_sparse_nd_array.py

Additional linter rules added to our baseline config:  BLE, C4 and YTT.
Also fixes the errors raised by these new rules.
Part of SOMA-323

[python] enable Ruff lint rules BLE, C4 and YTT

---

apis/python/src/tiledbsoma/io/ingest.py

**Issue and/or context:** SOMA-160.
**Changes:** Updates docstrings for `update_obs` and `update_var` to document importance of `new_data`'s row order.

Document row order assumptions for update_obs/var

---

apis/python/tests/test_experiment_query.py

(hopefully) fixes SOMA-349
Add explicit delete and gc to a test which uses a lot of memory

[python] reduce memory use in test

---

apis/python/tests/ht/_ht_util.py
apis/system/tests/test_sparsendarray_write_r_read_python.py

Fixes SOMA-363
Fixes SOMA-364
Arrow 20 chnages:
* fixed a casting bug for BooleanScalar types, which exposed a bug in the unit test logic for comparing empty arrays.
* update to sparray (scipy.sparse) changes

[python] unit tests:  Arrow 20 API changes

---

.github/workflows/python-remote-storage.yml
apis/python/tests/ht/_array_state_machine.py
apis/python/tests/ht/test_ht_caching_reader.py
apis/python/tests/ht/test_ht_densendarray.py
apis/python/tests/test_update_dataframes.py

Correct typos in unit tests incorrectly using Hypothesis `precondition` decorator.
Fixes  SOMA-368
Fixes  #4174 
Note to reviewers: testing this PR also exposed an OOM condition in unit tests (on MacOS runners), due to use of the default SOMA context (which allows for more memory than is available in small runners). Fixed by specifying the small mem context used elsewhere in unit tests.
Note 2 to reviewer: PR also contains a temporary pin for `tiledb` to work-around the core version breakage caused by new symbols being added in a patch release.

[python] fix unit test bugs related to hypothesis usage

---

apis/python/tests/test_registration_mappings.py

Add and use `soma_tiledb_context` fixture in registration mapping periodically failing from OOM.

[python] Add soma_tiledb_context to test failing on CI

---

.github/workflows/python-packaging.yml

`python-packaging.yml` uses `pypa/cibuildwheel@v2.23.2`, latest is [v3.1.1](https://github.com/pypa/cibuildwheel/releases/tag/v3.1.1)
Fixes [SOMA-375](https://linear.app/tiledb/issue/SOMA-375/python-packagingyml)
Resolves [SOMA-242](https://linear.app/tiledb/issue/SOMA-242/update-soma-gh-action-workflow-versions)
Note for reviewers: I've adjusted the workflow triggers to include PRs that modify `python-packaging.yml`; I can remove this if necessary

[ci] Update `pypa/cibuildwheel` version

---

.github/workflows/libtiledbsoma-asan-ci.yml
.github/workflows/python-ci-packaging.yml
.pre-commit-config.yaml
apis/python/HISTORY.md
apis/python/src/tiledbsoma/io/_registration/ambient_label_mappings.py
apis/python/src/tiledbsoma/io/_registration/id_mappings.py
apis/python/tests/_util.py
apis/python/tests/conftest.py
apis/python/tests/ht/_ht_util.py
apis/r/DESCRIPTION
apis/r/NEWS.md
apis/r/tools/get_tarball.R
apis/system/tests/test_sparsendarray_write_r_read_python.py
libtiledbsoma/cmake/Modules/FindTileDB_EP.cmake

**Changes:**
* Update TileDB core version from 2.28.0 to 2.28.1
* Update changelogs and TileDB-R version
* Backport a series of small test/linter fixes

Update TileDB core to 2.28.1

---

.github/workflows/R-CMD-check.yaml
.github/workflows/libtiledb-ci.yml
.github/workflows/libtiledbsoma-asan-ci.yml
.github/workflows/python-ci-single.yml
.github/workflows/python-dependency-variation.yml
.github/workflows/r-python-interop-testing.yml

Update GitHub actions to fetch tags with depth=1 instead of cloning entire repo.

[ci] Update checkout to fetch tags with depth=1

---

apis/python/src/tiledbsoma/_query_condition.py
apis/python/src/tiledbsoma/common.h
apis/python/src/tiledbsoma/query_condition.cc
apis/python/tests/test_query_condition.py

Similarly to what is done in https://github.com/TileDB-Inc/TileDB-Py/pull/2211
Closes SOMA-377

[python] Add support for `not` in query conditions

---

apis/python/src/tiledbsoma/io/_common.py
apis/python/src/tiledbsoma/io/conversions.py
apis/python/tests/_util.py
apis/python/tests/test_experiment_query.py
apis/python/tests/test_fastercsx.py

`AnnData` equally supports `scipy.sparse.sparray` (eg., csr_array) and `scipy.sparse.spmatrix` (eg. csr_matrix) since the 0.11 release.
`tiledbsoma.io.from_anndata` seems to work just fine when given an `AnnData` containing an X of type `csr_array`, but the type signatures do not contain these types.
Request: add `csr_array` and `csc_array` support "officially" to tiledbsoma.io.from_anndata
**Changes:**
`apis/python/src/tiledbsoma/io/conversions.py` - Type hints and isinstance checks
`apis/python/src/tiledbsoma/io/_common.py` - SparseMatrix union type
`apis/python/tests/test_experiment_query.py` - Compatible assertions
`apis/python/tests/_util.py` - Utility compatibility
`apis/python/tests/test_fastercsx.py` - Type annotations
This PR is a …

Adding sparray official support from_anndata

---

apis/python/tests/test_experiment_query.py

**Changes:**
* Remove redundant section of the test
* Delete obs/var sooner

Attempt to make historical test garbage collection more aggressive

---

apis/python/HISTORY.md
apis/python/setup.py
apis/python/src/tiledbsoma/__init__.py
apis/python/src/tiledbsoma/_coordinate_selection.py
apis/python/src/tiledbsoma/_dataframe.py
apis/python/src/tiledbsoma/_dense_nd_array.py
apis/python/src/tiledbsoma/_geometry_dataframe.py
apis/python/src/tiledbsoma/_point_cloud_dataframe.py
apis/python/src/tiledbsoma/_sparse_nd_array.py
apis/python/src/tiledbsoma/coordinate_selection.cc
apis/python/src/tiledbsoma/options/__init__.py
apis/python/src/tiledbsoma/options/_tiledb_create_write_options.py
apis/python/src/tiledbsoma/pytiledbsoma.cc
apis/python/src/tiledbsoma/soma_dataframe.cc
apis/python/src/tiledbsoma/soma_point_cloud_dataframe.cc
apis/python/src/tiledbsoma/soma_sparse_ndarray.cc
apis/python/tests/test_dataframe.py
apis/python/tests/test_dense_nd_array.py
apis/python/tests/test_geometry_dataframe.py
apis/python/tests/test_point_cloud_dataframe.py
apis/python/tests/test_sparse_nd_array.py

* Closes SOMA-175
* Closes SOMA-174
**Changes:**
* Add internal class `CoordinateValueFilter` for constructing delete cells query condition.
* Add `TileDBDeleteOptions` for platform config (currently no options).
* Add/implement `delete_cells` method for `SparseNDArray`, `DataFrame`, and `PointCloudDataFrame`.
* Add `delete_cells` method to `GeometryDataFrame`, but throw a `NotImpelmentedError` for now.
* Add `delete_cells` method to `DenseNDArray` that throws a `NotImplementedError` (not supported in core).

[python] Add python implementation for delete cells

---

apis/python/HISTORY.md
apis/python/src/tiledbsoma/_common_nd_array.py
apis/python/tests/test_dense_nd_array.py
apis/python/tests/test_sparse_nd_array.py

SOMA SparseNDArray and DenseNDArray arrays are created with a specific data type (e.g., type=pa.float32), but there is no direct way to retrieve this type via the API. Users must currently inspect the underlying Arrow schema and infer the type from there.
**Changes:**
Adding a new `property` inside the NDArray class to be inherited by both Sparse and DenseNDArray classes.
None

Adding `.type` property for Sparse/DenseNDArrays

---

apis/python/HISTORY.md
apis/python/src/tiledbsoma/io/_util.py
apis/python/tests/test_basic_anndata_io.py

SOMA-449 / #4219 demonstrate a race in the H5AD IO path for `tiledbsoma.io`. 
This race can occur with any storage system (it was reported against GCS, but testing revealed it against a local filesystem as well).

[python] concurrency safe monkey patch for AnnData IO path

---

doc/source/python-tiledbsoma-dataframe.rst
doc/source/python-tiledbsoma-experiment.rst
doc/source/python-tiledbsoma-pointclouddataframe.rst
doc/source/python-tiledbsoma-sparsendarray.rst

**Issue and/or context:** Towards SOMA-475
**Changes:**
* Update read-the-docs generation to include new delete cell methods

[python] Add delete cells methods to read-the-docs

---

apis/python/src/tiledbsoma/io/ingest.py

**Issue and/or context:** SOMA-275
**Changes:** Update `register_h5ads()` docstrings to document the two supported append-mode workflows. I also reworded some of the narrative text for clarity.
**Notes for Reviewer:** This also restructures some of the additional narrative text to use indentation rather than underlines to separate sections, which aligns with Google style docstrings.

[python] Document supported workflows for registration functions

---

.github/workflows/python-remote-storage.yml

**Issue and/or context:** Closes SOMA-373
**Changes:**
Remove pin that was temporarily needed while release process was underway for release 2.28.1.

[ci] Remove github workflow tiledb-py pin

---

.github/workflows/python-packaging.yml

The `macOS 13` runner image will be retired by `December 4th, 2025`. To raise awareness of the upcoming removal, jobs using `macOS 13` will temporarily fail during the scheduled brownout.
**Changes:**
- Changed the `macos-13` with `macos-15-intel` which is newly introduced label for environments that require the x86_64 (Intel) environment
- 

Substitute macos-13 runners with macos-15-intel

---

apis/python/src/tiledbsoma/io/ingest.py

**Issue and/or context:**  Improves the docstring formatting for the `update_obs` and `update_var` functions to better align with google's pydoc conventions.

Improve formatting of `update_obs`/`update_var` docstrings

---

libtiledbsoma/src/soma/soma_dimension.cc
libtiledbsoma/src/soma/soma_dimension.h
libtiledbsoma/src/soma/soma_geometry_column.cc
libtiledbsoma/src/soma/soma_geometry_column.h
libtiledbsoma/src/tiledb_adapter/platform_config.h
libtiledbsoma/src/utils/arrow_adapter.cc
libtiledbsoma/src/utils/arrow_adapter.h
libtiledbsoma/test/CMakeLists.txt
libtiledbsoma/test/test_platform_config.cc
libtiledbsoma/test/unit_soma_sparse_ndarray.cc

**Issue and/or context:** Towards SOMA-619
**Changes:**
This moves `SOMADimension` and `SOMAGeometyColumn` construction out of the ArrowAdapter class and into the respective column classes. This is in preparation for creating C++ constructors for SOMA arrays (e.g. `SOMADataFrame`, `SOMASparseNDArray`) without first creating intermediary arrow tables.

[c++] Move column construction from ArrowAdapter to Column subclasses
