single-cell-data/TileDB-SOMA

- apis/python/README.md
- apis/python/setup.cfg
Note `TileDB-Py` `0.14.1` or higher.
> Add dependency-version requirement for TileDB-Py

- apis/python/src/tiledbsc/scgroup.py
- apis/python/src/tiledbsc/util_tiledb.py
Add config/context to python scgroup class to let the user set a TileDB configuration or TileDB context for opening/reading/writing the arrays and groups.
> Add config/context to python scgroup class

- apis/python/src/tiledbsc/scgroup.py
One step for #17.
Note: this is distinct from https://github.com/single-cell-data/TileDB-SingleCell/issues/12.
Using this repo's `ingestor.py` on [anndata/pbmc3k_processed.h5ad](./anndata/pbmc3k_processed.h5ad):
```
$ du -hs tiledb-data/pbmc3k_processed.old/X/*
4.0K	tiledb-data/pbmc3k_processed.old/X/__group
0B	tiledb-data/pbmc3k_processed.old/X/__meta
0B	tiledb-data/pbmc3k_processed.old/X/__tiledb_group.tdb
52M	tiledb-data/pbmc3k_processed.old/X/data
496M	tiledb-data/pbmc3k_processed.old/X/raw
$ du -hs tiledb-data/pbmc3k_processed/X/*
4.0K	tiledb-data/pbmc3k_processed/X/__group
0B	tiledb-data/pbmc3k_processed/X/__meta
0B	tiledb-data/pbmc3k_processed/X/__tiledb_group.tdb
26M	tiledb-data/pbmc3k_processed/X/data
168M	tiledb-data/pbmc3k_processed/X/raw
```
Focus on particular files:
``` …
```
> Improve default filters on X storage

- apis/python/tests/test_tiledbsc.py
A couple changes to our existing tests that will make it easier to swap reference objects and reuse code:
- use fixtures to generate file path for the test h5ad file and (separately) read it into memory as an `anndata` object
- use the [pathlib-based `HERE` convention](https://github.com/scverse/anndata/blob/a3af650d40fd804cd866d55a674a7eeaa20fdec0/anndata/tests/test_readwrite.py#L22) to conveniently reference test datasets
- update tests to compare directly against the test `anndata` object
> Refactor tests to compare against a reference object

- apis/python/src/tiledbsc/soma.py
- apis/python/tests/test_tiledbsc.py
Updates write methods to avoid densifying `X`, `raw` and `obsp`/`varp`. 
Adds two new private methods for:
1. converting the `ndarray`/`csr_matrix`/`csc_matrix` to coo format prior to ingestion. 
2. creating a sparse 2D tiledb array with string labels
which are used internally by `write_annotation_matrices()` (for `obsp`/`varp`) and `write_X_array()`.
Tests have also been added to check the number of non-zero elements to verify the original sparsity of data is maintained.
> Maintain sparsity of X and obsp/varp

- apis/python/src/tiledbsc/soma.py
- apis/python/tests/test_tiledbsc.py
More in the vein of #28. Simultaneously, fixes `obsm`/`varm` mislabeling as identified in issue #26.
Context: #12.
> Maintain sparsity of obsm/varm

- apis/python/src/tiledbsc/soma.py
This takes a significant amount of time and space on larger data files.
It was used in previous revisions of the code this week but the need for it has been modded away.
> Remove meshgrid deadcode

- apis/python/src/tiledbsc/util_ann.py
Several of the type-diversity issues at
https://github.com/single-cell-data/TileDB-SingleCell/issues?q=is%3Aissue+is%3Aopen+label%3Aedge-case
involve various dtypes for `obs` and `var` in anndata files.
Here we surface those readily at a glance. (I use the `desc-ann.py` script routinely as a keystroke-saver/work-accelerator for this project.)
```
$ ./desc-ann.py ~/scdata/anndata/bruce-spatial.h5ad
================================================================ {input_path}
ANNDATA SUMMARY:
AnnData object with n_obs × n_vars = 6471 × 33
obs: 'CellType', 'Region', 'Valid', 'n_genes_by_counts', 'log1p_n_genes_by_counts', 'total_counts', 'log1p_total_counts', 'leiden', 'louvain'
var: 'Fluorophore', 'Hybridization', 'n_cells_by_counts', 'mean_counts', 'log1p_mean_counts', …
```
> Show column dtypes for obs and var

- .gitignore
- apis/python/desc-array-fragments.py
Adds a small utility to print a table containing details for each fragment in an array, including their size and non-empty domains for each dim.
Example:
```
> ./desc-array-fragments.py dev/arrays/bruce-559-ordered/X/data
Listing fragments for array: 'dev/arrays/bruce-559-ordered/X/data'
array_schema_name  num  cell_num     size                                  d0                             d1
0  __1651499718503_1651499718503_eb799bf7b8354d02...    0   1001152  3381993  (X1000010011.A01, X1000010014.B07)  (ENSG00000000003, ERCC-00171)
1  __1651499718503_1651499718503_eb799bf7b8354d02...    1   1002502  3427963  (X1000010014.B08, X1000010016.D03)  (ENSG00000000003, ERCC-00171)
2  __1651499718503_1651499718503_eb799bf7b8354d02...    2   1001036  3523571   (X1000010016.D04, X1000101204.C3) …
```
> Array fragment printer

- apis/python/desc-ann-types.py
- apis/python/ingestor.py
- apis/python/src/tiledbsc/soma.py
- apis/python/src/tiledbsc/util.py
- apis/python/src/tiledbsc/util_ann.py
Context: #37 
For CSR X data/raw matrices (CSC flagged as a to-do), ingest the CSR to COO not all at once, but rather, a few rows at a time, converting each chunk to COO and doing a TileDB write on that chunk.
For CSR matrices which can be whole-COO'ed into RAM, this runs no faster than before; for those which are too large to be whole-COO'ed into RAM, this makes ingestion possible.
Resulting storage space can be slightly larger than it otherwise would be: each TileDB write forces a new fragment, so we should carefully consider the chunk-sizing decision. As of this writing, this is done by matching chunk nnz to a fixed parameter -- which we can make configurable on #27.
PR-reviewer alert: there's some timing-related/transparency stuff on this PR, so …
> Add row-wise chunked-COO ingest for CSR X/data and X/raw

- apis/python/README-csr-ingest.md
- apis/python/src/tiledbsc/soma.py
Context: #37.
Caveats are as noted within `README-csr-ingest.md` which is more easily reviewable at
https://github.com/single-cell-data/TileDB-SingleCell/blob/kerl/sc-17395/chunked-csr-enable/apis/python/README-csr-ingest.md
> Enable chunked-CSR writes

- apis/python/README.md
- apis/python/src/tiledbsc/soma.py
- apis/python/src/tiledbsc/util.py
- apis/python/src/tiledbsc/util_tiledb.py
- apis/python/tests/test_tiledbsc.py
Context: https://github.com/single-cell-data/TileDB-SingleCell/issues/15
Reviewer advice: this is a cross-cutting PR; going through
https://github.com/single-cell-data/TileDB-SingleCell/pull/64/commits
may be helpful ... 🙏 
Old:
```
GROUP
|-- X GROUP
|------ data ARRAY
|------ raw ARRAY
|-- obs ARRAY
|-- var ARRAY
|-- obsm GROUP
|------ foo ARRAY
|-- varm GROUP
|------ bar ARRAY
```
New:
```
GROUP
|-- X GROUP
|------ data ARRAY
|-- obs ARRAY
|-- var ARRAY
|-- obsm GROUP
|------ X_tsne ARRAY
|------ X_pca ARRAY
|-- varm GROUP
|------ PCs ARRAY
|-- obsp GROUP
|------ distances ARRAY
|-- raw GROUP
|------ X GROUP
|---------- data ARRAY
|------ var ARRAY
```
Sample ingest:
```
$ ./ingestor.py anndata/pbmc3k_processed.h5ad
START  SOMA.from_h5ad anndata/pbmc3k_processed.h5ad -> …
```
> Change group structure to have raw/X, raw/var, raw/varm

- apis/python/tests/test_anndata_raw.py
Two additional tests to check the behavior of from_anndata for `.raw.X` and `.raw.var`.
Note that the `.raw.var` test is disabled due to issue #50
> initial test for saving raw X and var

- apis/python/src/tiledbsc/soma.py
- apis/python/src/tiledbsc/util.py
- apis/python/tests/test_type_diversity.py
Several fixes related to AnnData dataframes:
* When a DataFrame contains a CategoricalDtype, attempt to encode in TileDB using the underlying primitive type (eg, int, string, ...), rather than presuming that all categoricals are string.  Related to #30
* Catch cases where "not a category", aka NaN, is not supported by the underlying category type, and it can not be converted to a native TileDB type (eg, an int64 category).  Related to #60
* Handle cases where dataframes have no columns (ie, only an index).  Related to #33 and #45
* Unit test improvements for the above
An important type handling decision codified by this PR (see second bullet) -- categoricals with "nan" which can not be converted to string or float will raise an exception, as they would if Pandas `astype` was used.  The …
> DataFrame type handling fixes

- apis/python/setup.cfg
- apis/python/src/tiledbsc/assay_matrix.py
- apis/python/src/tiledbsc/util.py
Ingesting larger `.h5ad` files can take a while, principally in `X/data` and `raw/X/data`: on my laptop, anyway, a few hours total for a muiti-gigabyte file. On this PR we offer an ETA for each chunked ingest:
```
$ ingestor.py --ifexists replace anndata/tabula-sapiens-immune.h5ad
START  SOMA.from_h5ad anndata/tabula-sapiens-immune.h5ad -> ./tiledb-data/tabula-sapiens-immune
START  READING anndata/tabula-sapiens-immune.h5ad
FINISH READING anndata/tabula-sapiens-immune.h5ad TIME 58.058 seconds
START  DECATEGORICALIZING
FINISH DECATEGORICALIZING TIME 1.817 seconds
START  WRITING ./tiledb-data/tabula-sapiens-immune
Creating TileDB group ./tiledb-data/tabula-sapiens-immune
Creating TileDB group ./tiledb-data/tabula-sapiens-immune/X
START  WRITING ./tiledb-data/tabula-sapiens-immune/X/data …
```
> Print chunk-ingest ETA

- .github/workflows/format.yml
Great advice from @Shelnutt2.
This is an automated enforced for the manual run done on #92.
Help standardize the code coming out this week for #95.
Note: `black` is already in our `apis/python/setup.cfg`.
> Add Python-formatter to CI for Python code

- apis/python/setup.cfg
Following on https://github.com/TileDB-Inc/TileDB-Py/pull/1109
For existing checkouts: `pip install --upgrade tiledb`
> Depend on new TileDB-Py 0.15.1

- apis/python/src/tiledbsc/annotation_dataframe.py
- apis/python/src/tiledbsc/soma_options.py
- apis/python/tests/test_tiledbsc.py
As discussed on #99, these columns are non-queryable -- a blocker for prototype/demo work on #95 et al. -- unless they're stored as ASCII.
This allows us to generate SOMA data for the prototype/demo timeframe.
> Store to-be-queried obs/var columns as ASCII (workaround)

- apis/python/src/tiledbsc/annotation_matrix_group.py
- apis/python/src/tiledbsc/annotation_pairwise_matrix_group.py
- apis/python/tests/test_soma_group_indexing.py
This allows nice syntax like:
```
soma = tiledbsc.SOMA('/Users/johnkerl/mini-corpus/tiledb-data/tabula-sapiens-epithelial')
for e in soma.obsm:
print('obsm/'+e.name, e.shape(), e.uri)
for e in soma.varm:
print('varm/'+e.name, e.shape(), e.uri)
for e in soma.obsp:
print('obsp/'+e.name, e.shape(), e.uri)
for e in soma.varp:
print('varp/'+e.name, e.shape(), e.uri)
```
```
obsm/X_scvi_umap (104148, 2) file:///Users/johnkerl/mini-corpus/tiledb-data/tabula-sapiens-epithelial/obsm/X_scvi_umap
obsm/X_scvi (104148, 50) file:///Users/johnkerl/mini-corpus/tiledb-data/tabula-sapiens-epithelial/obsm/X_scvi
obsm/X_pca (104148, 50) file:///Users/johnkerl/mini-corpus/tiledb-data/tabula-sapiens-epithelial/obsm/X_pca
obsm/X_umap (104148, 2) file:///Users/johnkerl/mini-corpus/tiledb-data/tabula-sapiens-epith …
```
> 'for matrix in soma.obsm: ...' et al

- apis/python/src/tiledbsc/annotation_dataframe.py
- apis/python/src/tiledbsc/annotation_matrix.py
- apis/python/src/tiledbsc/annotation_pairwise_matrix.py
- apis/python/src/tiledbsc/assay_matrix.py
- apis/python/src/tiledbsc/soma.py
- apis/python/tests/test_dim_select.py
Context: #95 
Examples (see also test cases on this PR):
```
$ ./tools/ingestor anndata/pbmc-small.h5ad ./tiledb-data/pbmc-small
...
```
```
>>> import tiledbsc
>>> soma = tiledbsc.SOMA('./tiledb-data/pbmc-small')
>>> soma.obs.ids()
[b'AAATTCGAATCACG', b'AAGCAAGAGCTTAG', b'AAGCGACTTTGACG', b'AATGCGTGGACGGA', [snip] b'TTGCATTGAGCTAC', b'TTGGTACTGAATCC', b'TTTAGCTGTACTCT']
>>> soma.var.ids()
[b'AKR1C3', b'CA2', b'CD1C', b'GNLY', b'HLA-DPB1', b'HLA-DQA1', b'IGLL5', b'MYL9', b'PARVB', b'PF4', b'PGRMC1', b'PPBP', b'RP11-290F20.3', b'RUFY1', b'S100A8', b'S100A9', b'SDPR', b'TREML1', b'TUBB1', b'VDAC3']
>>> soma.obs.dim_select([b'AAGCGACTTTGACG', b'AATGCGTGGACGGA'])
orig.ident  nCount_RNA  nFeature_RNA  RNA_snn_res.0.8  letter.idents groups  RNA_snn_res.1
obs_id
AAGCGACTTTGACG           0 …
```
> Implement SOMA-level dimension-slicing

- apis/python/src/tiledbsc/annotation_dataframe.py
- apis/python/src/tiledbsc/soma.py
- apis/python/tests/test_attribute_filter.py
Context: #95 
Examples:
```
>>> soma = tiledbsc.SOMA('/Users/johnkerl/mini-corpus/tiledb-data/tabula-sapiens-immune')
```
```
>>> soma.obs.attribute_filter('tissue == "blood"', ['development_stage'])
development_stage
obs_id
AAACCCAAGACCAAGC_TSP14_Blood_NA_10X_3_1            59-year-old human stage
AAACCCAAGCAACAGC_TSP1_blood_3                      59-year-old human stage
AAACCCAAGCACCAGA_TSP8_Blood_NA_10X_1_1             56-year-old human stage
AAACCCAAGCATCAAA_TSP2_Blood_NA_10X_1_3             61-year-old human stage
AAACCCAAGCCGTCGT_TSP7_Blood_NA_10X_1_1             69-year-old human stage
...                                                                    ...
TTTGTTGTCCTAAACG_TSP2_Blood_NA_10X_1_3             61-year-old human stage
TTTGTTGTCGATTGAC_TSP7_Blood_NA_10X_1_1 …
```
> Attribute-filter logic for obs and var

- apis/python/src/tiledbsc/annotation_dataframe.py
- apis/python/src/tiledbsc/annotation_matrix.py
- apis/python/src/tiledbsc/annotation_pairwise_matrix.py
- apis/python/src/tiledbsc/assay_matrix.py
- apis/python/src/tiledbsc/tiledb_array.py
- apis/python/tests/test_soma_group_indexing.py
These are schema-introspection accessors. In an upcoming PR, we'll have an `examples/` directory, along with some vignette-style documentation.
* These are largely tiledb-agnostic -- returning `pandas.DataFrame` etc. There is, however, a `foo.tiledb_array_schema()` method
* At present the single X layers are `soma.X.data` and `soma.raw.X.data`. In a future PR these will be `soma.X["data"]` and `soma.raw.X["data"]` along with an add-layer functionality.
* At present (on this PR) there are three ways to get schema-related info:
* `soma.foo.df().keys() and `some.foo.df().dtypes` -- loads a dataframe and returns pandas/numpy types
* Plus: not storage-specific/tiledb-specific
* Minus: requires loading the df. We can do `soma.foo.df(["nonesuch"]).dtypes` to get a "no such answer" query but this …
> SOMA-component dataframe/schema accessors

- apis/python/README.md
- apis/python/src/tiledbsc/annotation_dataframe.py
- apis/python/src/tiledbsc/annotation_matrix.py
- apis/python/src/tiledbsc/annotation_matrix_group.py
- apis/python/src/tiledbsc/annotation_pairwise_matrix.py
- apis/python/src/tiledbsc/annotation_pairwise_matrix_group.py
- apis/python/src/tiledbsc/assay_matrix.py
- apis/python/src/tiledbsc/assay_matrix_group.py
- apis/python/src/tiledbsc/raw_group.py
- apis/python/src/tiledbsc/soma.py
- apis/python/src/tiledbsc/tiledb_array.py
- apis/python/src/tiledbsc/tiledb_group.py
- apis/python/src/tiledbsc/tiledb_object.py
- apis/python/src/tiledbsc/uns_array.py
- apis/python/src/tiledbsc/uns_group.py
- apis/python/src/tiledbsc/util.py
- apis/python/src/tiledbsc/util_ann.py
- apis/python/src/tiledbsc/util_tiledb.py
- apis/python/tests/test_mem_fs.py
- apis/python/tests/test_soma_group_indexing.py
While Python of course does not have method-access categories such as `public`, `protected`, or `private`, nonetheless we can more clearly mark some for-internal-use methods as being such.
Also, when a user does something like `soma.obs.` and then tries to tab-complete in the Python interpreter, the methods/attributes having leading underscores are left out by default, allowing the user to focus on methods which truly belong to the SOMA API and which aren't simply tiledb-specific implementation details toward that API. (Implementation-oriented users can tab-complete with `soma.obs._` if they like, and/or use `dir(soma.obs)`.)
This becomes ever more important as we flesh out the SOMA API last week and this week.
> Flag some for-internal-use methods more clearly as such

- apis/python/tests/test_type_diversity.py
#58 just needs a test case re-enabled; the underlying `TileDB-Py` issue has been fixed.
> Close issue #58

- apis/python/src/tiledbsc/annotation_dataframe.py
- apis/python/src/tiledbsc/annotation_matrix.py
- apis/python/src/tiledbsc/annotation_matrix_group.py
- apis/python/src/tiledbsc/annotation_pairwise_matrix.py
- apis/python/src/tiledbsc/annotation_pairwise_matrix_group.py
- apis/python/src/tiledbsc/assay_matrix_group.py
- apis/python/src/tiledbsc/raw_group.py
- apis/python/src/tiledbsc/soma.py
- apis/python/src/tiledbsc/tiledb_array.py
- apis/python/src/tiledbsc/tiledb_group.py
- apis/python/src/tiledbsc/uns_array.py
- apis/python/src/tiledbsc/uns_group.py
- apis/python/src/tiledbsc/util_ann.py
- apis/python/tests/test_mem_fs.py
Previously I was spelling out calls to `self._open()` and `self._close()`. Issues:
* The`with-as` syntax is more compact and more pythonic
* Having `self._open()` set `self._tiledb_group` for other methods to use until `self._close()` introduced a mysterious-looking quasi-global
* Abnormal exits were causing a "group is already open" on subsequent accesses
To do:
* As commented clearly in `tiledb_array.py`, with-open-as and open/close pairs both work correclty for arrays, using a single `_open` method.
* As also commented in `tiledb_group.py`, with-open-as and open/close pairs require two separate methods for groups, until the `TileDB-Py` `Group` object has an `__enter__`/`__exit__` pair defined on it.
CC (and a big thank-you) to @thetorpedodog for a fantastic conversation about with-as …
> Use with-open-as idiom internally

- apis/python/src/tiledbsc/soma_options.py
- apis/python/src/tiledbsc/tiledb_group.py
- apis/python/tests/test_soco_ops.py
- apis/python/tools/README.md
- apis/python/tools/ingestor
The `relative` flag, which we set correctly for TileDB Cloud ops, is not desirable for local-disk or S3 operations within a SOMA. For pre-demo experiments, creating a little mini-collection of SOMAs and moving them around, this is a bit annoying -- @ebezzi and I have both bumped into this.
```
$ ingestor --ifexists replace anndata/pbmc-small.h5ad
...
```
```
$ peek-soma tiledb-data/pbmc-small
>>> soma.obs.df()
orig.ident  nCount_RNA  nFeature_RNA  RNA_snn_res.0.8  letter.idents groups  RNA_snn_res.1
obs_id
AAATTCGAATCACG           0       327.0            62                1              1     g2              1
AAGCAAGAGCTTAG           0       126.0            48                0              0     g1              0
AAGCGACTTTGACG           0       443.0            77                1 …
```
> Allow correct relative-membership flags for local disk as well as TileDB Cloud [WIP]

- apis/python/src/tiledbsc/tiledb_group.py
Before:
```
johnkerl@Kerl-MBP.home[prod][python]$ peek-soma nonesuch
>>> soma.obsp.keys()
File "/Users/johnkerl/git/single-cell-data/TileDB-SingleCell/apis/python/src/tiledbsc/tiledb_group.py", line 84, in _open
G = self._open_withlessly(mode)
File "/Users/johnkerl/git/single-cell-data/TileDB-SingleCell/apis/python/src/tiledbsc/tiledb_group.py", line 72, in _open_withlessly
return tiledb.Group(self.uri, mode=mode, ctx=self._ctx)
File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/tiledb/group.py", line 188, in __init__
super().__init__(cctx, uri, query_type)
tiledb.cc.TileDBError: [TileDB::Group] Error: Cannot open group; Group does not exist
During handling of the above exception, another exception occurred:
Traceback …
```
> Better group-member handling on non-existent paths

- apis/python/src/tiledbsc/annotation_matrix.py
- apis/python/src/tiledbsc/annotation_pairwise_matrix_group.py
- apis/python/src/tiledbsc/assay_matrix.py
- apis/python/src/tiledbsc/assay_matrix_group.py
- apis/python/src/tiledbsc/raw_group.py
- apis/python/src/tiledbsc/soma.py
- apis/python/tests/test_soma_group_indexing.py
Context: #125 
Example:
```
import tiledbsc
soma = tiledbsc.SOMA('tiledb-data/pbmc3k_processed')
print(soma.X.data.shape())
print(soma.obs.shape())
print(soma.var.shape())
print(soma.obsm['X_pca'].shape())
print(soma.varm['PCs'].shape())
print(soma.obsp['distances'].shape())
print(soma.raw.X.data.shape())
print(soma.raw.var.shape())
```
```
(2638, 1838)
(2638, 4)
(1838, 1)
(2638, 50)
(1838, 50)
(2638, 2638)
(2638, 13714)
(13714, 1)
```
> Support soma.X.shape(), initial implementation

- apis/python/src/tiledbsc/annotation_dataframe.py
- apis/python/src/tiledbsc/annotation_matrix.py
- apis/python/src/tiledbsc/assay_matrix.py
- apis/python/src/tiledbsc/tiledb_array.py
- apis/python/src/tiledbsc/tiledb_group.py
- apis/python/src/tiledbsc/util_tiledb.py
- apis/python/tests/test_soco_ops.py
- apis/python/tests/test_tiledbsc.py
This will be useful for tree-traversal in the C++ implementation, as well as for Python/R compatibility checks.
Example (in addition to unit-test cases on this PR):
```
$ ingestor anndata/pbmc-small.h5ad tiledb-data/pbmc-small
...
```
```
$ populate-soco -o soco -a tiledb-data/pbmc-small
Adding pbmc-small to tiledb-data/pbmc-small
Creating TileDB group soco
```
```
$ python
>>> import tiledb
>>> A = tiledb.open('tiledb-data/pbmc-small/X/data')
>>> A.meta['__soma_object_type__']
'AssayMatrix'
>>> A.close()
>>> G = tiledb.group.Group('tiledb-data/pbmc-small/X')
>>> G.meta
<tiledb.group.Group.GroupMetadata object at 0x7f9e51e79f70>
>>> G.meta['__soma_object_type__']
'AssayMatrixGroup'
>>> G.close()
>>> G = tiledb.group.Group('tiledb-data/pbmc-small')
>>> G.meta['__soma_object_type__']
'SOMA' …
```
> Write SOMA object type as group/array metadata

- apis/python/README-ingestion.md
- apis/python/src/tiledbsc/assay_matrix.py
- apis/python/src/tiledbsc/util.py
- apis/python/src/tiledbsc/util_ann.py
When originally coding the ingestor for this package, at the Python REPL I asked some `anndata` slot for its `type` and what came back was `scipy.sparse._csr.csr_matrix` -- so I shrugged, typed that in, and continued.
This is an internal name; it's better to use `scipy.sparse.csr_matrix`.
This is an ask from one of our early kick-the-tires users.
> Use the public name for scipy.sparse.csr_matrix

- apis/python/src/tiledbsc/annotation_dataframe.py
- apis/python/src/tiledbsc/soma_options.py
- apis/python/tests/test_type_diversity.py
- apis/python/tools/peek-ann
Context: issue #99. (See also: issue #106 and PRs #101 and #117.)
As pointed out by @bkmartinjr in a Slack conversation, the selection of string columns to store as ASCII on #101 was artificial, and likely to cause confusion. The better approach he suggested was to do this to _all_ string attributes.
This PR implements that better approach.
We will need this store-as-ASCII, decode-to-Unicode on read workaround for a couple months or so now pending some non-trivial work in TileDB core to fully support `QueryCondition` logic on Unicode attributes. As a reminder on the important of this workaround, string attributes are _non-queryable_ unless they are stored as ASCII, until full core-level support is in place; cc @Shelnutt2 and @ihnorton.
Note for @ebezzi and @bkmartinjr -- we will need a …
> Extend ASCII-queryability workaround

- apis/python/src/tiledbsc/tiledb_group.py
At the moment we can't read back group-element names from the TileDB Group API. Previously I worked around this by taking basename of element URI and calling that "name" but this isn't a good heuristic in cases like this:
```
/Users/johnkerl/mini-corpus/tiledb-data-seurat/adipocytes-seurat/soma_RNA"
/Users/johnkerl/mini-corpus/tiledb-data-seurat/wilms-tumors-seurat/soma_RNA"
```
as these have the same basename.
On this PR is a better way to get the names these were added with.
On an upcoming TileDB-Py release we'll have direct TileDB-API support for this.
> Group-names readback

- apis/python/src/tiledbsc/annotation_dataframe.py
- apis/python/tests/test_ascii_and_unicode.py
Context: #106 
See also: #138 #101 #99
The idea is that:
* For the next few months, pending an upcoming TileDB-core release, we'll be taking `obs`/`var` Unicode strings and storing them as "ASCII" which really means bytes -- "α,β,γ" stores as "\xce\xb1,\xce\xb2,\xce\xb3"
* On readback of `obs`/`var` dataframes we decode back to "α,β,γ"
* This was being done correctly on the `AnnotationDataFrame`'s `dim_select` / `df` accessor; the same logic needs applied to its `attribute_filter` accessor
> Correct ASCII-to-Unicode readback for attribute_filter

- libtiledbsc/cmake/Modules/FindSpdlog_EP.cmake
- libtiledbsc/cmake/Superbuild.cmake
- libtiledbsc/include/tiledbsc/logger_private.h
- libtiledbsc/include/tiledbsc/logger_public.h
- libtiledbsc/src/CMakeLists.txt
- libtiledbsc/src/cli/cli.cc
- libtiledbsc/src/logger.cc
- libtiledbsc/src/logger.h
Add `spdlog` support to the C++ API.
Example usage:
``` c++
#include <tiledbsc/logger_private.h>
...
LOG_CONFIG("debug");
...
LOG_INFO("walking soco URI = '{}'", uri);
...
```
> Add spdlog to C++ API

- apis/python/src/tiledbsc/tiledb_group.py
- apis/python/src/tiledbsc/tiledb_object.py
- apis/python/src/tiledbsc/uns_group.py
- apis/python/src/tiledbsc/util_tiledb.py
- apis/python/tests/test_soma_metadata.py
This introduces some metadata accessors but doesn't yet put them to use.
Places to use them include #106, where:
* For columns, we'll store original category-type names (for anndata categoricals which were downcast to TileDB strings)
* For arrays, we'll store information like "this was originally CSR" or "this was originally CSC"
* For `uns`, we'll store scalars no longer as length-1 arrays but rather as group metadata
* For SOMA objects, we'll store information like "this was written by `tiledbsc-r v0.1.2`
See also #115 which is stacked atop this.
Note: this is stacked atop #144, hence the higher line-count -- see https://github.com/single-cell-data/TileDB-SingleCell/pull/116/commits
> Initial group/array metadata access methods

- apis/python/src/tiledbsc/uns_array.py
- apis/python/src/tiledbsc/uns_group.py
- apis/python/tests/test_anndata_uns.py
Context: #88 
Example data:
```
>>> soma = tiledbsc.SOMA('tiledb-data/brown-adipose-tissue-mouse')
>>> soma.uns.show()
uns:
X_normalization: log1p, base e, scaled
publication_doi: https://doi.org/10.1038/s41586-020-2496-1
schema_version: 2.0.0
title: Brown adipose tissue — A single-cell transcriptomic atlas characterizes ageing tissues in the mouse
uns/layer_descriptions:
X: log(counts_per_thousand+1)
raw.X: raw
uns/neighbors:
uns/neighbors/params:
uns/neighbors/params/n_pcs/
[5]
uns/neighbors/params/metric/
['euclidean']
uns/neighbors/params/method/
['umap']
uns/neighbors/params/n_neighbors/
[15]
uns/louvain:
uns/louvain/params:
uns/louvain/params/random_state/
[0]
uns/leiden:
uns/leiden/params:
uns/leiden/params/random_state/
[0]
uns/leiden/params/n_iterations/
[-1] …
```
> Store uns scalars as group metadata, not 1D arrays

- apis/python/doc/README-ingestion.md
- apis/python/doc/annotation_matrix_group.md
- apis/python/doc/annotation_pairwise_matrix_group.md
- apis/python/doc/assay_matrix_group.md
- apis/python/doc/soma.md
- apis/python/doc/tiledb_array.md
- apis/python/doc/tiledb_group.md
- apis/python/doc/tiledb_object.md
- apis/python/doc/uns_group.md
- apis/python/src/tiledbsc/annotation_matrix_group.py
- apis/python/src/tiledbsc/annotation_pairwise_matrix_group.py
- apis/python/src/tiledbsc/assay_matrix_group.py
- apis/python/src/tiledbsc/soma.py
- apis/python/tests/test_tiledbsc.py
These include:
* `soma.obs_keys()` for `soma.obs_names` for `soma.obs.ids()`
* `soma.var_keys()` for `soma.var_names` for `soma.var.ids()`
* `soma.n_obs` for `soma.obs.shape()[0]`
* `soma.n_var` for `soma.var.shape()[0]`
Also:
* `soma.X.data` for `soma.X['data']`
* `soma.obsm.X_pca` for `soma.obsm['X_pca']`
* `soma.obsp.distances` for `soma.obsp['distances']`
See also #125
> Implement some convenience-accessors, imitating AnnData

- apis/python/src/tiledbsc/soma_options.py
Based on experiments with chunking and consolidation. We can write fewer, larger fragments without OOMing, with comparable query time.
> Bump default goal-chunk-nnz for chunked X ingest

- apis/python/src/tiledbsc/util.py
- apis/python/tools/ingestor
- apis/python/tools/outgestor
Just one spot in `tools/ingestor`. All other callsites within the package seem to be well-handled already via `tiledb.methodnamegoeshere(..., ctx=self._ctx)`.
```
$ ingestor anndata/pbmc-small.h5ad s3://tiledb-johnkerl/scratch/pbmc-small-s3-upload
START  SOMA.from_h5ad anndata/pbmc-small.h5ad -> s3://tiledb-johnkerl/scratch/pbmc-small-s3-upload
START  READING anndata/pbmc-small.h5ad
FINISH READING anndata/pbmc-small.h5ad TIME 0.048 seconds
START  DECATEGORICALIZING
FINISH DECATEGORICALIZING TIME 0.005 seconds
START  WRITING s3://tiledb-johnkerl/scratch/pbmc-small-s3-upload
Creating TileDB group s3://tiledb-johnkerl/scratch/pbmc-small-s3-upload
START  WRITING s3://tiledb-johnkerl/scratch/pbmc-small-s3-upload/obs
FINISH WRITING s3://tiledb-johnkerl/scratch/pbmc-small-s3-upload/obs TIME …
```
> Allow S3 ingest

- libtiledbsc/cmake/Superbuild.cmake
- libtiledbsc/include/tiledbsc/buffer_set.h
- libtiledbsc/include/tiledbsc/carrow.h
- libtiledbsc/include/tiledbsc/common.h
- libtiledbsc/include/tiledbsc/generic_typed_vector.h
- libtiledbsc/include/tiledbsc/ij_query.h
- libtiledbsc/include/tiledbsc/managed_query.h
- libtiledbsc/include/tiledbsc/query_result.h
- libtiledbsc/include/tiledbsc/sc_arrowio.h
- libtiledbsc/include/tiledbsc/tiledbsc.h
- libtiledbsc/include/tiledbsc/util.h
- libtiledbsc/src/soma_collection.cc
- scripts/test
* Update the clang-format check to find all source files
* Update source files missed with the previous `make format`
* Fix a bug in reading group metadata
> Improve clang-format checking

- apis/python/src/tiledbsc/annotation_dataframe.py
- apis/python/src/tiledbsc/assay_matrix.py
- apis/python/src/tiledbsc/io/anndata.py
- apis/python/src/tiledbsc/raw_group.py
- apis/python/src/tiledbsc/util.py
We had two dataframe methods; there should be just one.
Moreover this makes for a nice API enhancement used by @ebezzi . Namely:
```
>>> df = soma.X['data'].dim_select(None,['AKR1C3','VDAC3'])
>>> csr = tiledbsc.util.X_and_ids_to_sparse_matrix(df, 'obs_id', 'var_id', 'value', soma.obs.ids(), soma.var.ids())
>>> csr.shape
(80, 20)
>>> csr.mean(axis=1).shape
(80, 1)
```
> Coalesce two dataframe methods into one

- apis/python/src/tiledbsc/annotation_dataframe.py
- apis/python/src/tiledbsc/assay_matrix.py
- apis/python/src/tiledbsc/util.py
- apis/python/tests/test_dim_select.py
Example from @ebezzi -- this occurs when dim-selecting on `X` matrices where the slice contains all-zero rows/columns.
Before:
```
$ peek-soma ~/Desktop/collab/bezzi/bezzi-soma
>>> var_df = soma.var.df()
>>> var_df[var_df.feature_name == "CLMP"]
feature_biotype  feature_is_filtered feature_name feature_reference
var_id
ENSG00000166250            gene                    0         CLMP    NCBITaxon:9606
>>> var_ids = ['ENSG00000166250']
>>> xdf = soma.X.data.dim_select(obs_ids=None, var_ids=var_ids)
>>> csr = tiledbsc.util.X_and_ids_to_sparse_matrix(xdf, 'obs_id', 'var_id', 'value', soma.obs.ids(), var_ids)
>>> csr.shape
(2092, 1)
>>> len(soma.obs.ids())
2113
```
After:
```
$ peek-soma ~/Desktop/collab/bezzi/bezzi-soma
>>> var_df = soma.var.df()
>>> var_df[var_df.feature_name == "CLMP"] …
```
> Ensure sliced matrices are correctly dimensioned

- apis/python/src/tiledbsc/soma_options.py
The goal was to up fragment sizes --
Before:
```
-rw-r--r--  1 johnkerl  staff    21M Jun  3 17:09 try-pre-consol/X/data/__fragments/__1654290548407_1654290548407_9d622d5ea1364b488cd9cf0ee9e44286_13/d1_var.tdb
-rw-r--r--  1 johnkerl  staff    21M Jun  3 17:09 try-pre-consol/X/data/__fragments/__1654290561536_1654290561536_6ac6853ea4774c28845614a9f1fba039_13/d1_var.tdb
-rw-r--r--  1 johnkerl  staff    21M Jun  3 17:12 try-pre-consol/X/data/__fragments/__1654290742771_1654290742771_9fe9df06edd14cdaba738ac70399fc2d_13/d1_var.tdb
-rw-r--r--  1 johnkerl  staff    21M Jun  3 17:07 try-pre-consol/X/data/__fragments/__1654290467666_1654290467666_c59a65e556334be0975d90248512740c_13/d1_var.tdb
-rw-r--r--  1 johnkerl  staff    21M Jun  3 17:08 …
```
> #149 was overly ambitious

- apis/python/src/tiledbsc/io/anndata.py
Arose when using the following test-only script which (biologically nonsensically) splits SOMAs into smaller pieces for testing:
https://gist.github.com/johnkerl/774746589db7a951bae68abe57ed07a6
> Allow outgest of rawless SOMAs

- apis/python/examples/soma-collection-reconnaissance.md
- apis/python/src/tiledbsc/soma.py
- apis/python/src/tiledbsc/soma_collection.py
These are keystroke-savers for frequently-asked questions about SOMA/SOCO data.
> Add len and cell-count convenience accessors

- apis/python/setup.cfg
Numba's latest version [0.55.2](https://github.com/numba/numba/releases/tag/0.55.2) added support for numpy 1.22, so we no longer need to pin it to `<1.22`, which was preventing installation on M1 macs. 
Further, because numpy is already a requirement of tiledb-py, we can drop it from `setup.cfg` altogether.
> Remove numpy pin

- apis/python/setup.cfg
Fixes intermittent SEGV as reported by @bkmartinjr, which happened when creating a `SOMACollection` then a `SOMA` within it, using the same tiledb-context object.
Does not address `bool` issue, as [0.15.5](https://github.com/TileDB-Inc/TileDB-Py/releases/tag/0.15.5) doesn't do what we need to get `bool` support in `tiledb.from_pandas` context (`AnnotationDataFrame` as used by `obs` and `var`), since `TileDB-Py` 0.15.5 depends on core 2.9.4:
https://github.com/TileDB-Inc/TileDB-Py/blob/dev/tiledb/dataframe_.py#L125-L127
> Depend on TileDB-Py 0.15.5

- .github/workflows/ci.yml
Update the CI Github actions to:
- Build a wheel for the TileDB-SingleCell Python API
- When a new release is published:
- Upload it to [Test PyPI](https://test.pypi.org/)
- Upload it to (the official) PyPI If it's not a pre-release.
An admin of this repo must:
1. Create an account on Test PyPI and PyPI to register this project under.
Note: these are two independent accounts. 
2. Create an API token for each account (under account settings: https://test.pypi.org/manage/account/ / https://pypi.org/manage/account/) to use for this project.
3. Add two [action secrets](https://github.com/single-cell-data/TileDB-SingleCell/settings/secrets/actions) in the settings of this repo:
- `TEST_PYPI_TOKEN`: API token for Test PyPI
- `PYPI_TOKEN`: API token for PyPI
> Github action for uploading to PyPI

- apis/python/tools/desc-ann
- apis/python/tools/desc-soma
- apis/python/tools/ingestor
- apis/python/tools/outgestor
- apis/python/tools/peek-ann
- apis/python/tools/peek-soma
- apis/python/tools/populate-soco
As of #185 we have `isort .` and `flake8` in addition to the already existing `black .`.
However these check only `.py` files; some items in `apis/python/tools` can be checked using `flake8 tools/*`.
Note: The `tools/peek-*` scripts have a `python -i` shebang line and are intended to be invoked and interacted with. This means they _intentionally_ import more packages than the files themselves use; in fact their _entire purpose_ is for keystroke-reduction for the user, so they can get a Python prompt and do things with a minimum of manual imports.
> More flake8 findings

- apis/python/doc/annotation_matrix.md
- apis/python/doc/soma_collection.md
- apis/python/doc/util_tiledb.md
- apis/python/src/tiledbsc/__init__.py
- apis/python/src/tiledbsc/annotation_matrix_group.py
- apis/python/src/tiledbsc/annotation_pairwise_matrix_group.py
- apis/python/src/tiledbsc/assay_matrix_group.py
- apis/python/src/tiledbsc/raw_group.py
- apis/python/src/tiledbsc/soma.py
- apis/python/src/tiledbsc/tiledb_group.py
- apis/python/src/tiledbsc/uns_group.py
- apis/python/src/tiledbsc/util_tiledb.py
- apis/python/tools/desc-soma
I'm not including unit-test cases here because of (a) credentials, and (b) clean-up associated with the tests.
I'll write up some doc-content on a separate PR. For the moment, do know that laptop -> S3/tiledb-cloud is slow. Best performance is had by running a client on a large EC2 instance in the same AWS region as the storage, or from a TileDB Cloud notebook (which does the same).
Note I have the following public on TileDB Cloud:
* `tiledb://johnkerl-tiledb/pbmc-small`
* `tiledb://johnkerl-tiledb/pbmc3k_processed`
Examples:
```
$ ingestor anndata/pbmc3k_processed.h5ad tiledb://johnkerl-tiledb/s3://tiledb-johnkerl/scdata/pbmc3k_processed
```
```
$ peek-soma tiledb://johnkerl-tiledb/pbmc3k_processed
>>> soma.uri
'tiledb://johnkerl-tiledb/pbmc3k_processed'
>>> soma.obs.uri …
```
> tiledb-cloud testing results

- .github/workflows/format.yml
- apis/python/src/tiledbsc/annotation_matrix_group.py
- apis/python/src/tiledbsc/annotation_pairwise_matrix_group.py
- apis/python/src/tiledbsc/assay_matrix.py
- apis/python/src/tiledbsc/uns_array.py
- apis/python/src/tiledbsc/uns_group.py
- apis/python/src/tiledbsc/util.py
- apis/python/src/tiledbsc/util_ann.py
- apis/python/tests/test_type_diversity.py
- apis/python/tools/ingestor
- apis/python/tools/peek-ann
- apis/python/tools/peek-soco
- apis/python/tools/peek-soma
- apis/python/tools/populate-soco
- Follow up to #187 for running the linters over the tools/* scripts too.
- Consistent import of `scipy.sparse` instead of `scipy`.
> Lint tools

- apis/python/setup.cfg
- apis/python/tests/test_or-query.py
Split out from #191.
Example:
```
$ peek-soma tiledb-data/pbmc-small
>>> soma.obs.df(attrs=['groups']).size
80
>>> soma.obs.query('groups == "g1"', attrs=['groups']).size
44
>>> soma.obs.query('groups == "g2"', attrs=['groups']).size
36
>>> soma.obs.query('groups == "g1" or groups == "g2"', attrs=['groups']).size
80
```
> Update to tiledb-py 0.16.0

- apis/python/setup.cfg
This brings in bugfix release https://pypi.org/project/tiledb/0.16.1 from `tiledb-py`.
> Update to tiledb-py 0.16.1

- apis/python/examples/uniformizer.py
- apis/python/tools/ingestor
- apis/python/tools/outgestor
Following great advice from @gsakkis 
To check:
* `tools/outgestor`
* `tools/outgestor -q`
* Make sure the first one prints progress updates and the latter does not
> Neaten logger-init code

- apis/python/doc/annotation_dataframe.md
- apis/python/doc/soma.md
- apis/python/doc/soma_collection.md
- apis/python/examples/soco-reconnaissance.md
- apis/python/src/tiledbsc/annotation_dataframe.py
- apis/python/src/tiledbsc/soma.py
- apis/python/src/tiledbsc/soma_collection.py
- apis/python/tests/test_or-query.py
These let people easily find cell-count that will be involved before running a query. For example:
```
import tiledbsc
soco = tiledbsc.SOMACollection('/mini-corpus/soco')
>>> [len(soma.obs) for soma in soco]
[264824, 4636, 6288, 2223, 59506, 100, 2638, 982538, 385, 67794, 2638, 104148, 44721, 3799, 11574, 1679, 3589, 700, 584884, 16245, 4603, 3726, 4636, 7348, 3589, 40268, 12971, 4232, 80, 82478, 97499, 38024]
>>> sum(len(soma.obs) for soma in soco)
2464363
```
```
>>> [soma.obs.query('cell_type == "B cell"').size for soma in soco if 'cell_type' in soma.obs.keys()]
[514982, 0, 0, 14283, 245240, 391446, 0, 0, 0, 125154, 0, 29060, 0, 0, 311259, 176, 6120, 2480, 0, 0, 0, 26325, 5220, 0, 12750, 0]
>>> sum([soma.obs.query('cell_type == "B cell"').size for soma in soco if 'cell_type' in …
```
> Expressive cell-count queries

- apis/python/doc/uns_group.md
- apis/python/src/tiledbsc/uns_group.py
- apis/python/tests/test_anndata_uns.py
```
>>> soma.uns
uns:
soma_encoding_version: '0'
soma_object_type: 'UnsGroup'
uns/neighbors:
soma_encoding_version: '0'
soma_object_type: 'UnsGroup'
uns/neighbors/params:
soma_encoding_version: '0'
soma_object_type: 'UnsGroup'
uns/neighbors/params/method/
['snn']
```
> Make soma.uns display by default in notebooks

- apis/python/examples/uniformizer.py
- apis/python/src/tiledbsc/logging.py
- apis/python/tools/ingestor
- apis/python/tools/outgestor
Ever since #186, data-ingestion in notebooks is silent by default, with no ready recourse. This is disturbing and unhelpful.
Here we retain silent-by-default, but we implement a one-liner, to be used in example notebooks, to give users a comforting reassurance that the ingestion cell is, indeed, "doing something".
> Make it easier to see progress indicators in notebook ingests

- apis/python/src/tiledbsc/annotation_matrix_group.py
- apis/python/src/tiledbsc/annotation_pairwise_matrix_group.py
- apis/python/src/tiledbsc/io.py
- apis/python/src/tiledbsc/raw_group.py
- apis/python/tests/test_add_layer.py
```
>>> soma.obsm.keys()
['X_tsne', 'X_pca']
```
```
>>> soma.obsm.add_layer_from_matrix_and_dim_values(soma.obsm.X_tsne.df(), soma.obs_keys(), 'voila')
```
```
>>> soma.obsm.keys()
['X_pca', 'X_tsne', 'voila']
>>> soma.obsm.voila.df()
X_tsne_1   X_tsne_2
obs_id
AAATTCGAATCACG -31.988231 -16.622181
AAGCAAGAGCTTAG  15.682430 -26.610128
AAGCGACTTTGACG -31.919623  -0.864304
AATGCGTGGACGGA  -1.839384  22.204006
AATGTTGACAGTCA  16.964273  -9.429598
...                   ...        ...
TTACGTACGTTCAG  41.689558  20.468961
TTGAGGACTACGCA -18.422789  22.004794
TTGCATTGAGCTAC  -6.034624   4.744967
TTGGTACTGAATCC   4.517332   8.024611
TTTAGCTGTACTCT  -3.208584  21.943824
[80 rows x 2 columns]
```
> Allow users to add new matrices to obsm,varm,obsp,varp

- apis/python/src/tiledbsc/annotation_dataframe.py
- apis/python/src/tiledbsc/annotation_matrix_group.py
- apis/python/src/tiledbsc/annotation_pairwise_matrix_group.py
- apis/python/src/tiledbsc/assay_matrix_group.py
- apis/python/src/tiledbsc/soma.py
- apis/python/src/tiledbsc/soma_collection.py
```
>>> soma
<tiledbsc.soma.SOMA object at 0x7f98d0b33b80>
```
```
>>> soma
Name:    pbmc-small
URI:     tiledb-data/pbmc-small
(n_obs, n_var): (80, 20)
X:       'data'
obs:     'orig.ident', 'nCount_RNA', 'nFeature_RNA', 'RNA_snn_res.0.8', 'letter.idents', 'groups', 'RNA_snn_res.1'
var:     'vst.mean', 'vst.variance', 'vst.variance.expected', 'vst.variance.standardized', 'vst.variable'
obsm:    'X_tsne', 'X_pca'
varm:    'PCs'
obsp:    'distances'
varp:
raw/X:   'data'
raw/var: 'vst.mean', 'vst.variance', 'vst.variance.expected', 'vst.variance.standardized', 'vst.variable'
uns:     neighbors
```
> Make a simple default display for SOMA objects in notebooks

- apis/python/src/tiledbsc/annotation_dataframe.py
- apis/python/src/tiledbsc/annotation_matrix.py
- apis/python/src/tiledbsc/assay_matrix.py
- apis/python/src/tiledbsc/soma_options.py
- apis/python/src/tiledbsc/uns_array.py
Following R impl at https://github.com/TileDB-Inc/tiledbsc/pull/69
> Disallow duplicates

- apis/python/src/tiledbsc/soma.py
- apis/python/src/tiledbsc/soma_collection.py
- apis/python/src/tiledbsc/soma_slice.py
Following on #199.
Setting `allow_duplicates=False` is the path of least surprise for users. This ensures that, if a matrix is ever re-written/updated, when people query, expecting a matrix of numbers, they'll get that -- vs a matrix of lists where each cell contains historical values.
However, this comes at some read-performance cost. The get-all-the-data timing queries done on #199 were insufficient; better queries are shown in the details below.
Using TileDB Core 2.10, which is released, we see about a 2x slowdown going to the 'safe' mode `allow_duplicates=False'. Using dev version of core with mods to be released in TileDB Core 2.11 (in a couple weeks) we see the slowdown more like 1.2x.
We took the same 59K cell (393M total) dataset, stored in four ways:
* `dupes-noconsol` -- …
> Optimize queries for allow_duplicates=False

- libtiledbsc/CMakeLists.txt
- libtiledbsc/cmake/Modules/FindTileDB_EP.cmake
- libtiledbsc/include/tiledbsc/column_buffer.h
- libtiledbsc/include/tiledbsc/managed_query.h
- libtiledbsc/include/tiledbsc/soma.h
- libtiledbsc/include/tiledbsc/tiledbsc
- libtiledbsc/include/tiledbsc/util.h
- libtiledbsc/src/CMakeLists.txt
- libtiledbsc/src/cli.cc
- libtiledbsc/src/column_buffer.cc
- libtiledbsc/src/managed_query.cc
- libtiledbsc/src/soma.cc
- libtiledbsc/src/util.cc
- libtiledbsc/test/CMakeLists.txt
- libtiledbsc/test/unit_column_buffer.cc
- libtiledbsc/test/unit_managed_query.cc
Add ManagedQuery class which provides a nice API for querying TileDB arrays.
Example code:
```c++
// Open SOMA
auto soma = SOMA::open(soma_uri);
// Create ManagedQuery for "obs" array
auto mq = ManagedQuery(soma.open_array("obs"));
// Select columns to materialize
mq.select_columns({"obs_id", "percent_mito"});
// Select dimension points and ranges to query
mq.select_points<std::string>("obs_id", {"AAACATACAACCAC-1"});
mq.select_ranges<std::string>(
"obs_id", {{"TTTCGAACTCTCAT-1", "TTTGCATGCCTCAC-1"}});
// Execute query and loop until complete (in case of an incomplete query)
while (auto num_cells = mq.execute()) {
// Get std::span view of "percent_mito" data
auto mito = mq.data<float>("percent_mito");
for (size_t i = 0; i < num_cells; i++) {
// Get string_view of "obs_id"
auto obs = …
```
> Add C++ ManagedQuery

- apis/python/src/tiledbsc/annotation_matrix_group.py
- apis/python/src/tiledbsc/annotation_pairwise_matrix_group.py
- apis/python/src/tiledbsc/soma_collection.py
- apis/python/src/tiledbsc/tiledb_group.py
- apis/python/tests/test_soco_ops.py
- apis/python/tests/test_soma_group_indexing.py
Python analog of https://github.com/TileDB-Inc/tiledbsc/pull/71
> Support group member deletion

- apis/python/src/tiledbsc/annotation_dataframe.py
- apis/python/src/tiledbsc/annotation_matrix.py
- apis/python/src/tiledbsc/annotation_matrix_group.py
- apis/python/src/tiledbsc/annotation_pairwise_matrix_group.py
- apis/python/src/tiledbsc/assay_matrix.py
- apis/python/src/tiledbsc/io.py
- apis/python/src/tiledbsc/logging.py
- apis/python/src/tiledbsc/raw_group.py
- apis/python/src/tiledbsc/tiledb_group.py
- apis/python/src/tiledbsc/uns_array.py
- apis/python/src/tiledbsc/uns_group.py
- apis/python/tools/ingestor
Logging ingests is crucial -- while some intro datasets take a few seconds to upload, gigascale data takes more time. During this time it's essential to give the user something to see, some indication that something is happen.
Before this PR, the log levels were silent, or verbose. During notebook/doc work this week I found the latter was taking up more than a full screen in notebook views -- which is overkill.
On this PR we strike a middle ground: `info` level gives a brief summary, with something every so often for the time-consuming bits (if any), but minimalistic in character-count. The old verbosity is still available using `tiledbsc.logging.debug()`.
Before-and-afters using `tiledbsc.logging.info()` in a notebook:
> Support quiet/info/debug levels for data ingest

- apis/python/src/tiledbsc/io.py
During notebook/doc work this week (see also the [public soma-testing notebook](https://cloud.tiledb.com/notebooks/details/johnkerl-tiledb/d3d7ff44-dc65-4cd9-b574-98312c4cbdbd/preview), I found myself skipping ingest for alread-uploaded data.
I suspect our users will be doing a lot of iffing unless we help them out with a way to express this common desire in a single line.
> Allow skip ingest if exists

- apis/python/setup.cfg
Brings in https://github.com/TileDB-Inc/TileDB-Py/releases/tag/0.16.2 which in turns brings in core https://github.com/TileDB-Inc/TileDB/releases/tag/2.10.2 which is a bugfix release.
> Depend on TileDB-Py 0.16.2

- apis/python/src/tiledbsc/tiledb_group.py
Found during today's notebook work.
Element deletion was working fine for local disk and S3, but not for TileDB Cloud; as of this PR it works for all three.
Note that we (intentionally) don't have tiledb-cloud unit-test cases in this repo -- although there are many local-disk cases. Nonetheless for the record here is a scenario:
```
>>> import tiledbsc
>>> soco = tiledbsc.SOMACollection('tiledb://johnkerl-tiledb/s3://tiledb-johnkerl/scratch/soco123')
>>> soma1 = tiledbsc.SOMA('tiledb://johnkerl-tiledb/pbmc3k_processed')
>>> soma2 = tiledbsc.SOMA('tiledb://johnkerl-tiledb/pbmc-small')
>>> soco.add(soma1)
>>> soco.add(soma2)
>>> soco.keys()
['pbmc3k_processed', 'pbmc-small']
>>> soco.remove(soma1)
>>> soco.keys()
['pbmc-small']
>>> del soco['pbmc-small']
>>> soco.keys()
[]
```
> Correctly support element deletion in TileDB Cloud

- apis/python/src/tiledbsc/raw_group.py
- apis/python/src/tiledbsc/soma.py
- apis/python/src/tiledbsc/soma_collection.py
- apis/python/src/tiledbsc/tiledb_group.py
- apis/python/src/tiledbsc/uns_group.py
- apis/python/tools/ingestor
Analysis for various read & write operations on `tiledb://...` URIs reveals that:
* Core-to-REST-server requests appear in things like `tiledb.object_type`, `tiledb.group.Group`, etc.
* These have server-side latency
* There are server-side optimizations we can do, certainly, but also on the client side we can _batch_ and _cache_:
* Getting group-element name-to-URI mappings takes about half a second per request whether we ask for one group member at a time, or for all group elements at once.
* Once we've gotten a name-to-URI mapping -- or a construction of an object which contains such -- we can cache the result to avoid subsequent, redundant requests (with, of course, cache-invalidation logic in the right places)
> Optimize constructor time for tiledb-cloud case

- apis/python/src/tiledbsc/tiledb_group.py
More performance optimization along the lines of #222.
Re the call to `exists()` in `_open()`:
* This was introduced on #126 to avoid a very confusing exception which only happened _before_ the with-open-as syntax was added to `TileDB-Py` on https://github.com/TileDB-Inc/TileDB-Py/pull/1124.
* But now, this `exists()` call can be completely omitted in with no negative effects: the exception wording is quite clear and appropriate now.
* This was a double-whammy since the `exists()` (no longer called here) was doing `tiledb.object_type()` which makes _two_ REST-server calls: open-array to return is-array (resulting in a 404 for us), and open-group to return is-group (resulting in a 200 for us). Now we avoid the 404 as well as the 200 (both of which had server-side time costs in auth).
Re …
> More REST-server call-avoidance

- apis/python/src/tiledbsc/soma_collection.py
> Do not throw on "in" check on unpopulated collection

- .github/workflows/ci.yml
Today CI jobs are being canceled for this, so it's time to move up.
See also https://github.com/TileDB-Inc/TileDB-Cloud-Py/pull/320 for prior art -- thanks @thetorpedodog ! :)
> Use macos-12 for CI due to GitHub brownout of macos-10.15

- apis/python/src/tiledbsc/soma_collection.py
Parallelize soma collection queries via threading. This works as a short term item for performance improvements. We have a number of additional changes in flight for Soma collections that will yield better and longer term improvements.
> Parallelize soma collection queries

- apis/python/src/tiledbsc/annotation_dataframe.py
- apis/python/src/tiledbsc/soma.py
- apis/python/src/tiledbsc/soma_collection.py
- apis/python/src/tiledbsc/soma_slice.py
The main point here is that the `query` method of `SOMACollection` doesn't make deep use of the `SOMACollection` object -- the latter is used there solely as a springboard to generate a list of `SOMA` objects. It ought to be possible to do a slice-query on a list of `SOMA` objects as well as a `SOMACollection`; it now is.
In addition to that code motion, a couple more thread-pool-executor experiments were tried; without significant benefit at this point as long as we're leveraging the (non-trivial) `to_anndata` and `anndata.concat` logic for slice-concatenation, as these appear to be pure Python and don't parallelize. (Future work on the `libtiledbsc` C++ library, as well as the upcoming `tiledbsoma` refactor, will make deeper use of Arrow along with GIL-releasing C++, and these will then …
> SOMA-list query option, and further thread-pool experiments

- apis/python/src/tiledbsc/soma.py
- apis/python/tests/test_add_layer.py
Going through @aaronwolen 's tutorial notebook and porting it to Python, I realize this crucial method needs to be simpler for the user to keystroke
> Keystroke-saver method for add-X-layer

- apis/python/src/tiledbsc/annotation_dataframe.py
Data written by `tiledbsc-py` or `tiledbsc-r` have compatible `obs` schemas -- for example:
```
ArraySchema(
domain=Domain(*[
Dim(name='obs_id', domain=(None, None), tile=None, dtype='|S0', var=True),
]),
attrs=[
Attr(name='orig.ident', dtype='ascii', var=True, nullable=False, filters=FilterList([ZstdFilter(level=-1), ])),
Attr(name='nCount_RNA', dtype='float64', var=False, nullable=False, filters=FilterList([ZstdFilter(level=-1), ])),
Attr(name='nFeature_RNA', dtype='int32', var=False, nullable=False, filters=FilterList([ZstdFilter(level=-1), ])),
Attr(name='seurat_annotations', dtype='ascii', var=True, nullable=False, filters=FilterList([ZstdFilter(level=-1), ])),
],
cell_order='row-major',
tile_order='row-major',
capacity=256,
sparse=True,
allows_duplicates=False,
)
```
however, …
> Set dataframe indices correctly on readback, if from R

- libtiledbsc/include/tiledbsc/logger_public.h
This switches to use the highlevel spdlog fmt includes which automatically handles if fmt is bundled or unbundled.
> Support fmt that is system installed with spdlog

- apis/python/src/tiledbsc/tiledb_group.py
- apis/python/src/tiledbsc/uns_array.py
- apis/python/tools/ingestor
Heretofore, `from_anndata` / `from_hd5` would fail if the SOMA already existed. Now, those can be used to update a SOMA..
Note: this was the plan all along; it was blocked by a missing `TileDB-Py` feature which is now deployed, so it's OK to move forward now.
> Support update-write of SOMAs

- scripts/bld
Build failed with
```
make[3]: *** No targets specified and no makefile found.  Stop.
```
which was because the build does `cd` to `build/libtilesbsc` which is an empty directory, while `cmake` outputs had been written to `libtiledbsc` rather than `build/libtiledbsc`, so `build/libtilebsc` was an empty directory.
Also note I found that in spite of this PR,  I needed to clean out `cmake` artifacts from `libtiledbsc` -- just a caveat for anyone else running into this issue.
> Fix for MacOS localhost build

- apis/python/src/tiledbsc/annotation_dataframe.py
No measured performance gain, but the syntax was unnecessary
> Query-syntax neaten in AnnotationDataFrame

- apis/python/src/tiledbsc/annotation_dataframe.py
- apis/python/src/tiledbsc/annotation_matrix.py
- apis/python/src/tiledbsc/assay_matrix.py
- apis/python/src/tiledbsc/soma.py
- apis/python/src/tiledbsc/soma_collection.py
- apis/python/src/tiledbsc/soma_slice.py
- apis/python/tests/test_soco_slice_query.py
Note that ingest-from-arrow is a separate issue and is not covered on this PR.
> Support return_arrow for various queries

- apis/python/examples/uniformizer.py
- apis/python/src/tiledbsc/__init__.py
- apis/python/tools/ingestor
- apis/python/tools/outgestor
The first screenshot is currently the default, and is less-good UX since it gives the user no idea about the ETA or progress or even liveness.
The second screenshot is currently only opt-in via `tiledbsc.logging.info()`, and is good UX.
This PR makes the good UX the default UX.
> tiledbsc.logging.info() by default for good uploader UX

- .github/workflows/ci.yml
- .github/workflows/cpp-ci.yml
- apis/python/pyproject.toml
- apis/python/setup.py
- apis/python/src/tiledbsc/__init__.py
- libtiledbsc/src/CMakeLists.txt
- libtiledbsc/src/pyapi/CMakeLists.txt
- libtiledbsc/test/test_simple.py
- libtiledbsc/test/test_soma.py
- scripts/bld
- scripts/test
Build and install the `libtiledbsc` native library as part of the pip install process.
* Local non-editable install: `pip install .`
* Local editable install: `pip install -e .`
The `./scripts/bld` script is reused for pip install, CI, and local builds.
> Build and install libtiledbsc with pip install

- .github/workflows/ci.yml
FIxing https://github.com/single-cell-data/TileDB-SingleCell/pull/261 which did not change from `ubuntu-latest` to `ubuntu-22.04` in all places
This was causing https://pypi.org/project/tiledbsc/ to not see new releases
I'll delete the 0.1.9 tag and re-create it
cc @gspowley
> Unbreak PyPI release

- .github/workflows/ci.yml
- scripts/bld
https://github.com/single-cell-data/TileDB-SingleCell/runs/8059247274?check_suite_focus=true
```
Checking dist/bin: ERROR    InvalidDistribution: Unknown distribution format: 'bin'                
```
Before https://github.com/single-cell-data/TileDB-SingleCell/pull/261 the command
```
python -m pip wheel --no-deps --wheel-dir=dist apis/python
```
created only
```
dist/tiledbsc-0.1.x-cp310-cp310-linux_x86_64.whl
```
but now there is
```
$ ls -l dist
total 776
drwxrwxr-x 2 ubuntu ubuntu   4096 Aug 22 22:11 bin
drwxrwxr-x 3 ubuntu ubuntu   4096 Aug 22 22:11 include
drwxrwxr-x 2 ubuntu ubuntu   4096 Aug 22 22:11 lib
-rw-r--r-- 1 root   root   781539 Aug 28 17:24 tiledbsc-0.1.9-cp310-cp310-linux_x86_64.whl
$ ls -l dist/*
-rw-r--r-- 1 root   root   781539 Aug 28 17:24 …
```
> Continuing to try to fix PyPI CI with libtiledbsc

- scripts/setup
I got an error while running this with a missing dependency -- we should die at the right time to give the right error, rather than failing less clearly later on.
This PR is for the `main` branch; #284 is for the `main-v0` branch.
> Check for errors on scripts/setup

- apis/python/src/tiledbsoma/soma_collection.py
- apis/python/src/tiledbsoma/soma_dataframe.py
- apis/python/src/tiledbsoma/soma_dense_nd_array.py
- apis/python/src/tiledbsoma/soma_experiment.py
- apis/python/src/tiledbsoma/soma_indexed_dataframe.py
- apis/python/src/tiledbsoma/soma_measurement.py
- apis/python/src/tiledbsoma/soma_sparse_nd_array.py
Found by @gspowley while he was working hard on C++/`libtiledbsoma` which is a priority, and the bug caused him some confusion. Let's make better use of developer time by behaving in a Pythonic way.
Before: inconsistent:
```
>>> exp = tiledbsoma.SOMAExperiment('tiledb-data/pbmc-small')
>>> exp.nonesuch
File "<stdin>", line 1, in <module>
File "/home/ubuntu/git/single-cell-data/TileDB-SOMA/apis/python/src/tiledbsoma/soma_experiment.py", line 71, in __getattr__
raise AttributeError(f"{self.__class__.__name__} has no attribute '{name}'")
AttributeError: unrecognized attribute: nonesuch
>>> type(exp.obs.nonesuch)
<class 'NoneType'>
>>> exp.ms.nonesuch
File "<stdin>", line 1, in <module>
File …
```
> Make __getattr__ Pythonic on key-not-found

- apis/python/src/tiledbsoma/io.py
It's all too easy to type `tiledbsoma.from_h5ad(soma, adata)` -- here we offer an explicit type-check along with a suggested course of action.
> Error-check types on from_anndata/from_h5ad

- libtiledbsoma/CMakeLists.txt
- libtiledbsoma/src/CMakeLists.txt
- libtiledbsoma/src/pyapi/CMakeLists.txt
- libtiledbsoma/test/CMakeLists.txt
- scripts/bld
This is in the context of SC 21583. After an extended debug session, these are mods worth keeping, as quality-of-life improvements. This is opt-in via the two environment variables checked at the top of `scripts/bld`.
> Enable option for enhancing debug-log visibility

- apis/python/src/tiledbsoma/io.py
- apis/python/src/tiledbsoma/util_ann.py
- apis/python/tests/test_anndata_layers.py
DIscovered today in collaboration with @aaronwolen doing data prep.
All along, this is where `AnnData` keeps its additional `X` layers. We should ingest them all.
> Correctly ingest multiple AnnData X layers

- apis/python/src/tiledbsoma/soma_dataframe.py
- apis/python/src/tiledbsoma/soma_indexed_dataframe.py
- apis/python/src/tiledbsoma/util_tiledb.py
- apis/python/tests/test_soma_dataframe.py
- apis/python/tests/test_soma_indexed_dataframe.py
Fixes #312 
Changes:
* add unit test exercising expected behavior for SOMADataFrame and SOMAIndexedDataFrame read ops
* add utility function to split column names into dims / attrs so that they may be correctly passed to the underlying tiledb.Array query
* remove the `soma_rowid` column suppression in SOMADataFrame.read_as_pandas*
* remove the `soma_rowid` attribute creation in SOMAIndexedDataframe create
*Note:* SOMAIndexedDataFrame read_as_pandas/read_as_pandas_all is unimplemented, and the corresponding tests are disabled until such time as the methods exist.
> improve column_name handling in dataframe read operations

- apis/python/src/tiledbsoma/util_tiledb.py
An earlier PR missed some double-backtics in docstrings.
> add missing double backtick

- apis/python/setup.cfg
> Depend on TileDB-Py 0.17.4

- apis/python/src/tiledbsoma/io.py
- apis/python/src/tiledbsoma/soma_collection.py
- apis/python/src/tiledbsoma/soma_dataframe.py
- apis/python/src/tiledbsoma/soma_dense_nd_array.py
- apis/python/src/tiledbsoma/soma_experiment.py
- apis/python/src/tiledbsoma/soma_indexed_dataframe.py
- apis/python/src/tiledbsoma/soma_measurement.py
- apis/python/src/tiledbsoma/soma_sparse_nd_array.py
- apis/python/src/tiledbsoma/tiledb_array.py
- apis/python/src/tiledbsoma/tiledb_object.py
- apis/python/src/tiledbsoma/types.py
- apis/python/src/tiledbsoma/util_arrow.py
- apis/python/tests/__init__.py
- apis/python/tests/test_soma_collection_basic.py
- apis/python/tests/test_soma_dense_nd_array.py
- apis/python/tests/test_soma_experiment_basic.py
- apis/python/tests/test_soma_sparse_nd_array.py
- apis/python/tests/test_type_system.py
- apis/python/tools/ingestor
First of several PRs to update NdArray to match the spec. Breaking into smaller PRs for easier review.
This PR focuses on create/schema issues and the mapping between Arrow and TileDB type systems. It also cleans up the property API (eg, `shape`) to be more pythonic and fix issues preventing static code analysis by mypy.
Fixes #337
Partial fix for #330 (more work to be done)
Changes:
* Revised utility `get_arrow_type_from_tiledb_dtype` to correctly handle Arrow types which can be expressed in TileDB, but which were not correctly being handled by the previous implementation.
* Added test case for the type system conversion (anndata->tiledb and tiledb->anndata)
* Various properties (shape, ndim, etc) were implemented with a specialized __getattr__ method, rather than the more Python use of …
> NdArray implementation work (create, props)

- apis/python/setup.py
The `main` branch has C++ working well with `pip install`.
On the `main-old` branch though this does not succeed. This in turn is one reason we have a doc-build fail at https://readthedocs.com/projects/tiledb-inc-tiledb-soma/builds/.
> Suppress C++ build for old branch

- .readthedocs.yml.pending
Currently readthedocs should publish from `main-old` (there will be a separate PR on that branch for fixups).
> No readthedocs build on main for now

- libtiledbsoma/src/soma_reader.cc
The `timestamp()` accessor is deprecated, replacing it with `open_timestamp_end()` is recommended in the header.
> Replace array->timestamp() with array->open_timestamp_end()

- libtiledbsoma/src/pyapi/CMakeLists.txt
Up until now:
* On Linux, without core in `/usr/local`, builds fine
* On Mac, without core in `/usr/local`, builds fine
* On Linux, with core in `/usr/local`, builds fine
* On Mac, with core in `/usr/local`, build fails with
```
/Users/johnkerl/git/single-cell-data/TileDB-SOMA/libtiledbsoma/src/pyapi/../../include/tiledbsoma/logger_public.h:41:10: fatal error: 'spdlog/spdlog.h' file not found
#include <spdlog/spdlog.h>
^~~~~~~~~~~~~~~~~
1 error generated.
```
This is a crucial ability for any developers on MacOS (which is several of us).
Fixed after long debug with the incomparable @ihnorton :D
> Fix MacOS build with local TileDB core

- apis/python/src/tiledbsoma/soma_collection.py
The SOMACollection __getitem__ will raise a KeyError incorrectly whencreating any object that is specialized from SOMACollection (eg, SOMAExperiment).
This is due to a bug in the __getitem__ logic checking for create failures in _construct_factory.  It checked for a falsey value, rather than check explicitly for None.  Any SOMACollection or SOMACollection subclass will now tests falsey if it is empty, as it obeys the Colleciton ABC API (empty collections are falsey)
> SOMACollection: fix loose check in create logic

- apis/python/src/tiledbsoma/soma_dense_nd_array.py
- apis/python/src/tiledbsoma/soma_sparse_nd_array.py
- apis/python/tests/test_soma_dense_nd_array.py
- apis/python/tests/test_soma_sparse_nd_array.py
Fixes #297 
TileDB does not support zero-length domains for a dimension.  Add error check and raise a meaningful exception.
> add error check for zero length dimensions in ndarray

- .github/workflows/ci.yml
Temporarily revert https://github.com/single-cell-data/TileDB-SOMA/pull/366
I knew (but had forgotten) that now that we have C++ `libtiledbsoma` we need a 'source wheel' and this is why PyPI CI is failing.
After we fix the 'source wheel' issue we can then re-enable PyPI publishing on `main`.
> Pause PyPI publish on main

- .github/workflows/cpp-ci.yml
As detailed at
https://github.com/actions/runner-images/issues/6350
There don't appear (in my googling so far anyway) to be good options besides 'downgrade' :disappointed: so this is my best attempt at present
> Work around recent Mac GHA issue

- .github/workflows/ci.yml
- .github/workflows/cpp-ci.yml
- libtiledbsoma/test/CMakeLists.txt
Follow-on from #354 
For MacOS with TileDB in `/usr/local`,  #354 makes `pip install -e apis/python` succeed.
This PR makes `./scripts/test` succeed.
> Fix scripts/test for MacOS

- apis/python/src/tiledbsoma/soma_indexed_dataframe.py
- apis/python/tests/test_soma_indexed_dataframe.py
Previously `numpy.iinfo` was used to retrieve the range of all non-string dtypes when constructing a `SOMAIndexedDataFrame`. Now `numpy.iinfo` is only used for integer dtypes and `numpy.finfo` is used for floating point dtypes.
> Fix for SOMAIndexedDataFrames with float dims

- apis/r/DESCRIPTION
- apis/r/cleanup
- apis/r/configure
- apis/r/src/Makevars.in
- apis/r/tools/get_tarball.R
- libtiledbsoma/cmake/Modules/FindTileDB_EP.cmake
This PR generalizes the build setup for the R package to use _either_ a system-wide installation of TileDB Core for the C++ headers and library, and a dowloaded artifact.  
This (loosely) follows the behavior of the `tiledb` R package on CRAN.  
It has been tested with system-wide TileDB and without (in Docker and on CI).  Tests in CI for macOS are not yet feasible as that setup appears to lack sufficient C++20 support.  Actual CI support may be added in a subsequent PR.
> [r] Support build against external artifact and system library

- libtiledbsoma/include/tiledbsoma/managed_query.h
- libtiledbsoma/include/tiledbsoma/soma_reader.h
- libtiledbsoma/src/managed_query.cc
- libtiledbsoma/src/pyapi/libtiledbsoma.cc
- libtiledbsoma/src/soma_reader.cc
- libtiledbsoma/test/CMakeLists.txt
- libtiledbsoma/test/test_query_condition.py
- libtiledbsoma/test/test_soma_reader.py
- libtiledbsoma/test/unit_managed_query.cc
- libtiledbsoma/test/unit_soma_reader.cc
Add fast nnz to C++ API, as discussed in #383:
* if one fragment, there are no dups, so use cell_num
* if multiple, non-overlapping fragments, sum fragment cell_num
* if overlapping fragments, read/count the overlapping fragments
Closes #383.
> [c++] Add fast nnz

- apis/python/src/tiledbsoma/soma_dataframe.py
- apis/python/src/tiledbsoma/soma_indexed_dataframe.py
the SOMADataFrame and SOMAIndexedDataFrame `read_as_pandas_all` was returning a malformed index with repeated values. It should be a simple range index from [0, len), but was in instead the original (partial read) dataframe indices concatenated.
End result was that the index had repeated values (eg, index zero would show up many times).  Here is an example - note how the index and soma_rowid (and total number of rows) are not consistent:
```
In [15]: %time census['human'].obs.read_as_pandas_all(column_names=['soma_rowid', 'soma_joinid', 'dataset_id', 'assay_ontology_term_id', 'cell_type_ontology_term_id', 'development_stage_ontology_term_id', 'disease_ontology_term_id', 'et
...: hnicity_ontology_term_id', 'organism_ontology_term_id', 'sex_ontology_term_id', 'tissue_ontology_term_id']) …
```
> fix index in pandas read all

- apis/python/src/tiledbsoma/util_arrow.py
- apis/python/src/tiledbsoma/util_scipy.py
- apis/python/tests/test_type_system.py
Context: #405
Fantastic unit-testing was added by @bkmartinjr on #407 which was merged into this PR.
Issue (for the record): `bytes` and `ascii` both read back with `np.dtype("S") == "bytes"`. We need to use either `attr._tiledb_dtype` or `attr.isascii` when reading TileDB schema, to determine which Arrow schema type (`large_binary` or `large_string`) to report.
> Disambiguate bytes/ascii on tiledb schema -> arrow schema

- libtiledbsoma/include/tiledbsoma/soma_reader.h
This PR exposes two existing functions from `managed_query` one level higher up in the `soma_reader` to, respectively, access the underlying schema and select columns (if one hasn't at instantiation) which matches the row setters.
> [c++] Expose two functions from managed_query in soma_reader

- apis/python/tests/test_soma_indexed_dataframe.py
- apis/python/tests/test_unicode.py
This PR adds unit tests for issues #415, #418 and #419.
NOTE: all tests are marked `xfail`, until such time as the issues are resolved.
> add unit tests for issues 415, 418, 419

- apis/r/configure
- apis/r/prune_libtilesoma_sources.sh
- apis/r/src/Makevars.in
- apis/r/tests/testthat/test_SOMASparseNdArray.R
- libtiledbsoma/CMakeLists.txt
- libtiledbsoma/include/externals/span/span.hpp
- libtiledbsoma/include/tiledbsoma/array_buffers.h
- libtiledbsoma/include/tiledbsoma/column_buffer.h
- libtiledbsoma/include/tiledbsoma/managed_query.h
- libtiledbsoma/include/tiledbsoma/soma_reader.h
- libtiledbsoma/include/tiledbsoma/util.h
- libtiledbsoma/src/pyapi/libtiledbsoma.cc
This (draft) PR lowers our C++ compilation standard from C++20 (which works well on Linux and modern macOS) to C++17 (which should permit CI on macOS under the R setup, ditto for windows) and would close #353.  
It does two fairly simple things:
- replaces uses of `std::span` (which C++20 or later only) with [tcb::span](https://github.com/tcbrindle/span) (as TileDB Core does)
- switches the instantiation from `std::span` to `tcp::span`
- switches the include to `externals/span/span.hpp` 
- adds a new header directory `includes/externals/`
- changes a single `contains()` for `unordered_map` (also C++20 or later) to `find() != end()`   
It also switches the R package to then use C++17.  Tests pass for me on R.
This should be considered a proposal-only.  I am not that deep into `cmake` etc …
> Use C++17 to ease build requirements 

- .github/workflows/ci.yml
- .github/workflows/cpp-ci.yml
On #354 we got MacOS CI working in the presence of an XCode 14 linker bug by downgrading to MacOS 11. As discussed at https://github.com/actions/runner-images/issues/6350, we can stay on MacOS 12 but force XCode 13.4 (non-buggy).
Also, it's not a bad idea or a bad time to use Python 3.9 for CI (we have been using 3.8, which is now in a 'security fixes only' phase).
Note that if/when this PR is accepted, I'll switch the required builds in the branch-protection rules for this repo to require 3.9 passes rather than 3.8 (as now).
> Use MacOS 12 for CI

- .github/workflows/r-ci.yml
- apis/r/DESCRIPTION
- apis/r/configure
- apis/r/tests/testthat/test-SOMADataFrame.R
- apis/r/tests/testthat/test-SOMAIndexedDataFrame.R
- apis/r/tests/testthat/test_SOMASparseNdArray.R
- apis/r/tools/get_tarball.R
- apis/r/tools/r-ci.sh
This (draft) PR adds continuous integration via GitHub Actions.  It is (at least for now) intentionally limited to Linux as the standard R setup on macOS cannot compile under C++20 (see #353 on that), and it also skips Windows.
For now two existing test files are skipped to expediate ensuring the overall mechanics of gettings dependencies including TileDB artifacts as well as source from `libtiledbsoma` setup to work.  The PR is marked as draft until we know what is going on with the two other tests which work for me locally. 
The script used for CI setup is borrowed from both tiledb-r and tiledbcloud-r.
> [r] Add Continuous Integration for the R package

- .github/workflows/ci.yml
- apis/python/src/tiledbsoma/__init__.py
- apis/python/src/tiledbsoma/query_condition.py
- libtiledbsoma/CMakeLists.txt
- libtiledbsoma/src/pyapi/libtiledbsoma.cc
- libtiledbsoma/src/pyapi/query_condition.cc
- libtiledbsoma/src/soma_reader.cc
- scripts/bld
- scripts/show-versions.py
This contains some pieces from #439 (see also #443) which are not dependent on the upcoming core 2.12 release.
> Internal context-handling updates

- apis/r/configure
This PR corrects an oversight and ensure `R_HOME` is always set whereever `configure` may need it.
> Correct configure by ensuring R_HOME is set early

- apis/python/src/tiledbsoma/query_condition.py
- libtiledbsoma/src/pyapi/libtiledbsoma.cc
- libtiledbsoma/test/test_query_condition.py
Based on https://github.com/TileDB-Inc/TileDB-Py/pull/1333, remove the requirement to add attributes used in query conditions to the `SOMAReader` `column_names`.
> [c++] Do not require query condition columns in column_names

- libtiledbsoma/src/pyapi/libtiledbsoma.cc
Support passing `column_names=None` to `SOMAReader` in python.
> [c++] Support passing column_names as None

- .github/workflows/ci.yml
- .github/workflows/cpp-ci.yml
- .github/workflows/format.yml
- .github/workflows/r-ci.yml
This PR update the yml files from version two to version three of the core checkout action and thereby suppresses a nag displayed about node.js version 12 soon going away.
> [ci] Update to checkout/actions@v3 to suppress nag about node.js 12

- apis/python/README-ingestion.md
- apis/python/src/tiledbsoma/annotation_matrix_group.py
- apis/python/src/tiledbsoma/annotation_pairwise_matrix_group.py
- apis/python/src/tiledbsoma/assay_matrix_group.py
- apis/python/src/tiledbsoma/soma_collection.py
- apis/python/src/tiledbsoma/tiledb_group.py
- apis/python/src/tiledbsoma/uns_group.py
- apis/python/tests/test_soco_ops.py
- apis/python/tests/test_soma_group_indexing.py
The idiom `[soma.uri for soma in soco]` is marvelously expressive but instantiates each `SOMA`. This is parallelized via `TheadPoolExecutor` but even then with remotely stored data the overhead can be undesirable.
There is a `soco._get_member_uris` which _only_ consults the group meta for the parent `SOMACollection`, and is almost instantaneous. This should be made a first-class citizen, as it does only what the user wants (no more) and is much more performant.
> Expose a faster method for member-URI enumeration

- apis/python/src/tiledbsoma/annotation_matrix_group.py
- apis/python/src/tiledbsoma/annotation_pairwise_matrix_group.py
- apis/python/src/tiledbsoma/uns_group.py
The `to_anndata` method says "writing" or "wrote" when it should say "reading" or "read". With this PR:
```
>>> soma = tiledbsoma.SOMA('/Users/johnkerl/s/t/pbmc-small')
```
```
>>> tiledbsoma.logging.info()
>>> tiledbsoma.io.to_anndata(soma)
data
Read pbmc-small/obsm
Read pbmc-small/varm
distances
Read pbmc-small/obsp
Read pbmc-small/varp
data
Read pbmc-small/raw/varm
Read pbmc-small/uns/neighbors/params
Read pbmc-small/uns/neighbors
Read pbmc-small/uns
AnnData object with n_obs × n_vars = 80 × 20
obs: 'orig.ident', 'nCount_RNA', 'nFeature_RNA', 'RNA_snn_res.0.8', 'letter.idents', 'groups', 'RNA_snn_res.1'
var: 'vst.mean', 'vst.variance', 'vst.variance.expected', 'vst.variance.standardized', 'vst.variable'
uns: 'neighbors'
obsm: 'X_tsne', 'X_pca'
varm: 'PCs'
obsp: 'distances'
```
```
>>> …
```
> Wording-neaten for to_anndata with logging

- libtiledbsoma/src/pyapi/libtiledbsoma.cc
- libtiledbsoma/test/test_soma_reader.py
Accept dim_points as `pyarrow.Array`, not just `pyarrow.ChunkedArray`.
Closes #497.
> [c++] Accept dim_points as pyarrow.Array

- apis/python/src/tiledbsoma/annotation_dataframe.py
- apis/python/src/tiledbsoma/annotation_matrix.py
- apis/python/src/tiledbsoma/annotation_matrix_group.py
- apis/python/src/tiledbsoma/annotation_pairwise_matrix_group.py
- apis/python/src/tiledbsoma/assay_matrix.py
- apis/python/src/tiledbsoma/io.py
- apis/python/src/tiledbsoma/raw_group.py
- apis/python/src/tiledbsoma/tiledb_group.py
- apis/python/src/tiledbsoma/uns_array.py
- apis/python/src/tiledbsoma/uns_group.py
- apis/python/tests/test_basic_anndata_io.py
- apis/python/tools/outgestor
Before:
```
>>> tiledbsoma.io.to_anndata(tiledbsoma.SOMA('tiledb://johnkerl-tiledb/pbmc-small'))
9c04b575-3e82-4b2b-b92b-cc2a5bad15bc
Read pbmc-small/obsm
Read pbmc-small/varm
dcfab2d6-b62a-4854-abf5-47652c305b25
Read pbmc-small/obsp
Read pbmc-small/varp
651eec7e-64ff-400c-91d3-66edb8133ff7
Read pbmc-small/raw/varm
Read pbmc-small/uns/eb28e180-dc88-43d2-8eaa-020cd08716ad/0ef47a66-077f-46b6-8c31-3cb36c518c34
Read pbmc-small/uns/eb28e180-dc88-43d2-8eaa-020cd08716ad
Read pbmc-small/uns
AnnData object with n_obs × n_vars = 80 × 20
obs: 'orig.ident', 'nCount_RNA', 'nFeature_RNA', 'RNA_snn_res.0.8', 'letter.idents', 'groups', 'RNA_snn_res.1'
var: 'vst.mean', 'vst.variance', 'vst.variance.expected', 'vst.variance.standardized', 'vst.variable'
uns: 'eb28e180-dc88-43d2-8eaa-020cd08716ad'
obsm: …
```
> Correct element names on to_anndata for tiledb-cloud URIs

- .github/workflows/r-ci.yml
- apis/r/tools/r-ci.sh
This PR enables code coverage for the R package and submits the report under flag 'r' with the repo token for codecov.io.
The actual coverage analysis is provided by the widely-used CRAN package [covr](https://cloud.r-project.org/package=covr) which is loaded when coverage is requested (when running on Linux).
> [r] Add coverage reports in script and yaml

- apis/python/setup.cfg
- apis/python/setup.py
Not to be merged until `TileDB-Py` 0.18.1 appears in Conda:
https://anaconda.org/conda-forge/tiledb-py
> Depend on TileDB-Py 0.18.1 [main-old]

- apis/python/setup.cfg
- apis/python/setup.py
Not to be merged until TileDB-Py 0.18.1 appears in Conda:
https://anaconda.org/conda-forge/tiledb-py
> Depend on TileDB-Py 0.18.1 [main]

- apis/python/src/tiledbsoma/soma.py
These two are independent of one another and may be run in parallel.
For a very small SOMA and small query sizes, this takes the total `soma.query` time (averaged over 10 trials of before and after) from 5.7 seconds to 3.8 seconds.
For a larger SOMA and larger query sizes, the difference was not noticeable with variation of query times.
> Parallelize obs & var within soma.query

- apis/r/R/TileDBArray.R
- apis/r/R/utils-arrow.R
- apis/r/tests/testthat/test-Arrow-utils.R
This adds internal helpers for converting TileDB dimensions, attributes, and schemas to their Arrow equivalents. We'll use these in a future PR to return Arrow schemas from the foundational classes.
Also tweaked `TileDBArray$dimensions()` to return a named list, which matches the behavior of `TileDBArray$attributes()`.
> [r] Arrow conversion utilities

- apis/r/DESCRIPTION
- apis/r/NEWS.md
- apis/r/R/SOMACollection.R
This implements @dan11mcguire's fix for https://github.com/TileDB-Inc/tiledbsc/issues/82. Previously we were implicitly using Seurat's default name for the first assay created by `to_seurat()`. Now we always explicitly supply an assay name from the corresponding SOMA.
> Don't use default assay name for Seurat objects

- libtiledbsoma/src/pyapi/libtiledbsoma.cc
- libtiledbsoma/test/test_soma_reader.py
This PR provides python/C++ bindings to control the internal TileDB stats collection.
* The python bindings should be wrapped with python functions/docstrings for inclusion in the API docs.
* Similar functions can be implemented in R.
New libtiledbsoma python functions:
```python
import tiledbsoma.libtiledbsoma as clib
clib.stats_enable()
clib.stats_disable()
clib.stats_reset()
clib.stats_dump()
```
Example output:
```
libtiledbsoma=faa9021-modified
libtiledb=2.12.0
[
{
"timers": {
"Context.StorageManager.subSubarray.read_load_relevant_rtrees.sum": 0.000191879,
"Context.StorageManager.subSubarray.read_load_relevant_rtrees.avg": 2.74113e-05,
"Context.StorageManager.subSubarray.read_compute_tile_overlap.sum": 0.00102588,
"Context.StorageManager.subSubarray.read_compute_tile_overlap.avg": …
```
> [c++] Enable internal TileDB stats collection

- Makefile
- libtiledbsoma/CMakeLists.txt
- libtiledbsoma/README.md
- libtiledbsoma/cmake/Modules/FindTileDB_EP.cmake
- libtiledbsoma/test/test_soma_reader.py
- scripts/bld
Update build scripts based on more feedback, including better support for building with a custom build of TileDB.
```
Usage: make rule [options]
Rules:
install [options]   Build C++ library and install python module
r-build [options]   Build C++ static library with "#define R_BUILD" for R
update              Incrementally build C++ library and update python module
test                Run tests
clean               Remove build artifacts
Options:
build=BUILD_TYPE    Cmake build type = Release|Debug|RelWithDebInfo|Coverage [Release]
prefix=PREFIX       Install location [dist]
tiledb=TILEDB_DIST  Absolute path to custom TileDB build 
Examples:
Install Release build
make install
Install Debug build of libtiledbsoma and libtiledb
make install build=Debug
Install Release build with custom …
```
> [c++] Improve build experience

- apis/python/src/tiledbsoma/dataframe.py
- apis/python/src/tiledbsoma/indexed_dataframe.py
- apis/python/src/tiledbsoma/sparse_nd_array.py
For the Python package, add a temporary means of configuring the SOMAReader via the `ctx` support.
This enables configuration to be passed to the C++ reader:
```
df = soma.IndexedDataFrame(uri, ctx=tiledb.Ctx({"vfs.s3.region": "us-west-2"})
df.read_as_pandas_all()
```
This will be superseded by the upcoming context/platform_config work.
> add temporary configuration to SOMAReader instances

- apis/r/DESCRIPTION
- apis/r/R/AssayMatrix.R
- apis/r/R/TileDBObject.R
Larger-scale queries (in the megacell range) have revealed an opportunity to more closely align tile capacity with remote-read performance.
This PR ports #533 from Python to R on `main-old`.
> [r] Use X_capacity=1000 to optimize reads

- apis/r/DESCRIPTION
- apis/r/NEWS.md
- apis/r/R/AnnotationMatrix.R
- apis/r/R/AssayMatrix.R
- apis/r/R/SOMA.R
- apis/r/R/SOMACollection.R
- apis/r/R/TileDBArray.R
- apis/r/man/AnnotationMatrix.Rd
- apis/r/man/SOMA.Rd
- apis/r/man/SOMACollection.Rd
- apis/r/tests/testthat/test_AnnotationMatrix.R
This PR expands batched reader support to the `AnnotationMatrix` class. It's off by default but can be enabled with the `batch_mode` argument that was added to the `to_matrix()` method.
> [r] Expand batched reader support to AnnotationMatrix arrays

- apis/python/src/tiledbsoma/tiledb_array.py
Scenario:
* Append-to-single-soma ingestion contexts
* Some configs are present only in `ctx` and not in the shell environment
* After successful schema-only ingest, the data-ingest fails [here](https://github.com/single-cell-data/TileDB-SOMA/blob/93855155949ee97b222877bdb9e1268bbaf474a2/apis/python/src/tiledbsoma/annotation_dataframe.py#L378) because the array-exists method [here](https://github.com/single-cell-data/TileDB-SOMA/blob/93855155949ee97b222877bdb9e1268bbaf474a2/apis/python/src/tiledbsoma/tiledb_array.py#L44) is not using the `self._ctx` as it should
This PR fixes that.
> Apply ctx to tiledb.array_exists

- codecov.yml
The code coverage analysis also descends into a directory containing headers from TileDB Core which are not part of this repo, and should be excluded from coverage analysis.  Setting an `ignore:` directive achieves this.
No code changes in this PR.
> [r] Ignore directory with TileDB Core headers in coverage analysis

- apis/r/src/rinterface.cpp
- apis/r/src/riterator.cpp
- apis/r/src/rutilities.cpp
This PR updates the logging code to using the recently-enhanced versions offering templated access which alleviates the (explicit but wordier) use of the `fmt::format()` layer. 
No code changes in this PR.
> [r] Update logging code utilizing templated interface

- apis/python/src/tiledbsoma/tiledb_group.py
See the comments at
https://github.com/single-cell-data/TileDB-SOMA/blob/0f9aac4c5e2f9eb939262e210fca68895b1d7fb8/apis/python/src/tiledbsoma/tiledb_group.py#L237-L244
which tell the whole story:
```
```
Re-writing the URIs here was a convenience; however, for append-mode ingests, it can be error-prone -- when the soma object is already instantiated, and a schema-only ingest has been done with `schema_only=True`, the user will need to come back and ingest data with `schema_only=False` and the pre-creation URI needs to still be in place.
> Do not rewrite pre-creation URI to post-creation URI

- apis/python/src/tiledbsoma/dataframe.py
- apis/python/src/tiledbsoma/dense_nd_array.py
- apis/python/src/tiledbsoma/io.py
- apis/python/src/tiledbsoma/sparse_nd_array.py
- apis/python/src/tiledbsoma/tiledb_platform_config.py
- apis/python/src/tiledbsoma/types.py
- apis/python/tests/test_platform_config.py
This adds a `platform_config` parameter, which allows a user to tune options relating to the creation of their TileDB array.
The structure of the data it expects can be described with this TypeScript specification:
```typescript
interface PlatformConfig {
tiledb?: TDBConfig;
}
interface TDBConfig {
create?: TDBCreateOptions;
}
interface TDBCreateOptions {
dims?: { [dim: string]: TDBDimension };
attrs?: { [attr: string]: TDBAttr };
offsets_filters?: TDBFilter[];
capacity?: number;
cell_order?: string;
tile_order?: string;
}
interface TDBDimension {
filters?: TDBFilter[];
tile?: number;
}
interface TDBAttr {
filters?: TDBFilter[];
}
/**
* Either the name of a filter (in which case it will use
* the default arguments) or a specification with filter args.
*/
type TDBFilter = string | …
```
> Add the `platform_config` parameter to create methods.

- apis/r/R/RcppExports.R
- apis/r/man/SOMADataFrame.Rd
- apis/r/man/sr_setup.Rd
- apis/r/src/RcppExports.cpp
- apis/r/src/riterator.cpp
This PR extend the 'iterating reader' to accept an optional argument `config`: a (standard R) named character vector for `key=value` pairs used to seed the `platform_config` map.  This now permits to set configuration values.  Here is an example of turning logging one by passing `config=c("config.logging_level" = "5")`:
```sh
$ ./quickCheck.R 
[2022-11-18 17:24:38.034] [Process: 2773728] [info] [1668813877360419015-Context: 2] [Query: 1] [DenseReader: 1] using cache
[2022-11-18 17:24:38.274] [Process: 2773728] [info] [1668813877360419015-Context: 2] [Query: 1] [DenseReader: 1] using cache
[2022-11-18 17:24:38.355] [Process: 2773728] [info] [1668813877360419015-Context: 2] [Query: 1] [DenseReader: 1] using cache
[2022-11-18 17:24:38.543] [Process: 2773728] [info] …
```
> [r] Extend iterated reader interface with platform_config

- apis/python/tests/test_dataframe.py
- apis/python/tests/test_type_system.py
- libtiledbsoma/include/tiledbsoma/arrow_adapter.h
Problem: `TILEDB_BOOL` is stored as a `uint8_t`, while Arrow uses 1-bit `bool`. 
Solution: Overwrite the `ColumnBuffer`'s bytemap in-place with its corresponding byte-aligned bitmap.
Test case:
```python
import os
import shutil
import numpy as np
import pandas as pd
import pyarrow as pa
import tiledbsoma as soma
import tiledbsoma.libtiledbsoma as clib
uri = "489"
if os.path.exists(uri):
shutil.rmtree(uri)
df = pd.DataFrame(
{
"soma_joinid": np.asarray([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20], dtype=np.int64),
"b": np.array([False,True,True,False,True,False,True, False,False,False,True,False,True,False,False,False,True,False,True,False], dtype=bool),
}
)
tbl = pa.Table.from_pandas(df)
sdf = soma.DataFrame(uri)
sdf.create(schema=tbl.schema, …
```
> [c++] Map 8-bit TILEDB_BOOL to 1-bit Arrow boolean

- apis/python/README.md
Based on a note I left on #562, I figured the `platform_config` format should probably be documented someplace more visible and durable than the contents of a single commit message.
> Add documentation for `platform_config` to the Python README.

- apis/r/configure
This PR aims to robustify building from source out of the repo reflecting some of the experience Pablo had.  We add an explicit test for `cmake` which, while listed as required, is less commonly present in R environments, and reactivate a section using the build script if we are in fact in the repo.
No new code.
> [r] Make source build more robust

- apis/python/src/tiledbsoma/dataframe.py
- apis/python/src/tiledbsoma/sparse_nd_array.py
- apis/python/src/tiledbsoma/util.py
- apis/python/tests/test_dataframe.py
- apis/python/tests/test_sparse_nd_array.py
Use `nonempty_domain` to convert half-slices of `(None, int)` or `(int, None)` to valid ranges interpreted by the SOMAReader.
> Support half-slices in SOMAReader

- apis/python/src/tiledbsoma/collection.py
See issue #583 for details; and also the code comments on this PR.
Prior art: https://github.com/TileDB-Inc/TileDB-Py/blob/dev/tiledb/tests/test_group.py
> Fix flaky unit test

- apis/python/setup.cfg
- apis/python/setup.py
- apis/r/DESCRIPTION
- apis/r/tools/get_tarball.R
- libtiledbsoma/cmake/Modules/FindTileDB_EP.cmake
Core 2.13 aligns with TileDB-Py 0.19 and TileDB-R 0.17. These are already released.
> Update to TileDB 2.13 [main]

- apis/python/tests/test_dense_nd_array.py
For #560. Follow-on from #581.
> Extend indexing-related unit-test cases for DenseNdArray

- apis/r/R/utils-arrow.R
- apis/r/tests/testthat/test-SOMADataFrame.R
This updates the internal `tiledb_type_from_arrow_type()` utility to convert Arrow `large_utf8` to TileDB `STRING_ASCII`, just as it does for the `utf8` and `string` types. 
These conversions are temporary until utf8 filtering support is added to core.
> [r] Convert arrow::large_utf8() to ascii

- .github/workflows/ci.yml
Part of #544.
Note 3.11 may take a bit more work, and 3.7 quite a bit more (due to `typing` changes). This PR just takes a quick and easy step, as the first of more to come.
With this PR we'll have Python 3.8 through 3.10 covered in CI testing.
> Include Python 3.10 in CI matrix

- apis/python/setup.py
- apis/python/src/tiledbsoma/collection.py
- apis/python/src/tiledbsoma/dataframe.py
- apis/python/src/tiledbsoma/dense_nd_array.py
- apis/python/src/tiledbsoma/experiment.py
- apis/python/src/tiledbsoma/io.py
- apis/python/src/tiledbsoma/measurement.py
- apis/python/src/tiledbsoma/sparse_nd_array.py
- apis/python/src/tiledbsoma/types.py
It turns out you can fulfil the requirements of abstract properties using just members. `Final` gives users some static analysis hints that maybe they shouldn't be writing to that field.
---
As seen in somabase: https://github.com/single-cell-data/SOMA/pull/59
> Shorten class constants using `Final` typing thing.

- libtiledbsoma/include/tiledbsoma/column_buffer.h
- libtiledbsoma/include/tiledbsoma/managed_query.h
- libtiledbsoma/include/tiledbsoma/soma_reader.h
- libtiledbsoma/src/column_buffer.cc
- libtiledbsoma/src/managed_query.cc
- libtiledbsoma/src/soma_reader.cc
- libtiledbsoma/test/test_soma_reader.py
- libtiledbsoma/test/unit_column_buffer.cc
This PR provides the empty range query support described in #593 (a query containing only empty ranges should return empty results).
While reviewing #593, I realized some C++ refactoring would make empty range queries easier to support.
**Note** - This PR does not contain the python API changes in #593, in case we want to keep those changes separate.
> [c++] Support empty range query

- .github/workflows/pkgdown.yaml
- .github/workflows/r-cmd-check.yaml
- apis/r/DESCRIPTION
- apis/r/NEWS.md
Updates package version number to 0.1.19 in preparation for release. 
Other changes:
- Updated `setup-r` GitHub Action to v2
Note: CI test failures are due to a core issue that will be fixed in 2.13.1.
> [r] Release 0.1.19

- apis/python/src/tiledbsoma/tiledb_object.py
- apis/python/tools/peek-exp.py
Addresses issue #391
This is temporary pending TileDB-internal Shortcut task 23827
Validation/use-case:
```
$ export AWS_DEFAULT_REGION=us-west-2
$ python
>>> import tiledbsoma as soma
>>> exp = soma.Experiment("s3://bucket-which-is-in-us-west-2/path/to/soma/experiment")
>>> print(exp)
```
This is crucial for good out-of-the-box UX and uptake/exploration.
(Of course, if a config region is supplied,it is honored -- this mod applies solely for users who don't have a `ctx`/`cfg` and perhaps haven't even learned what those are yet.)
> Honor AWS_DEFAULT_REGION if no overriding ctx is specified

- .github/workflows/r-ci.yml
- apis/r/DESCRIPTION
- apis/r/copy_source.sh
Fixes a minor issue with `copy_source.sh` resulting from the different behavior of `cp` on macOS and Linux. 
For posterity (and I because I will surely forget almost immediatley), the issue was that `cp -a` on macOS copies the contents of a directory rather than the directory itself if the source ends in a `/`.
Also bumps the minimum required version of _arch_ to 0.0.2 (thanks to @eddelbuettel).
> Fix and re-enable CI macOS builds

- apis/r/tests/testthat/test_SOMASparseNdArray.R
This PR updates one test to refer to the now-renamed `soma_data` method (see #397 for original rationale).
> [r] Adjust SparseNDArray test to renamed soma_data method

- apis/r/R/SOMADataFrame.R
- apis/r/tests/testthat/test-SOMADataFrame.R
This updates `SOMADataFrame`'s write method to temporarily disable arrow's `int64->int32` downcasting behavior. 
Thanks to @eddelbuettel for the help tracking down and solving this issue.
> [r] Fix storage of int64 values by SOMADataFrame

- apis/r/R/SOMADataFrame.R
- apis/r/tests/testthat/helper-test-data.R
- apis/r/tests/testthat/test_SOMADataFrame.R
Addresses #386 for the R package.
Updates `SOMADataFrame`'s `create` method to: 
- automatically add `soma_joinid` if it's missing from the schema.
- prevents the creation of `SOMADataFrames` with `soma_` prefixed columns
- assert `soma_joinid` is of type `int64`
> [r] Correct handling of soma_joinid and soma_rowid

- .github/workflows/format.yml
- apis/python/setup.cfg
- apis/python/setup.py
- apis/r/DESCRIPTION
- tools/ci/install-r-dependencies.sh
Core 2.13 aligns with TileDB-Py 0.19 and TileDB-R 0.17. Those are already released.
After this we can tag TileDB-SOMA 0.1.19.
Once TileDB Cloud is updated to 2.13 (REST server) then we can include TileDB-SOMA 0.1.19 in the UDF/notebook-image repos.
> Update to TileDB 2.13 [main-old branch]

- apis/python/src/tiledbsoma/io.py
Simply does two things:
* Remove a no-longer-needed handler-func indirect (used in `main-old`, not `main`);
* Order functions in top-down call order
This is a line-count-reducing PR to make an upcoming non-trivial a little easier for the reviewer to follow.
> [python] Trivial io-module function-reorder

- apis/python/tests/test_basic_anndata_io.py
The unit-test code on this PR was, erroneously, using a new tempdir on each rewrite pass -- not actually testing rewrite of the same soma directory. This PR fixes that oversight.
> [python] Improve resume-mode/schema-only testing [main-old]

- apis/r/R/SOMADataFrame.R
- apis/r/R/utils-arrow.R
- apis/r/tests/testthat/test_SOMADataFrame.R
Minor tweaks to `SOMADataFrame` to support creation of dimensions with int64, float/double, and string data types. As per the spec, we limit the domain of numeric dimensions to non-negative values.
> [r] Fix creation of SOMADataFrames with non-int32 dimensions

- apis/python/src/tiledbsoma/io.py
- apis/python/tests/test_basic_anndata_io.py
Development on #664 revealed some underlying unit-test work that had been left incomplete. This PR fixes that problem.
> [python] Complete basic anndata I/O tests

- apis/python/setup.py
Fixes https://github.com/single-cell-data/TileDB-SOMA/issues/675:
- Remove `if __name__ == "__main__"`; it [confuses cibuildwheel](https://github.com/pypa/cibuildwheel/blob/7c4bbf8cb31d856a0fe547faf8edf165cd48ce74/cibuildwheel/projectfiles.py#L41-L46)
- Add back `ext_modules` option; it's needed (even if `sources` are empty) otherwise the wheel is considered pure-Python.
> Fix setup.py to play well with cibuildwheel

- apis/python/src/tiledbsoma/test_general_utilities.py
This somehow found its way into the main source when it should be (and already is!) in `tests/`.
> Remove duplicate `test_general_utilities.py` file.

- apis/python/src/tiledbsoma/io.py
This would have been a port of #682 from `main` to `main-old`.
However (as noted in the comments here) `h5py` doesn't suppor the kind of permuted reads that `main-old` requires (and `main` does not require).
> [python] No more memory reduction [main-old]

- apis/python/src/tiledbsoma/io.py
- apis/python/src/tiledbsoma/util_scipy.py
- apis/python/tests/test_basic_anndata_io.py
This is crucial good UX for uptake of the SOMA product.
Here we leverage two things:
* `adata = anndata.read_h5ad(path_to_h5ad, "r")` with the `"r"` already in place (not new)
* Replace `adata.X[:]` with `adata.X` (new) -- this is a paginable object we can use to read CSR/CSC into memory a chunk at a time without needing to read the entire CSR/CSV into memory
Sandbox experiments using `htop` and a 58GB `.h5ad` file have shown peak memory on ingest drops from over 30GB without this PR, to about 15GB with this PR.
Note: currently stacked atop `kerl/resume-mode-main-2` which is also awaiting code review.
> [python] More memory-reduction for ingest [main]

- .github/workflows/format.yml
- .pre-commit-config.yaml
- Bump versions of precommit hooks & add [flake8-bugbear](https://github.com/PyCQA/flake8-bugbear)
- Update linter Github action to trigger pre-commit hooks instead of running manually black/isort/flake8/...
> [python] Bump versions of precommit hooks

- apis/r/DESCRIPTION
https://github.com/single-cell-data/TileDB-SOMA/releases/tag/0.1.20 was fine but lacked a PyPI wheel.
This release will fix that.
See also https://github.com/single-cell-data/TileDB-SOMA/wiki#branches-and-releases which I recently updated with an info tip to help avoid the very mistake I just made this morning -- specifically this part:
> If you've created a GitHub branch (not tag, branch) like 0.1.20, do not tag that branch -- instead, merge that PR back to main-old and then make the tag on main-old -- else PyPI-publish CI won't run
> tiledbsoma 0.1.21 [main-old]

- apis/python/src/tiledbsoma/collection.py
- apis/python/src/tiledbsoma/dataframe.py
- apis/python/src/tiledbsoma/dense_nd_array.py
- apis/python/src/tiledbsoma/experiment.py
- apis/python/src/tiledbsoma/measurement.py
- apis/python/src/tiledbsoma/sparse_nd_array.py
- apis/python/src/tiledbsoma/tiledb_object.py
- apis/python/tests/test_basic_anndata_io.py
I discovered this bug while working on #685, but the bug precedes #685. For `Measurement` and `Experiment` objects, we have been writing soma type `SOMACollection` rather than `SOMAMeasurement` and `SOMAExperiment`, respectively. This bug wasn't caught sooner because it wasn't tested sooner. This PR fixes both problems.
> [python] Correct incorrect object-type metadata on storage

- libtiledbsoma/src/column_buffer.cc
- libtiledbsoma/src/soma_reader.cc
A few strings in error messages were unquoted, which meant it was sometimes ambiguous as to what was going on or what the invalid value might be.
> Add quote marks around a few strings in C++ errors.

- apis/python/setup.py
Context: #713 
Fixes the problem as described in that issue.
Works for all of Python 3.7 .. 3.10.
> [python] Update pyarrow dependency

- .github/workflows/python-ci.yml
- Separates the `pip install` steps for the build-/test-only deps (pytype, typeguard, etc.) from the package itself.
- Installs the `wheel` package so that we use wheels to install where possible (editor's note: why is this not included by default???).
> Separate pip installation of prereqs and tiledbsoma itself.

- apis/python/setup.cfg
- apis/python/setup.py
- apis/r/DESCRIPTION
Update for TileDB Cloud. The rule `tiledb >= 0.19.0` suffices (and is already used in `main`).
`tiledb >= 0.19.0` rather than `tiledb >= 0.19.1`
> tiledbsoma 0.1.22

- apis/python/src/tiledbsoma/__init__.py
- apis/python/tests/test_experiment_query.py
This PR is in preparation for landing PR single-cell-data/SOMA#61.  See also, related PR single-cell-data/SOMA#83
* Added two somacore name exports for better API UX:  `AxisQuery` and `ExperimentAxisQuery`
*  Reworked the `ExperimentAxisQuery` tests to use the public interface (the private interfaces are changing).  Tests do the same thing, but now use the supported API.
None.
> [python] Prep for ExperimentAxisQuery perf work in `somacore`

- .github/workflows/python-ci.yml
- .pre-commit-config.yaml
- apis/python/setup.cfg
Run `mypy` via `pre-commit` so that typing errors are caught before being committed.
One small downside is the need to specify explicitly the dependencies to be installed in the mypy virtualenv (e.g. `somacore`), instead of having all the `tiledbsoma` dependencies already installed as on https://github.com/single-cell-data/TileDB-SOMA/pull/726. That's because AFAICT the `additional_dependencies` option can install only PyPI packages, not local dependencies (e.g. `apis/python/`).
> Add pre-commit hook for mypy and remove explicit mypy step from python-ci

- .github/workflows/python-ci.yml
This uses the Python GitHub Action's built-in tool to cache the Pip downloaded package directory. This cache contains the wheels (or other package files) that were downloaded and thus avoids having to download them again. Only the downloaded package files themselves are cached; this does not enforce "stickiness" on what versions are installed (i.e. if a new version of a dependency is released, that new version will be downloaded and used; the cache will not "stick" to the old version indefinitely).
> [python] Set up caching for packages downloaded with Pip

- Makefile
- apis/r/R/SOMADenseNdArray.R
- apis/r/R/SOMASparseNdArray.R
- apis/r/src/rinterface.cpp
- apis/r/src/riterator.cpp
#707 -- general pre-release neatening
Whenever there is one or more spaces followed by one or more tabs, simply expand the tabs.
This way comments will align respecting the author's intent even when the code reader uses a different tab-width than the code author.
Nothing but whitespace; no functional changes.
> [r/python/c++] Expand tabs that are immediately following spaces

- .github/workflows/python-ci.yml
Context: #693
This caches the `build` and `dist` directories [was: `dist/lib`], which is the output from the libtiledbsoma build process. It uses the hash of all files in the `libtiledbsoma` directory (as well as `setup.py`) to ensure that when any file is changed, the cache is invalidated and the build is done anew.
---
I'm not sure how I would set this up on the R side but something analogous would be good there, too.
> [python] Cache builds of libtiledbsoma in Python CI

- .github/workflows/python-ci.yml
Context: #693 
Pre-commit sets up its runtime environments in a cache directory. If that cache does not exist, it has to download and set up the environment anew with every run (cf. "This may take a few minutes..." in the pre-commit output). This accounts for the majority of the runtime of the step within GitHub actions. Caching the environments means that this no longer needs to happen.
> [python] Cache pre-commit environments

- apis/python/tests/test_experiment_query.py
See #755 and chanzuckerberg/cell-census#56
Add a test to validate changes introduced in single-cell-data/SOMA#89    
Please review with single-cell-data/SOMA#89
*IMPORTANT:* This test will fail until `tiledbsoma` is upgraded to use the fix in `somacore`
> [python] Add test for to_anndata column_names

- .pre-commit-config.yaml
- apis/python/src/tiledbsoma/experiment_query.py
- apis/python/src/tiledbsoma/io.py
- apis/python/src/tiledbsoma/types.py
- apis/python/src/tiledbsoma/util_ann.py
- apis/python/src/tiledbsoma/util_tiledb.py
Add public type stubs for `pandas` via [pandas-stubs](https://pypi.org/project/pandas-stubs/) and fix the 9 resulting mypy errors.
> Add pandas-stubs for mypy and fix uncovered typing issues

- .github/workflows/python-ci-single.yml
Because pre-commit–based `mypy` doesn’t depend upon the packages in the installed directory, the only thing we need to install is pre-commit.
Context: #693
> [python] Remove unnecessary steps from lint job

- apis/python/tests/test_experiment_query.py
Public API for ExperimentAxisQuery indexer was accidentally removed in the `somacore` refactoring.  See #768 
single-cell-data/SOMA#90 resolves the underlying issue.
This PR adds a unit test.
Add unit test of public API.
The test change will fall back on the old (private) API, as a temporary work-around until such time as `tiledbsoma` is updated to use a `somacore` release that contains this fix.
> [python] Add test case for issue 768 -- existence of `ExperimentAxisQuery.get_indexer()`

- apis/r/tests/testthat/test_SOMADataFrame.R
#737 
Simple write-and-read-back tests for UTF-8 strings in `SOMADataFrame`.
There's more we can check, of course. While doing a quick health check with core 2.14 (#770) I typed this up, and it works, and I figured, why not put up an initial PR -- ?
> [r] Simple R UTF-8 test

- apis/python/src/tiledbsoma/options/soma_tiledb_context.py
#391 , now possible since core 2.14 at #770 is merged
> [python] Undo AWS_DEFAULT_REGION workaround

- apis/python/tests/test_experiment_query.py
#778  - need to increase unit tests
Added additional unit tests for `somacore.ExperimentAxisQuery` and related.
Note: routines in `_fast_csr` compiled by numba are tested, but codecov will not report them as such
> [python] Additional experiment-query unit tests

- apis/python/examples/soco-batch-query.py
- apis/python/examples/uniformizer.py
- apis/python/src/tiledbsoma/annotation_dataframe.py
- apis/python/src/tiledbsoma/annotation_matrix_group.py
- apis/python/src/tiledbsoma/annotation_pairwise_matrix_group.py
- apis/python/src/tiledbsoma/assay_matrix_group.py
- apis/python/src/tiledbsoma/util_tiledb.py
- apis/r/DESCRIPTION
- apis/r/NEWS.md
- apis/r/R/SOMACollection.R
- apis/r/R/utils.R
- apis/r/man/SOMACollection.Rd
- apis/r/tests/testthat/helpers.R
- apis/r/tests/testthat/test_SOMACollection_Seurat.R
This PR adds a `somas` argument to `SOMACollection`'s `to_seurat()` method that allows you to select a subset of `SOMA`s and, optionally, `X` layers when converting to a `Seurat` object. 
You can pass either a vector of `SOMA` names
```r
soco$to_seurat(somas = c("SOMA1", "SOMA2"))
```
_or_ a named list of character vectors, where each element corresponds to a `SOMA` name and the value is a character vector of `X` layers from that `SOMA` to include in the corresponding Seurat `Assay`:
```r
soco$to_seurat(somas = list(SOMA1 = c("counts", "data"), SOMA2 = "counts"))
```
> [r] Make SOMAs and X layers selectable when converting to a Seurat object

- apis/python/src/tiledbsoma/io.py
- apis/python/tests/test_basic_anndata_io.py
#643
This is a key piece of UX present within `main-old` but currently lacking in `main`, on discussion with @ckrilow on feature-parity gap analysis between `main-old` and `main`. Namely, a key workflow is like this:
```
import tiledbsoma, tiledbsoma.io
import scanpy
adata = ... AnnData object obtained somehow
exp = soma.Experiment(uri)
soma.io.from_anndata(exp, adata, "RNA")
scanpy.pp.normalize_total(adata, inplace=True)
scanpy.pp.log1p(adata, copy=False)
... need to make a new exp.ms["RNA"].X["normalized"] from adata.X
```
The problem with the existing `write` methods is they all assume Arrow format. This leaves the user with many lines of plumbing to invent. We need to do this for them so they don't have to.
This is a crucial bit of feature parity with `main-old`.
> [python] Make add-X-layer logic friendlier

- apis/python/README.md
This `README.md` is propagated to https://pypi.org/project/tiledbsoma and is currently given erroneous instruction on how to pip-install for folks using `main` (the current pre-release development version).
> [python] Fix pip-install instructions

- .pre-commit-config.yaml
- apis/python/pyproject.toml
- apis/python/setup.cfg
- apis/python/setup.py
- apis/python/src/tiledbsoma/dataframe.py
Replace flake8 & isort with [ruff](https://github.com/charliermarsh/ruff), a blazing fast Python linter.
> [python] Replace flake8 & isort with ruff

- apis/python/src/tiledbsoma/query_condition.py
- doc/source/conf.py
- doc/source/gensidebar.py
- ruff.toml
Too many times I have bitten myself by running `black . && isort .` at the root of the repo and had it introduce lots of spurious changes. This adds an isort config so that won't happen, and formats everything appropriately.
> [python] Create an isort (now ruff) config at the root of the repository

- apis/r/DESCRIPTION
The iterated reader is only truly testable on a large dataset as we do not (currently) set the chunk size of reads. A local data package, containing a compressed tarball of the standard dataset in the repo (in hdf5 form) has been useful for local tests.  Before (or inconjunction to) moving the data set to cloud storage we can also _very cheaply_ take advantage of infrastructure we already have in the `Additional_repositories:` field used to provide the Arrow helper `arch` while we await to Arrow team's release of `nanoarrow`.
A one word addition to `DESCRIPTION`, plus an injection of the data package into the [ghrr drat repo via this commit](https://github.com/ghrr/drat/commit/a91e5118e57863ebe0da85712ecccdc6c45735a8)
This permits the [unit test file we long …
> [r] Allow use pbmc3k data package in test

- apis/python/src/tiledbsoma/factory.py
- apis/python/src/tiledbsoma/sparse_nd_array.py
- apis/python/tests/test_factory.py
- apis/python/tests/test_sparse_nd_array.py
We need to increase unit tests
* Improved unit tests for SparseNDArray
* New unit tests for factory.py 
* Fixed a couple of minor bugs related to error handling:
* Partial fix for #801 - check encoding version in reification. We still need to check it for other code paths
* Correctly handle the case of missing object metadata (use `meta.get(key, None)` rather than `meta[key]`)
None
> More unit tests, plus partial fix for #801

- apis/python/src/tiledbsoma/collection.py
- apis/python/src/tiledbsoma/dataframe.py
- apis/python/src/tiledbsoma/dense_nd_array.py
- apis/python/src/tiledbsoma/experiment.py
- apis/python/src/tiledbsoma/factory.py
- apis/python/src/tiledbsoma/measurement.py
- apis/python/src/tiledbsoma/sparse_nd_array.py
- apis/python/src/tiledbsoma/tiledb_array.py
- apis/python/src/tiledbsoma/tiledb_object.py
- apis/python/tests/test_collection.py
- apis/python/tests/test_factory.py
- apis/python/tests/test_tiledb_object.py
#638 
This is one step on #638. One of the things that needs doing is making `create` a class method. There, there won't be a `parent` naturally passed in.
Meanwhile, ever since the Misty Days of Yore -- mid-2022 -- we have been propagating both `parent` and `context` through the constructor call chain. The `parent` used to do many things, but in this current SOMA epoch, all but one use of `parent` has been refactored away, leaving solely `parent.context` being put to use. Instead of passing `parent` and `context` both down the call chain, only to take `context` or `parent.context` at the bottom, now we can simply -- with zero loss of _any functionality_ -- pass `context` at the top of the call chain.
> [python] Propagate context rather than parent.context

- .pre-commit-config.yaml
- apis/python/devtools/ingestor
- apis/python/setup.py
- apis/python/src/tiledbsoma/collection.py
- apis/python/src/tiledbsoma/dataframe.py
- apis/python/src/tiledbsoma/dense_nd_array.py
- apis/python/src/tiledbsoma/experiment.py
- apis/python/src/tiledbsoma/io.py
- apis/python/src/tiledbsoma/measurement.py
- apis/python/src/tiledbsoma/sparse_nd_array.py
- apis/python/src/tiledbsoma/tiledb_object.py
- apis/python/tests/test_collection.py
- apis/python/tests/test_dataframe.py
- apis/python/tests/test_dense_nd_array.py
- apis/python/tests/test_experiment_basic.py
- apis/python/tests/test_experiment_query.py
- apis/python/tests/test_metadata.py
- apis/python/tests/test_platform_config.py
- apis/python/tests/test_sparse_nd_array.py
- apis/python/tests/test_tiledb_object.py
- apis/python/tests/test_type_system.py
- apis/python/tests/test_unicode.py
This change imports the new version of somacore, but does not actually implement any of the new APIs specified by it.
- Because `create` and `open` are now class methods with different semantics, the existing methods are renamed `create_legacy` and `open_legacy`.
- Duplicate methods (reimplementing the context manager protocol) have been removed and are delegated to somacore.
> Import somacore v0.0.0a7, without making any functional changes.

- apis/python/src/tiledbsoma/collection.py
- apis/python/src/tiledbsoma/factory.py
- apis/python/src/tiledbsoma/util.py
- apis/python/tests/test_factory.py
- Replaced the `if/elif/elif/....` logic in `factory._construct_member` with a dict lookup. Classes are first-class (pun not intended) objects  in Python so they can be stored as values in a `SPEC_NAME_TO_CLASS` dict.
- Tightened `context` and `object_type` parameters to be non-optional. Also changed `object_type` to be an actual type instead of str.
> Refactor factory._construct_member

- apis/python/src/tiledbsoma/annotation_matrix_group.py
- apis/python/src/tiledbsoma/annotation_pairwise_matrix_group.py
- apis/python/tests/test_add_layer.py
On last month's #628 , `ingest_mode` was made optional and defaulting to `"write"` in _almost_ all callsites -- I missed two, as @ckrilow noticed.
> [python] Correctly default ingest mode for  updates to obsm et al.

- apis/python/src/tiledbsoma/__init__.py
- apis/python/src/tiledbsoma/collection.py
- apis/python/src/tiledbsoma/dataframe.py
- apis/python/src/tiledbsoma/dense_nd_array.py
- apis/python/src/tiledbsoma/experiment.py
- apis/python/src/tiledbsoma/general_utilities.py
- apis/python/src/tiledbsoma/io.py
- apis/python/src/tiledbsoma/logging.py
- apis/python/src/tiledbsoma/measurement.py
- apis/python/src/tiledbsoma/options/__init__.py
- apis/python/src/tiledbsoma/options/soma_tiledb_context.py
- apis/python/src/tiledbsoma/options/tiledb_create_options.py
- apis/python/src/tiledbsoma/options/tiledb_platform_config.py
- apis/python/src/tiledbsoma/sparse_nd_array.py
- apis/python/src/tiledbsoma/tiledb_array.py
- apis/python/src/tiledbsoma/tiledb_object.py
- apis/python/tests/test_io.py
- apis/python/tests/test_platform_config.py
#708 
- Added to all publicly exported classes and their methods, including constructor
- Added to top-level functions in io, logging, general_utilties modules
- Not added to @property methods
- Not added to exceptions
- All are "experimental" maturity for now
Unrelated:
- Removed dead code: `TileDBPlatformConfig` class
- No longer export `TileDBCreateOptions` or `MetadataMapping` (they're for internal use only)
If this is approved, will tackle R changes in a separate PR.
> Add lifecycle maturity tags to public API docstrings (Python)

- .pre-commit-config.yaml
- apis/python/setup.py
- apis/python/src/tiledbsoma/experiment.py
- apis/python/src/tiledbsoma/measurement.py
This does not include any behavior changes relative to current code but will make for smoother sailing for changes that depend upon it by ensuring that the native libraries are cached for the new `setup.py`.
> Switch to somacore 0.0.0a10.

- .github/workflows/python-ci-single.yml
- apis/python/setup.py
We were (I was) using the contents of `setup.py` for the cache key when building the tiledbsoma C++ library. This was not ideal since it meant the cache would be busted when unrelated changes happened. We should instead use the `bld` script, which does the actual blding, as the key.
> [python] Use the contents of `bld`, not `setup.py`, for binary cache

- apis/r/DESCRIPTION
Building on Windows will likely require changes to the `cmake` setup.
Set the OS_type: field in `DESCRPTION`
See https://app.shortcut.com/tiledb-inc/story/24923/r-limit-builds-to-unix-operating-systems
> [r] Limit builds to unix operating systems

- apis/python/tests/test_experiment_basic.py
Prep-work for #821
```
>>> from urllib.parse import urljoin
>>> urljoin("A", "B")
'B'
>>> urljoin("A"+"/", "B")
'A/B'
>>> import os
>>> os.path.join("A", "B")
'A/B'
```
`urljoin` is confusing and error-prone. (Its use for unit tests tracks back to #381.). We should not use it for unit tests.
`os.path.join` is correct and trustworthy. We should use it for unit tests.
Barring that, we should work around the idiosyncracies of `urljoin`.
> [python] Fix legacy misuse of`urllib.parse.urljoin`

- apis/r/R/SOMADenseNdArray.R
- apis/r/R/SOMASparseNdArray.R
- apis/r/tests/testthat/test_SOMAReader-Iterated.R
Additional read accessors in 'iterated' mode
Support for iterated sparse matrices 
Still flagged a draft for comment.  Test function may be best illustration.  Sparse matrix representation mode is cached locally. 
See https://app.shortcut.com/tiledb-inc/story/24951/support-iterated-sparse-matrix-reads
> [r] Support iterated sparse and dense matrix reads

- apis/python/src/tiledbsoma/common_nd_array.py
- apis/python/src/tiledbsoma/dense_nd_array.py
- apis/python/src/tiledbsoma/io.py
- apis/python/src/tiledbsoma/sparse_nd_array.py
Eliminates some duplicate code and some redundant type-assertions/casts.
> Pull the common parts of NDArrays into the base NDArray class.

- apis/python/setup.py
When `libtiledbsoma` was installed to a system directory, `setup.py` was not able to find the shared library object and build from source. This is one of the first steps we need to solve in order to get conda builds to work.
Ported over certain functions from TileDB-Py's `setup.py` to fix the above issue. The ctypes's `CDLL` function finds global installs of the shared library object. On Linux, `CDLL` only returns a relative path. We need to use ctypes's `dlinfo` to get the absolute path.
N/A
> Modify `setup.py` To Find System Installed `libtiledbsoma` On POSIX

- apis/python/src/tiledbsoma/tiledb_object.py
Because SOMA objects have a lot of complex state, saying that they have the same URI isn't really enough for equality, and the existence of the `__eq__` method is more likely to cause confusion if the user has two separate handles open on the same backing object.
> Remove `__eq__` method from base `TileDBObject` class.

- apis/python/src/tiledbsoma/collection.py
- apis/python/src/tiledbsoma/experiment.py
- apis/python/src/tiledbsoma/measurement.py
- apis/python/src/tiledbsoma/util.py
- apis/python/tests/test_collection.py
- apis/python/tests/test_experiment_basic.py
- apis/python/tests/test_experiment_query.py
This adds, in three steps, the `add_new_collection` implementation to Collection. The use of a relative vs. absolute URI is derived from the URI passed into the function (if it's relative, it's relative, if it's absolute, it's absolute). This does not currently support adding to a collection stored on TileDB Cloud without a URI specified.
As I understand it, because the `io.from_whatever` functions all generated their own URIs of the form `parent_uri/child_name`, this was never going to work with groups/arrays stored on TileDB Cloud, because it would try to generate a URI that looked like `tiledb://some_ns/some_group/child_name`, which is not allowed. This meant the `use_relative_uri` function was moot inside those functions anyway, since you can’t actually do the thing you want to use …
> Add `add_new_collection` implementation.

- apis/python/src/tiledbsoma/collection.py
- apis/python/src/tiledbsoma/tiledb_object.py
- apis/python/tests/test_collection.py
- apis/python/tests/test_experiment_query.py
Collections are now responsible for the lifecycle of elements created using `collection.add_new_whatever` and items accessed through `collection["something"]`. This allows close operations to cascade from parent to child and allows a coherent API structure where the user opens a collection, has access to everything inside, and closes everything when they close the collection.
Part of #843.
Huge shout-out to @mlin for introducing `ExitStack`, which I had not heard of before, and which made this work almost trivial.
> [python] Track ownership of accessed and added collection members.

- apis/python/src/tiledbsoma/util.py
Pylance (the Python language server used by VSCode) got confused by the way we were defining our `typeguard_ignore` setup. This new formulation has the same behavior but does not confuse pylance.
> Make `typeguard_ignore` decorator play nice with Pylance.

- apis/python/src/tiledbsoma/collection.py
- apis/python/tests/test_collection.py
- apis/python/tests/test_experiment_query.py
This completes the `add_new_` methods to allow users to add not just collections but also data objects.  Just like `add_new_collection`, the newly-added members' lifecycle is owned by the collection itself.
> [python] Add `add_new_dataframe` and `_sparse`/`_dense_ndarray`

- apis/python/src/tiledbsoma/dataframe.py
- apis/python/tests/test_dataframe.py
#419
All core-level support now exists. This is just a matter of un-xfailing the relevant unit-test cases.
> [python] Support indices of type `bytes`

- apis/python/src/tiledbsoma/collection.py
- apis/python/src/tiledbsoma/common_nd_array.py
- apis/python/src/tiledbsoma/dataframe.py
- apis/python/src/tiledbsoma/factory.py
- apis/python/src/tiledbsoma/tiledb_array.py
- apis/python/src/tiledbsoma/tiledb_object.py
Context: #860.
If a user called
something = tiledbsoma.Experiment(whatever)
after they got the expected exception saying "use the factory method instead", they would also get an unexpected error from the `__del__` method of the SOMA object.
This change:
- Eliminates the `__del__` error
- Improves the error message you get from improper construction
- Makes the secret key parameter name even more descriptive.
> Fix `__del__` error when improperly constructing a TileDB object.

- apis/python/src/tiledbsoma/dataframe.py
- apis/python/src/tiledbsoma/factory.py
We were pre-caching the dimension names for the DataFrame because we were previously opening and closing the TileDB array handle (if it was not already open) when they were requested. However, since we now have a long-lived handle that we keep around, that is no longer needed.
---
Based on @bkmartinjr’s [a comment on an earlier review](https://github.com/single-cell-data/TileDB-SOMA/pull/824#discussion_r1089607732):
> I'm not sure caching the index column names makes any sense given the change to stateful handles. I believe that it was originally put in place to avoid repeated calls to open on the array (just to get the dimension names). With an open handle guaranteed, getting dim names is cheap, ergo caching is not worth the complexity.
> [python] Directly use backend TileDB dimension names for `DataFrame`

- apis/python/src/tiledbsoma/util_tiledb.py
In conjunction with #863, this allows ingest to tiledb-cloud URIs to again succeed.
```
uri = 'tiledb://johnkerl-tiledb/s3://tiledb-johnkerl/scratch/test-cloud-20230201'
soma = tiledbsoma.SOMA(uri)
tiledbsoma.io.from_h5ad(soma, '/tmp/test.h5ad')
```
Note this test scenario does not pass until and unless #863 is also included. I'm putting this up as a PR on `main` instead of atop #863 at the explicit request of @thetorpedodog .
Since this is an open-source package we do not have unit tests taking the `tiledb.cloud` dependency.
> [python] Fix ingest to cloud URIs (part 1 of 2)

- apis/python/src/tiledbsoma/common_nd_array.py
- apis/python/tests/test_dense_nd_array.py
- apis/python/tests/test_sparse_nd_array.py
Fixes #875
Undoes the inadvertent https://github.com/single-cell-data/TileDB-SOMA/pull/681/commits/fa08391e68cc1555275a92362c1971c189c9acab#diff-c57e3497da1ff73a9f6544da46c2129f132e4c4a73dbc4c96ee972d9fb3bdf39L112
Does not address #876, which will be handled on a separate PR.
> [python] No allow-duplicates for sparse N-d arrays

- apis/python/src/tiledbsoma/__init__.py
#791 
With a `TODO` to neaten after `tiledbsoma` is updated to `somacore` version `0.0.0a12`.
> [python] Re-export `somacore`'s `AxisColumnNames` at top level

- apis/python/README.md
Adds `allows_duplicates` and `validity_filters` to the documentation for `TDBCreateOptions` in the README file.
(See also: #888, #876)
> Document newly-created `platform_config` options.

- apis/python/src/tiledbsoma/__init__.py
- apis/python/tests/test_factory.py
Adds some tests to `factory.open` to make sure it is ready for universal consumption and, having done so, makes it available for universal consumption.
---
Fixes #539.
> Export `open` function, to universally open everything.

- apis/python/tests/test_util_tiledb.py
- libtiledbsoma/test/test_soma_reader.py
Because of missing `stats_reset` calls in previous code, there would be huge volumes (megabytes) of stats output if you did `pytest -vs ./tests` with no options. This captures the output from `stats_dump` in a fixture and verifies its presence, and removes debugging stats management calls.
> [python] Capture stdout/stderr from `stats_dump` output

- apis/python/src/tiledbsoma/collection.py
- apis/python/src/tiledbsoma/common_nd_array.py
- apis/python/src/tiledbsoma/dataframe.py
- apis/python/src/tiledbsoma/dense_nd_array.py
- apis/python/src/tiledbsoma/exception.py
- apis/python/src/tiledbsoma/factory.py
- apis/python/src/tiledbsoma/measurement.py
- apis/python/src/tiledbsoma/query_condition.py
- apis/python/src/tiledbsoma/sparse_nd_array.py
- apis/python/src/tiledbsoma/tiledb_object.py
- Adds many missing docstrings
- Reformats unwrapped docstrings to wrap around 80–88 lines for easier onscreen reading
- Converts some docstrings to be (closer to?) Sphinx format.
Part of #858 and #602.
> [python] Add and improve documentation for many public-facing methods

- apis/python/src/tiledbsoma/collection.py
- apis/python/src/tiledbsoma/factory.py
- apis/python/src/tiledbsoma/funcs.py
- apis/python/src/tiledbsoma/io/conversions.py
- apis/python/src/tiledbsoma/io/ingest.py
- apis/python/src/tiledbsoma/util.py
- apis/python/tests/test_funcs.py
In #848 the main reason I used `functools.partialmethod` was to avoid having to repeat the same parameter list multiple times (and specify the same defaults multiple times, etc. etc.). However, `partialmethod` doesn't pick up the function's `__doc__` and related attributes, which meant that doing `help(coll.add_new_sparse_ndarray)` just gave you the documentation for `partialmethod`, which is completely useless.
This is one potential solution, which IMO has a lot of advantages:
- less repetition, and useful in more places than anticipated.
- no way for arg lists/defaults to go out of sync.
- pretty much the intended use case for `**kwargs`.
However, it does have some disadvantages:
- less static analysis support.
- somewhat complex internals (though they are well-tested and hidden behind …
> [python] Use `**kwargs` and a function decorator to forward arguments

- apis/python/src/tiledbsoma/dataframe.py
- apis/python/src/tiledbsoma/dense_nd_array.py
- apis/python/src/tiledbsoma/sparse_nd_array.py
- apis/python/src/tiledbsoma/tiledb_object.py
- Makes `_handle.closed` the canonical place that `close` comes from.
- Uses `_handle.schema` to get array schemas rather than going through the `writer`.
> Minor cleanup to deduplicate some code.

- apis/python/src/tiledbsoma/dataframe.py
- apis/python/src/tiledbsoma/dense_nd_array.py
- apis/python/src/tiledbsoma/sparse_nd_array.py
- apis/python/tests/test_dataframe.py
- apis/python/tests/test_dense_nd_array.py
- apis/python/tests/test_sparse_nd_array.py
This is an oddity I noticed when working on documentation for the `DataFrame.read` method in somacore. It's not a bug per se but is a special case that I found unexpected. I dug through back to #538 where this was introduced and didn't find the reasoning behind this particular behavior. It's fine to keep as-is but I figured I would see if we do want to keep this behavior.
---
Currently, DataFrame allows passing a sequence of coordinates shorter than the number of indexed dimensions:
df.read(coords=[1, 2, 3, 4])
df.read(coords=[1, 2])
df.read(coords=[1])
However, this pattern does not continue down to 0 dimensions:
df.read(coords=[])
despite the fact that not passing coordinates at all is allowed:
df.read(coords=None)
This change treats the zero-length array equivalent to an array of any …
> Allow passing 0-length lists of coordinates to DataFrame.

- apis/python/src/tiledbsoma/collection.py
- apis/python/src/tiledbsoma/tiledb_object.py
- apis/python/tests/test_collection.py
This adds more information to the general `__repr__` of SOMA objects, including their open mode and status, and slightly reformats the representation of collections.
It also ensures that `repr` will work on objects and collections that have been closed, and that `repr` will only recurse into sub-elements of a collection that have already been opened (so it doesn't eagerly open up an entire collection tree).
---
Yet another entry from the List Of Things I Notice While Doing Other Things.
> Put more info in the `__repr__` of SOMA objects.

- apis/python/src/tiledbsoma/dataframe.py
- apis/python/src/tiledbsoma/sparse_nd_array.py
- apis/python/src/tiledbsoma/util.py
- apis/python/tests/test_dataframe.py
Since we don't yet support partitioning, we shouldn't return results which aren't partitioned to callers who expect it.
> [python] Check to ensure we're not doing partitioned reads

- apis/python/src/tiledbsoma/dataframe.py
- apis/python/src/tiledbsoma/util.py
While we previously allowed the slice `step` value to be 1, this doesn't make sense when we slice in the context of floating-point dimensions (or string dimensions). For this reason, steps are disallowed entirely.
---
This is a proposal which I’m fine with seeing rejected, however this is the reasoning behind the language I put [disallowing slice steps](https://github.com/single-cell-data/SOMA/blob/2765ce5cf36ff6a374c8cca2c512dd0dc734fd22/python-spec/src/somacore/data.py#L113-L114) in the specification side (and make sure that it gets noticed too)
> [python] Explicitly remove support for slice steps.

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
I'm having some buyer's remorse now that we're seeing these in issues -- I'd rather be looking at more lower-casing in the issues list.
Thoughts? :)
> Don't use shouty-caps in issue templates

- apis/r/src/rinterface.cpp
- apis/r/src/riterator.cpp
- apis/r/src/rutilities.cpp
- apis/r/src/rutilities.h
- apis/r/tests/testthat/test_SOMAReader-Arrow.R
Issue #900 showed that selecting dimension points (or ranges) outside the non-empty domain lead to errors.  This PR reflect is domain of a dimension and only applies forming point (or range) selections.
The Dimension object is passed down to the helper functions setting points or ranges
See #900 and [SC #25314](https://app.shortcut.com/tiledb-inc/story/25314/soma-reader-attempts-to-set-dim-points-beyond-array-dimension) and [SC #25319](https://app.shortcut.com/tiledb-inc/story/25319/soma-r-package-check-ranges-and-dim-points-agains-non-empty-domain)
<details>  
With logging at the info level, we now see that the previously 'bad' ceases to select beyond index position nine.
```r
> library(tiledbsoma)
> uri <- "/tmp/tiledb/foosnda"
> ndarray <- SOMASparseNDArray$new(uri)
> tbl_bad <- …
```
> [r] Use dimension information when applying coords

- .pre-commit-config.yaml
- apis/python/setup.py
- apis/python/src/tiledbsoma/collection.py
- apis/python/src/tiledbsoma/dataframe.py
- apis/python/src/tiledbsoma/dense_nd_array.py
- apis/python/src/tiledbsoma/sparse_nd_array.py
- apis/python/tests/test_dataframe.py
- apis/python/tests/test_sparse_nd_array.py
- Remove `batch_size` from `DenseNDArray.read`.
- Make `coords` parameters non-`Optional`.
- Enable chaining on `read` and `set` methods.
---
Adopts https://github.com/single-cell-data/SOMA/pull/119 and https://github.com/single-cell-data/SOMA/pull/123.
Fixes #638.
> [python] Upgrade to somacore==0.0.0a13

- apis/python/tests/test_dataframe.py
Adds a "name" field to `test_read_indexing` parameters and renames columns to describe the data that gets put in them.
> [python] Give dataframe tests descriptive names and columns

- apis/python/setup.py
matplotlib just released v3.7, and unfortunately it introduced an incompatibility with scanpy:
https://github.com/scverse/scanpy/issues/2411
Excluding v3.7 works around this issue. This workaround can be removed once scanpy itself excludes v3.7, or if scanpy fixes the root cause.
---
In trying to figure out why https://github.com/single-cell-data/TileDB-SOMA/pull/928 failed despite not changing anything that would cause that type of failure, I figured that there must have been a dependency change.
So I looked at the output from the `pip install -e apis/python` step from [the failing job](https://github.com/single-cell-data/TileDB-SOMA/actions/runs/4168929983/jobs/7216289034) to see if there were any new libraries. A new library would not be in the pip cache, so it would have to have been …
> Exclude matplotlib 3.7 due to incompatible scanpy.

- apis/python/src/tiledbsoma/dataframe.py
Described fully at https://github.com/single-cell-data/SOMA/issues/121
> [python] Bring `SOMADataFrame` domain into spec compliance

- apis/python/src/tiledbsoma/common_nd_array.py
Just a typofix. It looks like the code modified here was once only for `DenseNDArray`, but is now being leveraged for duplicate sparse/dense use.
> [python] Typo-fix in `NDArray` `create` error message

- pull_request_template.md
No tracking issue -- just aesthetics.
Having used this template for a while I find the `##` a bit much, and unnecessary. Also, it's error-prone as if one does at first
```
```
one needs to immediately re-edit to
```
foo
```
which is error-prone and (micro-)time-consuming.
> Make the pull-request template a little less shouty

- .pre-commit-config.yaml
- apis/python/setup.py
- apis/python/src/tiledbsoma/dataframe.py
- apis/python/src/tiledbsoma/sparse_nd_array.py
- apis/python/src/tiledbsoma/tiledb_array.py
- apis/python/src/tiledbsoma/types.py
- apis/python/src/tiledbsoma/util.py
- apis/python/tests/test_dataframe.py
- apis/python/tests/test_sparse_nd_array.py
- apis/python/tests/test_util.py
- Removes the "slice indices must be positive" requirement,  per discussion on https://github.com/single-cell-data/SOMA/pull/119.
- Enables slicing for string dimensions.
This change also follows up on the previous change to allow"over-indexing" off the low end of a domain to work just as it does when indexing off the high end of a domain: the low end is clipped to the bottom of the domain. So for a dimension with domain [−3, 8]:
slice(-100, 100) -> -3, 8
slice(-5, 0) -> -3, 0
slice(5, 10) -> 5, 8
slice(-100, -50) -> error (too low)
slice(50, 100) -> error (too high)
Since this uses the New And Improved `is_slice_of` function, this also pulls in the new somacore (where that is the only change present).
Fixes #933.
> Allow slicing with any type and with negative values.

- apis/python/setup.py
Ensures installation of scanpy 1.9.2, which includes the matplotlib fix: https://github.com/scverse/scanpy/releases/tag/1.9.2
> Remove matplotlib pin since scanpy is fixed.

- apis/python/tests/test_util_tiledb.py
- libtiledbsoma/src/pyapi/libtiledbsoma.cc
Even after #887 was submitted, I would occasionally see stats output written to the console after tests completed (when running with `-s`, to disable output capture by default). I believe this is due to buffering within `std::cout` where the text may not actually hit the fd by the time the function returns and the test ends.
It could have also potentially introduced confusing output:
print("before")
tiledbsoma_stats_dump()
print("after")
Depending upon how Python internally buffers `sys.stdout` and how that interacts with the system, the "before" could potentially appear after the `tiledbsoma_stats_dump` output (and it may be possible for "after" to appear *before* it? not sure about that).
Just letting Python handle it all with `py::print` is way easier.
> [c++/python] Use `py::print` in libtiledbsoma11 to print, not `cout`

- apis/python/src/tiledbsoma/_collection.py
- apis/python/src/tiledbsoma/_tdb_handles.py
- apis/python/src/tiledbsoma/_tiledb_object.py
- apis/python/src/tiledbsoma/io/ingest.py
- apis/python/tests/test_basic_anndata_io.py
- apis/python/tests/test_collection.py
- apis/python/tests/test_experiment_basic.py
For metadata: Keep track of the operations we need to do and perform them only when we close.
For group contents: Forbid the forbidden operations.
Detailed explanations available in the commit messages.
Fixes #919.
> [python] Stop using the flush hack when writing metadata or group contents

- apis/python/src/tiledbsoma/_tdb_handles.py
- apis/python/tests/test_metadata.py
> python: Include key–value pairs in metadata `repr`.

- apis/python/src/tiledbsoma/_tdb_handles.py
- apis/python/src/tiledbsoma/_tiledb_array.py
- apis/python/src/tiledbsoma/options/_soma_tiledb_context.py
- apis/python/tests/test_collection.py
- apis/python/tests/test_dataframe.py
- apis/python/tests/test_dense_nd_array.py
- apis/python/tests/test_platform_config.py
- apis/python/tests/test_sparse_nd_array.py
This eliminates the distinction between the timestamps used to read and write TileDB data. This ensures that:
- All data is written with the same timestamp.
- When one context is used to write and then read the same data, the same timestamp is used for both operations.
- A consistent view of a TileDB object is used for metadata when opening a handle for writing.
---
Given that all our tests pass, and this eliminates the "auxiliary read at time now" hack, I think this might be the right thing to do for this case.
> [python] Use the same timestamp across read and write operations

- Makefile
- apis/python/tests/test_dataframe.py
- libtiledbsoma/src/soma_reader.cc
- libtiledbsoma/test/unit_soma_reader.cc
#988 
**Changes:**
We've established the pattern that:
* `allow_duplicates=False` is the default
* `allow_duplicates=True` is supported with user caveats that uniqueness is the application's responsibility
Here we honor that pattern.
> [c++] Support `nnz` when `allow_duplicates=True`

- apis/r/DESCRIPTION
- apis/r/NEWS.md
- apis/r/R/SOMA.R
- apis/r/R/utils-seurat.R
- apis/r/tests/testthat/test_SOMA_Seurat.R
Seurat allows empty matrices for `counts` and `scale.data`
Empty matrices are defined as 0x0 or 1x1 with a value of `NA` 
Use `SeuratObject::IsMatrixEmpty` to determine empty matrices 
Skip writing empty matrices
fixes Tiledb-Inc/tiledbsc#92
> [r] Handle empty matrices when creating SOMA from Seurat

- apis/python/src/tiledbsoma/io/ingest.py
- doc/source/conf.py
- doc/source/python-api.rst
Just a few neatenings related to `readthedocs` format.
See `doc/README.md` in the base of this repo for how to render locally. Some example screenshots are here:
More work remains to do here for certain; nonetheless the updates on this PR are worth making.
> [python] A few minor readthedocs-related neatens

- .github/workflows/r-ci.yml
I was puzzled as to why, whenever we updated dependencies, the R build workflow would run despite R code not being changed. Turns out it was because the pre-commit configuration (which lives outside of the ignored Python directory) was triggering it to run.
Since R currently does not use pre-commit, we can safely ignore it, meaning that Python dependency changes will no longer trigger mysterious R workflows.
> Don't do R CI jobs on pre-commit changes.

- apis/python/src/tiledbsoma/_tiledb_array.py
- apis/python/src/tiledbsoma/options/_soma_tiledb_context.py
- apis/python/tests/test_platform_config.py
Storing timestamps in the Context is problematic since it is likely that users will want to share many parts of the Context across multiple open calls.  This would result in every object opened on that shared context having the same timestamp, and not just the child tree of a single open call from user code.  This is already an issue with Cell Census, which uses a single shared context for the entire duration of the program.
Because of this, it's better to have the timestamp be unset rather than having it set to context creation.
> [python Make the default timestamp in `SOMATileDBContext` be `None`

- apis/r/R/SOMASparseNdArray.R
- apis/r/man/SOMASparseNDArray.Rd
> [r] Make `SparseNDArray$write` arg name match Python/spec

- .pre-commit-config.yaml
- apis/python/setup.py
- apis/python/src/tiledbsoma/_dense_nd_array.py
- apis/python/src/tiledbsoma/_util.py
Upcoming `tiledbsoma` 1.0.0rc2 will get bugfix PR #1003 into a release. Along the way (secondarily), keeps latest-as-of-now `somacore` and `tiledbsoma` in sync.
> [python] Depend on somacore 1.0.0rc3

- .pre-commit-config.yaml
`pandas-stubs` released a new version on 2023-02-27, which caused builds to break despite no changes.  We should fix the new issues, but in the short term, just pin the stubs to the then-current version.
(See the build breakage from the last rev of #1001.)
> [python] Pin stub versions used in type checking

- apis/python/src/tiledbsoma/__init__.py
- apis/python/src/tiledbsoma/_collection.py
- apis/python/src/tiledbsoma/_common_nd_array.py
- apis/python/src/tiledbsoma/_dataframe.py
- apis/python/src/tiledbsoma/_exception.py
- apis/python/src/tiledbsoma/_factory.py
- apis/python/src/tiledbsoma/_general_utilities.py
- apis/python/src/tiledbsoma/_sparse_nd_array.py
- apis/python/src/tiledbsoma/_tiledb_array.py
- apis/python/src/tiledbsoma/_tiledb_object.py
- apis/python/src/tiledbsoma/options/_soma_tiledb_context.py
- libtiledbsoma/src/pyapi/libtiledbsoma.cc
Fixes #976 
Specifically, added tags to any class or function that is visible via pydocs, and validated with `python -m pydoc tiledbsoma`
This means that some superclass methods remain unannotated, but that seems fine at this point in time.
See also: https://github.com/single-cell-data/SOMA/pull/144
> lifecycle maturity tags

- apis/python/tests/test_dataframe_index_columns.py
- libtiledbsoma/src/pyapi/libtiledbsoma.cc
**Issue and/or context:** Found while implementing PR #1027 for issue #961.
**Changes:** The code here was not actually testing all four timestamp types. That unit-test oversight is fixed, as is the `libtiledbsoma` bug revealed thereby.
> [c++/python] Correctly handle all four timestamp types

- apis/python/src/tiledbsoma/_collection.py
- apis/python/src/tiledbsoma/_common_nd_array.py
- apis/python/src/tiledbsoma/_dataframe.py
- apis/python/src/tiledbsoma/_factory.py
- apis/python/src/tiledbsoma/_tdb_handles.py
- apis/python/src/tiledbsoma/_tiledb_array.py
- apis/python/src/tiledbsoma/_tiledb_object.py
- apis/python/src/tiledbsoma/_types.py
- apis/python/src/tiledbsoma/_util.py
- apis/python/src/tiledbsoma/options/_soma_tiledb_context.py
- apis/python/tests/test_collection.py
- apis/python/tests/test_dataframe.py
- apis/python/tests/test_dense_nd_array.py
- apis/python/tests/test_platform_config.py
- apis/python/tests/test_sparse_nd_array.py
This change is intended as one cohesive unit, but its three parts can be separated from each other if not wanted:
1. Adding a `tiledb_timestamp` parameter to `open`s to allow us to open entire collections in a timestamp-coherent manner.
2. Allowing users to pass that `tiledb_timestamp` as a Python datetime.
3. Making the `tiledb_timestamp` member on TileDB objects into a Python datetime (while the raw msec value is still available at `tiledb_timestamp_ms`.
This also removes the `timestamp_start` parameter, which seems like an advanced feature on top of the already advanced feature that is timestamps.
The overall goal is to provide the “expected” behavior, where opening a collection of objects acts like opening one object, and when you don’t specify a timestamp, things just work and you …
> [python] Allow all operations on a collection to share a timestamp

- apis/r/tests/testthat/test_SOMAExperiment-query.R
Last minute changes in #1030 broke two tests.
> [r] Fix test for X-layer assertions

- apis/python/src/tiledbsoma/_collection.py
- apis/python/tests/test_collection.py
#834, https://github.com/single-cell-data/TileDB-SOMA/issues/834#issuecomment-1452797584
**Changes:**
Use `kind` for collection type param in `CollectionBase.add_new_collection()`
> [python] Improve spec/impl consistency on `cls`/`type`/`kind` parameters

- .pre-commit-config.yaml
- apis/python/setup.py
- apis/python/src/tiledbsoma/_dense_nd_array.py
- apis/python/src/tiledbsoma/_util.py
Things this gives us:
- "kind" as child collection type parameter
- explicit dataframe sizing in the base spec
- more accurate types
- doc updates (maturity tags)
> [python] Depend on somacore 1.0.0rc4

- apis/python/src/tiledbsoma/_collection.py
- doc/local-build.sh
- doc/source/conf.py
https://github.com/single-cell-data/TileDB-SOMA/issues/977
**Changes:**
- Convert Python docstrings into [Google-style docstrings](https://google.github.io/styleguide/pyguide.html#38-comments-and-docstrings) 
1. For now, this only converts _collection.py. As I get feedback I will finish converting the remaining ones.
2. Do we want to regenerate the docs (at least locally) to see if this introduces formatting/design issues?
> [docs] Convert docstrings in `_collection.py` to Google style

- apis/r/README.md
The R README does not currently detail installation from source in the same detail as Python and C++
**Changes:**
Expanded README.md, tested locally.
#1032
[SC 25993](https://app.shortcut.com/tiledb-inc/story/25993/add-developer-information-to-the-wiki)
> [r] Expand developer instructions in README.md

- apis/python/version.py
Low-priority:
- more-thoroughly document why we currently use this instead of setuptools_scm
- enable use from any working directory
> [python] Polish `version.py`

- .github/workflows/python-packaging.yml
- apis/python/setup.py
**Issue and/or context:** #1051. The old pip solver (default on ubuntu 20.04) doesn't handle the numba's particular numpy version constraints when numba itself is only our transitive dependency (via scanpy).
**Changes:** After trying a bunch of things (see commit history) it seems that pinning the exact current numba version and also lifting up its numpy constraints is the least-bad solution. Also left a comment on when the pins can/should be relaxed, and tests the ubuntu 20.04 case in in the python-packaging workflow.
> [python] Constrain numba & numpy versions for compatibility with old pip solver

- apis/python/src/tiledbsoma/io/ingest.py
- apis/python/tests/test_basic_anndata_io.py
**Issue and/or context:** Some very common and very small datasets -- e.g. the ubiquitious `pbmc3k_processed` -- have their `X` stored as dense (`numpy.ndarray`). Ingesting these as dense makes them more awkward to query.
> [python] Support ingest of H5AD dense X as SOMA sparse X

- .pre-commit-config.yaml
- apis/python/setup.py
The upcoming `tiledbsoma` 1.0.0rc5 gets #1053 and #1061 into notebook author's hands. This PR brings in recent `somacore` docstring work (althoug there will be more such this week of course).
> [python] Depend on somacore 1.0.0rc5

- apis/r/R/SOMAArrayBase.R
Noticed while working with @mlin on dataset traversal in R.
Here is a repro script:
```
#!/usr/bin/env Rscript
library(tiledbsoma)
library(tiledb)
cat("Loading experiment:\n")
exp <- SOMAExperiment$new('path/to/data')
cat("\nGetting var:\n")
sdf <- exp$ms$get("RNA")$var
cat("\nDefining iterated read:\n")
sdf$read(iterated=TRUE)
cat("\nread_next 1:\n")
print(sdf$read_next())
cat("\nread_next 2:\n")
print(sdf$read_next())
```
Before this change, we see:
```
Loading experiment:
Getting var:
Defining iterated read:
read_next 1:
Table
60664 rows x 4 columns
$soma_joinid <int64 not null>
$feature_id <large_string not null>
$feature_name <large_string not null>
$feature_length <int64 not null>
read_next 2:
Error: Can't convert input object to pointer
```
With this change, we see:
```
Loading …
```
> [r] Avoid "Error: Can't convert input object to pointer"

- apis/r/tests/testthat/test_SOMAReader-Iterated.R
Follow on from #1082 -- thanks to @eddelbuettel
> [r] Don't doubly specify in a unit-test case

- apis/r/R/RcppExports.R
- apis/r/R/SOMAArrayBase.R
- apis/r/R/SOMADataFrame.R
- apis/r/R/SOMADenseNdArray.R
- apis/r/R/SOMASparseNdArray.R
- apis/r/man/soma_reader.Rd
- apis/r/src/RcppExports.cpp
- apis/r/src/rinterface.cpp
As reported by @mlin . Similar scenario as #1078 but with non-iterated readers.
Repro script:
```
#!/usr/bin/env Rscript
library(tiledbsoma)
library(tiledb)
uri <- 's3://.....'
config <- tiledb_config()
config["vfs.s3.region"] <- "us-west-2"
ctx <- tiledb_ctx(config)
cat("Loading experiment:\n")
exp <- SOMAExperiment$new(uri, ctx=ctx)
cat("\nGetting var:\n")
sdf <- exp$ms$get("RNA")$var
cat("\nDoing read:\n")
print(sdf$read())
```
This was failing to get the AWS region correct:
```
Error in soma_reader(uri = uri, colnames = column_names, qc = value_filter,  :
Error opening array: 's3://cellxgene-data-public/cell-census/2023-03-06/soma/census_data/homo_sapiens/ms/RNA/var'
[TileDB::Array] Error: Error while listing with prefix 's3://cellxgene-data-public/cell-census/2023-03-06/soma/census_da …
```
> [r] Handle config in non-iterated readers

- apis/python/src/tiledbsoma/_sparse_nd_array.py
- apis/python/tests/test_sparse_nd_array.py
A `SparseNDArray` can be created with a capacity that is too high for slices to be handled when reading a slice of the array. For instance, this is what gets created by default on my machine when converting a very small h5ad:
```
>>> X.shape
(9223372036854773760, 9223372036854773760)
>>> X.read((slice(0),)).coos().concat().to_scipy().todense()
ValueError: array is too big; `arr.size * arr.dtype.itemsize` is larger than the maximum possible size.
```
This issue makes working with the slices very difficult since scipy will refuse to densify the array (a similar behavior occurs when converting to a `csr_matrix`)
**Changes:**
This adds an optional parameter to `.coos()` that allows specifying a custom shape. This will be particularly useful when the exact shape of …
> [python] Add optional shape parameter to `SparseNDArrayRead .coos()`

- .pre-commit-config.yaml
- apis/python/setup.py
Brings in most recent somacore in prep for next rc of this package.
> [python] Depend on somacore 1.0.0rc6

- .readthedocs.yml
- apis/python/src/tiledbsoma/__init__.py
- apis/python/src/tiledbsoma/_dense_nd_array.py
- apis/python/src/tiledbsoma/_sparse_nd_array.py
- apis/python/version.py
- doc/source/gensidebar.py
- doc/source/python-api.rst
**Issue and/or context:** #1041 
**Changes:**
Gets Python API docs into `readthedocs`. 
Current preview link (not on main): https://tiledbsoma.readthedocs.io/en/kerl-readthedocs-initial/python-api.html
There's more work to do but this gets the bulk of the docs available on the web for users to see. In particular `readthdocs` still  needs a button poked manually; I don't have commit-triggers set up. Also some info about this (and R's `pkgdown`) needs to be written in this repo's developer wiki.
> [python] Get `readthedocs` going

- README.md
#1041 
**Changes:**
Link to the now-hosted docs
> Update `README.md` to include API docsites

- .github/workflows/python-ci-single.yml
- apis/python/requirements_dev.txt
- apis/python/setup.py
https://pypi.org/project/typeguard/3.0.0/ just dropped yesterday. As a result all new CI is failing with
```
from typeguard.importhook import install_import_hook
E   ModuleNotFoundError: No module named 'typeguard.importhook'
```
**Changes:**
Don't use typeguard 3.
> [python] Pin typeguard to < 3.0

- apis/r/R/SOMASparseNdArray.R
- apis/r/tests/testthat/test_SOMASparseNdArray.R
#1099
Quick hit here to set the `sparseMatrix` dims for non-iterated reads only. I have WIP on iterated reads, but ran into a few complications, so I'd like to keep working on that in additional PR(s) to come.
> [r] `SOMASparseNDArray$read_sparse_matrix`: set dims on the returned `sparseMatrix`

- apis/r/tests/testthat/test_SOMAReader-Iterated.R
RELATED: #1099, #1110
The existing tests "Iterated Interface from SOMA Sparse Matrix" were passing, but they were checking weird quantities in a way I doubt was intentional (but do correct me otherwise :). It checked that the sum of `dim(dat)[1]` over each returned `sparseMatrix` shard `dat` was 6596. This is a weird assertion because the whole test matrix has only 2638 rows. As we aren't yet expressly setting the dims of each `sparseMatrix` shard, `dim(dat)` defaults to (max row number with a nonzero entry, max column number with a nonzero entry) of each shard -- see `?Matrix::sparseMatrix`. As we progress in row-major order, the max row number keeps increasing to 2638 on the last iteration; thus the running total is much greater than nrow=2638.
This diff changes the test to verify …
> [r] Fix testing logic for iterated reads from `SOMASparseNDArray`

- apis/r/R/SOMASparseNdArray.R
- apis/r/tests/testthat/test_SOMAReader-Iterated.R
- apis/r/tests/testthat/test_SOMASparseNdArray.R
For iterated reads, I think the dims of each shard have to match the whole array shape, because in principle we could be returning entries from anywhere in the array.
It would be nice to have some other slot that would make it easy for the user to figure out the 'bounding box' of the returned shard, without having to do something cute like `nnzRows <- function(m) { sum(Matrix::rowSums(m != 0) > 0) }` (which is partly due to ChatGPT btw =). Not sure where to hang that though, any suggestions?
Should complete #1099
> [r] `SOMASparseNDArray$read_sparse_matrix`: set dims on iterated `sparseMatrix` parts

- .github/workflows/pkgdown.yaml
Every push or pull request currently triggers `pkgdown` rebuilds which is more than is needed.  
**Changes:**
Limits triggers to releases and manual calls (aka `workflow_dispatch` see [here](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#workflow_dispatch))
[SC 26530](https://app.shortcut.com/tiledb-inc/story/26530/tiledbsoma-ci-burns-too-many-cycles-for-pkgdown)
> [r] Limit pkgdown runs to releases and manual triggers

- .github/workflows/python-ci-full.yml
- .github/workflows/python-ci-minimal.yml
Appears to fix current main CI...unclear if setting gcc was intentional, and we do NOT do that for the wheel builds.
> [ci] Ensure macOS builds use clang instead of gcc

- .github/workflows/python-packaging.yml
- apis/python/MANIFEST.in
- apis/python/setup.py
- apis/python/src/tiledbsoma/_general_utilities.py
- scripts/show-versions.py
Recent changes resulted in wheel-build failures. This PR takes input from @nguyenv, @mlin, and myself to solve this problem.
Note this is a neaten of the exploratory PR #1113. We do not run wheel builds on every PR, pre-merge or post-merge -- only on releases, and in a nightly cron. #1113 contains the fixes here, and it also has a dev-only tweak to run wheel builds pre-merge. That is how this current PR was validated.
> [python] Fix wheel builds given recent Conda-related changes

- doc/source/conf.py
- doc/source/index.rst
- doc/source/notebooks/tutorial_exp_query.ipynb
- doc/source/notebooks/tutorial_soma_objects.ipynb
- doc/source/notebooks/tutorial_soma_reading.ipynb
https://github.com/single-cell-data/TileDB-SOMA/issues/1017
**Changes:**
Add notebooks as tutorials
> [docs] Add notebooks as tutorials to the docsite

- .github/workflows/r-cmd-check.yaml
In the `main-old` branch,  PR #1100 accomodated setting 'legacy validity' and needed to (temporarily) install tiledb-r from GitHub to have access to a new enough version 0.18.0.3.  As 0.19.0 is now on CRAN we can revert this.
**Changes:**
Revert one add block in the CI yaml
[SC 26661](https://app.shortcut.com/tiledb-inc/story/26661/revert-use-of-github-tiledb-in-main-old-ci)
> [r] Revert back to CI use of tiledb-r from CRAN

- apis/python/src/tiledbsoma/io/ingest.py
- apis/python/tests/test_basic_anndata_io.py
**Issue and/or context:** In support of #1135, as not all SOMA experiments have a `var` with a column named `var_id` -- it may be `feature_id`, or something else.
> [python] Allow `to_anndata` when `feature_id` not `var_id` is in `var` columns

- apis/python/setup.py
In the case where we passed `--libtiledbsoma=...` to the builder, `libtiledbsoma_dir` would end up being a string rather than a Path, so we couldn't do `/` operations on it.
> Ensure that `libtiledbsoma_dir` is always a `pathlib.Path`.

- apis/r/R/SOMADenseNdArray.R
- apis/r/man/SOMADenseNDArray.Rd
The `write` member class is currently limited to matrices; reads can take more dimensions.  This can be extended as needed.
**Changes:**
Documentation has been updated in the R file, and the generated Rd file.
Mostly following earlier Slack discussion
[SC 26798](https://app.shortcut.com/tiledb-inc/story/26798/clarify-densendarray-writes-limited-to-matrices)
> [r] Clarify status of DenseNDArray writes and matrices

- apis/python/src/tiledbsoma/__init__.py
- apis/python/src/tiledbsoma/_dataframe.py
- apis/python/src/tiledbsoma/_factory.py
- apis/python/src/tiledbsoma/_read_iters.py
- apis/python/src/tiledbsoma/_sparse_nd_array.py
- apis/python/src/tiledbsoma/_tiledb_array.py
- apis/python/src/tiledbsoma/io/ingest.py
- apis/python/src/tiledbsoma/pytiledbsoma.cc
https://github.com/single-cell-data/TileDB-SOMA/issues/1089
This PR doesn't touch in-package links -- those will be a separate PR
> [docs/python] Add more external links for docsite

- apis/r/DESCRIPTION
- apis/r/R/SOMAExperimentAxisQuery.R
`matrix::sparseMatrix` drops unused rows/columns at the end of the matrix. This causes issues when reading in an `X` layer to a Seurat assay 
As a fix, explicitly set the matrix shape to `c(query$n_obs, query$n_vars)` when reading
> [R] Fix reading very sparse assays

- apis/system/tests/test_densendarray_write_python_read_r.py
- apis/system/tests/test_densendarray_write_r_read_python.py
https://github.com/single-cell-data/TileDB-SOMA/issues/435
**Changes:**
- Add a pair of tests for DenseNDArray
- The Python->R testing creates a 3-dimensional array (for generality)
- The R->Python testing creates a 2-dimensional array (right now, it looks like that's the only way you can create a DenseNDArray in R)
> [r][python] DenseNDArray R-Python roundtrip testing

- libtiledbsoma/CMakeLists.txt
- libtiledbsoma/cmake/inputs/Config.cmake.in
- libtiledbsoma/src/CMakeLists.txt
This setups installation of the cmake targets and config for libtiledbsoma. This allows other cmake packages to correctly detect and inhert the build targets for libtiledbsoma.
> [c++] Install cmake Target and Config for libtiledbsoma

- apis/python/src/tiledbsoma/io/ingest.py
- apis/python/tests/test_basic_anndata_io.py
This ingests `uns` data into a similar structure to what v0.1.x does: a nested collection of groups, TileDB objects, and metadata.
- Scalar values are ingested as metadata entries.
- Pandas dataframes are ingested as SOMA dataframes, using the same logic as non-uns dataframes.
- Numpy ndarrays are ingested as SOMA dense ndarrays.
> [python] Ingest `uns` values from AnnData files

- .pre-commit-config.yaml
- apis/python/setup.py
**Issue and/or context:** #1089
**Changes:** The sole change on `somacore` 1.0.1 is more lifecycle-experimental tags for things imported into `tiledbsoma`.
> [python] Depend on somacore 1.0.1

- apis/r/tools/r-ci.sh
CI for R on Ubuntu takes advantage of binary packages and the newest version of the `bspm` improves some corner case.  This is the same change just made for tiledb-cloud-r.
**Changes:**
In essence reactivate one bahavior option to consider source as well once binaries have been used.
[SC 26820](https://app.shortcut.com/tiledb-inc/story/26820/update-ci-with-a-new-bspm-release-and-configuration)
> [r] Tweak CI on Ubuntu by taking advantage of newest bspm release

- apis/r/R/utils-tiledb.R
Small 'quality of life' improvement also showing OS version
**Changes:**
Adds a line to the helper function:
```r
> tiledbsoma::show_package_versions()
tiledbsoma:    0.0.0.9014
tiledb-r:      0.19.0.1
tiledb core:   2.16.0
libtiledbsoma: libtiledbsoma=d5492c54-modified;libtiledb=2.16.0
R:             R version 4.2.3 (2023-03-15)
OS:            Ubuntu 22.10
> 
```
closes #1148
[SC 26873](https://app.shortcut.com/tiledb-inc/story/26873/also-show-utils-osversion-when-showing)
> [r] Also show osVersion when displaying package versions

- apis/r/DESCRIPTION
- apis/r/R/SOMAExperimentAxisQuery.R
Set cell names in cell-level meta data with `row.names<-` instead of `as.data.frame()`; addresses issue where returned cell-level meta data had `NAs` instead of actual values
```R
> expt <- tiledbsoma::SOMAExperimentOpen(
"s3://cellxgene-data-public/cell-census/2023-03-16/soma/census_data/mus_musculus",
tiledbsoma_ctx = tiledbsoma::SOMATileDBContext$new(c("vfs.s3.region" = "us-west-2"))
)
> obs_query <- tiledbsoma::SOMAAxisQuery$new(
value_filter = "tissue_general == 'vasculature'"
)
> var_query <- tiledbsoma::SOMAAxisQuery$new(
value_filter = "feature_name %in% c('Gm53058', '0610010K14Rik')"
)
> expt_query <- tiledbsoma::SOMAExperimentAxisQuery$new(
expt, "RNA",
obs_query = obs_query,
var_query = var_query
)
> seurat <- expt_query$to_seurat(
c(counts = "raw"),
obs_column_names = …
```
> [R] Fix `to_seurat()` cell-level meta data

- apis/python/setup.py
- apis/python/src/tiledbsoma/_general_utilities.py
Conda issue: https://github.com/TileDB-Inc/tiledbsoma-feedstock/pull/9#issuecomment-1486852905
Reverts https://github.com/single-cell-data/TileDB-SOMA/pull/1177/commits/70cce388ae5dd81d5d371b265e5c5f4573569c45
> [python] Don't use `distro` in `show_package_versions`

- apis/python/README.md
The `main-old` branch is defunct and no longer needs to be documented.
**Changes:**
- Remove `main-old` branch documentation
- Link to abstract spec in top summary line
- Link to platform_config docs in spec
> Remove main-old branch documentation

- apis/r/DESCRIPTION
- apis/r/R/RcppExports.R
- apis/r/R/SOMADataFrame.R
- apis/r/R/SOMADenseNdArray.R
- apis/r/R/SOMASparseNdArray.R
- apis/r/man/ConfigList.Rd
- apis/r/man/PlatformConfig.Rd
- apis/r/man/SOMAArrayBase.Rd
- apis/r/man/SOMACollection.Rd
- apis/r/man/SOMACollectionBase.Rd
- apis/r/man/SOMAContextBase.Rd
- apis/r/man/SOMADataFrame.Rd
- apis/r/man/SOMADenseNDArray.Rd
- apis/r/man/SOMAExperiment.Rd
- apis/r/man/SOMAMeasurement.Rd
- apis/r/man/SOMASparseNDArray.Rd
- apis/r/man/SOMATileDBContext.Rd
- apis/r/man/ScalarMap.Rd
- apis/r/man/TileDBArray.Rd
- apis/r/man/TileDBGroup.Rd
- apis/r/man/roxygen/templates/param-result-order.R
- apis/r/src/RcppExports.cpp
**Issue and/or context:** #1195
**Changes:** A follow-up to #1195 that updates the documentation for `result_order` to remove invalid options: global_order and unordered. I've also set the result_order default to "auto" for all reader functions.
**Notes for Reviewer:** GitHub Actions is currently suffering an outage so no CI atm. However, I did validate this locally and confirmed it addresses the minor issue introduced in #1195.
> [r] Update result_order docs and defaults

- libtiledbsoma/include/tiledbsoma/soma_array_reader.h
> [c++] Final rename `SOMA_READER` -> `SOMA_ARRAY_READER`

- libtiledbsoma/cmake/Modules/FindCatch_EP.cmake
The third-party `catch2` package has
```
/Users/johnkerl/git/single-cell-data/TileDB-SOMA/build/libtiledbsoma/_deps/catch2-src/src/catch2/catch_session.cpp:64:25: warning: variable 'reporterIdx' set but not used [-Wunused-but-set-variable]
std::size_t reporterIdx = 0;
```
which is not new,  but, newly this errors out in MacOS 13.3 (which yours truly installed just today).
**Changes:**
Since we don't control this third-party library but we do control how we compile it, apply the correct flags.
> [c++] Fix build on MacOS 13.3

- libtiledbsoma/src/version.cc
As in #1193. The commit-hash information is (a) not always available; (b) never useful to the end user; (c) completely superseded now that we are (as we have been for some months now) doing tagged releases on `main`.
> [c++] Omit no-longer-needed libtiledbsoma commit-hash info from `show_package_versions`

- apis/r/R/SOMADataFrame.R
- apis/r/R/SOMADenseNdArray.R
- apis/r/R/SOMAExperimentAxisQuery.R
- apis/r/R/SOMASparseNdArray.R
- apis/r/R/utils-assertions.R
- apis/r/src/rinterface.cpp
- apis/r/tests/testthat/test_SOMADataFrame.R
- apis/r/tests/testthat/test_SOMAExperiment-query.R
In #1171 @mlin points out some usabilit shortcomings with an axis query.  This PR addresses one of the two concerns and lifts the requirement for explicit `as.integer64()` casts.  Changing the naming is a litte tricker as can be confronted with one or two dimension data sets and use a list with names if case fewer than all dimensions are constrained in the query.
**Changes:**
Integer vectors are now converted to `integer64` as needed.
#1171
[SC 27100](https://app.shortcut.com/tiledb-inc/story/27100/r-improve-usability-of-somaaxisquery-coords)
> [r] Upcast axis query coords to integer64

- apis/r/R/SOMAArrayBase.R
- apis/r/R/SOMADataFrame.R
- apis/r/R/SOMADenseNdArray.R
- apis/r/R/SOMASparseNdArray.R
- apis/r/R/SOMATileDBContext.R
- apis/r/R/TileDBArray.R
- apis/r/R/TileDBGroup.R
- apis/r/R/TileDBObject.R
- apis/r/man/SOMATileDBContext.Rd
Per #1011 and the spec, an accessor named `context()` is desired.
**Changes:**
The _existing_ one is renamed in the R code and the generated Rd documentation.  Tests are not affected.
closes #1011
[SC 27095](https://app.shortcut.com/tiledb-inc/story/27095/r-add-a-context-accessor)
> [r] Provide `context()` accessor

- apis/r/configure
https://github.com/single-cell-data/TileDB-SOMA/issues/1220
Different Linux distros install libraries to different directories. On Debian-based systems libraries may be installed into `lib` or `lib/x86_64-linux-gnu`. On Fedora-based, they are installed into `lib64`.
**Changes:**
`Makevars` includes a link to `lib/libtilesoma.a`. To account for the fact that not all distros install to `lib`, we now copy `libtiledbsoma.a` into `lib` in `configure` as suggested by @eddelbuettel.
> [r] Static library is configured to install to `lib`

- apis/python/src/tiledbsoma/_tdb_handles.py
- apis/r/tools/get_tarball.R
- libtiledbsoma/cmake/Modules/FindTileDB_EP.cmake
**Issue and/or context:** #1169. See also a follow-on tracker which is #1198.
See also #1222
> [python] Avoid context leak on group-set-timestamp operation; use TileDB Embedded 2.15.1

- apis/python/devtools/ingestor
- apis/python/src/tiledbsoma/io/ingest.py
Solves #1223.
**Changes:**
Wire `context` all the way from `tiledbsoma.io.from_anndata` to group/array I/O methods.
I don't have ideas for unit-testing strategy.
What I did to test locally:
```
unset AWS_ACCESS_KEY_ID
unset AWS_SECRET_ACCESS_KEY
unset AWS_DEFAULT_REGION
```
Then edit `cfg.txt` and put in
```
vfs.s3.aws_access_key_id ***
vfs.s3.aws_secret_access_key ****
vfs.s3.region us-east-1
```
Then
```
ingestor --tiledb-config cfg.txt /path/to/local.h5ad s3://bucket/path
```
> [python] Wire `context` through `tiledbsoma.io.from_anndata`

- apis/python/src/tiledbsoma/_common_nd_array.py
- apis/python/src/tiledbsoma/options/_tiledb_create_options.py
Found while working on #1223, #1224, and some performance analysis.
> [python] Put `capacity` on the same footing as other `PlatformConfig` parameters

- apis/python/devtools/ingestor
**Issue and/or context:** This was useful on #1223; also very useful on some parameter-tuning work I'm doing.
**Changes:** Allows `devtools/ingestor` to get saved-off `tiledb.Config` and `PlatformConfig` from files at the command line.
**Notes for the reviewer:** This PR wires the `context` from the CLI to `tiledbsoma.io`. #1224 wires it from there.
Sample invocation:
```
ingestor --platform-config-file=pc.json --tiledb-config-file cfg.txt ~/s/a/pbmc-small.h5ad ~/s/v/pbmc-small
```
> [python] Support CLI config arguments in `devtools/ingestor`

- apis/r/R/SOMADataFrame.R
- apis/r/R/SOMADenseNDArray.R
- apis/r/R/SOMASparseNDArray.R
- apis/r/tests/testthat/test-SOMAArrayReader-Iterated.R
The common `read()` accessor for data frames and (dense and sparse) arrays has a boolean toggle `iterated`. When true, one-shot reads are attempted (subject to the memory budget constraints).  
When false, we had previously pushed the responsibility of iterating to the user.  This PR suggests to change that and to return a list of Arrow Table objects to the user.
A list is _the_ fundamental 'large' data structure in R. It is common and well understood; users can then proceed to iterated over the chunks as needed.
**Changes:**
A rather small code change for each of the three accessors along with a simplification in the unit tests as the test no longer needs to loop.
[SC 27280](https://app.shortcut.com/tiledb-inc/story/27280/r-provide-iterate …
> [r] Return lists of Arrow 'Table' objects in `read(iterated=TRUE)`

- apis/r/configure
PR #1221 had a one-char typo in its 'else' branch:  `lib` and `x86_64-linux-gnu` were not separated.
**Changes:**
The typo is corrected and the statement is moved before the subsequent `cd ..` making it a little shorter and more succinct.
No new code.
Attempts to test this at the R-Hub builder service failed, as it did at the 'mac-builder' provided by CRAN.  Dependencies of this package are somewhat extensive and attempts to install all of these from source failed :-/  In at least one case simply because `cmake` was not around.  Such is life.  
We also made two different attempts to address this via `cmake`, neither one was successful.  Doing it from `cmake` has the added risk of being dependent on a particular version of the tool.  So …
> [r] Correct typo and minor edit to configure

- apis/python/src/tiledbsoma/_common_nd_array.py
- apis/python/src/tiledbsoma/_dataframe.py
- apis/python/src/tiledbsoma/options/_tiledb_create_options.py
More of #1229. Found at https://github.com/single-cell-data/TileDB-SOMA/pull/1216#discussion_r1161724856.
> [python] Put `allows_duplicates` on the same footing as other `PlatformConfig` parameters

- .github/workflows/python-packaging.yml
cf. https://github.com/single-cell-data/TileDB-SOMA/issues/1226#issuecomment-1501009554
This at least stops GitHub from choking on the YAML. I doubt the PyPI publishing will actually work yet, but we can come back to that a bit later since we can fall back on manual publishing.
> [ci] Fix publish_to_pypi.yml parse error

- libtiledbsoma/cmake/Modules/FindCatch_EP.cmake
As tracked on #1226, #1206 fixed a MacOS build error for version 13 but introduced one for MacOS 11.
> [c++] Update MacOS 13 check from #1206

- .github/workflows/daily-test-build-issue-template.md
- .github/workflows/python-packaging.yml
This will help to more quickly surface failures like the one fixed by #1226.
**Changes:**
Cloned shamelessly from https://github.com/TileDB-Inc/TileDB-Py.
> [ci/python] Auto-create a GH issue on nightly CI fail

- doc/source/tutorials.rst
This file was missing and prevented the tutorials from being added to the docsite
**Changes:**
> [docs/python] Add `tutorials.rst`

- apis/python/setup.py
Context: https://github.com/TileDB-Inc/tiledbsoma-feedstock/pull/11#issuecomment-1505662937
> [python] Pin anndata to < 0.9 since it doesn't support Python 3.7 like we do

- apis/r/DESCRIPTION
- apis/r/R/SOMAExperimentAxisQuery.R
- apis/r/R/utils-seurat.R
- apis/r/tests/testthat/test-SeuratOutgest.R
Following discussion about #1200, `query$to_seurat()` and `query$to_seurat_reduction()` now expect arrays in `obsm` and `varm` to be sparse. Warnings are thrown if arrays are dense, but will continue to read them.
See also #1245.
> [r] Seurat outgestors expect sparse arrays in `obsm` and `varm`

- apis/python/src/tiledbsoma/_experiment.py
- apis/python/src/tiledbsoma/_tiledb_object.py
TileDB Cloud uses the `dataset_type` key to provide richer information about datasets. They need to be set on the root Experiment.
> [python] Write TileDB Cloud–specific metadata to Experiments

- apis/python/src/tiledbsoma/io/ingest.py
Entries in `uns` may be read as numpy scalars rather than native Python types (e.g. `numpy.float64` rather than `float`). We only accept normal Python values in metadata, so unwrap those numpy scalars.
> Unwrap numpy scalar values when importing `uns` data.

- apis/r/DESCRIPTION
- apis/r/R/TileDBGroup.R
**Changes:** This refines member cache handling in the `TileDBGroup` class.
**Notes for Reviewer:** When adding a new member, the original URI is now preserved in the member cache.
> [r] Refine group member caching behavior

- apis/r/tools/r-ci.sh
We found on another R package that `R-latest.pkg` doesn't exist. Update here thanks to @eddelbuettel .
> [r/ci] Update R MacOS CI, given R 4.3.0

- .github/workflows/python-ci-full.yml
- .github/workflows/python-ci-minimal.yml
- apis/python/setup.py
This is a trial balloon for #544, to see what we would need to do to support Python 3.11.
First result: at https://github.com/single-cell-data/TileDB-SOMA/actions/runs/3661926647/jobs/6190605155 we see `numba` is not yet supported in Python 3.11. cc @thetorpedodog @bkmartinjr @Shelnutt2 .
```
Collecting numba>=0.41.0
Downloading numba-0.56.4.tar.gz (2.4 MB)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.4/2.4 MB 146.6 MB/s eta 0:00:00
Preparing metadata (setup.py): started
Running command python setup.py egg_info
File "<string>", line 2, in <module>
File "<pip-setuptools-caller>", line 34, in <module>
File "/tmp/pip-install-0tpo_aju/numba_b1ec8a6b557b450ea19a316e9668617a/setup.py", line 51, in <module>
_guard_py_ver()
File …
```
> [python/ci] Include Python 3.11 in CI matrix

- apis/python/src/tiledbsoma/_dataframe.py
- apis/python/src/tiledbsoma/io/ingest.py
- apis/python/tests/test_basic_anndata_io.py
Cast Numpy nulls (eg. NaN) to an arrow null when writing data frames. Necessary when obs/var in AnnData/h5ad contain nulled columns
Reprex:
```python
import os
import shutil
import tiledbsoma.io
import tempfile
import pandas as pd
import scanpy as sc
import numpy as np
SOMA_PATH = os.path.join(tempfile.gettempdir(), "soma-exp")
tiledbsoma.logging.debug()
adata = sc.datasets.pbmc3k()
adata.obs["empty"] = pd.Categorical(
[np.NaN] * adata.n_obs, dtype=pd.CategoricalDtype(categories=[], ordered=False)
)
if os.path.exists(SOMA_PATH):
print(f"Removing existing SOMA: {SOMA_PATH}")
shutil.rmtree(SOMA_PATH)
tiledbsoma.io.from_anndata(
experiment_uri=SOMA_PATH, anndata=adata, measurement_name="RNA"
)
```
> [python] Explicit casting of Numpy nulls to Arrow nulls

- apis/system/tests/test_write_anndata_read_seurat.py
#1184 
**Changes:**
Adds an AnnData -> SOMA -> Seurat using the existing python/R framework
1. It is possible to add more assertions if desired (e.g. on the X layer)
2. It is possible to replicate the tests on different artifacts. This one uses a stripped down version of pbmc3k that was already in the repo
3. Right now, the R side requires a query since `to_seurat` is only available at a query level. Eventually it will be available on `SOMAExperiment` (#1261) and this test should be updated to be simpler.
4. Right now we can only do one "trip" of the test, since Seurat -> SOMA isn't in main yet (it's [here](https://github.com/single-cell-data/TileDB-SOMA/pull/1146) though). Once this is merged we can add the other test.
> [r][python] Create an AnnData -> SOMA -> Seurat test 

- apis/r/R/SOMAExperimentAxisQuery.R
- apis/r/tests/testthat/test-SeuratOutgest.R
Apparently, calling `paste()` on `objs_joinids()` or `var_joinids()` no longer works. This changes all calls to `objs_joinids()` and `var_joinids()` in the Seurat outgestors to `objs_joinids()$as_vector()` and `var_joinids()$as_vector()`
> [r] Coerce `obs_joinids()` and `var_joinids()` to vectors

- apis/python/src/tiledbsoma/_experiment.py
- apis/r/R/SOMACollectionBase.R
This follows on #1260 to always set the `dataset_type` key on SOMA Experiments.
> [python/r] Always write TileDB Cloud–specific metadata to Experiments

- apis/python/setup.py
**Issue and/or context:** Normally in our `setup.py` we pin like `tiledb==0.21.*`. However, I found the following today:
* I have an EC2 instance I normally leave powered off. It had a recent `tiledbsoma` version, and therewith, `tiledb-py 0.21.1` 
* Today I did `pip install tiledbsoma`
* This upgraded `tiledbsoma` to 1.2.2 (recent) but it left `tiledb-py` as-is, at 0.21.1.
* However we _truly require features_ from 0.21.2 -- in particular the new `config` argument to `Group`
* I had to manually `pip install -U tiledb`. Our users shouldn't have to.
(Side note: our `tiledbsoma`-to-core dependency is fine: https://github.com/single-cell-data/TileDB-SOMA/blob/main/libtiledbsoma/cmake/Modules/FindTileDB_EP.cmake)
> [python] Require TileDB-Py >= 0.21.1

- apis/python/setup.py
It was brought up to me that using `tiledb>=0.21.2` could result in v0.22.0 matching, which is not what we want (this would cause a core version mismatch, which is Bad™). Instead, we should pin to `~=0.21.2`, which means "any v0.21.x version where x >= 2".
> Tighten TileDB pypi dependency to be a 0.21.x version.

- libtiledbsoma/src/utils/util.cc
- libtiledbsoma/src/utils/util.h
When running _TileDB-SOMA Python CI (Full)_, we fail when building with error `no member named 'memcpy' in namespace 'std'`. This was not caught when running the minimal CI tests.
**Changes:**
Include `cstring` header in `utils/util.h`.
Full CI run working [here](https://github.com/single-cell-data/TileDB-SOMA/actions/runs/4832925550).
> [c++] Add `cstring` Header to `util.cc`

- apis/python/setup.py
- apis/r/DESCRIPTION
- apis/r/tools/get_tarball.R
- libtiledbsoma/cmake/Modules/FindTileDB_EP.cmake
**Issue and/or context:** As these packages are now released.
**Changes:**
**Notes for Reviewer:** See also https://github.com/TileDB-Inc/tiledbsoma-feedstock/pull/17
> [c++/r/python] Update to core 2.15.2, TileDB-Py 0.21.3, TileDB-R 0.19.1

- libtiledbsoma/src/CMakeLists.txt
https://github.com/single-cell-data/TileDB-SOMA/issues/1317
The source files are getting installed alongside the header files as of #1301.
**Changes:**
Explicitly list out header files to install instead of using wildcard matching.
> [c++] Do not install source files

- apis/python/src/tiledbsoma/pytiledbsoma.cc
- apis/r/src/rinterface.cpp
- apis/r/src/riterator.cpp
- libtiledbsoma/src/cli/cli.cc
- libtiledbsoma/src/soma/managed_query.h
- libtiledbsoma/src/soma/soma_array.cc
- libtiledbsoma/src/soma/soma_array.h
- libtiledbsoma/test/unit_soma_array.cc
https://github.com/single-cell-data/TileDB-SOMA/issues/926
**Changes:**
- Add `SOMAArray` metadata methods and test
- `SOMAArray::open` now also takes in mode as required argument
> [c++] Add Array metadata methods

- apis/r/R/SOMAExperimentAxisQuery.R
- apis/r/R/write_seurat.R
- apis/r/R/write_soma.R
- apis/r/man/write_soma.Rd
- apis/r/man/write_soma.Seurat.Rd
- apis/r/tests/testthat/test-SeuratIngest.R
- Improved messaging for `to_seurat()`
- Silence unnecessary warnings for default arguments
- Silence duplicate warnings emitted by `to_seurat()` and downstream methods
- Improve messaging about ingesting extended assays
- `write_soma.Seurat()` now returns the URI instead of the experiment to be more inline with Python
> [r] Seurat <> SOMA Integration Improvements

- apis/python/src/tiledbsoma/_experiment.py
- apis/python/src/tiledbsoma/_measurement.py
Takes expanded copy from the `somacore` package and adds an example for `Experiment`.
Suggestions and adding other relevant reviewers welcome. Fixes #974.
> [docs/python] Expand docstrings for `Experiment` and `Measurement`

- libtiledbsoma/src/external/include/thread_pool/producer_consumer_queue.h
- libtiledbsoma/src/external/src/thread_pool/thread_pool.cc
The logger interface moved to soma/ and two more files need an adjustment,
**Changes:**
For two include paths:  `s/tiledbsoma/soma/`
[SC 28590](https://app.shortcut.com/tiledb-inc/story/28590/leftover-path-adjustment)
> [c++] Adjust two more include paths

- scripts/bld
The C++ library build used to, but no longer does, have an option to do something special for R.  It now redundant and can be removed
**Changes:**
Removal in `scripts/bld`
[SC 28611](https://app.shortcut.com/tiledb-inc/story/28611/remove-remaining-traces-of-r-build-from-bld)
> [c++] Remove unused references to removed R_BUILD option

- libtiledbsoma/CMakeLists.txt
#1344 removed the no-longer-needed 'build for R' option from `bld`; it failed to also address `CMakeLists.txt`.
**Changes:**
Simplify `CMakeLists.txt` by removing the remaining (unused) lines for a (no longer available or needed) build for R use.
[SC 28648](https://app.shortcut.com/tiledb-inc/story/28648/remove-remaining-traces-of-build-r-from-cmakelists-txt)
> [c++] Remove remaining traces of BUILD_R from library CMakeLists.txt

- apis/r/tests/testthat/helper-test-data.R
- apis/r/tests/testthat/helper-test-soma-objects.R
This is a line-count-reducing PR which will help simplify #1325.
It puts the helpers which make SOMA data `helper-test-soma-objects.R` and leaves the ones that do not in `helper-test-data.R`.
> [r] Put like with like in test-helpers

- apis/r/R/Factory.R
- apis/r/R/SOMADataFrame.R
- apis/r/tests/testthat/helper-test-data.R
- apis/r/tests/testthat/test-Factory.R
- apis/r/tests/testthat/test-SOMADataFrame.R
Found on PR #1325 for issue #1346.
This is a simple Python/R parity issue.
> [r] Allow default `index_column_names=c("soma_joinid")`

- apis/python/src/tiledbsoma/_collection.py
- apis/python/src/tiledbsoma/_common_nd_array.py
- apis/python/src/tiledbsoma/_dataframe.py
- apis/python/src/tiledbsoma/_util.py
- apis/python/src/tiledbsoma/io/ingest.py
- apis/python/tests/test_io.py
Resolves a UX issue encountered yesterday.
Note that Python doesn't do run-time type-checking.
We do have types enabled, and we do have CI for `ruff` and `mypy`, and we do have `typeguard` enabled in our CI which _does_ enforce run-time type checking at CI time -- for all code within this package.
However, `typeguard` is not used at runtime outside of CI, so we must add manual checks at the user interface where arguments are coming from out-of-package. This PR is one in a series of several PRs wherein we manually add a type-check to a crucial argument.
> [python] Add run-time type checks to `PlatformConfig` on ingest/create

- README.md
closes #1374 
As discussed in #1374 we can add two badges to link to packages
**Changes:**
Adds two lines of markdown (and, while at it, ensures each new section ('two hashes') has two empty lines in front of it which reads more clearly
#1374
[SC 28916](https://app.shortcut.com/tiledb-inc/story/28916/extend-readme-with-two-package-to-pypi-and-r-universe)
> [python,r] Added two badges (and ensure consistent two break before sections)

- apis/r/inst/include/tiledbsoma_types.h
When checking the package with `R CMD check`, a NOTE is issued because output is directed to `stderr` which R and CRAN dislike.  Per _Writing R Extensions_ all output should go via R's own io buffers to be nicely synchronised.
This actually comes from `spdlog` and it is something I noticed a few years ago, and convinced upstream to accomodate with a very simple (double) switch (from [here](https://github.com/gabime/spdlog/blob/57a9fd0841f00e92b478a07fef62636d7be612a8/include/spdlog/logger-inl.h#L250-L254) in current sources, in our version in another file but 
```c++
#if defined(USING_R) && defined(R_R_H) // if in R environment
REprintf(null, err_counter, date_buf, name().c_str(), msg.c_str());
#else
std::fprintf(stderr, null, err_counter, date_buf, …
```
> [r] Set #define so that spdlog uses REprintf

- apis/r/NEWS.md
- apis/r/inst/include/tiledbsoma_types.h
- apis/r/src/Makevars.in
- apis/r/src/rinterface.cpp
- apis/r/src/riterator.cpp
- apis/r/src/rutilities.cpp
- apis/r/src/stats.cpp
- apis/r/src/version.cpp
With the different PRs adding polish and suppressing warnings we were down to two:  one concern the fact that we used a (so-called) non-portable flag to suppress deprecations warning -- so I took this inside the source files instead. The other concerned the (incomplete) NEWS file which was lacking a version to match a checking regexp, so I added that.
**Changes:**
See above.  No code or test changes.  But now beautiful 'Status: OK' without any nags.
[SC 29034](https://app.shortcut.com/tiledb-inc/story/29034/avoid-remaining-nags-from-r-cmd-check)
> [r] Address remaining two R CMD check nags

- apis/r/R/SOMACollectionBase.R
- apis/r/R/TileDBGroup.R
- apis/r/R/write_seurat.R
- apis/r/R/write_soma.R
- apis/r/tests/testthat/test-SeuratOutgest-graph.R
- apis/r/tests/testthat/test-SeuratOutgest-object.R
- apis/r/tests/testthat/test-SeuratOutgest-reduction.R
Addresses #1378:
* Remove `mode` optarg on `collection$get`
* Have opened children inherit parent's mode
> [r] Update mode semantics for implicit open

- apis/python/src/tiledbsoma/_dataframe.py
- apis/python/src/tiledbsoma/_dense_nd_array.py
- apis/python/src/tiledbsoma/_sparse_nd_array.py
- apis/python/src/tiledbsoma/_tiledb_array.py
Note that fragment metadata and commits are easy to consolidate and we should always do it immediately post-write. This is not to be confused with consolidating array data, which is opt-in.
Tracked in SC-25195.
**Changes:** Leverages TileDB Cloud 2.15.
> [python] Auto-consolidate fragment metadata and commits

- apis/r/R/write_seurat.R
- apis/r/tests/testthat/test-SeuratIngest.R
**Issue and/or context:** When a Seurat object is created with a single matrix it populates the `Assay`'s `counts` _and_ `data` slots with the same data.
```r
library(SeuratObject)
data("pbmc_small")
counts_mat <- GetAssayData(pbmc_small[["RNA"]], "counts")
seurat_obj <- CreateSeuratObject(counts = counts_mat)
seurat_obj
```
Retrieve the `counts` slot:
```r
GetAssayData(seurat_obj, "counts")[1:10, 1:5]
```
Retrieve the `data` slot:
```r
GetAssayData(seurat_obj, "data")[1:10, 1:5]
```
Verify they're identical:
```r
identical(GetAssayData(seurat_obj, "counts"), GetAssayData(seurat_obj, "data"))
```
Currently, `write_soma()` would ingest both the `counts` and `data` slots, creating redundant data in the SOMA experiment.
**Changes:** This PR adds a check to `write_soma()` to ensure that the …
> [r] Update Seurat ingestor to skip the data slot when it's identical to counts

- apis/python/src/tiledbsoma/__init__.py
- doc/source/conf.py
- doc/source/python-api.rst
- doc/source/python-tiledbsoma-io.rst
- doc/source/python-tiledbsoma-logging.rst
- doc/source/python-tiledbsoma.rst
Fixes #1326 
**Changes:**
- Adds `autosummary` to the docs. This creates auto-generated pages for each doc entry (functions, classes etc) and groups them using a hierarchical toctree that shows up in the sidebar
- Preview here: https://tiledbsoma.readthedocs.io/en/ebezzi-autosummary/
> [docs][python] Add autosummary

- apis/r/src/Makevars.in
- apis/r/src/nanoarrow.c
- apis/r/src/nanoarrow.h
- apis/r/src/rinterface.cpp
- apis/r/src/riterator.cpp
- apis/r/src/rutilities.cpp
This change mirrors the very-recently merged PR 550 in tiledb-r ensuring that the pointers to columns in a 'struct' aka 'table' aka data.frame are also assigned to external pointers.
**Changes:**
Two new helper functions init and allocate in the, respectively, arrow array and arrow struct objects describing the arrow table that is returned.  Doing so required access to two functions from nanoarrow.c whose signature was changed by removing `static` (and while at it we also updated the vendored copy to the one now used in tiledb-r).
[SC 29294](https://app.shortcut.com/tiledb-inc/story/29294/refine-arrow-export-placing-pointers-to-children-objects-in-external-pointer), [(merged) tiledb-r PR …
> [r] Minor arrow refactor ensuring ext pointers use for struct cols

- apis/r/R/SOMASparseNDArray.R
- apis/r/man/SOMASparseNDArray.Rd
- apis/r/tests/testthat/test-SOMASparseNDArray.R
Restore reading of one-based sparse matrices. Zero-based sparse matrices cause issues with the downstream ecosystems (eg. #1279). This PR brings back support for reading one-based matrices while retaining ability to read zero-based sparse matrices. Code is shared between both readers to reduce duplication.
Also makes uses of `Matrix::sparseMatrix(index1 = FALSE)` to reduce the amount of coercion from zero-based in SOMA &rarr; 1-based in call to `Matrix::sparseMatrix()` &rarr; 0-based internally within Matrix
> Restore `SOMASparseNDArray$read_sparse_matrix()`

- _pkgdown.yml
- apis/r/_pkgdown.yml
Fixes #1376
As discussed in #1376, the order of articles ("vignettes") presented is rule-based (by filename) and not ideal.
**Changes:**
We impose an explicit ordering and segmentation in the navigation bar:
We also update the basic rendering to bootstrap5 which uses crisper CSS all-around.  The logic in the GitHub Action should be unaffected the basic `build_site()` is embedded in the 'update and push to gh-pages' step.
#1376
[SC 29399](https://app.shortcut.com/tiledb-inc/story/29399/fine-tune-pkdown-listing-of-vignettes_
> [r/docs] Fine-tune article display in pkgdown setup

- apis/r/DESCRIPTION
- apis/r/vignettes/soma-objects.Rmd
Fixes #1416 
Vignette builds stumble over one line using `[..,..]` access to a zero-based sparse matrix which now requires a view.
**Changes:**
The code (and text leading in) are adjusted.
#1416 
[SC 29483](https://app.shortcut.com/tiledb-inc/story/29483/r-docs-adjust-one-vignette)
> [r] Adjust vignette to change in zero-based access and views

- apis/r/R/RcppExports.R
- apis/r/R/SOMADataFrame.R
- apis/r/R/SOMADenseNDArray.R
- apis/r/R/SOMASparseNDArray.R
- apis/r/man/SOMACollectionBase.Rd
- apis/r/man/SOMADataFrame.Rd
- apis/r/man/SOMADenseNDArray.Rd
- apis/r/man/SOMASparseNDArray.Rd
- apis/r/man/TileDBGroup.Rd
- apis/r/man/sr_setup.Rd
- apis/r/man/write_soma.Rd
- apis/r/man/write_soma.Seurat.Rd
- apis/r/man/write_soma_objects.Rd
- apis/r/man/write_soma_seurat_sub.Rd
- apis/r/src/riterator.cpp
Individual object-readers were resetting a requested global log level.
Example:
```
tiledbsoma:::set_log_level('debug')
experiment <- SOMAExperimentOpen('/var/s/v/ileum')
query <- SOMAExperimentAxisQuery$new(experiment = experiment, measurement_name = "RNA")
obj <- query$to_seurat(X_layers = c(data = 'data'))
print(obj)
```
At line 1 the log level is set. But desired log lines were not appearing because of:
* https://github.com/single-cell-data/TileDB-SOMA/blob/1.2.4/apis/r/R/SOMADataFrame.R#L187 (and simillar lines)
* https://github.com/single-cell-data/TileDB-SOMA/blob/1.2.4/apis/r/src/rinterface.cpp#L82-L85
when the `read` methods were invoked through the `query` callchain.
**Changes:**
Set the log level to `"auto"` as intended.
> [r] Respect global log level

- apis/r/src/riterator.cpp
- apis/r/tests/testthat/test-SOMAArrayReader-Iterated.R
- libtiledbsoma/src/soma/soma_array.h
Fixes #1420
A non-initial read of an incomplete query object (for a query that has in fact no data) would crash assumed there was data to be had.  
**Changes:**
The internal SOMA Array class already had a predicate to indicate whether the read was initial or not.  Together with the existing accessor for the number of data cells ("rows" so to speak) read, we can identify non-initial but unsatisfiable queries.
Note that we expand one `libtiledbsoma` header file so if using thiss with a system-wide `libtiledbsoma` a quick rebuild is needed.
Percolating this result to higher-level functions will be addressed next in a subsequent PR.
#1420 
[SC 29567](https://app.shortcut.com/tiledb-inc/story/29567/c-r-ensure-subsequent-reads-on-empty-queries-do …
> [c++,r] Use knowing whether read is initial or not when reading 'next' result set

- apis/r/src/riterator.cpp
- apis/r/tests/testthat/test-SOMAArrayReader-Iterated.R
- apis/r/tests/testthat/test-SOMAExperiment-query.R
With the change in #1422 we can return an empty arrow table (as the usual two `void*` of its C API) rather than just two `NULL`.  This allows transparent use through the different query access paths.
**Changes:**
The change also required a small change in how the check for completeness of a query is determined, and affects two test conditions in the unit test file.  It also lets us enable a largers from the experiment query test which required this change.
[SC 29587](https://app.shortcut.com/tiledb-inc/story/29587/minor-refactoring-of-iterated-read-results-when-result-set-is-empty)
> [r] Return empty arrow table on empty results set

- apis/r/R/RcppExports.R
- apis/r/src/RcppExports.cpp
- apis/r/src/rinterface.cpp
- apis/r/src/riterator.cpp
- apis/r/tests/testthat/test-SOMASparseNDArray.R
Fixes #1421 
The `sr_setup` function was not exposing `batch_size` and `result_order`
**Changes:**
The interface has been expanded, and a set of previously commented-out tests are enabled.
#1421 
[SC 29598](https://app.shortcut.com/tiledb-inc/story/29598/expand-sr-setup-interface)
> [r] Expose two more arguments for `sr_setup` and enable tests

- apis/python/src/tiledbsoma/__init__.py
- apis/python/src/tiledbsoma/_collection.py
- apis/python/src/tiledbsoma/_common_nd_array.py
- apis/python/src/tiledbsoma/_dataframe.py
Finishes the Python side of #1394.
> [python] Export `TileDBCreateOptions` at the top level, and add to docs

- apis/python/src/tiledbsoma/io/ingest.py
To avoid unnecessary "during the handling of exception A, exception B was raised" messages (since "collection doesn't exist yet" isn't really an error condition), this pulls the "create" step out of the exception handler for the "open" step, breaking the exception causation chain. (The other does-not-exist blocks should probably be changed similarly, but those would require more work than this minor fix.)
> Improve stack traces on collection create/open in the ingestor.

- .github/workflows/r-ci.yml
fixes #1406
Total time for CI is currently the time for tests _plus_ the time for coverage where it runs making the 'linux' run slower than macOS.  We can safe a bit of total CI time by running coverage while the normal unit tests run, making the net total time the time of slower unit test setup, currently macOS.
**Changes:**
Expand the CI matrix to include field 'covr', run unit tests as before when the field is not but run coverage when it is yes.
#1406, [SC 29906](https://app.shortcut.com/tiledb-inc/story/29906/r-run-coverage-in-parallel)
> [r] Run coverage in parallel instead of sequentially after test

- libtiledbsoma/src/soma/managed_query.cc
- libtiledbsoma/src/soma/managed_query.h
- libtiledbsoma/src/soma/soma_array.cc
- libtiledbsoma/src/soma/soma_array.h
- libtiledbsoma/src/utils/array_buffers.h
- libtiledbsoma/src/utils/column_buffer.cc
- libtiledbsoma/src/utils/column_buffer.h
- libtiledbsoma/test/unit_managed_query.cc
- libtiledbsoma/test/unit_soma_array.cc
#1364
**Changes:**
* Add `SOMAArray::create`
* Add `SOMAArray::write`
* Add `SOMAArray::set_column_data`
In a future PR, the write function should take an Arrow data structure as specified in the abstract spec instead of a vector. The create function should also take in an Arrow struct instead of a TileDB ArraySchema.
> [c++] Addition of `SOMAArray::create` and `SOMAArray::write`

- apis/python/devtools/outgestor
- apis/python/src/tiledbsoma/io/ingest.py
Items in `apis/python/devtools/` exist with the contract that they're dev-only. This is one of them.
Some ad-hoc feedback received during an info session: if the to-be-outgested SOMA experiment's `var` has, say, `gene_ids` rather than `var_id` -- which is already supported in `to_anndata` -- let these be specified two levels up, namely, `to_h5ad` and the `devtools/outgestor` convenience script.
Testing:
```
ingestor ileum.h5ad ileum
outgestor --var-id-name=gene_ids ileum re-ileum.h5ad
```
with `ileum.h5ad` from
https://cellxgene.cziscience.com/collections/5c868b6f-62c5-4532-9d7f-a346ad4b50a7
> [python] Wire obs/var ID options to `devtools/outgestor`

- apis/python/src/tiledbsoma/io/ingest.py
- apis/python/tests/test_basic_anndata_io.py
**Issue and/or context:** This arose in response to a user-support request in the TileDB Community Slack's `#genomics` channel.
**Changes:** Add `anndata.layers` by default, without need for a manual step afterward.
> [python] Ingest `anndata.layers` by default in `tiledbsoma.io`

- apis/r/R/SOMASparseNDArray.R
**Issue and/or context:** Just a typo found while reading log output.
> [r] Trivial typofix

- README.md
- apis/python/README.md
- apis/r/README.md
**Issue and/or context:** The quick-start pages at https://github.com/single-cell-data/TileDB-SOMA/wiki instruct the user to click into `apis/python/README.md` and `apis/r/README.md` for "full installation instructions". So, it's important that the latter have as much conda-install information as the former do.
Tracking issue: #1387
> [docs] Some doc-link updates

- apis/python/setup.py
**Issue and/or context:** Resolves #1470, since we've had full support for Python 3.11 since [1.2.2](https://github.com/single-cell-data/TileDB-SOMA/releases/tag/1.2.2).
> [python] Add 3.11 to `classifiers=` in `setup.py`

- apis/python/setup.py
Fixes #1463 
**Changes:**
Pins for numba and numpy updated on Python 3.11
Will manually run the GHA for python-ci-full as this tests the full matrix ([run link](https://github.com/single-cell-data/TileDB-SOMA/actions/runs/5246123389))
> [python] Update numba/numpy versions for Python 3.11

- libtiledbsoma/src/soma/managed_query.h
- libtiledbsoma/src/soma/soma_array.cc
- libtiledbsoma/src/soma/soma_array.h
- libtiledbsoma/src/utils/column_buffer.h
- libtiledbsoma/test/unit_soma_array.cc
Separated out from PR https://github.com/single-cell-data/TileDB-SOMA/pull/1449.
**Changes:**
Previously, `SOMAArray` write buffers were set with `set_column_buffer`. The `write` function now takes in an `ArrayBuffers` data structure directly.
N/A
> [c++] `SOMAArray::write` Modified To Take in `ArrayBuffers`

- apis/r/DESCRIPTION
- apis/r/NEWS.md
- apis/r/R/SOMAAxisIndexer.R
- apis/r/R/SOMAExperimentAxisQuery.R
- apis/r/R/utils-arrow.R
- apis/r/man/SOMAExperimentAxisQuery.Rd
- apis/r/tests/testthat/test-SOMAExperiment-query-matrix-outgest.R
- apis/r/vignettes/soma-experiment-queries.Rmd
**Changes:** This PR adds a new method to `SOMAExperimentAxisQuery` that allows users to load any layer from the queried experiment as a sparse matrix with _named_ dimensions (i.e., row and column names are populated).
As noted in the docs, dimension names default to joinids but may come from any obs or var column (depending on the collection type) containing values that uniquely identify each record.
Quick example:
```r
library(tiledbsoma)
experiment <- load_dataset("soma-exp-pbmc-small")
query <- SOMAExperimentAxisQuery$new(
experiment = experiment,
measurement_name = "RNA",
obs_query = SOMAAxisQuery$new(coords = 0:9),
var_query = SOMAAxisQuery$new(coords = 0:9)
)
query$to_sparse_matrix(
collection = "X",
layer = "counts",
obs_index = "obs_id",
var_index = "var_id"
)
##
```
More usage …
> [r] Add `to_sparse_matrix()` method to `SOMAExperimentAxisQuery`

- apis/python/setup.py
Backport #1471 from `main` to `release-1.2` in prep for 1.2.6
> [python] Backport #1471 from `main` to `release-1.2` branch

- apis/python/setup.py
Backport #1472 from `main` to `release-1.2` in prep for 1.2.6
> [python] Backport #1472 from `main` to `release-1.2` branch

- apis/python/src/tiledbsoma/io/ingest.py
Backport #1468 from `main` to `release-1.2` in prep for 1.2.6
> [python] Backport #1468 from `main` to `release-1.2` branch

- libtiledbsoma/src/utils/column_buffer.cc
- libtiledbsoma/src/utils/column_buffer.h
- libtiledbsoma/test/unit_column_buffer.cc
- libtiledbsoma/test/unit_soma_array.cc
#1488
**Changes:**
Previously the `ColumnBuffer` called `alloc` which correctly allocated buffer sizes by checking config. This was inadvertently removed in #1439 and now reverted.
> [c++] `ColumnBuffer` Constructor Should Call `alloc` Method

- apis/r/DESCRIPTION
- apis/r/R/SOMAExperimentAxisQuery.R
- apis/r/R/SOMASparseNDArray.R
- apis/r/R/SOMASparseNDArrayRead.R
- apis/r/R/SparseReadIter.R
- apis/r/R/utils-readerTransformers.R
- apis/r/tests/testthat/helper-test-soma-objects.R
- apis/r/tests/testthat/test-SOMASparseNDArray.R
**Issue and/or context:** #1487
**Changes:** This makes a few adjustment to improve our handling of arrays with domains greater than 2^31-1.
- `SOMASparseNDArray$read()` no longer warns if `nnz() > .Machine$integer.max`, since these arrays can be read without issue using `SOMASparseNDArray$read()$tables()`
- `SOMASparseNDArrayRead$sparse_matrix()` truncates `shape` to `2^31 - 1` if `shape > 2^31-1` and lets the user know via a warning. I decided to add this logic here rather than deeper in the stack so that it executes only once when reading sparse matrices, rather than once per iteration.
- Fixed `SparseReaditer`'s `shape` assertion
- `arrow_table_to_sparse` adds a final check to ensure that `shape` is `<= 2^31 - 1` and all coordinates are within `[0, 2^31 - 1)` (since `shape` is 1-based …
> [r] Improve handling of arrays with with domains greater than 2^31 - 1

- apis/r/DESCRIPTION
- apis/r/R/SOMAExperimentAxisQuery.R
- apis/r/man/SOMAExperimentAxisQuery.Rd
- apis/r/tests/testthat/test-SOMAExperiment-query-matrix-outgest.R
Change `SOMAExperimentAxisQuery$to_sparse_matrix()` to utilize soma join IDs for dims instead of labels. This better handles gaps (all implicitly stored) in the arrays, which can happen by storage or by query
For obsm/varm, utilize span of `soma_dim_1` for columns (`dim()[2L]`) as there is no join ID for this axis
> [r] Adjust `SOMAExperimentAxisQuery$to_sparse_matrix()` to handle gapped matrices

- .github/workflows/backport.yml
**Issue and/or context:** #1335
**Changes:** See PR diff
Following on @eddelbuettel 's comments on #1506 -- in my tiptoe into backport-bot for `TileDB-SOMA`, I thought to imitate core as closely as possible (since known-good), then tweak versions after. However we found that `ubuntu-18.04` actually resulted in launch failures so let's try `ubuntu-20.04`.
> [ci] Backport Ubuntu-image update

- apis/r/README.md
* ~~Change above-the-fold installation instructions to use chanzuckerberg R-universe (which serves the latest GitHub Release of tiledbsoma) instead of TileDB-Inc (which serves the head of `main`). As agreed in #1427~~
* Add `install_github()` instruction for users who do desire the head of `main`
* Rebrand existing source installation instructions as developer setup
Note: the chanzuckerberg R-universe serves tiledbsoma but not TileDB-R. Users following the instructions in a fresh environment will get the GitHub-Released version of tiledbsoma, and the CRAN version of tiledb. Consequently, to release tiledbsoma we must ensure any necessary changes to TileDB-R have made it out to CRAN. (We do plan to publish tiledbsoma on CRAN once ready, so this just pulls that constraint forward a bit.)
> [r] Update README.md installation instructions in preparation for 1.0[rc]

- apis/python/src/tiledbsoma/io/ingest.py
- apis/python/tests/test_basic_anndata_io.py
**Issue and/or context:** Resolves #1400
**Changes:** As discussed on #1400
```
>>> import tiledbsoma
>>> exp = tiledbsoma.Experiment.open("./pbmc3k")
>>> exp.ms["RNA"]["uns"]["louvain_colors"].read().concat()
pyarrow.Table
soma_joinid: int64
values: large_string
----
soma_joinid: [[0,1,2,3,4,5,6,7]]
values: [["#1f77b4","#ff7f0e","#2ca02c","#d62728","#9467bd","#8c564b","#e377c2","#bcbd22"]]
>>> exp.ms["RNA"]["uns"]["louvain_colors"].read().concat().to_pandas()
soma_joinid   values
0            0  #1f77b4
1            1  #ff7f0e
2            2  #2ca02c
3            3  #d62728
4            4  #9467bd
5            5  #8c564b
6            6  #e377c2
7            7  #bcbd22
```
> [python] Ingest uns string arrays as single-attr SOMADataFrame

- .github/workflows/python-ci-full.yml
- .github/workflows/python-ci-minimal.yml
Since GitHub appears to have pushed a working version of Python 3.7.17, this workaround is no longer needed.
Rev e66553c6fa76265941546f8474fadeb85ccc784c is a change where I had the build run.
> Remove GitHub Python 3.7 build workaround.

- apis/python/src/tiledbsoma/__init__.py
- apis/r/DESCRIPTION
- apis/r/R/SOMAExperimentAxisQuery.R
- apis/r/R/utils-assertions.R
**Issue and/or context:** #1518
**Changes:** In #1504 `SOMAExperimentAxisQuery$to_seurat_graph()` was updated to leverage the newer `to_sparse_matrix()`, which  avoided the expensive creation of CsparseMatrix objects with dimensions equal to the underlying array's domain. This carries over the same change to `SOMAExperimentAxisQuery$to_seurat_graph()`.
This also addresses the CI issues described [here](https://github.com/single-cell-data/TileDB-SOMA/pull/1440#issuecomment-1614953938) and blocking #1440.
**Notes for Reviewer:** I'm on the fence about whether or not we need to throw a warning every time a user attempts to call `to_seurat_reduction()` on a dense ND array. It should be an incredibly rare occurrence and I'm not sure what value the warning provides. Let me know if you have …
> [r] Optimize export of obsm/varm arrays to Seurat

- apis/python/setup.py
- apis/r/DESCRIPTION
- apis/r/tools/get_tarball.R
- libtiledbsoma/cmake/Modules/FindTileDB_EP.cmake
**Issue and/or context:** Core 2.16 is out
**Changes:** Depend on updated versions of affected dependent packages
This _will_ fail CI until https://github.com/TileDB-Inc/TileDB-Py/pull/1805 is merged, and PyPI artifacts have propagated to https://pypi.org/project/tiledb/
> Use core 2.16, tiledb-py 0.22, tiledb-r 0.20

- .gitignore
- apis/r/R/utils-assertions.R
- apis/r/tests/testthat/test-SOMAAxisQuery.R
closes #1537
As seen in #1537, passing numeric coordinates for an axis query leads to these being silently dropped.
**Changes:**
Numeric coordinates now get converted explicitly to `integer64`.  As small test has been added.
[SC-31919](https://app.shortcut.com/tiledb-inc/story/31919/somaexperimentaxisquery-drops-numeric-query-coordinates)
[SC-29979](https://app.shortcut.com/tiledb-inc/story/29979/r-add-support-for-querying-non-numeric-coordinates)
I also snuck a one-liner addition to `.gitignore` which helps with some local scripts I keep. This can of course be reverted if need be.
> [r] Ensure numeric axis query coordinates are converted

- apis/python/src/tiledbsoma/io/ingest.py
For local disk and S3, creation and readback URIs are the same. For Cloud, there is a syntactical difference:
* Creation: `tiledb://namespace/s3://bucket/path/to/exp/ms/RNA/X`
* Readback (for the same object): `tiledb://namespace/uuid`
For the former, we can append to make `tiledb://namespace/s3://bucket/path/to/exp/ms/RNA/X/newlayer`; for the latter we cannot.
**Changes:**
Respect the syntax and semantics for different storage URIs.
This repository is an open-source repository which does not have unit tests that rely on cloud infrastructure. For this reason, it's correct and appropriate that this PR does not introduce new unit-test cases. Test cases are appropriately placed in cloud-specific repositores.
For the record, here is a test …
> [python] Generalize `add_X_layer` URI handling

- apis/python/src/tiledbsoma/io/ingest.py
**Issue and/or context:** This made debugging https://forum.tiledb.com/t/tiledberror-tiledb-s3-error-storing-h5ad-with-soma-format/602 a bit confusing.
**Changes:** Add the missing log-line.
> [python] Add a missing log-line for uns ndarray ingest

- apis/python/src/tiledbsoma/io/ingest.py
**Issue and/or context:** Hypothesized cause of https://forum.tiledb.com/t/tiledberror-tiledb-s3-error-storing-h5ad-with-soma-format/602/1 -- although I cannot yet repro this myself on a cross-region write.
**Changes:** Add the visibly missing `context` argument in the particular `.open`
> [python] Adding missing context in ingest uns ndarray

- apis/python/src/tiledbsoma/_query_condition.py
This replaces the one (two) remaining use(s) of dataclasses with attrs. Elsewhere we use attrs since it has some minor benefits over dataclasses so this brings consistency. The API for users is completely compatible.
> Replace dataclasses with attrs.

- libtiledbsoma/src/soma/soma_array.cc
- libtiledbsoma/src/soma/soma_array.h
The (non-static) constructor for SOMAArray contains a shared_ptr<Context> making the lifetime management from R a little trickier.  An easier alternative is to also offer a map<string,string> platform_config from which a Config and Context can be derived -- as in the two static ctors.
**Changes:**
This PR adds a second constructor with platform_config interface and places the validation code into a new helper function both non-static constructors call.
[SC-32281](https://app.shortcut.com/tiledb-inc/story/32281/c-additional-constructor-for-somaarray)
> [c++] Add new constructor, factor validation helper

- apis/python/src/tiledbsoma/_arrow_types.py
- apis/python/src/tiledbsoma/io/ingest.py
- apis/python/src/tiledbsoma/io/registration/signatures.py
- apis/python/tests/test_registration_signatures.py
Tracking issue: #1278 
**Changes:**
* Create the `Signature` class which will be used for append-mode pre-check on an upcoming PR
* Unit-test that
* This is a split-out PR -- created for mercifulness to reviewers -- as a line-count reduction from raw material on #1498.
* Question for @aaronwolen @mojaveazure : If an input file has raw and non-raw data do we want them both to be ingested? Or just one or the other? This is actually a design question -- which I'll also put in our tracking doc.
> [python] Append-mode pre-check logic

- .github/workflows/r-ci.yml
- apis/r/DESCRIPTION
**Issue and/or context:** #1567
**Changes:** This bumps the minimum required version of tiledb-r to 0.20.2. Also modifies the R API's CI to install tiledb-r from r-universe. tiledbsoma 1.4.0 now requires tiledb-r >= 0.20.2 (built against TileDB 2.16.1). We won't be able to upload tiledb-r 0.20.2 to CRAN until they return from break on Aug 7. In the meantime, we can install tiledb-r builds from R-universe, which already has 0.20.2 available.
Thanks to @eddelbuettel for the assist.
> [r] Temporarily install tiledb-r from r-universe

- apis/python/src/tiledbsoma/io/conversions.py
- apis/python/src/tiledbsoma/io/ingest.py
We cannot ingest these, as a stack trace makes quite clear.
However, we can offer improved guidance on which columns are problematic.
> [python] Improve guidance on non-ingestible NaN data in categorical-int obs/var columns

- apis/python/setup.py
- apis/r/DESCRIPTION
- apis/r/configure
- apis/r/tools/get_tarball.R
- libtiledbsoma/cmake/Modules/FindTileDB_EP.cmake
**Issue and/or context:** #1567
**Changes:** Micro-bump core and R/Python layers
> Depend on core 2.16.2, TileDB-Py 0.22.2, and TileDB-R 0.20.3

- libtiledbsoma/src/soma/soma_array.h
- libtiledbsoma/src/soma/soma_collection.cc
- libtiledbsoma/src/soma/soma_collection.h
- libtiledbsoma/src/soma/soma_dataframe.cc
- libtiledbsoma/src/soma/soma_dense_ndarray.cc
- libtiledbsoma/src/soma/soma_experiment.h
- libtiledbsoma/src/soma/soma_group.cc
- libtiledbsoma/src/soma/soma_group.h
- libtiledbsoma/src/soma/soma_measurement.h
- libtiledbsoma/src/soma/soma_sparse_ndarray.cc
- libtiledbsoma/test/unit_soma_group.cc
#1575
**Changes:**
* `SOMAGroup` derived objects (ie. `SOMA{Collection,Measurement,Experiment}`) now take in both the start and end timestamps which is consistent with `SOMAArray` derived objects
* Set the `name` (label used by `ManagedQuery` when debugging) of the `SOMAArray` to the URI
> [c++] `SOMACollection` Takes Start and End Timestamp

- apis/r/README.md
Testing installs of 1.4.0 on fresh EC2 instances, and Docker images.
With `cmake` and `git`, I can successfully install with R 4.1 or 4.3.
> [r] Include system prerequisites in install notes

- apis/python/src/tiledbsoma/io/registration/__init__.py
- apis/python/src/tiledbsoma/io/registration/ambient_label_mappings.py
- apis/python/src/tiledbsoma/io/registration/id_mappings.py
- apis/python/src/tiledbsoma/io/registration/signatures.py
- apis/python/tests/test_registration_mappings.py
Tracking issue: #1278 
**Changes:**
* Create the classes `ExperimentAmbientLabelMapping`, `AxisAmbientLabelMapping`, `ExperimentIDMapping`, and `AxisIDMapping`
* None of these will be exposed to the user; they are internal-only.
* This is a split-out PR -- created for mercifulness to reviewers -- as a line-count reduction from raw material on #1498. See also #1554.
* See also #1554 which is another, orthogonal component.
* Actual use by the ingestor logic will be on a subsequent PR.
> [python] Append-mode label/ID-mapping logic

- apis/python/src/tiledbsoma/pytiledbsoma.cc
- apis/python/tests/test_experiment_query.py
#1456
The PyArrow `_export_to_c` function sets a pointer to the beginning of the given Arrow array. However, input data may not always point to the start. The coordinates listed in the bug report uses disjointed slices that are offset.
**Changes:**
Directly convert the input Arrow array into a Python list using PyArrow's `Array.tolist`. Then convert the Python list into a C++ vector using Pybind11's `cast`. Pass this into `SOMAArray::set_dim_points`.
The option for passing partitioning indexes to `set_dim_points_arrow` has been removed for simplicity as this is not used anywhere in TileDB-SOMA-Py.
> [python] Fix For #1456: Invalid Result With PyArrow Array Coords

- apis/r/configure
Versions 0.20.2 and 0.20.3 (current) could not be uploaded to CRAN while CRAN was on break, but provided an update to TileDB Embedded that was needed.  To obtain it, installation relied on a temporary installation via r-universe.  With version 0.20.3 now on CRAN this is no longer needed.
**Changes:**
Removal of a temporary accomation.
[SC-32602](https://app.shortcut.com/tiledb-inc/story/32602/remove-temporary-cran-accomodation)
> [r] Remove workaround for tiledb-r 0.20.3 while CRAN was on break

- .github/workflows/r-ci.yml
- apis/r/tools/r-ci.sh
We use a copy of script `r-ci.sh` which (for ease of use with tiledb-r) had the ability to install BioConductor repos removed.  This does of course limit SOMA's ability to test with BioConductor packages so this PR restores this ability,
It has been tested on macOS and Linux with shortened one-off CI setup, see below the fold.
<details>
</details>
**Changes:**
The 'command' `install_bioc` is added which installs package `BiocManager` and uses it to install the named packages.
[SC 32783](https://app.shortcut.com/tiledb-inc/story/32783/add-ability-to-install-bioconductor-packages-to-r-ci-sh)
> [r] Add ability to install BioC packages to r-ci.sh [ci skip]

- apis/python/src/tiledbsoma/io/ingest.py
- apis/python/tests/test_basic_anndata_io.py
Testing on #1592 did not cover enough cases.
> [python] Update to `_create_or_open_coll` for 1.2.7 compatibility

- libtiledbsoma/src/soma/soma_array.cc
- libtiledbsoma/src/soma/soma_array.h
- libtiledbsoma/src/soma/soma_collection.cc
- libtiledbsoma/src/soma/soma_collection.h
- libtiledbsoma/src/soma/soma_dataframe.cc
- libtiledbsoma/src/soma/soma_dataframe.h
- libtiledbsoma/src/soma/soma_dense_ndarray.cc
- libtiledbsoma/src/soma/soma_dense_ndarray.h
- libtiledbsoma/src/soma/soma_group.cc
- libtiledbsoma/src/soma/soma_group.h
- libtiledbsoma/src/soma/soma_object.h
- libtiledbsoma/src/soma/soma_sparse_ndarray.cc
- libtiledbsoma/src/soma/soma_sparse_ndarray.h
- libtiledbsoma/src/utils/common.h
- libtiledbsoma/src/utils/util.cc
- libtiledbsoma/src/utils/util.h
- libtiledbsoma/test/unit_soma_array.cc
- libtiledbsoma/test/unit_soma_collection.cc
- libtiledbsoma/test/unit_soma_dataframe.cc
- libtiledbsoma/test/unit_soma_dense_ndarray.cc
- libtiledbsoma/test/unit_soma_group.cc
- libtiledbsoma/test/unit_soma_sparse_ndarray.cc
- #1577
- https://github.com/single-cell-data/SOMA/blob/main/abstract_specification.md#somametadatamapping
**Changes:**
* Cache metadata values  when opening the array or group so that it can be accessed in either read or write mode If the `SOMAArray` or `SOMAGroup` is already open in read mode, fill the cache by using `metadata_num` and `get_metadata_from_index`. If it is open in write, open a temp handle in read mode to fill the metadata mapping and then close the temp handle.
* Add metadata functions and accompanying unit tests for `SOMAObject`s
* `get_metadata` checks if key exists and returns `std::nullopt` if DNE
N/A
> [c++] Support reading `SOMAObject` metadata in read and write mode

- libtiledbsoma/src/soma/soma_group.cc
- libtiledbsoma/src/soma/soma_group.h
- libtiledbsoma/test/unit_soma_collection.cc
- libtiledbsoma/test/unit_soma_group.cc
https://github.com/single-cell-data/TileDB-SOMA/issues/1623
**Changes:**
Extend caching introduced in #1584 to also store `SOMAGroup` member-to-uri mapping so that this information can also be accessed in both read and write mode.
N/A
> [c++] Support reading member-to-uri mapping in read and write mode

- libtiledbsoma/src/soma/soma_collection.h
- libtiledbsoma/src/soma/soma_dataframe.h
- libtiledbsoma/src/soma/soma_dense_ndarray.h
- libtiledbsoma/src/soma/soma_object.h
- libtiledbsoma/src/soma/soma_sparse_ndarray.h
Follow up PR for https://github.com/single-cell-data/TileDB-SOMA/pull/1584#discussion_r1298880070
**Changes:**
* Correct `SOMAObject` metadata methods to be virtual
* Update documentation for `get_metadata`
> [c++] `SOMAObject` Metadata Methods Should Be Virtual

- apis/r/tools/build_libtiledbsoma.sh.in
Installation in RedHat-family distributions, when using the local build of `libtiledbsoma` as triggered by `R CMD INSTALL` when no system library is found, was not accomodating the `lib64` directory and failed to link.
**Changes:**
When local installation is used and the results are placed in `lib64` these files are now moved to `lib`.  This only affects the internal use of `libtiledbsoma` by the R package.  The location is not exported making this change minimal.
The change has been tested under Fedora 38.
[SC-33364](https://app.shortcut.com/tiledb-inc/story/33364/support-from-source-installation-on-redhat-alike-distros)
> [r] Accomodate RedHat install path in package-internal path

- apis/python/src/tiledbsoma/io/ingest.py
- apis/python/tests/test_update_dataframes.py
These should be used to mutate columns only.
> [python] Check that `update_obs`/`update_var` do not update row counts

- apis/r/R/SOMASparseNDArray.R
- apis/r/R/TileDBArray.R
- apis/r/man/SOMAArrayBase.Rd
- apis/r/man/SOMADataFrame.Rd
- apis/r/man/SOMADenseNDArray.Rd
- apis/r/man/SOMANDArrayBase.Rd
- apis/r/man/SOMASparseNDArray.Rd
- apis/r/man/TileDBArray.Rd
- apis/r/tests/testthat/test-SOMASparseNDArray.R
Add support for encoding and retrieving bounding box information from arrays. The bounding box stored in array-level metadata and created during write
Bounding box metadata is structured as `{<DIMENSION_NAME>_DOMAIN: [<lower_bound>, <upper_bound>]}` (for example, `{soma_dim_0_DOMAIN: [0, 79]}`). The bounds are 0-based, inclusive, and stored as 64-bit integers
New SOMA Methods
- `TileDBArray$non_empty_domain()`: retrieves the maximal value of the non-empty domain via `tiledb::tiledb_array_get_non_empty_domain_from_name()`
- parameter `index1`: return the one-based index for the non-empty domain; defaults to `FALSE`
- `TileDBArray$used_shape()`: retrieves the bounding box for array-level meta data
- parameter `simplify`: return only the maximal bounds of the used shape (essentially assumes …
> [r] Add bounding box to arrays

- apis/r/DESCRIPTION
- apis/r/NEWS.md
- apis/r/R/SOMASparseNDArray.R
- apis/r/R/TileDBArray.R
- apis/r/tests/testthat/test-SOMASparseNDArray.R
Flatten out the bounding box metadata to be single integer64 values instead of arrays of two integer64 values. Instead of just `<dimname>_domain`, bounding boxes are now stored as `<dimname>_domain_lo` and `<dimname>_domain_hi`
`SOMASparseArray$write()` is now modified to flatten the bounding box before writing and `TileDBArray$used_shape()` is modified to read four metadata values instead of two
The inputs and to `SOMASparseNDArray$write(bbox =)` and `TileDBArray$used_shape()` are unchanged
Context: issue #1445; follow-on to PR #1513.
> [r] Adjust bounding box to be spec compliant

- apis/r/DESCRIPTION
- apis/r/README.md
- apis/r/inst/AUTHORS
- apis/r/src/Makevars.in
- apis/r/tools/build_libtiledbsoma.sh.in
- apis/r/vignettes/soma-objects.Rmd
- apis/r/vignettes/soma-reading.Rmd
An r-devel check is mandatory and sometimes reveals more issues than the release version.  There are also other non-coded tests the 'incoming packages desk' at CRAN would check and look for (as eg 'references for methods' and 'document authors and copyright holders of all code included').
**Changes:**
See commit by commit.  No new code.  Changes only to metadata.
[SC-33482](https://app.shortcut.com/tiledb-inc/story/33482/additional-cran-polish)
This PR does not claim to be exhaustive but addresses a few 'known knowns'.  On my machine with a current r-devel build (from today) the log is favorable, see below the fold.
<details>
```sh
edd@rob:~/git/tiledb-soma/apis/r(de/sc-33482/cran_polish)$ rdcc.sh tiledbsoma_1.4.3.tar.gz 
* using log …
```
> [r] Additional polish for R CMD check --as-cran by r-devel

- .github/workflows/python-ci-minimal.yml
- .github/workflows/r-valgrind.yaml
- apis/r/DESCRIPTION
- apis/r/R/RcppExports.R
- apis/r/R/ReadIter.R
- apis/r/src/RcppExports.cpp
- apis/r/src/riterator.cpp
- apis/r/tests/testthat.R
- apis/r/tests/testthat/helper-test-tiledb-objects.R
- apis/r/tests/testthat/test-EphemeralCollection.R
- apis/r/tests/testthat/test-Factory.R
- apis/r/tests/testthat/test-SCEOutgest.R
- apis/r/tests/testthat/test-SOMAArrayReader-Arrow.R
- apis/r/tests/testthat/test-SOMAArrayReader-Iterated.R
- apis/r/tests/testthat/test-SOMAAxisQuery.R
- apis/r/tests/testthat/test-SOMACollection.R
- apis/r/tests/testthat/test-SOMADataFrame.R
- apis/r/tests/testthat/test-SOMADenseNDArray.R
- apis/r/tests/testthat/test-SOMAExperiment-query-matrix-outgest.R
- apis/r/tests/testthat/test-SOMAExperiment-query.R
- apis/r/tests/testthat/test-SOMASparseNDArray.R
- apis/r/tests/testthat/test-SOMATileDBContext.R
- apis/r/tests/testthat/test-SeuratIngest.R
- apis/r/tests/testthat/test-SeuratOutgest-assay.R
- apis/r/tests/testthat/test-SeuratOutgest-graph.R
- apis/r/tests/testthat/test-SeuratOutgest-object.R
- apis/r/tests/testthat/test-SeuratOutgest-reduction.R
- apis/r/tests/testthat/test-Stats.R
The SOMAArray instance used by the iterated reader contains a shared pointer to a Context instance.  This PR adds a finalizer to ensure this is properly unwould.  Unit tests are refactored to test under `valgrind` and an actions has been added.
**Changes:**
Addiition of a finalizer function, refactored tests and added valgrind action
[SC 33353](https://app.shortcut.com/tiledb-inc/story/33353/added-finalizers-as-well-test-restructuring-for-valgrind-compliance) and the notion doc referenced therein
> [r] Add a finalizer for the SOMAArray instance and assure valgrind tests pass

- apis/r/DESCRIPTION
- apis/r/R/SOMADataFrame.R
- apis/r/R/SOMAExperiment.R
- apis/r/R/TileDBArray.R
- apis/r/R/utils-arrow.R
- apis/r/R/utils.R
- apis/r/man/SOMADataFrame.Rd
- apis/r/man/SOMAExperiment.Rd
- apis/r/man/TileDBArray.Rd
- apis/r/tests/testthat/test-Arrow-utils.R
- apis/r/tests/testthat/test-SOMADataFrame.R
- apis/r/tests/testthat/test-SOMAExperiment.R
**Issue and/or context:** #1591 
**Changes:**  Adds `update_obs` and `update_var` methods to the `SOMAExperiment` class. These methods accept either an arrow table, arrow record batch, or a `data.frame` as input and update the existing `SOMADataFrame` on disk. The core logic for these methods is implemented in `SOMADataFrame$update`.
Other changes:
- `SOMADataFrame` attribute filters now default to ZSTD compression if no filter is specified in the `platform_config`, previously we were defaulting to no compression.
- Added new internal utility to create tiledb attributes from arrow fields (`tiledb_attr_from_arrow_field()`), which is now used by `SOMADataFrame$create` and `SOMADataFrame$update`
- `TileDBArray` class now has a private method for reopening an array in a different mode
**Notes …
> [r] Support updating obs and var

- .github/workflows/python-ci-single.yml
- apis/python/src/tiledbsoma/eta.py
- apis/python/src/tiledbsoma/io/ingest.py
**Issue and/or context:** Found while doing development and corner-case testing for #1648.
**Changes:** For completely empty sparse arrays, we were getting `chunk_size=1` and doing lots of loops over zero-element chunks. Now, we detect that; do a single write (for metadata consistency), then stop.
After (`z.h5ad` which you can find in our sandbox at `s3://tiledb-johnkerl/s/a/z.h5ad` has empty `X`):
```
$ ingestor.py --debug ~/s/a/z.h5ad z
START  Experiment.from_h5ad /Users/johnkerl/s/a/z.h5ad
START  READING /Users/johnkerl/s/a/z.h5ad
FINISH READING /Users/johnkerl/s/a/z.h5ad TIME 0.019 seconds
Registration: registering isolated AnnData object.
START  DECATEGORICALIZING
FINISH DECATEGORICALIZING TIME 0.001 seconds
START  WRITING z
START  WRITING z/obs
START  WRITING z/obs
FINISH WRITING …
```
> [python] Avoid unnecessary slowdown on empty sparse arrays

- .github/workflows/r-valgrind.yaml
Valgrind summaries are a little sparse by default. 
**Changes:**
Three options are added at the `valgrind` invocation in the GitHub Action
[SC-33661](https://app.shortcut.com/tiledb-inc/story/33661/r-add-valgrind-options)
> [r] Add three valgrind options

- apis/r/R/RcppExports.R
- apis/r/R/ReadIter.R
- apis/r/R/SOMADataFrame.R
- apis/r/R/SOMASparseNDArray.R
- apis/r/inst/include/tiledbsoma_types.h
- apis/r/src/RcppExports.cpp
- apis/r/src/riterator.cpp
- apis/r/src/rutilities.h
- apis/r/tests/testthat/test-SOMAArrayReader-Iterated.R
PR #1636 has been seen "to work in theory yet not in practice" so the lifetime management of the iterated reader and its SOMArray object has been refactored.
**Changes:**
A struct is wrapped around the shared pointer which allows for R lifetime management (of an external pointer to the struct) to coexist with the C++ shared_pointer (inside the struct).  No more explicit finalizer.
[SC 33659](https://app.shortcut.com/tiledb-inc/story/33659/r-refactor-iterated-reader-lifetime)
> [r] Refactor iterated reader lifetime

- apis/r/tests/testthat/test-SOMADataFrame.R
- apis/r/tests/testthat/test-SOMAExperiment.R
- apis/r/tests/testthat/test-SingleCellExperimentIngest.R
- apis/r/tests/testthat/test-SummarizedExperimentIngest.R
The nightly valgrind run revealed a more nagging notes.
**Changes:**
A few more tests have been conditioned on the existing variable.
Two checks are wrapped in `suppressMessages()` as a change at BioConductor currently leads to a fresh warning.
[SC 33688](https://app.shortcut.com/tiledb-inc/story/33688/r-more-test-tweaking)
> [r] More tweaks for tests

- apis/python/src/tiledbsoma/options/_soma_tiledb_context.py
We use the basic `functools.cache` decorator to ensure one default Ctx is created.
This avoids immediately constructing a Ctx upon importing tiledbsoma, and means that if a user only ever passes in their own context into SOMATileDBContext constructors, the default is never initialized.
Helps address #1550. This change is convenient because it imposes no user API changes; everything Just Works.
> Lazily initialize a default global TileDB context.

- .github/workflows/python-ci-single.yml
- .gitignore
- test/README.md
**Issue and/or context:** Found in #1511 / #866 et al. while attempting pre-tag/pre-merge tests with core 2.17.0-rc0. Here we use `tiledbsoma-py` to generate test data for `libtiledbsoma` code. That's currently failing due to `tiledbsoma-py` in the generator step being built with core 2.16 rather than 2.17. But this highlights a bigger issue: let's not be circular in our test paths. Rather, let's validate C++ code using C++ and shell tools; then move up the testing stack to Python and R.
**Changes:** Simply can the generated inputs into `test/soco.tgz`. As an added bonus we get some backward-compatilbility test here.
> [c++] Don't use Python to generate C++ test inputs

- apis/python/src/tiledbsoma/io/ingest.py
This was fixed on #1649. But a bad merge on #1648 here undid it:
https://github.com/single-cell-data/TileDB-SOMA/commit/a21e43fa8456b539d6ae1908fef728866ba56b01#r127159208
**Changes:**
> [python] Restore efficiency on zero-cell `X`

- apis/python/tests/test_platform_config.py
> [python] Update default-filter-list handling in unit tests

- apis/python/src/tiledbsoma/options/_soma_tiledb_context.py
- apis/python/tests/test_context.py
- apis/python/tests/test_platform_config.py
To allow users to mess with their TileDB configs and modify them without actually instantiating an actual TileDB Context (which entails allocation of significant resources), we lazily wait until the caller actually requests the Context to create it just in time. This ensures that we don't waste resources that are not easy to reclaim (particularly the shared global context, which is never GCable).
Further addresses #1550. It may fix it; I leave it to @bkmartinjr et al to see if it completely addresses their issues once this change is deployed.
> Initialize TileDB Contexts extremely lazily.

- apis/python/setup.py
- apis/python/tests/test_platform_config.py
- apis/r/DESCRIPTION
- apis/r/tools/get_tarball.R
- libtiledbsoma/cmake/Modules/FindTileDB_EP.cmake
**Issue and/or context:** For #866. The "real" PRs are #1519, #1511, and #1559 which are at the moment depending on core 2.17.0-rc0. On this PR, if CI passes, I'll attempt to first merge solely the core-dependency change -- and then the big three PRs will be able to be rebased on top of this once it's merged.
**Changes:**
* Core 2.17.0
* #1676 redux 
* TileDB-Py 0.23.0
* TileDB-R 0.21.0
> [c++] Depend on core 2.17.0

- apis/python/src/tiledbsoma/pytiledbsoma.cc
> [c++] Removed unused-variable warning

- apis/r/R/write_soma.R
- apis/r/man/write_soma_objects.Rd
Allow `write_soma.data.frame()` to write factors as categoricals. `write_soma()` will no longer cast factors to characters prior to writing
> Update `write_soma.data.frame()` to support categoricals

- apis/python/src/tiledbsoma/_query_condition.py
- apis/python/src/tiledbsoma/pytiledbsoma.cc
- libtiledbsoma/src/soma/soma_array.cc
- libtiledbsoma/src/soma/soma_array.h
The query condition init needs the array schema and the enumeration values. Fetching the enumeration values requires opening the array. This was previously changed but the opening of the array did not properly consider the the user configurations or timestamps. This change passes the user config and timestamps to the array open in python inside the query condition.
The overall design needs significant improvement. Opening the array inside the query condition is likely to cause other issues as now there are additional context created and additional performance impacts of opening the array and closing it after enumerations are fetched.
It is left to a followup pull request to change the design to a sustainable one that users enumerations from C++, in a similar way to the previous passing of …
> Pass user configuration/timestamp to query condition init

- apis/r/R/write_soma.R
- apis/r/man/write_soma_objects.Rd
- apis/r/tests/testthat/test-write-soma-objects.R
Allow `write_soma.data.frame()` to write factors as categoricals. `write_soma()` will no longer cast factors to characters prior to writing
Redo of #1683 since it got removed from #1559
> [r] Update `write_soma.data.frame()` to support categoricals

- apis/python/src/tiledbsoma/_dataframe.py
- apis/python/src/tiledbsoma/pytiledbsoma.cc
- apis/python/tests/test_dataframe.py
**Issue and/or context:** As discussed with @bkmartinjr. Parent context: #866.
**Changes:** When schema indicates non-categorical, permit auto-flattening write of categorical dataframe data in order to smooth the transition from tiledbsoma-without-categories to tiledbsoma-with-categories.
> [python] Categorical-write corner-case

- apis/python/tests/test_dataframe.py
The ordering if the boolean orderes test waa inversed between the TileDB enumeration definition and the Pandas test dataframe.
**Issue and/or context:** #866 and PR #1691
**Changes:**
> Fix pandas categorical test

- .github/workflows/python-ci-minimal.yml
- apis/python/src/tiledbsoma/_dataframe.py
- apis/python/src/tiledbsoma/_dense_nd_array.py
- apis/python/src/tiledbsoma/_sparse_nd_array.py
- apis/python/src/tiledbsoma/_tiledb_array.py
- apis/python/src/tiledbsoma/options/_tiledb_create_options.py
Consolidation and vacuuming need to be controllable by the user, and should default at the low level to off. In higher level APIs we need to follow up with automatic handling.
**Changes:**
Commit and fragment_metadata consolidation and vacuuming can improve the opening and query performance of SOMA experiments. Vacuuming requires slight coordination though and should not happen by default. Instead a platform config allows the user to control these operations based. This will be expanded to defaults for top-level `io` packages where its more likely a user is doing a one-shot ingestion and will want automatic handling.
A new platform config, `consolidate_and_vacuum` has been added which is a boolean to handle this behavior.
> [python] Consolidation and vacuuming are now platform configuration options

- apis/python/src/tiledbsoma/_dataframe.py
- apis/python/tests/test_dataframe.py
**Issue and/or context:** #866
> [python] Flatten categorical `soma_joinid` if presented at `write`

- apis/python/version.py
- libtiledbsoma/src/utils/logger.cc
- libtiledbsoma/test/CMakeLists.txt
Minor follow-up to https://github.com/single-cell-data/TileDB-SOMA/pull/1695
**Changes:**
- `logger->set_pattern` call should run unconditionally (currently runs on "!windows")
Also:
- remove `EXCLUDE_FROM_ALL` cmake annotation on `unit_soma` so that the target updates reliably
- add a note about a failure mode of `readGitVersion` when working from an unsynchronized fork
> Minor follow-up to #1695

- apis/python/tests/test_sparse_nd_array.py
- libtiledbsoma/src/soma/managed_query.cc
- libtiledbsoma/src/soma/managed_query.h
https://github.com/single-cell-data/TileDB-SOMA/issues/1703
**Changes:**
Modify `subarray_range_empty_` to be a mapping of dimension name to whether the query range is empty. `is_empty_query()` returns true if any of the ranges are empty.
> [c++] Fix for empty-indexed multi-dimensional array

- apis/r/DESCRIPTION
- apis/r/NEWS.md
- apis/r/R/SOMADataFrame.R
- apis/r/tests/testthat/test-SOMADataFrame.R
Add an check in `SOMADataFrame$create()` to detect if a column in the schema is ordered. If so, automatically mark the enumerations as such.
Note: this only happens if
- there are enumerations for the column
- the column in the arrow schema is marked as ordered
- there is no attribute `'ordered'` on the enumerations for the column
> [r] Update `SOMADataFrame$create()` to automatically mark `ordered()`

- apis/python/src/tiledbsoma/io/_registration/signatures.py
- apis/python/src/tiledbsoma/io/ingest.py
- apis/python/tests/test_registration_mappings.py
- apis/python/tests/test_update_dataframes.py
**Issue and/or context:** #1718
**Changes:**
* Accept `obs` / `var` either from mutations of the original source data or mutations of readback data
* Split out unit tests for fine-grained testing of signature computation, given a variety of places the SOMA index-column name may be located within a Pandas DataFrame (including a finer test for the problem reported on #1718)
* Parameterize `test_update_dataframes.py` to take a flag for use-mutated-original or use-mutated-readback
> [python] `update_obs`/`update_var` with original or readback source

- .github/workflows/r-ci.yml
- libtiledbsoma/src/soma/column_buffer.cc
- libtiledbsoma/src/soma/column_buffer.h
- libtiledbsoma/src/utils/arrow_adapter.h
Enumerations also support `ordered` variants of `factor` types. This PR adds support.
**Changes:**
The 'ordered' state is now reflected in the column buffer type, and the appropriate Arrow flag is set for the schema.
[SC 34679](https://app.shortcut.com/tiledb-inc/story/34679/soma-iterated-readers-cannot-handle-ordered-columns)
> [c++] Support return of `ordered` enumerations

- apis/r/DESCRIPTION
- apis/r/src/rinterface.cpp
- apis/r/src/rutilities.cpp
- apis/r/src/rutilities.h
This PR reduces the code surface by replacing three `integer64` conversion utility functions with use from the [RcppInt64](https://cran.r-project.org/package=RcppInt64) package.  A similar change was made to the tiledb-r package in a recent PR.
**Changes:**
Remove three helper functions, add a header import in two C++ files.
[SC 34753](https://app.shortcut.com/tiledb-inc/story/34753/r-replace-two-utility-functions-with-use-of-rcppint64-package-equivalents)
> [r] Replace three local utility functions with use of RcppInt64

- apis/python/setup.py
The newer version lets us clean up some existing dependency complications -- especially a constraint against newer versions of numpy, which was getting more problematic as time goes on.
> [python] update to numba 0.58

- apis/r/DESCRIPTION
- apis/r/NEWS.md
- apis/r/R/SOMADataFrame.R
- apis/r/tests/testthat/test-SOMADataFrame.R
Manual backport of #1720 to `release-1.5` as backport bot there silently failed to create a PR (not sure why)
> [r] Backport #1720 to `release-1.5`

- .github/workflows/r-ci.yml
- apis/python/setup.py
- apis/r/DESCRIPTION
- apis/r/tools/get_tarball.R
- libtiledbsoma/cmake/Modules/FindTileDB_EP.cmake
> Depend on core 2.17.1, TileDB-Py 0.23.1, TileDB-R 0.21.1

- .github/workflows/python-ci-minimal.yml
- .github/workflows/python-ci-single.yml
- apis/python/src/tiledbsoma/io/_registration/signatures.py
- apis/python/src/tiledbsoma/io/ingest.py
- apis/python/tests/test_update_dataframes.py
**Issue and/or context:** Validates `update_obs`/`update_var` when the newly added column is an enumeration: tracking issue #1710, with grandparent #866.
**Changes:**
> [python] Support enumerations in `update_obs`/`update_var`

- apis/python/setup.py
**Issue and/or context:** For #1733. Today we cannot build TileDB-SOMA in Conda with numba at 0.58.
**Changes:**
This is only for the release-1.5 branch (cc @thetorpedodog and @mlin) for the immediate term. #1723 still stands on `main` as tracked on #1733.
> [python][release-1.5] Revert to numba 0.57 until it's available in Conda

- .github/workflows/r-ci.yml
- .github/workflows/r-python-interop-testing.yml
> [ci/r] Use TileDB-R 0.21.1 binaries

- apis/python/src/tiledbsoma/_dataframe.py
- apis/python/tests/test_dataframe.py
**Issue and/or context:** #1739
**Changes:**
> [python] Check for downgraded categorical write

- .github/workflows/r-ci.yml
- .github/workflows/r-python-interop-testing.yml
- apis/python/src/tiledbsoma/_dataframe.py
- apis/python/src/tiledbsoma/_dense_nd_array.py
- apis/python/src/tiledbsoma/_sparse_nd_array.py
- apis/python/src/tiledbsoma/pytiledbsoma.cc
- apis/r/src/rinterface.cpp
- apis/r/src/riterator.cpp
- libtiledbsoma/src/cli/cli.cc
- libtiledbsoma/src/soma/managed_query.cc
- libtiledbsoma/src/soma/managed_query.h
- libtiledbsoma/src/soma/soma_array.cc
- libtiledbsoma/src/soma/soma_array.h
- libtiledbsoma/src/soma/soma_dataframe.cc
- libtiledbsoma/src/soma/soma_dense_ndarray.cc
- libtiledbsoma/src/soma/soma_sparse_ndarray.cc
- libtiledbsoma/test/test_query_condition.py
- libtiledbsoma/test/test_soma_array.py
- libtiledbsoma/test/unit_managed_query.cc
- libtiledbsoma/test/unit_soma_array.cc
#1744
**Changes:**
- Do not submit query until `read_next()` is called
- Remove `SOMAArray::submit()`
> [c++] Rework `SOMAArray` reader iterator sequence

- .github/workflows/r-ci.yml
The r-ci.yml workflow duplicates one step in what may have been a copy and paste error.
**Changes:**
Remove extra step.
[SC 35048](https://app.shortcut.com/tiledb-inc/story/35048/undo-copy-and-paste-error-in-workflow-file)
> [r] Remove duplicated step in workflow

- .github/workflows/r-valgrind.yaml
The nightly valgrind jobs have been failing since a recent (unrelated) R package update now requiring the newest version of package Matrix.
**Changes:**
An `apt upgrade` step ensures the already installed Matrix package updates to the most recent version that one of R packages depends upon.  It also does not hurt to update the other packages.  
The change was validated in a local Docker run and should restore the scheduled nightly job.
We can do this as a pure `apt` step (rather than via `update.packages()`) as this is an Ubuntu-only workflow.
[SC 35052](https://app.shortcut.com/tiledb-inc/story/35052/r-restore-valgrind-job)
> [r] Update installed packages in workflow

- apis/r/tests/testthat.R
- apis/r/tests/testthat/helper-test-tiledb-objects.R
As noted in #1774, recent runs of CI on macOS experienced instability and failures we had not seen.  This PR aims to address these.
**Changes:**
We reduce the test surface for macOS in a way that is equivalent to the non-CI tests, while allowing an override option.
[SC-35423](https://app.shortcut.com/tiledb-inc/story/35423/r-macos-ci-woes-of-late)
> [r] Tweak CI rules for extended runs for macOS (closes #1774)

- README.md
For some reason despite the tag `backport release-1.5` on #1757 we didn't get a backport. This is a manual replacement.
> Manually backport #1757

- apis/r/tests/testthat.R
- apis/r/tests/testthat/helper-test-tiledb-objects.R
For some reason despite the tag `backport release-1.5` on #1779 we didn't get a backport. This is a manual replacement.
> Manually backport #1779

- apis/python/src/tiledbsoma/_query_condition.py
- apis/python/src/tiledbsoma/_tiledb_array.py
- apis/python/src/tiledbsoma/io/ingest.py
- apis/python/src/tiledbsoma/pytiledbsoma.cc
- apis/python/src/tiledbsoma/query_condition.cc
- libtiledbsoma/src/soma/managed_query.h
- libtiledbsoma/src/soma/soma_array.h
- libtiledbsoma/test/test_query_condition.py
**Issue and/or context:** 
Issue #1742. Necessary prerequisite for #1756.
**Changes:**
- Separate `set_condition` from `SOMAArray` constructor
- `init_query_condition` function no longer takes `config` argument; now replaced by `ArraySchema` and a mapping of enumeration labels to NumPy datatype
- Rename `query_condition.cc` module loader to `load_query_condition`
- `PyQueryCondition::combine` static method no longer takes a ctx argument. Instead it uses the global ctx created by the `PyQueryCondition` constructor
> [python] Create separate `set_condition`

- apis/python/src/tiledbsoma/_query_condition.py
- apis/python/src/tiledbsoma/io/ingest.py
- apis/python/src/tiledbsoma/query_condition.cc
- apis/python/tests/test_experiment_query.py
**Issue and/or context:** This is an adaptation of PR https://github.com/TileDB-Inc/TileDB-Py/pull/1837 for issue https://github.com/single-cell-data/TileDB-SOMA/issues/1742
> [python] Support new set-membership query condition

- .github/workflows/python-ci-minimal.yml
- .github/workflows/r-ci.yml
- .github/workflows/r-python-interop-testing.yml
- apis/python/src/tiledbsoma/_dataframe.py
- apis/python/src/tiledbsoma/_dense_nd_array.py
- apis/python/src/tiledbsoma/_sparse_nd_array.py
- apis/python/src/tiledbsoma/_tiledb_array.py
- apis/python/src/tiledbsoma/options/_tiledb_create_options.py
Following https://github.com/single-cell-data/TileDB-SOMA/pull/1690#issuecomment-1766455633
To get green CI I needed to update R CI to install 0.20.3 which gets core 2.16, which is essential since 0.21/2.17 do now exist
> Backport #1690 to `release-1.4`

- apis/python/devtools/outgestor
- apis/python/src/tiledbsoma/io/ingest.py
- apis/python/tests/test_basic_anndata_io.py
**Issue and/or context:** #1764
**Changes:**
**Notes for Reviewer:** This PR is ready for review.
> [python] Outgest `uns`

- apis/python/src/tiledbsoma/_dense_nd_array.py
- apis/python/src/tiledbsoma/_sparse_nd_array.py
- apis/python/src/tiledbsoma/_tdb_handles.py
- apis/python/src/tiledbsoma/_tiledb_array.py
- apis/python/tests/test_dense_nd_array.py
**Issue and/or context:** In support of PR #1768 with issue #1769.
Needles to thread for `update_uns`:
The existing `tiledbsoma.io.update_obs`, `tiledbsoma.io.update_var`, `tiledbsoma.io.add_X_layer` methods all take as argument a `tiledbsoma.Experiment` which is already open for writing. Goal: do the same for `tiledbsoma.io.update_uns`.
Common use-case:
* Ingest data from AnnData to SOMA
* Outgest to AnnData; run ScanPy, curation, etc
* Write the updates back to SOMA
Technical factors:
* Whereas all the `X`, `obsm`, `varm`, `obsp`, `varp` are `SparseNDArray`, `uns` can contain `DenseNDArray` which are ingested from `numpy.ndarray`
* If the after-uns has `numpy.ndarray` that the before-uns didn't (new data on update), there is no problem
* If the after-uns has `numpy.ndarray` of the same …
> [python] Support default-coord reads of corner-written dense ND arrays

- libtiledbsoma/src/soma/managed_query.cc
- libtiledbsoma/test/test_soma_array.py
[sc-35642]
**Changes:**
* After setting `results_complete = false` for incomplete queries, the variable was not updated to `true` once it completed
> [c++] Correct `results_complete`

- apis/python/src/tiledbsoma/io/ingest.py
- apis/python/tests/test_basic_anndata_io.py
> [python] Allow `X_layer_name=None` for outgest of X-free experiments

- libtiledbsoma/cmake/Modules/FindCatch_EP.cmake
As on https://github.com/single-cell-data/TileDB-SOMA/actions/runs/6640942410/job/18042371782
Advice from @davisp given https://github.com/catchorg/Catch2/commit/52066dbc2a53f4c3ab2a418d03f93200a8245451
> [c++] Avoid intermittent CI fail building `catch2`

- apis/r/R/SOMAExperimentAxisQuery.R
- apis/r/R/write_seurat.R
- apis/r/tests/testthat/test-SOMAExperiment-query-matrix-outgest.R
- apis/r/tests/testthat/test-SeuratOutgest-assay.R
- apis/r/tests/testthat/test-SeuratOutgest-object.R
SeuratObject v5 creates v5 assays by default (didn't always). This PR sets options in `SOMAExperimentAxisQuery$to_seurat()` and `SOMAExperimentAxisQuery$to_seurat_assay()` to force SeuratObject to create v3 assays instead of v5 ones
At some point, adding support for exporting v5 assays will be needed, but that's a much larger task
Addresses chanzuckerberg/cellxgene-census#816
fixes #1808
> [r] Force exporting v3 assays with SeuratObject v5 installed

- apis/python/src/tiledbsoma/pytiledbsoma.cc
- libtiledbsoma/src/CMakeLists.txt
- libtiledbsoma/src/cli/cli.cc
- libtiledbsoma/src/soma/array_buffers.cc
- libtiledbsoma/src/soma/array_buffers.h
- libtiledbsoma/src/soma/column_buffer.cc
- libtiledbsoma/src/soma/column_buffer.h
- libtiledbsoma/src/soma/managed_query.cc
- libtiledbsoma/src/soma/managed_query.h
- libtiledbsoma/src/soma/soma_array.cc
- libtiledbsoma/src/soma/soma_array.h
- libtiledbsoma/src/utils/arrow_adapter.cc
- libtiledbsoma/src/utils/arrow_adapter.h
- libtiledbsoma/test/unit_soma_array.cc
- libtiledbsoma/test/unit_soma_group.cc
`libtiledbsoma` still erroneously required `spdlog` as a dependency due to exposing `logger.h` in the public API headers. This was reported in a channel internal to TileDB [here](https://tiledb.slack.com/archives/C052CFC4D2Q/p1698953405794929). 
**Changes:**
- Public headers using `logger.h` have been replaced by `logger_public.h`
- The `fmt` library is a part of `spdlog` which means it cannot be used or accessed except internally
- When possible, code that was using `fmt` in the public headers have now been moved into the `cc` source code which may continue to use the internal `logger.h`
- For `fmt` usage in templated functions, unit tests, and `pytiledbsoma.cc`, string formatting has been refactored to use either `std::ostringstream` or basic `std::string` …
> [c++] Remove `spdlog` requirement

- apis/python/src/tiledbsoma/_dataframe.py
- apis/python/src/tiledbsoma/pytiledbsoma.cc
- apis/python/tests/test_dataframe.py
- apis/r/src/rinterface.cpp
- apis/r/src/riterator.cpp
- libtiledbsoma/src/soma/column_buffer.h
- libtiledbsoma/src/utils/arrow_adapter.cc
- libtiledbsoma/src/utils/arrow_adapter.h
Updates in Pandas 2.0 has introduced changes to `DictionaryArray.from_arrays` that required refactoring in `pytiledbsoma.cc`. This bug motivated a change in the C++ `ArrowAdapter::to_arrow` method to further handle all supported enumerated types.
**Changes:**
- Several pre-existing C++ and Pybind11 modifications have pulled from https://github.com/single-cell-data/TileDB-SOMA/pull/1793
- Previously in the Python API the `ArrowTable` was converted from `Table.from_arrays` and then enumerations were added in an additional step with `DictionaryArray.from_arrays`. `DictionaryArray.from_arrays` has now been completely removed and now only uses `Table.from_arrays`
- The required changes for the above to work required refactoring of the C++ `ArrowAdapter::to_arrow` …
> [c++/python] Expanded enumeration support in `ArrowAdapter::to_arrow`

- .github/workflows/r-ci.yml
> [r] No more "Last 13 lines of output:" in CI

- apis/r/R/write_bioc.R
Bioc 3.18 and R 4.3.2 now throw deprecation warnings when casting from `S4Vectors::DataFrame` to `data.frame`; this PR suppresses deprecation warnings when doing that cast, but allows additional warnings to percolate through
[sc-36559]
replaces #1874
resolves #1875
> [r] Suppress deprecation warnings in `write_soma.DataFrame()`

- apis/python/tests/test_sparse_nd_array.py
Changes:
* increase sparsity of test arrays for blockwise iterator unit tests
* add an explicit soma context to some tests that benefit from a bit more memory in their initial query
Context: #1862
> [python] Make Python blockwise tests less resource-intensive

- .github/workflows/r-valgrind.yaml
The DESCRIPTION file now mandated `tiledb (>= 0.21.2)` but that version is not on CRAN and not in r2u leading to the valgrind workflow file being unable to satisfy the dependency.
**Changes:**
We add a package installation step for the corresponding r-universe binary.  
[SC 36508](https://app.shortcut.com/tiledb-inc/story/36508/r-adjust-r-valgrind-for-not-at-cran-not-in-r2u-version-of-tiledb)
> [r] Install required tiledb package version from r-universe

- apis/r/DESCRIPTION
**Issue and/or context:** #1867 #1862
**Changes:**
> [r] Depend on TileDB-R 0.21.3

- libtiledbsoma/src/soma/soma_array.cc
This fixes a bug reported on Slack where `SOMAArray::result_order` intermittenly returned garbage values.
**Changes:**
Set `result_order_` in the `SOMAArray` constructor initializer list.
> Set `result_order_` In Constructor Initializer List

- apis/python/src/tiledbsoma/_sparse_nd_array.py
The addition of bounding box calculation used Python built-in `max` to find the max coordinate for each dimension.  Using Arrow builtin is over 100X faster
In addition, this removes the extra copy (to_pylist) when the input is an Arrow ChunkedArray
Note: this does not address the extra copy operation in the write operation. That is filed as #1896
> [python] Fix performance regression in bounding-box calculation

- .github/workflows/r-ci.yml
SeuratObject imports S4 classes from Matrix, which results in S4 method/class caches that can become out of date. If Matrix gets updated, but the binary from CRAN is not rebuilt, then the S4 cache can refer to methods/classes that no longer exist (cause of R CI failure on 2023-11-08). This forces SeuratObject to be rebuilt from source to make use of the updated S4 methods/classes in Matrix
> [r] Install SeuratObject from source on macOS, rely on update r2u binary on linux

- apis/r/tools/r-ci.sh
CI on macOS can currently warns 'package xyz built under R 4.3.2' because the version installed is still hard-wired to 4.3.1 -- and because the [default version of R at GitHub Actions on macOS](https://github.com/actions/runner-images/blob/main/images/macos/macos-13-Readme.md) is still 4.3.1.
**Changes:**
The script is changed to use a fall-back default of 4.3.2.
[SC 36713](https://app.shortcut.com/tiledb-inc/story/36713/r-determine-r-version-at-run-time-in-r-ci-for-macos)
> [r] Determine the R version dynamically in r-ci

- apis/r/DESCRIPTION
- apis/r/NEWS.md
This is a small bugfix release
> [r] Update `DESCRIPTION` to 1.5.1

- .github/workflows/r-ci.yml
- apis/r/tests/testthat/test-SeuratOutgest-object.R
PR #1809 disabled some tests due to SeuratObject v5 bugs. These bugs have been patched on development versions of SeuratObject;as such, this PR restores those tests. It also pulls the development versions of SeuratObject from r-universe (replacing source builds for macOS) and only runs `Seurat` object outgestion tests for Seurat v4 or patched versions of Seurat v5
resolves #1839
> [r] Restore `expect_no_condition()` tests in `Seurat` object outgestion

- apis/r/tests/testthat/test-write-soma-objects.R
Some of our tests have been conditioned on being in 'extended' runs to manage test run time and avoid some false flags.
**Changes:**
This PR extends the conditioning to one more file.
[SC 36957](https://app.shortcut.com/tiledb-inc/story/36957/condition-one-more-test-file-on-extended-or-not)
> [r] Condition one more test file on 'extended mode'

- apis/python/src/tiledbsoma/_sparse_nd_array.py
Running TileDB-SOMA-Py unit tests on a system with `pyarrow` version 12:
```
...
File "/home/ubuntu/git/single-cell-data/TileDB-SOMA/apis/python/src/tiledbsoma/io/ingest.py", line 340, in from_h5ad
uri = from_anndata(
File "/home/ubuntu/git/single-cell-data/TileDB-SOMA/apis/python/src/tiledbsoma/io/ingest.py", line 545, in from_anndata
with _create_from_matrix(
File "/home/ubuntu/git/single-cell-data/TileDB-SOMA/apis/python/src/tiledbsoma/io/ingest.py", line 1336, in _create_from_matrix
_write_matrix_to_sparseNDArray(
File "/home/ubuntu/git/single-cell-data/TileDB-SOMA/apis/python/src/tiledbsoma/io/ingest.py", line 2217, in _write_matrix_to_sparseNDArray
soma_ndarray.write(
File "/home/ubuntu/git/single-cell-data/TileDB-SOMA/apis/python/src/tiledbsoma/_sparse_nd_array.py", line 250, in …
```
> [python] Fix `pyarrow.compute` import for version 12

- apis/r/R/utils-assertions.R
R-devel aka R 4.4.0 to be changes the behavior of `is.atomic` slightly.  Quoting from the [NEWS file of R-devel](https://github.com/wch/r-source/blob/e26e3f02a5e4255c4aad0842a46e141c03eed379/doc/NEWS.Rd):
**Changes:**
We adjust one line.  Tests behave admiringly (under r-devel, the one warning is unrelated and @mojaveazure is on it)
>  [ FAIL 0 | WARN 1 | SKIP 0 | PASS 2043 ]
[SC 37024](https://app.shortcut.com/tiledb-inc/story/37024/future-proofing-one-assertion)
> [r] Future-proof one assertion for an upcoming change in R 4.4.0

- codecov.yml
This PR divide the codecov report to two components (`python api` and `libtiledbsoma`) for better breakdown and analysis.
https://github.com/single-cell-data/TileDB-SOMA/issues/1915
> Adding components to codecov

- apis/python/src/tiledbsoma/io/ingest.py
Found during testing. This is trivial to review, and trivial to approve.
Before, with `tiledbsoma.io.from_h5ad` and `tiledbsoma.logging.debug()`:
```
START  Experiment.from_h5ad /var/s/a/pbmc-small.h5ad
START  READING /var/s/a/pbmc-small.h5ad
FINISH READING /var/s/a/pbmc-small.h5ad TIME 0.075 seconds
Registration: registering isolated AnnData object.
START  DECATEGORICALIZING
FINISH DECATEGORICALIZING TIME 0.000 seconds
START  WRITING foo
START  WRITING foo/obs <-------------- DUPLICATE
START  WRITING foo/obs
FINISH WRITING foo/obs TIME 0.047 seconds
...
```
After:
```
START  Experiment.from_h5ad /var/s/a/pbmc-small.h5ad
START  READING /var/s/a/pbmc-small.h5ad
FINISH READING /var/s/a/pbmc-small.h5ad TIME 0.075 seconds
Registration: registering isolated AnnData object.
START …
```
> [python] Avoid a double log statement on debug-mode ingest

- apis/python/src/tiledbsoma/io/_registration/ambient_label_mappings.py
- apis/python/tests/test_registration_mappings.py
Resolves #1917.
More context:
* Existing append-mode unit-test coverage is thorough when the user ingests data to one measurement, then appends to that same measurement
* Unit-test coverage was lacking (and a bug was present) when the append is to a second measurement.
Specifically, the second measurement's `var` already exists in the former case, but does not in the latter case, so this PR is about checking for that.
> [python] Append-mode ingestion with disjoint measurement names

- apis/r/R/utils.R
- apis/r/R/write_soma.R
- apis/r/tests/testthat/test-SOMAArrayReader-Iterated.R
- apis/r/tests/testthat/test-SOMAOpen.R
This PR is two-fold: 
1) remove use of SeuratObject code in ecosystem-agnostic workflows
2) update tests for `SOMAOpen()`
3) skip iterated matrix reader tests on CI
The current `write_soma.data.frame()` pipeline uses `SeuratObject::RandomName()`; this shouldn't happen as `write_soma.data.frame()` is supposed to be ecosystem agnostic. This PR re-implements `SeuratObject::RandomName()` as `random_name()` and uses that instead
The tests for `SOMAOpen` currently use `expect_true()` with a long call to `inherits()`; when these fail, the error message omits the call so all we see is
```r
inherits(...) is not TRUE
`actual`:   FALSE
`expected`: TRUE 
```
this PR replaces `expect_true()` with `expect_s3_class()` so that we get error messages about the class failure. In addition, this expands two …
> [r] Update tests

- apis/r/R/RcppExports.R
- apis/r/R/utils-tiledb.R
- apis/r/src/RcppExports.cpp
- apis/r/src/rutilities.cpp
- apis/system/tests/test_version_match.py
This is a minor 'quality of life' improvement which aligns the version number display to show, say
```r
> tiledbsoma::show_package_versions()
tiledbsoma:    1.5.1
tiledb-r:      0.21.3.3
tiledb core:   2.18.0
libtiledbsoma: 2.18.0
R:             R version 4.3.2 (2023-10-31)
OS:            Ubuntu 23.04
> 
```
instead of 
```r
> tiledbsoma::show_package_versions()
tiledbsoma:    1.5.1                                    
tiledb-r:      0.21.3.3                                   
tiledb core:   2.18.0                                   
libtiledbsoma: libtiledb=2.18.0               
R:             R version 4.3.2 (2023-10-31)   
OS:            Ubuntu 23.04  
>
```
**Changes:**
The version string is now constructed locally from the version triplet and no longer exports …
> [r] No longer show 'libtiledb=' before core library version triplet

- apis/python/setup.py
**Issue and/or context:** Following on https://github.com/single-cell-data/TileDB-SOMA/issues/1926#issuecomment-1834695149
**Changes:** The bug has been bisected to `pyarrrow==12.0` good and `pyarrow==13.0` bad, along with `aws-sdk-cpp` 1.11, on MacOS (`x86_64` or `arm64`).  The `aws-sdk-cpp` issues https://github.com/aws/aws-sdk-cpp/issues/2411
and https://github.com/aws/aws-sdk-cpp/issues/2699 are many months old, and we cannot realistically expect traction. Therefore we pin `pyarrow<13.0` on MacOS. Also note we have `import pyarrow_hotfix` for the `pyarrow` CVE. (See also #1926.)
> [python] Work around bug with `aws-sdk-cpp` and `pyarrow` on MacOS

- apis/python/setup.py
- apis/python/tests/test_experiment_query.py
Resolves #1930 together with https://github.com/single-cell-data/SOMA/pull/179. Requires the latter to be released before tests can pass, so this is still marked as draft.
**Changes:**
This PR only contains the unit tests. All the code changes are in the SOMA repo.
> [python] Add unit tests for obsm, obsp, and to_anndata

- apis/python/tests/test_experiment_query.py
Backports #1934 to `release-1.6`
> [Backport release-1.6][python] Add unit tests for obsm, obsp, and to_anndata

- apis/r/DESCRIPTION
- apis/r/NEWS.md
- apis/r/R/RcppExports.R
- apis/r/R/SOMADataFrame.R
- apis/r/R/SOMADenseNDArray.R
- apis/r/R/SOMASparseNDArray.R
- apis/r/tests/testthat/test-SOMADataFrame.R
- apis/r/tests/testthat/test-SOMADenseNDArray.R
- apis/r/tests/testthat/test-SOMASparseNDArray.R
**Issue and/or context:** `TileDBArray`-based classes are returned in an invalid state after calling `$write()` in which:
-  `self$private$.mode == "open"` but 
- `tiledb::tiledb_array_is_open(self$object)` is `FALSE`
This happens because [tiledb-r closes arrays](https://github.com/TileDB-Inc/TileDB-R/blob/faf3ecadc9b739760812f648774f4b21a4d70f19/R/TileDBArray.R#L1412-L1413) after performing a write via `"[<-"`,  so the handle is closed following [this step](https://github.com/single-cell-data/TileDB-SOMA/blob/8bf00f9eaf2bb9c333c16a1b78fa988667aa5db3/apis/r/R/SOMADataFrame.R#L188) but the internal `private$.mode` isn't updated to reflect this.
**Changes:** Arrays are now re-opened in write mode after performing a write to be spec compliant. 
> [r] Arrays should remain open after write

- .github/workflows/python-ci-single.yml
- libtiledbsoma/src/soma/managed_query.cc
- libtiledbsoma/src/soma/managed_query.h
- libtiledbsoma/src/soma/soma_array.cc
- libtiledbsoma/test/unit_managed_query.cc
Across both APIs we have observed the `SOMAArray` intermittenly segfault when accessing the array. This occurs due to a race condition where we have multiple read queries and one query closes the array before the other queries have completed. When a query that has not completed tries to access a closed array, it segfaults. The solution is to modify the C++ `ManagedQuery` so that it performs async queries and waits for all query threads to complete before closing the `SOMAArray`.
**Changes:**
- Changes pulled from #1817
> [c++] Modify `ManagedQuery` to perform async queries

- apis/r/DESCRIPTION
- apis/r/NEWS.md
**Issue and/or context:** Keeps `main` in sync with `release-1.6` after #1943, which I should have applied the other way round but did not
**Changes:**
> [r] Apply #1943 to main

- apis/python/src/tiledbsoma/io/ingest.py
- apis/python/tests/test_basic_anndata_io.py
**Issue and/or context:** Bug report from user attempting to append an AnnData object to an existing SOMA experiment using a custom name for `var_id`.  
**Changes:** The `var_id_name` argument is no longer ignored. Relevant unit tests were updated to validate the set of columns read back from `obs` and `var` exactly match the input.
> [python] Fix `from_anndata()` to respect `var_id_name`

- apis/python/src/tiledbsoma/_query_condition.py
- libtiledbsoma/test/test_query_condition.py
This error was reported in an internal channel by @ckrilow.
**Changes:**
- These changes have already been applied to TileDB-Py https://github.com/TileDB-Inc/TileDB-Py/pull/1877 but need to also be ported over to TileDB-SOMA
> [python] QueryCondition should error out if given empty set

- .github/workflows/r-ci.yml
- .github/workflows/r-python-interop-testing.yml
- apis/r/DESCRIPTION
- apis/r/NEWS.md
- apis/r/tests/testthat/test-SOMAArrayReader-Iterated.R
- apis/r/tests/testthat/test-SOMAOpen.R
- apis/system/tests/test_version_match.py
- codecov.yml
1.5.2 will deliver a Python-only bugfix on the `release-1.5` branch. R is not affected, other than our commitment to keep Python and R API versions synchronized.
Please also see https://github.com/single-cell-data/TileDB-SOMA/wiki/Branches-and-releases
> [r] Update `DESCRIPTION` and `NEWS.md` for 1.5.2

- .github/workflows/libtiledb-ci.yml
- libtiledbsoma/src/CMakeLists.txt
- libtiledbsoma/test/CMakeLists.txt
- scripts/bld
> [C++] Extending codecov to cover tiledbsoma library

- apis/python/src/tiledbsoma/_dataframe.py
- apis/python/tests/test_dataframe.py
#1973
When not all the categorical values are present in the column to be written, the index values are incorrect and results in data loss.
**Changes:**
Update the column with the extended enumerations so that the index values are mapped correctly.
> [python] Fix data loss for multiple writes with `Enumeration` extend

- apis/python/src/tiledbsoma/_dataframe.py
- apis/python/tests/test_dataframe.py
https://github.com/single-cell-data/TileDB-SOMA/issues/1975
**Changes:**
Raise `ValueError` if the number of enumerations exceeds the limit of the index value type.
> [python] Error if extending enum past index type limit

- .github/workflows/r-ci.yml
- apis/r/R/SOMADataFrame.R
- apis/r/tests/testthat.R
- apis/r/tests/testthat/test-SOMAArrayReader-Iterated.R
- apis/r/tests/testthat/test-SOMADataFrame.R
When a `factor` variable `factor(c("A", "B", "A"))` is written, we write vector `c(1,2,1)` and labels `c("A", "B")`.  So far, so good.  As @bkmartinjr demonstrated if we then append a `factor(c("B", "C", "B"))` that is constructed without knowledge of the prior factor we also see `c(1,2,1)` and labels `c("B", "C"))`.   We were already correctly augmenting the stored enumeration labels to be `c("A", "B", "C")` but we still wrote `c(1,2,1)` -- when it should be `c(2, 3, 2)`.   
**Changes:**
The missing step of 're-levelling' the factor variable that is appended is now added.  
New tests have been added.
[SC 38305](https://app.shortcut.com/tiledb-inc/story/38305/diagnose-multiple-categorical-write-issue-for-tiledb-soma-py-and-tiledb-soma-r)
> [r] Ensure factors are releveled before appending w/ expanded levels

- .github/workflows/r-ci.yml
- .github/workflows/r-python-interop-testing.yml
- apis/python/src/tiledbsoma/io/ingest.py
- apis/python/tests/test_basic_anndata_io.py
**Issue and/or context:** #1993 for the `release-1.6` branch
**Changes:**
> Allow specification of X names on ingest [release-1.6]

- apis/python/setup.py
- apis/python/tests/test_dataframe.py
- apis/r/DESCRIPTION
- apis/r/tools/get_tarball.R
- libtiledbsoma/cmake/Modules/FindTileDB_EP.cmake
- scripts/update-tiledb-version.py
> Depend on TileDB core 2.19, TileDB-Py 0.25, TileDB-R 0.23

- .pre-commit-config.yaml
- apis/python/setup.py
somacore v1.0.7 is fully compatible with v1.0.6 and does not introduce any behavior changes. It does *prepare* us for the reindexer change: https://github.com/single-cell-data/TileDB-SOMA/pull/1728
Note: This can be folded into #1728 if we want, and I have no objections to doing so.
> Update to use somacore==1.0.7.

- apis/r/DESCRIPTION
- apis/r/NEWS.md
Following our established procedure:
https://github.com/single-cell-data/TileDB-SOMA/wiki/Branches-and-releases
The content of 1.5.3 is #1993 and #2003 which are Python-only.
> TileDB-SOMA 1.5.3

- apis/r/DESCRIPTION
- apis/r/NEWS.md
This is a direct analog of #2004.
* 1.5.3 is a Python-only bugfix on the `release-1.5` branch, delivering #1995 . #2004 R-tags 1.5.3.
* 1.6.2 is a Python-only bugfix on the `release-1.6` branch, delivering #1996 . This PR R-tags 1.6.2.
* Both #1995 and #1996 are backports to their respective branches of the same bugfix #1993
> [r] tiledbsoma 1.6.2

- apis/r/R/SOMADataFrame.R
- apis/r/tests/testthat/test-SOMADataFrame.R
As discussed in #1975, index type can overflow when factor levels are added.
**Changes:**
When factor levels are added, the sum of 'before plus added' is compared to the capacity of the index type, and an error is signalled if the latter is exceeded.  An unit test has been where writing 130 levels exceeds the possible 128 on `int8_t` leading to error and passes on `uint8_t` indexing.
[SC 39079](https://app.shortcut.com/tiledb-inc/story/39079/r-ensure-factor-levels-do-not-overflow)
[SC 38448](https://app.shortcut.com/tiledb-inc/story/38448/dataframe-categorical-handling-does-not-handle-extension-past-index-type-limit)
#1975
> [r] Ensure addition of factor levels does not overflow capacity of index type

- apis/python/setup.py
Allow numba 0.57.1 which has an important bugfix per @bkmartinjr
> [release-1.6][python] Allow numba 0.57.1

- apis/python/setup.py
Allow numba 0.57.1 which has an important bugfix per @bkmartinjr
> [release-1.5][python] Allow numba 0.57.1

- apis/r/DESCRIPTION
- apis/r/NEWS.md
- apis/r/R/write_soma.R
- apis/r/man/write_soma_objects.Rd
- apis/r/tests/testthat/test-write-soma-objects.R
This PR adds a `key` parameter to three `write_soma()` methods enabling automatic registration of an array into the parent collection. The following methods have been modified
- `write_soma.data.frame()`: for `data.frame` and derived objects (eg. `tibble`)
- `write_soma.matrix()`: for dense matrices
- `write_soma.TsparseMatrix()`: for sparse matrices
By default, `key` is set to `NULL`, which disables registration and preserves existing behavior
> [r] Add support for registering arrays with `write_soma()`

- libtiledbsoma/src/CMakeLists.txt
- libtiledbsoma/test/CMakeLists.txt
This issue was reported in https://github.com/TileDB-Inc/tiledbsoma-feedstock/issues/71 by @jdblischak.
**Changes:**
Previously the `CMAKE_C{,XX}_FLAGS` variable was being replaced by `$ENV{TILEDBSOMA_COVERAGE}`, causing issues when compiling in the [tiledbsoma-feedstock](https://github.com/TileDB-Inc/tiledbsoma-feedstock) nightly builds. The change appends this variable to any existing flags instead of replacing it.
> [c++] Append `TILEDBSOMA_COVERAGE` to cmake flags

- apis/r/R/RcppExports.R
- apis/r/R/SOMADataFrame.R
- apis/r/src/RcppExports.cpp
- apis/r/src/rutilities.cpp
In #2008 we added the ability to test enum (aka `factor`) levels from overflowing when appending, and relied on a small helper in tiledb-r.  Which is only in the development version which we do not want to impose on all deployments so this PR brings over a local copy of the helper function.
**Changes:**
Provide a local `tiledb_datatype_max_value()`
[SC 39486](https://app.shortcut.com/tiledb-inc/story/39486/ensure-overflow-detection-for-enums-does-not-require-dev-version-of-tiledb-r)
This can be removed / replaced on the next tiledb-r release is out, it can rely on the development version but we do not want to impose the development version on every (non-CI) run
> [r] Add a helper function to determine max value per int type

- .github/workflows/r-ci.yml
- apis/r/tests/testthat/test-SOMAArrayReader-Iterated.R
- apis/r/tests/testthat/test-SeuratIngest.R
- apis/r/tests/testthat/test-SummarizedExperimentIngest.R
- apis/r/tools/r-ci.sh
Sporadic and generally non-reproducible segmentation faults in CI have beeen an irritant. This PR enables support of a glibc feature (apparently now deprecated, but still supported by Linux distros) to wrap a script `catchsegv` around an execution leading to a stacktrace and register dump in case of segmentation fault.
**Changes:**
The `r-ci.sh` script has been altered to, if `catchsegv` is opted into and on Linux, install the `glibc-tools` package and prefix both coverage and test calls with `catchsegv`.
[SC 39492](https://app.shortcut.com/tiledb-inc/story/39492/add-libsegfault-backtrace-dumping-to-soma-ci)
> [r] Enable opt-in use of 'catchsegv', enable in CI on Linux

- apis/python/tests/test_dataframe.py
- apis/python/tests/test_experiment_query.py
- apis/python/tests/test_sparse_nd_array.py
https://github.com/single-cell-data/TileDB-SOMA/issues/2038
**Changes:**
* `scipy.sparse.vstack` no longer takes in generator argument directly - relevant unit tests have been replaced with list comprehension semantics
* Temporarily compare categorical string-like dtypes by `kind` to get CI passing - bytes are being output as str and needs to be fixed in tiledb-py, not tiledb-soma
> [python] Update unit tests for pandas 2.2 and scipy 1.12

- apis/python/MANIFEST.in
#2032
**Changes:**
Add `common.h` to `MANIFEST.in` as C++ (source and) header files are not added by `setuptools` to the distribution by default.
Proof of working: https://github.com/single-cell-data/TileDB-SOMA/actions/runs/7603111075
> [python] Add `common.h` to `MANIFEST.in`

- libtiledbsoma/src/soma/soma_array.h
- libtiledbsoma/src/soma/soma_dataframe.h
- libtiledbsoma/src/soma/soma_dense_ndarray.h
- libtiledbsoma/src/soma/soma_sparse_ndarray.h
- libtiledbsoma/src/utils/common.h
From https://github.com/single-cell-data/TileDB-SOMA/actions/runs/7618476508/job/20749733125#step:5:916
**Changes:**
The odd thing is this fires only on `pkgdown` CI, which in turn only runs on releases ... 🤔
> [c++/ci] Fix a `pkgdown` CI error about unnecessary semicolons

- .github/workflows/pkgdown.yaml
**Issue and/or context:** As described in #2052.
**Changes:** Run the install nightly, but not the deploy, as the install surfaces a `libtiledbsoma` build path that we want to flex regularly, without waiting for it to fail at release-tag time.
> [r/ci] Run pkgdown build, but not deploy, in nightly cron

- apis/python/src/tiledbsoma/_experiment.py
- apis/python/src/tiledbsoma/_index_util.py
- apis/python/tests/test_indexer.py
Found by @bkmartinjr on read-through. (See also #915 for context.)
* We have `_util.py` and `utils.py`, which seems one too many
* We have been following the convention of putting private-ish things with leading `_` module/class/function/etc names
**Changes:**
* I couldn't move `build_index` from `utils.py` to `_util.py`, as this resulted in a circular-import error for `SOMATileDBContext`
* So I renamed `utils.py` to `_index_util`.
> [python] Rename `utils.py` to `_index_util.py`

- apis/python/src/tiledbsoma/_dataframe.py
- apis/python/src/tiledbsoma/soma_dataframe.cc
- apis/python/tests/test_dataframe.py
- libtiledbsoma/src/soma/soma_array.cc
- libtiledbsoma/src/soma/soma_array.h
- libtiledbsoma/src/soma/soma_dataframe.cc
- libtiledbsoma/src/soma/soma_dataframe.h
As reported internally, the code below breaks as the AWS S3 settings are ignored.
```
uri = "s3://cellxgene-census-public-us-west-2/cell-census/2024-01-16/soma/"
with soma.open(
uri,
context=soma.SOMATileDBContext(
tiledb_config={
"vfs.s3.no_sign_request": "true",
"vfs.s3.region": "us-west-2",
}
),
) as census:
census["census_data"]["homo_sapiens"].obs.read()
```
```
SOMAError: Error opening array: 's3://cellxgene-census-public-us-west-2/cell-census/2024-01-16/soma/census_data/homo_sapiens/obs'
[TileDB::Array] Error: Caught std::exception: [TileDB::S3] Error: Error while listing with prefix 's3://cellxgene-census-public-us-west-2/cell-census/2024-01-16/soma/census_data/homo_sapiens/obs/' and delimiter '/'[Error Type: 100] [HTTP Response Code: 301] [Exception: …
```
> [python] Pass config options to `DataFrame.read`

- apis/python/src/tiledbsoma/io/ingest.py
- apis/python/src/tiledbsoma/options/_tiledb_create_options.py
- apis/python/tests/test_io.py
**Issue and/or context:** Implement chunked writes for `DataFrame` in addition to `NDArray`. Along the way, offer a centralized nbytes cap for remote object stores.
* For `SparseNDArray`, even before this PR, COO cell sizes are already capped at 24 bytes: 8 each for `soma_dim_0` and `soma_dim_1`, and 1,2,4,8 for `soma_data` depending on the cell-value type (8 bytes for `float64` and `int64`). This means that before this PR, given `goal_chunk_nnz = 100_000_000` times cell cap of 24 bytes, we already had a hard cap of 2_400_000_000 bytes per chunked write. Now we do explicit byte arithmetic, which is a logging/visibility improvement.
* For `DenseNDArray` aside from `uns`, the same is true but cell sizes are capped at 8 not 24 since we don't offer IJV triples on the …
> [python] Chunked writes for DataFrame; byte-caps for Arrow-table writes

- apis/python/src/tiledbsoma/_read_iters.py
- apis/python/src/tiledbsoma/_sparse_nd_array.py
**Issue and/or context:** #2066
Block-wise iterators still use panda indexers and this must to switch to our new indexer.
**Changes:**
I may add a benchmark for this change later.
> [python] Using optimized reindexer in blockwise iterators

- apis/python/src/tiledbsoma/_experiment.py
- apis/python/src/tiledbsoma/_index_util.py
- apis/python/src/tiledbsoma/_read_iters.py
- apis/python/src/tiledbsoma/_sparse_nd_array.py
- apis/python/tests/test_indexer.py
Backports #2081 to the `release-1.7` branch
> [Backport release-1.7] [python] Using optimized reindexer in blockwise iterators

- apis/python/src/tiledbsoma/_index_util.py
Backports #2094 to the `release-1.7` branch
> [Backport release-1.7] [python] Fix some docstring typos

- apis/python/tests/test_indexer.py
- libtiledbsoma/src/reindexer/reindexer.cc
When key size is smaller than thread count, we incorrectly throw an exception
**Changes:**
> [c++] Fix for error when the key array size is smaller than thread count

- apis/r/tools/get_tarball.R
When we do releases and depedency bumps following our [established procedure](https://github.com/single-cell-data/TileDB-SOMA/wiki/Branches-and-releases), `apis/r/tools/get_tarball.R` has always required a manual-edit step.
This PR lets `apis/r/tools/get_tarball.R` be updated hands-off, automatically, along with `libtiledbsoma/cmake/Modules/FindTileDB_EP.cmake`.
This PR centralizes the hash-computation and file-update logic in a way that no longer requires the operator to be familiar with C++/Python/R build internals.
* Check out today's `main`
* `./scripts/update-tiledb-version.py 2.19.0`
* `git diff`
`scripts/update-tiledb-version.py 2.19.0`
```
diff --git a/apis/r/tools/get_tarball.R b/apis/r/tools/get_tarball.R
index 34d435d6..52b87072 100644
--- a/apis/r/tools/get_tarball.R
+++ …
```
> [r] Let `get_tarball.R` interop with `update-tiledb-version.py`

- apis/r/configure
**Issue and/or context:** This arose while doing a Docker build within a particular TileDB-internal build environment. There exists platforms within which
```
root@1f09efc85df8:/# /bin/sh
/bin/sh: 2: export: -std: bad variable name
```
**Changes:** Properly double-quote variables which may contain spaces.
As discussed in Slack.
This will also be applied to the `main` branch: #2103
> [r] Fix quoting for a particular Docker-build environment (`release-1.7`)

- apis/python/src/tiledbsoma/_arrow_types.py
- apis/python/tests/test_basic_anndata_io.py
https://github.com/single-cell-data/TileDB-SOMA/issues/2014
**Changes:**
* "object" and "category" need explicit casting as the converter functions `pa.infer_type` and `pa.from_numpy_dtype` do not map to the correct associated pandas extension dtype
* Use `None` instead of `pa.null` as `pa.null` can only be used for numerics
> [python] Specially handle cast for object and category dtypes

- apis/python/setup.py
- apis/python/src/tiledbsoma/pytiledbsoma.cc
- apis/python/src/tiledbsoma/reindexer.cc
In #1793, for readability purposes, the Python bindings were reorganized so that class bindings resided in their own files. In #1728, the `Reindexer` bindings were placed into `pytiledbsoma.cc`, which at the time was the singular file in which all bindings were placed, with plans for a follow-up PR to separate them out.
**Changes:**
The `Reindexer` binding class is now in `reindexer.cc`.
> [python] Reorganize `Reindexer` bindings into separate file

- apis/python/src/tiledbsoma/io/_registration/ambient_label_mappings.py
- apis/python/tests/test_registration_mappings.py
**Issue and/or context:** `tiledbsoma.io.register_anndatas()` would fail to return all obs/var IDs on disk if they exceeded the configured column-buffer size.
**Changes:** IDs are now accumulated across batches.
> [python] Accumulate obs/var IDs across batched reads in `register_anndatas()`

- apis/python/setup.py
Numba was pinned to `~=0.58.0`. With numba `0.59.0` released, there is demand for allowing more recent variants. See also #1733.
**Changes:**
Numba pin modified to `>=0.58.0`
> [python] relax numba dependency

- apis/python/setup.py
- apis/r/configure
- libtiledbsoma/src/soma/soma_array.cc
- libtiledbsoma/src/soma/soma_array.h
- libtiledbsoma/src/soma/soma_collection.cc
- libtiledbsoma/src/soma/soma_collection.h
- libtiledbsoma/src/soma/soma_dataframe.cc
- libtiledbsoma/src/soma/soma_dataframe.h
- libtiledbsoma/src/soma/soma_dense_ndarray.cc
- libtiledbsoma/src/soma/soma_dense_ndarray.h
- libtiledbsoma/src/soma/soma_group.h
- libtiledbsoma/src/soma/soma_object.cc
- libtiledbsoma/src/soma/soma_object.h
- libtiledbsoma/src/soma/soma_sparse_ndarray.cc
- libtiledbsoma/src/soma/soma_sparse_ndarray.h
[#2123](https://github.com/single-cell-data/TileDB-SOMA/issues/2123)
**Changes:**
- DRY: refactor `SOMAArray` and `SOMAGroup` to inherit from `SOMAObject`
- Set `-mmacosx-version-min=11.0` to support usage of  C++17 feature `std::filesystem::path`
These changes were picked out of https://github.com/single-cell-data/TileDB-SOMA/pull/1817. I am opening smaller PRs to make it easier to review this time.
> [c++] Refactor `SOMAArray` and `SOMAGroup` to inherit from `SOMAObject`

- apis/python/tests/test_indexer.py
#2091 
**Changes:**
Uses `pytest.parametrize`, `pytest.raises`. and `numpy.testing` in the reindexer unit tests. Splits the pass/fail unit tests into separate test functions and inlines the testing logic.
> [python] `pytest`-ify reindexer unit tests

- .github/workflows/python-ci-full.yml
- .github/workflows/python-ci-minimal.yml
* Issue #1849 
* I put up PR #2108 and it was green so I merged it
* Now PRs #2119 #2136 and anything else new is failing MacPS Python 3.12 CI fails
* Unable to install wheel for `pyarrow`
* https://github.com/single-cell-data/TileDB-SOMA/actions/runs/7896650237/job/21550972931?pr=2138 for example
* Another issue: TileDB-Py doesn't have wheels for 3.12
* https://pypi.org/project/tiledb/#files
**Changes:**
* Leave 3.12 support in place -- don't entirely revert #1849 
* Don't fail CI for 3.12 until the above is resolved
* Leave #1849 open for tracking
> [python/ci] Leave 3.12 support provisional

- .github/workflows/python-ci-minimal.yml
- apis/python/src/tiledbsoma/io/ingest.py
- apis/python/tests/test_basic_anndata_io.py
**Issue and/or context:** Issue #2079
> [python] Outgest additional X layers to AnnData

- .github/workflows/python-ci-minimal.yml
- apis/python/src/tiledbsoma/io/ingest.py
- apis/python/tests/test_basic_anndata_io.py
> [Backport release-1.7] [python] Add type checks to `obsm`, `obsp`, `varm` and `varp` early in ingestion

- apis/python/src/tiledbsoma/options/_tiledb_create_options.py
We mistakenly used `_name` in the literal rather than `_type`.
> Fix inconsistency in DictFilterSpec docstring.

- apis/r/DESCRIPTION
- apis/r/R/SOMAExperimentAxisQuery.R
- apis/r/R/utils-seurat.R
- apis/r/R/utils.R
- apis/r/tests/testthat/test-SeuratOutgest-command.R
Fix a bug in Seurat ingestion where `exp/uns` is present but `exp/uns/seurat_commands` is not
fixes #2153
> [r] Fix Seurat ingestion with missing command logs collection

- apis/r/DESCRIPTION
- apis/r/R/SOMAExperimentAxisQuery.R
- apis/r/R/utils-seurat.R
- apis/r/R/utils.R
- apis/r/tests/testthat/test-SeuratOutgest-command.R
Backport #2154 to the `release-1.7` branch.
I don't know why the backport bot silently did nothing here.
> [Backport release-1.7] [r] Fix Seurat ingestion with missing command logs collection

- .github/workflows/r-ci.yml
- .github/workflows/r-python-interop-testing.yml
- apis/r/tools/get_tarball.R
- libtiledbsoma/cmake/Modules/FindTileDB_EP.cmake
**Issue and/or context:** Applies the same pattern as #1972 did for the `release-1.5` branch and `#1996` did for the `release-1.6` branch.
**Changes:** As on #1972 and #1996. This is necessary since [TileDB-R 0.24.0](https://tiledb-inc.r-universe.dev/tiledb) now exists, and the R `DESCRIPTION` file does not syntactically support `tiledb < 0.24` or `tiledb <= 0.24`. Therefore (see also this comment https://github.com/single-cell-data/TileDB-SOMA/pull/1996#issuecomment-1881702859) we do a controlled downgrade to TileDB-R 0.23 on this PR, for the `release-1.7` branch.
Every stanza in this PR has been proved necessary via the dialog on #1972 and #1996. See in particular https://github.com/single-cell-data/TileDB-SOMA/pull/1996#pullrequestreview-1809807165.
> [r/ci] Controlled downgrade for TileDB-R 0.23

- apis/python/src/tiledbsoma/options/_soma_tiledb_context.py
https://github.com/single-cell-data/TileDB-SOMA/pull/2158#discussion_r1500959184
This was my fault for merging this PR in before getting a follow-up review for my change.
**Changes:**
Use `_internal_tiledb_config` in `native_context`.
> [python] Use `_internal_tiledb_config` in `native_context`

- apis/python/src/tiledbsoma/_arrow_types.py
- apis/python/src/tiledbsoma/_dataframe.py
- apis/python/src/tiledbsoma/_dense_nd_array.py
- apis/python/src/tiledbsoma/_tdb_handles.py
- apis/python/src/tiledbsoma/_tiledb_object.py
- apis/python/src/tiledbsoma/soma_array.cc
- apis/python/src/tiledbsoma/soma_dense_ndarray.cc
- apis/python/src/tiledbsoma/soma_object.cc
- apis/python/tests/test_dataframe.py
- apis/python/tests/test_dense_nd_array.py
- libtiledbsoma/src/soma/soma_dense_ndarray.h
https://github.com/single-cell-data/TileDB-SOMA/issues/2078
**Changes:**
Use `clib.DenseNDArray` for read path, replacing usage of `tiledb.Array`.
These changes were picked out of https://github.com/single-cell-data/TileDB-SOMA/pull/1817.
These changes are on top of https://github.com/single-cell-data/TileDB-SOMA/pull/2129.
> [python] Use bindings for `DenseNDArray` readpath

- .github/workflows/r-ci.yml
- apis/python/setup.py
- apis/r/DESCRIPTION
- apis/r/tools/get_tarball.R
- libtiledbsoma/cmake/Modules/FindTileDB_EP.cmake
- scripts/update-tiledb-version.py
> Use TileDB Core 2.20, TileDB-Py 0.26, TileDB-R 0.24

- apis/r/DESCRIPTION
Following our [established procedure](https://github.com/single-cell-data/TileDB-SOMA/wiki/Branches-and-releases) in prep for upcoming 1.8.0
> [r] Set `apis/r/DESCRIPTION` version to 1.8.99

- apis/python/src/tiledbsoma/io/__init__.py
- apis/python/tests/test_registration_mappings.py
**Issue and/or context:** The subpackage `tiledbsoma.io._registration` is mostly internals, and rightly so. There are `tiledbsoma.io.register_anndatas` and `tiledbsoma.io.register_h5ads` exposed at `tiledbsoma.io`, and this is _almost_ sufficient.
I noted on #2172, though, something I should have thought of -- namely, if any user wants to do Python type-checking on the _result_ of `tiledbsoma.io.register_anndatas` or `tiledbsoma.io.register_h5ads` then tney currently need to cal this `tiledbsoma.io._registration.ExperimentAmbientLabelMapping`. This is non-ideal since they have to type out something with a leading underscore.
**Changes:** Expose `tiledbsoma.io.ExperimentAmbientLabelMapping`
> [python] Expose `tiledbsoma.io.ExperimentAmbientLabelMapping`

- apis/python/src/tiledbsoma/reindexer.cc
- apis/python/tests/test_indexer.py
- libtiledbsoma/src/CMakeLists.txt
- libtiledbsoma/src/reindexer/test_indexer_dtatye_perf.py
https://github.com/single-cell-data/TileDB-SOMA/issues/2099
**Changes:**
> [c++] Optimizing indexer for pandas and pyarrow

- apis/python/src/tiledbsoma/_experiment.py
- apis/python/src/tiledbsoma/_index_util.py
- apis/python/src/tiledbsoma/_read_iters.py
- apis/python/src/tiledbsoma/reindexer.cc
- apis/python/tests/test_indexer.py
- apis/python/tests/test_reindexer_api.py
- libtiledbsoma/src/CMakeLists.txt
- libtiledbsoma/src/reindexer/reindexer.cc
- libtiledbsoma/src/reindexer/reindexer.h
- libtiledbsoma/src/reindexer/test_indexer_dtatye_perf.py
- libtiledbsoma/src/soma/soma_context.cc
- libtiledbsoma/src/soma/soma_context.h
- libtiledbsoma/test/test_indexer.cc
**Issue and/or context:** #2149
**Changes:**
> [c++/python] Use a shared threadpool for the reindexer

- .github/workflows/python-ci-full.yml
- .github/workflows/python-ci-minimal.yml
- apis/python/setup.py
- apis/python/tests/test_soma_array.py
**Issue and/or context:** #1790
**Changes:** 🔥 
> [python] Drop support for Python 3.7

- scripts/bld
When building TileDB-SOMA in Docker on Mac, this was manifesting as an error like:
```
Building Release build
CMake Error: The source directory "/TileDB-SOMA/+" does not exist.
Specify --help for usage, or press the help button on the CMake GUI.
```
when `scripts/bld` called `cmake`, because `extra_opts` had a stray `+` sign.
I was working around it with:
```bash
export DOCKER_DEFAULT_PLATFORM=linux/amd64
```
which is generally useful, but then I noticed this typo/bug.
> fix `scripts/bld` typo (`aarch64` opts)

- apis/r/R/SOMADataFrame.R
See #2197 for context and the Python example:  multiple calls to evolve an array schema can have side effects.
**Changes:**
On write, one call is now made (as needed) which is similar to what the update process already did. 
[SC 42531](https://app.shortcut.com/tiledb-inc/story/42531/r-fix-race-in-somadataframe-schema-with-multiple-enumerated-columns)
> [r] Call array schema evolution after loop setting up enums

- apis/python/src/tiledbsoma/_dataframe.py
I don't know how this got into `main` without failing pre-merge but here we go:
https://github.com/single-cell-data/TileDB-SOMA/actions/runs/8158687565/job/22301179196
To make this PR I simply ran `alias pav='python -m pre_commit run -a -v'` on `main`, after `git pull` and before making a PR branch.
No GitHub issue here, as this is a drive-by fix.
> [python] Fix a lint fail on `main`

- .github/workflows/python-so-copying.yml
- scripts/update-tiledb-version.py
**Issue and/or context:** Found on drive-by while debugging https://github.com/TileDB-Inc/tiledbsoma-feedstock/pull/95
**Changes:** Now that we have one more hard-coded path (#1937), have the updater not fail to update it
> [ci] Updated hard-coded core version in another file

- .github/workflows/python-so-copying.yml
* Follow up to #1937 
* Linked Issue: #2210
**Changes:**
Expands SO copying pipeline to include a macOS job
I have good news and bad news. The good news is that I added a macOS job, and its behavior is correct! The bad news of course is that this means it doesn't explain the feedstock failures where the macOS builds fail to find the shared objects.
I suspect this is because the feedstock is still using the older `setup.py` with the flag `--libtiledbsoma` ([script](https://github.com/TileDB-Inc/tiledbsoma-feedstock/blob/6e28425785020e98e088390bec528a13eeea2dc6/recipe/build-tiledbsoma-py.sh#L8)). This was required pre-#1937. However, now that #1937 has been merged, we can now upgrade to the more modern alternative:
```sh
export …
```
> [ci] Add MacOS job to test shared object copying

- scripts/bld
Sibling of #2216 and #2217
See also https://github.com/single-cell-data/TileDB-SOMA/issues/2219 for tracking
> Append `LD_LIBRARY_PATH` for census

- .github/workflows/python-so-copying.yml
- apis/python/setup.py
* Closes #2210
* Follow-up to #2220 
* Address broken feedstock builds in https://github.com/TileDB-Inc/tiledbsoma-feedstock/pull/91 and https://github.com/TileDB-Inc/tiledbsoma-feedstock/pull/95
**Changes:**
* Restores the flags `--tiledb` and `--libtiledbsoma` that are passed to `setup.py`
Here's what happened. PR #1937 fixed the shared object copying when an external libtiledb or libtiledbsoma is provided via the env vars `TILEDB_PATH` or `TILEDBSOMA_PATH`. Unfortunately, it broke the command-line flags `--tiledb` and `--libtiledbsoma`. It overwrites them with `None`. This is why the tiledbsoma-feedstock nightlies immediately started failing after it was merged, which is the only place where we still build tiledbsoma-py with `setup.py`. …
> [python] Fix and test `setup.py` flags to external shared objects

- .github/workflows/python-so-copying.yml
* Follow up to #1937, #2220, and #2221 
**Changes:**
* Only runs this CI workflow that tests the build steps if the PR/commit modifies a file that involves finding libtiledb and/or libtiledbsoma at build/run time
* These tests are quick, but we noticed that the recently added macOS builds are extremely flaky, often requiring a restart to succeed. It's unclear to me why the macOS builds are so less reliable than the Docker ones
* For the Python package, I included both `setup.py` (finds libtiledbsoma at build time) and `src/tiledbsoma/__init__.py` (finds libtiledbsoma at runtime)
> [ci] Only run build tests when build files are modified

- README.md
- apis/python/setup.py
- apis/python/src/tiledbsoma/_common_nd_array.py
- apis/python/src/tiledbsoma/_sparse_nd_array.py
- apis/python/tests/__init__.py
Re: the first commit, https://github.com/single-cell-data/TileDB-SOMA/commit/9870a3fe7baf016c192519b773edf85194478d6a:
- [3rd paragraph of README](https://github.com/single-cell-data/TileDB-SOMA?tab=readme-ov-file#tiledb-soma) ("Get started…") links to `#quick-start`, which doesn't exist.
- Relevant section appears to be [APIs Installation and Quick Start](https://github.com/single-cell-data/TileDB-SOMA?tab=readme-ov-file#apis-installation-and-quick-start) a.k.a. `#apis-installation-and-quick-start`.
- Rather than "hard-code" that, I appended an empty anchor tag with a canonical `id` (`#quick-start`) to the end of the &lt;h2&gt; line. I've used this technique in the past and found it preferable / never had problems, but can use Github's default auto-generated dash-cased version if that is …
> Typo fixes, broken README link

- apis/r/tools/r-ci.sh
The `covr()` function of the eponymous package has an argument `quiet` defaulting to TRUE; our attempt to set it to FALSE was thwarted by the fact that we accidentally included in the other, preceding argument.
**Changes:**
Move one character a few places in both parts of the if/else call.
[SC 42849](https://app.shortcut.com/tiledb-inc/story/42849/r-correct-misplaced-parenthesis-in-coverage-call-in-r-ci-sh)
> [r] Correct parenthesis in covr() call activate quiet=FALSE

- apis/python/tests/test_sparse_nd_array.py
#1791 
Add a test case to `test_sparse_nd_array_table_slicing`, verifying that `pa.ChunkedArray` (of integers) and `pa.IntegerArray` work as `SparseNDCoord`s.
Ideally we'd have a repro where:
- Type checker fails when `pa.ChunkedArray` passed to `SparseNDArray.read` (before any changes to `SparseNDCoord` [in somacore](https://github.com/single-cell-data/SOMA/blob/76b2d2bbca7c8baf543b5cc9cf71fc5c9138a39a/python-spec/src/somacore/options.py#L172-L179); see https://github.com/single-cell-data/SOMA/pull/187).
- Same checks succeed when `pa.ChunkedArray` is added to `SparseNDCoord`.
The existing test I've modified here apparently isn't subjected to such runtime type-checking. A more explicit version in https://github.com/single-cell-data/TileDB-SOMA/commit/0d93315e34d86549524959ba5fec98f7818779 …
> [python] Verify `pa.{Chunked,Integer}Array` args to `SparseNDArray.read`

- .github/workflows/python-ci-minimal.yml
- apis/python/tests/test_io.py
- profiler/src/profiler/data.py
- profiler/src/profiler/profiler.py
**Issue and/or context:** https://github.com/single-cell-data/TileDB-SOMA/issues/2238#issuecomment-1989020356
Tracking issue: #2248
3.10 was removed from the CI matrix, but the lint/codecov conditions were not updated, inadvertently removing those checks from pre-merge CI.
> Restore pre-merge lint checks

- .github/workflows/r-ci.yml
- apis/r/DESCRIPTION
- apis/r/tools/install_missing_deps.R
Force binary-only installation for macOS. By setting as an option in `~/.Rprofile`; this should affect both package installation and updating through `utils::install.packages()`, `utils::update.packages()`, and `remotes::install_deps()`
resolves #2254
> [r/ci] Set `options(pkgType = "binary")` for MacOS

- apis/python/src/tiledbsoma/_query_condition.py
**Issue and/or context:** #2185
**Changes:** 
* Remove types from the Python ast package that were deprecated in Python 3.8.
> Remove deprecated Python 3.7  ast types

- .github/workflows/r-ci.yml
See comments in the affected CI YAML file.
> [r/ci] Point at correct TileDB-R location

- .github/workflows/python-packaging.yml
As surfaced in the nightly smoke test for wheel-install:
https://github.com/single-cell-data/TileDB-SOMA/actions/runs/8294234646/job/22699837592
Follow-on/completion from #2267
> [python/ci] Complete 3.8 -> 3.11 work

- apis/python/src/tiledbsoma/io/ingest.py
**Issue and/or context:** This is from a non-GitHub bug report.
**Changes:** Avoid division by zero on entirely empty chunks.
**Notes for Reviewer:** I tried to create synthetic data that would trigger the corner case, but failed to repro. Had I succeeded, I'd have created a new unit-test case on this PR. As is, I was only able to repro with some larger data I'm not willing to check in. Regardless, the change has been tested successfully against that dataset, and furthermore, it's a clear and solid code mod.
> [python] Fix an ingestion corner case with empty chunks

- apis/python/tests/test_registration_mappings.py
**Issue and/or context:** Issue #2242
**Changes:** This is some factoring to help simplify #2281, which will be rebased on top of this PR.
> [python] Neaten registration-mapping test code

- apis/python/src/tiledbsoma/io/_registration/ambient_label_mappings.py
- apis/python/src/tiledbsoma/io/_registration/signatures.py
- apis/python/src/tiledbsoma/io/_util.py
- apis/python/src/tiledbsoma/io/ingest.py
**Issue and/or context:** This will allow us to use append mode with multiple `.h5ad` files stored on S3.
**Changes:** Extract the fs-wrapper function to a util location, and call it everywhere we were using `anndata.read_h5ad` before.
> [python] Extract fs wrapper to util file

- .github/workflows/python-ci-single.yml
- .github/workflows/r-python-interop-testing.yml
- apis/python/requirements_dev.txt
- apis/python/setup.py
- apis/python/src/tiledbsoma/_collection.py
- apis/python/src/tiledbsoma/_dataframe.py
- apis/python/src/tiledbsoma/_dense_nd_array.py
- apis/python/src/tiledbsoma/_factory.py
- apis/python/src/tiledbsoma/_funcs.py
- apis/python/src/tiledbsoma/_index_util.py
- apis/python/src/tiledbsoma/_query_condition.py
- apis/python/src/tiledbsoma/_read_iters.py
- apis/python/src/tiledbsoma/_tdb_handles.py
- apis/python/src/tiledbsoma/_tiledb_array.py
- apis/python/src/tiledbsoma/_tiledb_object.py
- apis/python/src/tiledbsoma/_util.py
- apis/python/src/tiledbsoma/io/_util.py
- apis/python/src/tiledbsoma/io/ingest.py
- apis/python/src/tiledbsoma/options/_tiledb_create_options.py
- apis/python/tests/__init__.py
- apis/python/tests/_util.py
- apis/python/tests/test_collection.py
- apis/python/tests/test_dataframe.py
- apis/python/tests/test_dense_nd_array.py
- apis/python/tests/test_experiment_query.py
- apis/python/tests/test_metadata.py
- apis/python/tests/test_registration_mappings.py
- apis/python/tests/test_sparse_nd_array.py
- apis/python/tests/test_tiledbobject.py
Some post-1.6.0 housekeeping.
We've been seeing literally hundreds of `pytest` warnings per CI run, which is frictional to sort through on CI fails.
Regarding the dominant error which is `no type annotations present -- not typechecking {}'.format(function_name(func))` I could not easily find any _where_ location. (Maddening.) But by comment-out bisection on `tiledbsoma.io` I found `_create_and_open_coll` and `_create_and_open_collection` (and `@overload` variants), the _existence_ of which on a typeguarded import results in these warnings.
I found https://github.com/agronholm/typeguard/issues/108 and in particular https://github.com/agronholm/typeguard/issues/108#issuecomment-1379547357 indicating that this is a fault of older typeguard versions.
Meanwhile thanks to yours truly on …
> [python] Fix many `typeguard` warnings

- .github/workflows/r-ci.yml
- .github/workflows/r-python-interop-testing.yml
**Issue and/or context:** Applies the same pattern on the `release-1.8` branch as #1972 did for the `release-1.5` branch, #1996 did for the `release-1.6` branch, and #2157 did for the `release-1.7` branch.
Standard procedure:
https://github.com/single-cell-data/TileDB-SOMA/wiki/Branches-and-releases#incrementing-core-versions
[sc-43172]
**Changes:** As on #1972, #1996, and #2157. This is necessary since [TileDB-R 0.25.0](https://tiledb-inc.r-universe.dev/tiledb) now exists, and the R `DESCRIPTION` file does not syntactically support `tiledb < 0.25` or `tiledb <= 0.25`. Therefore (see also this comment https://github.com/single-cell-data/TileDB-SOMA/pull/1996#issuecomment-1881702859) we do a controlled downgrade to TileDB-R 0.24 on this PR, for the `release-1.8` branch.
**Notes for …
> [r/ci] Controlled downgrade for TileDB-R 0.24

- apis/python/src/tiledbsoma/_tdb_handles.py
- apis/python/src/tiledbsoma/_tiledb_object.py
- apis/python/src/tiledbsoma/_types.py
- apis/python/src/tiledbsoma/io/ingest.py
- apis/python/tests/test_basic_anndata_io.py
- apis/python/tests/test_metadata.py
**Issue and/or context:** #2252 
TODO:
> [python] Let ingest accept `additional_metadata: dict[str, Metadatum]`

- .github/workflows/python-ci-single.yml
- .github/workflows/r-python-interop-testing.yml
- apis/python/requirements_dev.txt
- apis/python/setup.py
- apis/python/src/tiledbsoma/_collection.py
- apis/python/src/tiledbsoma/_dataframe.py
- apis/python/src/tiledbsoma/_dense_nd_array.py
- apis/python/src/tiledbsoma/_factory.py
- apis/python/src/tiledbsoma/_funcs.py
- apis/python/src/tiledbsoma/_index_util.py
- apis/python/src/tiledbsoma/_query_condition.py
- apis/python/src/tiledbsoma/_read_iters.py
- apis/python/src/tiledbsoma/_tdb_handles.py
- apis/python/src/tiledbsoma/_tiledb_array.py
- apis/python/src/tiledbsoma/_tiledb_object.py
- apis/python/src/tiledbsoma/_util.py
- apis/python/src/tiledbsoma/io/_util.py
- apis/python/src/tiledbsoma/io/ingest.py
- apis/python/src/tiledbsoma/options/_tiledb_create_options.py
- apis/python/tests/__init__.py
- apis/python/tests/_util.py
- apis/python/tests/test_collection.py
- apis/python/tests/test_dataframe.py
- apis/python/tests/test_dense_nd_array.py
- apis/python/tests/test_experiment_query.py
- apis/python/tests/test_metadata.py
- apis/python/tests/test_sparse_nd_array.py
- apis/python/tests/test_tiledbobject.py
Backport #1960 to the `release.1.8` branch
> [Backport release-1.8] [python] Fix many `typeguard` warnings

- apis/python/src/tiledbsoma/_read_iters.py
- apis/python/src/tiledbsoma/_util.py
- apis/python/tests/_util.py
- apis/python/tests/conftest.py
- apis/python/tests/test_basic_anndata_io.py
- apis/python/tests/test_experiment_query.py
- apis/python/tests/test_io.py
- apis/python/tests/test_notebook_sparse_dense.py
- apis/python/tests/test_platform_config.py
- apis/python/tests/test_registration_mappings.py
- apis/python/tests/test_registration_signatures.py
- apis/python/tests/test_update_dataframes.py
- apis/python/tests/test_update_matrix.py
**Issue and/or context:** #1988
**Changes:**
- Add test to verify #1988
- Factor `pytest.fixture`s, misc test cleanup
- Test cleanups can be factored out to another PR, if desired.
- I verified that the new test, [`test_empty_categorical_query`](https://github.com/single-cell-data/TileDB-SOMA/pull/2299/commits/6dbb9a0084a03f4b3c390fb51b226b966adb6909#diff-356b52ccf7c4b2025a8d80701d49afb9ee699e70f42e5e54f3357a8cbb29bba3R910), raises `ArrowInvalid` with TileDB 2.20.1, but passes here with 2.21.0.
> Factor `pytest.fixture`s, verify #1988

- apis/python/src/tiledbsoma/io/_registration/ambient_label_mappings.py
- apis/python/src/tiledbsoma/io/_registration/signatures.py
- apis/python/src/tiledbsoma/io/_util.py
- apis/python/src/tiledbsoma/io/ingest.py
- apis/python/tests/__init__.py
**Issue and/or context:** follow-on changes to #2290
**Changes:** simplify calling new `read_h5ad` helper by using `@contextmanager`/`yield` pattern
- ~I could only get this to type-check using `typeguard>=3` (per https://github.com/agronholm/typeguard/issues/115#issuecomment-987188701), so this includes a minimal version of #1960 (and fixes #1116). It might make more sense to merge #1960 separately, then put this and #2290 on top of that.~ **Update:** #1960 is merged, this is rebased on it.
- I modified `_FSPathWrapper` to subclass from `pathlib.Path`, also to resolve type-checking issues; that's probably more accurate anyway, it's meant to quack like a `Path`.
> Make `_util.read_h5ad` a `@contextmanager`

- apis/python/tests/test_experiment_query.py
**Issue and/or context:** #2299, #1988, #2307
Test now verifies that:
- TileDB<2.21 ⟹ `ArrowInvalid` raised
- TileDB>=2.21 ⟹ `[]` returned
> Make `test_empty_categorical_query` work with TileDB<2.21

- .github/workflows/python-ci-single.yml
- .github/workflows/r-python-interop-testing.yml
- apis/python/requirements_dev.txt
- apis/python/setup.py
typeguard 4.2.0 and 4.2.1 were just released, raise errors on main. Pin to 4.1.5 for now.
Issue: #2312
> [python/ci] Pin `typeguard==4.1.5`

- apis/r/tests/testthat/test-SOMAExperiment-query.R
Add a tests for doing value filters on enums in `SOMAExperimentAxisQuery`; test for levels both present and missing. Skip missing level tests for core < 2.21
addresses #1988 
[sc-43700]
> [r] Add tests for enum value filters in `SOMAExperimentAxisQuery `

- libtiledbsoma/src/soma/managed_query.cc
Closes #2319
See #2319 for discussion
**Changes:**
The use of `std::future::wait()` is replaced by `std::future::get()`.
[SC 43721](https://app.shortcut.com/tiledb-inc/story/43721/asynchronous-functions-should-use-get-not-wait-so-that-errors-from-core-propagate)
> [c++] Use `std::future::get()` instead of `::wait()`

- .github/workflows/python-ci-minimal.yml
- apis/python/tests/test_dataframe.py
- libtiledbsoma/src/utils/arrow_adapter.cc
- libtiledbsoma/src/utils/arrow_adapter.h
**Issue and/or context:** Details on #2306 
Checker from #2306:
```
import tiledbsoma as soma
sdf = soma.open('test_dataframe')
print(sdf.schema)
```
Output after this PR:
```
soma_joinid: int64 not null
int_cat: dictionary<values=int64, indices=int8, ordered=0> not null
int: int64 not null
str_cat: dictionary<values=string, indices=int8, ordered=0> not null
str: large_string not null
byte_cat: dictionary<values=binary, indices=int8, ordered=0> not null
byte: large_binary not null
```
**Changes:** Report binary appropriately
**Notes for Reviewer:** Failing CI
> [c++] Fix display of Arrow schema for enum of `bytes` datatype

- apis/r/DESCRIPTION
> [r] Bump `DESCRIPTION` version for `main` past 1.9

- .github/workflows/python-ci-single.yml
- .github/workflows/r-python-interop-testing.yml
- apis/python/requirements_dev.txt
- apis/python/setup.py
- apis/python/src/tiledbsoma/_collection.py
- apis/python/src/tiledbsoma/_factory.py
- apis/python/src/tiledbsoma/options/_soma_tiledb_context.py
**Issue and/or context:** #2312
**Changes:**
- use requirements_dev.txt in CI, setup.py: https://github.com/single-cell-data/TileDB-SOMA/commit/c47fa2a03b97c2b1550956f114556953374c5020
- use typeguard>=4.2, fixup some type checks: https://github.com/single-cell-data/TileDB-SOMA/pull/2314/commits/74c530b77c0b630b1540b9a662ebc4b20eb83733
`requirements_dev.txt` seemed to be unused. I:
- populated `requirements_dev.txt` with the actual `[dev]` reqs from `setup.py` (plus a few that were only listed in CIs: `pytest-cov`, `sparse`)
- made `setup.py` use the new reqs file
- made CIs install `-e apis/python[dev]` (they were previously installing sans `[dev]`, and pre-installing a few select dev reqs)
Previously the typeguard pin existed in 4 places, for no good reason …
> [python/ci] `typeguard==4.2.1`, make `requirements_dev.txt` canonical

- .github/workflows/python-ci-single.yml
- .github/workflows/r-python-interop-testing.yml
- apis/python/requirements_dev.txt
- apis/python/setup.py
- apis/python/src/tiledbsoma/_collection.py
- apis/python/src/tiledbsoma/_factory.py
- apis/python/src/tiledbsoma/options/_soma_tiledb_context.py
- apis/python/tests/test_experiment_query.py
Backport #2314 to the `release-1.8` branch
> [Backport release-1.8] [python/ci] `typeguard==4.2.1`, make `requirements_dev.txt` canonical

- apis/python/MANIFEST.in
- apis/python/setup.py
**Issue and/or context:** Attempt on #2337
**Changes:** per @nguyenv 
> [python/ci] Unbreak wheel builds

- apis/python/MANIFEST.in
Ports #2339 (which was on the `release-1.9` branch) to `main`
#2311
[sc-43673]
> [python/ci] Unbreak wheel builds, `main`

- apis/r/DESCRIPTION
- apis/r/NEWS.md
We need a 1.9.1 for our upcoming Python-only 1.9.1
#2311
[sc-43673]
> [r] tiledbsoma-r 1.9.1

- apis/python/src/tiledbsoma/__init__.py
- apis/python/src/tiledbsoma/_indexer.py
**Issue and/or context:** #2343
**Changes:** 
Restore function `tiledbsoma_build_index`. Deprecate instead of removing.
> Add back deprecated function `tiledbsoma_build_index`

- apis/python/tests/__init__.py
**Issue and/or context:** https://github.com/single-cell-data/TileDB-SOMA/pull/1960#discussion_r1528881351, #2293
**Update:**
- The underlying segfault still exists: #2293; occurs on macOS when `tiledb` is imported before `tiledbsoma`
- #2299 made it harder to trigger while unit-testing, because it made `conftest.py` import `tiledbsoma` very early during test initialization ([here](https://github.com/single-cell-data/TileDB-SOMA/pull/2299/files#diff-23e074510ec289097bb974f8ee8a2e0c94dfd3f8056d69fc83dc4739c382c4e1R6))
- It's probably safe/reasonable to remove the `_query_condition` import, as this PR does, since it is no longer helping us work around Typeguard issues or the segfault.
<details><summary>Previous description</summary>
If a `from tiledbsoma import _query_condition` is omitted …
> [python] Remove no-longer-necessary `_query_condition` import

- apis/r/DESCRIPTION
- apis/r/NEWS.md
- apis/r/R/SOMAExperimentAxisQuery.R
- apis/r/man/SOMAExperimentAxisQuery.Rd
- apis/r/tests/testthat/test-SOMAExperiment-query-m-p.R
Add support for querying `*m` and `*p` layers from `SOMAExperimentAxisQuery`; note, just like `$X()`, these methods only support layers stored as `SOMASparseNDArrays`
Implemented SOMA methods:
- `SOMAExperimentAxisQuery$obsm()`: read an `obsm` layer for only the coordinates in the query
- `SOMAExperimentAxisQuery$varm()`: read a `varm` layer for only the coordinates in the query
- `SOMAExperimentAxisQuery$obsp()`: read an `obsp` layer for only the coordinates in the query
- `SOMAExperimentAxisQuery$varp()`: read a `varp` layer for only the coordinates in the query
resolves #1997
> [r] Add `obsm`, `varm`, `obsp`, and `varp` to `SOMAExperimentAxisQuery`

- apis/r/DESCRIPTION
- apis/r/NEWS.md
- apis/r/R/SOMAExperimentAxisQuery.R
- apis/r/man/SOMAExperimentAxisQuery.Rd
- apis/r/tests/testthat/test-SOMAExperiment-query-m-p.R
Manual backport of #2351 per https://github.com/single-cell-data/TileDB-SOMA/pull/2351#issuecomment-2033273608 -- I don't know why the backport bot didn't run
> [Backport release-1.9] [r] Add `obsm`, `varm`, `obsp`, and `varp` to `SOMAExperimentAxisQuery`

- .github/workflows/r-ci.yml
- .github/workflows/r-python-interop-testing.yml
**Issue and/or context:** Applies the same pattern on the `release-1.9` branch as #1972 did for the `release-1.5` branch, #1996 did for the `release-1.6` branch, #2157 did for the `release-1.7` branch, and #2295 did for the `release-1.8` branch.
Standard procedure:
https://github.com/single-cell-data/TileDB-SOMA/wiki/Branches-and-releases#incrementing-core-versions
**Changes:** As on #1972, #1996, #2157, and #2295. This is necessary since [TileDB-R 0.26.0](https://tiledb-inc.r-universe.dev/tiledb) will soon exist, and the R language's `DESCRIPTION` file does not syntactically support `tiledb < 0.26` or `tiledb <= 0.26`. Therefore (see also this comment https://github.com/single-cell-data/TileDB-SOMA/pull/1996#issuecomment-1881702859) we do a controlled downgrade to TileDB-R 0.25 on this …
> [r/ci] Controlled downgrade for TileDB-R 0.25

- apis/python/tests/test_basic_anndata_io.py
**Issue and/or context:** [sc-43541](https://app.shortcut.com/tiledb-inc/story/43541/failed-to-convert-buffer-for-attribute-on-ingest), extends #2357
**Changes:** sweep over more configurations when testing AnnData appends with empty columns:
- not all values `nan`
- not all `obs` IDs duplicated between initial and appended AnnData
Per offline discussion with @aaronwolen and @johnkerl.
> [python] More `nan_append` checks: not-all-NaN, non-dupe IDs

- apis/python/src/tiledbsoma/io/_registration/id_mappings.py
- apis/python/tests/test_registration_mappings.py
**Issue and/or context:** When non-unique values are present in `obs` or `var` then append-mode ingest, if it uses that non-uniquely-valued field name as registration inputs, will fail at ingestion time with
```
Error: Duplicate coordinates (1413) are not allowed
```
This problem happens during the data write.
**Changes:**
The error should be surfaced earlier, at registration time:
* Before the write has begun
* WIth a more informative error message
* 
> [python] Check for uniqueness of registration obs/var field-name inputs

- apis/python/src/tiledbsoma/io/_registration/ambient_label_mappings.py
- apis/python/tests/test_registration_mappings.py
There are two use-cases for registration:
* The SOMA Experiment does not exist, and there are one or more `AnnData` objects to be registered and then ingested.
* This user intent is signaled by passing `experiment_uri=None` to the registrar
* The SOMA Experiment does exist, and there are one or more `AnnData` objects to be co-registered with the existing experiment, and then the `AnnData` objects are to be ingested
* This user intent is signaled by passing a non-empty `experiment_uri` to the registrar
Due to an unforunate implementation bug (in the code touched by this PR) these two use-cases were getting conflated.
**Changes:**
* Raise an exception if the `experiment_uri` passed to the registrar is not `None`. This is a non-breaking change, since the existing …
> [python] Enforce if-not-exists semantics for append/registration

- libtiledbsoma/src/external/src/nanoarrow/nanoarrow.c
#2393
**Changes:**
`nanoarrow.c` mods were passing all regular per-commit CI but were failing wheel builds which are done nightly, and at release time.
Compile error appearing in wheel builds:
```
/project/tiledbsoma-1.5.0rc0.post284.dev1878736499/dist_links/libtiledbsoma/src/utils/nanoarrow.c:1775:28: error: null destination pointer [-Werror=format-truncation=]
1775 |     n_chars_last = snprintf(out, n, ">");
|                    ~~~~~~~~^~~~~~~~~~~~~
```
This unblocks my attempt to tag 1.9.4.
Validation: I manually ran https://github.com/single-cell-data/TileDB-SOMA/actions/runs/8572181618/job/23494196523 with PR #2390 which is essentially this PR.
> [r/ci] Unbreak wheel builds

- libtiledbsoma/src/utils/arrow_adapter.cc
When running under `valgrind` (by for example calling an R script or expression and starting as `R -q -d valgrind`) and with the proper `memcheck` instrumentation for chasing leaks, we were reminded that we lost a small fixed amoumt of 248 bytes per column retrieved.  This was due to allocating the (opaque) `private_data` by default and then (as we do here for buffer management) store the ArrowBuffer / ColumnBuffer container handle.  
**Changes:**
By freeing the default allocation before assigning, we no longer leak.  We also removed another small assignment (and helper function used) taken care of now by `nanoarrow` following #2188.
[SC 44774](https://app.shortcut.com/tiledb-inc/story/44774/c-squash-final-valgrind-leak)
> [c++] Address final `valgrind` issue

- apis/python/src/tiledbsoma/soma_array.cc
- libtiledbsoma/src/soma/soma_array.cc
- libtiledbsoma/src/soma/soma_array.h
- libtiledbsoma/src/soma/soma_collection.cc
- libtiledbsoma/src/soma/soma_collection.h
- libtiledbsoma/src/soma/soma_dataframe.cc
- libtiledbsoma/src/soma/soma_dataframe.h
- libtiledbsoma/src/soma/soma_dense_ndarray.cc
- libtiledbsoma/src/soma/soma_dense_ndarray.h
- libtiledbsoma/src/soma/soma_experiment.cc
- libtiledbsoma/src/soma/soma_experiment.h
- libtiledbsoma/src/soma/soma_group.cc
- libtiledbsoma/src/soma/soma_group.h
- libtiledbsoma/src/soma/soma_measurement.cc
- libtiledbsoma/src/soma/soma_measurement.h
- libtiledbsoma/src/soma/soma_object.h
- libtiledbsoma/src/soma/soma_sparse_ndarray.cc
- libtiledbsoma/src/soma/soma_sparse_ndarray.h
- libtiledbsoma/src/utils/common.h
- libtiledbsoma/test/unit_soma_array.cc
- libtiledbsoma/test/unit_soma_collection.cc
- libtiledbsoma/test/unit_soma_dataframe.cc
- libtiledbsoma/test/unit_soma_dense_ndarray.cc
- libtiledbsoma/test/unit_soma_group.cc
- libtiledbsoma/test/unit_soma_sparse_ndarray.cc
#2182 
I am refactoring the create and metadata methods in C++ after I noticed issues while working on transitioning the Python `SOMADataFrame` write path to use `clib.DataFrame`.
**Changes:**
* Store read-mode `Array` or `Group` that holds metadata values valid as a class memeber
```
// Metadata values need to be accessible in write mode as well. When adding
// or deleting values in the array, instead of closing to update to
// metadata; then reopening to read the array; and again reopening to
// restore the array back to write mode, we just store the modifications to
// this cache
std::map<std::string, MetadataValue> metadata_;
// Array associated with metadata_. We need to keep this read-mode array
// alive in order for the metadata value pointers in the cache …
```
> [c++] Refactor `metadata` and `create` to respect timestamps

- apis/r/R/Init.R
closes #1837 
Issue #1837 proposed a check to ensure library versions of TileDB Core as used by the TileDB R package and the TileDB SOMA package match, and to error if not 
**Changes:**
A check has been added
[SC 43169](https://app.shortcut.com/tiledb-inc/story/43169/r-py-check-at-package-startup-and-load-and-warn-or-even-die-if-two-different-core-libraries-are-seen)
[SC 44807](https://app.shortcut.com/tiledb-inc/story/44807/r-error-on-mismatched-core-libraries)
> [r] Check that TileDB Core library versions match

- .github/workflows/python-so-copying.yml
Closes #2237
We have a flaky macOS job that fails too often. Sometimes the macOS System Integrity Protection (SIP) unsets `DYLD_LIBRARY_PATH`, which prevents `libtiledbsoma.dylib` from finding `libtiledb.dylib`
**Changes:**
There is no way to disable SIP during a run. Fortunately the GitHub Actions runner `macos-13` has it disabled by default, so I switched to it. If SIP is enabled in the future, then we'll have to revisit.
I added a step to run `csrutil status`, which will help us troubleshoot in the future if SIP is enabled
So far this has passed twice on my fork
https://github.com/jdblischak/TileDB-SOMA/actions/runs/8652010719/job/23723973384
https://github.com/jdblischak/TileDB-SOMA/actions/runs/8652049846/job/23724080889
> Run SO copying workflow on macos-13 to avoid SIP

- .github/workflows/python-so-copying.yml
- apis/python/src/tiledbsoma/__init__.py
- apis/python/src/tiledbsoma/_collection.py
- apis/python/src/tiledbsoma/_common_nd_array.py
- apis/python/src/tiledbsoma/_dataframe.py
- apis/python/src/tiledbsoma/_exception.py
- apis/python/src/tiledbsoma/io/ingest.py
**Issue and/or context:** #2433
**Changes:** As narrated on #2433. The only additional details is that to balance the `DoesNotExistError` for `open`, we need a completely analogous `AlreadyExistsError` for `create`.
**Notes for Reviewer:** There is a bit more performance improvement to be made, but it needs to be done in core; I will track that work separately. Also, as this is for Python; I'll track the R work -- both a needs-analysis, and any possible (maybe no) dev work -- separately.
> [python] Ingestion performance
